# -*- coding: utf-8 -*-
"""aday_ekle_27_21_30.py — blok 27:21-30 adayları (800-810) ve bağları."""
import json

ADAYLAR = [
{"no":800,
 "aday":"27:21 KORPUSUN EN YÜKSEK TEKİT YOĞUNLUĞU. n=9'luk ayette EMPH 6 → oran 0,67. Aynı orana ulaşan iki ayet daha var (29:11 ve 7:6, ikisi de 4/6); **mutlak tekit sayısında 27:21 hepsinden yüksek.** Mutlak en yüksek EMPH 4:119'da (12) ama oran 0,57.",
 "olculen":{"ayet":"27:21","n":9,"EMPH":6,"oran":0.67,"korpus_esdeger":["29:11 (4/6)","7:6 (4/6)"],"mutlak_en_yuksek":"4:119 (12/21, oran 0,57)"},
 "durum":"KAPALI","oncelik":"P2","kaynak":"okuma blok 27:21-30",
 "etiket":"ararken bulundu (tam korpus sayımı koşuldu)",
 "test_notu":"Tam korpus sayımı koşuldu; kip alanı çalışan alan (aday 722 dersi karşılanıyor). Oran ölçütü n>=6 ayetlerde anlamlı; n<6 ayetlerde payda küçüklüğü nedeniyle hesaplanmadı."},
{"no":801,
 "aday":"DÜŞEN KAYIT — 27:21'İN 'SÛRENİN EN UZUN AYETİ (n=61)' KAYDI YANLIŞ. Kapanış notu (2026-09-04) devam noktasında 27:21'i sûrenin en uzun ayeti ve n=61 olarak kaydetmişti. **Ölçülen n=9.** Sûrenin en uzun ayetleri: 27:40 (n=38) · 27:44 (n=28) · 27:60 (n=27) · 27:19 (n=24) · 27:61 (n=21). Kayıt, sıralı listedeki (n=21, ayet=61) ikilisinin ters okunmasından gelmiş.",
 "olculen":{"iddia":"27:21 n=61, sûrenin en uzunu","olculen_n":9,"gercek_en_uzun":[["27:40",38],["27:44",28],["27:60",27],["27:19",24],["27:61",21]],"hata_mekanizmasi":"(n, ayet) ikilisinin ters okunması"},
 "durum":"KAPALI","oncelik":"P1","kaynak":"okuma blok 27:21-30",
 "etiket":"okuma sırasında ölçüldü",
 "test_notu":"**Kayıt sessizce değiştirilmedi, düşürüldüğü belgelendi.** Ders: oturum kapanış notlarındaki sayısal beklentiler bloğa girmeden önce defterden doğrulanacak. Bu, aday 780'in (dört sûrelik aralıktan hipotez) not tarafı: **not alma sırasında da ölçüm ile hafıza karışabiliyor.**"},
{"no":802,
 "aday":"ADSIZ AKTÖR 'imrae' ALANININ TAM KORPUS DENETİMİ — 11 TOKENİN 7'Sİ HATALI (%63,6). Alan kök düzeyinde eşleşiyor; مرأ kökü üç lemma taşıyor ve üçü de tek etikete iniyor. DOĞRU 4: 4:12 · 4:128 · 27:23 · 33:50 (lemma امْرَأَت, dişil, gerçek kişi). ERİL 6: 4:176 (امْرُؤٌا) · 24:11 · 52:21 · 70:38 · 74:52 · 80:37 (امْرِئ) — 'adam' dişil etiketle işaretlenmiş. KİŞİ DEĞİL 1: 4:4 (مَّرِيٓـًٔا, sıfat: 'afiyetli').",
 "olculen":{"toplam_token":11,"dogru":4,"eril_ters":6,"kisi_degil":1,"hata_orani":0.636,
   "dogru_ayetler":["4:12","4:128","27:23","33:50"],
   "eril_ayetler":["4:176","24:11","52:21","70:38","74:52","80:37"],
   "kisi_degil_ayetler":["4:4"],
   "lemmalar":{"امْرَأَت":4,"امْرِئ":5,"امْرُؤٌا":1,"مَرِيئ":1}},
 "durum":"ACIK","oncelik":"P0","kaynak":"okuma blok 27:21-30",
 "etiket":"ararken bulundu (denetim istendi, tam sayıma genişletildi)",
 "test_notu":"**Aday 765'in (dört alanın ortak lemma+bağlam eksiği) aktör ayağı için ilk TAM SAYIMLI vaka.** Önceki vakalar tekildi: نُفُورا→nefer (462/579), فِرْقٍ→ferîk (641). **Ve yeni bir hata sınıfı: CİNSİYET TERSİNMESİ** — sözcük kişi ama karşı cinsiyet; 11 tokenin 6'sı. Onarım: kök eşleşmesi yerine lemma eşleşmesi yeterli (üç lemma zaten ayrı), bağlam denetimi gerekmiyor. **Bu alan, dört alan içinde en ucuz onarılanı.** Daha önce bildirilen '%67 hata' tahmini doğrulandı (%63,6)."},
{"no":803,
 "aday":"مُبِين ESMÂ ARTEFAKTI SÛRE 27'DE DÖRT/DÖRT — KAPATILAMAZ. Sûrenin altı مُبِين tokeninden okunan dördü de artefakt: 27:1 gönderge كِتاب · 27:13 gönderge سِحْر · 27:16 gönderge فَضْل · 27:21 gönderge سُلْطان. Dördünde de gönderge ilâhî değil; dördünde de fâsıla konumunda; dördü de mühürsüz.",
 "olculen":{"sure_toplam_token":6,"okunan":4,"artefakt":4,"okunmayan":["27:75","27:79"],
   "gondergeler":{"27:1":"كِتاب","27:13":"سِحْر","27:16":"فَضْل","27:21":"سُلْطان"}},
 "durum":"ACIK","oncelik":"P0","kaynak":"okuma blok 27:21-30",
 "etiket":"okuma sırasında ölçüldü",
 "test_notu":"**KAPATILAMAZ — 27:75 ve 27:79 okunmadı** (ders 774). Sûre 26'da مُؤْمِن 15/15 artefakttı (682/709); burada مُبِين 4/4. **İki sûre, iki ayrı lemma, aynı desen: fâsıla konumundaki sıfat-esmâ lemması gönderge denetimi olmadan token üretiyor.** Esmâ gönderge sınıfları envanterine (aday 747) 'yapı/nesne niteliği' sınıfı için beş vaka birikti."},
{"no":804,
 "aday":"SÛRE 27'DE AZINLIK KAFİYESİ م İLE MÜHÜR TAM ÖRTÜŞÜYOR. 93 ayetin 84'ü ن, 9'u م fâsılalı. **Altı mühür ayetinin ALTISI da م fâsılalı** (27:6, 9, 11, 30, 40, 78). Kalan üç م ayeti mühürsüz ve ÜÇÜ DE bu blokta: 27:23 (عَظِيم) · 27:26 (ٱلْعَظِيم) · 27:29 (كَرِيم). Dokuz م fâsılasının dokuzu da فَعِيل vezninde.",
 "olculen":{"sure":27,"ayet":93,"nun":84,"mim":9,"muhur":6,"muhur_mim":6,
   "mim_ayetler":[6,9,11,23,26,29,30,40,78],
   "mim_muhursuz":[23,26,29],"vezin":"hepsi فَعِيل"},
 "durum":"ACIK","oncelik":"P1","kaynak":"okuma blok 27:21-30",
 "etiket":"ararken bulundu (tam sûre sayımı koşuldu)",
 "test_notu":"**Kafiye tarafı KAPALI: fs alanı çalışan alan, tam sayım koşuldu (9/9, 6/6).** **Mühür tarafı KAPATILAMAZ: 27:40 ve 27:78 okunmadı, mühür geçerliliği okuma denetiminden geçmedi** (esmâ tablosu güvenilmez, aday 444/461). ÖN-KAYIT: sûre sonuna kadar okuduğumuzda 27:40 ve 27:78'in mühürleri GEÇERLİ çıkacak; gerekçe okunan dört mührün dördünün de geçerli çıkmış olması. **Bu ön-kayıt ÇALIŞAN alan (fs) üzerine değil, EKSİK alan (esma_k) üzerine kuruluyor — aday 722'nin dersi gereği ZAYIF etiketiyle kaydedildi.** Sonraki sûrelerde sınanacak genelleme: 'azınlık fâsıla harfi esmâ mührüne ayrılır' — sûre 26'da fâsıla neredeyse tekdüzeydi, sınama için uygun değil."},
{"no":805,
 "aday":"27:23 ↔ 27:26 — عَرْش + عَظِيم ÇİFTİ, BELİRSİZDEN BELİRLİYE. 27:23 عَرْشٌ عَظِيمٌ (belirsiz, kraliçenin tahtı, fâsıla) · 27:26 ٱلْعَرْشِ ٱلْعَظِيمِ (belirli, Rabbin arşı, fâsıla). Aynı iki kök, aynı sıra, aynı fâsıla konumu, üç ayet arayla. **`esit` alanı İKİSİNDE DE BOŞ.**",
 "olculen":{"ayetler":["27:23","27:26"],"ortak_kokler":["عرش","عظم"],"mesafe":3,
   "belirlilik":["INDEF","DEF"],"fasila_konumu":True,"esit_alani":[[],[]],
   "sure_ici_arş_ayetleri":[23,26,38,41,42]},
 "durum":"ACIK","oncelik":"P0","kaynak":"okuma blok 27:21-30",
 "etiket":"okuma sırasında ölçüldü",
 "test_notu":"**`esit`in yedi eşik türünden 'esit_yapi (iskelet)' türü için temiz sınama vakası** — mevcut sınama kümesindeki 26:90≈26:91 ve 26:64·66·172 üçlüsüne ek. Bu vakanın farkı: **kelime örtüşmesi iki kökle sınırlı ama belirlilik karşıtlığı anlamlı ve fâsıla konumu ortak.** Eşik tanımı yazılırken 'ortak kök sayısı' tek başına yetmiyor; 'fâsıla konumunda ortak' bir alt ölçüt adayı. NOT: sûre içi عرش beş ayette (23, 26, 38, 41, 42); üçü okunmadı, dizi KAPATILAMAZ."},
{"no":806,
 "aday":"DİKEY KATMANDA YÜKSEK KAT, HEDEF KÖKÜN DEĞİL ORTAK KÖKÜN SEYREKLİĞİNDEN GELİYOR — MEVCUT KORUMA YANLIŞ DEĞİŞKENDE. Kural 'n<=25 köklerin yüksek katları güvenilmez' diyor ve hedef kökün n'sine bakıyor. Bu blokta n'si yüksek üç kök yine de çok yüksek kat verdi: عظم (n=128) ▸ مضغ ×69,8 · سجد (n=92) ▸ شطر ×43,3 · مرأ (n=38) ▸ عقر ×177,0. Ölçüldü: ortak kökün korpus sıklığı ve kaç AYRI ayetten geldiği belirleyici.",
 "olculen":{"vakalar":[
   {"hedef":"عظم","n_hedef":128,"ortak":"مضغ","n_ortak":3,"komsulukta":2,"ayri_ayet":1,"kaynak_ayet":["23:14"],"kat":69.8},
   {"hedef":"سجد","n_hedef":92,"ortak":"شطر","n_ortak":5,"komsulukta":3,"ayri_ayet":3,"kaynak_ayet":["2:144","2:149","2:150"],"kat":43.3,"not":"üç ayet ama tek sahne (kıble bölütü)"},
   {"hedef":"مرأ","n_hedef":38,"ortak":"عقر","n_ortak":8,"komsulukta":3,"ayri_ayet":3,"kaynak_ayet":["3:40","19:5","19:8"],"kat":177.0},
   {"hedef":"عرش","n_hedef":33,"ortak":"ستت","n_ortak":8,"komsulukta":6,"ayri_ayet":6,"kat":145.0},
   {"hedef":"شمس","n_hedef":33,"ortak":"قمر","n_ortak":27,"komsulukta":21,"ayri_ayet":21,"kat":129.3,"not":"YÜKSEK KAT AMA ARTEFAKT DEĞİL — çok sayıda ayrı ayetten"},
   {"hedef":"ذبح","n_hedef":9,"ortak":"حيي","n_ortak":189,"komsulukta":3,"ayri_ayet":3,"kat":232.7}],
  "ayirt_edici":"ortak kökün n'si ve katkı veren AYRI AYET sayısı"},
 "durum":"ACIK","oncelik":"P0","kaynak":"okuma blok 27:21-30",
 "etiket":"okuma sırasında ölçüldü (dikey satır denetlenirken)",
 "test_notu":"**P0 #2'nin ('aynı sahne' alanı) işlevsel tanımı buradan çıkıyor: alan hedef kökün n'sini değil, KATKI VEREN AYRI AYET SAYISINI saymalı.** شمس ▸ قمر ×129,3 yirmi bir ayrı ayetten geliyor ve gerçek bir birliktelik; عظم ▸ مضغ ×69,8 TEK ayetten (23:14) geliyor ve artefakt. **İkisi de mevcut n<=25 korumasının dışında kalıyor — koruma yanlış değişkeni hedefliyor.** Bu, biçim ihlâli önleminin ('blok boyu ON') aynı hatasının ölçüm tarafındaki karşılığı: doğru sonucu yanlış değişkenle korumak. ÖNERİLEN EŞİK (ön-kayıt, TUR SONU'nda sınanacak): katkı veren ayrı ayet sayısı <=2 ise satır yorumlanmaz; 3-5 ise 'tek sahne' uyarısı; >5 ise serbest. Sûre 26'nın dokuz vakası ve sûre 27'nin üç vakası bu eşikle yeniden etiketlenecek."},
{"no":807,
 "aday":"27:24-25-26 — SÛRE 27'DE İLK KEZ ÜÇ ARDIŞIK AYETTE ALLAH LAFZI. Sûrenin ilk yirmi ayetinde üç lafız vardı ve üçü dağınıktı (27:8, 27:9, 27:15). Bu blokta dört lafız var ve üçü art arda (27:24, 25, 26). Okunan sûrelerde 3+ ardışık lafız dizisi 60 kez geçiyor ve hepsi on sûrede toplanıyor: 9, 10, 11, 12, 13, 14, 16, 18, 22, 24.",
 "olculen":{"dizi":[24,25,26],"sure_27_ilk_20_lafiz":[8,9,15],"blok_lafiz":[24,25,26,30],
   "okunan_sürelerde_3plus_dizi":60,
   "dizi_bulunan_sureler":[9,10,11,12,13,14,16,18,22,24],
   "dizi_bulunmayan_okunan_sureler":[1,15,17,19,20,21,23,25,26]},
 "durum":"ACIK","oncelik":"P1","kaynak":"okuma blok 27:21-30",
 "etiket":"ararken bulundu (okunan korpus taraması koşuldu)",
 "test_notu":"Dizi bulunan on sûrenin tamamı ya Medenî ya lafız-yoğun; 27 Mekkî ve A/R = 2,25. **Sûre 27, ardışık lafız dizisi veren ilk Mekkî-anlatı sûresi olabilir — ama bu KAPATILAMAZ: dizi taraması yalnız okunan sûrelerde koşuldu, korpusun tamamında değil.** TUR SONU: tüm korpusta 3+ ardışık lafız dizisi taranıp Mekkî/Medenî ve A/R ile çapraz kurulacak. Konum-eşli null gerektirir (aday 435)."},
{"no":808,
 "aday":"سمو KÖKÜ TEK BLOKTA İKİ ANLAM ALANINDA — 529 KÜMESİNİN BLOK İÇİ VAKASI. 27:25'te ٱلسَّمَٰوَٰت (gökler), 27:30'da ٱسْم (ad); beş ayet arayla, aynı blokta, aynı kök. Kök sözlüğünde iki anlam zaten yazılı ('ad; gök') ama dikey katman ikisini tek satırda topluyor ve iki ayetin سمو satırı BİRBİRİNİN AYNISI.",
 "olculen":{"kok":"سمو","n":381,"ayetler":["27:25","27:30"],"anlamlar":["gökler","ad"],
   "lemmalar":["سَماء","اسْم"],"dikey_satiri_ayni":True,"mesafe":5},
 "durum":"ACIK","oncelik":"P0","kaynak":"okuma blok 27:21-30",
 "etiket":"okuma sırasında ölçüldü",
 "test_notu":"**529'un üç katmanlı onarımında 'lemma' katmanının temiz vakası** — سَماء ve اسْم ayrı lemmalar, bağlam denetimine gerek yok. جنن·صلح·جبل kümesine dördüncü vaka. **Ve bu vaka, otomatik tespit ölçütünün ('iki anlam da dikey satırında görünüyor') SINIRINI gösteriyor: burada ölçüt ÇALIŞMIYOR** — dikey satır 'mühlet ×13,9 · كسف ×11,1 · kandil ×18,5' veriyor, hepsi gök anlamından; 'ad' anlamı satırda hiç görünmüyor çünkü ٱسْم geçişleri sayıca ezilmiş. **Ölçüt dört vakada 2/4 çalışmıştı (طلع, ذكر çalıştı; لسن, نظر çalışmadı); bu beşinci vaka ve ÇALIŞMADI → 2/5.** Hipotez güçleniyor: ikinci anlamın korpus sıklığı belirleyici."},
{"no":809,
 "aday":"ÇIPA/YILDIZ TERS İLİŞKİSİ — SÛRE 27'DE İKİNCİ GÖSTERİM. 27:24 sûrenin okunan tek gök cismi ayeti (شمس, güneşe secde) → YILDIZSIZ. 27:25 hiçbir gök cismi anmıyor, bir süreç ve bir alan adlandırıyor → ★★★ ve kaynağı yalnız hapaks (خبأ). Birinci gösterim 27:16-20 bölütüydü (aday 799).",
 "olculen":{"tablo":[
   {"ayet":"27:24","icerik":"güneş (gök cismi) + secde yönü","cipa":"adlandırma","yildiz":0},
   {"ayet":"27:25","icerik":"gizli olanın çıkarılması + gökler/yer","cipa":"adlandırma+alan","yildiz":3,"kaynak":"hapaks"},
   {"ayet":"27:26","icerik":"arş","cipa":"adlandırma","yildiz":2,"kaynak":"eksen"},
   {"ayet":"27:29","icerik":"mektup","cipa":"yok","yildiz":2,"kaynak":"pas"}]},
 "durum":"ACIK","oncelik":"P0","kaynak":"okuma blok 27:21-30",
 "etiket":"okuma sırasında ölçüldü",
 "test_notu":"Aday 599/602/799 kümesine. **İki bağımsız bölütte aynı desen: sûre 27'de yıldız kaynakları hapaks, edilgenlik ve eksen; içerik hiçbirinde kaynak değil.** TUR SONU: çıpa tanımı yazıldıktan sonra 26 ve 27 için çıpa/yıldız korelasyonu birlikte hesaplanacak (aday 781'in kontrollü çifti). Aday 602'nin korpus taraması (r=-0,367) nakarat düzeltmeli yeniden koşulacak."},
{"no":810,
 "aday":"BLOK 27:21-30 BİLANÇOSU. Yıldız: ★★★ 1 (27:25) · ★★ 2 (27:26, 27:29) · ★ 2 (27:23, 27:30) · yıldızsız 5. Kaynaklar: hapaks 1 · pas 2 · eksen 2 — içerikten sıfır. İltifât 0/10. Esmâ token 3 (2 artefakt, 1 geçerli mühür). Allah lafzı 4 (27:24, 25, 26, 30) · Rab 1 (27:26). Adlı aktör 3 (سَبَإ, شَيْطان, سُلَيْمان) · adsız aktör 1 (imrae, DOĞRU). Yeni kök 2 (سبأ, خبأ). Hapaks 1 (خبأ). Kafiye kırılması 0.",
 "olculen":{"blok":"27:21-30","ayet":10,
   "yildiz":{"3":1,"2":2,"1":2,"0":5},
   "yildiz_kaynak":{"hapaks":1,"pas":2,"eksen":2,"icerik":0},
   "iltifat":0,"esma_token":3,"esma_artefakt":2,"muhur":1,
   "allah_lafzi":4,"rab":1,"adli_aktor":3,"adsiz_aktor":1,
   "yeni_kok":2,"hapaks":1,"kafiye_kirilmasi":0,
   "mim_fasila":4,"ort_n":10.7},
 "durum":"KAPALI","oncelik":"P2","kaynak":"okuma blok 27:21-30",
 "etiket":"okuma sırasında ölçüldü",
 "test_notu":"Sûre 27 ilk otuz ayet toplamı: ★★★ 4 · ★★ 3 · ★ 2 · yıldızsız 21. Esmâ token 15, geçerli mühür 4, artefakt 5. Allah lafzı 6 · Rab 3 → A/R = 2,00 (makro 2,25; ilk otuz ayet biraz aşağıda). İltifât 1/30 (27:6)."},
]

BAGLAR = [
 {"bag":"27:22 ↔ 34:15","kural":"L1","not":"سبأ *(Sebe (yer/kavim adı))* korpusta iki geçişli; ikincisi kendi adını taşıyan sûrede. Okumada ilk kez bir yer adı sonraki bir sûrenin adını önceden veriyor (aday 800 bloğu)."},
 {"bag":"27:23 ↔ 27:26","kural":"L1","not":"**عَرْش + عَظِيم çifti, belirsizden belirliye, üç ayet arayla, ikisi de fâsıla konumunda; `esit` alanı ikisinde de boş (aday 805).**"},
 {"bag":"27:23 ↔ 18:84 · 27:16","kural":"L2","not":"xref آتى + كلّ + شىء — 'her şeyden verilme' kalıbı; 27:16'da Süleymân'a, burada kraliçeye. **Sûre içi ve sûre dışı aynı kalıp.**"},
 {"bag":"27:24 ↔ 29:38 · 40:37","kural":"L2","not":"xref عمل + صدّ + سبيل ve شيطان + عمل + صدّ; 'şeytanın amelleri süslemesi + yoldan çevirmesi' donmuş kalıp adayı."},
 {"bag":"27:25 ↔ 14:38 · 60:1","kural":"L1","not":"خفي *(gizleme, gizli olan)* ile علن *(açığa vurma, alenî)* korpusta üç ayette birlikte; üçünde de aynı ikili yapı."},
 {"bag":"27:26 ↔ 9:129 · 23:86 · 23:116","kural":"L2","not":"xref ربّ + عرش + عظيم (9:129, 23:86) ve إله + ربّ + عرش (23:116); üç bağ, ikisi sûre 23'te."},
 {"bag":"27:27 ↔ 27:28","kural":"L1","not":"نظر *(bakma; mühlet verme)* iki ardışık ayette: سَنَنظُرُ (Süleymân'ın bakışı) → فَٱنظُرْ (hüdhüde emir). Aynı kök, aynı bab, özneden nesneye."},
 {"bag":"27:28 ↔ 27:29","kural":"L1","not":"لقي *(karşılaşma, kavuşma; atma)* iki ardışık ayette çatı değiştiriyor: فَأَلْقِهْ (emir, Süleymân) → أُلْقِىَ (edilgen, kraliçe). **İki ağız, iki çatı, tek kök.**"},
 {"bag":"27:29 ↔ 27:32 · 27:38 · 28:38","kural":"L2","not":"xref قال + أيّ + ملأ; üç bağın ikisi sûre içi, üçüncüsü Firavun'un ağzında."},
 {"bag":"27:30 ↔ 1:1","kural":"L1","not":"**Tam besmele korpusta 114 kez sûre başında ve ayet içinde YALNIZ 27:30'da.** Kısa biçim بِسْمِ ٱللَّهِ ayrıca 11:41'de. رَحْمٰن *(Rahmân)* sûre 27'nin tek tokeni burada (aday 803/804)."},
]

pa = '/home/claude/repo/bulgular/aday_bulgular.json'
AD = json.load(open(pa, encoding='utf-8'))
AD['AH_neml'].extend(ADAYLAR)
json.dump(AD, open(pa, 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
print('aday_bulgular: AH_neml →', len(AD['AH_neml']), '| son no', AD['AH_neml'][-1]['no'])

pb = '/home/claude/repo/notlar/okuma_baglantilari.json'
BG = json.load(open(pb, encoding='utf-8'))
BG['AG_neml'].extend(BAGLAR)
json.dump(BG, open(pb, 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
print('okuma_baglantilari: AG_neml →', len(BG['AG_neml']))
