# -*- coding: utf-8 -*-
"""aday_ekle_27_31_40.py — blok 27:31-40 adayları (811-821) ve bağları."""
import json

ADAYLAR = [
{"no":811,
 "aday":"27:31 — İLTİFÂT BİR ALINTI METNİN İÇİNDE. 27:30 mektubu üçüncü şahısla açıyor (إِنَّهُۥ مِن سُلَيْمَٰنَ), 27:31 birinci-ikinci şahsa geçiyor; alan bunu ilt=1, yön 3>12 diye kaydediyor. Sûrenin ikinci iltifâtı (birincisi 27:6, anlatı kipinde).",
 "olculen":{"ayet":"27:31","ilt":1,"yon":"3>12","sure_iltifat_ayetleri":["27:6","27:31","27:69"],
   "fark":"27:6 anlatı katmanında, 27:31 alıntı katmanının sınırında"},
 "durum":"ACIK","oncelik":"P1","kaynak":"okuma blok 27:31-40",
 "etiket":"okuma sırasında ölçüldü",
 "test_notu":"**İltifât alanının bilinen eksiği ad→zamir geçişleri (aday 461/517); bu vaka farklı bir tür ve alan onu YAKALADI.** TUR SONU: iltifât vakaları 'anlatı içi' / 'alıntı sınırında' / 'alıntı içi' diye sınıflandırılacak; sınıf dağılımı bilinmeden iltifât sayımları karşılaştırılamaz. Sûre 26'nın 15 iltifâtı (nakarat düzeltmeli ≤11) bu sınıflandırmadan geçmedi."},
{"no":812,
 "aday":"27:34 ↔ 27:37 — ذلل İKİ AĞIZDA, AYNI KALIPTA. 27:34'te kraliçe kralların yaptığını anlatıyor: أَعِزَّةَ أَهْلِهَآ أَذِلَّةً. 27:37'de Süleymân tehdit ediyor: وَلَنُخْرِجَنَّهُم مِّنْهَآ أَذِلَّةً. Aynı kök, aynı kalıp (أَذِلَّة), üç ayet arayla. **Kraliçenin kralların yapacağını söylediği şey, cevabında ona söyleniyor.** 27:34 ayrıca عزز/ذلل karşıt çiftini tek cümlede taşıyor.",
 "olculen":{"ayetler":["27:34","27:37"],"kok":"ذلل","n":24,"kalip":"أَذِلَّة","mesafe":3,
   "agiz":["kraliçe","Süleymân"],"karsit_cift_ayeti":"27:34","karsit":["عزز","ذلل"]},
 "durum":"ACIK","oncelik":"P1","kaynak":"okuma blok 27:31-40",
 "etiket":"okuma sırasında ölçüldü",
 "test_notu":"26:16↔26:18 ve 26:42↔26:58 sınıfından, ama bu kez **iki ayrı KONUŞMACI arasında**. `esit` alanının hiçbir eşiğine takılmıyor (kelime örtüşmesi tek). **'Konuşmacı-arası kalıp yankısı' `esit`in sekizinci eşik türü adayı** — mevcut yedi türün hiçbiri konuşmacı bilgisini kullanmıyor."},
{"no":813,
 "aday":"27:33 — 2FS KORPUSTA SEYREK VE 27:33 EN ÜSTTE. 2FS işareti korpusun 6236 ayetinden yalnız 30'unda (%0,48). 27:33'te DÖRT işaret — en yüksek dördüncü değer (28:7 ve 19:26 dokuzla başta, 3:43 yediyle, 12:29 altıyla). Sûre 27'de üç 2FS ayeti var (27:33, 27:42, 27:44) ve üçü de aynı kişiye.",
 "olculen":{"korpus_2fs_ayet":30,"oran":0.0048,"27:33":4,"sira":"ortak 7.",
   "en_yuksek":[["28:7",9],["19:26",9],["3:43",7],["12:29",6]],
   "sure_27_2fs":[["27:33",4],["27:44",2],["27:42",1]]},
 "durum":"KAPALI","oncelik":"P2","kaynak":"okuma blok 27:31-40",
 "etiket":"ararken bulundu (tam korpus sayımı koşuldu)",
 "test_notu":"`sah` çalışan alan; tam sayım koşuldu. **Sûre 27, tek bir kadın muhataba yönelen üç ayet taşıyan tek Mekkî anlatı sûresi olabilir — KAPATILAMAZ, korpus çapında muhatap sürekliliği taraması koşulmadı.** 2FS'nin dağılımı 'anlatıda kadın muhatap' ölçüsü için ham veri; kavram alanına bağlanmadı."},
{"no":814,
 "aday":"هدي KÖKÜ SÛRE 27'DE İKİ ANLAM ALANINDA — 529 KÜMESİNE İKİNCİ SÛRE İÇİ VAKA. 27:24'te ٱهْتَدَى (yol bulma), 27:35 ve 27:36'da هَدِيَّة (hediye). Aynı kök, on bir ayet arayla. Dikey satırı YALNIZ 'yol gösterme' anlamından geliyor (صرط ×13,7 · furkan ×10,6 · yol ×8,2); 'hediye' anlamı satırda hiç görünmüyor.",
 "olculen":{"kok":"هدي","n":316,"ayetler":["27:24","27:35","27:36"],
   "anlamlar":["yol bulma","hediye"],"dikey_satiri_ayni":True,
   "otomatik_olcut_calisti":False},
 "durum":"ACIK","oncelik":"P0","kaynak":"okuma blok 27:31-40",
 "etiket":"okuma sırasında ölçüldü",
 "test_notu":"**Otomatik tespit ölçütü ('iki anlam da dikey satırında görünüyor') ALTINCI vakada da çalışmadı → 2/6.** Çalışan: طلع, ذكر. Çalışmayan: لسن, نظر, سمو (aday 808), هدي. **Hipotez artık desteklenmiş sayılabilir: ikinci anlamın korpus sıklığı belirleyici; azınlık anlamı ezildiğinde ölçüt kör.** TUR SONU: ölçüt terk edilip lemma katmanına geçilecek — هدي'de هُدَى/هَدِيَّة ayrı lemmalar, bağlam denetimi gerekmiyor."},
{"no":815,
 "aday":"عرش SÛRE 27'DE ÜÇÜNCÜ KİPTE — ADAY 805'İN ÇİFTİNE ÜÇÜNCÜ ÜYE. 27:23 عَرْشٌ عَظِيمٌ (belirsiz, kraliçenin) · 27:26 ٱلْعَرْشِ ٱلْعَظِيمِ (belirli, Rabbin) · 27:38 بِعَرْشِهَا (iyelikli, kraliçenin). Üç ayet, üç belirlilik kipi.",
 "olculen":{"kok":"عرش","n":33,"sure_ici_ayetler":[23,26,38,41,42],
   "okunan":[23,26,38],"kipler":["INDEF","DEF","POSS"],
   "fasila_konumu":[True,True,False]},
 "durum":"ACIK","oncelik":"P1","kaynak":"okuma blok 27:31-40",
 "etiket":"okuma sırasında ölçüldü",
 "test_notu":"**Aday 805'in 'fâsıla konumunda ortak' alt ölçütünü sınıyor ve ayırıyor: 27:38 fâsıla konumunda DEĞİL** ve yapısal benzerlik belirgin biçimde daha zayıf. Bu, alt ölçütün ayırt edici olduğuna ilk veri. **KAPATILAMAZ — 27:41 ve 27:42 okunmadı** (ders 774)."},
{"no":816,
 "aday":"27:39 — ESMÂ ALANINDA YENİ GÖNDERGE SINIFI: GAYB VARLIĞI, BİRİNCİ ŞAHIS. قَوِيّ tokeninin göndergesi bir CİN (ifrît) ve cin KENDİ HAKKINDA konuşuyor: إِنِّى عَلَيْهِ لَقَوِىٌّ أَمِينٌ. Şimdiye kadar sayılan gönderge sınıfları: ilâhî / insan (tekil ve çoğul) / nesne / soyut kavram / yapı. **Gayb varlığının kendini nitelemesi yeni.**",
 "olculen":{"ayet":"27:39","esma":"قَوِيّ","konum":15,"n":16,"muhur":False,
   "gonderge":"عِفْرِيت (cin)","sahis":"birinci","artefakt":True,
   "sinif_envanteri":["ilâhî","insan tekil","insan çoğul","nesne","soyut kavram","yapı","GAYB VARLIĞI 1. şahıs (YENİ)"]},
 "durum":"ACIK","oncelik":"P0","kaynak":"okuma blok 27:31-40",
 "etiket":"okuma sırasında ölçüldü",
 "test_notu":"**Aday 747'nin gönderge sınıfları envanterine yedinci sınıf.** Bu sınıf için hüküm açık (artefakt) ama **onarım kuralı zor: gönderge bir zamir ve merci cümle başındaki özne** — lemma denetimi yetmez, bağlam denetimi gerekir. **Aday 765'in dört alanı içinde esmânın en pahalı onarılanı olduğuna ek kanıt.** 27:34'ün iki 'çoğul insan' tokeniyle birlikte blokta üç artefakt, üç ayrı sınıf."},
{"no":817,
 "aday":"ADAY 804'ÜN ÖN-KAYDI SINANDI VE TUTTU — 27:40 MÜHRÜ GEÇERLİ. Ön-kayıt: 27:40 ve 27:78'in mühürleri geçerli çıkacak; gerekçe okunan dört mührün dördünün de geçerli olması. **27:40 okundu: غَنِيّ|كَرِيم, gönderge رَبّ + iyelik, GEÇERLİ.** Fâsıla harfi م — sûrenin dokuz م fâsılasından beşincisi ve altı mührün beşincisi.",
 "olculen":{"ayet":"27:40","cift":"غَنِيّ|كَرِيم","gonderge":"رَبّ + iyelik (Rabbim)","gecerli":True,
   "fasila_harfi":"م","muhur_sirasi":5,"farkli_cift_sirasi":5,
   "kalan_sinama":"27:78"},
 "durum":"ACIK","oncelik":"P1","kaynak":"okuma blok 27:31-40",
 "etiket":"ön-kayıt sınaması",
 "test_notu":"**Ön-kayıt EKSİK alan (esma_k geçerliliği) üzerine kurulmuştu ve ZAYIF etiketliydi; ilk gözlemde TUTTU.** Aday 722'nin desenine göre eksik alan üzerine kurulan tahminlerin düşmesi bekleniyordu; bu vaka desene UYMADI. **Tek gözlem; 27:78 okunmadan dizi KAPATILAMAZ.** Not: mühür bayrağı yapısal olarak hesaplanıyor (iki esmânın bitişikliği + son konum), yani ön-kayıt aslında yapısal bir bayrak ile okuma denetimi arasındaki örtüşmeyi sınıyor — aday 818'e bak."},
{"no":818,
 "aday":"SÛRE 27:1-40'TA MÜHÜR BAYRAĞI GÖNDERGE GEÇERLİLİĞİNİ KUSURSUZ AYIRIYOR. 23 esmâ tokeni: **10'u mühür tokeni (beş mühür) ve onunun onu da GEÇERLİ; 13'ü mühürsüz ve on üçünün on üçü de ARTEFAKT.** Mühürsüz tokenlerde geçerlilik oranı 0/13.",
 "olculen":{"aralik":"27:1-40","toplam_token":23,
   "muhur_token":10,"muhur_gecerli":10,
   "muhursuz_token":13,"muhursuz_gecerli":0,
   "muhur_ayetleri":[6,9,11,30,40],
   "muhursuz_ayetler":[1,2,3,4,5,13,15,16,21,29,34,34,39],
   "artefakt_sinif":{"nesne/yapı":["27:1","27:13","27:16","27:21","27:29"],
     "insan tekil":["27:2","27:15"],"zaman/yer":["27:3","27:4","27:5"],
     "insan çoğul":["27:34 مَلِك","27:34 عَزِيز"],"gayb 1. şahıs":["27:39"]}},
 "durum":"ACIK","oncelik":"P0","kaynak":"okuma blok 27:31-40",
 "etiket":"ararken bulundu (aralık içinde tam sayım koşuldu)",
 "test_notu":"**P0 (esmâ tablosu onarımı) için en güçlü tek veri: mühür bayrağı, tablonun yapamadığı gönderge denetimini bu bölütte kusursuz yapıyor.** AMA bayrak YAPISAL (iki esmânın bitişikliği + son konum); **tek başına gelen geçerli bir ilâhî ismi tanım gereği yakalayamaz.** ÖN-KAYIT: sûrenin kalan sekiz mühürsüz tokeni (27:49 وَلِيّ · 27:59 سَلام · 27:63 بَرّ · 27:66 آخِر · 27:75 مُبِين · 27:77 مُؤْمِن · 27:79 مُبِين · 27:88 خَبِير) içinde **en az biri GEÇERLİ çıkacak ve ayrım bozulacak**; gerekçe bayrağın yapısal olması, gönderge bilgisi taşımaması. **Bu ön-kayıt ÇALIŞAN alan (esma_k.muhur, yapısal hesap) üzerine kurulu ve bilinçli olarak AYRIMIN BOZULACAĞI yönünde** — tuttuğunda bayrağın yeterli değil ama gerekli olmadığı gösterilmiş olur."},
{"no":819,
 "aday":"DÜŞEN KAYIT — 27:19'UN 'OKUMADA İLK KEZ ÜÇ KÖK BİRDEN İKİLENİYOR' İDDİASI YANLIŞ. Aday 797 ve blok 27:11-20 metni 27:19'u (قول, نعم, صلح) 'okumada ilk kez üç kök' diye kaydetmişti. **Tam sayım: okunan sûrelerde 3+ farklı kökü ikilenen 107 ayet var; en yükseği 24:31 (ON BİR farklı kök, toplam 27 tekrar).** Korpus geneli rekoru 2:282 (on altı kök).",
 "olculen":{"iddia":"27:19 okumada ilk kez üç kök ikileniyor",
   "okunan_sürelerde_3plus":107,
   "okunan_rekor":{"ayet":"24:31","farkli_kok":11,"toplam":27},
   "korpus_rekor":{"ayet":"2:282","farkli_kok":16,"toplam":52},
   "27:19":3,"27:40":5,
   "sure_27_en_yuksek":{"ayet":"27:40","farkli_kok":5}},
 "durum":"KAPALI","oncelik":"P1","kaynak":"okuma blok 27:31-40",
 "etiket":"okuma sırasında ölçüldü (yeni kayıt eskiyi düşürdü)",
 "test_notu":"**Kayıt sessizce değiştirilmedi, düşürüldüğü belgelendi.** Doğru ifade: 27:40 SÛRE 27'nin en çok ikilenen ayeti (beş kök, biri üç kez); 27:19 sûrenin üçüncüsü. **Ders (aday 728'in kardeşi): 'okumada ilk kez' demeden önce okunan bölüt üzerinde tam sayım koşulmalı.** Aday 801 ile aynı sınıf: iki blok üst üste, kapanış/okuma notundaki bir sayısal iddia tam sayımla düştü."},
{"no":820,
 "aday":"SÜREÇ HATASI — TABAN DOSYASI KİRLETİLDİ VE ONARILDI. Blok 27:21-30 kapanışında `anahtar_denetim_raporu_tohum0.txt` yeniden yazılırken `kok_turkce.json` `betikler/` içinde UNUTULMUŞTU; taban başlığı 22976 anahtar olarak kaydedildi. Doğru sayı `kok_turkce.json` dışarıdayken 21910 (o an) idi.",
 "olculen":{"kirli_taban":22976,"kok_turkce_katkisi":1066,
   "dogru_taban_blok_27_21_30_sonrasi":21910,
   "dogru_taban_blok_27_31_40_sonrasi":21977,
   "ihlal":58,"ihlal_listesi_degisti":False},
 "durum":"KAPALI","oncelik":"P1","kaynak":"okuma blok 27:31-40",
 "etiket":"okuma sırasında ölçüldü (kendi hatam)",
 "test_notu":"**İhlâl listesi hiç değişmedi (58, birebir); yalnız başlıktaki anahtar sayısı şişmişti.** Onarıldı: taban `kok_turkce.json` `betikler/` dışındayken yeniden yazıldı → 21977 / 58, tam diff = 0. **YENİ KURAL: taban dosyası yalnızca `kok_turkce.json` `betikler/` dışındayken yazılır; `turkce_denetim.py` koşulduktan sonra dosya HEMEN silinir.** Bu, 2026-09-09'un 'bir denetimin ne taradığı sonucundan önce bilinmeli' dersinin ikinci vakası — bu kez fazla taranıyordu, az değil."},
{"no":821,
 "aday":"BLOK 27:31-40 BİLANÇOSU. Yıldız: ★★★ 1 (27:39) · ★★ 1 (27:40) · ★ 0 · yıldızsız 8. Kaynaklar: hapaks 1 · uzunluk (n z) 1 — içerikten sıfır. İltifât 1/10. Esmâ token 5: üçü artefakt (27:34 x2, 27:39), ikisi geçerli mühür (27:40). Allah lafzı 1 · Rab 2 (ikisi de 27:40'ta). Adlı aktör 1 · adsız aktör 0. Yeni kök 2 (صغر, عفر). Hapaks 1. Kafiye kırılması 0.",
 "olculen":{"blok":"27:31-40","ayet":10,
   "yildiz":{"3":1,"2":1,"1":0,"0":8},
   "yildiz_kaynak":{"hapaks":1,"uzunluk":1,"icerik":0},
   "iltifat":1,"esma_token":5,"esma_artefakt":3,"muhur":1,
   "allah_lafzi":1,"rab":2,"adli_aktor":1,"adsiz_aktor":0,
   "yeni_kok":2,"hapaks":1,"kafiye_kirilmasi":0,"mim_fasila":1,"ort_n":14.3},
 "durum":"KAPALI","oncelik":"P2","kaynak":"okuma blok 27:31-40",
 "etiket":"okuma sırasında ölçüldü",
 "test_notu":"Sûre 27 ilk kırk ayet toplamı: ★★★ 5 · ★★ 4 · ★ 2 · yıldızsız 29. Esmâ token 23 (13 artefakt, 10 geçerli mühür tokeni). Allah lafzı 7 · Rab 5 → A/R = 1,40 (makro 2,25; ilk kırk ayet belirgin biçimde aşağıda — **sûre içi eksen dalgalanması, aday 780'in konum-eşli null gereğine veri**). İltifât 2/40. **Blokta yıldızsız oran %80 — okumada görülen en düşük yıldız payı olabilir; KAPATILAMAZ, blok bazlı tam sayım koşulmadı.**"},
]

BAGLAR = [
 {"bag":"27:30 ↔ 27:31","kural":"L1","not":"**İltifât alıntı metnin içinde: 27:30 üçüncü şahısla açıyor, 27:31 birinci-ikinci şahsa geçiyor (ilt 3>12).** Sûrenin ikinci iltifâtı ve ilk kez alıntı sınırında (aday 811)."},
 {"bag":"27:31 ↔ 27:38","kural":"L1","not":"Fâsıla aynı kelime: مُسْلِمِينَ. Mektubun son sözü, yedi ayet sonra Süleymân'ın kendi cümlesinde geri dönüyor."},
 {"bag":"27:32 ↔ 12:43","kural":"L2","not":"xref أيّ + ملأ + يفتي — 'meclise danışma' formülü; 12:43'te Firavun'un rüyası bağlamında."},
 {"bag":"27:32 ↔ 27:38 · 28:38","kural":"L2","not":"xref قال + أيّ + ملأ; **sûre içinde üç kez (27:29, 27:32, 27:38) ve iki ayrı meclis**, dördüncüsü 28:38'de Firavun'un ağzında. Aynı hitap formülü üç hükümdarda (aday 815 bloğu)."},
 {"bag":"27:34 ↔ 27:37","kural":"L1","not":"**ذلل aynı kalıpta (أَذِلَّة) iki ayrı ağızda: kraliçe kralların yaptığını anlatıyor, Süleymân onu tehdit olarak kullanıyor.** `esit`in hiçbir eşiğine takılmıyor (aday 812)."},
 {"bag":"27:24 ↔ 27:35 · 27:36","kural":"L1","not":"هدي kökü iki anlam alanında: 27:24 ٱهْتَدَى *(yol buldu)*, 27:35-36 هَدِيَّة *(hediye)*. 529 kümesine sûre içi vaka; otomatik tespit ölçütü çalışmadı (aday 814)."},
 {"bag":"27:36 ↔ 11:31","kural":"L2","not":"xref آتى + اللّه + خير — 'Allah'ın verdiği daha hayırlıdır' kalıbı."},
 {"bag":"27:33 ↔ 27:39","kural":"L1","not":"قوي kökü iki geçiş ve **ikisi de KENDİ HAKKINDA güç iddiası**: danışmanlar (أُو۟لُوا۟ قُوَّةٍ), ifrît (لَقَوِىٌّ). İkisi de sonuçsuz kalıyor (aday 816)."},
 {"bag":"27:23 ↔ 27:26 ↔ 27:38","kural":"L1","not":"عرش üç belirlilik kipinde: belirsiz (27:23) → belirli (27:26) → iyelikli (27:38). Aday 805'in çiftine üçüncü üye; 27:38 fâsıla konumunda değil (aday 815)."},
 {"bag":"27:40 ↔ 31:12","kural":"L2","not":"xref şükür/nefis/nankörlük üçlüsü iki 3-gram ile tek ayete düşüyor: وَمَن شَكَرَ فَإِنَّمَا يَشْكُرُ لِنَفْسِهِۦ kalıbı 31:12'de birebir."},
 {"bag":"27:40 ↔ 6:148 · 13:43","kural":"L2","not":"xref قال + عند + علم ve عند + علم + كتاب; 'yanında kitaptan ilim' kalıbı."},
]

pa = '/home/claude/repo/bulgular/aday_bulgular.json'
AD = json.load(open(pa, encoding='utf-8'))
AD['AH_neml'].extend(ADAYLAR)
json.dump(AD, open(pa, 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
print('aday_bulgular: AH_neml →', len(AD['AH_neml']), '| son no', AD['AH_neml'][-1]['no'])

pb = '/home/claude/repo/notlar/okuma_baglantilari.json'
BG = json.load(open(pb, encoding='utf-8'))
BG['AG_neml'].extend(BAGLAR)
json.dump(BG, open(pb, 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
print('okuma_baglantilari: AG_neml →', len(BG['AG_neml']))
