# -*- coding: utf-8 -*-
"""aday_ekle_27_61_70.py — blok 27:61-70 adayları (843-853) ve bağları."""
import json

ADAYLAR = [
{"no":843,
 "aday":"DÜŞEN KAYIT — 27:51'DE 'نظر SÛREDE ALTINCI GEÇİŞ' YANLIŞTI, YEDİNCİ. Bir önceki blokta 27:51 mercek metni 27:27, 28, 33, 35, 41, 51 diye saymış ve **27:14'ü atlamıştı**. 27:14 de aynı kalıbı taşıyor (fânzur keyfe kâne âkıbetü'l-müfsidîn). Doğru sayım: sûrede sekiz geçiş (27:14, 27, 28, 33, 35, 41, 51, 69); 27:51 yedincisi.",
 "olculen":{"iddia":"27:51'de نظر altıncı geçiş","dogru":"yedinci",
   "sure_27_nazar_ayetleri":[14,27,28,33,35,41,51,69],"toplam":8,
   "atlanan":"27:14","onarildi":True,
   "onarim_yeri":["okuma_metni.json 27:51 mercek","mercek_kayit.json 27:51"]},
 "durum":"KAPALI","oncelik":"P1","kaynak":"okuma blok 27:61-70",
 "etiket":"okuma sırasında ölçüldü (kendi hatam)",
 "test_notu":"**Üçüncü blok içinde üçüncü sayım hatası** (aday 801: kapanış notundaki n=61; aday 819: '27:19 ilk kez üç kök'; burası). **Ortak mekanizma: sayımı okunan bloktan yapıp daha önceki blokları taramamak.** KURAL: bir kök/kalıp için 'sûrede kaçıncı geçiş' denecekse **sayım defterden tam koşulacak, hafızadan değil.** Metin sessizce değiştirilmedi; düzeltme notu ayetin mercek satırına gömüldü."},
{"no":844,
 "aday":"★ NAKARAT ALANININ MEKANİZMASI BULUNDU — ALAN AYET DÜZEYİNDE EŞLEŞİYOR, AYET-İÇİ NAKARATI GÖRMÜYOR. `أَءِلَٰهٌ مَّعَ ٱللَّهِ` ifadesi KORPUSUN TAMAMINDA yalnız beş ayette geçiyor ve beşi de ardışık: 27:60, 61, 62, 63, 64. Beşi de `أَمَّنْ` ile açılıyor. **`nakarat` alanı beşinde de SIFIR.** Buna karşılık sûre 26'da alan 34 ayette dolu — çünkü orada nakarat TAM AYET (26:8 'إنّ في ذلك لآية وما كان أكثرهم مؤمنين' bir bütün ayet olarak tekrar ediyor).",
 "olculen":{"ifade":"أَءِلَٰهٌ مَّعَ ٱللَّهِ","korpus_ayet_sayisi":5,
   "ayetler":[[27,60],[27,61],[27,62],[27,63],[27,64]],"ardisik":True,
   "acilis_kalibi":"emmen (أمن yazımlı soru kalıbı)","acilis_korpus":[[27,60],[27,61],[27,62],[27,63],[27,64],[38,28],[39,9],[67,20],[67,21]],
   "nakarat_alani_sure_27":0,"nakarat_alani_sure_26":34,
   "sure_26_nakarat_birimi":"tam ayet","sure_27_nakarat_birimi":"ayet-içi kalıp",
   "mekanizma":"alan yalnız ayet düzeyinde tekrarı eşliyor"},
 "durum":"ACIK","oncelik":"P0","kaynak":"okuma blok 27:61-70",
 "etiket":"okuma sırasında ölçüldü",
 "test_notu":"**P0 #4 (nakarat alanının yeniden tanımı) için aranan mekanizma bu.** Ve **aday 833'le aynı hata sınıfı: alan yanlış dilbilgisel birime bağlanmış.** Adsız aktör alanı 'adsız'ı 'belirsiz'le karıştırıyordu; nakarat alanı 'tekrar'ı 'ayet tekrarı'yla karıştırıyor. **İki P0 alanı, aynı tür arıza: doğru kavram, yanlış birim.** ONARIM: nakarat alanı n-gram düzeyinde çalışmalı (ayet-içi, sabit uzunlukta kalıp). **Ve bu, aday 700/739/771'in sûre 26 nakarat düzeltmesini de etkiliyor: orada sayılan 34 ayet YALNIZ ayet düzeyindekiler; sûre 26'da ayet-içi nakaratlar da varsa sayı eksik.**"},
{"no":845,
 "aday":"SÛRE 27'NİN İKİNCİ AYET-İÇİ NAKARATI: `كَيْفَ كَانَ عَٰقِبَةُ` ÜÇ KEZ. 27:14 (ٱلْمُفْسِدِينَ), 27:51 (مَكْرِهِمْ), 27:69 (ٱلْمُجْرِمِينَ). Korpusta yirmi bir ayette geçiyor. `nakarat` alanı üçünde de sıfır.",
 "olculen":{"kalip":"كَيْفَ كَانَ عَٰقِبَةُ","sure_27":[14,51,69],
   "korpus_ayet":21,"nakarat_alani":0,
   "degisen_oge":["el-müfsidîn","mekrihim","el-mücrimîn"],
   "sure_27_ayet_ici_nakaratlar":2},
 "durum":"ACIK","oncelik":"P0","kaynak":"okuma blok 27:61-70",
 "etiket":"okuma sırasında ölçüldü",
 "test_notu":"**Aday 844'e ikinci vaka ve bu kez DEĞİŞKEN SONLU bir kalıp** — sabit gövde + değişen tamlanan. Yani onarılmış nakarat alanının iki şeyi ayırt etmesi gerekiyor: **sabit kalıp** (أَءِلَٰهٌ مَّعَ ٱللَّهِ, birebir) ve **şablon kalıp** (كَيْفَ كَانَ عَٰقِبَةُ + X). Sûre 26'nın tam-ayet nakaratları birinci türden. **Üç tür nakarat: tam ayet · sabit ayet-içi kalıp · şablon kalıp.** TUR SONU: tanım üçünü de kapsamalı."},
{"no":846,
 "aday":"ADAY 818'İN ÖN-KAYDI ÜÇÜNCÜ VE DÖRDÜNCÜ KEZ SINANDI — 27:63 بَرّ VE 27:66 آخِر, İKİSİ DE ARTEFAKT. 27:63'te gönderge ٱلْبَرِّ وَٱلْبَحْرِ (kara ve deniz), bir yer/alan adı. 27:66'da gönderge ٱلْءَاخِرَة (âhiret), bir zaman/yer adı; sûrenin dört آخِر tokeninin dördüncüsü ve dördü de aynı gönderge. Ayrım: mühür tokeninde 10/10 geçerli, mühürsüz tokende 0/17.",
 "olculen":{"sinama_no":[3,4],"ayetler":["27:63","27:66"],
   "esma":["بَرّ","آخِر"],"gondergeler":["yer/alan adı","zaman/yer adı"],
   "gecerli":[False,False],
   "muhursuz_token_toplam":17,"muhursuz_gecerli":0,
   "muhur_token_toplam":10,"muhur_gecerli":10,
   "kalan_sinama":["27:75 مُبِين","27:77 مُؤْمِن","27:79 مُبِين","27:88 خَبِير"]},
 "durum":"ACIK","oncelik":"P0","kaynak":"okuma blok 27:61-70",
 "etiket":"ön-kayıt sınaması",
 "test_notu":"**Sekiz sınamanın dördü geçti, dördü kaldı; ayrım 27/27.** Ön-kayıt (en az biri geçerli çıkacak) hâlâ ayakta ama **kalan dört sınamadan üçü tekrar eden lemma** (مُبِين x2, مُؤْمِن) ve bu lemmaların sûredeki tüm geçişleri artefakt çıkmıştı. **Ön-kaydın kaderi büyük ölçüde 27:88 خَبِير'e bağlı.**"},
{"no":847,
 "aday":"27:63 — YILDIZ EŞİĞİNİN ALTINDA KALAN EN YÜKSEK EKSEN Z'Sİ: allah z=1,47. İki lafız (16. ve 18. sıra) ama n=20 olduğu için seyreliyor. Okunan ayetlerde yıldız veren en düşük z'ler 1,55 (27:60, n) ve 1,57 (27:23, pas); eşik 1,5 civarında.",
 "olculen":{"ayet":"27:63","n":20,"A":[16,18],"allah_z":1.47,"yildiz":0,
   "esik_tahmini":1.5,
   "esik_ustu_en_dusuk":[["27:60","n z",1.55],["27:23","pas z",1.57]],
   "karsilastirma":{"27:59":{"n":12,"lafiz":2,"allah_z":2.80,"yildiz":2},
     "27:63":{"n":20,"lafiz":2,"allah_z":1.47,"yildiz":0}}},
 "durum":"ACIK","oncelik":"P1","kaynak":"okuma blok 27:61-70",
 "etiket":"okuma sırasında ölçüldü",
 "test_notu":"**Aday 827/837'nin ÜÇÜNCÜ vakası ve en temizi: 27:59 ile 27:63 aynı eksen içeriğini taşıyor (iki lafız) ve tek fark n (12'ye 20); sonuç ★★ ile SIFIR.** Eşik 1,5 civarında olduğu için 27:63 kılpayı düşüyor. **Yıldız alanının eksen ölçümü uzunluğa aşırı duyarlı.** TUR SONU: eksen yoğunluğu hem ham hem normalize hesaplanıp hangisinin anlamlı olduğu sınanacak."},
{"no":848,
 "aday":"27:68 — PAS Z KORPUS TAVANINDA (5,38) VE TAVAN 124 AYETLE PAYLAŞILIYOR. Ayetin tek fiili var ve o da edilgen (وُعِدْنَا), oran 1/1 = 1,00. Yıldız ★★★ ve kaynağı YALNIZ edilgenlik. **Yani z burada bir sıralama değil, bir doygunluk noktası.**",
 "olculen":{"ayet":"27:68","n":12,"fiil":1,"edilgen":1,"oran":1.0,
   "pas_z":5.38,"korpus_tavani":5.38,"tavani_paylasan_ayet":124,
   "yildiz":3,"yildiz_kaynak":"pas",
   "blok_karsilastirma":{"doga_boluту_27:60-64":{"ayet":5,"toplam_yildiz":1},
     "27:68":{"ayet":1,"yildiz":3}}},
 "durum":"ACIK","oncelik":"P1","kaynak":"okuma blok 27:61-70",
 "etiket":"okuma sırasında ölçüldü",
 "test_notu":"**pas z tek fiilli ayetlerde otomatik tavana çıkıyor** — oran her zaman 0 ya da 1. **Yani ★★★'ların bir bölümü yalnızca 'ayette tek fiil var ve o edilgen' demek.** Korpusta 124 ayet bu durumda. TUR SONU: pas z'nin payda küçüklüğüne karşı düzeltilmesi gerekip gerekmediği sınanacak (n=1 paydalı oranlar için güven aralığı). **Ve içerik tarafı: doğa bölütünün beş ayeti toplam bir ★ alırken bir inkâr cümlesi ★★★ alıyor — aday 599/602'ye bu bloktan en keskin veri.**"},
{"no":849,
 "aday":"DOĞA BÖLÜTÜ (27:60-64) YILDIZ ÜRETMİYOR — ÇIPA TABLOSUNA BEŞİNCİ VE EN GENİŞ GÖSTERİM. Beş ayet: 27:60 ★ (kaynak uzunluk) · 27:61, 62, 63, 64 YILDIZSIZ. 27:61 sûrenin en 'yerbilimsel' ayeti (karar yeri, ırmaklar, sabit dağlar, iki deniz arasında engel — جعل dört kez) ve yıldızsız. Aynı blokta 27:68 (bir inkâr cümlesi) ★★★ alıyor.",
 "olculen":{"bolut":"27:60-64","ayet":5,
   "yildiz":[["27:60",1,"uzunluk"],["27:61",0,None],["27:62",0,None],["27:63",0,None],["27:64",0,None]],
   "27:61_icerik":["karar yeri","ırmaklar","sabit dağlar","iki deniz arasında engel"],
   "27:61_jaal_tekrari":4,
   "blok_tek_yildizli":"27:68 (★★★, kaynak pas)",
   "27:64_dis_dugum":7},
 "durum":"ACIK","oncelik":"P0","kaynak":"okuma blok 27:61-70",
 "etiket":"okuma sırasında ölçüldü",
 "test_notu":"**Aday 599/602/809/838 dizisine beşinci ve en geniş gösterim: artık tek ayet değil, BEŞ AYETLİK bir bölüt.** Sûre 27'nin doğaya ayrılmış tek bölütü ve toplam yıldız verimi bir ★, o da uzunluktan. **Ayrıca 27:64 sûrenin en çok dış bağı olan ayeti (dış düğüm 7) ve hiçbir yıldız kaynağı taşımıyor** — 'dış bağ yoğunluğu' ile 'yıldız' arasında da ilişki yok. TUR SONU: çıpa tanımı yazıldıktan sonra bu bölüt 26/27 korelasyonunun çekirdek verisi olacak."},
{"no":850,
 "aday":"ADAY 806/835'İN SINIRI — 'AYRI AYET SAYISI' DONMUŞ KALIBI ANLAMSAL BİRLİKTELİKTEN AYIRAMIYOR. Bu blokta iki örnek aynı sayıyı verdi ama farklı şeyler: سطر ▸ أول ×49,7 dokuz ayrı ayetten geliyor ama hepsi TEK donmuş ifade (أساطير الأوّلين); عمي ▸ صمم ×93,1 sekiz ayrı ayetten geliyor ve gerçek bir anlamsal birliktelik (körlük-sağırlık). Sayı neredeyse aynı, tür farklı.",
 "olculen":{"donmus_kalip":{"cift":["سطر","أول"],"ayri_ayet":9,"kat":49.7,"ifade":"أساطير الأوّلين"},
   "anlamsal_birliktelik":{"cift":["عمي","صمم"],"ayri_ayet":8,"kat":93.1},
   "blok_diger_olcumler":[
     {"cift":["هات","برهن"],"ayri_ayet":4,"kat":810.8,"tur":"donmuş kalıp (هاتوا برهانكم)","kaynak":["2:111","21:24","27:64","28:75"]},
     {"cift":["رسو","ميد"],"ayri_ayet":3,"kat":452.9,"tur":"donmuş kalıp","kaynak":["16:15","21:31","31:10"]},
     {"cift":["سير","مور"],"ayri_ayet":1,"kat":301.9,"tur":"tek ayet","kaynak":["52:9"]},
     {"cift":["ترب","نطف"],"ayri_ayet":4,"kat":103.4,"tur":"yaratılış dizisi kalıbı"}]},
 "durum":"ACIK","oncelik":"P0","kaynak":"okuma blok 27:61-70",
 "etiket":"okuma sırasında ölçüldü",
 "test_notu":"**Kendi ölçütümün sınırını kaydediyorum: ayrı ayet sayısı ARTEFAKTI ayırıyor ama DONMUŞ KALIBI anlamsal birliktelikten ayırmıyor.** Bunun için ikinci bir alan gerekiyor: **ortak geçişlerin aynı n-gram'ı paylaşıp paylaşmadığı.** أساطير الأوّلين dokuz yerde ama tek ifade; عمي/صمم sekiz yerde ve her seferinde farklı terkip. **Yani 'aynı sahne' alanının yanına 'aynı ifade' alanı da gerekiyor — ve bu, aday 844'ün nakarat n-gram altyapısıyla AYNI altyapı.** İki P0 tek bir araçla çözülebilir."},
{"no":851,
 "aday":"SÛRE 27'NİN ÜÇ İLTİFÂTI ÜÇ AYRI KATMANDA — TAM KÜME. 27:6 (3>2, anlatı içi) · 27:31 (3>12, alıntı sınırında) · 27:69 (1>23, emir zincirinde). Sûrede başka iltifât yok.",
 "olculen":{"sure":27,"iltifat_ayetleri":[[6,"3>2"],[31,"3>12"],[69,"1>23"]],
   "katmanlar":["anlatı içi","alıntı sınırı","emir zinciri"],"tam_kume":True},
 "durum":"KAPALI","oncelik":"P1","kaynak":"okuma blok 27:61-70",
 "etiket":"okuma sırasında ölçüldü",
 "test_notu":"**Aday 811'in sınıflandırma önerisine sûre içi TAM küme: üç iltifât, üç farklı katman, tekrar yok.** Sûre sonuna kadar okunmadan kapatılmadı — defterden doğrulandı ki sûrede toplam üç iltifât var (ders 774 karşılandı). **Sûre 26'nın on beş iltifâtı bu sınıflandırmadan geçmediği için 26/27 iltifât karşılaştırması hâlâ yapılamaz.**"},
{"no":852,
 "aday":"27:61 ↔ 27:62 — ARDIŞIK AYETLERDE ZIT SAYI ALANI. 27:61 fâsıla öncesi أَكْثَرُهُمْ (çoğu), 27:62 fâsıla öncesi قَلِيلًا (az). Aynı bölüt, aynı konum, zıt nicelik.",
 "olculen":{"ayetler":["27:61","27:62"],"say_alani":[["كثر","أَكْثَر"],["قلل","قَلِيل"]],
   "konum":"fâsıla öncesi","sure_27_say_alani_dolu":["27:48 تسع","27:61 كثر","27:62 قلل"]},
 "durum":"KAPALI","oncelik":"P2","kaynak":"okuma blok 27:61-70",
 "etiket":"okuma sırasında ölçüldü",
 "test_notu":"`say` alanı sûre 27'de üç ayette dolu (27:48, 61, 62) ve ikisi ardışık ve zıt. **Sayı alanı 'nicelik' değil 'sayı sözcüğü' sayıyor — أَكْثَر ve قَلِيل sayı değil, nicelik belirteci; تِسْعَة gerçek sayı.** Alan bu ikisini ayırmıyor. Küçük ama kayda değer bir tür karışıklığı; P2."},
{"no":853,
 "aday":"BLOK 27:61-70 BİLANÇOSU. Yıldız: ★★★ 1 (27:68, kaynak PAS) · ★★ 0 · ★ 0 · yıldızsız 9. **Doğa bölütünün gövdesi (27:61-64) tamamen yıldızsız.** İltifât 1/10 (27:69, sûrenin sonuncusu). Esmâ token 2, ikisi de artefakt. Allah lafzı 6 · **Rab 0 — iki blok üst üste.** Adlı aktör 0 · adsız aktör 0 — **okumada ilk kez bir blokta hiç aktör yok.** Yeni kök 1 (حجز). Hapaks 0. Kafiye kırılması 0.",
 "olculen":{"blok":"27:61-70","ayet":10,
   "yildiz":{"3":1,"2":0,"1":0,"0":9},
   "yildiz_kaynak":{"pas":1,"icerik":0},
   "iltifat":1,"esma_token":2,"esma_artefakt":2,"muhur":0,
   "allah_lafzi":6,"rab":0,"adli_aktor":0,"adsiz_aktor":0,
   "yeni_kok":1,"hapaks":0,"kafiye_kirilmasi":0,"mim_fasila":0,
   "nakarat_alani_dolu":0,"ort_n":13.4},
 "durum":"KAPALI","oncelik":"P2","kaynak":"okuma blok 27:61-70",
 "etiket":"okuma sırasında ölçüldü",
 "test_notu":"Sûre 27 ilk yetmiş ayet: ★★★ 6 · ★★ 5 · ★ 5 · yıldızsız 54. Esmâ token 27 (17 artefakt, 10 geçerli mühür tokeni). Allah lafzı 23 · Rab 5 → **A/R = 4,60** (ilk kırkta 1,40 · ellide 2,80 · altmışta 3,40; makro 2,25). **Oran monoton artıyor ve makronun iki katına çıktı — sûrenin ikinci yarısı belirgin biçimde eksen yoğun.** İltifât 3/70 (tamamlandı). **Beş blok üst üste yıldızsız oran ≥%80.**"},
]

BAGLAR = [
 {"bag":"27:60 ↔ 27:61 ↔ 27:62 ↔ 27:63 ↔ 27:64","kural":"L1","not":"**`أَءِلَٰهٌ مَّعَ ٱللَّهِ` — korpusun tamamında yalnız bu beş ayette, ardışık, hepsi `أَمَّنْ` ile açılıyor. `nakarat` alanı beşinde de SIFIR** (aday 844)."},
 {"bag":"27:14 ↔ 27:51 ↔ 27:69","kural":"L1","not":"**`كَيْفَ كَانَ عَٰقِبَةُ` sûrede üç kez, değişen tamlananla (müfsidîn / mekrihim / mücrimîn). Korpusta yirmi bir ayet. `nakarat` alanı üçünde de sıfır** — şablon kalıp türü (aday 845)."},
 {"bag":"27:44 ↔ 27:62","kural":"L1","not":"كشف *(giderme, açma)* sûrede iki geçiş, iki anlam alanı: baldırların açılması / kötülüğün giderilmesi. 529 kümesinin sûre içi dördüncü vakası; otomatik ölçüt yine çalışmadı (2/8)."},
 {"bag":"27:64 ↔ 2:111 · 21:24 · 28:75","kural":"L2","not":"**هات + برهن korpusta dört ayette birlikte ve hepsi aynı donmuş ifade (هاتوا برهانكم); karşılıklı kat ×914,0 ve ×810,8.** Aday 835'in Tür B'si (aday 850)."},
 {"bag":"27:61 ↔ 16:15 · 21:31 · 31:10","kural":"L2","not":"رسو *(sabit dağ)* ▸ ميد ×452,9 üç ayrı ayetten ve üçü de aynı kalıp: 'yeri sarsmasın diye sabit dağlar'. Tür B."},
 {"bag":"27:68 ↔ 23:83","kural":"L2","not":"Üç xref 3-gram'ın üçü de bu ayete: aynı diriliş itirazı korpusta birebir tekrar ediyor."},
 {"bag":"27:70 ↔ 16:127","kural":"L2","not":"İki 3-gram'ın ikisi de bu ayete: aynı iki yasak (üzülme / sıkıntıda olma) aynı sırayla, başka bir sûrede birebir — donmuş kalıp."},
 {"bag":"27:25 ↔ 27:37 ↔ 27:56 ↔ 27:67","kural":"L1","not":"خرج *(çıkma, çıkarma)* sûrede dört geçiş ve dört ayrı 'çıkarılan': gizli olan · ordudan çıkarılanlar · şehirden çıkarılacak aile · topraktan çıkarılacak ölüler. **Kök tek anlam alanında, nesnesi her seferinde başka katmanda.**"},
 {"bag":"27:59 ↔ 27:63","kural":"L1","not":"**Aynı eksen içeriği (iki lafız), tek fark n (12'ye 20): 27:59 → allah z=2,80 ve ★★; 27:63 → allah z=1,47 ve SIFIR.** Aday 827/837'nin en temiz vakası (aday 847)."},
 {"bag":"27:6 ↔ 27:31 ↔ 27:69","kural":"L1","not":"Sûrenin üç iltifâtı, üç ayrı katmanda: anlatı içi (3>2) · alıntı sınırı (3>12) · emir zinciri (1>23). Tam küme (aday 851)."},
 {"bag":"27:50 ↔ 27:51 ↔ 27:70","kural":"L1","not":"مكر *(tuzak)* sûrede altı token, üç ayette, yirmi ayetlik bir yay içinde: dört kez tuzak kuranların, bir kez sonucu, bir kez peygambere yasak."},
]

pa = '/home/claude/repo/bulgular/aday_bulgular.json'
AD = json.load(open(pa, encoding='utf-8'))
AD['AH_neml'].extend(ADAYLAR)
json.dump(AD, open(pa, 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
print('aday_bulgular: AH_neml →', len(AD['AH_neml']), '| son no', AD['AH_neml'][-1]['no'])

pb = '/home/claude/repo/notlar/okuma_baglantilari.json'
BG = json.load(open(pb, encoding='utf-8'))
BG['AG_neml'].extend(BAGLAR)
json.dump(BG, open(pb, 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
print('okuma_baglantilari: AG_neml →', len(BG['AG_neml']))
