# -*- coding: utf-8 -*-
"""aday_ekle_33_ahzab.py — sûre 33 (Ahzâb) adayları (AR_ahzab) ve okuma bağları (AM_ahzab).

BLOK BAŞI KAYIT: her blok sonunda bu dosyaya o bloğun adayları ve bağları EKLENİR ve betik
yeniden koşulur. Set bütünüyle yeniden yazılır (idempotent): iki kez koşmak çift kayıt üretmez.
Numaralar havuzun sonundan devam eder; havuz boyu defterden değil aday_bulgular.json'dan okunur
ve betik sıranın kopmadığını doğrular.
"""
import json

AHZAB = [
# ---------------- blok 1-10 ----------------
{"no":979,
 "aday":"blok_goster.py BESMELE ARIZASI — 1. ayet ayıklaması yalnız 5 kelimelik açılışları (besmele + tek kelime) tanıyordu: 112 besmeleli açılışın 26'sı. 33:1 besmeleyle basılacaktı.",
 "olculen":{"eski_kural":"len(ayet)==5","eski_yakalanan":26,"yeni_yakalanan":112,"toplam":112,
   "yeni_kural":"1:1'in ilk dört kelimesinin iskeleti (korpustan, Arapça sabit yok)",
   "yan_bulgu":"1:1 metninin başında BOM (U+FEFF) — ilk denemede hiçbir sûre eşleşmedi"},
 "durum":"KAPALI","oncelik":"P0","kaynak":"sûre 33 okuması, blok 1-10","etiket":"okumayı bloke eden arıza — yerinde onarıldı",
 "test_notu":"Araç dondurma kararının istisnası: arıza okumayı fiilen bloke ediyordu. uret_blok_33 aynı kuralı taşıyor ve besmele kalırsa DURUYOR."},
{"no":980,
 "aday":"okuma_metni.json'da BESMELE KALINTISI — ayet düzeyinde kayıtlı 23 sûrenin (10-32) 6'sında 1. ayetin ar alanı besmeleyle başlıyor: 20, 21, 22, 25, 26, 27.",
 "olculen":{"taranan":"okuma_metni.json, ar alanı olan sûreler 10-32 (TAM SAYIM)","kirli":[20,21,22,25,26,27],"kirli_sayi":6,"taranan_sayi":23,
   "olcum_etkisi":"yok — ölçüm defterden (n temiz); yalnız görüntü metni"},
 "durum":"ACIK","oncelik":"P2","kaynak":"aday 979'un retroaktif taraması","etiket":"kayıt kirliliği",
 "test_notu":"Onarım ertelendi (dondurma). Tek betikle altı ar alanı kırpılabilir; özgün kayıt korunup 'duzeltildi' alanı eklenmeli."},
{"no":981,
 "aday":"★★ SAY ALANI YANLIŞ POZİTİFLERİ — zevc 'eş' anlamında (33:4, 33:6) ve a'adde 'hazırladı' (33:8, adad kökü IV. bab) sayı işareti sayılıyor; qalîl üç kez (33:16, 18, 20) miktar sözcüğü olarak işaretli.",
 "olculen":{"yanlis_pozitif":{"33:4":"zevc (eş)","33:6":"zevc (eş)","33:8":"a'adde (hazırlamak)"},
   "tartismali":{"33:16":"qalîl","33:18":"qalîl","33:20":"qalîl"},"blok":"33:1-20"},
 "durum":"ACIK","oncelik":"P1","kaynak":"sûre 33 okuması","etiket":"borç #13 (say alanı)",
 "test_notu":"Kök düzeyi eşleşme anlamı ayırmıyor: zevc hem 'çift' hem 'eş'. Korpus çapında zevc'in sayı/eş ayrımı sayılmadan alan kullanılamaz."},
{"no":982,
 "aday":"★ MM2 BİTİŞİKLİK KOŞULU — ardışık iki ayette iki mef'ûl-i mutlak: 33:10 (fiil + araya lafız + masdar) YAKALANMIYOR, 33:11 (bitişik) YAKALANIYOR.",
 "olculen":{"kacirilan":["27:58 (önceki kayıt)","33:10"],"yakalanan":["33:11"],"kural":"08_adli_ve_mm_onarim: aynı kök + ACC isim w+1'de"},
 "guncelleme_41_50":{"kacirilan_ek":"33:41 (üzkürullâhe zikran — araya lafız)","sure_33_1_50":{"kacirilan":["33:10","33:41"],"yakalanan":["33:11","33:23","33:28","33:32","33:33 ×2","33:36","33:49"]}},
 "durum":"ACIK","oncelik":"P2","kaynak":"sûre 33 okuması","etiket":"araç açığı (aday 924: metin hakkında kanıt değil)",
 "test_notu":"Bitişik olmayan mef'ûl-i mutlak sayısı bilinmiyor. mm2 dağılımına dayanan hiçbir iddia bu açık kapanmadan kurulmaz."},
{"no":983,
 "aday":"★★ YILDIZIN OTOMATİK ★★★ TETİKLEYİCİLERİ — sûre 33'ün ilk 20 ayetindeki beş ★★★'ın beşi de otomatik: allah yoğunluğu (33:3, 6 kelimede 2 lafız, z=6,14), hapaks (33:4, 33:18, 33:19), edilgenlik (33:11, iki fiilin ikisi edilgen, z=5,38). İçerikten gelen ★★★ yok.",
 "olculen":{"ucyildiz":{"33:3":"allah 6,14","33:4":"hapaks 3,28","33:11":"pas 5,38","33:18":"hapaks 3,28","33:19":"hapaks 3,28"},
   "tek_olcut_sorunu":{"33:4":"hapaks + n 1,65 + kafiye kırığı","33:19":"hapaks + n 2,40"},
   "kaynak":"blok_bilanco.py (defter, TAM SAYIM)"},
 "guncelleme_31_40":{"sure_33_1_40_ucyildiz":10,"kaynak":{"hapaks":5,"allah":3,"pas":1,"n":1},"icerikten":0,"tek_olcut_sorunu_ek":{"33:37":"n 3,78 + hapaks 3,28 + allah 1,56"},"kaynak_betik":"blok_bilanco.py"},
 "guncelleme_41_50":{"sure_33_1_50_ucyildiz":11,"kaynak":{"hapaks":5,"allah":3,"pas":1,"n":2},"icerikten":0,"yeni":"33:50 n z=5,16"},
 "guncelleme_51_60":{"sure_33_1_60_ucyildiz":12,"kaynak":{"hapaks":5,"allah":3,"pas":1,"n":3},"icerikten":0,"yeni":"33:53 n z=6,01"},
 "guncelleme_61_70":{"sure_33_1_70_ucyildiz":13,"kaynak":{"hapaks":5,"allah":3,"pas":2,"n":3},"icerikten":0,"yeni":"33:61 pas z=5,38"},
 "guncelleme_sure_sonu":{"sure_33_ucyildiz":14,"kaynak":{"hapaks":5,"allah":4,"n":3,"pas":2},"icerikten":0,"tum_yildiz":{"ayet":42,"kaynak":{"allah":22,"n":8,"hapaks":5,"pas":5,"rab":2}}},
 "durum":"ACIK","oncelik":"P1","kaynak":"sûre 33 okuması, bloklar 1-10 ve 11-20","etiket":"borç #7 ve #15",
 "test_notu":"Kısa ayette oran büyüyor (33:3, 33:11): ölçek etkisi. Formül en büyük |z|'yi alıyor, ikinci bağımsız işareti eklemiyor (33:4, 33:19)."},
{"no":984,
 "aday":"★★ FÂSILA: SÛRE 33'ÜN 73 AYETİNİN 72'Sİ A SINIFI, TEK İSTİSNA 33:4 (es-sebîl). Aynı lemma 33:67'de uzatma elifiyle (es-sebîlâ) ayet sonunda.",
 "olculen":{"sure_73":{"A":72,"ل":1},"istisna":"33:4","ayni_lemma_elifli":"33:67","kaynak":"defter fs alanı, TAM SAYIM"},
 "durum":"ACIK","oncelik":"P1","kaynak":"sûre 33 okuması — okurken fark edildi, sonra sayıldı","etiket":"okuma gözlemi",
 "test_notu":"Korpus çapında: aynı lemmanın aynı sûrede hem elifli hem elifsiz fâsıla olduğu kaç vaka var? Sayılmadan iddia kurulmaz."},
{"no":985,
 "aday":"★★★ ÖN-KAYIT §4.3 MÜHÜR TANIMI KONUM SÜZGECİ UYGULAMIYOR — son-üç içerik lemmasında esmâ lemması varsa mühür sayılıyor; göndergenin Allah olup olmadığına bakılmıyor.",
 "olculen":{"sure_33_1_20":{"muhur_43":7,"gecerli":5,"yanlis":2},
   "yanlis":{"33:11":"mü'min (insanlar)","33:17":"velî + nasîr ÇİFT ('Allah'tan başka')"},
   "blok":{"1-10":"5/5 geçerli","11-20":"0/2 geçerli"},
   "sinif_etkisi":"33:11 e_oto ile E sınıfı, e_el ile 0 sınıfı",
   "sinama_kumesine_ek":["33:6 mü'min ×2 + velî","33:11 mü'min","33:17 velî + nasîr"],
   "kaynak":"esma_kayit.json + esma_el.py"},
 "guncelleme_21_30":{"sure_33_1_30":{"muhur_43":11,"gecerli":8,"yanlis":3},"blok_21_30":"4 mühür, 3 geçerli; yanlış: 33:21 âhir (âhiret günü)","kaynak":"blok_bilanco.py"},
 "guncelleme_31_40":{"sure_33_1_40":{"muhur_43":16,"gecerli":11,"yanlis":5},"blok_31_40":"5 mühür, 3 geçerli; yanlış: 33:31 kerîm (rızık), 33:36 mübîn (sapıklık)","E_sinifi":{"oto":["33:11","33:32"],"el":[],"not":"sûre 33'te 40 ayette E sınıfının ikisi de esmâ yanlış pozitifinden; okuyucu kararıyla E sınıfı BOŞ"}},
 "guncelleme_41_50":{"sure_33_1_50":{"muhur_43":21,"gecerli":14,"yanlis":7},"blok_41_50":"5 mühür, 3 geçerli; yanlış: 33:44 selâm+kerîm (ÇİFT), 33:47 kebîr","cift_ve_ton_kirliligi":"33:43 tek gerçek esmâ (rahîm) ama son-üçteki nûr ve mü'min yüzünden 'ÇİFT' ve ton 'karma' — cift/ton alanları da e_el üzerinden tanımlanmalı","E_sinifi":{"oto":["33:11","33:32","33:43","33:44"],"el":["33:43"],"not":"50 ayette okuyucu kararıyla tek E: 33:43 (özne zamir, rahîm yüklem)"}},
 "guncelleme_51_60":{"sure_33_1_60":{"muhur_43":28,"gecerli":19,"yanlis":9},"blok_51_60":"7 mühür, 5 geçerli; yanlış: 33:57 âhir, 33:58 mübîn","E_sinifi":{"oto_ek":["33:58"],"el_ek":[],"sure_33_1_60_el":["33:43"]}},
 "guncelleme_61_70":{"sure_33_1_70":{"muhur_43":31,"gecerli":19,"yanlis":12},"blok_61_70":"3 mühür, 0 geçerli: 33:63 karîb, 33:65 velî+nasîr (ÇİFT), 33:68 kebîr","R_sinifi":["33:67","33:68"],"E_sinifi":{"oto_ek":["33:65"],"sure_33_1_70_el":["33:43"]}},
 "guncelleme_sure_sonu":{"sure_33":{"muhur_43":32,"gecerli":20,"yanlis":12,"yanlis_ayet":[11,17,21,31,36,44,47,57,58,63,65,68]},"E_sinifi":{"oto":6,"el":1},"esma_token":{"oto":65,"ilahi":29},"kaynak":"ahzab_kapanis.py → esma_kayit.json _profil_33"},
 "durum":"ACIK","oncelik":"P0","kaynak":"esmâ kaydı, sûre 33","etiket":"ön-kayıt dondurma öncesi karar noktası (4)",
 "test_notu":"Karar: mühür ve sınıf e_oto üzerinden mi e_el üzerinden mi tanımlanır? Dondurma §9 doldurulmadan kapanmalı. Sonuca bakılmadan karar verilmeli."},
{"no":986,
 "aday":"★★ ESMÂ TONU KAPSAMI — esma_listesi.json'un 72 lemmasından yalnız 26'sı varlik_katalog.json'da ton (cemâl/denge/celâl) taşıyor; 46'sı katalog-dışı. Katalogdaki azîm (denge) listede yok.",
 "olculen":{"liste":72,"katalogda_tonlu":26,"katalog_disi":46,"katalogda_listede_olmayan":["azîm"],"ilk_vaka":"33:3 vekîl"},
 "durum":"ACIK","oncelik":"P0","kaynak":"esmâ kaydı, sûre 33","etiket":"ön-kayıt dondurma öncesi karar noktası (3)",
 "test_notu":"Bu kapsamla H2'nin mühürlerinin çoğu tonsuz kalır. Ton ataması katalogdan mı genişletilir, yoksa H2 yalnız tonlu 26 lemmayla mı koşulur — dondurmadan önce karar."},
# ---------------- blok 11-20 ----------------
{"no":987,
 "aday":"★★★ KÖK GLOSSU KÖKÜN BASKIN ANLAMINI TAŞIMIYOR — belâ 'eskiyip yıpranma' (baskın anlam sınama), devr 'yurt, ev' (33:19 dönmek), velî 'dost, veli' (33:15 arka çevirmek).",
 "olculen":{"bela":{"gloss":"eskiyip yıpranma","envanter":"sınama lemmaları baskın; yıpranma lemması 2 kez"},
   "devr":{"gloss":"yurt, ev","33:19":"dönmek (fiil)"},
   "veli":{"gloss":"dost, veli; velâyet","envanter":"tevellâ 78 · vellâ 30 (çevirmek/yüz çevirmek)"},
   "blok":"33:11-20"},
 "guncelleme_51_60":{"hayy":{"gloss":"diri olma, hayat","tasimayan":"istihyâ (utanmak; envanterde 9+1) — 33:53 ×2 · tahiyye (selamlama; 6) — 33:44"},"karar_ayni":"kaydedildi, onarılmadı"},
 "guncelleme_61_70":{"nur":{"gloss":"nûr, ışık","envanter":"nâr 145 · nûr 43 · münîr 6","33:66":"fi'n-nâr (ateş)","not":"gloss baskın lemmanın tersini gösteriyor — belâ ile aynı tür"},"sedd":{"gloss":"set","33:70":"kavlen sedîdâ (doğru söz)"},"sure_33_toplam_kok":["بلو","دور","ولي","حيي","نور","سدد"]},
 "durum":"ACIK","oncelik":"P1","kaynak":"sûre 33 okuması, blok 11-20","etiket":"borç #5b'nin kök düzeyi eşi",
 "test_notu":"belâ glossu daha önce okunan her ayette yanlış anlam basmış olabilir. Onarım retroaktif gloss turu ister; özgün gloss korunup 'duzeltildi' alanı eklenmeli."},
{"no":988,
 "aday":"★ QALÎLÂ FÂSILASI — sûre 33'te qalîlâ ile biten 4 ayet: 16, 18, 20, 60. Üçü ikinci blokta, çift sıradaki ayetlerde.",
 "olculen":{"ayetler":[16,18,20,60],"kaynak":"defter fs alanı, TAM SAYIM (sûre)"},
 "durum":"KAPATILAMAZ","oncelik":"P2","kaynak":"sûre 33 okuması — OKURKEN bulundu","etiket":"taraflı örneklem uyarısı (aday 899)",
 "test_notu":"Okuma sırasında fark edilen dizilim; boş model yok. Tek başına kanıt değil, yalnız kayıt."},
{"no":989,
 "aday":"TARAYICI v4 SÛRE 33 ARA BİRİKİM (1-20) — iki aday (33:9 G_bakış, 33:16 A_şart), ikisi de çıpa değil; L4 çıpa 0. Anma 0/0 · kesinlik 0/2.",
 "olculen":{"aday":["33:9","33:16"],"cipa_L4":[],"anma":"0/0","kesinlik":"0/2",
   "kademe_isaretli":{"33:4":"L1 olgu","33:9":"L0 olgu","33:10":"L0","33:13":"L3-benzeri, olgu değil","33:19":"L1"},
   "dizi":{"27":"4/4","28":"3/3","29":"3/3","30":"2/9","31":"0/3","32":"2/2"}},
 "guncelleme_21_30":{"aday":["33:9","33:16","33:28"],"cipa_L4":[],"anma":"0/0","kesinlik":"0/3"},
 "guncelleme_31_40":{"aday":["33:9","33:16","33:28","33:35","33:37"],"cipa_L4":[],"anma":"0/0","kesinlik":"0/5"},
 "guncelleme_41_50":{"aday":["33:9","33:16","33:28","33:35","33:37","33:43","33:49","33:50"],"cipa_L4":[],"anma":"0/0","kesinlik":"0/8"},
 "guncelleme_51_60":{"aday_ek":["33:51","33:52","33:53","33:59"],"toplam_aday":12,"cipa_L4":[],"anma":"0/0","kesinlik":"0/12"},
 "guncelleme_61_70":{"aday_ek":[],"toplam_aday":12,"cipa_L4":[],"anma":"0/0","kesinlik":"0/12"},
 "guncelleme_sure_sonu":{"sure_33":{"aday":12,"cipa_L4":0,"anma":"0/0","kesinlik":"0/12"},"dizi":{"27":"4/4","28":"3/3","29":"3/3","30":"2/9","31":"0/3 (kesinlik 0/7)","32":"2/2","33":"0/0 (kesinlik 0/12)"},"not":"Sûre 33'te hiç L4 çıpa yok ve tarayıcı 12 aday verdi: kesinlik sûreler arasında en düşük. Ölçüt DEĞİŞTİRİLMEDİ; karar tam okuma bitince."},
 "durum":"ACIK","oncelik":"P0","kaynak":"sûre 33 okuması","etiket":"aday 948 birikimi (ara)",
 "test_notu":"Sûre bitince bu kayıt sûre toplamıyla güncellenir. Ölçüt DEĞİŞTİRİLMEDİ."},
{"no":990,
 "aday":"BİÇİM İHLÂLİ + KAYIT RİSKİ — 33:1-20 okuması dosyaya yazılıp sohbete yalnız bilanço verildi (sohbette 0/20 '### S:N' başlığı); ayrıca okuma_metni, mercek_kayit, adaylar ve bağlar tur sonuna bırakıldığı için 20 ayetin bulguları yapılandırılmış hâlde hiçbir yerde yoktu.",
 "olculen":{"baslik_sohbette":"0/20 → 33:1-10 yeniden okundu (10/10)","kayit_once":"yalnız kok_turkce, dikey JSON, esma_kayit, metin modülü",
   "karar":"BLOK BAŞI KAYIT (kullanıcı onayı 2026-09-24): uret_blok_33 + blok_bilanco + ahzab_kayit + bu betik her blokta koşulur"},
 "durum":"KAPALI","oncelik":"P0","kaynak":"kullanıcı düzeltmesi","etiket":"protokol ihlâli (aday 975 ailesi)",
 "test_notu":"Sûre 31'in tur sonunun atlanıp borca dönmesi aynı riskin gerçekleşmiş hâliydi. Blok başı kayıtla oturum yarıda kalsa da okunan her blok kayıtlı."},
# ---------------- blok 21-30 ----------------
{"no":991,
 "aday":"★★ SÛRE İÇİ AYNA ÇİFTLERİ — üçüncü blok ikinci bloğun ayetlerini aynı kalıpla ters yönde tekrarlıyor: 33:12↔33:22 (vaat: gurûr / îmân), 33:15↔33:23 (ahit: bozulan / sadık kalınan), 33:8↔33:24 (sâdıkîn: sorgu / karşılık), 33:3↔33:25 (kifâyet: ilke / olay), 33:9-10↔33:26 (kuşatma: gelen / indirilen).",
 "olculen":{"ciftler":{"33:12-33:22":"nakarat3 (4 kelime) + iki HASR","33:15-33:23":"عهد sûrede 3/3","33:8-33:24":"li- + sâdıkîn + sıdkıhim, fiil sor → karşılık ver","33:3-33:25":"كفي 2/4","33:9-10-33:26":"kuşatma yönü tersine"},
   "yontem":"okuma sırasında görüldü; kalıp eşleşmeleri ölçüm satırı ve kök [x/y] sayılarıyla doğrulandı"},
 "durum":"KAPATILAMAZ","oncelik":"P1","kaynak":"sûre 33 okuması, blok 21-30","etiket":"taraflı örneklem uyarısı (aday 899)",
 "test_notu":"Tek tek eşleşmeler ölçümle doğrulanmış; 'sûre ayna yapısında' iddiası DEĞİL. Boş model: aynı sûrede rastgele ayet çiftlerinde nakarat3/kök paylaşımı oranı. Kurulmadan yapı iddiası yok."},
{"no":992,
 "aday":"★★ SAY ALANI YANLIŞ NEGATİFİ — 33:30 di'fayn ('iki kat', ikili sayı) ayetteki tek gerçek sayı ifadesi ve say alanı onu YAKALAMIYOR; aynı blokta kesîr, zevc ve a'adde'yi yakalıyor.",
 "olculen":{"yanlis_negatif":"33:30 ضعف (yudâ'af · di'fayn)","sure_33_1_30_yanlis_pozitif":{"zevc":["33:4","33:6","33:28"],"a'adde":["33:8","33:29"],"kesîr":["33:21"]},"tartismali":{"qalîl":["33:16","33:18","33:20"]}},
 "guncelleme_31_40":{"yanlis_negatif_ek":"33:31 merrateyn (iki kere) — 33:30 di'fayn ile ardışık","kok_duyarliligi":"a'adde (عدد) işaretleniyor, aynı anlamdaki a'tednâ (عتد, 33:31) işaretlenmiyor: alan anlama değil köke bakıyor","yanlis_pozitif_ek":{"zevc":["33:37 ×3"]},"tartismali_ek":{"ehad":["33:32","33:39","33:40"]}},
 "guncelleme_41_50":{"dogru_pozitif":"33:49 'idde ta'teddûnehâ (عدد: sayma)","ayni_kok_yanlis_pozitif":"a'adde (عدد: hazırlama) dört kez — 33:8, 33:29, 33:35, 33:44","sonuc":"kök düzeyinde eşleşme aynı kökün iki anlamını ayıramıyor; lemma düzeyi gerekli"},
 "guncelleme_61_70":{"yanlis_negatif_ek":"33:68 di'fayn (azabın iki katı)","sure_33_ikil":{"gercek":["33:30","33:31","33:68"],"isaretli":0},"a'adde_toplam":{"ayet":["33:8","33:29","33:35","33:44","33:57","33:64"],"isaretli":6,"dogru":0}},
 "durum":"ACIK","oncelik":"P1","kaynak":"sûre 33 okuması, blok 21-30","etiket":"borç #13 (aday 981'in eşi)",
 "test_notu":"say alanı bir sözcük listesiyle çalışıyor; sayısal içerik (ikil, kat, oran) sözcük listesinde değilse görünmüyor. Kesinlik ve anma ayrı ayrı ölçülmeden alan kullanılamaz."},
{"no":993,
 "aday":"★ ESMÂ TON ETİKETİ 'KARMA' İKİ DURUMU AYIRMIYOR — 33:25 kavî + azîz: kavî katalog-dışı, azîz katalogda cemâl; esma_kayit 'karma' yazıyor. Ayrıca azîz'in cemâl sınıfında olması katalog kararı, gerekçesi kayıtta yok.",
 "olculen":{"vaka":"33:25","kavi":"katalog-dışı","aziz":"cemâl","etiket":"karma"},
 "durum":"ACIK","oncelik":"P1","kaynak":"esmâ kaydı, sûre 33","etiket":"aday 986 ailesi (ton kapsamı)",
 "test_notu":"H2 için 'karma' yalnız iki farklı TON varken kullanılmalı; eksik ton ayrı bir değer ('eksik') almalı. Dondurmadan önce tanım netleşmeli — veri toplanmaya devam ediyor, etiket ham lemma listesiyle birlikte kayıtlı olduğundan sonradan yeniden türetilebilir."},
# ---------------- blok 31-40 ----------------
{"no":994,
 "aday":"★★ İLTİFÂT ALANI AYET İÇİ CİNSİYET/SAYI GEÇİŞİNİ GÖRMÜYOR — 33:33 hitap 2FP (11 kez) ile başlıyor ve ehl-el-beyt kısmında 2MP'ye (iki kez) geçiyor; ilt alanı 0.",
 "olculen":{"vaka":"33:33","sahis":{"2FP":11,"2MP":2,"3MS":4},"ilt":0,"kaynak":"olcum_bicim şahıs dökümü"},
 "durum":"ACIK","oncelik":"P1","kaynak":"sûre 33 okuması, blok 31-40","etiket":"alan arızası (iltifât tanımı)",
 "test_notu":"İltifât tanımı yalnız kişi (1/2/3) değişimini sayıyorsa cinsiyet ve sayı değişimleri tanım dışında kalır — bu bir karar, hata değil olabilir; tanım belgesiyle karşılaştırılmalı. Korpus çapında 2FP→2MP ayet içi geçiş sayısı bilinmiyor."},
# ---------------- tur sonu ----------------
{"no":995,
 "aday":"SÛRE 33 KAPANIŞ BİLANÇOSU (TAM SAYIM) — 73 ayet · 1287 kelime · lafız 90 (51 ayet) · Rab 3 (33:2, 67, 68) → A/R = 30,0 · fâsıla 72 A + 1 ل (33:4) · ★★★ 14 · ★★ 16 · ★ 12 · yıldızsız 31 · yıldızlı 42 ayetin kaynakları: lafız 22 · uzunluk 8 · hapaks 5 · edilgenlik 5 · Rab 2 · İÇERİK 0.",
 "olculen":{"kaynak":"ahzab_kapanis.py → okuma_metni['33']['_bilanco_sure']","edilgen_ayet":11,"iltifat":[45,46],"hapaks_ayet":[4,18,19,23,26,37],"mm2_ayet":12,"en_uzun":"33:53 (69 kelime)","cipa":{"L4":0,"tarayici":"0/12"}},
 "durum":"KAYIT","oncelik":"P2","kaynak":"sûre 33 tur sonu","etiket":"kapanış bilançosu",
 "test_notu":"Sûre 32 ile karşılaştırma: A/R 0,1 → 30,0 (sûre 31: 16,0). Üç sûre arka arkaya kutup değiştiriyor; bu okuma gözlemi, test değil."},
{"no":996,
 "aday":"SÛRE 33 ESMÂ PROFİLİ (KAYIT, ölçüm değil) — sınıf e_oto: A 50 · AR 1 · E 6 · R 2 · 0 14; e_el: A 50 · AR 1 · E 1 · R 2 · 0 19. Esmâ tokeni 65, ilâhî 29. §4.3 mühür 32, geçerli 20, yanlış 12. Geçerli mühürlerin tonu: cemâl 13 · katalog-dışı 5 · karma 2.",
 "olculen":{"kaynak":"esma_kayit.json → _profil_33","bant":"KAPI_KAPALI","esma_listesi_sha256":"19fb1b12d6745b1c…"},
 "durum":"KAYIT","oncelik":"P0","kaynak":"ön-kayıt esmâ takibi, ilk sûre","etiket":"ONKAYIT_esma_katmanlari §6 sûre profili",
 "test_notu":"H1-H4 KOŞULMADI. Tek sûrelik profil, dondurma öncesi beş karar noktasının (nakarat2/3 · Hâdî/Hayy · ton kapsamı · §4.3'ün e_oto/e_el tanımı · kök glossu) hepsinin de gerçek veride nasıl çalıştığını gösteriyor: e_oto ile e_el arasında E sınıfında 6 → 1, 0 sınıfında 14 → 19 fark var; mühürlerin %37,5'i (12/32) yanlış."}
]

BAGLAR = {"AM_ahzab": [
 {"bag":"33:4 ↔ 33:6","kural":"okuma gözlemi (أمم kökü sûrede 2 kez, TAM SAYIM)",
  "not":"Aynı etiket iki ayette ters yönde: 'eşlerinizi analarınız KILMADI' / 'eşleri onların ANALARIDIR'. Fark etiketi koyanda: ağızlarınızdaki söz / Kitap'ta yazılmış."},
 {"bag":"33:4 → 33:5","kural":"okuma gözlemi",
  "not":"Soy etiketinin reddi ve pozitif kuralı: babalarına nispet edin; baba bilinmezse dinde kardeş ve mevlâ."},
 {"bag":"33:4 · 33:5 · 33:10 · 33:12","kural":"kök [x/y] (قلب, sûrede 11)",
  "not":"Kalp dört ayette dört işlevde: bedensel organ · niyet eden kalp · gırtlağa dayanan kalp · hastalıklı kalp."},
 {"bag":"33:3 → 33:48","kural":"nakarat3 TAM (6 kelime / 2 ayet)",
  "not":"Tevekkül formülü sûrede aynen tekrarlanıyor."},
 {"bag":"33:7 → 4:21 · 4:154","kural":"xref (mîsâkan galîzan)",
  "not":"Aynı ifade üç ilişkide: peygamberler · evlilik · İsrâiloğulları. Sûre 4 okunmadığı için DOĞRULANMADI."},
 {"bag":"33:7-8 → 33:15","kural":"okuma gözlemi (سأل sûre içi 1-4/7; عهد ×2)",
  "not":"Ahit ve sorgu çifti: peygamberlerden ahit alınıp sâdıklara sorulacak (33:8) · kaçmayacaklarına ahit verenlerin ahdi sorulacak (33:15)."},
 {"bag":"33:10 ↔ 33:11","kural":"mm2 karşıt çifti",
  "not":"İki ardışık mef'ûl-i mutlak: 33:10 yakalanmıyor (araya lafız), 33:11 yakalanıyor (bitişik). Aday 982."},
 {"bag":"33:12 → 33:60","kural":"xref",
  "not":"Münafıklar ve kalplerinde hastalık olanlar sûrede ikinci kez."},
 {"bag":"33:13 → 33:16","kural":"kök (فرر)",
  "not":"33:13 firârâ ile kapanıyor, 33:16 kaçışın fayda vermediğini ölçüyor."},
 {"bag":"33:4 ↔ 33:67","kural":"fâsıla TAM SAYIM (sûre)",
  "not":"Aynı lemma: 33:4 elifsiz (sûrenin tek A-dışı fâsılası), 33:67 elifli. Aday 984."},
 {"bag":"33:20 → 33:22","kural":"kök (حزب, sûrede 3: 20'de iki, 22'de bir)",
  "not":"Sûrenin adı metinde ilk kez 33:20'de."},
 {"bag":"33:12 ↔ 33:22","kural":"nakarat3 (4 kelime / 2 ayet) + iki HASR","not":"Aynı vaat kalıbı, aynı olay: münafıklar 'aldatmaca', mü'minler 'doğru söylemişler'. Aday 991."},
 {"bag":"33:15 ↔ 33:23","kural":"kök (عهد sûrede 3/3)","not":"Bozulan ahit / sadık kalınan ahit."},
 {"bag":"33:8 ↔ 33:24","kural":"okuma gözlemi (li- + sâdıkîn + sıdkıhim)","not":"Sorsun diye → karşılık versin diye. Ahit-sorgu ipliği kapanıyor."},
 {"bag":"33:3 → 33:25","kural":"kök (كفي sûrede 2/4)","not":"Vekil olarak Allah yeter (ilke) → Allah mü'minlere savaşta yetti (olay)."},
 {"bag":"33:9-10 ↔ 33:26","kural":"okuma gözlemi","not":"Kuşatma tersine: ordular geliyor / destekçiler kalelerinden indiriliyor; yürekler gırtlağa / kalplere korku atılıyor."},
 {"bag":"33:4 ↔ 33:26","kural":"kök (ظهر sûrede 2/2)","not":"Aynı kök iki anlam: zıhar / destek vermek (zâherûhum)."},
 {"bag":"33:8 ↔ 33:29","kural":"lemma (a'adde, sûrede 2)","not":"Aynı fiil iki uç: kâfirlere acıklı azap / muhsinelere büyük ecir."},
 {"bag":"33:19 ↔ 33:30","kural":"nakarat3 (5 kelime / 2 ayet)","not":"'Bu Allah'a kolaydır': amellerin boşa çıkarılması / azabın katlanması."},
 {"bag":"33:1 → 33:28","kural":"nidâ kalıbı (eyy-nebî)","not":"İkinci nidâ bölüm geçişi: hitap ilk kez 2FP (ilk 27 ayette yok)."},
 {"bag":"33:28 ↔ 33:29","kural":"okuma gözlemi (aynı şart fiili iki dal)","not":"İkili seçim: dünya hayatı ve süsü / Allah, Resûl ve âhiret yurdu."},
 {"bag":"33:21 → 60:6","kural":"xref (üsve hasene)","not":"Aynı ifade İbrâhîm için. Sûre 60 okunmadı — DOĞRULANMADI."},
 {"bag":"33:30 ↔ 33:31","kural":"okuma gözlemi (ikil: di'fayn / merrateyn)","not":"Azap iki kat / ecir iki kere. İkisi de say alanında görünmüyor (aday 992)."},
 {"bag":"33:4 ↔ 33:32","kural":"okuma gözlemi","not":"Sınıflama: 33:4 üç sınıf reddi / 33:32 'siz kadınlardan herhangi biri gibi değilsiniz'."},
 {"bag":"33:12 ↔ 33:32","kural":"nakarat3 (fî kalbihî maradun)","not":"Kalbinde hastalık olan sûrede ikinci kez."},
 {"bag":"33:33 → 33:34","kural":"kök (بيت 2-4/5)","not":"Evlerinizde oturun → evlerinizde okunanı anın."},
 {"bag":"33:8 · 33:29 · 33:35","kural":"lemma (a'adde, sûrede 3)","not":"Hazırladı: azap / ecir / mağfiret ve ecir."},
 {"bag":"33:21 → 33:35","kural":"okuma gözlemi","not":"'Allah'ı çok anmak' 33:21'de örneğin koşulu, 33:35'te on çiftlik listenin son maddesi."},
 {"bag":"33:4 → 33:37","kural":"lemma (ed'iyâ, دعو)","not":"Evlatlık kuralı (33:4) bir olayda uygulanıyor (33:37). Adlı aktör Zeyd, korpusta tek ayet."},
 {"bag":"33:37 ↔ 33:39","kural":"kök (خشي sûrede 4/4)","not":"İnsanlardan çekinmek, Allah daha lâyık / Allah'tan başka kimseden çekinmemek."},
 {"bag":"33:37 → 33:38","kural":"nakarat3 (kâne emrullâh)","not":"Emir yerine geldi / emir takdir edilmiş kaderdir."},
 {"bag":"33:38 → 33:62","kural":"nakarat3 (7 kelime)","not":"Sünnetullah formülü sûrede ileride tekrar — 33:62 henüz okunmadı."},
 {"bag":"33:3 · 33:25 · 33:39","kural":"kök (كفي sûrede 3/4) + nakarat3","not":"Vekil olarak yeter / savaşta yetti / hesap görücü olarak yeter."},
 {"bag":"33:4 · 33:5 · 33:40","kural":"kök (أبو 1-3/4, رجل 1/3/3)","not":"Soy ekseni kapanıyor: evlatlık oğul değil / babalarına nispet / Muhammed hiçbirinizin babası değil. racül üç kez: 33:4 · 33:23 · 33:40."},
 {"bag":"33:1 · 33:3 → 33:48","kural":"nakarat3 (4 kelime + 6 kelime)","not":"Açılış üçlüsü tek ayette birleşik tekrar: 'kâfirlere ve münafıklara boyun eğme' + 'Allah'a dayan; vekil olarak Allah yeter'. وكل ve كفي 4/4 burada tamamlanıyor."},
 {"bag":"33:9 → 33:41","kural":"nakarat3 (yâ eyyühe'llezîne âmenû + ذكر)","not":"'Anın' emri ikinci kez: 33:9 nimeti, 33:41 Allah'ı."},
 {"bag":"33:21 · 33:35 · 33:41","kural":"okuma gözlemi (zikr-i kesîr)","not":"Allah'ı çok anmak: örneğin koşulu / listenin son maddesi / emir."},
 {"bag":"33:43 → 33:46","kural":"kök (نور 1-2/3)","not":"Karanlıklardan nura çıkarmak (Allah'ın işi) → aydınlatan kandil (Peygamber'in rolü)."},
 {"bag":"33:45 → 33:47","kural":"kök (بشر 2/2)","not":"Müjdeci rolü → 'müjdele' emri."},
 {"bag":"33:28 ↔ 33:49","kural":"nakarat3 (4 kelime)","not":"Faydalandırıp güzellikle salıverme formülü: Peygamber'in eşleri / mü'minlerin dokunulmadan boşanan eşleri."},
 {"bag":"33:8 · 33:29 · 33:35 · 33:44","kural":"lemma (a'adde, sûrede 4)","not":"Hazırladı: azap / ecir / mağfiret+ecir / kerîm ecir. Aynı kökten 'idde (33:49) say alanının tek açık doğru pozitifi."},
 {"bag":"33:37 · 33:38 · 33:50","kural":"kök (حرج 3/3)","not":"Güçlük olmasın: mü'minlere / Peygamber'e / sana."},
 {"bag":"33:5 · 33:24 · 33:50","kural":"nakarat3 (kâne'llâhu gafûran rahîmâ)","not":"Gafûr-rahîm çift mührü sûrede üçüncü kez."},
 {"bag":"33:50 ↔ 33:52","kural":"kök (حلل 2/2)","not":"Sana helâl kıldık / sana helâl değil — izin kümesi tanımlanıp kapanıyor; istisna ikisinde de 'mâ meleket yemînuk'."},
 {"bag":"33:33 ↔ 33:51","kural":"kök (قرر 2/2)","not":"Evlerinizde oturun / gözleri aydın olsun — aynı kök iki anlam."},
 {"bag":"33:51 ↔ 33:59","kural":"nakarat3 (zâlike ednâ en)","not":"Daha uygun: razı olmalarına / tanınıp incitilmemelerine."},
 {"bag":"33:27 · 33:40 · 33:52 · 33:54 · 33:55","kural":"kök (كلل/شيأ) + nakarat3","not":"'Her şey' formülü beş kez: kadîr · alîm · rakîb · alîm · şehîd. كلل ve شيأ 33:55'te tamamlanıyor."},
 {"bag":"33:37 → 33:54","kural":"kök (خفي 2/2, بدو 3/3)","not":"Tek olayda gizlemek-açığa çıkmak → genel kural: açığa vursanız da gizleseniz de."},
 {"bag":"33:50 ↔ 33:55","kural":"okuma gözlemi","not":"İki akrabalık listesi birbirini dışlıyor: 33:50 evlenilebilenler (amca/hala/dayı/teyze kızları) · 33:55 mahremler (baba/oğul/kardeş/yeğen)."},
 {"bag":"33:53 → 33:55","kural":"okuma gözlemi","not":"Perde kuralı / istisna kümesi (yedi kategori)."},
 {"bag":"33:43 ↔ 33:56","kural":"kök (صلو) + okuma gözlemi","not":"O ve melekleri size salât eder / Allah ve melekleri Peygamber'e salât eder — aynı iki özne, nesne değişiyor."},
 {"bag":"33:57 ↔ 33:58","kural":"okuma gözlemi (ellezîne yü'zûne ×2)","not":"Allah'ı ve Resûlü incitmek → lânet+azap / mü'minleri incitmek → bühtan ve günah yüklenmek."},
 {"bag":"33:48 · 33:53 · 33:57 · 33:58 · 33:59","kural":"kök (أذي 1-6/7)","not":"Eziyet ipliği: yedi geçişin altısı 33:48-59 arasında."},
 {"bag":"33:12 → 33:60","kural":"nakarat3 (5 kelime)","not":"Münafıklar ve kalbinde hastalık olanlar; üçüncü grup ekleniyor: mürcifûn."},
 {"bag":"33:13 ↔ 33:60","kural":"aktör (PN yer)","not":"Aynı şehir iki adla: Yesrib (münafıkların sözünde) / el-Medîne (Allah'ın sözünde)."},
 {"bag":"33:16 · 33:18 · 33:20 · 33:60","kural":"fâsıla TAM SAYIM","not":"qalîlâ sûrede 4/4 ile tamamlanıyor."},
 {"bag":"33:11 ↔ 33:61","kural":"okuma gözlemi (pas: 2/2 → 3/3)","not":"Failsiz edilgen dizisi: iki fiil ikisi edilgen / üç fiil üçü edilgen. İkisi de ★★★ tek kaynak pas."},
 {"bag":"33:23 ↔ 33:62","kural":"kök (بدل) + fâsıla tebdîlâ","not":"Sadıklar hiç değiştirmediler / Allah'ın sünnetinde değişme bulamazsın."},
 {"bag":"33:38 → 33:62","kural":"nakarat3 (7 kelime)","not":"Sünnetullah formülü ikinci kez; 33:62'de 'değişmez' cümlesiyle. esit2: 48:23 BENZER (okunmadı)."},
 {"bag":"33:8 · 33:14 · 33:15 · 33:20 · 33:53 · 33:63","kural":"kök (سأل 7/7)","not":"Sorgu ipliği: Allah'ın sorusuyla açılıyor, insanların saati sormasıyla kapanıyor."},
 {"bag":"33:8 · 33:29 · 33:35 · 33:44 · 33:57 · 33:64","kural":"lemma (a'adde 6/6)","not":"Üç iyi karşılık, üç kötü karşılık. say alanı altısını da sayı sayıyor."},
 {"bag":"33:17 ↔ 33:65","kural":"nakarat3 (veliyyen ve lâ nasîrâ)","not":"Aynı olumsuz formül; ikisi de çift yanlış mühür."},
 {"bag":"33:1 · 33:33 · 33:48 · 33:66 · 33:67 · 33:71","kural":"kök (طوع)","not":"İtaat ipliği: boyun eğme (1, 48) / itaat edin (33) / keşke itaat etseydik (66) / efendilere itaat ettik (67) / Allah'a itaat eden (71)."},
 {"bag":"33:2 · 33:67 · 33:68","kural":"eksen (Rab 3/3)","not":"Rab: vahyin kaynağı (33:2) / cehennemliklerin yakarışı (33:67, 33:68)."},
 {"bag":"33:4 ↔ 33:67","kural":"lemma (sebîl) + kök (ضلل)","not":"Allah yola iletir / büyükler yoldan saptırdı; fâsıla elifsiz / elifli."},
 {"bag":"33:30 · 33:68","kural":"kök (ضعف 1-3/3)","not":"Azabın iki katı: Peygamber'in hanımları için şart / saptıranlar için yakarış. say alanı ikisini de görmüyor."},
 {"bag":"33:7 → 33:69","kural":"aktör (Mûsâ)","not":"Peygamber listesindeki ad, sûrede ikinci kez bir örnek olarak."},
 {"bag":"33:66 ↔ 33:69","kural":"kök (وجه 2/2)","not":"Yüzleri ateşte çevrilenler / Allah katında vecîh."},
 {"bag":"33:48 · 33:53 · 33:57 · 33:58 · 33:59 · 33:69","kural":"kök (أذي 7/7)","not":"Eziyet ipliği Mûsâ örneğiyle kapanıyor."},
 {"bag":"33:32 ↔ 33:70","kural":"mm2 + okuma gözlemi","not":"Kavlen ma'rûfâ / kavlen sedîdâ — sözün iki niteliği; قول 21/21 33:70'te tamamlanıyor."},
 {"bag":"33:1 → 33:70","kural":"kök (وقي 1/5 → 5/5)","not":"Sakınma emri sûreyi açıyor (Peygamber'e) ve blokta kapanıyor (mü'minlere)."},
 {"bag":"33:1 · 33:48 · 33:66 · 33:67 · 33:71","kural":"kök (طوع 7/7)","not":"İtaat ipliği kapanıyor: boyun eğme yasağı → keşke itaat etseydik → efendilere itaat → Allah'a ve Resûlüne itaat eden büyük başarıya erdi."},
 {"bag":"33:33 ↔ 33:72","kural":"kök (جهل 2/2)","not":"İlk câhiliye / insan çok cahil."},
 {"bag":"33:43 ↔ 33:72","kural":"kök (ظلم 2/2)","not":"Karanlıklar / insan çok zalim."},
 {"bag":"33:58 ↔ 33:72","kural":"kök (حمل 3/3)","not":"Bühtanı yüklendiler / emaneti insan yüklendi."},
 {"bag":"33:24 → 33:73","kural":"okuma gözlemi (li- + azap + tevbe; توب 2/2)","not":"Münafıklara şartlı azap/tevbe → münafık ve müşriklere azap, mü'minlere tevbe; üç eril-dişil çift."},
 {"bag":"33:35 · 33:73","kural":"okuma gözlemi (eril-dişil çift listesi)","not":"On çiftlik sıfat listesi / üç çiftlik kapanış."},
 {"bag":"33:1 ↔ 33:73","kural":"mühür","not":"Sûre alîm-hakîm çift mührüyle açılıyor, gafûr-rahîm çift mührüyle kapanıyor."},
]}

pa = '/home/claude/repo/bulgular/aday_bulgular.json'
AD = json.load(open(pa, encoding='utf-8'))
AD.pop('AR_ahzab', None)
onceki = max(x['no'] for v in AD.values() if isinstance(v, list) for x in v if isinstance(x, dict) and 'no' in x)
nos = [x['no'] for x in AHZAB]
assert nos == list(range(onceki + 1, onceki + 1 + len(nos))), 'numara sırası kopuk: önceki %d, bu set %s' % (onceki, nos)
AD['AR_ahzab'] = AHZAB
json.dump(AD, open(pa, 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
tot = sum(len(v) for v in AD.values() if isinstance(v, list))
print('AR_ahzab', len(AHZAB), '(%d-%d) | toplam aday' % (nos[0], nos[-1]), tot)

pb = '/home/claude/repo/notlar/okuma_baglantilari.json'
BG = json.load(open(pb, encoding='utf-8'))
BG.update(BAGLAR)
json.dump(BG, open(pb, 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
print('okuma_baglantilari: AM_ahzab', len(BAGLAR['AM_ahzab']))
