# -*- coding: utf-8 -*-
"""aday_ekle_31_32.py — sûre 31 (Lokmân), sûre 32 (Secde) ve bu oturumun
ön-kayıtlı ölçüm turundan çıkan adaylar (959-978) + okuma bağları."""
import json

LOKMAN = [
{"no":959,
 "aday":"★★★ TARAYICI v4 SÛRE 31'DE İKİNCİ SIFIR ANMA — anma 0/3, kesinlik 0/7. Üç çıpanın üçü de kaçtı, verilen yedi adayın yedisi de yanlış pozitif.",
 "olculen":{"cipa":["31:10 (L2)","31:14 (L4, tartışmalı)","31:34 (L2, tartışmalı)"],
   "aday":["31:11","31:16","31:20","31:25","31:27","31:29","31:31"],
   "anma":"0/3","kesinlik":"0/7",
   "kacirma_sebebi":"31:10 amaç cümlesi أَن + muzârî ile (ta'lîl LÂMI yok); 31:14 ve 31:34 düz haber cümlesi",
   "yanlis_pozitif_sebebi":"işaret var ama olgu ÖRNEK/BENZETME (hardal tanesi, ağaç-kalem, deniz-mürekkep)",
   "dizi":{"27":"4/4","28":"3/3","29":"3/3","30":"2/9","31":"0/3"}},
 "durum":"ACIK","oncelik":"P0","kaynak":"sûre 31 okuması","etiket":"aday 948 birikimi",
 "test_notu":"Aday 948'in söz-eylemi varsayımına sûre 30'dan sonra İKİNCİ sûre boyu olumsuz veri. Ölçüt DEĞİŞTİRİLMEDİ (dondurma kararı). Karar tam okuma bitince verilecek."},
{"no":960,
 "aday":"★★ HAPAKS OTOMATİK ★★★ TETİKLEYİCİSİ ÜÇ YENİ VAKA — 31:18 (صعر), 31:32 (ختر), 32:16 (جفو). Üçünde de ★★★'ın TEK kaynağı hapaks z=3,28.",
 "olculen":{"vaka":["31:18","31:32","32:16"],"hapaks_z":3.28,
   "sure_31_ucyildiz":3,"bunlardan_hapaks":2,"sure_32_ucyildiz":1,"bunlardan_hapaks":1,
   "diger_kaynak":"31:26 allah z=3,47 (payda etkisi)"},
 "durum":"ACIK","oncelik":"P1","kaynak":"sûre 31-32 okuması","etiket":"borç #7",
 "test_notu":"Borç #7 (yıldızın iki otomatik ★★★ tetikleyicisi) iki sûrede üç yeni vaka aldı. **İçerikten gelen tek ★★★ yok.**"},
{"no":961,
 "aday":"★★★ ESMÂ MÜHRÜ İKİ AYRI HATA TÜRÜ ÜRETİYOR — mühürsüzlerde yanlış pozitif 8/10 (iki sûre).",
 "olculen":{"sure_31":{"token":24,"muhurlu":16,"muhurlu_gecerli":16,"muhursuz":8,"yanlis_pozitif":6},
   "sure_32":{"token":5,"muhurlu":3,"muhurlu_gecerli":3,"muhursuz":2,"yanlis_pozitif":2},
   "tur_A_ilahi_olmayan_sifat":["31:2 حَكِيم (Kitab)","31:4 آخِر (âhiret)","31:10 كَرِيم (çift)","31:11 مُبِين (dalâl)","31:31 شَكُور (insan)","31:32 بَرّ (KARA)","32:4 وَلِيّ","32:18 مُؤْمِن"],
   "tur_B_gercek_esma_ama_muhursuz":["31:23 عَلِيم","31:29 خَبِير"]},
 "durum":"ACIK","oncelik":"P0","kaynak":"sûre 31-32 okuması","etiket":"borç #9/#12",
 "test_notu":"Mühür ölçütü ayet sonunda ÇİFT arıyor; tekil gerçek esmâ mühürsüz kalıyor (tür B). Tür A ise token düzeyinde ilâhî olmayan sıfatları esmâ sayıyor. **İki hata türü ayrı ayrı onarım ister.**"},
{"no":962,
 "aday":"★★ KAFİYE KIRIĞI KURALI GEÇİŞ BÖLGESİNDE ÇİFT İŞARET KOYUYOR — 31:14 ve 31:15 alternasyonun iki yanı, ikisi de 'kırık' sayılıyor.",
 "olculen":{"kural":"iki komşu aynı fâsıla sınıfı + ayet farklı → kırık",
   "sure_31_kirik":[12,14,15,26],"gecis":"sûre ortasında N → R",
   "31_14":"R, iki N arasında","31_15":"N, iki R arasında",
   "yildiz_etkisi":"31:14'ün ★'ının TEK kaynağı kafiye kırığı"},
 "durum":"ACIK","oncelik":"P1","kaynak":"sûre 31 okuması","etiket":"yeni alan arızası",
 "test_notu":"Kural bir KIRILMA ile bir GEÇİŞ'i ayırt etmiyor: sûre baskın sınıfını değiştirirken her iki ayet de işaretleniyor. Korpus çapında sayım gerekiyor: kaç 'kırık' aslında geçiş bölgesinde?"},
{"no":963,
 "aday":"★★ ARDIŞIK İKİ SÛRE EKSENİN İKİ UCUNDA — sûre 31 A/R = 16,0 (32 lafız / 2 Rab), sûre 32 A/R = 0,1 (1 lafız / 10 Rab).",
 "olculen":{"dizi":{"27":2.25,"28":1.42,"29":8.4,"30":8.0,"31":16.0,"32":0.1},
   "ham":{"31":{"A":32,"R":2},"32":{"A":1,"R":10}},
   "not":"küçük paydalar oranı oynak kılıyor; ham sayı okunur"},
 "durum":"ACIK","oncelik":"P1","kaynak":"sûre 31-32 okuması","etiket":"sûreler arası dağılım",
 "test_notu":"Aday 932/936/957'nin beklediği korpus çapında A/R dağılımı hâlâ kurulmadı. **Bu iki sûre dizinin iki ucunu veriyor; tek başına bir iddia değil.** Sıralı 114 sûre dağılımı ve lafız payı A/(A+R) güven aralığıyla ölçülmeli."},
{"no":964,
 "aday":"DÜŞEN KAYIT — 31:9 merceğine 'sekiz kelimede İKİ lafız' yazıldı; defter TEK lafız veriyor (A=[4]).",
 "olculen":{"yazilan":"2 lafız","defter":"1 lafız","sebep":"ölçüm satırındaki [2/32] gösterimi lafız sayısı sanıldı"},
 "dusuruldu":"31:9 lafız sayısı — düzeltildi, mercek metni güncellendi",
 "durum":"KAPALI","oncelik":"P1","kaynak":"sûre 31 okuması","etiket":"hafızadan sayım (aday 843 ailesi)",
 "test_notu":"Hafızadan sayım kuralının bu oturumdaki ilk ihlali. **Blok bilançosu koşulurken yakalandı** — yani bilanço adımı kendi denetim işlevini gördü."},
{"no":965,
 "aday":"★★ ÇIPA KADEME ÖLÇÜTÜNÜN TANIM AÇIĞI — 'yeti sınırı' FİİL yetisi için mi, BİLGİ için de mi? 31:34 ve 32:17 bilgi sınırı koyuyor ('hiçbir nefis bilmez').",
 "olculen":{"vaka":["31:34 (yağmur + rahimler + 'hiçbir nefis bilmez')","32:17 ('hiçbir nefis bilmez')"],
   "L2_tanimi":"nedensel bağımlılık YA DA yeti sınırı",
   "31_14":"L4 adayı: ölçü var (iki yıl), mekanizma yok",
   "sure_27_28_L4":0},
 "durum":"KAPATILAMAZ","oncelik":"P0","kaynak":"sûre 31 okuması","etiket":"borç #14 (merdiven tanım açığı)",
 "test_notu":"Kademe kararı okumaya bağlı kaldığı sürece çıpa sayıları karşılaştırılabilir değil. **Tanım netleşene kadar 31:14 ve 31:34 TARTIŞMALI olarak kayıtlı.**"},
]

SECDE = [
{"no":966,
 "aday":"★★★ TARAYICI v4 SÛRE 32'DE TAM İSABET — anma 2/2, kesinlik 2/2. Sûre 30 (2/9) ve 31 (0/3) çöküşünden sonra tam tersi tablo.",
 "olculen":{"aday":["32:5 (F_ölçü)","32:27 (G_bakış)"],"ikisi_de_cipa":True,
   "dizi":{"27":"4/4","28":"3/3","29":"3/3","30":"2/9","31":"0/3","32":"2/2"},
   "kesinlik_dizi":{"30":"2/5","31":"0/7","32":"2/2"},
   "sebep":"sûre 32'nin iki olgu ayeti ölçü kelimesi (مِقْدَار) ve bakış sorusu (أَوَلَمْ يَرَوْا) taşıyor"},
 "durum":"ACIK","oncelik":"P0","kaynak":"sûre 32 okuması","etiket":"aday 948 birikimi",
 "test_notu":"**Tarayıcının başarısı ölçüte değil, sûrenin üslûbuna bağlı:** işaret taşıyan çıpaları buluyor, düz haber cümlesiyle kurulan çıpaları bulamıyor. Dört sûrelik tablo (30-31-32) bu okumayı destekliyor ama karar tam okuma sonuna bırakıldı."},
{"no":967,
 "aday":"★★★ MORFOLOJİ VERİ HATASI — 2:111, 2:135 ve 2:140'taki هُودًا ('Yahudi') PN Hûd (peygamber) olarak etiketlenmiş. Hûd anmasının 3/10'u yanlış.",
 "olculen":{"yanlis":["2:111","2:135","2:140"],"dogru_peygamber":["7:65","11:50","11:53","11:58","11:60","11:89","26:124"],
   "oran":0.30,"etkilenen":"pn_turleri.json ve adlı aktör alanları (adli, adli2) — KONTROL EDİLMEDİ"},
 "durum":"ACIK","oncelik":"P0","kaynak":"elçi kalıbı ön-kaydı (tasarım aşaması)","etiket":"kaynak veri hatası",
 "test_notu":"Hata tasarım sırasında yakalandı ve o testte düzeltildi, ama **korpus genelinde düzeltilmedi.** Adlı aktör sayımları etkilenmiş olabilir."},
{"no":968,
 "aday":"★★★ MORFOLOJİ İ'RÂB TUTARSIZLIĞI — etken خلق/فطر fiilinin HEMEN ardındaki ٱلسَّمَٰوَٰت (nesne konumu) 29 vakanın 9'unda ACC, 20'sinde GEN etiketli.",
 "olculen":{"nesne_konumu":{"ACC":9,"GEN":20},
   "korpus_samavat_FP":{"GEN":168,"ACC":13,"NOM":9},
   "FP_geneli":{"NOM":287,"ACC":387,"GEN":949},
   "sonuc":"ses-dişil çoğulun nasb hâli (kesra) cer ile karışıyor",
   "etkilenen":"defter `irab` alanı"},
 "durum":"ACIK","oncelik":"P0","kaynak":"خلق fiili ön-kaydı","etiket":"kaynak veri hatası",
 "test_notu":"**Nesne dağılımı ölçümü bu yüzden KAPATILAMAZ çıktı** (elle doğrulamada 5 hatanın 5'i de bu sebepten). Defterdeki i'râb temelli her sayım etkileniyor."},
{"no":969,
 "aday":"★★ KÖK TUZAĞI — 'gök' (سَماء) ve 'isim' (اِسْم, سَمَّى) morfolojide AYNI kökte (سمو). Kök düzeyindeki her gök sayımı isim kullanımlarını da içeriyor.",
 "olculen":{"ornek_sahte_eslesme":"3:36 (سَمَّيْتُهَا 'ona ad koydum') gök taramasına girdi",
   "cozum":"lemma düzeyinde süzme (LEM:سَماء)"},
 "durum":"ACIK","oncelik":"P1","kaynak":"gök kapısı dökümü","etiket":"sayım tuzağı",
 "test_notu":"Bu oturumun gök taramalarında sonuç etkilenmedi (elle ayıklandı), ama kök düzeyi süzme kullanan eski sayımlar kontrol edilmeli."},
{"no":970,
 "aday":"KAPSAM NOTU — LEM إِنسان, أُناس ve أَنَاسِيّ biçimlerini de içeriyor (6 token, MP). 'insân 71' sayısı bu 6'yı kapsıyor; tekil insân 65.",
 "olculen":{"toplam":71,"tekil":65,"MP":6,"ornek":["7:82","27:56"]},
 "durum":"ACIK","oncelik":"P2","kaynak":"insan üçlüsü ön-kaydı","etiket":"tanım açığı",
 "test_notu":"Etkisi küçük; insan üçlüsü sonuçları (belirlilik, hâl, nüzul, hitap) yeniden koşulmadı."},
{"no":971,
 "aday":"★★ EXP/RES ETİKETİ İSTİSNAYI GÜVENİLİR AYIRMIYOR — 70:22 ve 103:3 EXP, ama anlamca aynı işi yapan 11:11 RES etiketli.",
 "olculen":{"EXP":102,"RES":557,
   "istisna_ornekleri":{"70:22":"EXP","103:3":"EXP","11:11":"RES"},
   "sonuc":"etikete dayanan istisna sayımı 4 gerçek istisnadan birini kaçırırdı"},
 "durum":"ACIK","oncelik":"P1","kaynak":"sıfat istisnaları ön-kaydı","etiket":"etiket güvenilirliği",
 "test_notu":"İstisna taraması bu yüzden etiketten BAĞIMSIZ kuruldu ve bütün إِلّا adayları elle sınıflandı."},
{"no":972,
 "aday":"★★ KÖKSÜZ ÖZEL ADLAR `ikili` ALANINDA YAPISAL OLARAK GÖRÜNMEZ — 21:81 ve 34:12 aynı iki kelimeyle açılıyor (وَلِسُلَيْمَٰنَ ٱلرِّيحَ) ama üç bağ alanı da bu çifti yakalamıyor.",
 "olculen":{"cift":["21:81","34:12"],
   "esit2":"ayet benzerliği düşük","nakarat3":"alt sınır 3 kelime",
   "ikili":"iki kelimenin ikisinin de KÖKLÜ olmasını istiyor; Süleyman adının kökü yok",
   "korpus":"ikinci kelimesi ٱلرِّيحَ olan üç ayetten ikisi bunlar"},
 "durum":"ACIK","oncelik":"P1","kaynak":"Süleyman merceği","etiket":"alan açığı",
 "test_notu":"Özel adlar korpusta köksüz olduğu için ad taşıyan bütün kalıplar `ikili`de görünmez. Onarım: PN lemmasını kök yerine geçirmek."},
{"no":973,
 "aday":"★★★ BİRİM ONARIMI — kavram ve kişi merceklerinde sayım birimi TOKEN'dan AYET'e çevrildi; 'insân → وزر ×44,6' sonucu düştü.",
 "olculen":{"eski":"token sayımı","yeni":"kök bir ayette kaç kez geçerse geçsin 1",
   "dusen":"وزر: 7 tokenin 6'sı iki ayetten (39:7, 53:38, formül 3'er token); 7.si 75:11 eşsesli 'sığınak'",
   "kalan":{"INS_korpusa_karsi":["خلق ×5,3","مسس ×6,6","نطف ×22,1","شرر ×7,7 (yeni)"]},
   "tahmin":"4/4 tuttu"},
 "dusuruldu":"insân → وزر zenginleşmesi (kavram merceği ve insan üçlüsü turlarında)",
 "durum":"KAPALI","oncelik":"P0","kaynak":"ayet birimi ön-kaydı","etiket":"aday 926 dersinin tekrarı",
 "test_notu":"**Aday 926 (token değil ayet say) dersi iki tur sonra aynı biçimde tekrarlandı.** Birim artık ön-kayıtta açıkça yazılıyor."},
{"no":974,
 "aday":"★★ ELLE YAZILAN ARAPÇA DİZGELER KORPUSLA EŞLEŞMİYOR — dört vaka: أَيُّوب, مُحَمَّد (şedde/hareke sırası), dağ lemması (elle yazılan biçim korpusta yok; doğrusu جَبَل), 3:55 إِلَىَّ (regex kaçırdı).",
 "olculen":{"vaka":["أَيُّوب","مُحَمَّد","dağ lemması (elle yazım)","3:55 إِلَىَّ"],
   "cozum":"betiklere NFC doğrulama satırı konuldu; eşleşmeyen dizge koşuyu DURDURUYOR",
   "kazanc":"iki koşu hata vermeden önce durdu"},
 "durum":"KAPALI","oncelik":"P1","kaynak":"peygamber merceği + Necm dökümü","etiket":"aday 945 ailesi",
 "test_notu":"Bilinen hata ailesinin dördüncü tekrarı. **Doğrulama satırı çözüm oldu:** artık sessiz sıfır sonuç yerine koşu duruyor."},
{"no":975,
 "aday":"★★ OKUMA BİÇİMİ İHLALİ VE ONARIMI — 31:11'den 32:20'ye ölçüm satırı ELLE kısaltıldı, ▽ satırları verilmedi, ### başlıkları kullanılmadı.",
 "olculen":{"ihlal":["› satırı elle kısaltma (kural: ELLE YAZILMAZ)","▽ dikey satırların atlanması","### S:N başlıklarının kullanılmaması","blok sonu denetimlerinin atlanması"],
   "etkilenen_ayet":64,
   "onarim":"betikler/blok_goster.py — biçimi otomatik kuruyor (başlık, Arapça, meal, defterden ölçüm, mercek, JSON'dan dikey)",
   "kayit_etkisi":"YOK — metin dosyaları ve blok betikleri doğru üretti"},
 "durum":"KAPALI","oncelik":"P1","kaynak":"kullanıcı denetimi","etiket":"protokol ihlali",
 "test_notu":"**Hata sohbet çıktısındaydı, kayıtta değil.** Bundan sonra her blok blok_goster.py ile üretilir."},
{"no":976,
 "aday":"PROTOKOL ADIMININ KARŞILIĞI YOK — `dokum.py` depoda mevcut değil; 'ham ölçüm dökümü' adımı karşılıksız. Yerine oku_blok.py + olcum_bicim.py kullanıldı.",
 "olculen":{"aranan":"dokum.py","bulunan":"yok (dosya ve notlarda geçmiyor)","kullanilan":["oku_blok.py","olcum_bicim.py"]},
 "durum":"ACIK","oncelik":"P2","kaynak":"tur sonu","etiket":"protokol/depo tutarsızlığı",
 "test_notu":"Oturum promptundaki blok protokolü depoda karşılığı olmayan bir betiğe atıf yapıyor. Protokol metni güncellenmeli."},
]

ONKAYIT = [
{"no":977,
 "aday":"★★★ ÖN-KAYITLI ÖLÇÜM TURU BİLANÇOSU — on üç ön-kayıt, yetmiş tahmin: 54 tuttu (%77), 13 düştü, 3 kapatılamaz/değerlendirilemez.",
 "olculen":{"onkayitlar":["ALM pilotu","Süleyman merceği","Süleyman × Dâvûd","bütün peygamberler (özgül kökler)",
     "elçi kıssası kalıbı","kavram merceği (cennet/sâlih/insan)","insanın üç adı","ayet birimi düzeltmesi",
     "sıfatlar ve yaratılış sırası","sıfat istisnaları","sâlihât köprüsü","yıl sayıları → ışık yılı","dört yönlü düzen","göğe geçiş"],
   "tahmin":{"toplam":70,"tuttu":54,"dustu":13,"kapatilamaz":3},
   "en_ogretici_dusenler":[
     "peygamber merceği: en çok özgül kök Mûsâ'da DEĞİL (Îsâ, Âdem, İbrâhim önde)",
     "elçi kalıbı: beş elçi söz dağarcığı düzeyinde AYRI KÜME DEĞİL (p=0,21); kalıp birkaç formülden ibaret",
     "sâlihât köprüsü: köprü imana değil SÂLİH AMELE bağlı (%54'e %19)",
     "insan üçlüsü: beşer'in ayet sonu eğilimi kafiye artefaktı (4/4 sûre 74)"],
   "cerceve_duzeltmeleri":[
     "sâlihât köprüsü 'insânın kusurundan çıkış' DEĞİL: öncüllerin yalnız 6/33'ünde insân/nâs/beşer var; kökler كفر 16 · عذب 13 · ظلم 10",
     "göğe geçiş T4'ün kapsamı yalnız kapı/yol kelimeleri; رفع ile yükseltilenler (3:55, 4:158, 19:57) ayrı"]},
 "durum":"KAPALI","oncelik":"P0","kaynak":"ön-kayıtlı ölçüm turu","etiket":"tur bilançosu",
 "test_notu":"**Turun asıl kazancı düşen tahminler:** üçü çerçeve düzeltmesi getirdi, dördü artefakt yakaladı. Ön-kayıt + boş model disiplini, okuma sırasında bulunan örüntülerin taraflı örneklem tuzağına (aday 899) düşmesini engelledi."},
{"no":978,
 "aday":"★★ KORPUS BULGUSU — 'O'na yükseliş' aynı kalıpla iki farklı süre veriyor: iş 1.000 yıl (32:5), melekler ve Rûh 50.000 yıl (70:4). Ölçü kelimesi (مِقْدَار) korpusta üç ayette.",
 "olculen":{"mikdar_ayet":["13:8","32:5","70:4"],"olcu_kalibi":["22:47 (bin yıl)","32:5 (bin yıl)","70:4 (elli bin yıl)"],
   "yil_sayimi_araci":{"10:5":"ayın menzilleri → yılların sayısı","17:12":"gece-gündüz → yılların sayısı","2:189":"hilâller vakit ölçüsü","9:36":"on iki ay"},
   "isik_yili_testi":{"test_kumesi":9,"L1_eslesme":5,"beklenen_N1":2.56,"p_N1":0.080,"beklenen_N2":3.60,"p_N2":0.263,
     "L2_eslesme":3,"p":0.448,"sonuc":"rastgeleden ayırt edilemez"},
   "cerceve_duyarliligi":{"Dunya":"1,1 c","Gunes":"33 c","Galaksi":"252 c","CMB":"404 c"}},
 "durum":"ACIK","oncelik":"P2","kaynak":"32:5 ön-kayıtları","etiket":"metin yapısı + dış yorum testi",
 "test_notu":"**Metin içi yapı ölçülebilir ve sağlam:** süre yükselen şeye bağlı, ölçü 'sizin saydığınız' yıla bağlanmış, yıl sayımının aleti (ay ve güneş) korpusta tanımlı. **Dış çeviriler (mesafe, ışık hızı) testten geçmedi** ve referans çerçevesine göre 400 kat değişiyor."},
]

pa = '/home/claude/repo/bulgular/aday_bulgular.json'
AD = json.load(open(pa, encoding='utf-8'))
AD['AO_lokman'] = LOKMAN
AD['AP_secde'] = SECDE
AD['AQ_onkayit'] = ONKAYIT
json.dump(AD, open(pa, 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
tot = sum(len(v) for v in AD.values() if isinstance(v, list))
print('AO_lokman', len(LOKMAN), '| AP_secde', len(SECDE), '| AQ_onkayit', len(ONKAYIT), '| toplam aday', tot)

BAGLAR = {
 "AK_lokman": [
  {"bag":"31:1 ↔ 2:1 · 3:1 · 29:1 · 30:1 · 32:1","kural":"esit2 TAM",
   "not":"Altı ALM açılışı. Bu oturumun ön-kayıtlı ALM pilotunda ayet başı ve kelime başı dizilişi rastgeleden ayırt EDİLEMEDİ (Ö3 p=0,58 · Ö4 p=0,33); dizilişe dair iddia kurulmaz."},
  {"bag":"31:4 → 27:3 (TAM) · 31:5 → 2:5 (TAM)","kural":"esit2",
   "not":"**Lokmân'ın açılışı Neml ve Bakara açılışlarının tanım cümlelerini art arda taşıyor.**"},
  {"bag":"31:12 → 27:40","kural":"okuma gözlemi",
   "not":"'Kim şükrederse kendisi için şükreder' yapısı Süleyman'ın sözüyle aynı (doğrulandı). شكر, Süleyman merceğinde üç sahneli köklerden biriydi."},
  {"bag":"31:26 → 22:64 (BENZER) · 31:30 → 22:62 (YAKIN 0,98)","kural":"esit2",
   "not":"**Sûre 31'in bağ hedeflerinde Hac başta: 12 bağ.** Kapanışa yakın bölüm Hac 22:61-65 dizisiyle örtüşüyor."},
  {"bag":"31:8 (sâlihât köprüsü)","kural":"ölçüm bağı",
   "not":"33 köprü çapasından biri: öncül 31:6-7'de azap, ardılda cennetler. Blok yapıyı birebir taşıyor."},
 ],
 "AL_secde": [
  {"bag":"32:4 → 7:54, 10:3, 25:59, 57:4","kural":"yaratılış sırası grafiği",
   "not":"'Altı günde yaratma → SONRA Arş'a istivâ' kalıbını taşıyan beş ayetten biri. Kenar gök-yer arasında DEĞİL, yaratılış ile istivâ arasında."},
  {"bag":"32:7 → 32:8 → 32:9","kural":"yaratılış sırası grafiği",
   "not":"**Grafiğin üç kenarının kaynağı bu ayet zinciri:** طِين → سُلالَة (32:7-8) ve سُلالَة → سَوَّى/نَفَخَ (32:8-9). Tesviye ve nefh HER ZAMAN maddeden sonra (15:28-29, 32:7-9, 38:71-72)."},
  {"bag":"32:19 → 53:15","kural":"TAM SAYIM (me'vâ + cennet 4 ayet: 5:72, 32:19, 53:15, 79:41)",
   "not":"Necm'de sidrenin yanındaki Me'vâ cenneti, burada iman + sâlih amelin karşılığı. 32:19 ayrıca bir köprü çapası."},
  {"bag":"32:23 → 17:2","kural":"xref",
   "not":"Mûsâ'ya Kitap ve İsrâiloğullarına hidayet. 17:1 (gece yolculuğu) bu oturumda ayrıca incelendi; 17:2 onun hemen ardılı."},
  {"bag":"32:16 → 7:56","kural":"TAM SAYIM (دعو + خوف + طمع: yalnız iki ayet)",
   "not":"'Korku ve umutla dua'. 7:56 'Allah'ın rahmeti muhsinlere YAKINDIR' ile sürüyor — dua taramasındaki yakınlık hattı (2:186, 40:60)."},
  {"bag":"32:26 → 20:128 (BENZER 0,88)","kural":"esit2",
   "not":"'İşitmiyorlar mı' (32:26) ve 'görmüyorlar mı' (32:27): 32:9'da verilen yetiler sûrenin kapanışında soruya dönüşüyor."},
 ],
}
pb = '/home/claude/repo/notlar/okuma_baglantilari.json'
BG = json.load(open(pb, encoding='utf-8'))
BG.update(BAGLAR)
json.dump(BG, open(pb, 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
print('okuma_baglantilari: AK_lokman', len(BAGLAR['AK_lokman']), '| AL_secde', len(BAGLAR['AL_secde']))
