# -*- coding: utf-8 -*-
"""aday_ekle_onarim_02.py — ONARIM TURU 2 (889-896)."""
import json
ADAYLAR = [
{"no":889,
 "aday":"★ VERİ KİRLİLİĞİNİN TAM TABLOSU VE `harf` ONARIMI (aday 879 genişletildi). Birebir aynı iki ayet (39:1 / 45:2) üzerinden ölçüldü. KİRLİ: harf (+19) · fHz (−20) · sesli (−2) · ebced (+786) · mod19 (+7) · bits. TEMİZ: ar_saf · mora · ritim_kod · fasila_tipi · med_yuku_waqf · p0110 · mukattaa. Kirlilik 112 ayette.",
 "olculen":{"etkilenen_ayet":112,
   "kirli":["harf","fHz","sesli","ebced","mod19","bits"],
   "temiz":["ar_saf","mora","ritim_kod","fasila_tipi","med_yuku_waqf","p0110","mukattaa"],
   "deftere_giren_kirli_alan":["harf"],
   "harf_kullanan_betikler":["dis_sinav.py","genelleme.py","oku_blok.py"]},
 "durum":"ACIK","oncelik":"P0","kaynak":"onarım turu 2",
 "etiket":"onarım sırasında ölçüldü",
 "test_notu":"**`harf` dis_sinav.py ve genelleme.py'de İSTATİSTİĞE giriyor** — o betiklerin sonuçları 112 ayet için kirli girdiyle üretilmiş. **fHz, sesli, ebced, mod19, bits BU PROJEDE kullanılmıyor ama kardeş projenin (fonetik analiz) çekirdek alanları; orada denetlenmeli — bu, projeler arası bir borç.**"},
{"no":890,
 "aday":"`harf`İN TANIMI GERİ ÇIKARILAMADI — ALAN YENİDEN HESAPLANAMAZ, YALNIZ BESMELE KATKISI ÇIKARILABİLDİ. kuran_veri.json'un üreteci depoda YOK. Düz Arapça harf sayımı `harf`i üretmiyor: temiz 6124 ayette r=0,99915 ama **ortalama +2,94 (std 3,01) sabit bir fazla** var (hançer elif / hemze kürsüsü gibi işaretler de sayılıyor olmalı).",
 "olculen":{"r":0.99915,"ortalama_sapma":2.94,"sapma_std":3.01,
   "uretec_depoda":False,
   "onarim":"gömülü ayetlerde harf2 = harf − 19 (19 = 1:1'in kendi harf değeri)",
   "dogrulama":{"gomulu_sapma_once":{"ort":20.44,"std":2.78,"z":5.81},
     "gomulu_sapma_sonra":{"ort":1.44,"std":2.78,"z":-0.50}},
   "27:1":{"eski":46,"yeni":27},"alan_adi":"harf2"},
 "durum":"ACIK","oncelik":"P0","kaynak":"onarım turu 2",
 "etiket":"onarım",
 "test_notu":"**Doğrulama güçlü: düzeltmeden sonra 112 ayetin sapması temiz dağılımın içine düşüyor (z 5,81 → −0,50).** Ama **alanın kuralı hâlâ bilinmiyor ve bu, tek başına ciddi bir borç: kullanımda olan, istatistiğe giren, tanımı belgelenmemiş bir alan.** KAPATILAMAZ — üreteç bulunana kadar `harf`in ne saydığı bilinmiyor; ortalama +2,94'lük fazlanın kaynağı doğrulanmadı."},
{"no":891,
 "aday":"★ ADAY 781'İN KONTROLLÜ ÇİFTİ HESAPLANDI — VE OKUMANIN 'SÛRE 26 NAKARATLI / SÛRE 27 NAKARATSIZ' İKİLİSİ DÜŞTÜ. Onarılmış nakarat2 ile: nakaratlı ayet oranı sûre 26'da %27,3, sûre 27'de %32,3 — **neredeyse eşit.** Fark PRESENCE'ta değil TÜR ve AĞIRLIK'ta: sûre 26'da TAM AYET nakaratı 34, sûre 27'de 0; nakaratın kelime payı %23,1'e %8,7 (2,7 kat).",
 "olculen":{"sure_26":{"ayet":227,"nakaratli":62,"oran":0.273,"tam":34,"ic":28,
     "kalip":18,"guclu_kalip":9,"kelime_orani":0.231},
   "sure_27":{"ayet":93,"nakaratli":30,"oran":0.323,"tam":0,"ic":30,
     "kalip":17,"guclu_kalip":2,"kelime_orani":0.087},
   "sure_26_en_uzun_kalip":"11 kelime, 5 ayet",
   "sure_27_en_uzun_guclu":"3 kelime, 5 ayet"},
 "durum":"KAPALI","oncelik":"P0","kaynak":"onarım turu 2",
 "etiket":"onarım sonrası ölçüm",
 "test_notu":"**Okuma boyunca 'sûre 26 nakaratlı, sûre 27 nakaratsız' diye yazdım; bu ikili YANLIŞ.** Doğrusu: **her iki sûrede de ayetlerin üçte biri bir nakarat kalıbına değiyor; sûre 26'nın nakaratları TAM AYET ve UZUN (11 kelimeye kadar), sûre 27'ninkiler AYET-İÇİ ve KISA (3 kelime).** Ayrım ikili değil, iki boyutlu: birim (ayet/ayet-içi) ve ağırlık (kelime payı). **Beşinci düşen kayıt** (801, 819, 843, 883, burası)."},
{"no":892,
 "aday":"★★★ SÛRE 26'NIN 41 ★★★'ININ 16'SI İKİ NAKARATIN SEKİZER TEKRARI — VE HER KÜMEDE KAYNAK TEK. `inne rabbeke le-hüve'l-azîzu'r-rahîm` sekiz ayette ★★★ ve sekizinde de tek kaynak `rab`. `fe'ttekû'llâhe ve etîûn` sekiz ayette ★★★ ve sekizinde de tek kaynak `allah`. Kalan 25 ★★★ nakaratsız ayetlerde ve kaynakları karışık.",
 "olculen":{"sure_26_yildiz3":41,
   "nakarat_kumeleri":[{"kalip":"inne rabbeke le-hüve'l-azîzu'r-rahîm","ayet":8,"kaynak":"rab","farkli_kaynak":1},
     {"kalip":"fe'ttekû'llâhe ve etîûn","ayet":8,"kaynak":"allah","farkli_kaynak":1}],
   "nakaratsiz_yildiz3":25,
   "nakaratsiz_kaynaklar":{"rab":13,"pas":6,"hapaks":4,"rab+hapaks":1,"hapaks+pas":1},
   "nakarat_duzeltmeli_yildiz3":27,
   "oran_once":0.181,"oran_sonra":0.119,
   "sure_27_yildiz3":9,"sure_27_nakaratli_yildiz3":2,"sure_27_duzeltme":0,
   "sure_27_oran":0.097},
 "durum":"KAPALI","oncelik":"P0","kaynak":"onarım turu 2",
 "etiket":"onarım sonrası ölçüm",
 "test_notu":"**Aday 700/739/771'in nakarat düzeltmesi artık SAYISAL: sûre 26'nın 41 ★★★'ı, 27 AYRI YAPIya iner** (41 − 16 + 2). Oran %18,1 → **%11,9.** Sûre 27'de düzeltme gerekmiyor (dokuz ★★★'ın ikisi nakaratlı ama kaynakları ayrı hapakslar), oran %9,7. **KONTROLLÜ ÇİFTİN SONUCU: 26 ile 27 arasındaki ★★★ farkı %18,1'e %9,7 değil, %11,9'a %9,7 — aradaki uçurum büyük ölçüde NAKARAT TEKRARINDAN geliyordu.** Aday 779 ve 781 bu sayıyla güncellenmeli."},
{"no":893,
 "aday":"`esit`E ÜÇÜNCÜ KADEME: 'benzer' (0,85-0,95). 0,80-0,95 bandında 217 çift var ve bandın üstü açıkça gerçek: 27:74 ↔ 28:69 (0,945) · 23:83 ↔ 27:68 (0,935) · 82:17 ↔ 82:18 (0,944, ARDIŞIK ayetler). Alan üç kademeli oldu: tam (1622 bağ) · yakin (84) · benzer (280). Ayet 253 → 520, kayıp 0.",
 "olculen":{"esik":0.85,"kademe":{"tam":1622,"yakin":84,"benzer":280},
   "ayet_eski":253,"ayet_yeni":520,"kayip":0,
   "band_0.80_0.95":217,
   "sure_27_esit2":[3,53,55,56,57,58,68,69,71,74,80,81],
   "bagimsiz_dogrulama":["27:74↔28:69 okumada xref ile bulunmuştu",
     "23:83↔27:68 okumada xref ile bulunmuştu"]},
 "durum":"ACIK","oncelik":"P1","kaynak":"onarım turu 2",
 "etiket":"onarım",
 "test_notu":"**Bağımsız doğrulama: 'benzer' kademesinin iki vakası okuma sırasında XREF ile zaten bulunmuştu** (27:74↔28:69 ve 27:68↔23:83) — yani kademe gerçek bağları yakalıyor. **KAPATILAMAZ: 0,85 eşiği örneklemeyle doğrulanmadı; 0,85-0,88 aralığının paraphrase mı yoksa ortak formül mü olduğu denetlenmedi.** Sûre 27'de esit dolu ayet 3 → 12."},
{"no":894,
 "aday":"SÛRE 27'DE `esit2` DOKUZ YENİ AYET AÇTI — OKUMADA GÖRÜLMEYEN BAĞLAR. Eski alan [3, 58, 71] veriyordu; yeni alan [3, 53, 55, 56, 57, 58, 68, 69, 71, 74, 80, 81]. Yeni bağların bir kısmı okumada xref ile görülmüştü (27:68↔23:83, 27:74↔28:69), bir kısmı hiç görülmedi (27:53↔41:18, 27:55, 27:56, 27:57, 27:69).",
 "olculen":{"eski":[3,58,71],"yeni":[3,53,55,56,57,58,68,69,71,74,80,81],
   "okumada_xrefle_gorulen":["27:68↔23:83","27:74↔28:69","27:80↔30:52","27:81↔30:53"],
   "okumada_hic_gorulmeyen":["27:53↔41:18","27:55","27:56","27:57","27:69"]},
 "durum":"ACIK","oncelik":"P1","kaynak":"onarım turu 2",
 "etiket":"onarım sonrası ölçüm",
 "test_notu":"**Lût bölütünün (27:54-58) neredeyse tamamı artık başka sûrelerdeki paralel anlatımlarla eşleşiyor** — okumada bunu yalnız xref üzerinden ve tek tek görmüştüm. **`esit2` bu bölütün korpusta üç sûrede anlatıldığını tek bakışta gösteriyor; aday 840'ın 'xref yoğunluğu ortak SAHNE ölçüyor' bulgusunun doğrudan doğrulaması.**"},
{"no":895,
 "aday":"ONARIM TURU 2 BİLANÇOSU. Üç iş: (1) veri kirliliğinin tam tablosu ve `harf` onarımı — ama tanım geri çıkarılamadı; (2) aday 781'in kontrollü çifti nihayet hesaplandı ve okumanın ikilisi düştü; (3) `esit`e üçüncü kademe. Toplam onarım (iki tur): on.",
 "olculen":{"tur_2_onarim":3,"toplam_onarim":10,
   "kapanan_aday":[781,870,891,892],
   "yeni_alanlar_tur2":["harf2","esit2 üçüncü kademe"],
   "kalan_borc":["harf tanımı bilinmiyor","fHz/sesli/ebced/mod19/bits kardeş projede kirli",
     "esit 0,85 eşiği örneklemeyle doğrulanmadı",
     "esit'in yedi eşik türü hâlâ yazılmadı (P0 #3)",
     "çıpa tanımı hâlâ yazılmadı (P0 #6)"]},
 "durum":"KAPALI","oncelik":"P2","kaynak":"onarım turu 2",
 "etiket":"onarım bilançosu",
 "test_notu":"**Turun asıl kazancı ölçüm değil, bir İDDİANIN DÜŞMESİ: okuma boyunca kurulan 'sûre 26 nakaratlı / sûre 27 nakaratsız' karşıtlığı yanlıştı ve bu karşıtlık üzerine kurulan bütün karşılaştırmalar (aday 779, 781, 829, 834, 839) yeniden yazılmalı.** **Beşinci düşen kayıt ve en pahalısı: bu, bir blokta değil, altı blok boyunca tekrarlanan bir çerçeveydi.** Ders: **okuma sırasında kurulan İKİLİ KARŞITLIKLAR (X'li / X'siz) ölçülmeden kullanılmamalı; ölçüldüğünde çoğu iki boyuta ayrışıyor.**"},
]
pa='/home/claude/repo/bulgular/aday_bulgular.json'
AD=json.load(open(pa,encoding='utf-8'))
AD['AI_onarim'].extend(ADAYLAR)
json.dump(AD,open(pa,'w',encoding='utf-8'),ensure_ascii=False,indent=1)
print('AI_onarim →',len(AD['AI_onarim']),'| son no',AD['AI_onarim'][-1]['no'])
