# -*- coding: utf-8 -*-
"""aday_ekle_27_41_50.py — blok 27:41-50 adayları (822-832) ve bağları."""
import json

ADAYLAR = [
{"no":822,
 "aday":"27:50 — KORPUSUN İKİNCİ EN YÜKSEK TEK-KÖK YOĞUNLUĞU. n=7'lik ayette مكر *(tuzak)* DÖRT kez; oran 0,57. Daha yüksek tek vaka 53:38 (3/5 = 0,60) ama mutlak sayıda 27:50 önde. Yapı simetrik: iki kez onlar, iki kez biz.",
 "olculen":{"ayet":"27:50","kok":"مكر","tekrar":4,"n":7,"oran":0.571,
   "korpus_en_yuksek_oran":{"ayet":"53:38","tekrar":3,"n":5,"oran":0.60},
   "mutlak_en_yuksek":{"ayet":"24:61","tekrar":10,"n":76,"oran":0.13}},
 "durum":"KAPALI","oncelik":"P2","kaynak":"okuma blok 27:41-50",
 "etiket":"ararken bulundu (tam korpus sayımı koşuldu)",
 "test_notu":"`ikile` çalışan alan; tam sayım koşuldu. **Blokta üç kez aynı yapı: kök sabit, konum sabit, özne ya da muhatap karşıt** — 27:36 (أتي, muhatap değişiyor), 27:43 (صدد, fâil değişiyor), 27:50 (مكر, özne değişiyor). Bu yapı `esit`in hiçbir eşiğine takılmıyor; **'tek ayet içi özne-karşıtlığı' dokuzuncu eşik türü adayı** (aday 812'nin sekizincisiyle birlikte)."},
{"no":823,
 "aday":"طير SÛRE 27'DE İKİ ANLAM ALANINDA — 529 KÜMESİNİN ÜÇÜNCÜ SÛRE İÇİ VAKASI VE EN KESKİNİ. 27:16, 27:17, 27:20'de 'kuş' (canlı); 27:47'de ٱطَّيَّرْنَا / طَٰٓئِرُكُمْ, yani 'uğursuzluk, fal'. Aynı kök, aynı sûre, yirmi yedi ayet arayla. Dikey satırı yalnız 'kuş' anlamından geliyor (şekil-biçim ×474,2 · طين ×59,3 · dağ ×18,2).",
 "olculen":{"kok":"طير","n":29,"sure_ici":[16,17,20,47],
   "anlamlar":{"kuş":[16,17,20],"uğur/fal":[47]},
   "dikey_ortaklar":["هيأ","طين","جبل"],"otomatik_olcut_calisti":False,
   "mesafe":27},
 "durum":"ACIK","oncelik":"P0","kaynak":"okuma blok 27:41-50",
 "etiket":"okuma sırasında ölçüldü",
 "test_notu":"**Otomatik tespit ölçütü YEDİNCİ vakada da çalışmadı → 2/7.** Ve bu vaka ölçütün neden kör olduğunu netleştiriyor: **azınlık anlamı burada korpusta seyrek DEĞİL** (27:47 dışında 7:131, 17:13, 36:19 gibi 'uğur' geçişleri var). Ölçüt sıklık yüzünden değil, **birlikte geçen köklerin anlam alanını hiç kullanmadığı için** kör. Sûre 27'de üç 529 vakası: سمو (aday 808), هدي (aday 814, ÜÇ anlam alanı — 27:41 ile 'tanıma' eklendi), طير. **Tek sûrede üç vaka; 529 kümesi seyrek bir arıza değil.**"},
{"no":824,
 "aday":"ADAY 806'NIN ÖLÇÜTÜ BEŞ YENİ VAKADA SINANDI VE SÛRE 27'NİN ÜÇ UYARI VAKASINI AÇIKLADI. Ölçüt: yüksek kat, hedef kökün değil ORTAK kökün seyrekliğinden ve katkı veren AYRI AYET sayısının azlığından gelir. Bu blokta ölçülen beş vakanın beşinde de ortak kök n≤4 ve ayrı ayet ≤2.",
 "olculen":{"yeni_vakalar":[
   {"hedef":"تسع","n":7,"ortak":"نعج","n_ortak":4,"kat":948.5,"ayri_ayet":1,"kaynak":["38:23"]},
   {"hedef":"طير","n":29,"ortak":"هيأ","n_ortak":4,"kat":474.2,"ayri_ayet":2,"kaynak":["3:49","5:110"]},
   {"hedef":"سوق","n":17,"ortak":"لفف","n_ortak":3,"kat":389.7,"ayri_ayet":1,"kaynak":["75:29"]},
   {"hedef":"بيت","n":73,"ortak":"عنكب","n_ortak":2,"kat":147.0,"ayri_ayet":1,"kaynak":["29:41"]},
   {"hedef":"مرد","n":5,"ortak":"شطن","n_ortak":88,"kat":45.1,"ayri_ayet":3,"kaynak":["4:117","22:3","37:7"]}],
  "sure_27_uyari_vakalari_cozuldu":[
   {"hedef":"تسع","ortak":"نعج","kat":948.5,"ayri_ayet":1},
   {"hedef":"ودي","ortak":"نمل","kat":534.8,"ayri_ayet":1,"kaynak":["27:18"]},
   {"hedef":"نمل","ortak":"ودي","kat":520.0,"ayri_ayet":1,"kaynak":["27:18"]}],
  "n25_korumasinin_kacirdigi":["بيت (n=73)","طير (n=29)","عظم (n=128)","سجد (n=92)","مرأ (n=38)","عرش (n=33)"]},
 "durum":"ACIK","oncelik":"P0","kaynak":"okuma blok 27:41-50",
 "etiket":"okuma sırasında ölçüldü (dikey satır denetlenirken)",
 "test_notu":"**Toplam ölçülen vaka on iki oldu ve ölçüt on ikisinde de ayırıyor.** En güçlü kanıt: **sûre 27'nin ÜÇ uyarı vakasının üçü de TEK ayetten geliyor** (38:23 doksan dokuz koyun; 27:18 karınca vadisi ×2) — yani 'aynı sahne' gerçekten tek sahne. Karşı örnek olarak şمس▸قمر ×129,3 yirmi bir ayrı ayetten geliyor ve artefakt değil. **Mevcut n≤25 koruması on iki vakanın altısını kaçırıyor.** ÖN-KAYIT ayakta: ayrı ayet ≤2 → yorumlanmaz; 3-5 → uyarı; >5 → serbest. TUR SONU'nda sûre 26'nın dokuz vakası bu eşikle yeniden etiketlenecek."},
{"no":825,
 "aday":"27:49 — SÛRENİN TEK YEMİNİ VE BİR SUİKAST YEMİNİ. Korpusta 71 QASEM ayeti var; sûre 27'de yalnız 27:49. Yemin edenler bir peygamberi ve ailesini geceleyin öldürmeye ant içiyor ve bunu بِٱللَّهِ diyerek yapıyor. Ayette EMPH 5 — sûrenin ikinci en tekitli ayeti (27:21'de altı).",
 "olculen":{"ayet":"27:49","fig":"QASEM","korpus_qasem_ayet":71,
   "sure_27_qasem":["27:49"],"EMPH":5,"n":14,
   "sure_en_tekitli":[["27:21",6],["27:49",5],["27:37",4]],
   "allah_lafzi_konumu":3,"yemin_edenler":"dokuz kişilik grup (27:48)"},
 "durum":"ACIK","oncelik":"P1","kaynak":"okuma blok 27:41-50",
 "etiket":"okuma sırasında ölçüldü",
 "test_notu":"**QASEM alanının bilinen eksiği taggerin eksikliği (P0 #6).** Bu vaka alanın DOĞRU çalıştığı bir örnek: تَقَاسَمُوا۟ بِٱللَّهِ açık bir yemin formülü ve alan yakaladı. **Ama asıl soru gönderge sınıfı: 71 QASEM'in kaçı olumlu bir ağızda, kaçı olumsuz bir ağızda?** Bu sûrede tek yemin ve olumsuz ağızda. **KAPATILAMAZ — korpus çapında QASEM konuşmacı sınıflandırması koşulmadı.** TUR SONU: QASEM tagger yazılırken 'yemin eden kim' alanı da üretilecek."},
{"no":826,
 "aday":"ADAY 818'İN ÖN-KAYDI İLK KEZ SINANDI — 27:49 وَلِيّ ARTEFAKT ÇIKTI, AYRIM BOZULMADI. Ön-kayıt: sûrenin kalan sekiz mühürsüz esmâ tokeninden en az biri GEÇERLİ çıkacak ve mühür bayrağının kusursuz ayrımı bozulacak. Birinci sınama: 27:49 وَلِيّ, gönderge لِوَلِيِّهِۦ (Sâlih'in kan yakını), İNSAN TEKİL, ARTEFAKT.",
 "olculen":{"sinama_no":1,"ayet":"27:49","esma":"وَلِيّ","gonderge":"insan tekil (Sâlih'in velisi)",
   "gecerli":False,"muhursuz_token_toplam":14,"muhursuz_gecerli":0,
   "muhur_token_toplam":10,"muhur_gecerli":10,
   "kalan_sinama":["27:59 سَلام","27:63 بَرّ","27:66 آخِر","27:75 مُبِين","27:77 مُؤْمِن","27:79 مُبِين","27:88 خَبِير"]},
 "durum":"ACIK","oncelik":"P0","kaynak":"okuma blok 27:41-50",
 "etiket":"ön-kayıt sınaması",
 "test_notu":"**Ayrım 24/24'e çıktı: mühür tokeninde 10/10 geçerli, mühürsüz tokende 0/14 geçerli.** Ön-kayıt hâlâ ayakta (sekiz sınamanın biri geçti). **Gönderge sınıfları envanterine sekizinci vaka türü eklenmiyor — 'insan tekil' sınıfı zaten vardı (27:2, 27:15).** Not: وَلِيّ korpusta ilâhî gönderge ile de geçen bir lemma; **bu, alanın lemma seviyesinde ayırt edilemeyeceğinin kanıtı — bağlam denetimi şart** (aday 816 ile aynı sonuç)."},
{"no":827,
 "aday":"27:44 — SÛRENİN EN YOĞUN EKSEN AYETİ, EKSENDEN YILDIZ ALMIYOR. Lafız bir kez (26. sırada), رَبّ İKİ kez (19. ve 27. sırada); sûrede iki Rab taşıyan ilk ayet. Yıldız ★ ve kaynağı YALNIZ uzunluk (n z=1,65); allah z=0,19 ve rab z=1,20 eşiği aşmıyor.",
 "olculen":{"ayet":"27:44","A":[26],"R":[[19,"رَبّ"],[27,"رَبّ"]],"rab_sayisi":2,
   "z":{"n":1.65,"allah":0.19,"rab":1.20},"yildiz":1,"yildiz_kaynak":"uzunluk",
   "sure_lafiz_rab_bulusan":["27:8","27:26","27:44"],
   "rab_kipleri":["seslenme (رَبِّ)","tamlama (رَبِّ ٱلْعَٰلَمِينَ)"],"ikisi_de_bagli":True},
 "durum":"ACIK","oncelik":"P1","kaynak":"okuma blok 27:41-50",
 "etiket":"okuma sırasında ölçüldü",
 "test_notu":"**z ölçütünün yapısal sonucu: eksen yoğunluğu UZUNLUKLA seyreltiliyor.** allah z ve rab z, eksen işaretinin ayet içindeki KONUMUNA ve ayetin uzunluğuna göre hesaplandığı için n=28'lik bir ayette üç eksen işareti bile eşiği aşmıyor; n=8'lik 27:26'da iki işaret ★★ üretmişti. **Bu, yıldız alanının uzun ayetlerde eksen körü olduğu anlamına gelir.** TUR SONU: z hesabında uzunluk normalizasyonu denetlenecek — aday 599/602'nin 'yıldız içeriği ölçmüyor' bulgusuna yapısal bir mekanizma daha."},
{"no":828,
 "aday":"27:43-49 — SÛRE 27'NİN İLK EKSEN KÜMESİ. Yedi ayetin ALTISINDA Allah lafzı (27:43, 44, 45, 46, 47, 49). Sûrenin ilk kırk iki ayetinde toplam sekiz lafız vardı; burada yedi ayette altı. Semûd bölütünün açılışıyla çakışıyor.",
 "olculen":{"pencere":"27:43-49","lafiz":6,"ayet":7,
   "sure_ilk_42_lafiz":8,"sure_toplam_lafiz":25,
   "okunan_korpusta_7lik_pencere_azami":7,
   "7over7_goruldugu_sureler":[24],
   "sure_27_kendi_azamisi":{"pencere":"27:59-65","deger":7,"okundu":False},
   "anlati_bolutleri":{"Mûsâ":"27:7-14","Dâvûd-Süleymân":"27:15-44","Semûd":"27:45-53"}},
 "durum":"ACIK","oncelik":"P1","kaynak":"okuma blok 27:41-50",
 "etiket":"ararken bulundu (okunan korpus pencere taraması koşuldu)",
 "test_notu":"Aday 807 üç ardışık lafız dizisini kaydetmişti; **bu onun büyük ölçekli biçimi ve yine bir anlatı bölütü sınırında.** KAPATILAMAZ — pencere taraması yalnız okunan sûrelerde koşuldu. **TUR SONU: eksen kümelerinin anlatı bölütü sınırlarıyla çakışması korpus çapında sınanacak; konum-eşli null gerekir (aday 435).** Not: sûre 27'nin kendi azamisi 27:59-65'te ve okunmadı; **bölüt sınırı hipotezi orada da sınanacak.**"},
{"no":829,
 "aday":"27:48 ↔ 26:152 — İKİ SÛRENİN SEMÛD BÖLÜTÜNDE BİREBİR AYNI FORMÜL. xref: أفسد + أرض + أصلح. 27:48 'يُفْسِدُونَ فِى ٱلْأَرْضِ وَلَا يُصْلِحُونَ'; 26:152 aynı terkip. İki sûre, aynı kavim, aynı formül.",
 "olculen":{"bag":"27:48 ↔ 26:152","xref":"أفسد أرض أصلح",
   "sure_26_semud":"26:141-159","sure_27_semud":"27:45-53",
   "27:48_karsit_cift":["فسد","صلح"]},
 "durum":"ACIK","oncelik":"P1","kaynak":"okuma blok 27:41-50",
 "etiket":"okuma sırasında ölçüldü",
 "test_notu":"**Aday 781'in kontrollü çiftine (sûre 26 ve 27) ANLATI düzeyinde ilk örtüşme.** İki sûre aynı kavmi anlatıyor ve aynı formülü kullanıyor — ama sûre 26'da bölüt nakaratlı, sûre 27'de nakaratsız. **Bu, nakarat alanının yeniden tanımı (P0 #4) için doğal bir sınama çifti: aynı içerik, farklı nakarat yapısı.** KAPATILAMAZ — 27:49-53 henüz okunmadı, bölüt kapanmadı."},
{"no":830,
 "aday":"عرش DİZİSİ KAPANDI — SÛRE 27'DE BEŞ GEÇİŞ, BEŞ FARKLI KİP. 27:23 عَرْشٌ عَظِيمٌ (belirsiz, fâsıla) · 27:26 ٱلْعَرْشِ ٱلْعَظِيمِ (belirli, fâsıla) · 27:38 بِعَرْشِهَا (iyelikli) · 27:41 عَرْشَهَا (iyelikli, nesne) · 27:42 عَرْشُكِ (iyelikli, soru). Beş geçişin beşi de okundu.",
 "olculen":{"kok":"عرش","n":33,"sure_ici":[23,26,38,41,42],"hepsi_okundu":True,
   "kipler":["INDEF fâsıla","DEF fâsıla","POSS mecrur","POSS mef'ûl","POSS mübtedâ"],
   "fasila_konumunda":[23,26],"esit_alani_dolu":[]},
 "durum":"KAPALI","oncelik":"P1","kaynak":"okuma blok 27:41-50",
 "etiket":"okuma sırasında ölçüldü",
 "test_notu":"**Dizi sûre sonuna kadar okunmadan kapatılmadı (ders 774 karşılandı): beş geçişin beşi de bu okumada geçti.** Sonuç: `esit` alanı BEŞİNDE DE BOŞ. **27:23-27:26 çifti (aday 805) yapısal olarak diğer üçünden ayrılıyor — ikisi de fâsıla konumunda, ikisi de sıfat tamlaması; diğer üçü iyelikli ve fâsıla dışı.** 'Fâsıla konumunda ortak' alt ölçütü beş vakalık bir dizide iki/üç ayrımını doğru yapıyor. `esit_yapi` eşiği yazılırken bu dizi sınama kümesine girsin."},
{"no":831,
 "aday":"BLOK 27:41-50 BİLANÇOSU — OKUMADA İLK KEZ BİR BLOKTA ★★ VE ÜSTÜ HİÇ YOK. Yıldız: ★★★ 0 · ★★ 0 · ★ 2 (27:42 pas z=1,95; 27:44 n z=1,65) · yıldızsız 8. Kaynaklar: pas 1 · uzunluk 1 — içerikten sıfır. İltifât 0/10. Esmâ token 1 (artefakt). Allah lafzı 6 — blok rekoru. Rab 2 (ikisi 27:44'te). Adlı aktör 3 · adsız aktör 0. Yeni kök 2 (صرح, رهط). Hapaks 0. Kafiye kırılması 0.",
 "olculen":{"blok":"27:41-50","ayet":10,
   "yildiz":{"3":0,"2":0,"1":2,"0":8},
   "yildiz_kaynak":{"pas":1,"uzunluk":1,"icerik":0},
   "iltifat":0,"esma_token":1,"esma_artefakt":1,"muhur":0,
   "allah_lafzi":6,"rab":2,"adli_aktor":3,"adsiz_aktor":0,
   "yeni_kok":2,"hapaks":0,"kafiye_kirilmasi":0,"mim_fasila":0,"ort_n":13.5},
 "durum":"KAPALI","oncelik":"P2","kaynak":"okuma blok 27:41-50",
 "etiket":"okuma sırasında ölçüldü",
 "test_notu":"Sûre 27 ilk elli ayet: ★★★ 5 · ★★ 4 · ★ 4 · yıldızsız 37. Esmâ token 24 (14 artefakt, 10 geçerli mühür tokeni). Allah lafzı 14 · Rab 5 → **A/R = 2,80** (makro 2,25; ilk kırk ayette 1,40 idi — **eksen oranı sûre içinde iki kat dalgalanıyor**). İltifât 2/50. **Üç blok üst üste yıldızsız oran ≥%80** (27:31-40 %80, 27:41-50 %80, 27:21-30 %50). **Kraliçe 27:23'ten 27:44'e kadar yirmi iki ayet boyunca sahnede ve 27:23 dışında hiçbir aktör alanına girmiyor** (aday 802'nin ikinci yüzü, ikinci gösterim)."},
{"no":832,
 "aday":"SÛRE 27'DE 529 KÜMESİ ÜÇ VAKA — TEK SÛREDE ÜÇ. سمو (27:25 gök / 27:30 ad) · هدي (27:24 yol bulma / 27:35-36 hediye / 27:41 tanıma — ÜÇ anlam alanı) · طير (27:16,17,20 kuş / 27:47 uğur). Üçünde de otomatik tespit ölçütü çalışmadı.",
 "olculen":{"sure":27,"vaka_sayisi":3,
   "vakalar":[{"kok":"سمو","alan_sayisi":2,"aday":808},
     {"kok":"هدي","alan_sayisi":3,"aday":814},
     {"kok":"طير","alan_sayisi":2,"aday":823}],
  "olcut_skoru":"2/7","karsi_ornek":"نظر — sûrede beş geçiş, tek anlam alanı"},
 "durum":"ACIK","oncelik":"P0","kaynak":"okuma blok 27:41-50",
 "etiket":"okuma sırasında ölçüldü",
 "test_notu":"**529 kümesi seyrek bir arıza değil: elli ayette üç vaka.** Ve iyi bir karşı örnek var: نظر sûrede beş kez geçiyor ve tek anlam alanında kalıyor — **yani sorun 'çok geçen kök' değil, kökün kendi lemma yapısı.** Üç vakanın üçünde de ayrı lemmalar var (سَماء/اسْم · هُدَى/هَدِيَّة · طَيْر/طائِر), bağlam denetimi gerekmiyor. **P0 #5'in (529'un üç katmanlı onarımı) lemma katmanı için sınama kümesi artık yedi vakalık.**"},
]

BAGLAR = [
 {"bag":"27:23 ↔ 27:26 ↔ 27:38 ↔ 27:41 ↔ 27:42","kural":"L1","not":"**عرش dizisi KAPANDI: sûre içi beş geçişin beşi de okundu, beş farklı kipte.** `esit` alanı beşinde de boş; 'fâsıla konumunda ortak' alt ölçütü 27:23-27:26 çiftini diğer üçünden doğru ayırıyor (aday 830)."},
 {"bag":"27:31 ↔ 27:38 ↔ 27:42","kural":"L1","not":"Fâsıla مُسْلِمِينَ üç kez: mektubun son sözü (27:31) → Süleymân'ın cümlesi (27:38) → **kraliçenin kendi sözü (27:42)**. Talep, on bir ayet sonra muhatabın ağzında yerine gelmiş olarak dönüyor."},
 {"bag":"27:42 ↔ 17:107","kural":"L2","not":"xref آتى + علم + قبل — 'daha önce ilim verilenler' kalıbı."},
 {"bag":"27:24 ↔ 27:43","kural":"L1","not":"صدد sûrede iki geçiş, **işlev aynı fâil değişiyor**: 27:24'te şeytan yoldan çeviriyor, 27:43'te taptıkları çeviriyor. Dikey satırı (▸önce زين ×15,6) bu sûre içi çifti korpus düzeyinde de doğruluyor."},
 {"bag":"27:44 ↔ 7:23 · 28:16","kural":"L2","not":"xref قال + ربّ + ظلم ve ربّ + ظلم + نفس — 'Rabbim, kendime zulmettim' formülü; üç ayrı ağızda (Âdem, Mûsâ, Sebe melikesi)."},
 {"bag":"27:46 ↔ 13:6","kural":"L2","not":"xref استعجل + سيّئة + قبل ve سيّئة + قبل + حسنة — 'iyilikten önce kötülüğü acele isteme' kalıbı."},
 {"bag":"27:47 ↔ 7:131","kural":"L2","not":"xref طائر + عند + اللّه — 'uğursuzluğunuz Allah katındadır' kalıbı; iki ayette de bir kavim elçiyi uğursuzlukla suçluyor."},
 {"bag":"27:16 · 27:17 · 27:20 ↔ 27:47","kural":"L1","not":"**طير iki anlam alanında: kuş (üç geçiş) ve uğur/fal (bir geçiş), yirmi yedi ayet arayla.** 529 kümesinin sûre içi üçüncü vakası; otomatik tespit ölçütü çalışmadı (aday 823)."},
 {"bag":"27:48 ↔ 26:152","kural":"L2","not":"**xref أفسد + أرض + أصلح — iki sûrenin Semûd bölütünde birebir aynı formül.** Aday 781'in kontrollü çiftine anlatı düzeyinde ilk örtüşme; nakarat alanının yeniden tanımı için doğal sınama çifti (aday 829)."},
 {"bag":"27:36 ↔ 27:43 ↔ 27:50","kural":"L1","not":"**Aynı yapı üç kez: kök sabit, konum sabit, özne ya da muhatap karşıt.** 27:36 أتي (muhatap değişiyor) · 27:43 صدد (fâil değişiyor) · 27:50 مكر (özne değişiyor, dört tekrar). `esit`in dokuzuncu eşik türü adayı (aday 822)."},
 {"bag":"27:45 ↔ 27:48","kural":"L1","not":"صلح kökü hem elçinin adı (صالِح) hem üç ayet sonraki fiil (يُصْلِحُونَ) — özel ad ve fiil aynı kökten, aynı bölütte."},
]

pa = '/home/claude/repo/bulgular/aday_bulgular.json'
AD = json.load(open(pa, encoding='utf-8'))
AD['AH_neml'].extend(ADAYLAR)
json.dump(AD, open(pa, 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
print('aday_bulgular: AH_neml →', len(AD['AH_neml']), '| son no', AD['AH_neml'][-1]['no'])

pb = '/home/claude/repo/notlar/okuma_baglantilari.json'
BG = json.load(open(pb, encoding='utf-8'))
BG['AG_neml'].extend(BAGLAR)
json.dump(BG, open(pb, 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
print('okuma_baglantilari: AG_neml →', len(BG['AG_neml']))
