# -*- coding: utf-8 -*-
"""aday_ekle_onarim_03.py — ONARIM TURU 3 (896-902)."""
import json
ADAYLAR = [
{"no":896,
 "aday":"★★★ `harf` ALANININ KURALI GERİ ÇIKARILDI — VE ALAN HARF SAYMIYOR. Artık (harf − düz harf sayımı), ar_saf'taki harf-dışı 33 kod noktasının sayımlarına en küçük karelerle çözüldü; bütün ağırlıklar +1 ya da 0 çıktı. SAYILANLAR: Arapça harfler + elif vasla + YİRMİ adet tilâvet/vakf işareti (küçük sîn, küçük mîm, secde işareti, rub'u'l-hizb, küçük vâv/yâ, vakf durakları). SAYILMAYANLAR: harekeler, şedde, sükûn, medde, hemze-üstü, hançer elif.",
 "olculen":{"temiz_ayet":6124,"kural_birebir_tutan":6115,"oran":0.9985,
   "tutmayan":["1:2","1:4","1:6","1:7","2:2","2:5","2:7","2:255","55:13"],
   "sayilan_ek_kodnoktasi":21,
   "toplam_harf_degeri":341021,"vakf_tilavet_isareti":18009,"isaret_payi":0.053,
   "isaretsiz_ayet":1160,
   "yeni_alanlar":{"harf3":"saf harf sayımı (belgeli)","isaret":"vakf/tilâvet işareti sayısı"}},
 "durum":"KAPALI","oncelik":"P0","kaynak":"onarım turu 3",
 "etiket":"onarım (aday 890 kapandı)",
 "test_notu":"**Alan HARF + VAKF/TİLÂVET İŞARETİ sayıyor ve işaretler değerin %5,3'ünü oluşturuyor.** Bu işaretler ayet uzunluğuyla değil DURAK KONUMLARIYLA dağılıyor — yani `harf` düz uzunluğun SAPMALI bir vekili. **Ve `harf` dis_sinav.py ile genelleme.py'de istatistiğe giriyor; o betiklerin uzunluk temelli bütün sonuçları bu karışımla üretilmiş.** Onarım: `harf3` (saf harf) ve `isaret` ayrı alanlar olarak yazıldı; eski `harf` ve `harf2` korundu. 1160 ayette hiç işaret yok, o ayetlerde harf = harf3."},
{"no":897,
 "aday":"★ ÇIPA TANIMI YAZILDI (P0 #6) — BEŞ KADEME. L0 adlandırma · L1 adlandırma+alan/yeti · L2 nedensel bağımlılık ya da yeti sınırı · L3 görünüş-durum ayrımı + karşılaştırma · L4 mekanizma/ölçü/sınıflandırma. Sûre 27'nin olgu içeren 17 ayeti kademelere yerleştirildi (yerleştirme okuma kayıtlarından).",
 "olculen":{"kademeler":["L0 adlandırma","L1 adlandırma+alan","L2 nedensellik/yeti sınırı",
     "L3 görünüş-durum ayrımı","L4 mekanizma/ölçü/sınıf"],
   "sure_27_dagilim":{"L0":4,"L1":8,"L2":5,"L3":1,"L4":0},
   "L3_ayet":"27:88","L4_ayet":[],
   "esik_L2_cipa":[60,62,64,86,88],"esik_L3_cipa":[88],"esik_L4_cipa":[]},
 "durum":"ACIK","oncelik":"P0","kaynak":"onarım turu 3",
 "etiket":"onarım",
 "test_notu":"**En önemli sonuç: L4 eşiğiyle sûre 27'de SIFIR çıpa var.** Yani 'mekanizma/ölçü/sınıflandırma' şartı konursa bu sûrede tek bir çıpa bile yok ve çıpa/yıldız sorusu bu sûre için ANLAMSIZ hale geliyor. L3 eşiğiyle tek ayet (27:88), L2 ile beş ayet. **Eşik kararı, sonucuna bakılarak verilemez (döngüsel olur); bu yüzden üç eşik de raporlandı ve karar sonraki sûrelerin verisine bırakıldı.**"},
{"no":898,
 "aday":"★★★ DÜŞEN KAYIT — 'ÇIPA/YILDIZ TERS İLİŞKİSİ' İDDİASI YANLIŞ YÖNDE. Okuma boyunca altı kez (aday 599/602/799/809/838/849/872) 'çıpası güçlü ayetler yıldızsız kalıyor' yazdım. Ölçüldü: sûre 27'de olgu içeren 17 ayetin %47,1'i yıldızlı, diğer 76 ayetin %26,3'ü. **İlişki TERS değil, DÜZ.**",
 "olculen":{"olgu_iceren":{"ayet":17,"yildizli":8,"oran":0.471,"ort_n":18.4,"hapaksli_oran":0.24},
   "digerleri":{"ayet":76,"yildizli":20,"oran":0.263,"ort_n":11.0,"hapaksli_oran":0.01},
   "uzunluk_eslemeli_n13":{"olgu":{"ayet":15,"yildizli":6,"oran":0.40,"hapaksli":0.20},
     "diger":{"ayet":23,"yildizli":6,"oran":0.26,"hapaksli":0.04}},
   "olgu_ayetlerinin_yildiz_kaynaklari":{"hapaks":4,"pas":2,"n":2,"icerik":0}},
 "durum":"KAPALI","oncelik":"P0","kaynak":"onarım turu 3",
 "etiket":"onarım sırasında ölçüldü (kendi kaydım düştü)",
 "test_notu":"**ALTINCI ve en yaygın düşen kayıt** (801, 819, 843, 883, 891, burası). **İki ayrı hata birleşmiş:** (a) iddia hiç sayılmadı, el ile seçilmiş çiftlere dayandırıldı (27:24 yıldızsız / 27:25 ★★★ gibi) — bu çiftler gerçek ama TEMSİLİ DEĞİL; (b) örnekler okuma sırasında dikkat çektikleri için seçildi, yani **örneklem yıldızın kendisiyle ilişkili bir süreçle oluştu.** **DOĞRU İFADE: yıldız içeriği ölçmüyor (olgu ayetlerinin 8 yıldızının 8'i de hapaks/pas/uzunluktan, sıfırı içerikten) AMA içerikle DÜZ korele — çünkü doğa olgusu anlatan ayetler daha uzun (18,4'e 11,0) ve nadir kelime taşıma olasılıkları 24 kat yüksek (%24'e %1).** Yani bağıntı bir KARIŞTIRICIDAN geliyor, içerik duyarlılığından değil."},
{"no":899,
 "aday":"OKUMA SIRASINDA KURULAN İDDİALARIN ÖRNEKLEM ARIZASI — YAPISAL BİR SORUN. Aday 891 (nakarat ikilisi) ve 898 (çıpa/yıldız) aynı kusuru paylaşıyor: **okuma sırasında dikkat çeken vakalardan genelleme.** Dikkat çekme süreci, ölçülmek istenen değişkenin kendisiyle ilişkili olduğu için örneklem taraflı oluyor.",
 "olculen":{"vakalar":[
   {"aday":891,"iddia":"sûre 26 nakaratlı / 27 nakaratsız","gercek":"%27,3'e %32,3 — birim ve ağırlık farkı"},
   {"aday":898,"iddia":"çıpa/yıldız ters ilişki","gercek":"düz ilişki, karıştırıcı kaynaklı"},
   {"aday":819,"iddia":"27:19 okumada ilk kez üç kök","gercek":"okunan bölütte 107 ayet"},
   {"aday":843,"iddia":"نظر altıncı geçiş","gercek":"yedinci"}],
  "ortak_kusur":"sayılmadan genelleme + taraflı örneklem"},
 "durum":"ACIK","oncelik":"P0","kaynak":"onarım turu 3",
 "etiket":"onarım sırasında ölçüldü",
 "test_notu":"**PROTOKOLE KALICI MADDE: okuma sırasında 'X'li ayetler Y oluyor' biçiminde bir iddia kurulursa, iddia KAPATILAMAZ etiketiyle kaydedilir ve tur sonunda TAM SAYIMLA sınanır. Okuma notlarından toplanan örneklerle sınanamaz — o örnekler okuma dikkatinin ürünüdür.** Bu, mevcut 'sûrenin sonuna kadar okunmadan dizi kapatılmaz' (774) kuralının örneklem tarafındaki eşi ve ondan daha geniş: 774 EKSİK sayıma karşı koruyor, bu TARAFLI sayıma karşı."},
{"no":900,
 "aday":"OLGU AYETLERİNİN YILDIZ KAYNAKLARI — İÇERİK SIFIR TEYİDİ AYAKTA. Sûre 27'nin olgu içeren 17 ayetinden 8'i yıldızlı ve kaynakları: hapaks 4 (27:20, 25, 39, 88) · edilgenlik 2 (27:16, 17) · uzunluk 2 (27:40, 60). İçerikten sıfır.",
 "olculen":{"yildizli_olgu_ayeti":8,
   "kaynak":{"hapaks":4,"pas":2,"n":2,"icerik":0},
   "ayet_kaynak":{"27:16":"pas","27:17":"pas","27:20":"hapaks","27:25":"hapaks",
     "27:39":"hapaks","27:40":"n","27:60":"n","27:88":"hapaks"}},
 "durum":"KAPALI","oncelik":"P1","kaynak":"onarım turu 3",
 "etiket":"onarım sırasında ölçüldü",
 "test_notu":"**Aday 872'nin 'içerik sıfır' kısmı AYAKTA ve şimdi olgu ayetleri alt kümesinde ayrıca doğrulandı.** Düşen yalnız 'ters ilişki' kısmı (aday 898). **Ayrım önemli: alanın içeriğe DUYARSIZ olması ile içerikle KORELE OLMAMASI ayrı şeyler; birincisi doğru, ikincisi yanlıştı.**"},
{"no":901,
 "aday":"27:88'İN ÇIPA KARARI — L3, VE SÛRENİN TEK L3'Ü. Görünüş-durum ayrımı (dağları donuk SANIRSIN, oysa GEÇERLER) + karşılaştırma (bulutların geçişi gibi). Sûre 27'de L4 hiç yok; 27:88 kademe tablosunun tepesi.",
 "olculen":{"ayet":"27:88","kademe":"L3","sure_27_L4":0,
   "yildiz":3,"yildiz_kaynagi":"hapaks (تقن, جمد)",
   "esik_L2_ile":"çıpa","esik_L3_ile":"çıpa","esik_L4_ile":"çıpa DEĞİL"},
 "durum":"ACIK","oncelik":"P1","kaynak":"onarım turu 3",
 "etiket":"onarım",
 "test_notu":"**Ayet, üç aday eşikten ikisinde çıpa sayılıyor, birinde sayılmıyor — yani eşik kararının pratik sonucu sûre 27'de neredeyse tümüyle bu ayete bağlı.** Ve ★★★'ını içerikten değil iki hapakstan alıyor; **çıpa kademesi ile yıldız kaynağı arasında bu ayette de bağ yok.** KAPATILAMAZ: kademe tablosu tek sûreden; L4 örneği görülmeden eşik kararı verilemez."},
{"no":902,
 "aday":"ONARIM TURU 3 BİLANÇOSU. Üç iş: (1) `harf`in kuralı geri çıkarıldı ve alan ikiye ayrıldı; (2) çıpa tanımı beş kademeyle yazıldı (P0 #6); (3) çıpa/yıldız ters ilişkisi iddiası düştü. Üç turda toplam onarım: on üç.",
 "olculen":{"tur_3_onarim":3,"toplam_onarim":13,
   "kapanan_aday":[890,896,898,900],
   "yeni_alanlar":["harf3","isaret"],
   "kalan_borc":["fHz/sesli/ebced/mod19/bits kardeş projede kirli",
     "esit 0,85 eşiği örneklemeyle doğrulanmadı",
     "esit'in yedi eşik türü yazılmadı (P0 #3)",
     "çıpa eşiği (L2/L3/L4) seçilmedi — ikinci sûre verisi gerekli",
     "aday 779/781 sayıları güncellenmedi",
     "dis_sinav.py ve genelleme.py harf ile koşulmuş, yeniden koşulmadı"]},
 "durum":"KAPALI","oncelik":"P2","kaynak":"onarım turu 3",
 "etiket":"onarım bilançosu",
 "test_notu":"**Üç turun toplam dersi: on üç onarımın üçü kendi yanlış negatifini üretti, ve okumanın ALTI kaydı düştü — dördü sayım hatası, ikisi (891, 898) ÖRNEKLEM hatası.** İkinci tür daha pahalı: sayım hatası bir bloğu, örneklem hatası bir ÇERÇEVEYİ bozuyor. **Aday 899 bunun için protokol maddesi öneriyor.** P0 borçlarının durumu: #1 aktör (kapandı) · #2 aynı sahne (kapandı) · #3 esit eşik türleri (AÇIK) · #4 nakarat (kapandı) · #5 529 lemma katmanı (altyapı hazır, uygulanmadı) · #6 çıpa (tanım yazıldı, eşik açık)."},
]
pa='/home/claude/repo/bulgular/aday_bulgular.json'
AD=json.load(open(pa,encoding='utf-8'))
AD['AI_onarim'].extend(ADAYLAR)
json.dump(AD,open(pa,'w',encoding='utf-8'),ensure_ascii=False,indent=1)
print('AI_onarim →',len(AD['AI_onarim']),'| son no',AD['AI_onarim'][-1]['no'])
