# -*- coding: utf-8 -*-
"""aday_ekle_27_51_60.py — blok 27:51-60 adayları (833-842) ve bağları."""
import json

ADAYLAR = [
{"no":833,
 "aday":"ADSIZ AKTÖR ALANININ YANLIŞ NEGATİFLERİ ÖLÇÜLDÜ — MEKANİZMA KESİN: ALAN 'ADSIZ'I 'BELİRSİZ'LE KARIŞTIRIYOR. Korpusta امْرَأَت lemmalı 25 ayet var; alan yalnız DÖRDÜNÜ yakalıyor. Yakalanan dördünün dördü de INDEF; kaçan yirmi ikisinin yirmi ikisi de belirli ya da izâfetli. **İstisna sıfır.** Duyarlılık 4/25 = %16; kesinlik 4/11 = %36,4.",
 "olculen":{"gercek_ayet":25,"etiketli_ayet":11,"dogru":4,
   "yanlis_pozitif":7,"yanlis_negatif":21,
   "duyarlilik":0.16,"kesinlik":0.364,
   "yakalanan":["4:12","4:128","27:23","33:50"],
   "kacan":["2:282","3:35","3:40","7:83","11:71","11:81","12:21","12:30","12:51","15:60","19:5","19:8","27:57","28:9","28:23","29:32","29:33","51:29","66:10","66:11","111:4"],
   "ayirt_edici":"INDEF","istisna":0,
   "kacan_ornekler":{"Lût'un karısı":["7:83","15:60","27:57","29:32","29:33"],
     "Firavun'un karısı":["28:9","66:11"],"İmrân'ın karısı":["3:35"],"Nûh ve Lût'un karıları":["66:10"],"Ebû Leheb'in karısı":["111:4"]}},
 "durum":"ACIK","oncelik":"P0","kaynak":"okuma blok 27:51-60",
 "etiket":"okuma sırasında ölçüldü (27:57'de alan boş çıkınca tarandı)",
 "test_notu":"**Aday 802'yi tamamlıyor ve ağırlaştırıyor: orada yalnız kesinlik ölçülmüştü (%36,4); şimdi duyarlılık da var (%16).** F1 ≈ 0,22. **Mekanizma tek bir ayrımda: alan belirsizlik işaretine bakıyor, adlandırılmışlığa değil.** Anlatının en tanınmış adsız kadın aktörleri — Lût'un karısı, Firavun'un karısı, İmrân'ın karısı, Ebû Leheb'in karısı — hepsi izâfetli olduğu için görünmez. **Onarım hâlâ ucuz: lemma eşleşmesi + belirlilik koşulunun KALDIRILMASI.** Aday 765'in dört alanı içinde en ucuz onarılanı olduğu kaydı korunuyor, ama arızanın boyutu iki kat büyüdü."},
{"no":834,
 "aday":"27:58 — `esit` ALANI OKUMADA İLK KEZ DOLU: [[26,173]]. Sûre 27'de esit dolu üç ayet var (27:3, 27:58, 27:71); okumada bu ilki. Eşleşme sağlam: üç xref 3-gram'ın üçü de 26:173'e düşüyor ve iki ayet neredeyse birebir.",
 "olculen":{"ayet":"27:58","esit":[[26,173]],
   "sure_27_esit_dolu":["27:3","27:58","27:71"],
   "xref_3gram":3,"hepsi_ayni_hedefe":True,"hedef":"26:173",
   "27:58_ikile":{"مطر":3},"n":6,"tek_kok_orani":0.50},
 "durum":"ACIK","oncelik":"P0","kaynak":"okuma blok 27:51-60",
 "etiket":"okuma sırasında ölçüldü",
 "test_notu":"**Aday 829'un sınama çiftini AYET düzeyine indiriyor: aynı kavim, aynı cümle, iki sûre — biri nakaratlı bölütte (26:160-175, on altı ayet), diğeri nakaratsız bölütte (27:54-58, beş ayet).** Nakarat alanının yeniden tanımı (P0 #4) için bundan temiz bir çift zor bulunur: **içerik sabit, nakarat yapısı değişken, bölüt uzunluğu 16'ya 5.** TUR SONU: nakarat tanımı yazıldıktan sonra bu çift ilk sınama olsun."},
{"no":835,
 "aday":"ADAY 806'NIN RAFİNESİ — 'TEK AYET' İLE 'TEK SAHNE' AYRI ŞEYLER VE İKİNCİSİ BİLGİ TAŞIYOR. 27:57'ye gelindiğinde görüldü ki 27:23'te uyarıyla geçilen مرأ ▸ geride-kalan ×126,4 satırı bu ayeti ÖNCEDEN işaret ediyormuş: satır beş ayrı ayetten geliyor (7:83, 15:60, 27:57, 29:32, 29:33) ve beşi de AYNI SAHNE (Lût'un karısının geride kalması). Aynı şey خوي ▸ arş-taht ×167,7 için de geçerli: üç ayet (2:259, 18:42, 22:45), tek KALIP.",
 "olculen":{"tur_A_tek_ayet":[
   {"cift":["تسع","نعج"],"ayri_ayet":1},{"cift":["بيت","عنكب"],"ayri_ayet":1},
   {"cift":["سوق","لفف"],"ayri_ayet":1},{"cift":["عظم","مضغ"],"ayri_ayet":1},
   {"cift":["ودي","نمل"],"ayri_ayet":1}],
  "tur_B_tek_sahne":[
   {"cift":["مرأ","غبر"],"ayri_ayet":5,"sahne":"Lût'un karısı geride kaldı","kat":126.4},
   {"cift":["خوي","عرش"],"ayri_ayet":3,"sahne":"çatısı üstüne çökmüş ıssız yapı","kat":167.7},
   {"cift":["شجر","زقم"],"ayri_ayet":3,"sahne":"zakkum ağacı"},
   {"cift":["سجد","شطر"],"ayri_ayet":3,"sahne":"kıble bölütü (2:144-150)"}],
  "tur_C_gercek_birliktelik":[{"cift":["شمس","قمر"],"ayri_ayet":21}]},
 "durum":"ACIK","oncelik":"P0","kaynak":"okuma blok 27:51-60",
 "etiket":"okuma sırasında ölçüldü",
 "test_notu":"**Onarım 'bu satırları sil' değil, 'kaynak ayetlerini etiketle' olmalı.** Tür A (tek ayet) bilgi taşımıyor. **Tür B (tek sahne, çok ayet) taşıyor: 27:57'ye vardığımızda satır doğrulandı.** Tür C gerçek birliktelik. ÖN-KAYIT GÜNCELLENDİ: ayrı ayet ≤2 → satır bastırılır; 3-5 → satır **kaynak ayetleriyle birlikte** gösterilir ('tek sahne: 7:83, 15:60, 27:57, 29:32, 29:33'); >5 → serbest. **Bu, 'aynı sahne' alanının çıktı biçimini de belirliyor: alan bir bayrak değil, bir KAYNAK LİSTESİ üretmeli.**"},
{"no":836,
 "aday":"ADAY 818'İN ÖN-KAYDI İKİNCİ KEZ SINANDI — 27:59 سَلام ARTEFAKT, AYRIM BOZULMADI. Gönderge وَسَلَٰمٌ عَلَىٰ عِبَادِهِ, yani bir selamlama; ilâhî isim değil. Mühür bayrağının ayrımı: mühür tokeninde 10/10 geçerli, mühürsüz tokende 0/15.",
 "olculen":{"sinama_no":2,"ayet":"27:59","esma":"سَلام","gonderge":"selamlama (soyut)",
   "gecerli":False,"muhursuz_token_toplam":15,"muhursuz_gecerli":0,
   "muhur_token_toplam":10,"muhur_gecerli":10,
   "kalan_sinama":["27:63 بَرّ","27:66 آخِر","27:75 مُبِين","27:77 مُؤْمِن","27:79 مُبِين","27:88 خَبِير"]},
 "durum":"ACIK","oncelik":"P0","kaynak":"okuma blok 27:51-60",
 "etiket":"ön-kayıt sınaması",
 "test_notu":"**Sekiz sınamanın ikisi geçti; ön-kayıt (en az biri geçerli çıkacak) hâlâ ayakta ve altı sınama kaldı.** Gönderge sınıfı 'soyut kavram' — envanterde zaten vardı. **Not: ayrım 25/25'e çıktı ve bu, mühür bayrağının ne kadar güçlü bir vekil ölçü olduğunu gösteriyor; ama bayrak yapısal olduğu için TEK BAŞINA gelen geçerli bir ismi yakalayamaz — ön-kaydın dayanağı bu ve 27:88 gibi bir ayet kaldıkça sınama sürüyor.**"},
{"no":837,
 "aday":"27:59 — SÛRENİN EN YÜKSEK EKSEN Z'Sİ (allah z=2,80) VE OKUMADA İLK KEZ TEK BAŞINA EKSENDEN ★★. n=12'lik ayette lafız İKİ kez (3. ve 9. sıra), ikisi de ilk yarıda. 27:44 bunun tersi: n=28'de üç eksen işareti (bir lafız, iki Rab) ve allah z=0,19 · rab z=1,20 — yıldız uzunluktan geldi.",
 "olculen":{"ayet":"27:59","n":12,"A":[3,9],"allah_z":2.80,"yildiz":2,"yildiz_kaynak":"eksen",
   "karsit_vaka":{"ayet":"27:44","n":28,"eksen_isareti":3,"allah_z":0.19,"rab_z":1.20,"yildiz_kaynak":"uzunluk"},
   "onceki_eksen_yildizi":{"ayet":"27:26","n":8,"kaynak":"allah+rab"}},
 "durum":"ACIK","oncelik":"P1","kaynak":"okuma blok 27:51-60",
 "etiket":"okuma sırasında ölçüldü",
 "test_notu":"**Aday 827'nin çift kanıtı tamamlandı: aynı sûre içinde iki karşıt vaka.** 27:44 (uzun, eksen yoğun, eksenden yıldız YOK) ve 27:59 (kısa, eksen yoğun, eksenden ★★). **Fark yalnız n.** z hesabının uzunluk normalizasyonu eksen işaretini ayet uzunluğuyla seyreltiyor; **bu, yıldız alanının ölçtüğü şeyin 'eksen yoğunluğu' değil 'eksen yoğunluğu ÷ uzunluk' olduğu anlamına gelir ve bu ikisi farklı ölçülerdir.** TUR SONU: z tanımı denetlenip her iki ölçü ayrı hesaplanacak."},
{"no":838,
 "aday":"27:60 — SÛRENİN DOĞA BÖLÜTÜ AÇILIYOR VE ÇIPA EŞİĞİNİN NEREDE DURDUĞUNU EN İYİ GÖSTEREN AYET. Ayet bir NEDENSEL BAĞIMLILIK (gökten su → göz alıcı bahçeler) ve bir YETİ SINIRI (ağacını siz bitiremezdiniz) kuruyor. Ölçü, mekanizma ve sınıflandırma yok; eşik aşılmadı. Ve ayet ★ alıyor, kaynağı YALNIZ uzunluk (n z=1,55); eksen işareti 23. sırada, z=0,21.",
 "olculen":{"ayet":"27:60","n":27,"yildiz":1,"yildiz_kaynak":"uzunluk",
   "allah_z":0.21,"bolut":"27:60-64 (doğa, beş ayet)",
   "yapi":["nedensel bağımlılık: gökten su → bahçe","yeti sınırı: ağacı siz bitiremezdiniz"],
   "eksik":["ölçü","mekanizma","sınıflandırma"],"cipa":False,
   "ikile":{"سمو":2,"نبت":2,"أله":2}},
 "durum":"ACIK","oncelik":"P0","kaynak":"okuma blok 27:51-60",
 "etiket":"okuma sırasında ölçüldü",
 "test_notu":"**Aday 599/602/809 dizisine DÖRDÜNCÜ gösterim: sûrenin doğaya en yakın ayeti doğadan değil uzunluktan yıldız alıyor.** Ve aday 799'un çıpa tanımı için en değerli sınır vakası: **'adlandırma'nın üstünde ama 'mekanizma'nın altında bir kat var — nedensel bağımlılık + yeti sınırı.** Çıpa tanımı yazılırken bu katın çıpa sayılıp sayılmayacağına karar verilmeli; **karar verilmeden 26/27 çıpa-yıldız korelasyonu hesaplanamaz** (aday 781)."},
{"no":839,
 "aday":"SÛRE 27'NİN ANLATI BÖLÜTLERİ — DÖRT BÖLÜT, UZUNLUKLAR 8 · 30 · 9 · 5. Mûsâ 27:7-14 (sekiz) · Dâvûd-Süleymân 27:15-44 (otuz) · Semûd 27:45-53 (dokuz) · Lût 27:54-58 (beş). Ortadaki bölüt diğer üçünün toplamının (22) üstünde. Doğa bölütü 27:60-64 ile anlatı biter.",
 "olculen":{"bolutler":[["Mûsâ","27:7-14",8],["Dâvûd-Süleymân","27:15-44",30],
   ["Semûd","27:45-53",9],["Lût","27:54-58",5],["doğa","27:60-64",5]],
  "sure_26_karsiliklari":{"Semûd":["26:141-159",19],"Lût":["26:160-175",16]},
  "sure_26_nakaratli":True,"sure_27_nakaratli":False},
 "durum":"ACIK","oncelik":"P1","kaynak":"okuma blok 27:51-60",
 "etiket":"okuma sırasında ölçüldü",
 "test_notu":"**Aday 781'in kontrollü çifti (26/27) artık bölüt düzeyinde ölçülü: aynı iki kavim, sûre 26'da 19+16=35 ayet ve nakaratlı, sûre 27'de 9+5=14 ayet ve nakaratsız.** Oran 2,5:1. **Nakaratın ne kadar yer kapladığı doğrudan ölçülebilir hale geldi.** KAPATILAMAZ — 27:60-93 okunmadı, doğa bölütünün sınırı doğrulanmadı. TUR SONU: nakarat alanının yeniden tanımı bu çiftle sınanacak (aday 834)."},
{"no":840,
 "aday":"XREF YOĞUNLUĞU ORTAK KELİMEYİ DEĞİL ORTAK SAHNEYİ ÖLÇÜYOR — ÜÇÜNCÜ VERİ. 27:55'te DÖRT 3-gram var ve dördü de TEK ayete düşüyor: 7:81. Önceki iki vaka: 27:10'da altı bağ, 27:19'da dokuz 3-gram'ın sekizi tek ayete. Üç vakanın üçünde de hedef, başka bir sûrede aynı sahnenin anlatımı.",
 "olculen":{"vakalar":[
   {"ayet":"27:55","gram_3":4,"hepsi_tek_hedefe":True,"hedef":"7:81","sahne":"Lût kavmine hitap"},
   {"ayet":"27:19","gram_3":9,"tek_hedefe":8,"hedef":"46:15"},
   {"ayet":"27:10","bag":6}],
  "27:56_ek":{"gram_3":4,"hedefler":["7:82","29:24","29:29"]}},
 "durum":"ACIK","oncelik":"P1","kaynak":"okuma blok 27:51-60",
 "etiket":"okuma sırasında ölçüldü",
 "test_notu":"**Aday 797'nin 'xref yoğunluğu' ölçütü netleşti: ölçtüğü şey ortak kelime değil ortak SAHNE.** Bu, ölçütü zenginleştiriyor ama aynı zamanda sınırlıyor: **yüksek xref yoğunluğu bir keşif değil, korpusta aynı olayın birden çok kez anlatıldığının göstergesi.** KAPATILAMAZ — korpus çapında 'xref yoğunluğu yüksek ayetler' listesi çıkarılıp kaçının paralel anlatı olduğu sayılmadı. TUR SONU: bu sayım koşulacak; **eğer oran yüksek çıkarsa ölçüt bir keşif aracı olarak DÜŞER ve yalnız paralel-anlatı tespiti için kullanılır.**"},
{"no":841,
 "aday":"27:57 — DİKEY SATIRIN BİR AYETİ ÖNCEDEN İŞARET ETTİĞİ İLK BELGELENMİŞ VAKA. 27:23'te مرأ satırı ▸sonra geride-kalan ×126,4 veriyordu ve n≤25 kuralı gereği değil ama 'tek sahne' şüphesiyle yorumlanmadan geçilmişti. Otuz dört ayet sonra 27:57'ye gelindiğinde ayetin fâsılası غبر kökünden çıktı (geride kalanlar) — yani satırın işaret ettiği sahne.",
 "olculen":{"satir_ayeti":"27:23","satir":"مرأ ▸sonra geride-kalan ×126,4",
   "varilan_ayet":"27:57","fasila":"غبر kökünden çoğul (geride kalanlar)","mesafe":34,
   "kaynak_ayetler":["7:83","15:60","27:57","29:32","29:33"],"hepsi_ayni_sahne":True},
 "durum":"KAPALI","oncelik":"P2","kaynak":"okuma blok 27:51-60",
 "etiket":"okuma sırasında ölçüldü",
 "test_notu":"**Yöntemsel değeri var: dikey katmanın 'artefakt' dediğimiz satırları bazen ileriyi gösteriyor.** Ama dikkat — **bu bir doğrulama değil, bir tesadüf sınıfı: satır 27:57'yi işaret ediyordu çünkü 27:57 zaten satırın kaynak ayetlerinden biriydi.** Yani satır bir tahmin yapmadı, kendi kaynağını gösterdi. **Bu ayrım kayda geçirildi ki ileride 'dikey katman öngörü yaptı' diye yanlış okunmasın** (aday 728'in dersiyle aynı sınıf: döngüsel doğrulama)."},
{"no":842,
 "aday":"BLOK 27:51-60 BİLANÇOSU. Yıldız: ★★★ 0 · ★★ 1 (27:59, kaynak EKSEN) · ★ 1 (27:60, kaynak uzunluk) · yıldızsız 8. **Okumada ilk kez bir ayet ★★'yi tek başına eksenden aldı.** İltifât 0/10. Esmâ token 1 (artefakt). Allah lafzı 3 · **Rab 0 — okumada ilk kez bir blokta Rab hiç yok.** Adlı aktör 2 (لُوط x2) · adsız aktör 0 (ama 27:57'de gerçek bir adsız aktör var, alan kaçırıyor). Yeni kök 1 (حدق). Hapaks 0. `esit` okumada ilk kez dolu (27:58).",
 "olculen":{"blok":"27:51-60","ayet":10,
   "yildiz":{"3":0,"2":1,"1":1,"0":8},
   "yildiz_kaynak":{"eksen":1,"uzunluk":1,"icerik":0},
   "iltifat":0,"esma_token":1,"esma_artefakt":1,"muhur":0,
   "allah_lafzi":3,"rab":0,"adli_aktor":2,"adsiz_aktor":0,
   "yeni_kok":1,"hapaks":0,"kafiye_kirilmasi":0,"mim_fasila":0,
   "esit_dolu":1,"ort_n":10.1},
 "durum":"KAPALI","oncelik":"P2","kaynak":"okuma blok 27:51-60",
 "etiket":"okuma sırasında ölçüldü",
 "test_notu":"Sûre 27 ilk altmış ayet: ★★★ 5 · ★★ 5 · ★ 5 · yıldızsız 45. Esmâ token 25 (15 artefakt, 10 geçerli mühür tokeni). Allah lafzı 17 · Rab 5 → **A/R = 3,40** (makro 2,25; ilk kırkta 1,40, ilk ellide 2,80 idi — **oran monoton artıyor ve sûrenin ikinci yarısı eksen yoğun**). İltifât 2/60. **Dört blok üst üste yıldızsız oran ≥%80** (%50, %80, %80, %80, %80 — 27:21-30 hariç). Ortalama n blok başına: 10,7 · 14,3 · 13,5 · 10,1."},
]

BAGLAR = [
 {"bag":"27:53 ↔ 27:57","kural":"L1","not":"نجو *(kurtulma, kurtarma)* blokta iki kez, iki ayrı kavmin kurtuluşu, dört ayet arayla, ikisi de 1P fâille (أَنجَيْنَا)."},
 {"bag":"27:54 ↔ 7:80 · 29:28","kural":"L2","not":"xref قال + قوم + أتى ve قوم + أتى + فاحشة; Lût'un ilk hitabı üç sûrede aynı terkiple."},
 {"bag":"27:55 ↔ 7:81","kural":"L2","not":"**DÖRT 3-gram ve dördü de TEK ayete.** Aday 797'nin xref yoğunluğu ölçütüne üçüncü veri; ölçtüğü şeyin ortak SAHNE olduğunu gösteriyor (aday 840)."},
 {"bag":"27:56 ↔ 7:82 · 29:24 · 29:29","kural":"L2","not":"xref كان + جواب + قوم ve türevleri; aynı sahne en az üç sûrede, terkipler neredeyse birebir."},
 {"bag":"27:57 ↔ 7:83 · 15:60 · 29:32 · 29:33","kural":"L1","not":"**Lût'un karısının geride kalması korpusta beş ayette; beşi de aynı sahne.** Dikey satır (مرأ ▸ geride-kalan ×126,4) bu sahneyi taşıyordu (aday 835/841). **Beşinin beşinde de adsız aktör alanı BOŞ** (aday 833)."},
 {"bag":"27:58 ↔ 26:173","kural":"L1","not":"**`esit` alanı dolu — okumada ilk kez.** Üç xref 3-gram'ın üçü de bu ayete; iki ayet neredeyse birebir. Aynı kavim, iki sûre: 26'da nakaratlı bölüt (on altı ayet), 27'de nakaratsız (beş ayet) — **P0 #4 için en temiz sınama çifti** (aday 834)."},
 {"bag":"27:23 ↔ 27:57","kural":"L1","not":"مرأ *(kişi; kadın (imrae))* sûrede iki geçiş: 27:23 belirsiz (alan YAKALADI) · 27:57 izâfetli (alan KAÇIRDI). **Tek sûre içinde alanın hem doğru hem yanlış çalıştığı çift; ayırt edici INDEF** (aday 833)."},
 {"bag":"27:43-49 ↔ 27:59-65","kural":"L1","not":"Sûrenin iki eksen kümesi: birincisi yedi ayette altı lafız (Semûd bölütünün açılışı), ikincisi **yedi ayette yedi** (sûrenin azamisi, 27:59'da başlıyor). İkisi de bölüt sınırında."},
 {"bag":"27:44 ↔ 27:59","kural":"L1","not":"**z'nin uzunluk normalizasyonunun iki karşıt vakası tek sûrede:** 27:44 n=28, üç eksen işareti, eksenden yıldız YOK · 27:59 n=12, iki işaret, eksenden ★★. Fark yalnız n (aday 837)."},
 {"bag":"27:60 ↔ 14:32 · 31:10","kural":"L2","not":"xref سماء + أرض + أنزل ve سماء + ماء + أنۢبت; doğa bölütünün açılış terkibi iki sûrede daha."},
 {"bag":"27:50 ↔ 27:58","kural":"L1","not":"Blokta iki tek-kök yoğunluğu: 27:50 مكر ×4 (n=7, oran 0,57) ve 27:58 مطر ×3 (n=6, oran 0,50). **İkisi de kısa ayet; ikisi de helâk sahnesi.**"},
]

pa = '/home/claude/repo/bulgular/aday_bulgular.json'
AD = json.load(open(pa, encoding='utf-8'))
AD['AH_neml'].extend(ADAYLAR)
json.dump(AD, open(pa, 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
print('aday_bulgular: AH_neml →', len(AD['AH_neml']), '| son no', AD['AH_neml'][-1]['no'])

pb = '/home/claude/repo/notlar/okuma_baglantilari.json'
BG = json.load(open(pb, encoding='utf-8'))
BG['AG_neml'].extend(BAGLAR)
json.dump(BG, open(pb, 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
print('okuma_baglantilari: AG_neml →', len(BG['AG_neml']))
