# -*- coding: utf-8 -*-
"""aday_ekle_27_81_93.py — blok 27:81-93 adayları (865-876) ve sûre 27 kapanışı."""
import json

ADAYLAR = [
{"no":865,
 "aday":"★ ADAY 818'İN ÖN-KAYDI TUTTU — 27:88 خَبِير GEÇERLİ, AYRIM BOZULDU. Ön-kayıt: 'sûrenin kalan mühürsüz esmâ tokenlerinden en az biri GEÇERLİ çıkacak ve mühür bayrağının kusursuz ayrımı bozulacak'; gerekçe bayrağın YAPISAL olması (iki esmânın bitişikliği + son konum) ve tek başına gelen geçerli bir ismi tanım gereği yakalayamaması. 27:88'de خَبِير mühürsüz ve göndergesi İLÂHÎ (إِنَّهُۥ, mercii صُنْعَ ٱللَّهِ). **Düştüğü yer de öngörülen yer: son ta'lîl cümlesinde tek başına duran bir isim.**",
 "olculen":{"sinama_no":8,"ayet":"27:88","esma":"خَبِير","konum":16,"n":18,
   "muhur":False,"gecerli":True,"gonderge":"ilâhî (zamir, mercii lafza-i celâl)",
   "sure_muhursuz_token":21,"muhursuz_gecerli":1,
   "sure_muhur_token":12,"muhur_gecerli":12,
   "ayrim_once":"32/32","ayrim_sonra":"33/34",
   "on_kayit":"tuttu","dayanak":"yapısal"},
 "durum":"KAPALI","oncelik":"P0","kaynak":"okuma blok 27:81-93",
 "etiket":"ön-kayıt sınaması (tamamlandı)",
 "test_notu":"**Bu, okumada YAPISAL GEREKÇEYLE kurulup KENDİ DESENİNİN BOZULACAĞINI öngören ilk ön-kayıt ve tuttu.** Sonuç: **mühür bayrağı gönderge geçerliliği için YETERLİ ama GEREKLİ DEĞİL.** Sûre 27'de 12/12 mühür tokeni geçerli (yanlış pozitif sıfır) ve 20/21 mühürsüz token artefakt (yanlış negatif bir). **Esmâ tablosunun onarımında bayrak güvenilir bir POZİTİF filtre olarak kullanılabilir; negatif filtre olarak kullanılamaz.** TUR SONU: korpus çapında mühür/mühürsüz × geçerli/artefakt çapraz tablosu çıkarılacak."},
{"no":866,
 "aday":"27:88 — SÛRENİN EN YÜKSEK z DEĞERİ: hapaks z=6,98, İKİ HAPAKS BİRDEN (تقن, جمد). Sûrenin tek çift-hapaks ayeti. Ayet ayrıca korpusta yalnız üç ayette bulunan `MM` (mef'ûl-i mutlak) biçimini taşıyor.",
 "olculen":{"ayet":"27:88","hapaks":["تقن","جمد"],"hapaks_z":6.98,
   "sure_hapaks_ayetleri":{"27:19":["بسم"],"27:20":["هدهد"],"27:25":["خبأ"],
     "27:39":["عفر"],"27:88":["تقن","جمد"]},
   "sure_hapaks_kok_sayisi":6,
   "korpus_en_yuksek_hapaks_z":{"2:61":17.8,"5:3":14.19},
   "fig":"MM","MM_korpus_ayet":3},
 "durum":"KAPALI","oncelik":"P2","kaynak":"okuma blok 27:81-93",
 "etiket":"okuma sırasında ölçüldü",
 "test_notu":"Korpus azamisi 2:61'de (beş hapaks, z=17,8); 27:88 sûre içi azami. **Sûrenin beş hapaks ayetinin dördü ★★★, biri (27:19) ★★★ — yani hapaks alanı sûrede kusursuz bir ★★★ üreticisi.** Bu, yıldız alanının içerikten bağımsızlığına ek veri: **hapaks bir 'nadirlik' ölçüsüdür, bir 'önem' ölçüsü değil.**"},
{"no":867,
 "aday":"`MM` (MEF'ÛL-İ MUTLAK) ALANININ ONARIMI AŞIRI DARALTMIŞ — 175'TEN 3'E. defter5.py'nin kendi çıktısı bunu kaydediyor: eski kural (V + aynı kökten N, bitişik) 175 ayet; yeni kural (V + aynı kökten VN) **3 ayet** (17:26, 27:88, 84:8). Sûre 27'de eski kurala uyan üç ayet var (27:21 عَذَابًا, 27:50 مَكْرًا x2, 27:88) ve yeni kural yalnız 27:88'i etiketliyor.",
 "olculen":{"eski_kural_ayet":175,"yeni_kural_ayet":3,
   "yeni_kural_ayetleri":["17:26","27:88","84:8"],
   "sure_27_eski":["27:21","27:50","27:88"],"sure_27_yeni":["27:88"],
   "kacan_ornekler":{"27:21":"لَأُعَذِّبَنَّهُۥ عَذَابًا","27:50":"مَكَرُوا۟ مَكْرًا (iki kez)"},
   "daralma_orani":58.3},
 "durum":"ACIK","oncelik":"P1","kaynak":"okuma blok 27:81-93",
 "etiket":"okuma sırasında ölçüldü",
 "test_notu":"**Bir ONARIMIN kendisi yeni bir arıza üretmiş: 175 → 3, elli sekiz kat daralma.** مَكَرُوا۟ مَكْرًا ders kitabı örneğidir ve alan görmüyor; sebep ikinci tokenin morfolojide 'VN' değil 'N' etiketli olması. **DERS: onarımlar kendi yanlış negatif denetiminden geçmeli.** Eski kural yanlış pozitif üretiyordu (175 fazla geniş), yeni kural yanlış negatif üretiyor (3 fazla dar); **doğru ölçüt ikisinin arasında: V + aynı kök + ACC/INDEF isim.** TUR SONU: ara ölçüt koşulup sayı ölçülecek. **Bu, aday 806'nın 'koruma yanlış değişkende' bulgusunun onarım tarafındaki eşi.**"},
{"no":868,
 "aday":"ADLI AKTÖR ALANINDA CİNS İSİM ARTEFAKTI — مُسْلِم 14 TOKEN, HEPSİ 'KAVİM' TÜRÜNDE. 27:91'de ٱلْمُسْلِمِينَ adlı aktör olarak sayılmış; ama bu bir cins isim, özel ad değil. Korpus taraması: alanın 105 adlık envanterinde مُسْلِم (14 token) ve نَصْرانِيّ (15 token) gibi cins isimler var.",
 "olculen":{"ad":"مُسْلِم","token":14,"tur":"kavim","hepsi_ayni_tur":True,
   "ornek_ayetler":["6:163","10:72","10:90","16:89","16:102","22:78","27:91","33:35","39:12","41:33"],
   "benzer":"نَصْرانِيّ (15 token)",
   "envanter_boyu":105,
   "sure_27_etkisi":"adlı aktör 25 tokenin en az 1'i artefakt"},
 "durum":"ACIK","oncelik":"P0","kaynak":"okuma blok 27:81-93",
 "etiket":"okuma sırasında ölçüldü",
 "test_notu":"**Aday 802/833'ün ADSIZ aktör tarafında bulduğu arızanın ADLI taraftaki karşılığı: alan 'özel ad'ı 'sözlükteki ad listesinde bulunma' ile karıştırıyor.** Envantere cins isimler girmiş. **Dört alanın (aday 765) aktör ayağı artık iki yönden de arızalı: adsız tarafta hem yanlış pozitif hem yanlış negatif, adlı tarafta yanlış pozitif.** KAPATILAMAZ — 105 adlık envanterin tamamı cins isim açısından taranmadı. TUR SONU: envanter elden geçirilecek; **ölçüt 'morfolojide PN etiketi var mı' olmalı** (korpus 106 PN lemma taşıyor, envanter 105 ad — sayılar yakın ama küme aynı değil)."},
{"no":869,
 "aday":"`esit` YANLIŞ NEGATİFİNİN İKİNCİ VAKASI — VE BU KEZ FARK KELİME İÇİNDE. 27:81 ile 30:53 arasındaki tek fark بِهَٰدِى / بِهَٰدِ, yani bir yâ harfi. `esit` ikisinde de boş. Bir önceki vakada (27:80 ↔ 30:52) fark baştaki bir bağlaçtı. **İki ardışık ayet (27:80-81) iki ardışık ayetle (30:52-53) neredeyse birebir eşleşiyor ve alan hiçbirini görmüyor.**",
 "olculen":{"cift":["27:81","30:53"],"fark":"kelime içi bir yâ harfi",
   "esit":[[],[]],"xref_3gram":4,"hepsi_tek_hedefe":True,
   "onceki_vaka":{"cift":["27:80","30:52"],"fark":"baştaki bağlaç"},
   "ardisik_ciftler":True},
 "durum":"ACIK","oncelik":"P0","kaynak":"okuma blok 27:81-93",
 "etiket":"okuma sırasında ölçüldü",
 "test_notu":"**Aday 854'ün önerdiği ucuz onarım (baştaki و/ف'yi kırp) bu vakayı YAKALAMAZ** — fark kelime içinde. **Yani `esit` onarımı gerçekten yaklaşık eşleme istiyor, kırpma yetmiyor.** Ve xref yine doğru çalışıyor (dört 3-gram, tek hedef): **aday 860'ın 'xref yoğunluğu esit'in kaçırdıklarını buluyor' kaydı ikinci vakada da doğrulandı.** ÖN-KAYIT (aday 860'ın): korpusta 'dört+ 3-gram tek hedefe VE esit boş' taraması çalıştırılırsa çıkanların çoğu yakın-eşleşme olacak — **iki vaka da bu yönde.**"},
{"no":870,
 "aday":"SÛRE 27'DE ÜÇ AYET-İÇİ NAKARAT VAR VE ALAN ÜÇÜNÜ DE GÖRMÜYOR. (1) `أَءِلَٰهٌ مَّعَ ٱللَّهِ` — beş kez, 27:60-64, korpusta başka yerde yok. (2) `كَيْفَ كَانَ عَٰقِبَةُ` + değişen tamlanan — üç kez, 27:14, 51, 69. (3) `وَقَعَ ٱلْقَوْلُ عَلَيْهِم` — iki kez, 27:82 ve 27:85, üç ayet arayla, birebir. **`nakarat` alanı sûre 27'de SIFIR.**",
 "olculen":{"sure":27,"nakarat_alani_dolu":0,
   "ayet_ici_nakaratlar":[
     {"kalip":"أَءِلَٰهٌ مَّعَ ٱللَّهِ","kez":5,"ayetler":[60,61,62,63,64],"tur":"sabit"},
     {"kalip":"كَيْفَ كَانَ عَٰقِبَةُ","kez":3,"ayetler":[14,51,69],"tur":"şablon"},
     {"kalip":"وَقَعَ ٱلْقَوْلُ عَلَيْهِم","kez":2,"ayetler":[82,85],"tur":"sabit"}],
   "sure_26_nakarat_alani_dolu":34,"sure_26_nakarat_birimi":"tam ayet"},
 "durum":"ACIK","oncelik":"P0","kaynak":"okuma blok 27:81-93",
 "etiket":"okuma sırasında ölçüldü (sûre tamamlandı)",
 "test_notu":"**Aday 844/845 tam sûre sayımıyla kapandı: üç nakarat, iki tür (sabit / şablon), alan sıfır.** Buna karşılık sûre 26'da alan 34 ayette dolu çünkü orada nakarat TAM AYET. **Onarılmış nakarat alanının kapsaması gereken üç tür: tam ayet · sabit ayet-içi kalıp · şablon kalıp.** VE BİR UYARI: aday 700/739/771'in sûre 26 nakarat düzeltmesi yalnız tam-ayet türünü saymıştı; **sûre 26'da da ayet-içi nakaratlar varsa o sayım eksik ve 26/27 karşılaştırması şu an YAPILAMAZ.**"},
{"no":871,
 "aday":"★ SÛRE 27 KAPANIŞ BİLANÇOSU — HAM SAYIMLAR. 93 ayet · ortalama n=12,38 · fâsıla 84 `ن` + 9 `م` · kafiye kırılması 0. YILDIZ: ★★★ 9 · ★★ 9 · ★ 10 · yıldızsız 65 (%69,9). EKSEN: lafız 27 token / 25 ayet · Rab 12 token / 10 ayet → A/R = 2,25. ESMÂ: 33 token. İLTİFÂT 3. HAPAKS 5 ayet / 6 kök. EDİLGEN 16 ayet. Adlı aktör 25 token, adsız aktör 1 token.",
 "olculen":{"sure":27,"ayet":93,"ort_n":12.38,
   "fasila":{"ن":84,"م":9},"kafiye_kirilmasi":0,
   "yildiz":{"3":9,"2":9,"1":10,"0":65},"yildizsiz_oran":0.699,
   "yildizli_ayet":28,
   "lafiz_token":27,"lafiz_ayet":25,"rab_token":12,"rab_ayet":10,"A_R":2.25,
   "esma_token":33,"muhur":6,"muhur_token":12,"muhursuz_token":21,
   "iltifat":3,"hapaks_ayet":5,"hapaks_kok":6,"pas_ayet":16,
   "adli_token":25,"adsiz_token":1,
   "esit_dolu":[3,58,71],"nakarat_dolu":0,
   "anlati_bolutleri":{"Mûsâ":8,"Dâvûd-Süleymân":30,"Semûd":9,"Lût":5,"doğa":5}},
 "durum":"KAPALI","oncelik":"P1","kaynak":"okuma blok 27:81-93",
 "etiket":"okuma sırasında ölçüldü (sûre tamamlandı)",
 "test_notu":"Sûre 26 ile karşılaştırma için ham taban. **Aday 781'in kontrollü çiftinin sûre 27 tarafı tamamlandı.** Sûre 26: 227 ayet, ★★★ 41 (%18,1), iltifât 15, esmâ 51 token, mühür 10, nakarat alanı 34 ayet. Sûre 27: 93 ayet, ★★★ 9 (%9,7), iltifât 3, esmâ 33 token, mühür 6, nakarat alanı 0. **★★★ oranı sûre 26'da neredeyse iki katı — ama sûre 26'nın nakarat düzeltmesi (aday 700/739/771) yapılmadan bu oran karşılaştırılamaz.**"},
{"no":872,
 "aday":"★ SÛRE 27'DE YILDIZ KAYNAKLARI — İÇERİK SIFIR. Yıldızlı 28 ayetin kaynak dağılımı: **edilgenlik 11 · hapaks 5 · lafız 5 · Rab 5 · uzunluk 3** (27:26 hem lafız hem Rab). **İçerik hiçbirinde kaynak değil.** Sûrenin doğaya değen ayetleri (27:24 güneş, 27:60-64 doğa bölütü, 27:61 yer yapıları, 27:86 gece-gündüz, 27:88 dağlar) toplam iki yıldız alıyor ve ikisinin de kaynağı başka: 27:60 uzunluk, 27:88 hapaks.",
 "olculen":{"yildizli_ayet":28,
   "kaynak":{"pas":11,"hapaks":5,"allah":5,"rab":5,"n":3},
   "icerik":0,
   "pas_ayetleri":[6,8,16,17,23,29,42,68,83,90,91],
   "hapaks_ayetleri":[19,20,25,39,88],
   "doga_ayetleri":{"27:24":0,"27:60":1,"27:61":0,"27:62":0,"27:63":0,"27:64":0,"27:86":0,"27:88":3},
   "doga_yildiz_kaynaklari":{"27:60":"uzunluk","27:88":"hapaks"}},
 "durum":"KAPALI","oncelik":"P0","kaynak":"okuma blok 27:81-93",
 "etiket":"okuma sırasında ölçüldü (sûre tamamlandı)",
 "test_notu":"**Aday 599/602/799/809/838/849 dizisinin SÛRE ÇAPINDA TAM SAYIMLI kapanışı: 28 yıldızlı ayet, kaynakların hiçbiri içerik değil.** En çarpıcı: **edilgenlik tek başına yıldızların %39'unu üretiyor.** Ve sûrenin doğaya değen sekiz ayetinin toplam yıldızı iki, ikisi de başka kaynaktan. **TUR SONU: çıpa tanımı yazıldıktan sonra 26/27 korelasyonu hesaplanacak; bu sayım sûre 27 tarafının hazır verisi.**"},
{"no":873,
 "aday":"27:17 ↔ 27:83 — NADİR BİR FİİLİN SÛRE İKİ UCUNDAKİ YANKISI. `وزع` korpusta BEŞ geçişli ve ikisi bu sûrede: 27:17'de Süleymân'ın orduları toplanıp 'bir arada tutuluyordu' (يُوزَعُونَ), 27:83'te mahşerde toplananlar aynı fiille tutuluyor. Aynı vezin, aynı edilgen çatı, altmış altı ayet arayla.",
 "olculen":{"kok":"وزع","n":5,"sure_27":[17,83],"mesafe":66,
   "cati":"edilgen (ikisinde de)","vezin":"aynı",
   "baglam":["Süleymân'ın orduları","mahşerde toplananlar"],
   "esit_alani":[[],[]]},
 "durum":"ACIK","oncelik":"P1","kaynak":"okuma blok 27:81-93",
 "etiket":"okuma sırasında ölçüldü",
 "test_notu":"**Sûrenin iki ucundaki iki toplanma sahnesi tek nadir kelimeyle bağlanıyor.** `esit` ikisinde de boş (kelime örtüşmesi tek). Aday 812/863'ün ('konuşmacı/muhatap-arası kalıp yankısı') üçüncü vakası ve bu kez değişen SAHNE. **`esit`in sekizinci eşik türü artık üç vakalı: konuşmacı değişimi (27:34↔37) · muhatap değişimi (27:46↔72) · sahne değişimi (27:17↔83).**"},
{"no":874,
 "aday":"529 KÜMESİ SÛRE 27'DE ALTI VAKA — TAM SAYIM. سمو (gök/ad) · هدي (yol bulma / hediye / tanıma / hidâyet — DÖRT alan, sekiz geçiş) · طير (kuş/uğur) · كشف (açma/giderme) · خلف (halife/ihtilaf) · أمن (iman/güvende olma). Karşı örnek: نظر sekiz geçiş, tek anlam alanı. Otomatik tespit ölçütü altısında da çalışmadı.",
 "olculen":{"sure":27,"vaka":6,
   "vakalar":[{"kok":"سمو","alan":2},{"kok":"هدي","alan":4,"gecis":8},
     {"kok":"طير","alan":2},{"kok":"كشف","alan":2},{"kok":"خلف","alan":2},{"kok":"أمن","alan":2}],
   "karsi_ornek":{"kok":"نظر","gecis":8,"alan":1},
   "olcut_skoru":"2/10"},
 "durum":"KAPALI","oncelik":"P0","kaynak":"okuma blok 27:81-93",
 "etiket":"okuma sırasında ölçüldü (sûre tamamlandı)",
 "test_notu":"**Tek sûrede altı vaka — 529 seyrek bir arıza değil, yapısal bir arıza.** `هدي` sekiz geçişte dört anlam alanına yayılıyor; `نظر` sekiz geçişte tek alanda kalıyor. **Sorun kesinlikle sıklık değil, kökün lemma yapısı.** Otomatik ölçüt **2/10**; **TERK EDİLMESİ ÖNERİLİYOR.** P0 #5'in lemma katmanı için sınama kümesi on vakalık ve altısı tek sûreden."},
{"no":875,
 "aday":"BLOK 27:81-93 BİLANÇOSU (on üç ayet). Yıldız: ★★★ 1 (27:88 hapaks) · ★★ 0 · ★ 4 (27:83, 90, 91 pas; 27:93 Rab) · yıldızsız 8. Kaynaklar: hapaks 1 · pas 3 · Rab 1 — içerikten sıfır. İltifât 0/13. Esmâ token 1 (27:88, **GEÇERLİ**). Allah lafzı 3 · Rab 2. Adlı aktör 2 (biri ARTEFAKT) · adsız aktör 0. Yeni kök 5. Hapaks 2.",
 "olculen":{"blok":"27:81-93","ayet":13,
   "yildiz":{"3":1,"2":0,"1":4,"0":8},
   "yildiz_kaynak":{"hapaks":1,"pas":3,"rab":1,"icerik":0},
   "iltifat":0,"esma_token":1,"esma_gecerli":1,"muhur":0,
   "allah_lafzi":3,"rab":2,"adli_aktor":2,"adsiz_aktor":0,
   "yeni_kok":5,"hapaks":2,"kafiye_kirilmasi":0,"ort_n":13.8},
 "durum":"KAPALI","oncelik":"P2","kaynak":"okuma blok 27:81-93",
 "etiket":"okuma sırasında ölçüldü",
 "test_notu":"**Sûrenin son altı yıldızlı ayetinin dördü edilgenlikten** (27:68, 83, 90, 91). Sûre kapanışında edilgenlik oranı artıyor. Blokta beş yeni kök (فوج, دخر, جمد, تقن, كبب) — **okumadaki en yüksek blok-başı yeni kök sayısı;** sûre sonu bölütü kelime dağarcığı açısından en yoğun bölüt."},
{"no":876,
 "aday":"SÛRE 27 OKUMASININ ALAN BİLANÇOSU — DÖRT ALANDA MEKANİZMA BULUNDU, HEPSİ AYNI AİLE. (1) adsız aktör: adlandırılmamışlığı BELİRSİZLİK ile karıştırıyor (duyarlılık %16, kesinlik %36,4). (2) nakarat: tekrarı AYET TEKRARI ile karıştırıyor (sûre 27'de 0/3). (3) esit: benzerliği TAM DİZGE ile karıştırıyor (en az iki yanlış negatif). (4) MM: onarım aşırı daraltmış (175 → 3). Ve beşinci: adlı aktör envanterinde cins isimler var (مُسْلِم 14 token).",
 "olculen":{"alanlar":[
   {"alan":"adsız aktör","hata":"INDEF ≠ adsız","duyarlilik":0.16,"kesinlik":0.364,"aday":833},
   {"alan":"nakarat","hata":"ayet düzeyi ≠ n-gram düzeyi","sure_27":"0/3","aday":844},
   {"alan":"esit","hata":"tam dizge ≠ yakın eşleşme","yanlis_negatif":">=2","aday":854},
   {"alan":"MM","hata":"onarım aşırı daraltma","eski":175,"yeni":3,"aday":867},
   {"alan":"adlı aktör","hata":"cins isim envanterde","token":14,"aday":868}],
  "ortak_onarim":"n-gram / yaklaşık eşleme altyapısı"},
 "durum":"ACIK","oncelik":"P0","kaynak":"okuma blok 27:81-93",
 "etiket":"okuma sırasında ölçüldü (sûre tamamlandı)",
 "test_notu":"**Sûre 27 okumasının asıl çıktısı bu: beş alanda mekanizma bulundu ve dördü aynı aileden — doğru kavram, yanlış birim.** Ve **üçünün onarımı tek bir altyapıyı paylaşıyor: n-gram / yaklaşık eşleme** (nakarat, esit, aday 850'nin 'aynı ifade' alanı). **TUR SONU ONARIM EVRESİ İÇİN ÖNCELİK SIRASI: (a) n-gram altyapısı — üç alanı birden açar; (b) adsız aktör belirlilik koşulunun kaldırılması — en ucuz, tek satır; (c) adlı aktör envanterinin PN etiketiyle denetimi; (d) MM ara ölçütü; (e) dikey katmanın 'aynı sahne' kaynak listesi (aday 835).**"},
]

BAGLAR = [
 {"bag":"27:81 ↔ 30:53","kural":"L1","not":"**Tek yâ harfi farkla aynı ayet ve `esit` ikisinde de boş — fark bu kez KELİME İÇİNDE.** 27:80↔30:52 ile birlikte iki ardışık ayet çifti (aday 869)."},
 {"bag":"27:17 ↔ 27:83","kural":"L1","not":"**`وزع` korpusta beş geçişli, ikisi bu sûrede: Süleymân'ın orduları / mahşerde toplananlar. Aynı vezin, aynı edilgen çatı, altmış altı ayet arayla** (aday 873)."},
 {"bag":"27:22 ↔ 27:84","kural":"L1","not":"`حوط` sûrede iki geçiş, ikisi de 'bilgiyle kuşatma' kalıbında: hüdhüdün bilgi üstünlüğü / insanın bilgi eksikliği. Altmış iki ayet arayla, karşıt yön."},
 {"bag":"27:82 ↔ 27:85","kural":"L1","not":"**`وَقَعَ ٱلْقَوْلُ عَلَيْهِم` üç ayet arayla birebir — sûrenin üçüncü ayet-içi nakaratı; `nakarat` alanı ikisinde de sıfır** (aday 870)."},
 {"bag":"27:87 ↔ 27:89","kural":"L1","not":"`فزع` korpusta altı geçişli, ikisi bu sûrede ve iki ayet arayla: dehşete kapılma / o dehşetten güvende olma. Aynı nadir kök, karşıt iki durum."},
 {"bag":"27:89 ↔ 27:90","kural":"L1","not":"Ardışık karşıt çift: جَآءَ بِٱلْحَسَنَةِ / جَآءَ بِٱلسَّيِّئَةِ — aynı fiil, aynı yapı, zıt nesne."},
 {"bag":"27:25 · 37 · 56 · 67 ↔ 27:82","kural":"L1","not":"**`خرج` sûrede beş geçiş, beş ayrı 'çıkarılan': gizli olan · ordudan çıkarılanlar · şehirden çıkarılacak aile · topraktan çıkarılacak ölüler · yerden çıkarılan canlı.** Kök tek anlam alanında, nesnesi beş katmanda."},
 {"bag":"27:77 ↔ 27:89","kural":"L1","not":"`أمن` iki anlam alanında: iman (27:77) / güvende olma (27:89). 529 kümesinin sûre içi altıncı vakası (aday 874)."},
 {"bag":"27:59 ↔ 27:93","kural":"L1","not":"`قُلِ ٱلْحَمْدُ لِلَّهِ` sûrede iki kez ve ikisi de bir bölütü açıp kapatıyor: 27:59 doğa bölütünü açıyor, 27:93 sûreyi kapatıyor."},
 {"bag":"27:88 ↔ 17:26 · 84:8","kural":"L2","not":"`MM` (mef'ûl-i mutlak) biçimi korpusta yalnız üç ayette — ama alanın onarımı aşırı daralttığı için (175 → 3) bu sayı güvenilmez (aday 867)."},
 {"bag":"27:76 ↔ 27:92","kural":"L1","not":"Sûrenin iki 'kitab' türü adlı aktörü de `قُرْءان` — biri anlatıyor, diğeri okunuyor."},
]

pa = '/home/claude/repo/bulgular/aday_bulgular.json'
AD = json.load(open(pa, encoding='utf-8'))
AD['AH_neml'].extend(ADAYLAR)
json.dump(AD, open(pa, 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
print('aday_bulgular: AH_neml →', len(AD['AH_neml']), '| son no', AD['AH_neml'][-1]['no'])

pb = '/home/claude/repo/notlar/okuma_baglantilari.json'
BG = json.load(open(pb, encoding='utf-8'))
BG['AG_neml'].extend(BAGLAR)
json.dump(BG, open(pb, 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
print('okuma_baglantilari: AG_neml →', len(BG['AG_neml']))
