# -*- coding: utf-8 -*-
"""aday_ekle_onarim_01.py — TUR SONU ONARIM EVRESİ, birinci tur (877-888)."""
import json

ADAYLAR = [
{"no":877,
 "aday":"★ ONARIM 1 — ADSIZ AKTÖR ALANI ONARILDI. Üç değişiklik: (a) kök eşleşmesi → LEMMA eşleşmesi, (b) INDEF (belirsizlik) koşulu KALDIRILDI, (c) `aktor2.py`'deki altı kök anahtarından biri YANLIŞ YAZILMIŞTI ve korpusta hiç eşleşmiyordu — 57 token ölüydü. Lemma seçimi korpustan üretilen `adsiz_lemma_listesi.json` üzerinden İNDEKSLE yapıldı; hiçbir Arapça dizge elle yazılmadı. Kökler ÇAPA KONUMLARDAN (sûre:ayet:kelime) türetildi.",
 "olculen":{"eski":{"token":119,"ayet":101},"yeni":{"token":214,"ayet":185},
   "dusen_ayet":15,"kazanilan_ayet":99,"ortak":86,
   "olu_anahtar":{"etiket":"karye","olu_token":57,"sebep":"ى/ي yazım farkı"},
   "dislanan_lemma_token":44,
   "yeni_etiket":"mer (eril kişi) — امْرِئ/مَرْء ailesi imrae'den ayrıldı",
   "etiket_dagilimi_yeni":{"racül":58,"karye":57,"ferîk":34,"imrae":26,"tâife":24,"mer":11,"nefer":4},
   "alan_adi":"adsiz2 (eski 'adsiz' KORUNDU)"},
 "durum":"KAPALI","oncelik":"P0","kaynak":"onarım turu 1",
 "etiket":"onarım",
 "test_notu":"**Eski alan yalnız yanlış pozitif değil, yanlış negatif de üretiyordu ve üstelik anahtarlarından biri hiç çalışmıyordu.** Alan adı `adsiz2`; eski `adsiz` korundu ki sûre 27 okumasının ölçümleri yeniden üretilebilir kalsın. **Çapa konumlarının kendisi de iki kez yanlış çıktı ve düzeltildi (racül → أله'ye, karye → أول'e düşmüştü); çapa yöntemi doğrulama olmadan güvenli değil.**"},
{"no":878,
 "aday":"ONARIM 1'İN DOĞRULAMASI — DÜŞEN 15 AYETİN 15'İ DE ARTEFAKT, SINAMA 11/11, imrae DUYARLILIĞI %16 → %100. Düşen ayetlerin lemmaları: مَرِيئ (afiyetli), رِجْل (ayak), طائِف, فُرْقان, تَفْرِيق, مُتَفَرِّقَة, نُفُور (×5), فِرْق, طافَ, مُسْتَنفِرَة, فارِقَة. Hiçbiri kişi/topluluk değil — sıfır gerçek kayıp.",
 "olculen":{"dusen":15,"dusen_hepsi_artefakt":True,
   "sinama_kumesi":11,"gecen":11,
   "imrae":{"gercek_ayet":25,"eski_yakalanan":4,"yeni_yakalanan":25,
     "eski_duyarlilik":0.16,"yeni_duyarlilik":1.00,
     "eski_kesinlik":0.364,"yeni_kesinlik":1.00,"yeni_yanlis_pozitif":0},
   "sinama_ayetleri":["27:23","27:57","7:83","15:60","28:9","3:35","111:4","4:4","4:12","4:128","33:50"]},
 "durum":"KAPALI","oncelik":"P0","kaynak":"onarım turu 1",
 "etiket":"onarım doğrulaması",
 "test_notu":"**Aday 867'nin dersi uygulandı: onarım kendi yanlış negatif denetiminden geçirildi.** Anlatının adsız kadın aktörlerinin tamamı artık görünüyor: Lût'un karısı (beş ayet), Firavun'un karısı, İmrân'ın karısı, Ebû Leheb'in karısı. **Aday 802 ve 833 böylece KAPANDI.**"},
{"no":879,
 "aday":"★ VERİ ARIZASI — `kuran_veri.json`'da 112 AYETİN METNİNE BESMELE GÖMÜLÜ ve `harf` ALANI BUNDAN KİRLİ. 39:1 ile 45:2 birebir aynı ayet; harf 47'ye 28, fark tam 19 (besmelenin harf sayısı). `mora` ve `n` temiz (`ar_saf` üzerinden hesaplanıyor), `harf` kirli.",
 "olculen":{"etkilenen_ayet":112,"kirli_alan":["harf"],"temiz_alan":["n","mora","fs"],
   "ornek":{"39:1":{"harf":47},"45:2":{"harf":28},"fark":19},
   "sure_27_etkilenen":["27:1"],
   "27:1_kayitli_harf":46,"27:1_dogru_harf":27},
 "durum":"ACIK","oncelik":"P0","kaynak":"onarım turu 1",
 "etiket":"ararken bulundu (onarım sırasında)",
 "test_notu":"**Okuma sırasında hiç fark edilmedi çünkü `harf` yorumda kullanılmıyordu; ama ölçüm satırlarında yazıldı.** Sûre 27'de yalnız 27:1 etkileniyor: kaydedilen harf=46, doğrusu 27. **Onarım: `harf` `ar_saf`tan yeniden hesaplanmalı.** KAPATILAMAZ — `harf` alanının başka hangi ölçümlere girdiği (fHz, ebced, bits gibi kuran_veri alanları) taranmadı; **bu alanlar da kirli olabilir ve bu proje için ciddi bir borçtur.**"},
{"no":880,
 "aday":"★ ONARIM 2 — N-GRAM ALTYAPISI KURULDU (morfoloji tabanlı). Ayet iskeleti `morph.txt`'nin BÖLÜTLERİNDEN kurulur ve `CONJ|PREF` bölütleri (bağlaç önekleri) atılır. Üç alanı birden açıyor: nakarat, esit, 'aynı ifade'.",
 "olculen":{"ayet":6236,"kelime":77429,
   "cok_ayetli_ngram":15098,
   "n_dagilimi":{"3":6081,"4":3764,"5":2317,"6":1436,"7":909,"8":591},
   "v1_arizasi":"iskelet ham metinden kuruluyordu; 27:82 'ووقع' ile 27:85 'وقع' eşleşmiyordu",
   "cozulen":["baştaki bağlaç farkı (27:80↔30:52)","kelimeye kaynamış bağlaç (27:82↔27:85)"]},
 "durum":"KAPALI","oncelik":"P0","kaynak":"onarım turu 1",
 "etiket":"onarım",
 "test_notu":"**Aday 876'nın öngördüğü gibi tek altyapı üç alanı birden açtı.** Ve v1'in kendi arızası, aday 854'ün bulduğu arızanın kelime-bölütleme tarafındaki eşiydi: **aynı hata iki ayrı katmanda.** Morfoloji zaten bağlaç öneklerini ayırmış; ham metin yerine morfolojiyi taban almak sorunu kökten çözdü."},
{"no":881,
 "aday":"★ ONARIM 3 — `esit` YAKIN EŞLEŞMEYE AÇILDI (eşik 0,95). Korpusta 253 → 336 ayet. Eşik taranarak seçildi; yedi sınama çiftinin yedisi de geçiyor (en düşük benzerlik 94:5↔94:6'da 0,963). Kazanılan 84 yakın bağın tamamı elle denetlendi ve hepsi gerçek yakın-aynı ayet.",
 "olculen":{"eski_ayet":253,"yeni_ayet":336,"kazanilan":83,"kaybedilen":0,
   "tam_bag":1622,"yakin_bag":84,"esik":0.95,
   "sinama":7,"gecen":7,
   "sinama_benzerlikleri":{"27:80↔30:52":0.989,"27:81↔30:53":0.991,"1:2↔37:182":0.971,
     "94:5↔94:6":0.963,"27:71↔10:48":1.0,"27:58↔26:173":1.0,"26:108↔26:110":1.0},
   "alan_adi":"esit2 (tür alanı: 'tam' | 'yakin')"},
 "durum":"KAPALI","oncelik":"P0","kaynak":"onarım turu 1",
 "etiket":"onarım",
 "test_notu":"**ONARIMIN KENDİ YANLIŞ NEGATİFİ ÇIKTI VE DÜZELTİLDİ.** İlk sürüm yalnız 4-gram bloklama kullanıyordu; üç kelimelik ayetlerin 4-gram'ı olmadığı için **46 ayet kayboldu — içlerinde sûre 26'nın nakarat ayetleri de vardı.** İkinci sürümde tam eşleşmeler karma ile doğrudan bulunuyor (kayıp imkânsız), yakın eşleşmeler 3-gram bloklama ile aranıyor. **Aday 867'nin dersi bu turda İKİ KEZ tekrarladı: hem MM'de hem burada. Onarımın kendi denetimi artık zorunlu adım.**"},
{"no":882,
 "aday":"★ ONARIM 4 — `nakarat` AYET DÜZEYİNDEN N-GRAM DÜZEYİNE. Yeni tanım: aynı sûrede en az iki ayrı ayette geçen, en az üç kelimelik AZAMİ kelime n-gramı; tür 'tam' (ayetin tamamı) ya da 'ic' (ayet içi). Korpus 119 → 1950 ayet, sıfır kayıp. Sûre 27: 0 → 30 ayet, 17 kalıp.",
 "olculen":{"eski_ayet":119,"yeni_ayet":1950,"kaybedilen":0,
   "tur":{"ic":3147,"tam":133},
   "sure_26":{"eski":34,"yeni":62,"kalip":18},
   "sure_27":{"eski":0,"yeni":30,"kalip":17},
   "sure_27_guclu_kaliplar":[
     {"kalip":"aeile mea allah","ayet":[60,61,62,63,64],"n":3},
     {"kalip":"keyfe kane akibete","ayet":[14,51,69],"n":3},
     {"kalip":"vakaa'l-kavlu aleyhim","ayet":[82,85],"n":3},
     {"kalip":"ene atike bihi kable en","ayet":[39,40],"n":5}]},
 "durum":"KAPALI","oncelik":"P0","kaynak":"onarım turu 1",
 "etiket":"onarım",
 "test_notu":"**Aday 844/845/870'in üç nakaratının ÜÇÜ DE yakalandı.** Ve okumada fark edilmeyen dördüncü bir kalıp çıktı: **27:39 ↔ 27:40, beş kelimelik `ene âtîke bihî kable en` — ifrît ile kitaptan ilim sahibinin aynı cümleyi kurması.** Okumada bu iki ayet ayrı ayrı işlendi ama ortak kalıp görülmedi; **alan onarıldığında okumanın kaçırdığını gösterdi.** UYARI: 1950 ayet korpusun %31'i — alan artık çok geniş; yorumda `>=3 ayet` ya da `>=4 kelime` süzgeci kullanılmalı (sûre 27'de bu süzgeç 17 kalıbı 6'ya indiriyor)."},
{"no":883,
 "aday":"TEŞHİS DÜZELTMESİ — ADAY 868 YANLIŞTI. 868 'alanın 105 adlık envanterine cins isimler girmiş' diyordu. Ölçüldü: `pn_lemma_listesi.json` korpusla BİREBİR AYNI (106 = 106); listede olup morfolojide PN olmayan sıfır, tersi de sıfır. **`مُسْلِم` ve `نَصْرانِيّ`'yi PN etiketleyen MORFOLOJİNİN KENDİSİ.** Arıza envanterde değil, kaynak veride.",
 "olculen":{"iddia":"envantere cins isimler girmiş","dogru":"morfoloji PN etiketliyor",
   "pn_lemma_morfolojide":106,"envanterde":106,"fark":0,
   "cins_isim_adaylari":8,"cins_token":52},
 "durum":"KAPALI","oncelik":"P1","kaynak":"onarım turu 1",
 "etiket":"onarım sırasında ölçüldü (kendi kaydım düştü)",
 "test_notu":"**Dördüncü düşen kayıt** (801, 819, 843, burası). Ortak mekanizma bu kez farklı: **bir alanın çıktısındaki arızayı gördüm ve sebebini DOĞRULAMADAN alana yükledim.** Ders: 'alan X'i yanlış yapıyor' demeden önce X'in girdisi denetlenecek. Envanter korpustan üretildiği için (projenin kendi kuralı) doğruydu; hata bir katman yukarıdaydı."},
{"no":884,
 "aday":"ONARIM 5 — ADLI AKTÖRDE 'cins' TÜRÜ. Korpusun PN etiketindeki mensubiyet/soyut adlar silinmedi, YENİDEN SINIFLANDI: نَصْرانِيّ 15 · مُسْلِم 14 · يَهُود 9 · إِسْلام 6 · صابِئ 3 · جاهِلِيَّة 3 · سِلْم 1 · مَجُوس 1 = 52 token. Kayıp sıfır.",
 "olculen":{"ayrilan_token":52,"secim":"indeksle (elle Arapça yazılmadı)",
   "eski_tur":{"kisi":660,"yer":173,"kavim":150,"gayb":101,"kitab":101,"diger":17,"sahte-ilah":10},
   "yeni_tur":{"kisi":660,"yer":173,"kavim":108,"gayb":101,"kitab":101,"cins":52,"sahte-ilah":10,"diger":7},
   "sure_27_etkilenen":1,"alan_adi":"adli2"},
 "durum":"KAPALI","oncelik":"P1","kaynak":"onarım turu 1",
 "etiket":"onarım",
 "test_notu":"**Silme yerine yeniden sınıflama seçildi: hiçbir token kaybolmuyor, aktör sayımından ayrılıyor, karar geri alınabilir.** Sınırda bırakılanlar (جَنَّة, مَدِينَة, رَمَضان, جُمُعَة) kasten korundu — bunlar özel ad işlevi de taşıyor. **KAPATILAMAZ: 106 lemmanın tamamı tek tek denetlenmedi, yalnız açık mensubiyet/soyut adlar ayrıldı.**"},
{"no":885,
 "aday":"ONARIM 6 — MM (MEF'ÛL-İ MUTLAK) ARA ÖLÇÜTÜ. Geniş kural (V + aynı kök N, bitişik) 175 ayet; dar kural (V + aynı kök VN) 3 ayet; YENİ ara kural (w. kelimede V, w+1. kelimede aynı kökten ACC isim) **125 ayet.** Dar kuralın üç ayeti de yeni kuralın içinde. Sınama 4/4.",
 "olculen":{"genis":175,"dar":3,"ara":125,
   "dar_kural_kapsandi":True,
   "sinama":[["27:50",True],["27:21",True],["27:88",True],["27:58",False]],
   "sure_27_eski":[88],"sure_27_yeni":[21,50,88],
   "alan_adi":"mm2"},
 "durum":"KAPALI","oncelik":"P1","kaynak":"onarım turu 1",
 "etiket":"onarım",
 "test_notu":"**ONARIMIN İLK SÜRÜMÜ DE DÜŞTÜ: segment düzeyinde eşleşiyordu ve مَكَرُوا۟ fiilinden sonra zamir bölütü geldiği için 27:50'yi kaçırıyordu.** Kelime düzeyine çekilince 4/4. **Aday 867'nin dersi bu turda üçüncü kez tekrarladı.** Not: 27:58 (أَمْطَرْنَا ... مَطَرًا) bitişik olmadığı için hâlâ dışarıda; **'araya kelime girmiş mef'ûl-i mutlak' ayrı bir ölçüt ister ve bu KAPATILAMAZ.**"},
{"no":886,
 "aday":"ONARIM 7 — DİKEY KATMANIN 'AYNI SAHNE' ALANI. Her (hedef, ortak) çifti için katkı veren AYRI AYET sayısı ve ortak geçişlerin AYNI n-gram'ı paylaşma oranı hesaplanıyor; dört sınıf: A-tek-ayet (<=2, bastırılır) · B-tek-sahne (3-5) · B2-donmuş-kalıp (>5 ama ifade ortaklığı >=0,50) · C-birliktelik. `blok_dikey.py` çıktısına etiket olarak basılıyor.",
 "olculen":{"sinif":{"A-tek-ayet":6,"B-tek-sahne":9,"B2-donmus-kalip":3,"C-birliktelik":2},
   "eski_koruma_isaretledigi":7,"yeni_siniflama_isaretledigi":18,"vaka":20,
   "ayirt_edici_ornek":{"سطر|أول":{"ayet":9,"ifade":0.56,"sinif":"B2"},
     "عمي|صمم":{"ayet":8,"ifade":0.25,"sinif":"C"}},
   "olcut_v1_arizasi":"kesişim kullanıyordu; سطر▸أول 0,00 veriyordu"},
 "durum":"KAPALI","oncelik":"P0","kaynak":"onarım turu 1",
 "etiket":"onarım",
 "test_notu":"**Aday 850'nin sınırı çözüldü: ayrı ayet sayısı tek başına donmuş kalıbı anlamsal birliktelikten ayırmıyordu; ikinci ölçüt (aynı n-gram paylaşımı) ayırıyor** — سطر▸أول 0,56 (donmuş) ile عمي▸صمم 0,25 (gerçek) arasında net fark. **Eski koruma (hedef n<15) yirmi vakanın 7'sini işaretliyordu; yeni sınıflama 18'ini.** Ve ölçütün ilk sürümü de düştü (kesişim yerine en sık ortak n-gram oranı gerekti)."},
{"no":887,
 "aday":"★ SÛRE 27 ONARILMIŞ ALANLARLA YENİDEN ÖLÇÜLDÜ — OKUMA KAYITLARINDAN DEĞİŞENLER. adsız aktör 1 → 6 token (27:23, 34, 45, 55, 56, 57) · nakarat 0 → 30 ayet / 17 kalıp · esit 3 → 6 ayet (dört yakın bağ) · adlı aktör 25 → 24 + 1 cins · MM 1 → 3 ayet (27:21, 50, 88) · 27:1 harf 46 → 27.",
 "olculen":{"sure":27,
   "adsiz":{"eski":1,"yeni":6,"yeni_ayetler":[23,34,45,55,56,57]},
   "nakarat":{"eski":0,"yeni":30,"kalip":17,"guclu_kalip":6},
   "esit":{"eski":[3,58,71],"yeni":[3,53,58,71,80,81],
     "yakin_baglar":[["27:53","41:18",0.9811],["27:71","67:25",0.9825],
       ["27:80","30:52",0.9888],["27:81","30:53",0.9905]]},
   "adli":{"eski_kavim":4,"yeni_kavim":3,"cins":1},
   "mm":{"eski":[88],"yeni":[21,50,88]},
   "harf_duzeltmesi":{"27:1":{"kayitli":46,"dogru":27}}},
 "durum":"ACIK","oncelik":"P0","kaynak":"onarım turu 1",
 "etiket":"onarım sonrası yeniden ölçüm",
 "test_notu":"**Okuma metni (okuma_metni.json) ESKİ alanlarla yazıldı ve DEĞİŞTİRİLMEDİ** — eski ölçümler yeniden üretilebilir kalsın diye. Bu kayıt, hangi ölçüm satırlarının artık aşıldığını gösterir. **Üç yeni bulgu okuma sırasında görülmemişti: (1) 27:53 ↔ 41:18 yakın eşleşme, (2) 27:71 ↔ 67:25'in de yakın olduğu, (3) 27:39 ↔ 27:40 beş kelimelik ortak kalıp.** **Ve 27:34, 27:45, 27:55, 27:56'da adsız aktör var; okumada 'aktör yok' yazılmıştı.**"},
{"no":888,
 "aday":"ONARIM TURU 1 BİLANÇOSU — YEDİ ONARIM, ÜÇÜ KENDİ YANLIŞ NEGATİFİNİ ÜRETTİ VE DÜZELTİLDİ. Onarılan alanlar: adsız aktör · n-gram altyapısı · esit · nakarat · adlı aktör · MM · dikey kaynak sınıflaması. Kapanan adaylar: 802, 833, 844, 845, 850, 854, 867, 868 (teşhis düzeltmesiyle), 869, 870, 876.",
 "olculen":{"onarim":7,
   "kendi_yanlis_negatifini_ureten":[{"onarim":"esit v1","kayip":46,"sebep":"4-gram bloklama kısa ayetleri atlıyordu"},
     {"onarim":"MM ara v1","kayip":"27:21, 27:50","sebep":"segment düzeyinde eşleşme"},
     {"onarim":"dikey ifade ölçütü v1","kayip":"donmuş kalıplar","sebep":"kesişim yerine oran gerekliydi"}],
   "kapanan_aday":[802,833,844,845,850,854,867,868,869,870,876],
   "yeni_alanlar":["adsiz2","esit2","nakarat2","adli2","mm2"],
   "eski_alanlar_korundu":True,
   "yeni_veri":["adsiz_lemma_listesi.json","ayet_iskelet.json","ngram_indeks.json",
     "nakarat_kaliplari.json","dikey_kaynak_ornek.json"]},
 "durum":"KAPALI","oncelik":"P0","kaynak":"onarım turu 1",
 "etiket":"onarım bilançosu",
 "test_notu":"**Turun asıl dersi: YEDİ onarımın ÜÇÜ ilk sürümünde kendi yanlış negatifini üretti.** Aday 867 (MM'in 175→3 aşırı daralması) bunu bir kez göstermişti; bu turda üç kez daha tekrarladı. **Onarım protokolüne kalıcı madde: hiçbir onarım, eski alanın yakaladıklarının tamamını yakaladığı gösterilmeden kabul edilmez (`kaybedilen == 0` savı).** KALAN BORÇ: (a) `harf` alanının besmele kirliliği onarılmadı (aday 879) ve `fHz/ebced/bits` alanları hiç denetlenmedi; (b) esit yakın eşleşme yalnız 0,95 üstünü alıyor, 0,80-0,95 bandı (54 çift) denetlenmedi; (c) 26/27 nakarat karşılaştırması artık YAPILABİLİR ama yapılmadı (aday 781)."},
]

pa = '/home/claude/repo/bulgular/aday_bulgular.json'
AD = json.load(open(pa, encoding='utf-8'))
AD.setdefault('AI_onarim', []).extend(ADAYLAR)
json.dump(AD, open(pa, 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
print('aday_bulgular: AI_onarim →', len(AD['AI_onarim']), '| son no', AD['AI_onarim'][-1]['no'])
