# -*- coding: utf-8 -*-
"""aday_ekle_27_71_80.py — blok 27:71-80 adayları (854-864) ve bağları."""
import json

ADAYLAR = [
{"no":854,
 "aday":"★ `esit` ALANININ MEKANİZMASI BULUNDU — TAM DİZGE EŞLEŞMESİ; BAŞTAKİ TEK BAĞLAÇ HARFİ EŞLEŞMEYİ BOZUYOR. 27:80 ile 30:52 arasındaki TEK fark baştaki فَ; başka hiçbir fark yok. **`esit` alanı İKİSİNDE DE BOŞ.** Oysa dokuz ayet önce 27:71'de aynı alan beş hedefi birden yakalamıştı (altı ayet birebir aynı). Tam ölçüm: korpusta tam aynı metinli 87 küme (257 ayet); baştaki و/ف atılınca 94 küme (273 ayet).",
 "olculen":{"tam_esleme_kume":87,"tam_esleme_ayet":257,
   "esit_alani_dolu_ayet":253,
   "vf_kirpilinca_kume":94,"vf_kirpilinca_ayet":273,
   "yalniz_vf_farkiyla_kacan_kume":9,"kacan_ayet":29,
   "ornekler":[["1:2","37:182"],["3:51","19:36"],["7:120","26:46"],["20:9","79:15"],
     ["27:80","30:52"],["37:174","37:178"],["94:5","94:6"]],
   "not":"94:5 ↔ 94:6 ARDIŞIK iki ayet ve alan görmüyor"},
 "durum":"ACIK","oncelik":"P0","kaynak":"okuma blok 27:71-80",
 "etiket":"okuma sırasında ölçüldü",
 "test_notu":"**Üçüncü 'yanlış birim / yanlış tolerans' alanı; aday 833 ve 844 ile aynı aile.** adsız aktör: adlandırılmamışlık yerine BELİRSİZLİK · nakarat: tekrar yerine AYET TEKRARI · esit: benzerlik yerine TAM DİZGE. **Üçünün onarımı da aynı altyapıyı istiyor: n-gram / yaklaşık eşleme.** Ve aday 850'nin ihtiyacı (donmuş kalıbı anlamsal birliktelikten ayırmak) da aynı altyapı. **DÖRT P0 tek araçla çözülebilir.** ONARIM (ucuz): eşleme öncesi baştaki و/ف kırpılsın → 29 ayet kazanılır, maliyet sıfır. **KAPATILAMAZ: yalnız baştaki bağlaç farkı tarandı; ara farklar (tek kelime ekleme/çıkarma) ölçülmedi.**"},
{"no":855,
 "aday":"27:71 — OKUMADA İLK ÇOK HEDEFLİ `esit`: BEŞ HEDEF. 10:48 · 21:38 · 34:29 · 36:48 · 67:25. Altı ayetin altısı da BİREBİR aynı metin (وَيَقُولُونَ مَتَىٰ هَٰذَا ٱلْوَعْدُ إِن كُنتُمْ صَٰدِقِينَ). `nakarat` alanı altısında da sıfır — doğru, çünkü tekrar sûre içi değil, sûreler arası.",
 "olculen":{"ayet":"27:71","esit_hedef":5,
   "hedefler":[[10,48],[21,38],[34,29],[36,48],[67,25]],
   "hepsi_birebir":True,"nakarat_alani":0,"dis_dugum":5,
   "fasila":"aynı (صَٰدِقِينَ) — 27:64 ile de ortak"},
 "durum":"KAPALI","oncelik":"P2","kaynak":"okuma blok 27:71-80",
 "etiket":"okuma sırasında ölçüldü",
 "test_notu":"**Alan burada tam olarak yapması gerekeni yapıyor ve bu, aday 854'ün kontrol vakası: aynı sûrede, dokuz ayet arayla, alan bir kez mükemmel çalışıyor bir kez tümüyle kör kalıyor — tek fark bir harf.** Ayrıca `nakarat` ile `esit` arasındaki iş bölümü netleşti: nakarat sûre içi, esit sûreler arası. **İkisinin de ayet-altı katmanı yok.**"},
{"no":856,
 "aday":"ADAY 804 KAPANDI — SÛRE 27'DE ALTI MÜHÜR, ALTI FARKLI ÇİFT, ALTISI DA `م` FÂSILALI VE ALTISI DA GEÇERLİ. Son sınama 27:78 (`عَزِيز|عَلِيم`, gönderge هُوَ, mercii رَبّ) tuttu. Sûrenin dokuz `م` fâsılasının altısı mühür; kalan üçü (27:23, 26, 29) mühürsüz ve üçü de okundu.",
 "olculen":{"sure":27,"muhur_sayisi":6,"farkli_cift":6,"hepsi_gecerli":True,
   "muhurler":[[6,"حَكِيم|عَلِيم"],[9,"عَزِيز|حَكِيم"],[11,"غَفُور|رَحِيم"],
     [30,"رَحْمٰن|رَحِيم"],[40,"غَنِيّ|كَرِيم"],[78,"عَزِيز|عَلِيم"]],
   "mim_fasila_toplam":9,"mim_muhur":6,"mim_muhursuz":[23,26,29],
   "on_kayit_sinamalari":[["27:40","tuttu"],["27:78","tuttu"]]},
 "durum":"KAPALI","oncelik":"P1","kaynak":"okuma blok 27:71-80",
 "etiket":"ön-kayıt sınaması (tamamlandı)",
 "test_notu":"**Ön-kayıt EKSİK alan (esma_k geçerliliği) üzerine kurulmuştu, ZAYIF etiketliydi ve İKİ SINAMANIN İKİSİNDE DE TUTTU.** Aday 722'nin deseni (eksik alan üzerine kurulan tahminler düşer) burada tutmadı. **Neden: mühür bayrağı aslında eksik alanın kendisi değil, onun üzerine kurulu YAPISAL bir hesap (bitişiklik + son konum) ve yapısal hesap çalışıyor** (aday 818). Genelleme adayı: **'azınlık fâsıla harfi esmâ mührüne ayrılır' — sûre 27'de 6/9. Sonraki sûrelerde sınanacak; sûre 26 fâsıla tekdüzeliği nedeniyle uygun değil.**"},
{"no":857,
 "aday":"ADAY 803 KAPANDI — `مُبِين` SÛRE 27'DE 6/6 ARTEFAKT. 27:1 (gönderge kitâb) · 27:13 (sihr) · 27:16 (fadl) · 27:21 (sultân) · 27:75 (kitâb) · 27:79 (hak). Hiçbirinde gönderge ilâhî değil; altısı da fâsıla konumunda; altısı da mühürsüz. Aynı blokta `مُؤْمِن` dizisi de kapandı: 3/3 artefakt (27:2, 15, 77), üçünde de gönderge insan. `آخِر` 4/4 artefakt (27:3, 4, 5, 66), dördünde de gönderge âhiret.",
 "olculen":{"mubin":{"token":6,"artefakt":6,"ayetler":[1,13,16,21,75,79],
    "gondergeler":["kitâb","sihr","fadl","sultân","kitâb","hak"]},
  "mumin":{"token":3,"artefakt":3,"ayetler":[2,15,77],"gonderge":"insan"},
  "ahir":{"token":4,"artefakt":4,"ayetler":[3,4,5,66],"gonderge":"âhiret"},
  "sure_26_mumin":{"token":15,"artefakt":15},
  "iki_surede_mumin_toplam":18},
 "durum":"KAPALI","oncelik":"P0","kaynak":"okuma blok 27:71-80",
 "etiket":"okuma sırasında ölçüldü (dizi sûre sonuna kadar okundu)",
 "test_notu":"**Ders 774 karşılandı: dizi sûre sonuna kadar okunmadan kapatılmadı.** Üç lemma, üç dizi, on üç token, **hepsi artefakt.** Sûre 26'nın 15 `مُؤْمِن` tokeniyle birlikte **iki sûrede on sekiz `مُؤْمِن` tokeni ve hepsi artefakt.** **Esmâ tablosunun sıfat-esmâ lemmaları (مُبِين, مُؤْمِن, آخِر) için gönderge denetimi olmadan token üretmesi artık tam sayımla belgelenmiş.** ONARIM: bu üç lemma için 'fâsıla konumunda ve mühürsüzse artefakt say' kuralı **bu iki sûrede %100 doğru** — ama genelleme korpus taramasıyla sınanmalı."},
{"no":858,
 "aday":"ADAY 818'İN ÖN-KAYDI BEŞİNCİ, ALTINCI VE YEDİNCİ KEZ SINANDI — ÜÇÜ DE ARTEFAKT. 27:75 مُبِين (kitâb) · 27:77 مُؤْمِن (insan çoğul) · 27:79 مُبِين (hak). Ayrım: mühür tokeninde 12/12 geçerli, mühürsüz tokende 0/20. **Sekiz sınamanın yedisi geçti; TEK sınama kaldı: 27:88 خَبِير.**",
 "olculen":{"sinama_no":[5,6,7],"ayetler":["27:75","27:77","27:79"],
   "gecerli":[False,False,False],
   "muhursuz_token_toplam":20,"muhursuz_gecerli":0,
   "muhur_token_toplam":12,"muhur_gecerli":12,
   "ayrim":"32/32","kalan_sinama":["27:88 خَبِير"]},
 "durum":"ACIK","oncelik":"P0","kaynak":"okuma blok 27:71-80",
 "etiket":"ön-kayıt sınaması",
 "test_notu":"**Ayrım 32/32 oldu ve ön-kaydın kaderi tek bir ayete indi.** Ön-kayıt: 'en az biri geçerli çıkacak ve ayrım bozulacak'; gerekçe mühür bayrağının YAPISAL olması ve tek başına gelen geçerli bir ismi yakalayamaması. **27:88 okunduğunda ön-kayıt ya tutacak ya düşecek; iki sonuç da bilgi verir:** tutarsa bayrak 'yeterli ama gerekli değil' olarak kalır; düşerse sûre 27'de bayrak kusursuz bir vekil ölçü olmuş olur ve genelleme korpus taramasına havale edilir."},
{"no":859,
 "aday":"z'NİN UZUNLUK NORMALİZASYONU — DÖRDÜNCÜ VE EN ÇARPICI VAKA: TEK LAFIZ, İKİ LAFIZDAN YÜKSEK z. 27:79'da n=7 ve TEK lafız → allah z=2,33 ve ★★. 27:63'te n=20 ve İKİ lafız → allah z=1,47 ve SIFIR. Sûrenin en yüksek eksen z'si 27:59 (n=12, iki lafız, z=2,80).",
 "olculen":{"vakalar":[
   {"ayet":"27:79","n":7,"lafiz":1,"allah_z":2.33,"yildiz":2},
   {"ayet":"27:63","n":20,"lafiz":2,"allah_z":1.47,"yildiz":0},
   {"ayet":"27:59","n":12,"lafiz":2,"allah_z":2.80,"yildiz":2},
   {"ayet":"27:44","n":28,"eksen_isareti":3,"allah_z":0.19,"rab_z":1.20,"yildiz":1,"kaynak":"uzunluk"}],
  "sonuc":"z eksen SAYISINI değil eksen/uzunluk ORANINI ölçüyor"},
 "durum":"ACIK","oncelik":"P1","kaynak":"okuma blok 27:71-80",
 "etiket":"okuma sırasında ölçüldü",
 "test_notu":"**Aday 827/837/847'nin dördüncü ve en net vakası: tek lafız iki lafızdan yüksek z veriyor.** Dört vaka aynı sûrede ve tek değişken n. **Yıldız alanının 'eksen' ölçüsü aslında 'eksen yoğunluğu' — bu ayrı bir ölçüdür ve adı alanda görünmüyor.** TUR SONU: ham sayı ve normalize oran ayrı alanlar olarak üretilip hangisinin yorumda kullanıldığı kayda geçirilecek."},
{"no":860,
 "aday":"XREF YOĞUNLUĞU DÖRDÜNCÜ VERİ — 27:80'DE BEŞ 3-GRAM VE BEŞİ DE TEK AYETE (30:52). Önceki üç vaka: 27:10 (altı bağ), 27:19 (dokuz 3-gram'ın sekizi 46:15'e), 27:55 (dört 3-gram'ın dördü 7:81'e). **Dördünde de hedef tek bir ayet ve o ayet neredeyse birebir aynı metin.**",
 "olculen":{"vakalar":[
   {"ayet":"27:80","gram_3":5,"hedef":"30:52","fark":"baştaki فَ"},
   {"ayet":"27:55","gram_3":4,"hedef":"7:81"},
   {"ayet":"27:19","gram_3":9,"tek_hedefe":8,"hedef":"46:15"},
   {"ayet":"27:10","bag":6}],
  "sonuc":"yüksek xref yoğunluğu = korpusta neredeyse aynı ayetin başka bir yerde bulunması"},
 "durum":"ACIK","oncelik":"P1","kaynak":"okuma blok 27:71-80",
 "etiket":"okuma sırasında ölçüldü",
 "test_notu":"**Aday 797/840 netleşti ve bir işlev kazandı: xref yoğunluğu, `esit`in kaçırdığı yakın-eşleşmeleri BULUYOR.** 27:80'de `esit` boş ama beş 3-gram tek hedefe düşüyor — **yani xref yoğunluğu, aday 854'ün onarımı için hazır bir aday üreteci.** ÖN-KAYIT: korpusta 'dört veya daha fazla 3-gram'ı tek hedefe düşen ve `esit`i boş olan' ayetler taranırsa, çıkanların büyük çoğunluğu yakın-eşleşme olacak. TUR SONU'nda koşulacak."},
{"no":861,
 "aday":"SÛRE 27'DE 529 KÜMESİ BEŞ VAKAYA ÇIKTI VE `هدي` DÖRT ANLAM ALANINA ULAŞTI. Vakalar: سمو (gök/ad) · هدي (yol bulma / hediye / tanıma / hidâyet) · طير (kuş/uğur) · كشف (açma/giderme) · خلف (halife/ayrılığa düşme). Otomatik tespit ölçütü beşinde de çalışmadı; skor 2/9.",
 "olculen":{"sure":27,"vaka_sayisi":5,
   "vakalar":[{"kok":"سمو","alan":2},{"kok":"هدي","alan":4,"ayetler":[24,35,36,41,63,77]},
     {"kok":"طير","alan":2},{"kok":"كشف","alan":2},{"kok":"خلف","alan":2,"ayetler":[62,76]}],
   "olcut_skoru":"2/9",
   "karsi_ornek":{"kok":"نظر","gecis":8,"alan":1}},
 "durum":"ACIK","oncelik":"P0","kaynak":"okuma blok 27:71-80",
 "etiket":"okuma sırasında ölçüldü",
 "test_notu":"**`هدي` sûrede altı geçiş ve DÖRT anlam alanı — 529 kümesinin en dallanmış vakası.** Ve karşı örnek güçlendi: `نظر` sûrede SEKİZ geçiş ve tek anlam alanı. **Sorun kesinlikle sıklık değil, kökün lemma yapısı** (هُدَى/هَدِيَّة ayrı lemmalar; نظر tek lemma ailesi). **P0 #5'in lemma katmanı için sınama kümesi dokuz vakalık.** Otomatik ölçüt 2/9'da; **terk edilmesi önerisi güçleniyor.**"},
{"no":862,
 "aday":"BLOKTA YILDIZLARIN TAMAMI EKSENDEN — OKUMADA İLK KEZ. ★★ 3 (27:74 Rab z=2,34 · 27:78 Rab z=2,34 · 27:79 allah z=2,33) · ★ 1 (27:73 Rab z=1,81). Dördünde de tek kaynak eksen; hapaks, pas, uzunluk katkısı sıfır.",
 "olculen":{"blok":"27:71-80",
   "yildizlar":[["27:73",1,"rab",1.81],["27:74",2,"rab",2.34],
     ["27:78",2,"rab",2.34],["27:79",2,"allah",2.33]],
   "diger_kaynaklar":0,
   "sure_rab_ayetleri":[8,19,26,40,44,73,74,78,91,93],
   "blok_rab":3},
 "durum":"KAPALI","oncelik":"P2","kaynak":"okuma blok 27:71-80",
 "etiket":"okuma sırasında ölçüldü",
 "test_notu":"**Okumada ilk kez bir blokta yıldız kaynaklarının tamamı eksen.** Önceki bloklarda kaynaklar hapaks, pas ve uzunluktu; içerik hiçbirinde kaynak olmamıştı ve burada da değil. **Not: 27:78'de mühür var ve mühür yıldıza KATKI VERMİYOR — yıldızı üreten yalnız Rab.** Esmâ ve yıldız alanları birbirinden bağımsız çalışıyor; bu, çıpa/yıldız korelasyonu hesaplanırken esmâ'nın kontrol değişkeni olarak kullanılabileceği anlamına gelir."},
{"no":863,
 "aday":"27:46 ↔ 27:72 — AYNI FİİL, AYNI VEZİN, İKİ AYRI KAVİM. 27:46'da Sâlih Semûd'a: لِمَ تَسْتَعْجِلُونَ بِٱلسَّيِّئَةِ. 27:72'de Mekke'ye: بَعْضُ ٱلَّذِى تَسْتَعْجِلُونَ. Aynı bab X fiili, yirmi altı ayet arayla, ikisi de azabın çabuklaştırılmasını isteme bağlamında.",
 "olculen":{"ayetler":["27:46","27:72"],"kok":"عجل","n":47,
   "fiil":"testa'cilûn (عجل kökü, bab X)","bab":"X","mesafe":26,
   "muhataplar":["Semûd","Mekke"],"esit_alani":[[],[]]},
 "durum":"ACIK","oncelik":"P1","kaynak":"okuma blok 27:71-80",
 "etiket":"okuma sırasında ölçüldü",
 "test_notu":"**Aday 812'nin ('konuşmacı-arası kalıp yankısı') ikinci vakası ve bu kez MUHATAP değişiyor, konuşmacı değil.** 27:34↔27:37'de kraliçe/Süleymân, burada Semûd/Mekke. **`esit` alanı ikisinde de boş** (kelime örtüşmesi tek). **`esit`in sekizinci eşik türü adayı iki vakaya çıktı; ayrıca 'muhatap değişimi' ile 'konuşmacı değişimi' ayrı alt türler olabilir.**"},
{"no":864,
 "aday":"BLOK 27:71-80 BİLANÇOSU. Yıldız: ★★★ 0 · ★★ 3 · ★ 1 · yıldızsız 6. **Kaynakların tamamı eksen (Rab x3, lafız x1); içerikten sıfır.** İltifât 0/10. Esmâ token 5: üçü artefakt, ikisi geçerli mühür. Allah lafzı 1 · **Rab 3 — okumada en yüksek blok Rab sayısı.** Adlı aktör 2 (قُرْءان türü KİTAB — sûrede ilk ve tek) · adsız aktör 0. Yeni kök 2 (ردف, كنن). Hapaks 0. **Üç dizi kapandı.** Yıldızsız oran %60 — altı blok sonra ilk kez %80'in altında.",
 "olculen":{"blok":"27:71-80","ayet":10,
   "yildiz":{"3":0,"2":3,"1":1,"0":6},
   "yildiz_kaynak":{"rab":3,"lafiz":1,"icerik":0},
   "iltifat":0,"esma_token":5,"esma_artefakt":3,"muhur":1,
   "allah_lafzi":1,"rab":3,"adli_aktor":2,"adsiz_aktor":0,
   "yeni_kok":2,"hapaks":0,"kafiye_kirilmasi":0,"mim_fasila":1,
   "esit_dolu":1,"ort_n":8.6,
   "kapanan_diziler":["مُبِين 6/6 artefakt","مُؤْمِن 3/3 artefakt","mühür 6/6 geçerli"]},
 "durum":"KAPALI","oncelik":"P2","kaynak":"okuma blok 27:71-80",
 "etiket":"okuma sırasında ölçüldü",
 "test_notu":"Sûre 27 ilk seksen ayet: ★★★ 6 · ★★ 8 · ★ 6 · yıldızsız 60. Esmâ token 32 (20 artefakt, 12 geçerli mühür tokeni). Allah lafzı 24 · Rab 8 → **A/R = 3,00** (kırkta 1,40 · ellide 2,80 · altmışta 3,40 · yetmişte 4,60; makro 2,25). **Oran yetmişte tepe yapıp düştü — monoton artış kaydı DÜŞTÜ; bu blokta üç Rab geldi ve oran geriledi.** İltifât 3/80. **Ortalama n=8,6 — okumadaki en kısa blok.**"},
]

BAGLAR = [
 {"bag":"27:71 ↔ 10:48 · 21:38 · 34:29 · 36:48 · 67:25","kural":"L1","not":"**`esit` beş hedefli — okumada ilk çok hedefli eşleşme; altı ayetin altısı da birebir aynı metin** (aday 855)."},
 {"bag":"27:80 ↔ 30:52","kural":"L1","not":"**Tek harf farkla (baştaki فَ) aynı ayet ve `esit` İKİSİNDE DE BOŞ.** Beş xref 3-gram'ın beşi de hedefe düşüyor — bağ görünüyordu, alan görmedi (aday 854/860)."},
 {"bag":"27:46 ↔ 27:72","kural":"L1","not":"Aynı bab X fiili (تَسْتَعْجِلُونَ), yirmi altı ayet arayla, iki ayrı muhataba: Semûd ve Mekke. `esit` ikisinde de boş (aday 863)."},
 {"bag":"27:25 ↔ 27:74","kural":"L1","not":"`علن` sûrede iki geçiş ve iki ayet de aynı yapıda: 'gizleneni de açığa vurulanı da bilir' — biri hüdhüdün ağzında, biri anlatıcının; elli ayet arayla."},
 {"bag":"27:65 ↔ 27:75","kural":"L1","not":"`غيب` sûrede iki geçiş, on ayet arayla: 'Allah'tan başkası gaybı bilmez' / 'gizli hiçbir şey yoktur ki kitapta olmasın' — **aynı konunun iki yüzü: bilinmezlik ve kayıt.**"},
 {"bag":"27:40 ↔ 27:73","kural":"L1","not":"`شكر` sûrede iki geçiş, karşıt yönde: 27:40'ta Süleymân'ın şükrü (kök üç kez), burada insanların çoğunun şükürsüzlüğü."},
 {"bag":"27:62 ↔ 27:76","kural":"L1","not":"`خلف` iki anlam alanında: خُلَفَآء *(halifeler)* / يَخْتَلِفُونَ *(ayrılığa düşüyorlar)*. 529 kümesinin sûre içi beşinci vakası (aday 861)."},
 {"bag":"27:24 · 35 · 36 · 41 · 63 ↔ 27:77","kural":"L1","not":"**`هدي` sûrede altı geçiş ve DÖRT anlam alanı: yol bulma · hediye · tanıma · hidâyet.** 529 kümesinin en dallanmış vakası (aday 861)."},
 {"bag":"27:74 ↔ 28:69","kural":"L2","not":"xref üç 3-gram'ın üçü de bu ayete: `ربّ + علم + أكنن` kalıbı birebir."},
 {"bag":"27:6 ↔ 27:9 ↔ 27:11 ↔ 27:30 ↔ 27:40 ↔ 27:78","kural":"L1","not":"**Sûrenin altı mührü: altı FARKLI çift, altısı da `م` fâsılalı, altısı da GEÇERLİ. Aday 804 kapandı** (aday 856)."},
 {"bag":"27:1 · 13 · 16 · 21 · 75 ↔ 27:79","kural":"L1","not":"**`مُبِين` sûrede altı token ve altısı da ARTEFAKT** (kitâb, sihr, fadl, sultân, kitâb, hak). Dizi kapandı; aday 803 kapandı (aday 857)."},
]

pa = '/home/claude/repo/bulgular/aday_bulgular.json'
AD = json.load(open(pa, encoding='utf-8'))
AD['AH_neml'].extend(ADAYLAR)
json.dump(AD, open(pa, 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
print('aday_bulgular: AH_neml →', len(AD['AH_neml']), '| son no', AD['AH_neml'][-1]['no'])

pb = '/home/claude/repo/notlar/okuma_baglantilari.json'
BG = json.load(open(pb, encoding='utf-8'))
BG['AG_neml'].extend(BAGLAR)
json.dump(BG, open(pb, 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
print('okuma_baglantilari: AG_neml →', len(BG['AG_neml']))
