# -*- coding: utf-8 -*-
"""aday_ekle_30_rum.py — sûre 30 (Rûm) adayları (948-958) ve bağları."""
import json

ADAYLAR = [
{"no": 948,
 "aday": "★★ ÇIPA TARAYICISI SÛRE 30'DA ÇÖKTÜ — VE SEBEP ÜÇ SÜRÜMÜN ORTAK VARSAYIMI. Anma **2/9**, kesinlik 2/5. Sûre 27'de 4/4, 28'de 3/3, 29'da (düzeltilmiş) 3/3 idi. **Yedi çıpa kaçtı ve yedisinin ortak özelliği tek: DÜZ HABER CÜMLESİ.** Tarayıcının sekiz işaret ailesinin hepsi bir SÖZ EYLEMİ işareti arıyor — şart, ta'lîl, recâ, yeti sınırı, görünüş, ölçü, gözleme çağrısı. **Ama Kur'an'ın en yoğun olgu katalogları düz haberdir.**",
 "olculen": {"sure_30": {"cipa": 9, "tarayici_adayi": 5, "dogru_pozitif": 2, "anma": "2/9", "kesinlik": "2/5"},
             "onceki_sureler": {"27": "4/4", "28": "3/3", "29": "3/3 (düzeltilmiş)"},
             "kacan_cipalar": ["30:11", "30:19", "30:24", "30:27", "30:40", "30:48", "30:54"],
             "hepsinin_ortak_ozelligi": "edim = haber, hiçbir işaret ailesi tetiklenmiyor",
             "korluk_tam_sayim": {"uc_arti_olgu_koklu_ayet": 221, "havuzda_olan": 86,
                                  "hicbir_aile_tetiklemeyen": 135, "oran_yuzde": 61,
                                  "bunlardan_ayi_koku_tasiyan": 22},
             "sure_30_yogun_ayetler": {"toplam": 10, "kacan": 8,
                                       "kacanlar": ["30:8", "30:19", "30:22", "30:23", "30:24", "30:27", "30:40", "30:48"]},
             "dogru_pozitifler": {"30:46": "B_ta'lîl + C_recâ", "30:50": "G_bakış EMİR kolu"}},
 "durum": "ACIK", "oncelik": "P0", "kaynak": "okuma sûre 30",
 "etiket": "aday 924'e üçüncü katman",
 "test_notu": "**Sûre 27-29 varsayımı doğrulamış GÖRÜNÜYORDU çünkü o sûrelerin çıpaları tesadüfen işaretliydi.** Sûre 30 ilk kez düz haberli bir olgu kataloğu sunuyor ve tarayıcı onu bütünüyle kaçırıyor. **Bu, aday 924'ün ölçümüne üçüncü katman:** v2 kök listesine bağlıydı, v3 işaret ailelerine, v4 lemmaya — **ama üç sürümün ortak varsayımı 'çıpa bir söz eylemi işareti taşır' ve bu yanlış.** Önerilen çözüm ölçülmeden yazılmamalı; **bir `H_katalog` ailesi (أيي kökü + 2 ya da daha fazla olgu lemması) havuzu ne kadar büyütür ve kesinliği ne kadar düşürür, korpus çapında ölçülmeli.** KAPATILAMAZ olan yan: sûre 30'un dokuz çıpası tek okuyucunun kararı; ikinci bir okuma olmadan anma tabanının kendisi sınanmış değil."},

{"no": 949,
 "aday": "★★ OKUMANIN ÜÇÜNCÜ L4'Ü — VE BOŞ KALAN ÜÇÜNCÜ KOL DOLDU. 30:48 **MEKANİZMA** kolundan: beş aşamalı bir süreç, her aşama adlandırılmış ve her biri bir öncekinden `فَ` ile türetilmiş — rüzgârların gönderilmesi → bulutun kaldırılması → gökte yayılması → parçalara ayrılması → yağmurun aradan çıkması. Ara durumlar adlandırılıyor (`سَحاب`, `كِسَف`, `وَدْق`) ve çıkışın yeri belirtiliyor (`مِنْ خِلَٰلِهِۦ`).",
 "olculen": {"L4_kayitlari": {"29:14": "ölçü", "29:40": "sınıflama", "30:48": "MEKANİZMA"},
             "ucu_de_orneklendi": True,
             "30:48_asamalar": ["إرسال الرياح", "إثارة السحاب", "بسط في السماء",
                                "جعل كسفاً", "خروج الودق من خلاله"],
             "ara_durum_adlari": ["سَحاب", "كِسَف", "وَدْق"],
             "merdiven_kaniti": {"30:24": "aynı olgu, iki aşama → L2",
                                 "30:48": "ara aşamalar açılınca → L4"},
             "okunan_ayet_bes_sure": 379, "L4_sayisi": 3, "yogunluk_yuzde": 0.8,
             "dar_kokler": {"ودق": 2, "كسف": 5, "سحب": 11, "ثور": 5}},
 "durum": "KAPALI", "oncelik": "P0", "kaynak": "okuma sûre 30",
 "etiket": "P0 #6'ya ek veri, aday 925'in tamamlanması",
 "test_notu": "**Aday 925'in 'üçüncü kol (mekanizma) hâlâ boş' kaydı kapandı.** Ve asıl bulgu karşılaştırmada: **30:24 ile 30:48 AYNI OLGUYU (yağmur) anlatıyor, biri iki aşamada biri beş aşamada, ve merdiven ikisine farklı basamak veriyor.** Bu, **merdivenin aynı olguda ayrım yapabildiğinin ilk ölçülü kanıtı** — kademe konuyu değil İDDİA YAPISINI ölçüyor. Yan bulgu: 30:48 üç dar kökü (2, 5, 11 ayet) tek ayette topluyor ve **hiçbiri hapaks2 değil**; ayetin yıldızı yalnız uzunluktan geliyor — 28:12'nin 'nadirlik yığılması ile hapaks ayrı şeyler' ayrımının okumada en yoğun örneği."},

{"no": 950,
 "aday": "★ `esit2` OKUMANIN EN YÜKSEK DEĞERLERİNİ VERDİ — VE İKİ ARDIŞIK AYET, İKİ ARDIŞIK AYETE BAĞLANDI. **30:52 ↔ 27:80 (0,9888)** ve **30:53 ↔ 27:81 (0,9905)**. Okumada ilk kez bir ayet ÇİFTİ, başka bir sûredeki ayet ÇİFTİNE sırasıyla bağlanıyor; 0,9905 mukattaa TAM'ları dışında ölçülen en yüksek değer. **Karşı uç OKUNMUŞ bir bölüt olduğu için doğrulanabilir durumda.**",
 "olculen": {"cift_cifte": {"30:52 ↔ 27:80": 0.9888, "30:53 ↔ 27:81": 0.9905},
             "onceki_yakin_kayitlari": {"29:28 ↔ 7:80": 0.9615, "30:37 ↔ 39:52": 0.9649},
             "30:52_xref": "beş 3-gram'ın beşi de 27:80'e — okumada en tam örtüşme",
             "30:53_xref": "dört 3-gram'ın dördü de 27:81'e",
             "sure_30_yakin_sayisi": 3, "sure_27_28_yakin": 0,
             "alanin_sinir": "esit2 AYET düzeyinde çalışıyor, BÖLÜT düzeyinde değil"},
 "durum": "ACIK", "oncelik": "P1", "kaynak": "okuma sûre 30",
 "etiket": "aday 929'un ikinci yapısal bulgusu",
 "test_notu": "**Aday 929'un 'üçlüyü tek küme olarak gören alan yok' kaydıyla aynı aile ve bir basamak yukarısı: burada bağlanan şey ayet değil BÖLÜT.** `esit2` iki ayrı ikili bağ veriyor ve bölüt yapısı ancak ikisi yan yana okununca görünüyor. **TUR SONU: korpus çapında 'ardışık ayet çifti ↔ ardışık ayet çifti' taraması yazılabilir — esit2'nin mevcut kayıtları üzerinden, ek ölçüm gerektirmeden.** KAPATILAMAZ: kaç böyle bölüt çifti olduğu sayılmadı."},

{"no": 951,
 "aday": "★ ADAY 929'UN ÜÇLÜSÜ ÜÇÜNCÜ UÇTAN GÖRÜLDÜ VE EŞKENAR OLMADIĞI ORTAYA ÇIKTI. 30:34 okununca üçlü **{16:55, 29:66, 30:34}** tamamlandı: **30:34 ↔ 16:55 = 1,0 (TAM)** · 30:34 ↔ 29:66 = 0,9275 · 29:66 ↔ 16:55 = 0,9275.",
 "olculen": {"uclu": ["16:55", "29:66", "30:34"],
             "oranlar": {"30:34 ↔ 16:55": 1.0, "30:34 ↔ 29:66": 0.9275, "29:66 ↔ 16:55": 0.9275},
             "yapi": "eşkenar DEĞİL — 16:55 ile 30:34 birebir aynı, 29:66 ikisinden de aynı uzaklıkta",
             "yan_bulgu": "30:34 ve 29:66'nın İKİSİNDE DE i'râb alanı tamamen boş; ölçüm bu ortaklığı bağlamıyor"},
 "durum": "KAPALI", "oncelik": "P1", "kaynak": "okuma sûre 30",
 "etiket": "aday 929'un tamamlanması",
 "test_notu": "**Aday 929 'alan üçlüyü ikili bağlarla veriyor' demişti; eksik olan, bağların AĞIRLIKLARININ farklı olduğuydu.** Üç uç da okunmadan küme yapısı görünmüyor — **ve bu, okumanın ölçümden ayrı bir bilgi ürettiği nadir vakalardan biri:** alan üç kaydı da vermişti, ama hangisinin merkez hangisinin uç olduğu ancak üçü yan yana konunca çıktı."},

{"no": 952,
 "aday": "★ OKUMADA ★★★'I İKİ BAĞIMSIZ KAYNAKTAN ALAN İLK AYET — VE FORMÜLÜN BİLGİ KAYBI. 30:17'de **hapaks z=3,38 VE allah z=2,80**, ikisi de eşik bölgesinde. Formül en büyüğünü alıyor, **toplamıyor.**",
 "olculen": {"30:17": {"hapaks_z": 3.38, "allah_z": 2.80, "yildiz": 3, "ilt": "13>2"},
             "korpus_iki_arti_olcut": 89, "sure_30_ornek": 1,
             "onceki_vaka": {"29:10": "n=1,97 ve allah=2,05, ikisi de eşik üstü ama ★★"},
             "formul_kurali": "max(|z|) — toplam değil"},
 "durum": "ACIK", "oncelik": "P2", "kaynak": "okuma sûre 30, tam sayım",
 "etiket": "yıldız formülünün sınırı",
 "test_notu": "**TAM SAYIM: korpusta iki ya da daha fazla ölçütü |z|>2 olan 89 ayet var ve formül hiçbirine ek ağırlık vermiyor.** İki bağımsız olgunun birlikteliği tek olgudan daha dikkat çekici olabilir ama nişan aynı. **Bu bir arıza değil, bir TASARIM KARARI ve sonucu ölçülmemiş:** 89 ayetin kaçı zaten ★★★, kaçı ★★'da kalıyor? KAPATILAMAZ. TUR SONU: 89 ayetin yıldız dağılımı çıkarılıp, 'birleşik ölçüt' bir alternatif formülle karşılaştırılabilir."},

{"no": 953,
 "aday": "★ `say` ALANI SAYIYI SAYIYOR, ÖLÇÜYÜ DEĞİL — sûre 30'da ÜÇ vaka. **30:4'te `بِضْع`** (birkaç yıl): alan on yedi sayı kökü tanıyor ve `بضع` aralarında yok; kökün geçtiği altı ayetin altısında da alan boş. **30:17-18'de dört vakit** sıralı olarak sayılıyor, **30:40'ta dört aşamalı döngü** — hiçbiri hiçbir alanda dizi olarak tutulmuyor.",
 "olculen": {"say_tanidigi_kok": 17,
             "kokler": {"كثر": 167, "أحد": 85, "زوج": 81, "قلل": 76, "وحد": 68, "عدد": 57,
                        "ثلث": 32, "ثني": 29, "سبع": 28, "عشر": 27, "ربع": 22, "ألف": 22,
                        "ثمن": 19, "خمس": 8, "نصف": 7, "تسع": 7, "سدس": 5},
             "بضع_gecen_ayet": ["12:19", "12:42", "12:62", "12:65", "12:88", "30:4"],
             "hepsinde_say_bos": True,
             "diger_vakalar": {"30:17-18": "dört vakit sıralı", "30:40": "dört aşamalı döngü"},
             "etkisi": "F_ölçü işaret ailesi bu vakaları göremiyor",
             "karsilastirma": "29:14 أَلْفَ سَنَةٍ إِلَّا خَمْسِينَ عَامًا → L4 (ölçü); 30:4 aynı yapının zayıf hâli, alan hiç görmüyor"},
 "durum": "ACIK", "oncelik": "P1", "kaynak": "okuma sûre 30, tam sayım",
 "etiket": "alan eksiği",
 "test_notu": "**`بضع` eksiği ucuz bir onarım (kök listesine eklemek) ama asıl mesele daha geniş: alan BELİRSİZ nicelikleri ve SIRALI dizileri hiç görmüyor.** 'Birkaç yıl' sınırlı bir niceliktir; 'akşam-sabah-ikindi-öğle' bir dizidir; 'yaratma-rızık-ölüm-diriliş' bir dizidir. **F_ölçü ailesi 'iki ya da daha fazla sayı işareti' arıyor ve üçünde de sıfır işaret buluyor.** TUR SONU: (a) `بضع` say listesine eklenmeli, (b) sıralı dizi için ayrı bir ölçüt gerekip gerekmediği korpus çapında sınanmalı."},

{"no": 954,
 "aday": "★ P0 #5'E SÛRE 30'DAN ALTI YENİ VAKA — VE İKİSİ TEK AYETTE İKİ ANLAM TAŞIYOR. **30:8'de `سمو`**: `ٱلسَّمَٰوَٰتِ` (gökler) ve `مُّسَمًّى` (adlandırılmış). **30:55'te `سوع`**: `ساعَة (Kıyamet)ُ` (Kıyamet) ve `ساعَةٍ` (bir saat). Ayrıca üç anlamlı iki kök: `خلف` (ardından gelme / caymak / farklılık) ve `ظهر` (görünen yüz / öğleye ermek / belirmek).",
 "olculen": {"tek_ayette_iki_anlam": {"30:8": ["سَماء", "مُسَمًّى"], "30:55": ["ساعَة (Kıyamet)", "ساعَة"]},
             "uc_anlamli": {"خلف": ["29:6 ardından gelme", "30:6 caymak", "30:22 farklılık"],
                            "ظهر": ["30:7 görünen yüz", "30:18 öğleye ermek", "30:41 belirmek"]},
             "diger": {"نهر": "30:23 gündüz, tablo 'ırmak'", "برر": "30:41 kara, esmâ artefaktı"},
             "kume_boyu": {"27": 6, "28": 12, "29": 4, "30": 6, "toplam": 28},
             "olumlu_ornek": {"ثور": "30:9 toprağı sürmek / 30:48 bulutu kaldırmak — karşılık ikisini de taşıyor",
                              "ظلل": "30:51 sürüp gitme — karşılık doğru"},
             "onarilmis_suzgec_dogru_calisti": {"30:8": "olgu-lemma süzgeci yalnız سَماء'yı olgu sayıyor"}},
 "durum": "ACIK", "oncelik": "P0", "kaynak": "okuma sûre 30",
 "etiket": "P0 #5b'ye veri",
 "test_notu": "**P0 #5'in sınama kümesi yirmi sekiz vakaya çıktı.** Yeni olan: **iki vaka TEK AYETTE iki anlam taşıyor** — yani bağlam bile ayırt edici değil, ayrım kelime düzeyinde yapılmak zorunda. **Ve 30:55'te ayetin bütün retorik yükü tam bu ayrımın üzerinde duruyor** (Kıyamet 'saat'i ile 'bir saat'). **Olumlu taraf: 30:8'de onarılmış olgu-lemma süzgeci doğru çalışıyor** — `سمو`nun iki tokeninden yalnız `سَماء` olgu sayılıyor; yani P0 #5a (lemma kimliği) tarayıcıyı onarmış durumda, açık kalan yalnız P0 #5b (Türkçe gloss)."},

{"no": 955,
 "aday": "★ MERDİVENDE İKİ YENİ BOŞLUK — VE 'OLGU' BAYRAĞININ TANIM AÇIĞI. **(1) Karşılaştırmalı sıralama okumada DÖRT vaka** (29:41 `أَوْهَنَ` · 30:10 `سَوْء ism-i tafdîli` · 30:27 `أَهْوَنُ` · 30:38 `خَيْرٌ`) ve dördü de L1'e sıkışıyor. **(2) Değişmezlik iddiası ilk vaka** (30:30 `لَا تَبْدِيلَ لِخَلْقِ ٱللَّهِ`). **(3) 30:41 'olgu' bayrağının olgunun KONUSU mu YERİ mi sayılacağını tanımlamadığını gösterdi.**",
 "olculen": {"karsilastirmali_siralama": {"29:41": "أَوْهَنَ ٱلْبُيُوتِ", "30:10": "سَوْء ism-i tafdîli",
                                          "30:27": "أَهْوَنُ عَلَيْهِ", "30:38": "ذَٰلِكَ خَيْرٌ"},
             "hepsi_L1": True,
             "degismezlik_iddiasi": {"30:30": "لَا تَبْدِيلَ لِخَلْقِ ٱللَّهِ", "kademe": "L1"},
             "olgu_bayragi_acigi": {"ayet": "30:41",
                                    "durum": "kara ve deniz olgu kökleri, iddia onlarda gerçekleşen bir DEĞİŞİMİ bildiriyor, nedensellik açık",
                                    "sorun": "iddianın öznesi ٱلْفَسَاد — doğa süreci değil",
                                    "karar": "L2, olgu = HAYIR",
                                    "acik": "bayrak olgunun KONUSU mu YERİ mi sayılacağını söylemiyor"}},
 "durum": "ACIK", "oncelik": "P1", "kaynak": "okuma sûre 30",
 "etiket": "KAPATILAMAZ ×3",
 "test_notu": "**Üçü de aynı sınıftan: merdiven ve bayrak, okuma sırasında karşılaşılan iddia türlerini tam örtmüyor.** Karşılaştırmalı sıralama dört kez çıktı ve her seferinde L1'e sıkıştı — **bir basamak gerekip gerekmediği ancak korpus çapında üstünlük yapısı sayılarak karara bağlanabilir** (aday 926 ailesinden). 30:41 ise ilk kez BELİRLEYİCİ oldu: kararın kendisi bayrağın tanımına bağlıydı ve tanım yok. **Tanım netleşmeden benzer vakalar tutarsız kalır ve bu, okuyucu kararlarının yeniden üretilebilirliğini doğrudan tehdit eder.**"},

{"no": 956,
 "aday": "★ BU OTURUMDAKİ DÖRT ONARIM TUTULAN KÜMEDE SINANDI — DÖRDÜ DE TUTTU. **`ريح` → `روح` (aday 946)**: 30:46'da çıpa ANCAK düzeltmeyle görünüyor. **`هوي` bağlam listesine (aday 945)**: 30:29'da `أَهْوَآءَهُم` = hevesler, olgu değil. **`قدر` lemma süzgeci (aday 944)**: 30:37'de `يَقْدِرُ` olgu sayılmıyor. **`عقب` dışlaması (aday 924)**: 30:9 ve 30:42'de iki kez doğru negatif.",
 "olculen": {"sinamalar": {
               "ريح → روح": {"ayet": "30:46", "sonuc": "çıpa ancak düzeltmeyle havuza giriyor", "aday": 946},
               "هوي": {"ayet": "30:29", "sonuc": "أَهْوَآءَهُم = hevesler, doğru dışlandı", "aday": 945},
               "قدر": {"ayet": "30:37", "sonuc": "رأي+INTG var ama يَقْدِرُ olgu değil — doğru negatif", "aday": 944},
               "عقب": {"ayet": ["30:9", "30:42"], "sonuc": "iki kez doğru negatif", "aday": 924}},
             "30:42_notu": "kalıbı hem نظر hem EMİR kipiyle taşıyor — dışlama olmasaydı kesin aday olurdu",
             "okuma_onarilmis_alanlarla": ["hapaks2", "fig2", "nakarat3", "yildiz2", "z2", "tarayıcı v4"],
             "sure_30_onarimlardan_etkilenmedi": {"yildiz_degisimi": 0, "hapaks_degisimi": 0,
                                                  "fig2_farki": "yalnız sıra"},
             "sonuc": "sûre 30, sûre 27-29 ile karşılaştırılabilir kalıyor"},
 "durum": "KAPALI", "oncelik": "P0", "kaynak": "okuma sûre 30",
 "etiket": "onarım doğrulaması (olumlu)",
 "test_notu": "**Okumanın bir onarım turunu doğrudan sınadığı ilk vaka ve dördü de tuttu.** En değerlisi `ريح` → `روح`: **`anahtar_denetim.py`'nin yakaladığı sessiz arıza olmasaydı sûrenin en açık L2'lerinden biri (30:46) havuza hiç girmeyecekti.** Bu, aday 946'nın 'küme hâlinde yazılan Arapça kök listeleri kullanılmadan önce korpusa karşı doğrulanmalı' dersinin somut bedelini gösteriyor. **Yan bulgu: okuma ilk kez onarılmış alanlarla koşuldu ve sûre 30 onarımlardan ETKİLENMEDİ** — yıldız değişimi yok, hapaks aynı; **yani sûre 27-29 ile karşılaştırılabilirlik korundu ve bu, onarımların geriye dönük tutarlılığının kanıtı.**"},

{"no": 957,
 "aday": "SÛRE 30'UN PROFİLİ: EN DÜŞÜK YILDIZLI ORAN, EN AZ ADLI AKTÖR, A/R = 8,00. Yıldızlı oran **%25,0** (27: %?, 28: %31, 29: %31,9). Adlı aktör **2 token** — 28'de 37, 29'da 21 idi. A/R **8,00**, sûre 29'un 8,4'üne çok yakın.",
 "olculen": {"30": {"ayet": 60, "ort_n": 13.62, "yildizli_oran": 25.0,
                    "yildiz": {"3": 3, "2": 3, "1": 9, "0": 45},
                    "kaynak": {"pas": 4, "allah": 4, "n": 3, "kafiye": 2, "hapaks": 1, "rab": 1, "icerik": 0},
                    "A_token": 24, "R_token": 3, "AR": 8.00,
                    "adli_token": 2, "adsiz_token": 1,
                    "esma": {"toplam": 14, "muhurlu": 6, "muhurlu_gecerli": 6,
                             "muhursuz": 8, "muhursuz_gecerli": 1, "artefakt": 7},
                    "iltifat": 1, "hapaks_ayet": 1, "kafiye_kirik": 2,
                    "harf": 3654, "harf3": 3434, "isaret_yuzde": 5.5,
                    "mm2": 1, "ic_dugum_ayet": 9, "nakarat3_dolu": 31, "ikili_dolu": 32,
                    "yeni_kok": 10},
             "AR_serisi": {"27": 2.25, "28": 1.42, "29": 8.4, "30": 8.00},
             "adli_aktor_serisi": {"28": 37, "29": 21, "30": 2},
             "uc_surede_muhurlu_yanlis_pozitif": 0,
             "muhurlu_kayitlar": {"27": "12/12", "28": "2/2", "29": "8/8", "30": "6/6"}},
 "durum": "ACIK", "oncelik": "P2", "kaynak": "okuma sûre 30",
 "etiket": "okuma sırasında ölçüldü",
 "test_notu": "**İki ardışık sûre lafız ağırlıklı (8,4 ve 8,00) ve ikisi de bundan önceki ikisinden keskin biçimde ayrılıyor (2,25 ve 1,42).** Aday 932'nin 'A/R dalgalanması büyük ve tek yönlü değil' kaydı dört sûreyle sürüyor ama **son iki sûre birbirine çok yakın: dalgalanma rastgele değil, kümelenme var.** Adlı aktör tarafında ters uç: sûre 30 okumanın **en az adlı aktörlü sûresi** (2 token) ve sûre 28 en çoğuydu (37). **Sûre 30'un anlatısı kişilerle değil olgularla kurulu** — ve bu, tarayıcının çöküşüyle (aday 948) aynı sebebe bağlı olabilir. KAPATILAMAZ: korpus çapında A/R ve adlı aktör dağılımları hâlâ çıkarılmadı (aday 932 ve 936'nın tur sonu işleri)."},

{"no": 958,
 "aday": "KOMŞULUK ÖLÇÜMÜ İLK KEZ SÛRE SINIRINI AŞARAK DOĞRULANDI. **30:59'da `طبع` + `قلب`.** Bu ikili **29:21'de** `قلب` kökünün dikey profilinde ×39,4 olarak durmuştu ve orada *'çok ayetli; ama buradaki lemma `قَلَبَ` (çevirme), o kalıp kalp anlamına ait: P0 #5 vakası'* diye kaydedilmişti. **Otuz dokuz ayet ve bir sûre sonra kalıp tam olarak, DOĞRU lemmayla metne giriyor.**",
 "olculen": {"kayit_yeri": "29:21 dikey satırı", "deger": 39.4,
             "gerceklestigi_ayet": "30:59", "aciklik_ayet": 39, "sure_asirilik": True,
             "29:21_notu": "lemma قَلَبَ (çevirme) — kalıp 'kalp' anlamına ait, P0 #5 vakası",
             "30:59_lemma": "قَلْب (kalp) — bu kez doğru",
             "sure_30_ici_haber_vermeler": {"30:11": "بدأ + عود", "30:36": "رحم + قنط",
                                            "30:46": "سخر → فلك", "30:24": "خوف + طمع"},
             "okumada_toplam": "dokuz vaka, sekizi sûre içi, biri sûre aşırı"},
 "durum": "KAPALI", "oncelik": "P2", "kaynak": "okuma sûre 30",
 "etiket": "dikey katman doğrulaması (olumlu)",
 "test_notu": "**Komşuluk ölçümünün önceden haber verdiği dokuz vakanın sekizi sûre içindeydi; bu ilk sûre-aşırı doğrulama.** Ve çifte değerli: **29:21'de kaydedilen P0 #5 uyarısı ('bu kalıp bu lemmaya ait değil') 30:59'da doğru lemmayla karşılanıyor** — yani hem komşuluk ölçümü hem lemma uyarısı aynı anda doğrulanmış oluyor. KAPATILAMAZ: dokuz vakanın kaçının rastlantı olduğu ölçülmedi; **komşuluk tablosunun 'haber verme' gücü için bir taban oran gerekli** (rastgele seçilen bir kökün profilindeki ilk üç ortaktan biri, sonraki N ayette ne sıklıkla çıkar?)."},
]

BAGLAR = [
 {"bag": "30:48 (L4)", "kural": "L2", "not": "**Okumanın ÜÇÜNCÜ L4'ü ve MEKANİZMA kolunu dolduran ilk ayet.** Beş aşamalı süreç, ara durumlar adlandırılmış (`سَحاب`, `كِسَف`, `وَدْق`), çıkışın yeri belirtilmiş. **L4'ün üç kolu artık örneklenmiş: ölçü 29:14 · sınıflama 29:40 · mekanizma 30:48** (aday 949)."},
 {"bag": "30:24 ↔ 30:48", "kural": "L2", "not": "**Merdivenin çalıştığının kanıtı: aynı olgu (yağmur), 30:24'te iki aşamada verilip L2, 30:48'de ara aşamalar açılınca L4.** Kademe konuyu değil İDDİA YAPISINI ölçüyor (aday 949)."},
 {"bag": "30:11 ↔ 30:27 ↔ 29:19 ↔ 27:64", "kural": "L1", "not": "`بدأ`+`عود` döngü iddiası dört ayette. **30:11 ve 30:27 düz haber, 29:19 soru kipinde — kademe aynı: iddia yapısı ölçülüyor, konuşma edimi değil.** `nakarat3` 30:11↔30:27'yi bağlıyor (dört kelime); `xref` 27:64'ü de gösteriyor. **Tarayıcı üçünü de kaçırdı.**"},
 {"bag": "30:19 ↔ 30:24 ↔ 30:50 ↔ 29:63", "kural": "L1", "not": "`يُحْىِ ٱلْأَرْضَ بَعْدَ مَوْتِهَا` kalıbı üç L2 çıpasında ve emsali 29:63'te. **`nakarat3` yalnız 30:19↔30:24'ü bağlıyor; üçünü birden gören alan yok** (30:50'de araya `كَيْفَ` giriyor)."},
 {"bag": "30:52 ↔ 27:80", "kural": "L2", "not": "**Okumanın en yüksek `esit2` değerlerinden: 0,9888.** Beş `xref` 3-gram'ının beşi de aynı ayete düşüyor — **okumada ölçülen en tam örtüşme**; fark tek kelimede (aday 950)."},
 {"bag": "30:53 ↔ 27:81", "kural": "L2", "not": "**0,9905 — mukattaa TAM'ları dışında okumanın en yüksek `esit2` değeri.** Ve 30:52↔27:80 ile birlikte **okumada ilk kez bir ayet ÇİFTİ, başka bir sûredeki ayet ÇİFTİNE sırasıyla bağlanıyor.** `esit2` bunu iki ayrı ikili bağla veriyor; **alan AYET düzeyinde çalışıyor, BÖLÜT düzeyinde değil** (aday 950)."},
 {"bag": "30:34 ↔ 16:55 ↔ 29:66", "kural": "L2", "not": "**Aday 929'un üçlüsü tamamlandı ve eşkenar olmadığı ortaya çıktı:** 30:34↔16:55 = **1,0 TAM**, ötekiler 0,9275. **Bağların ağırlıkları farklı; küme yapısı ancak üç uç da okununca görünüyor** (aday 951)."},
 {"bag": "30:37 ↔ 39:52", "kural": "L1", "not": "**Okumada ikinci 'yakin' kademesi (0,9649).** Ayrıca `يَبْسُطُ ٱلرِّزْقَ لِمَن يَشَآءُ وَيَقْدِرُ` cümlesinin **üçüncü geçişi**: 28:82 (insan sözü) · 29:62 (ilâhî beyan) · 30:37 (soru). **Aynı önerme, üç sûre, üç konuşma edimi — üçünü bağlayan alan yok.**"},
 {"bag": "30:9 ↔ 30:42", "kural": "L2", "not": "**`عقب` dışlama kuralının tutulan kümedeki iki sınaması ve ikisi de tuttu.** 30:42 kalıbı hem `نظر` hem EMİR kipiyle taşıyor — dışlama olmasaydı kesin aday olurdu. `nakarat3` ikisini bağlıyor (beş kelime), `dugum.ic` ikisinde de 1 (aday 956)."},
 {"bag": "30:30 ↔ 30:43", "kural": "L1", "not": "`فَأَقِمْ وَجْهَكَ لِلدِّينِ` on üç ayet arayla birebir. **`nakarat3` kalıbı görüyor ama süzgeci geçiremiyor (2 ayet / 3 kelime); `dugum.ic` ikisini de 1 sayıyor** — 29:32↔29:33'te kaydedilen 'iki alan aynı kalıba farklı davranıyor' deseninin üçüncü örneği."},
 {"bag": "30:12 ↔ 30:14 ↔ 30:55", "kural": "L1", "not": "`وَيَوْمَ تَقُومُ ساعَة (Kıyamet)ُ` **üç uçlu iç düğüm, kırk üç ayetlik açıklık.** Sûrenin ilk bloğunda açılıp kapanış bloğunda üçüncü ucunu veriyor. `nakarat3` üçünü de sayıyor (3 kelime / 3 ayet → geçer)."},
 {"bag": "30:46 ↔ aday 946", "kural": "L2", "not": "**Çıpa ANCAK bu oturumdaki onarım sayesinde görünüyor.** `anahtar_denetim.py` olgu kümesindeki `ريح` yazımının korpusta bulunmadığını, rüzgârın `روح` kökü altında (`LEM:رِيح`) olduğunu yakalamıştı; **düzeltme olmasaydı sûrenin en açık L2'lerinden biri havuza hiç girmeyecekti** (aday 956)."},
 {"bag": "30:29 ↔ aday 945", "kural": "L1", "not": "`هوي` kökü lemma turunda `BAGLAM_GEREKLI` listesine alınmıştı (`هَواء` hem 'hava' hem 'heva'). **30:29'da `أَهْوَآءَهُم` açıkça 'hevesler' ve olgu değil — karar tutulan kümede doğrulandı.**"},
 {"bag": "30:37 ↔ aday 944", "kural": "L1", "not": "**Lemma süzgecinin doğru negatifi:** `رأي` + `INTG` var, yani `G_bakış`ın iki şartı sağlanıyor; üçüncü şart sağlanmıyor çünkü `قدر` burada `يَقْدِرُ` (lemma `قَدَرَ`) ve onarılmış tabloda bu lemma olgu değil. **Rızkın genişletilmesi bir doğa olgusu değil.**"},
 {"bag": "30:59 ↔ 29:21", "kural": "L2", "not": "**Komşuluk ölçümünün ilk SÛRE-AŞIRI doğrulaması.** 29:21'de `قلب` profilinde `طبع` ×39,4 durmuş ve 'lemma yanlış: P0 #5 vakası' diye kaydedilmişti; **otuz dokuz ayet ve bir sûre sonra kalıp DOĞRU lemmayla metne giriyor** (aday 958)."},
 {"bag": "30:8 · 30:55", "kural": "L1", "not": "**P0 #5'in en keskin iki vakası: TEK AYETTE iki anlam.** 30:8'de `سمو` = gökler + adlandırılmış; 30:55'te `سوع` = Kıyamet + bir saat. **30:55'te ayetin bütün retorik yükü tam bu ayrımın üzerinde.** Bağlam bile ayırt edici değil; ayrım kelime düzeyinde yapılmak zorunda (aday 954)."},
 {"bag": "30:2", "kural": "L1", "not": "**Okumada ★★★ alan en kısa ayet: İKİ kelime.** Tek fiil, edilgen, oran 1,00, pas z=**5,38** — aday 903'ün ikinci otomatik tetikleyicisi dördüncü sûrede (28:70 · 29:57 · 30:2). `dis`=0 ve üç bağ alanı boş: **hiçbir yere bağlanmayan iki kelime, en yüksek nişanla.**"},
 {"bag": "30:17", "kural": "L2", "not": "**Okumada ★★★'ı iki bağımsız kaynaktan alan ilk ayet:** hapaks z=3,38 VE allah z=2,80. **TAM SAYIM: korpusta iki+ ölçütü |z|>2 olan 89 ayet.** Formül en büyüğünü alıyor, toplamıyor — **iki bağımsız olgunun birlikteliği ölçümde kayboluyor** (aday 952)."},
 {"bag": "30:5 · 30:11 · 30:59", "kural": "L2", "not": "**Aynı oran üç kez aynı z'yi veriyor:** üçü de 1 lafız / 8 kelime → allah z=**1,97** → ★. Aday 931'in payda etkisi kaydının yedinci, sekizinci ve dokuzuncu vakası."},
 {"bag": "29:6 · 29:44 · 30:60", "kural": "L2", "not": "**`allah` z=1,47 üç kez ve üçü de eşiğin 0,03 altında, üçü de yıldızsız.** Üçünde de bir lafız ve uzunluk 10-11 kelime — **eşiğin dibinde kümelenme.**"},
 {"bag": "30:50 · 30:54", "kural": "L2", "not": "**Sûre 30'un iki kafiye kırılması ve ikisi de yalnız kafiyeden ★.** Okumada dördüncü ve beşinci vaka (28:28, 29:21, 29:22). Aday 933'ün 'alan yerel komşuluğu ölçüyor' kaydı beşinci kez."},
 {"bag": "30:15 · 30:48 · 30:54 · 30:57", "kural": "L1", "not": "**Nadirlik yığılması ≠ hapaks — sûrede dört vaka.** `روض` 2 · `ودق` 2 · `شيب` 3 · `عتب` 4 ayet; hiçbiri `hapaks2` değil. **30:48 okumada ölçülen en yoğun örnek: üç dar kök (2, 5, 11 ayet) tek ayette ve ayetin yıldızı yalnız uzunluktan.** 28:12'nin ayrımı."},
 {"bag": "30:41", "kural": "L2", "not": "**'Olgu' bayrağının tanım açığı ilk kez BELİRLEYİCİ oldu.** Kara ve deniz olgu kökleri, iddia onlarda gerçekleşen bir değişimi bildiriyor, nedensellik açık — ama öznesi `ٱلْفَسَاد`. **Bayrak olgunun KONUSU mu YERİ mi sayılacağını söylemiyor.** L2/olgu-hayır verildi, KAPATILAMAZ kaydedildi (aday 955)."},
 {"bag": "30:33 ↔ 29:65", "kural": "L1", "not": "**Aynı davranış düzenliliği, iki sûre, ve ölçüm bağlamıyor.** Orada gemiye binince ihlâs / karaya çıkınca şirk; burada zarar dokununca yakarış / rahmet tadınca şirk. `esit2` boş, `nakarat3` boş, `xref` başka ayetlere gidiyor."},
]

pa = '/home/claude/repo/bulgular/aday_bulgular.json'
AD = json.load(open(pa, encoding='utf-8'))
AD.setdefault('AN_rum', []).extend(ADAYLAR)
AD['son_guncelleme'] = 'sûre 30 (Rûm) okuması — adaylar 948-958'
json.dump(AD, open(pa, 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
print('aday_bulgular: AN_rum →', len(AD['AN_rum']),
      '|', AD['AN_rum'][0]['no'], '-', AD['AN_rum'][-1]['no'])

pb = '/home/claude/repo/notlar/okuma_baglantilari.json'
BG = json.load(open(pb, encoding='utf-8'))
BG.setdefault('AJ_rum', []).extend(BAGLAR)
json.dump(BG, open(pb, 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
print('okuma_baglantilari: AJ_rum →', len(BG['AJ_rum']))
