# -*- coding: utf-8 -*-
# Claude-üretimi kök adları, parti 1 (frekans 1722→16)
ADLAR = {
"قول":"söz/demek","رسل":"elçi/rasûl","يوم":"gün","أرض":"yer/arz","عمل":"amel/iş",
"جعل":"kılmak/yapmak","كتب":"kitap/yazmak","حقق":"hak","جيأ":"gelmek","عبد":"kul/kulluk",
"بعد":"sonra/uzaklık","غفر":"bağışlama/mağfiret","دعو":"dua/çağırmak","حسن":"güzellik/ihsan","ضلل":"sapma/dalâlet",
"سمع":"işitmek","سبل":"yol/sebîl","تبع":"uymak/tâbi olmak","قتل":"öldürmek","شرك":"ortak koşma/şirk",
"سوأ":"kötülük","موت":"ölüm","شهد":"şahitlik/şehâdet","وعد":"vaat","بصر":"görmek/basîret",
"دون":"başka/aşağı (dûn)","نظر":"bakmak","سأل":"sormak/istemek","أهل":"ehil/aile","دخل":"girmek",
"خوف":"korku","رزق":"rızık","يدي":"el","أبو":"baba/atalar","أكل":"yemek/yemek yeme",
"فعل":"yapmak/fiil","أجر":"ecir/karşılık","وجد":"bulmak","رجع":"dönmek/rücû","فضل":"fazl/lütuf",
"صبر":"sabır","شدد":"şiddet/çetinlik","ولد":"çocuk/doğum","صلو":"namaz/salât","صحب":"arkadaş/ashâb",
"أخو":"kardeş","ليل":"gece","ليس":"değil/olmama","شطن":"şeytan","خلد":"kalıcılık/huld",
"توب":"tövbe","مول":"mal","أحد":"bir/tek (ehad)","كيف":"nasıl","زوج":"eş/çift",
"وحي":"vahiy","وجه":"yüz/yön","بلغ":"ulaşma/tebliğ","ألم":"acı/elem","كلم":"söz/kelime",
"شكر":"şükür","رضو":"rıza/hoşnutluk","غني":"zenginlik/müstağnîlik","متع":"geçimlik/meta","وكل":"tevekkül/vekil",
"ظنن":"zan","وحد":"bir/teklik (vahid)","هلك":"helâk","بعث":"diriltme/gönderme","كسب":"kazanma/kesb",
"خسر":"hüsran/kayıp","حمل":"taşıma/yük","جري":"akma","ذوق":"tatma","موه":"su",
"تلو":"okuma/tilâvet","قضي":"hüküm/kazâ","مسس":"dokunma","زيد":"artırma/ziyade","فتن":"fitne/imtihan",
"نسو":"kadınlar","ردد":"geri çevirme/red","ضرب":"vurma/örnek verme","قري":"şehir/karye","فسق":"fısk/yoldan çıkma",
"خبر":"haber/haberdarlık","تحت":"alt","نفع":"fayda","فسد":"bozgunculuk/fesat","طيب":"temiz/hoş",
"عقل":"akıl/akletme","خشي":"haşyet/korku","أثم":"günah/ism","طعم":"yiyecek/taam","كرم":"kerem/ikram",
"زين":"süsleme","عهد":"ahit/söz","وذر":"bırakma/terk etme","نسي":"unutma","صرط":"yol/sırât",
"بدل":"değiştirme/bedel","حفظ":"koruma/hıfz","مكر":"tuzak/mekr","حشر":"toplama/haşir","ترك":"bırakma/terk",
"حزن":"hüzün","لعن":"lânet","فلح":"kurtuluş/felâh","شرب":"içme","سلط":"güç/sultân",
"بلو":"sınama/belâ","نكر":"münker/yadırganan","سبق":"öne geçme","أوي":"barınma/sığınak","بطل":"bâtıl",
"قطع":"kesme","ريب":"şüphe/rayb","غفل":"gaflet","حين":"vakit/an","عفو":"af",
"كيد":"tuzak/keyd","ورث":"miras/vâris","هزأ":"alay","خفي":"gizlilik/gizleme","شمس":"güneş",
"كفي":"yetme/kâfî olma","عمي":"körlük","برك":"bereket","وسع":"genişlik/vüsat","ثلث":"üç",
"وصي":"vasiyet/tavsiye","حيث":"yer/nerede","طهر":"temizlik/tahâret","لبث":"kalma/eğleşme","سعي":"çalışma/koşma",
"أنث":"dişi","صرف":"çevirme/sarf","عسي":"umulur ki","جند":"ordu/asker","غشو":"bürüme/kaplama",
"صير":"varış yeri/masîr","دري":"bilme/bildirme","رفع":"yükseltme","فوز":"kurtuluş/kazanç","جدل":"tartışma/cedel",
"أبد":"ebed/sonsuzluk","يقن":"yakîn/kesin bilgi","خلو":"geçip gitme/yalnız kalma","عدل":"adalet/denklik","حوط":"kuşatma/ihâta",
"ثقل":"ağırlık/miskal","غرر":"aldatma/gurûr","بوب":"kapı","قمر":"ay (gök cismi)","خزي":"rezillik/hor olma",
"نبت":"bitirme/bitki","جحم":"cahîm/alevli ateş","لسن":"dil/lisan","وهب":"bağışlama/hibe","وعظ":"öğüt/vaaz",
"سقي":"sulama/içirme","حضر":"hazır bulunma","بسط":"yayma/genişletme","فلك":"gemi","صلي":"ateşe girme/yaslanma",
"أدم":"Âdem","شري":"satın alma/satma","غضب":"öfke/gazap","جهل":"cahillik","أذي":"eziyet",
"وقع":"vuku bulma","ثمر":"meyve","فحش":"hayâsızlık/fâhişe","مرض":"hastalık","كود":"az kalsın/neredeyse",
"يتم":"yetim","نكح":"nikâh","سرف":"israf","وزن":"tartı/mîzan","سرع":"hız/çabukluk",
"مشي":"yürüme","غرق":"boğulma","فرح":"sevinç/şımarma","خطأ":"hata/günah","تمم":"tamamlama",
"غوي":"azdırma/iğvâ","ربع":"dört","بقي":"kalma/bâkî olma","كتم":"gizleme/ketm","شهر":"ay (takvim)",
"حذر":"sakınma","فقه":"kavrama/fıkıh","حزب":"hizip/topluluk","نفخ":"üfleme","مري":"şüphe etme/tartışma",
"لعب":"oyun","كشف":"açma/giderme","نخل":"hurma","بلد":"belde/şehir","رشد":"doğru yol/rüşd",
"فكر":"düşünme/tefekkür","مكن":"imkân/yerleştirme","دبب":"canlı/dâbbe","لدن":"katında/nezd","ثبت":"sağlamlaştırma/sebat",
"خصم":"hasım/çekişme","نوب":"yönelme/inâbe","رأس":"baş","عوذ":"sığınma/istiâze","خشع":"huşû",
"أوب":"dönüş/meâb","منع":"engelleme","خفف":"hafifletme","ربص":"bekleme/gözetleme","شرق":"doğu/maşrık",
"علن":"açığa vurma","عتد":"hazırlama/hazır etme","خون":"hıyanet","جهر":"açıktan söyleme/cehr","لبب":"öz akıl/lübb",
}
