# -*- coding: utf-8 -*-
# Claude-üretimi kök adları, parti 3
ADLAR = {
"تبب":"kurumak/helâk (tebbet)","بدع":"örneksiz yaratma/bedî","رحب":"genişlik","نسخ":"nesh/hükmü kaldırma","وقف":"durdurma",
"حمأ":"balçık/kara çamur","زول":"yok olma/zeval","فشل":"gevşeyip çözülme","سلح":"silah","سول":"süslü gösterme/nefsin aldatması",
"جهز":"donatma/yük hazırlama","رتل":"tane tane okuma/tertîl","غضض":"gözü sakınma/kısma","نصي":"perçem/alın saçı","سخط":"öfke/hoşnutsuzluk",
"خسأ":"aşağılanmış kovulma","شيخ":"yaşlı/ihtiyar","يبس":"kuruluk/kuru yol","وفق":"başarı/tevfîk","طفل":"çocuk/bebek",
"سيل":"sel/akıntı","دلو":"sarkıtma/kova","مجد":"şan/mecîd","لمز":"ayıplama/dil uzatma","خفض":"alçaltma/kanat germe",
"جسد":"beden/ceset","سرج":"kandil/sirâc","رحل":"yük/eşya","أفل":"batıp kaybolma/ufûl","نحت":"yontma",
"غمر":"dalgınlık/gömülme","زلل":"ayak kayması/sürçme","خرق":"delme/yakıştırma","سقف":"tavan","بول":"akıl/hatıra (bâl)",
"عور":"açık/korumasız yer (avret)","نعج":"koyun","فلق":"yarma/yaran (fâlik)","قلم":"kalem","طلب":"isteme/talep",
"غيث":"yağmur/imdat","عجم":"yabancı dilli/Arap olmayan","دخر":"boyun eğip küçülme","رذل":"en düşkün/erzel","هنأ":"afiyetle/kutlu olsun",
"دحض":"çürütme/geçersiz kılma","حيض":"hayız","دحر":"kovulup uzaklaştırma","عفف":"iffetli davranma","سدر":"sidre ağacı",
"مهن":"aşağılık/değersiz","كرب":"sıkıntı/tasa","هات":"getirin bakalım","ميز":"ayırt etme/temyiz","شأن":"iş/durum",
"زخرف":"yaldız/süs","أمد":"süre/vade","صرح":"köşk/saray","كوب":"kupa/testi","ودع":"emanet yeri/bırakma",
"قنطر":"kantar/yığın mal","مزق":"paramparça etme","صلصل":"kuru çınlayan balçık/salsâl","طبق":"tabaka/kat kat","سمن":"semizlik/besili",
"عقم":"kısırlık","سفن":"gemi/sefine","سلخ":"sıyırıp çıkarma","رمن":"nar","مزج":"karışım/katkı",
"خذل":"yardımsız bırakma","وثن":"put (vesen)","جذع":"gövde/kütük","حدق":"bahçe","جدث":"kabirler (ecdâs)",
"شيب":"saç ağarması/ihtiyarlık","صخر":"kaya","قرد":"maymun","جأر":"yalvarıp yakarma","هزم":"bozguna uğratma",
"رهن":"rehin","جزأ":"parça/pay","هطع":"boyun uzatıp koşma","ظمأ":"susuzluk","أصر":"ağır yük/bağ",
"سلسل":"zincir","نكف":"büyüklenip çekinme","عير":"kervan","لجأ":"sığınak","صرم":"devşirme/kesme",
"كبت":"perişan edip alçaltma","أجج":"acı tuzlu (su)","دعع":"itip kakma","قرح":"yara","حفو":"lütufkâr/ısrarla sorma",
"نثر":"saçılma","نفذ":"delip geçme","عري":"çıplak açık yer","أفف":"öf deme/bıkkınlık","شأم":"uğursuzluk/sol yan",
"رهط":"küçük topluluk/oymak","ذأب":"kurt","بهج":"göz alıcılık/güzellik","فسح":"yer açma/genişletme","ردف":"ardı sıra gelme",
"شحن":"dolu yüklü","أزف":"yaklaşan (kıyamet)","مور":"çalkalanma","مرح":"kibirle böbürlenme","فجج":"geniş yol/geçit",
"لفت":"dönüp bakma/çevirme","جثو":"diz üstü çökme","خفت":"fısıldaşma/alçak sesle","ثلل":"cemaat/topluluk (sülle)","حوج":"ihtiyaç",
"همز":"dürtme/çekiştirme","ضغث":"demet/karmakarışık düş","ضجع":"yatak/yan yatılan yer","بهم":"davar/hayvan (behîme)","فتل":"çekirdek zarı/kıl payı",
"زبد":"köpük","سأم":"usanma/bıkma","فقد":"yitirme/yokluğunu görme","وتد":"kazık","سيح":"gezip dolaşma",
"كور":"dürülme/sarma","طفأ":"söndürme","بذر":"saçıp savurma","سلو":"bıldırcın/selvâ","لفو":"bulma (elfâ)",
"صرصر":"uğultulu dondurucu (rüzgâr)","روغ":"sıvışıp yönelme","نضد":"dizili/istifli","سربل":"gömlekler/zırhlar","شطط":"haddi aşma/saçmalık",
"لقف":"kapıp yutma","قبس":"kor/ateş parçası","أفق":"ufuk","جيب":"yaka/koyun","ركض":"koşma/topuk vurma",
"طفق":"koyulma/başlama","ذقن":"çene","شنأ":"kin/buğz (şeneân)","فزز":"yerinden oynatma/tedirgin etme","صبأ":"Sâbiî",
"نضر":"parlaklık/tazelik","لذذ":"lezzet","فتر":"gevşeme/ara dönem (fetret)","وجس":"içine korku düşme","رغد":"bolluk içinde",
"حضض":"teşvik etme","زقم":"zakkum","نكس":"baş aşağı çevirme","خبت":"gönülden boyun eğme/ihbât","برزخ":"berzah/ara engel",
"لهب":"alev","عزر":"destekleyip saygı gösterme","نأي":"uzaklaşma/yüz çevirme","ركم":"üst üste yığma","محو":"silme/mahv",
"فرت":"tatlı (su)/fırat","ستر":"örtü/perde","سجر":"kaynatıp doldurma","زفر":"inleyip soluma","متن":"sağlam/metîn",
"برح":"ayrılmama/vazgeçme","عبس":"yüz ekşitme","أسس":"temel atma/kurma","مضغ":"çiğnem et parçası/mudga","ذرو":"savurma",
"لفف":"derleyip toplama/karışık","نسب":"soy/nesep","سوغ":"boğazdan kolay geçen/içimli",
"بسل":"rehin bırakılıp mahvolma","أرب":"ihtiyaç/işe yarama","رسخ":"ilimde derinleşme/kökleşme","شكل":"yapı/mizaç (şâkile)","جزع":"sızlanma/feryat",
"رفث":"kadına yaklaşma/cinsî söz","خمد":"sönme","بسر":"yüz asma/somurtma","سبأ":"Sebe","وسل":"vesile",
"كدح":"didinip çabalama","زلم":"fal oku (ezlâm)","نزف":"başı dönme/tükenme","لهث":"dil çıkarıp solma","غثو":"çerçöp/köpük artığı",
"برم":"kesin karar bağlama/ibrâm","خدن":"gizli dost","أزز":"kışkırtıp dürtme","بنن":"parmak uçları/benân","دخن":"duman",
"رفت":"ufalanmış toz/döküntü","هور":"göçmeye yüz tutmuş/uçurum kenarı","سبغ":"bol bol verme/tamamlama","قطف":"devşirilen salkım","ركس":"tersine çevirme/gerisin geri",
"ضمم":"katıp kavuşturma","كلو":"her ikisi/kilâ","رعد":"gök gürültüsü","خور":"böğürme","صغو":"meyletme/kayma",
"غوص":"dalgıçlık/dalma","غدر":"bırakmama/eksik bırakma","شخص":"gözlerin donup kalması","أزر":"güç/destek (pazu)","لدد":"en yaman düşman/inatçı",
"خضع":"boyun eğme/yumuşama","قرطس":"kâğıt/sayfa (kırtâs)","همن":"gözetici/müheymin","بزغ":"doğup yükselme","أوه":"çok âh eden/yumuşak kalpli (evvâh)",
"سهو":"dalgınlık/gaflet","بدن":"beden/gövde","جسم":"cüsse/gövde","مخر":"suyu yara yara gitme","هشم":"kuru çöp/ufalanmış",
"حوذ":"kuşatıp ele geçirme (istihvâz)","صبع":"parmak","خصف":"yaprak yamama/örtme","خبل":"bozup şaşırtma/fesat","أشر":"şımarık küstah",
"نعس":"uyuklama","رطب":"yaş/taze","لمح":"göz açıp kapama/lemha","قيض":"musallat etme/ayarlama","جبب":"kuyu dibi",
"ثعب":"yılan/ejder","هلم":"gelin buraya","هبو":"toz zerresi/hebâ","كسل":"üşengeçlik","بخع":"kendini helâk etme",
"أثث":"ev eşyası","رقد":"uyuyanlar/uykuda","بعر":"deve","ملح":"tuzlu","طرو":"taze (et)",
"شفو":"uçurum kenarı/kıyı","عيي":"âciz kalma/yorulma","لغب":"yorgunluk/bitkinlik","وسق":"derleyip bürüme","دمع":"gözyaşı",
"خردل":"hardal tanesi","وبق":"helâk yeri/mahvolma","محص":"arındırıp temizleme/temhîs","قيل":"öğle uykusu/dinlenme","سرمد":"kesintisiz süreklilik",
"برص":"alaca hastalığı/abraş","طمث":"el değdirme/dokunma","كين":"boyun eğip yılgınlaşma","سقم":"hasta/rahatsız","عيل":"yoksulluk korkusu",
"سحق":"uzak/derin (yer)","عجف":"cılız/zayıf (inek)","زود":"azık edinme","نصت":"susup dinleme","حبس":"alıkoyma/tutma",
"رسس":"Ress halkı/kuyu","جرز":"kupkuru çorak","جنف":"haksızlığa kayma","زحزح":"uzaklaştırılma","حنجر":"gırtlak/boğaz",
"دهر":"zaman/dehr","حفف":"çepeçevre kuşatma","حقب":"nice yıllar/çağ (hukub)","عضل":"engel çıkarma/zorlaştırma","رفد":"destek/armağan",
"تور":"kez/defa (târe)","سفك":"kan dökme","دول":"el değiştirme/döndürme","عطل":"terk edilmiş/atıl","عنكب":"örümcek",
"زجج":"cam fanus/billur","غيض":"suyun çekilmesi/eksilme","غلي":"kaynama","قحم":"göğüs gerip dalma/atılma","حوش":"hâşâ",
"ذبب":"sinek","زمر":"bölük bölük/zümre","لقط":"yerden alıp bulma","ملق":"yoksulluk (imlâk)","شهق":"hıçkırıklı feryat/nefes çekişi",
"خنس":"sinip gizlenen (hünnes)","بسس":"un ufak savrulma","حطط":"bağışlanma dileği (hıtta)","ألل":"yemin/akrabalık bağı (ill)","رجج":"şiddetle sarsılma",
"رمم":"çürümüş kemik","كهل":"orta yaşlı/olgun","غرو":"salıverme/aralarına düşürme","خمص":"açlık darlığı/kıtlık","شيد":"sağlam yapılı/yükseltilmiş",
"هيج":"kuruyup sararmaa","كبب":"yüzüstü atılma","جذذ":"kesintisiz/kopmaz","قسطس":"doğru terazi/kıstas","محن":"imtihan etme/deneme",
"نكص":"gerisin geri dönme/topukları üzerinde kaçma","بطر":"nimet şımarıklığı/taşkınlık","كمه":"anadan doğma kör","سعد":"mutluluk/saîd","روض":"bahçe/ravza",
"محق":"silip yok etme/bereketini giderme","نبع":"kaynak/pınar","أمو":"cariye","عضض":"parmak ısırma","وصب":"kesintisiz/dâimî",
"عبث":"boş yere/oyun olsun diye","غوط":"tuvalet ihtiyacı/çukur yer","عتق":"eski/kadîm (Beyt-i Atîk)","غلو":"aşırıya kaçma/ğulüv","حنث":"yemini bozma",
"صنو":"aynı kökten çatal/ikiz","ضغن":"gizli kin (dığn)","حجز":"engel/perde","صفد":"pranga/zincir","جني":"devşirilmiş taze meyve",
"هرع":"koşuşturarak gelme","قلي":"darılıp terk etme","جرد":"çekirge","كرس":"kürsî","نشط":"düğümü çözercesine çıkarma/usulca çekme",
"عثر":"farkına varılma/ortaya çıkma","غطو":"perde/örtü","لبد":"üst üste yığılma/keçeleşme","غلف":"kılıflı/perdeli (kalp)","وسم":"iz süren/ferasetli",
"جلل":"ululuk/celâl","ثقب":"delip geçen ışıklı","حطب":"odun","أمل":"emel/uzun umut","قوع":"dümdüz boş ova",
"شغل":"meşguliyet/uğraş","وطر":"dilek/iş bitirme","طعن":"dil uzatma/saldırı","لبن":"süt","عضد":"pazu/destekçi",
"كهن":"kâhin","عزب":"gizli kalma/uzak kalma","عهن":"atılmış renkli yün","ودق":"yağmur damlası","قدو":"örnek alma/iktidâ",
"بعثر":"altüst edilip saçılma","ثخن":"iyice sindirme/ağır basma","بتل":"her şeyden kesilip yönelme/tebettül","كمم":"tomurcuk kılıfı","زلق":"kaygan/kaypak yer",
"خرب":"yıkıp harap etme",
}
