# -*- coding: utf-8 -*-
# Claude-üretimi kök adları, parti 4 (tek geçişliler)
ADLAR = {
"وكد":"pekiştirme/tekit","شكس":"geçimsiz/çekişen ortaklar","تين":"incir","سيب":"salıverilmiş deve (sâibe)","أيم":"bekârlar/eşsizler",
"تيه":"şaşkın dolaşma","عبأ":"değer verme/umursama","جبه":"alınlar","رتق":"bitişik/kapalı bütün","مزن":"yağmur bulutu",
"طرح":"atıp bırakma","صيص":"kaleler/burçlar (sayâsî)","غدق":"bol su/gürlük","زمل":"örtüsüne bürünen (müzzemmil)","قطمر":"çekirdek zarı/kıtmîr",
"غول":"baş ağrısı/sersemletme","دهق":"dolup taşan (kadeh)","ثرب":"kınama/başa kakma (tesrîb)","صفن":"soylu koşu atları (sâfinât)","دمدم":"kökünden kırıp geçirme",
"جمم":"pek çok/yığınla","صرع":"yere serilmiş/devrilmiş","حيف":"haksızlık etme","غمض":"göz yummadan alma/görmezden gelme","وفد":"heyet/konuk alayı",
"جلس":"meclisler","شمخ":"yüce/başı dik (dağlar)","رمز":"işaret/îmâ","قعر":"kökünden sökülmüş","حرس":"bekçiler",
"حثث":"kesintisiz kovalayan/hızlı","أثل":"ılgın ağacı","فرع":"dal/gövde üstü","سند":"dayalı kütükler (müsennede)","نحر":"kurban kesme/nahr",
"قصف":"kasıp kavuran fırtına","طلل":"çisenti/hafif yağmur","ينع":"olgunlaşma (meyve)","فوم":"sarımsak/buğday","جفأ":"atılıp giden köpük",
"سوح":"yurt/avlu (sâha)","غزو":"savaşa çıkma/gazâ","صكك":"yüzüne vurma/çarpma","هدم":"yıkılma","همر":"bardaktan boşanırcasına",
"شوك":"diken/silâh gücü","دهم":"koyu yeşil (iki cennet)","قشعر":"ürperip titreme","دسر":"gemi çivileri/perçin","مخض":"doğum sancısı",
"لفظ":"ağızdan söz çıkarma","درهم":"dirhem","لهم":"ilham etme","غصب":"zorla alma/gasp","وأل":"sığınılacak yer/mev'il",
"مشج":"karışım halinde (nutfe)/emşâc","تفث":"hac kirlerini giderme/tefes","هاء":"alın okuyun (hâüm)","صيف":"yaz","خلع":"çıkarma (ayakkabı)",
"فرث":"işkembe içi/fers","نون":"Nûn (harf)/balık sahibi","ليت":"eksiltme","صمع":"manastırlar (savâmi)","قني":"sermaye verip hoşnut etme",
"أبب":"otlak/mera (ebb)","وفر":"eksiksiz bol/mevfûr","حبك":"yollarla örülü (gök)/hubük","زهر":"dünya süsü/çiçeği (zehre)","كند":"nankör (kenûd)",
"جفو":"yataklardan uzaklaşma/tecâfî","معز":"keçi","وحش":"yaban hayvanları","ضير":"zarar","لقح":"aşılayıcı (rüzgârlar)/levâkıh",
"ذود":"sürüyü geri çekme/uzak tutma","رمد":"kül","قصم":"kırıp geçirme","نفث":"düğümlere üfleyen (neffâsât)","شرد":"darmadağın edip ürkütme",
"حير":"şaşkın/çaresiz (hayrân)","حصحص":"apaçık ortaya çıkma","نبط":"işin aslını çıkarma/istinbât","معي":"bağırsaklar (em'â)","دحو":"yayıp döşeme (yeri)",
"جمد":"donuk/hareketsiz sanılan (dağlar)","وبر":"deve tüyü/yapağı","قمل":"bit/haşerat (kummel)","وضن":"sırma işlemeli örgülü (tahtlar)","رتع":"gönlünce yiyip gezme",
"حيد":"kaçıp yan çizme","أبق":"kaçma (köle/gemiye)","نوأ":"ağır gelip bel büktürme (anahtarlar)","محل":"çetin tuzak/güç (mihâl)","زرق":"gök gözlü/morarmış (suçlular)",
"مسو":"akşama erme","نقع":"savrulan toz bulutu (nak')","وشي":"alacasız/lekesiz (şiye)","قدح":"kıvılcım çakma (kādihât)","نسر":"Nesr putu/kartal",
"زفف":"hızla süzülüp gelme","نوش":"uzaktan el uzatma/erişmeye çalışma (tenâvüş)","سجو":"sükûna erme/karanlığın durgunlaşması","حسم":"peş peşe uğursuz (günler)/husûm","جوس":"evleri arayıp tarama",
"نغض":"başını sallama","خبأ":"gizli saklı olan (hab')","فره":"ustalıkla şımarıkça (ev yontma)","قسر":"aslan (kasvere)","شمت":"düşmanı sevindirme/şamata",
"زهد":"değer vermeyen/isteksiz (zâhid)","لقم":"yutma (balığın Yûnus'u)","رفرف":"yeşil yastıklar/refref","شحم":"iç yağları (şuhûm)","جرر":"tutup çekme (kardeşinin başını)",
"خبو":"ateşin yavaşlaması/sönmeye yüz tutma","عبقر":"işlemeli döşekler/abkarî","فنن":"dallar/çeşitler (efnân)","خرطم":"burun/hortum (hurtûm)","سكت":"öfkenin dinmesi/susma",
"نجد":"iki apaçık yol (necdeyn)","قنو":"hurma salkımları (kınvân)","لقب":"lakap","جذو":"kor parçası/köz (cezve)","خشب":"kütükler/keresteler (huşub)",
"ضأن":"koyun (da'n)","رين":"kalbi pas tutma (rân)","ضنك":"dar/sıkıntılı geçim (dank)","أدد":"pek çirkin/korkunç şey (idd)","عنو":"yüzlerin boyun eğmesi (anet)",
"حفد":"torunlar (hafede)","نحب":"adağını yerine getirme/sonuna dek durma (nahb)","شمز":"tiksinip ürperme (iştimâzz)","همد":"kupkuru ölü (toprak)","جبن":"alın/şakak (cebîn)",
"نضخ":"fışkıran (iki pınar)/naddâha","بأر":"kuyu (bi'r)","حدب":"her tepeden (akın)/hadeb","بسم":"gülümseme (tebessüm)","عيب":"kusurlu yapma/ayıplama",
"زبن":"zebâniler","وفض":"koşup seğirtme (îfâd)","فصم":"kopma (kulpun)/infisâm","حنن":"gönül yumuşaklığı/şefkat (hanân)","قسس":"keşişler (kıssîsîn)",
"كدر":"yıldızların dökülüp kararması (inkedere)","وهي":"gevşeyip yarılma (gök)/vâhiye","صخخ":"kulakları sağır eden çığlık (sâhha)","ضمر":"yorgun zayıf binekler (dâmir)","فضح":"rezil etme",
"سلق":"sivri dille incitme (selk)","نطح":"süsülerek ölmüş (natîha)","فوض":"işini Allah'a bırakma/tefvîz","طلح":"muz ağacı/dikensiz akasya (talh)","ذبذب":"ikircikli bocalayan (müzebzeb)",
"شتو":"kış","جثث":"kökünden koparılma (icdüsse)","دثر":"örtüsüne bürünen (müddessir)","فقع":"parlak sapsarı (fâkı')","بجس":"fışkırıp akma (inbecese)",
"حرك":"dilini kıpırdatma (tahrîk)","صلد":"çıplak kaskatı kaya (sald)","بقع":"kutlu yer/bölge (buk'a)","نمرق":"sıra sıra yastıklar (nemârık)","قثأ":"salatalık (kıssâ)",
"شغف":"yüreğinin içine işleyen sevda (şeğafe)","شرط":"kıyamet alâmetleri (eşrât)","غطش":"geceyi karartma (ağtaşe)","ريش":"giyim süsü/tüy (rîş)","نكد":"verimsiz güç çıkan (bitki)/nekid",
"غبن":"aldanışın ortaya çıktığı gün (teğâbün)","مجس":"Mecûsîler","كنس":"yuvasına sinen yıldızlar (künnes)","نهج":"apaçık yol (minhâc)","لحي":"sakal (lihye)",
"رغم":"göç edip sığınacak yer/inadına genişlik (murâğam)","زمهر":"dondurucu soğuk (zemherîr)","دهي":"en belâlı/en acı (edhâ)","طود":"koca dağ (tavd)","سهم":"kura çekme (sâheme)",
"ثبي":"küçük birlikler halinde (sübât)","غلق":"kapıları sımsıkı kilitleme","سهل":"ovalar (sühûl)","غزل":"eğirilmiş iplik (ğazl)","أمت":"iniş çıkış/engebe (emt)",
"ذخر":"biriktirip saklama (iddihâr)","هدهد":"hüthüt kuşu","دسو":"nefsini karartıp gömme (dessâ)","عرم":"Arim seli/azgın baraj","سنم":"Tesnîm pınarı",
"كوي":"dağlanma (alınların)","جوو":"gök boşluğu (cevv)","دمغ":"beynini dağıtıp ezme (hakkın bâtılı)","خبط":"çarpıp sersemletme (şeytan)","ذهل":"dehşetten unutma (emzikli anne)",
"سحل":"sahil/kıyı","ألت":"amellerden eksiltme (elt)","قوس":"iki yay (kâbe kavseyn)","وهج":"alev alev parlayan (kandil)/vehhâc","عرجن":"kuru hurma dalı (urcûn)",
"دنر":"dinar","كشط":"göğün sıyrılıp açılması (küşitat)","هدد":"gürültüyle çöküp yıkılma (hedd)","ثري":"nemli toprak (serâ)","خمط":"buruk acı yemişli (ağaç)/hamt",
"خبز":"ekmek (hubz)","قمطر":"zorlu kara (gün)/kamtarîr","فيل":"fil","ضهأ":"öncekilerin sözüne özenme (mudâhât)","تعس":"yıkım olsun/yüzüstü düşme (ta's)",
"حقف":"Ahkāf/kum tepeleri","بلع":"suyunu yutma (yer)","فتق":"yarıp ayırma (gök ile yer)","زري":"hor görme (izdirâ)","حرد":"güç yetirme kararlılığı/engelleme (hard)",
"نضج":"derilerin pişip olması (nadicet)","مسخ":"suretini değiştirip dondurma (mesh)","بتر":"soyu kesik (ebter)","زنم":"soysuz damgalı (zenîm)","هيل":"akıp dağılan kum (mehîl)",
"فظظ":"kaba katı yürekli (fazz)","سردق":"kuşatan ateş duvarı/otağ (surâdık)","بصل":"soğan (basal)","حنذ":"kızartılmış (buzağı)/hanîz","عدس":"mercimek (ades)",
"صفصف":"dümdüz bomboş (yer)","هجد":"gece kalkıp namaz (teheccüd)","كفأ":"denk (küfüv)","سمك":"göğün yüksek tavanı (semk)","ثبط":"geri bırakıp alıkoyma (tesbît*)",
"جوف":"iç boşluğu/göğüs içi (cevf)","بقل":"sebze/baklagil (bakl)","سرد":"zırh halkalarını ölçülü dokuma (serd)","رخو":"tatlı yumuşak esen (rüzgâr)/ruhâ","ضيز":"haksız çarpık (paylaştırma)/dîzâ",
"رصص":"kurşunla kenetlenmiş (saf)/mersûs","دلك":"güneşin batıya kayması (dülûk)","مسد":"hurma lifi ip (mesed)","وأد":"diri diri gömülen kız (mev'ûde)","ضفدع":"kurbağalar (dafâdi)",
"رمض":"Ramazan","بهل":"lânetleşmeye çağırma (mübâhele)","قمح":"başı yukarı kalkık kalma (mukmah)","تلل":"alnı üzere yatırma (telle)","وسن":"uyuklama (sine)",
"دفق":"atılıp fışkıran (su)/dâfik","كفت":"toplayıp barındıran (yer)/kifât","حري":"doğruyu arama (taharrî)","ربح":"kâr etme (ticaret)","بيد":"yok olup gitme (tebîd)",
"كبد":"zorluk/meşakkat (kebed)","ذيع":"yayıp duyurma (izâa)","رحق":"mühürlü hâlis içecek (rahîk)","وطن":"savaş yerleri (mevâtın)","نمم":"laf taşıma/koğuculuk (nemîm)",
"شعل":"başın aklarla tutuşması (iştiâl)","مير":"erzak getirme (mîre)","خطط":"elle yazı yazma (hatt)","ترق":"köprücük kemikleri (terâkî)","وتن":"şah damarı (vetîn)",
"سمد":"gaflet içinde oyalanma (sâmid)","ضبح":"soluk soluğa koşan atlar (dabh)","عسل":"bal (asel)","وجب":"yanı üzerine düşme (vecebet)","قضض":"yıkılmaya yüz tutma (yenkadd)",
"تقن":"sapasağlam yapma (itkān)","لحف":"yüzsüzlük edip ısrar (ilhâf)","هشش":"yaprak silkeleme (ehüşşü)","كبكب":"yüzüstü atılma (kübkibû)","مطو":"çalım satarak yürüme (temettâ)",
"فتأ":"aralıksız sürdürme (tefteü)","رمح":"mızraklar (rimâh)","ذكو":"usulünce boğazlama (tezkiye)","ذأم":"kınanmış kovulmuş (mez'ûm)","سلب":"kapıp alma (yeslüb)",
"هيت":"haydi gel (heyte lek)","روع":"korkunun geçmesi (rav')","أود":"ağır gelip yorma (yeûdü)","لزب":"yapışkan (çamur)/lâzib","هجع":"gece az uyuma (hücû)",
"غصص":"boğaza duran (yiyecek)/gussa","نوي":"çekirdek (nevâ)","قضب":"yoncalık/taze ot (kadb)","بحث":"yeri eşeleme (yebhasü)","طفف":"ölçüde hile yapanlar (mutaffifîn)",
"فلن":"falanca (fülân)","نخر":"çürümüş dağılmış (kemik)/nahire","لحن":"söz eğip bükme/üslûp (lahn)","بسق":"boy atmış yüksek (hurmalar)/bâsikāt","جمح":"başını alıp koşma (yecmehûn)",
"عفر":"ifrit (cinlerden)","لوت":"geçti artık/vakit yok (lâte)","رهو":"denizi açık sakin bırakma (rahv)","جيد":"boyun (cîd)","صوع":"su kabı/ölçek (suvâ)",
"عول":"haksızlığa sapma/yoksul düşme (ta'ûlû)","ردم":"sağlam set (redm)","حتم":"kesinleşmiş hüküm (hatm)","مرو":"Merve","ختر":"gaddar dönek (hattâr)",
"فصح":"dili daha düzgün (efsah)","عسعس":"gecenin kararıp çekilmesi","سدي":"başıboş bırakılma (südâ)","ريع":"her yüksek tepe (rî')","ثجج":"şarıl şarıl dökülen (su)/seccâc",
"طمم":"her şeyi bastıran büyük felâket (tâmme)","نعق":"çobanın bağırması (yen'ıku)","أسن":"bozulmayan (su)/âsin","سنه":"yıllanıp bozulma (yetesenneh)","فند":"bunaklıkla suçlama (tüfennidûn)",
"وكز":"yumruk vurma (vekeze)","عزو":"bölük pörçük gruplar (ızîn)","كثب":"akıp dağılan kum yığını (kesîb)","ذعن":"boyun eğip koşarak gelme (müz'inîn)","سفع":"perçemden yakalayıp sürükleme (nesfean)",
"رقق":"ince açılmış sayfa (rakk)","حوب":"büyük günah (hûb)","خيم":"çadırlar (hıyâm)","عضو":"parça parça bölme (ıdîn)","نفح":"azaptan hafif bir esinti (nefha)",
"ركد":"denizde durgun kalma (revâkid)","كسد":"durgunluk (ticarette)/kesâd","شفه":"iki dudak (şefeteyn)","بتك":"hayvan kulaklarını yarma (yübettikû)","كلح":"dudakları çekilip sırıtan (kâlih)",
"فهم":"kavratma (fehhemnâ)","سطو":"saldırıp çullanma (yestûne)","سطح":"yerin serilip döşenmesi (sutihat)","شوظ":"dumansız alev (şüvâz)","فضو":"başbaşa kalma (efdâ)",
"نوص":"kaçıp kurtulacak yer (menâs)","زرب":"serili saçaklı halılar (zerâbî)","جسس":"gizlice araştırma (tecessüs)","خنق":"boğulmuş hayvan (münhanika)","وني":"gevşeklik gösterme (teniyâ)",
"ظعن":"göç günü (za'n)","شرذم":"küçük azlık topluluk (şirzime)","لوذ":"sıvışıp gizlenme (livâz)","نتق":"dağı yerinden koparıp kaldırma (netaknâ)","نجس":"pis (neces)",
"نعل":"ayakkabılar (na'leyk)","يقظ":"uyanıklar (eykāz)","فجو":"mağara boşluğu/açıklık (fecve)","صوف":"yünler (asvâf)","بطأ":"ağır davranıp geri kalma (yübattıe)",
"طحو":"yerin yayılıp döşenmesi (tahâhâ)","بغل":"katırlar (biğâl)","ركز":"en hafif ses/fısıltı (rikz)","سوط":"kamçı (sevt)","نبز":"kötü lakap takma (tenâbüz)",
"عطف":"böbürlenip yan çizme (sânîye ıtfih)","دفأ":"ısınma/sıcaklık (dif')","وقب":"karanlığın çöküp basması (vekabe)","سهر":"dümdüz uyanıklık yeri/mahşer (sâhire)","كدي":"elindekini kesip vermeme (ekdâ)",
"جفن":"havuz gibi çanaklar (cifân)","زحف":"ordu halinde ilerleme (zahf)","همس":"ayak fısıltısı/hışırtı (hems)","هرب":"kaçış (hereb)","قطط":"amel defteri/pay (kıtt)",
"عوق":"alıkoyup engelleyen (muavvikîn)","لفح":"ateşin yüzü yalaması (telfehu)","جبت":"cibt/put","لظي":"alev alev tutuşma (telezzâ)","حصل":"kalplerdekinin ortaya dökülmesi (hussıle)",
"ضنن":"gaybdan kıskanmayan (danîn)","ثيب":"dul (seyyibât)","قبح":"çirkin kılınmışlar (makbûhîn)","عمق":"derin uzak (yol)/amîk","جرف":"göçmek üzere olan uçurum kenarı (cüruf)",
"فني":"gelip geçici olma (fân)","دسس":"toprağa gömme (yedüssü)","هزل":"şaka/boş söz (hezl)","ضدد":"karşıt/aleyhte (dıdd)","شوب":"karışım/üstüne katık (şevb)",
"حوز":"bir birliğe katılma (mütehayyiz)","قوب":"iki yay arası mesafe (kābe)","كلأ":"gece gündüz koruma (yekleü)","أنم":"bütün canlılar (enâm)","صمت":"suskun (sâmit)",
"صمد":"Samed/her şeyin kendisine muhtaç olduğu","ردأ":"yardımcı/destek (rid')","هلع":"dayanıksız hırslı (helû)","غمز":"kaş göz işareti (yeteğâmezûn)","سكب":"çağlayıp dökülen (su)/meskûb",
"مكو":"ıslık çalma (mükâ)","قرش":"Kureyş","سغب":"açlık günü (mesğabe)","قمع":"demir topuzlar (mekāmi)","جرع":"yudum yudum zorla yutma (yetecerrau)",
"خضد":"dikensiz kesilmiş (sedir)/mahdûd","وقذ":"vurularak ölmüş (mevkūze)","قفل":"kilitler (akfâl)","قلع":"suyunu tutma (gök)/akli'","نفي":"sürgün edilme (yünfev)",
"صعر":"insanlardan yüz çevirme (tusa''ir)","فسر":"açıklama/tefsir","بدر":"tez elden savurma (bidâr)","حنك":"peşine takıp yönetme (ahtenike)",
}
