# -*- coding: utf-8 -*-
"""ahzab_metin_1.py — sûre 33 (Ahzâb) meal ve matematikçi merceği, ayet 1-73.
Arapça sabit YOK: kökler yalnız korpus kök biçimiyle anılır, kelime biçimleri Latin harfle."""
MEAL = {
 1: "Ey Peygamber! Allah'tan sakın; kâfirlere ve münafıklara boyun eğme. Şüphesiz Allah bilendir, hikmet sahibidir.",
 2: "Rabbinden sana vahyolunana uy. Şüphesiz Allah yaptıklarınızdan haberdardır.",
 3: "Allah'a dayan; vekil olarak Allah yeter.",
 4: "Allah bir adamın göğsünde iki kalp yaratmadı. Zıhar yaptığınız eşlerinizi analarınız kılmadı, evlatlıklarınızı da oğullarınız kılmadı. Bu, sizin ağızlarınızdaki sözünüzdür. Allah ise gerçeği söyler ve O yola iletir.",
 5: "Onları babalarına nispet ederek çağırın; bu, Allah katında daha adildir. Babalarını bilmiyorsanız, onlar dinde kardeşleriniz ve dostlarınızdır. Yanıldığınız şeyde size bir günah yok; ama kalplerinizin kastettiğinde var. Allah bağışlayandır, esirgeyendir.",
 6: "Peygamber mü'minlere kendilerinden daha yakındır; eşleri onların analarıdır. Akrabalar, Allah'ın Kitabı'nda birbirlerine, mü'minlerden ve muhacirlerden daha yakındır — dostlarınıza bir iyilik yapmanız müstesna. Bu, Kitap'ta yazılmıştır.",
 7: "Hani peygamberlerden ahitlerini almıştık: senden, Nûh'tan, İbrâhîm'den, Mûsâ'dan ve Meryem oğlu Îsâ'dan. Onlardan ağır bir ahit almıştık —",
 8: "— doğrulara doğruluklarını sorsun diye. Kâfirlere de acıklı bir azap hazırladı.",
 9: "Ey iman edenler! Allah'ın üzerinizdeki nimetini anın: hani size ordular gelmişti; biz de üzerlerine bir rüzgâr ve sizin görmediğiniz ordular göndermiştik. Allah yaptıklarınızı görendir.",
 10: "Hani üstünüzden ve aşağınızdan size gelmişlerdi; hani gözler kaymış, yürekler gırtlaklara dayanmıştı ve Allah hakkında türlü zanlarda bulunuyordunuz.",
}
M = {
 1: "◇ Sûre nidâ ile açılıyor ve muhatap adıyla değil KONUMUYLA çağrılıyor (yâ eyyühe'n-nebiyy). Bir emir, bir yasak, sonra çift mühür (alîm-hakîm). ikili alanı bu ayette BEŞ köklü çift veriyor — blokun en yoğunu; ama beşinin ikisi kalıp: mühür formülü (kâne-Allah, 6 ayet) ve nidâ formülü (eyy-nebî, 5 ayet). Esmâ kaydı: a=1 · e_el=1 · mühür ÇİFT, ton cemâl.",
 2: "◇ Blokun TEK Rab'i ve tek edilgeni aynı kelimede değil ama aynı cümlede: 'sana vahyolunan' (edilgen) + 'Rabbinden'. Rab özel hitap (2MS) içinde, lafız ise genel hitap (2MP) içinde: 'Rabbin' sana, 'Allah' hepinizin yaptığına. Eski esma_k MÜHÜRSÜZ diyor (tek esmâ, çift yok); ön-kaydın §4.3 tanımıyla MÜHÜR — aday 961'in 'tekil gerçek esmâ' türü.",
 3: "◇ Altı kelime, iki lafız, iki وكل: ayet kendi içinde kapalı bir halka — tevekkül et → vekil olarak yeter. ★★★'ın TEK kaynağı allah z=6,14, yani 2/6 lafız yoğunluğu; kısa ayette oran büyür (içerik değil ölçek). nakarat3 'tam' türünde tüm ayeti 33:48 ile eşliyor (6 kelime / 2 ayet) — sûre bu formülü 45 ayet sonra aynen tekrarlıyor. Esmâ vekîl katalogda TON TAŞIMIYOR (aşağıda borç).",
 4: "◇ ÜÇ olumsuz kılma (mâ ce'ale ×3), aynı sözdizimi, üç ayrı alan: beden (bir göğüste iki kalp) · evlilik (zıhar edilen eş anne değil) · soy (evlatlık oğul değil). Matematikçi okuması: üç yeniden-etiketleme reddi — bir nesneye verilen AD onun sınıfını değiştirmiyor; kapanış bunu adıyla söylüyor: 'bu sizin ağızlarınızdaki sözünüz'. İlk önerme bedensel bir olgu (🜁 kademe L1, olgu EVET: sayı + organ + yer; mekanizma yok), ama ayet onu olgu olarak değil ANALOJİNİN TABANI olarak kullanıyor. Tarayıcı v4 aday vermedi — doğru negatif (L4 değil). ★★★: hapaks جوف (z=3,28); ayrıca n z=1,65 ve sûrenin TEK kafiye kırığı — üç bağımsız işaret, formül yalnız birini sayıyor (borç #15). Fâsıla ile ilgili TAM SAYIM aşağıda.",
 5: "◇ 33:4'ün soy yasağının pozitif karşılığı: 'babalarına nispet edin'. Baba bilinmiyorsa YENİ sınıf veriliyor: dinde kardeş ve mevlâ. Yani 33:4-5 birlikte bir sınıflama kuralı: soy etiketi yalnız soya verilir; soy bilinmezse başka bir ilişki adı kullanılır. Hata/kasıt ayrımı ('yanıldığınız' / 'kalplerinizin kastettiği') — sorumluluk niyete bağlanıyor. قلب ikinci kez (33:4 bedensel kalp · 33:5 niyet eden kalp · 33:10 gırtlağa dayanan kalp): üç ayette üç ayrı işlev.",
 6: "◇ 33:4'ün simetrik karşıtı: orada 'eşlerinizi ANALARINIZ kılmadı', burada Peygamber'in 'eşleri ONLARIN ANALARIDIR'. أمم kökü iki ayette iki kez ve iki kez ters yönde: aynı etiket bir yerde reddediliyor, bir yerde veriliyor. Fark etiketi kimin koyduğu: 33:4'te 'ağızlarınızdaki söz', 33:6'da 'Kitap'ta yazılmış'. Esmâ üç token (mü'min ×2, velî) ve ÜÇÜ DE ilâhî değil — mü'minler ve dostlar; e_oto=1, e_el=0. Sınama kümesine 32:4/32:18 ile aynı iki lemma ekleniyor.",
 7: "◇ Lafız YOK, Rab YOK, esmâ YOK — ama fiil 1P (almıştık): konuşan açık. Beş adlı peygamber ve ADSIZ bir altıncı: 'senden' (2MS) — muhatap adlı listenin başında ama adsız. mîsâkan galîzan: xref 4:21 ve 4:154 — aynı ifade korpusta üç ayrı ilişkiye veriliyor (evlilik ahdi · İsrâiloğulları · peygamberler); sûre 4 okunmadığı için bağ DOĞRULANMADI, yalnız kaydedildi.",
 8: "◇ Amaç cümlesi: ahit alınması bir sorgunun ÖN KOŞULU (doğrulara doğruluklarını sormak). صدق ×2 aynı cümlede (sâdıkîn / sıdk) — ölçen ve ölçülen aynı kök. say alanı a'adde fiilini sayı işareti diye yakalıyor: عدد kökü ama anlam 'hazırlamak' — yanlış pozitif (borç #13 ailesi).",
 9: "◇ Olay anlatısı başlıyor ve ilk anılan şey NİMET: 'anın'. İki ordu karşılaştırılıyor: size gelen ordular (جند ×2) ve sizin görmediğiniz ordular — aynı kelime, biri görülen biri görülmeyen. Rüzgâr: روح kökü (aday 946 onarımı burada doğru eşledi). 🜁 kademe L0, olgu evet (rüzgâr adlandırılıyor, başka iddia yok). Tarayıcı v4 bu ayeti G_bakış ile ADAY VERDİ ('görmediğiniz') — çıpa değil: kesinlik 0/1. Eski esma_k mühürsüz, §4.3 ile mühür (tekil basîr).",
 10: "◇ Kuşatma iki eksenle çiziliyor: üst/alt (fevk / esfel) ve dış/iç — dışarıda ordular geliyor, içeride gözler kayıyor, yürekler gırtlağa çıkıyor, zanlar çoğalıyor. Beden hareketi DİKEY: yürek aşağıdan yukarı. ظنن ×2 (fiil + aynı kökten belirli çoğul isim, ACC) — biçim olarak mef'ûl-i mutlak, ama mm2 YAKALAMIYOR: araya lafız giriyor, mm2 bitişiklik istiyor (27:58'deki bilinen negatifin ikinci vakası; araç açığı, metin hakkında bilgi değil — aday 924). Fâsıla 'ez-zunûnâ': sonda uzatma elifi.",
}
MEAL2 = {
 11: "Orada mü'minler imtihan edildi ve şiddetli bir sarsıntıyla sarsıldılar.",
 12: "Hani münafıklar ve kalplerinde hastalık olanlar, 'Allah ve Resûlü bize aldatmacadan başka bir şey vaat etmedi' diyorlardı.",
 13: "Hani onlardan bir grup, 'Ey Yesrib halkı! Sizin için durulacak yer yok, geri dönün' demişti. Onlardan bir kısmı da 'Evlerimiz korunmasız' diyerek Peygamber'den izin istiyordu; oysa evleri korunmasız değildi. Onlar yalnızca kaçmak istiyorlardı.",
 14: "Eğer (şehrin) çevresinden üzerlerine girilse, sonra kendilerinden fitne istenseydi, onu hemen yaparlardı ve bunda pek az dururlardı.",
 15: "Oysa daha önce arkalarını dönüp kaçmayacaklarına dair Allah'a ahit vermişlerdi. Allah'a verilen ahit sorulacaktır.",
 16: "De ki: 'Ölümden ya da öldürülmekten kaçıyorsanız, kaçmak size fayda vermez; o zaman da ancak az bir süre yararlandırılırsınız.'",
 17: "De ki: 'Allah size bir kötülük dilerse ya da size bir rahmet dilerse, sizi Allah'tan kim koruyabilir?' Kendileri için Allah'tan başka ne bir dost ne bir yardımcı bulurlar.",
 18: "Allah içinizden (savaştan) alıkoyanları ve kardeşlerine 'Bize gelin' diyenleri bilir. Onlar savaşa pek az gelirler.",
 19: "Size karşı cimridirler. Korku gelince, ölüm baygınlığı geçiren kimse gibi gözleri dönerek sana baktıklarını görürsün. Korku gidince de mala düşkünlükle sizi keskin dillerle incitirler. Onlar iman etmemişlerdir; Allah da amellerini boşa çıkarmıştır. Bu, Allah'a kolaydır.",
 20: "Ahzâb'ın gitmediğini sanıyorlar. Ahzâb yeniden gelse, bedevîler arasında çölde olup sizin haberlerinizi uzaktan sormayı isterler. Aranızda olsalardı da pek az savaşırlardı.",
}
M2 = {
 11: "◇ Altı kelime, iki fiil, ikisi de EDİLGEN (pas z=5,38 → ★★★'ın tek kaynağı): imtihan eden ve sarsan adlandırılmıyor. zülzilû zilzâlen — mm2 BURADA YAKALIYOR (fiil ve masdar bitişik). 33:10 ile yan yana: iki ardışık ayet, iki mef'ûl-i mutlak, alan birini görüyor birini görmüyor — fark metinde değil bitişiklik koşulunda. بلو kökünün glossu 'eskiyip yıpranma', ama burada ve kökün baskın lemmalarında anlam SINAMA (aşağıda borç). Esmâ mü'min yine insan: e_oto=1 → sınıf E, e_el=0 → sınıf 0; §4.3 son-üç tanımı bunu MÜHÜR sayıyor.",
 12: "◇ 33:1'in yasak muhataplarından münafıklar burada konuşuyor; bir grup ekleniyor: 'kalplerinde hastalık olanlar' (قلب dördüncü kez). Söz HASR kalıbında (mâ ... illâ): vaat = aldatmaca. xref 33:60 — aynı üçlü sûrede tekrar gelecek.",
 13: "◇ Sûrenin tek adlı yeri: Yesrib (PN, yer). İki grup iki eylem: biri 'geri dönün' diyor (tâife), öbürü izin istiyor (ferîk) — adsiz2 ikisini de yakalıyor. عور ×2, iddia ve düzeltme aynı ayette: 'evlerimiz korunmasız' / 'korunmasız değildi'. Beyan ile durum açıkça ayrılıyor; yapı L3'e (görünüş-durum) benziyor ama konu olgu değil niyet: 🜁 olgu HAYIR, çıpa değil. Kapanış niyeti adlandırıyor: firar.",
 14: "◇ Karşı-olgusal şart (lev): gerçekleşmemiş bir kuşatma ve gerçekleşmemiş bir itaat. İki edilgen (dühılet · süilû) → ★★'ın tek kaynağı pas z=2,52. سأل kökü sûrede ikinci kez ve ters yönde: 33:8'de sâdıklara sorulur, burada onlardan fitne istenir.",
 15: "◇ 33:7-8'in ahit-sorgu çiftinin geri dönüşü: orada peygamberlerden ahit alınıp sâdıklara sorulacaktı; burada bunlar Allah'a ahit vermiş ve 'Allah'ın ahdi sorulacak' (عهد ×2, سأل üçüncü kez). ولي kökü burada 'arka çevirmek' anlamında; gloss 'dost, veli' bu kullanımı taşımıyor. ★★: allah z=2,55.",
 16: "◇ Kaçış kendi başına ölçülüyor: fayda vermez, verse de 'az'. فرر ×2 ve 33:13'ün son kelimesi firârâ — iki ayet aynı kökle bağlı. Fâsıla qalîlâ bu blokta 16, 18 ve 20'de: ÇİFT sıradaki üç ayet aynı kelimeyle kapanıyor (TAM SAYIM bilançoda). Tarayıcı v4 A_şart ile aday verdi — çıpa değil.",
 17: "◇ Simetrik soru: kötülük de rahmet de aynı fiille (رود ×2) Allah'ın dilemesine bağlanıyor ve ikisinden de 'korunma' soruluyor. Esmâ velî + nasîr ÇİFT olarak ayet sonunda, ama olumsuzlanan 'Allah'tan başka' birinin sıfatı: e_el=0. §4.3 tanımı bunu ÇİFT MÜHÜR sayıyor — 32:4 velî vakasının çift hâli ve ön-kayıt sınama kümesi için şimdiye kadarki en temiz yanlış mühür.",
 18: "◇ Allah bilen — 33:1'in alîm'i burada fiil (ya'lemu). ★★★ hapaks عوق (mu'avvikîn, 'alıkoyanlar'); هلم sûrede tek ama korpusta iki kez, hapaks değil. Kapanış yine 'az'.",
 19: "◇ Blokun en uzun ayeti (n=35, n z=2,40) ve bir teşbih: gözleri 'ölüm baygınlığı geçiren gibi' dönüyor. Korku iki kez (خوف ×2), iki yönde: gelince bakakalıyorlar, gidince dil uzatıyorlar — iki davranış korkunun varlığına ve yokluğuna bağlanıyor. شحح ×2 çerçeve. ★★★ hapaks سلق; ikinci bağımsız ölçüt n z=2,40 de eşiği geçiyor ve formül eklemiyor (borç #15'in yeni vakası). دور glossu 'yurt, ev' — tedûru (dönmek) için yanlış. 🜁 kademe L1 (davranış + karşılaştırma), olgu HAYIR.",
 20: "◇ Sûrenin adı ilk kez burada: el-ahzâb ×2 (حزب sûrede 3 kez: 20'de iki, 22'de bir) — ad metinde 20. ayete kadar geçmiyor. İki karşı-olgusal şart daha: 'gelseler' / 'aranızda olsalardı'. عرب kökü (a'râb) sûrede tek. Blok üçüncü qalîlâ ile kapanıyor.",
}
MEAL.update(MEAL2); M.update(M2)

MEAL3 = {
 21: "Andolsun, Resûlullah'ta sizin için —Allah'ı ve âhiret gününü uman ve Allah'ı çok anan kimse için— güzel bir örnek vardır.",
 22: "Mü'minler Ahzâb'ı görünce, 'İşte bu, Allah ve Resûlünün bize vaat ettiğidir; Allah ve Resûlü doğru söylemiş' dediler. Bu, onların yalnızca imanını ve teslimiyetini artırdı.",
 23: "Mü'minler içinde Allah'a verdikleri ahde sadık kalan adamlar vardır. Onlardan kimi adağını yerine getirdi, kimi de beklemektedir. Onlar hiçbir şekilde (ahitlerini) değiştirmediler.",
 24: "Allah sadıkları sadakatleri sebebiyle mükâfatlandırsın, münafıklara da dilerse azap etsin ya da tevbelerini kabul etsin diye. Şüphesiz Allah bağışlayandır, esirgeyendir.",
 25: "Allah inkâr edenleri öfkeleriyle, hiçbir hayra ulaşamadan geri çevirdi. Savaşta Allah mü'minlere yetti. Allah güçlüdür, üstündür.",
 26: "Onlara destek veren Kitap ehlini de kalelerinden indirdi ve kalplerine korku saldı. Bir kısmını öldürüyor, bir kısmını da esir alıyordunuz.",
 27: "Sizi onların topraklarına, yurtlarına, mallarına ve henüz ayak basmadığınız bir toprağa mirasçı kıldı. Allah her şeye gücü yetendir.",
 28: "Ey Peygamber! Eşlerine de ki: 'Eğer dünya hayatını ve onun süsünü istiyorsanız gelin size boşanma bedelinizi vereyim ve sizi güzellikle salıvereyim.'",
 29: "'Eğer Allah'ı, Resûlünü ve âhiret yurdunu istiyorsanız, şüphesiz Allah içinizden iyilik yapanlara büyük bir mükâfat hazırlamıştır.'",
 30: "Ey Peygamber'in hanımları! Sizden kim apaçık bir hayâsızlık yaparsa, onun azabı iki kat artırılır. Bu, Allah'a kolaydır.",
}
M3 = {
 21: "◇ Blokun ekseni burada kuruluyor: bir ÖRNEK (üsve hasene) ve örneğe kimin bakacağının iki koşulu (Allah'ı ve âhiret gününü ummak · Allah'ı çok anmak). Üç lafız (★★'ın tek kaynağı allah z=3,00). xref 60:6 — aynı ifade başka bir sûrede İbrâhîm için; sûre 60 okunmadığı için DOĞRULANMADI. Esmâ âhir: 'âhiret GÜNÜ'nün sıfatı, e_el=0 — ve son-üç içinde olduğu için §4.3 bunu MÜHÜR sayıyor (sûrede üçüncü yanlış mühür). say alanı kesîr'i sayı işareti sayıyor.",
 22: "◇ 33:12'nin AYNASI. Aynı dört kelimelik kalıp (mâ ve'adenallâhu ve rasûluh, nakarat3) iki grubun ağzında, aynı olayın (Ahzâb'ı görmek) karşısında: münafıklar 'bu vaat aldatmacadan başka bir şey değil' (33:12, HASR → gurûr) · mü'minler 'bu vaat edilenin kendisi, doğru söylemişler' (33:22, HASR → îmân ve teslîm). İki HASR, aynı sözdizimi, iki ters sonuç. حزب kökü burada 3/3 ile tamamlanıyor. Esmâ mü'min yine insan (e_el=0).",
 23: "◇ 33:15'in AYNASI: عهد kökü sûrede üç kez ve üçü de bu iki ayette — 33:15'te verilen ve bozulan ahit, 33:23'te 'ahde sadakat'. Sadık kalanlar iki alt kümeye bölünüyor: 'adağını tamamlayan' ve 'bekleyen' — ve iki küme için tek ortak yüklem: 'hiç değiştirmediler' (beddelû tebdîlen: mm2 yakaladı, bitişik). ★★★ hapaks نحب. Adsız aktör racül: 33:4'teki racül'ün (iki kalpli olmayan adam) sûredeki ikinci geçişi.",
 24: "◇ 33:8'in AYNASI, neredeyse harf harf: 33:8 li-yes'ele es-sâdıkîne 'an sıdkıhim (sorsun diye) · 33:24 li-yecziye'llâhu es-sâdıkîne bi-sıdkıhim (karşılık versin diye). Aynı amaç lâmı, aynı nesne, aynı ölçü — yalnız fiil değişiyor: SORGU → KARŞILIK. Blok 1'de açılan ahit-sorgu ipliği (33:7-8 → 33:15) burada kapanıyor. Münafıklar için tek bir sonuç yok, ŞART var: 'dilerse azap eder ya da tevbelerini kabul eder' — kapı açık. Mühür gafûr-rahîm ÇİFT: 33:5 ile aynı çift, cemâl.",
 25: "◇ Üç lafız (★★★'ın tek kaynağı allah z=3,22). كفي kökü sûrede ikinci kez: 33:3 'vekil olarak Allah YETER' (ilke) → 33:25 'Allah mü'minlere savaşta YETTİ' (olay). İlk bloktaki tevekkül formülünün olay karşılığı. Mühür kavî-azîz ÇİFT; esma_kayit tonu 'karma' diyor ama sebep ton farkı değil: kavî katalog-dışı, azîz katalogda cemâl. 'karma' etiketi eksik tonla gerçek ton farkını ayırmıyor (aşağıda borç). mü'min burada nesne (insan), e_el=0.",
 26: "◇ Lafız yok ama fail Allah (enzele, kazefe): 33:9-10'un kuşatması TERSİNE dönüyor — orada ordular yukarıdan ve aşağıdan geliyor, yürekler gırtlağa çıkıyordu; burada destek verenler kalelerinden İNDİRİLİYOR ve kalplerine korku ATILIYOR (قلب beşinci kez, beşinci işlev). Kapanış bir ayna sıralama: ferîkan taktulûne ve te'sirûne ferîkâ — isim-fiil-fiil-isim. ظهر kökü sûrede iki kez, iki ayrı anlam: 33:4 zıhar (eşi anaya benzetmek) · 33:26 zâherûhum (destek vermek). ★★★ hapaks صيص. xref 59:2 (kalplere korku atmak) — DOĞRULANMADI.",
 27: "◇ Miras dört kalem: toprak, yurt, mal ve 'henüz ayak basmadığınız bir toprak'. أرض ×2 bilinen ve bilinmeyen yer. 33:9 'görmediğiniz ordular' ile yan yana konunca blokta algılanmamış bir şey iki kez anılıyor — okurken fark edildi, sayılmadı. دور glossu ('yurt, ev') bu kez doğru (diyâr). Mühür kadîr TEKİL: eski esma_k mühürsüz, §4.3 geçerli mühür. nakarat3 'alâ kulli şey'in kadîr formülünü eşliyor.",
 28: "◇ BÖLÜM GEÇİŞİ: 'yâ eyyühe'n-nebî' sûrede ikinci kez (33:1'den sonra) ve hitap İLK KEZ 2FP — sûrenin ilk 27 ayetinde dişil çoğul muhatap YOK, bu ayette 8 kez (TAM SAYIM, ölçüm satırı). 33:28-29 bir ikili seçim: aynı şart fiili (in kuntunne turidne) iki dal açıyor — dünya hayatı ve süsü / Allah, Resûl ve âhiret yurdu. mm2 serâhan cemîlen yakalandı (bitişik). say alanı zevc'i yine sayı işareti sayıyor (sûrede üçüncü). Tarayıcı v4 A_şart ile ADAY verdi — çıpa değil.",
 29: "◇ İkinci dal ve karşılığı. a'adde (hazırladı) sûrede ikinci kez ve iki uçta: 33:8 kâfirlere acıklı AZAP · 33:29 muhsinelere büyük ECİR — aynı fiil, iki karşıt nesne. say alanı ikisini de sayı işareti sayıyor. Esmâ âhir burada 'âhiret YURDU'nun sıfatı (e_el=0); son-üç dışında kaldığı için bu kez mühür üretmedi. Son kelime azîm: varlik_katalog'da ilâhî isim, esmâ listesinde yok.",
 30: "◇ Hitap yine nidâ ile, bu kez konumla değil İLİŞKİYLE: 'ey Peygamber'in hanımları'. ضعف ×2: 'azabı İKİ KAT artırılır' (yudâ'af · di'fayn) — ayetteki TEK gerçek sayı ifadesi (ikili). say alanı bunu YAKALAMIYOR, oysa bu blokta kesîr, zevc ve a'adde'yi yakaladı: yanlış negatif (borç #13). Kapanış 'bu Allah'a kolaydır' 33:19 ile aynı beş kelime (nakarat3): orada amellerin boşa çıkarılması, burada azabın katlanması. xref 4:19, 65:1 (fâhişe mübeyyine) — okunmadı. ★ pas z=1,57 (yudâ'af)."
}
MEAL.update(MEAL3); M.update(M3)

MEAL4 = {
 31: "Sizden kim Allah'a ve Resûlüne gönülden itaat eder ve salih amel işlerse, ona mükâfatını iki kat veririz; ona cömertçe bir rızık da hazırlamışızdır.",
 32: "Ey Peygamber'in hanımları! Siz kadınlardan herhangi biri gibi değilsiniz. Eğer sakınıyorsanız, konuşurken yumuşak bir eda takınmayın ki kalbinde hastalık bulunan kimse ümide kapılmasın; uygun söz söyleyin.",
 33: "Evlerinizde oturun; ilk câhiliye döneminin açılıp saçılması gibi açılıp saçılmayın. Namazı kılın, zekâtı verin, Allah'a ve Resûlüne itaat edin. Ey Ehl-i Beyt! Allah sizden ancak kiri gidermek ve sizi tertemiz yapmak istiyor.",
 34: "Evlerinizde okunan Allah'ın âyetlerini ve hikmeti anın. Şüphesiz Allah lütufkârdır, her şeyden haberdardır.",
 35: "Müslüman erkekler ve müslüman kadınlar, mü'min erkekler ve mü'min kadınlar, gönülden itaat eden erkekler ve kadınlar, doğru erkekler ve doğru kadınlar, sabreden erkekler ve kadınlar, huşû içinde olan erkekler ve kadınlar, sadaka veren erkekler ve kadınlar, oruç tutan erkekler ve kadınlar, iffetlerini koruyan erkekler ve kadınlar, Allah'ı çok anan erkekler ve kadınlar — Allah bunlar için bağışlanma ve büyük bir mükâfat hazırlamıştır.",
 36: "Allah ve Resûlü bir işe hüküm verdiği zaman, mü'min bir erkek ve mü'min bir kadın için o işi kendi isteklerine göre seçme hakkı yoktur. Kim Allah'a ve Resûlüne karşı gelirse apaçık bir sapıklığa düşmüştür.",
 37: "Hani Allah'ın nimet verdiği, senin de iyilik ettiğin kimseye 'Eşini yanında tut, Allah'tan sakın' diyordun. Allah'ın açığa çıkaracağı şeyi içinde gizliyordun; insanlardan çekiniyordun, oysa asıl çekinmene lâyık olan Allah'tır. Zeyd ondan ilişiğini kesince, onu seninle evlendirdik ki evlatlıklarının eşleriyle —evlatlıkları onlardan ilişiklerini kestiklerinde— evlenmekte mü'minlere bir güçlük olmasın. Allah'ın emri yerine gelmiştir.",
 38: "Allah'ın kendisine farz kıldığı şeyde Peygamber'e bir güçlük yoktur. Bu, Allah'ın daha önce gelip geçenler hakkında da uyguladığı yasadır. Allah'ın emri, takdir edilmiş bir kaderdir.",
 39: "Onlar Allah'ın mesajlarını tebliğ eden, O'ndan korkan ve Allah'tan başka kimseden korkmayanlardır. Hesap görücü olarak Allah yeter.",
 40: "Muhammed sizin adamlarınızdan hiçbirinin babası değildir; fakat o, Allah'ın Resûlü ve peygamberlerin sonuncusudur. Allah her şeyi bilendir.",
}
M4 = {
 31: "◇ 33:30'un AYNASI, yine tek ayet arayla: 33:30 azabı İKİ KAT (di'fayn) · 33:31 ecri İKİ KERE (merrateyn). Aynı ikil, iki yön. say alanı ikisini de YAKALAMIYOR — iki ardışık gerçek sayı ifadesi, sıfır işaret (aday 992'nin ikinci vakası). Konuşan 1P'ye geçiyor (nu'tihâ, a'tednâ); iltifât alanı 0 diyor çünkü geçiş ayetler arası (33:30'da 'Allah'a kolaydır' 3MS). عتد 'hazırladık' — 33:8 ve 33:29'daki a'adde ile aynı iş, başka kök; say alanı bunu yakalamıyor, a'adde'yi yakalıyordu: aynı anlam, iki kök, iki farklı alan davranışı. Esmâ kerîm rızkın sıfatı: §4.3 YANLIŞ MÜHÜR.",
 32: "◇ Bir SINIFLAMA cümlesiyle açılıyor: 'siz kadınlardan herhangi biri gibi değilsiniz' — 33:4'ün üç sınıf reddi ve 33:6'nın 'eşleri analarıdır' ataması ile aynı iş: bir grubu genel kümeden ayırmak. Yasak konuşmanın BİÇİMİ üzerine (tahda'ne bi'l-kavl), emir de biçim üzerine (kavlen ma'rûfen, mm2 yakaladı). قول ×3. 'Kalbinde hastalık olan' sûrede ikinci kez (33:12'den sonra; nakarat3). Esmâ ehad 'herhangi biri' → e_oto=1 sınıf E, e_el=0 sınıf 0 — lafızsız ayette esmâ yanlış pozitifinin sınıfı doğrudan değiştirdiği ikinci vaka (33:11'den sonra).",
 33: "◇ Blokun en yoğun emir ayeti: dört IMPV + bir yasak, hepsi 2FP (11 kez). İki mef'ûl-i mutlak aynı ayette, ikisi de bitişik ve ikisini de mm2 yakalıyor: teberruce'l-câhiliyye (yasaklanan) · tathîren (istenen) — biri kaçınılacak biçim, biri erişilecek hâl. Kapanışta hitap 2FP'den 2MP'ye geçiyor ('ankumu / yutahhirakum', ehl-el-beyt): aynı ayette dişilden eril çoğula — iltifât alanı bunu şahıs geçişi olarak saymıyor. Esmâ evvel 'ilk câhiliye'nin sıfatı (e_el=0), son-üç dışında kaldı.",
 34: "◇ Eylem EV içinde: 33:33 'evlerinizde oturun' → 33:34 'evlerinizde okunanı anın' (بيت 3-4/5). Okunan iki şey: âyetler ve hikmet (حكم sûrede 2/2: 33:1 hakîm · 33:34 hikmet). Mühür latîf-habîr ÇİFT, cemâl — latîf sûrede ilk ve tek (لطف 1/1); habîr ikinci (33:2 tekil). ★★ allah z=2,33; ikinci eşik pas z=1,57 (yütlâ).",
 35: "◇ Bir sayım ayeti: ON sıfat, her biri ERİL-DİŞİL ÇİFT (20 terim). Kök ikilemesi alanı ÇİFTLERİ doğrudan veriyor: سلم, أمن, قنت, صدق (sadık + sadaka veren: aynı kök iki sıfat), صبر, خشع, صوم, حفظ, ذكر — dokuz kök, on çift. i'râb ACC 27: tamamı inne'nin ismi. Tüm liste tek bir yüklemde toplanıyor: 'Allah bunlar için mağfiret ve büyük ecir hazırladı' (a'adde üçüncü kez: 33:8 azap · 33:29 ecir · 33:35 mağfiret+ecir). 33:21'deki 'Allah'ı çok anmak' burada listenin son maddesi. Tarayıcı v4 ADAY verdi — çıpa değil. say alanı kesîr ve a'adde'yi yakalıyor, 'on çift' yapısını görmüyor.",
 36: "◇ Bir KARAR KURALI: Allah ve Resûl bir işe hükmedince mü'min erkek/kadın için 'seçme hakkı' (hıyera) yok. mü'min + mü'mine yine eril-dişil çift, 33:35'in dilinden devam. Karşı-dal: isyan → dalâlen mübînen (mm2 yakaladı). Esmâ mübîn sapıklığın sıfatı ve son-üç içinde: §4.3 YANLIŞ MÜHÜR (sûrede beşinci). مُؤْمِن yine insan.",
 37: "◇ Sûrenin en uzun ayeti (n=48, n z=3,78 → ★★★'ın kaynağı; hapaks وطر z=3,28 de eşikte — üç bağımsız ölçüt, biri sayılıyor: #15). Adlı aktör Zeyd (PN kişi; korpusta yalnız bu ayette — TAM SAYIM). Ayet 33:4'ün evlatlık kuralını bir OLAYDA uyguluyor: 'evlatlıklarının (ed'iyâ') eşleri' — دعو 33:4'teki ed'iyâ ile aynı lemma. İki karşıt fiil aynı cümlede: tuhfî (gizliyorsun) / mubdîh (açığa çıkaracak) — خفي/بدو. خشي ×2: insanlardan çekinmek / Allah'tan çekinmek daha lâyık. Beş lafız. Kapanış 'Allah'ın emri yerine gelmiştir' ve bir sonraki ayet aynı kalıpla kapanıyor (nakarat3). Tarayıcı v4 ADAY verdi — çıpa değil. say alanı zevc'i ÜÇ kez (eş anlamında) sayıyor.",
 38: "◇ 33:37'nin kapanış kalıbının ikizi: 'kâne emrullâhi mef'ûlâ' → 'kâne emrullâhi kaderan makdûrâ' (قدر ×2). Olay tek değil, bir YASA: 'Allah'ın önceki geçmişler hakkındaki sünneti' — nakarat3 7 kelimelik eşle 33:62'ye bağlıyor (sûrede ileride; henüz okunmadı). حرج ikinci kez: 33:37 mü'minlere güçlük olmasın · 33:38 Peygamber'e güçlük yok. Üç lafız, ★★ allah z=2,20.",
 39: "◇ 33:37'nin AYNASI: orada 'insanlardan çekiniyordun, Allah daha lâyık' · burada tebliğ edenler 'O'ndan çekinir, Allah'tan başka kimseden çekinmezler' (خشي sûrede 4/4: ikisi 33:37'de, ikisi burada; HASR). Kapanış 33:3'ün kalıbı: kefâ billâhi vekîlâ → kefâ billâhi hasîbâ (كفي üçüncü kez, nakarat3). Üç lafız 13 kelimede → ★★★'ın tek kaynağı allah z=4,09 (ölçek). Esmâ ehad 'hiç kimse' (e_el=0), hasîb temyiz (ilâhî, katalog-dışı ton).",
 40: "◇ Blok bir SOY cümlesiyle kapanıyor ve 33:4-5'e dönüyor: 33:4 'evlatlıklarınızı oğullarınız kılmadı' · 33:5 'babalarına nispet edin' · 33:40 'Muhammed sizin adamlarınızdan hiçbirinin BABASI değildir' (أبو 3/4). racül sûrede üç kez ve üçü de bu eksende: 33:4 (bir adamın göğsü) · 33:23 (sadık adamlar) · 33:40 (adamlarınızdan). Soy etiketi reddediliyor, yerine iki rol konuyor: Resûlullah ve hâtem en-nebiyyîn (ختم sûrede tek; korpusta hapaks değil). Muhammed adı korpusta 4 ayette (3:144, 33:40, 47:2, 48:29 — TAM SAYIM). Mühür alîm TEKİL (33:1'in alîm'i), geçerli.",
}
MEAL.update(MEAL4); M.update(M4)

MEAL5 = {
 41: "Ey iman edenler! Allah'ı çokça anın.",
 42: "Sabah akşam O'nu tesbih edin.",
 43: "Sizi karanlıklardan aydınlığa çıkarmak için size rahmet eden, melekleri de sizin için dua eden O'dur. O, mü'minlere karşı çok merhametlidir.",
 44: "O'na kavuşacakları gün onların sağlık dilekleri 'selâm'dır. Onlar için değerli bir mükâfat hazırlamıştır.",
 45: "Ey Peygamber! Biz seni bir şahit, bir müjdeci ve bir uyarıcı olarak gönderdik;",
 46: "Allah'ın izniyle O'na çağıran bir davetçi ve aydınlatan bir kandil olarak.",
 47: "Mü'minlere, kendileri için Allah'tan büyük bir lütuf olduğunu müjdele.",
 48: "Kâfirlere ve münafıklara boyun eğme; onların eziyetine aldırma ve Allah'a dayan. Vekil olarak Allah yeter.",
 49: "Ey iman edenler! Mü'min kadınlarla evlenip de onlara dokunmadan önce boşadığınızda, onlar üzerinde sayacağınız bir iddet hakkınız yoktur. Onlara faydalanacakları bir şey verin ve onları güzellikle salıverin.",
 50: "Ey Peygamber! Mehirlerini verdiğin eşlerini, Allah'ın sana ganimet olarak verdiklerinden sahip olduğun cariyeleri, seninle birlikte hicret eden amcanın kızlarını, halalarının kızlarını, dayının kızlarını, teyzelerinin kızlarını ve kendisini Peygamber'e hibe eden —Peygamber de onunla evlenmek isterse— mü'min bir kadını sana helâl kıldık. Bu, diğer mü'minlere değil yalnız sana mahsustur. Onlara eşleri ve sahip oldukları cariyeler hakkında neyi farz kıldığımızı biliyoruz. Bu, sana bir güçlük olmasın diyedir. Allah bağışlayandır, esirgeyendir.",
}
M5 = {
 41: "◇ 33:9'un açılışı (yâ eyyühe'llezîne âmenû + ذكر) ikinci kez (nakarat3). 'üzkürullâhe zikran kesîrâ' bir mef'ûl-i mutlak ama mm2 YAKALAMIYOR: fiil ile masdar arasına lafız giriyor — 33:10'dan sonra sûrede ikinci bitişik-olmayan vaka (aday 982). ذكر sûrede burada 7/7 ile tamamlanıyor; 'Allah'ı çok anmak' üçüncü kez (33:21 koşul · 33:35 liste maddesi · 33:41 emir). Yedi kelime, bir lafız → ★★ allah z=2,33 (ölçek).",
 42: "◇ Üç kelime: bir emir ve bir ZAMAN ÇİFTİ (bukre · asîl, sabah · akşamüstü). Lafız yok, zamir 'hu' 33:41'in lafzına dönüyor. Üç kökün üçü de sûrede tek. xref 48:9 — aynı üçlü; okunmadı.",
 43: "◇ Sûre 33'te OKUYUCU KARARIYLA İLK GERÇEK E SINIFI: lafız yok, Rab yok, özne 'huve' (33:41'in lafzı) ve kapanış 'kâne bi'l-mü'minîne rahîmâ' — rahîm ilâhî yüklem. Ama aynı ayette nûr ('karanlıklardan AYDINLIĞA') ve mü'min (insan) da esmâ lemması: son-üç = nûr · mü'min · rahîm, ve §4.3 bunu ÇİFT MÜHÜR, ton 'karma' sayıyor. Gerçekte tek ilâhî isim var: mühür geçerli ama 'çift' ve 'karma' etiketleri yanlış tokenlerden geliyor. Tek fiil iki özne: Allah ve melekleri 'size salât eder' (يصلي). ظلم/نور çoğul → tekil: zulumât (çoğul) · nûr (tekil). Tarayıcı v4 ADAY verdi — karanlık/ışık mecazı, olgu değil.",
 44: "◇ Lafızsız, Rab'sız, esmâlı (selâm, kerîm) ama ikisi de ilâhî değil: selâm bir selamlaşma, kerîm ecrin sıfatı. e_oto sınıfı E, e_el sınıfı 0 — ve §4.3 ÇİFT MÜHÜR sayıyor: sûrede tamamen yanlış tokenlerden oluşan ikinci çift mühür (33:17'den sonra). a'adde dördüncü kez (33:8 azap · 33:29 ecir · 33:35 mağfiret+ecir · 33:44 kerîm ecir); dördünün dördünde say alanı işaret koyuyor. لقي 'O'na kavuşacakları gün' — sûrede tek.",
 45: "◇ Sûrede üçüncü kez 'yâ eyyühe'n-nebî' (33:1 · 33:28 · 33:45; 33:50'de dördüncü). Bir ROL LİSTESİ başlıyor ve 33:46'da sürüyor: şâhid · mübeşşir · nezîr · dâ'î · sirâc münîr — beş rol, iki ayete bölünmüş. Konuşan 1P (innâ erselnâke); iltifât alanı 33:45 ve 33:46'yı işaretliyor (1P → 33:46'da 'Allah'ın izniyle' 3MS). xref 48:8 aynı üçlü — okunmadı.",
 46: "◇ Listenin son iki rolü: dâ'î (çağıran) ve sirâc münîr (aydınlatan kandil). نور sûrede ikinci kez ve iki ayet arayla: 33:43 'karanlıklardan NURA çıkarmak' (Allah'ın işi) · 33:46 'aydınlatan kandil' (Peygamber'in rolü). Işık bir fiilden bir nesneye geçiyor. Mecaz, olgu değil (🜁 yok). Altı kelime bir lafız → ★★ allah z=2,80.",
 47: "◇ Müjde emri (بشر 2/2: 33:45 mübeşşir rolü · 33:47 'müjdele' emri) — rol tanımlandı, hemen görevi veriliyor. Esmâ iki token, ikisi de ilâhî değil: mü'minler ve kebîr (fadlan kebîran, lütfun sıfatı) → §4.3 YANLIŞ MÜHÜR (sûrede yedinci).",
 48: "◇ Sûrenin açılış üçlüsünün BİRLEŞİK TEKRARI: 33:1 'kâfirlere ve münafıklara boyun eğme' (nakarat3, 4 kelime) + 33:3 'Allah'a dayan; vekil olarak Allah yeter' (nakarat3, 6 kelime — ayetin tamamı). 33:1-3'ün üç ayeti burada tek ayette. Arada bir yeni emir: 'eziyetlerine aldırma' (ودع sûrede tek). وكل 4/4 ve كفي 4/4 burada tamamlanıyor. Mühür vekîl, temyiz, geçerli (ton katalog-dışı).",
 49: "◇ Sûrede say alanının ilk açık DOĞRU pozitifi: 'iddetun ta'teddûnehâ' — 'sayacağınız bir bekleme süresi'; عدد kökü burada gerçekten SAYMA. Aynı kök a'adde'de (hazırladı) dört kez yanlış pozitif vermişti: kök aynı, isabet anlam düzeyinde ayrışıyor. Kapanış 33:28'in formülü: 'faydalandırın ve güzellikle salıverin' (nakarat3, 4 kelime; mm2 serâhan yakaladı). Karşılık durumu 'dokunmadan önce' — مسس sûrede tek. xref 2:237 — okunmadı.",
 50: "◇ Sûrenin en uzun ayeti (n=61, n z=5,16 → ★★★ tek kaynak; 33:37'nin 48'ini geçiyor). İçinde tam bir 2×2 AKRABALIK TABLOSU: baba tarafı (amca · hala) × anne tarafı (dayı · teyze), her hücrede 'kızları' — عمم ×2, خول ×2, بني ×4: dört hücre, eksiksiz. Ardından bir KÜME İSTİSNASI: 'hâlisaten leke min dûni'l-mü'minîn' — yalnız sana, mü'minlere değil. Adsız aktör imrae (hibe eden kadın). حرج sûrede 3/3 ile tamamlanıyor (33:37 mü'minlere · 33:38 Peygamber'e · 33:50 sana güçlük olmasın). Mühür gafûr-rahîm ÇİFT (33:5, 33:24 ile üçüncü). say alanı zevc'i iki kez sayıyor. Tarayıcı v4 ADAY verdi — çıpa değil.",
}
MEAL.update(MEAL5); M.update(M5)

MEAL6 = {
 51: "Onlardan dilediğini geri bırakır, dilediğini yanına alırsın; ayırdıklarından dilediğini yeniden istemende de sana bir günah yoktur. Bu, onların gözlerinin aydın olmasına, üzülmemelerine ve hepsinin kendilerine verdiğine razı olmasına daha uygundur. Allah kalplerinizde olanı bilir. Allah bilendir, halîmdir.",
 52: "Bundan sonra başka kadınlar —güzellikleri hoşuna gitse bile— sana helâl değildir; onları başka eşlerle değiştirmen de helâl değildir; sahip olduğun cariyeler müstesna. Allah her şeyi gözetendir.",
 53: "Ey iman edenler! Peygamber'in evlerine —yemeğe çağrılmanız hâli dışında— izin verilmeden, yemeğin pişmesini beklemeden girmeyin. Ama çağrıldığınızda girin; yemeği yiyince de dağılın, sohbete dalmayın. Bu, Peygamber'i incitiyor, o da sizden utanıyor; Allah ise haktan utanmaz. Onlardan bir şey istediğinizde perde arkasından isteyin. Bu, hem sizin kalpleriniz hem onların kalpleri için daha temizdir. Allah'ın Resûlünü incitmeniz ve ondan sonra eşleriyle hiçbir zaman evlenmeniz size yaraşmaz. Bu, Allah katında büyük bir günahtır.",
 54: "Bir şeyi açığa vursanız da gizleseniz de, Allah her şeyi bilendir.",
 55: "Peygamber'in hanımlarına babaları, oğulları, erkek kardeşleri, erkek kardeşlerinin oğulları, kız kardeşlerinin oğulları, (mü'min) kadınlar ve sahip oldukları köleler konusunda bir günah yoktur. Allah'tan sakının; Allah her şeye şahittir.",
 56: "Şüphesiz Allah ve melekleri Peygamber'e salât ederler. Ey iman edenler! Siz de ona salât edin ve tam bir teslimiyetle selâm verin.",
 57: "Allah'ı ve Resûlünü incitenleri Allah dünyada da âhirette de lânetlemiş ve onlara alçaltıcı bir azap hazırlamıştır.",
 58: "Mü'min erkekleri ve mü'min kadınları, yapmadıkları bir şeyle incitenler, bir iftira ve apaçık bir günah yüklenmişlerdir.",
 59: "Ey Peygamber! Hanımlarına, kızlarına ve mü'minlerin kadınlarına söyle: Dış örtülerini üzerlerine alsınlar. Bu, onların tanınıp incitilmemelerine daha uygundur. Allah bağışlayandır, esirgeyendir.",
 60: "Andolsun, münafıklar, kalplerinde hastalık olanlar ve şehirde kötü haber yayanlar vazgeçmezlerse, seni onların üzerine salarız; sonra orada senin yanında pek az kalabilirler.",
}
M6 = {
 51: "◇ İki fiil, iki yön: tercî (geri bırakırsın) · tü'vî (yanına alırsın) — ve üçüncü dal: ayırdığını yeniden istemek. Seçim Peygamber'e bırakılıyor; ölçüt eşlerin gönlü: 'gözleri aydın olsun, üzülmesinler, hepsi razı olsun' (قرر 2/2: 33:33'te 'evlerinizde OTURUN', burada göz AYDINLIĞI — aynı kök, kök glossu ikisini de taşıyor). 'zâlike ednâ en' kalıbı 33:59'da tekrar (nakarat3). Mühür alîm-halîm ÇİFT; halîm sûrede ilk ve tek (حلم 1/1). Tarayıcı v4 ADAY verdi — çıpa değil.",
 52: "◇ 33:50'nin KAPANIŞI: orada 'ahlelnâ leke' (sana HELÂL KILDIK) · burada 'lâ yahillu leke' (sana HELÂL DEĞİL) — حلل sûrede 2/2 ve iki kez ters yönde. İzin kümesi 33:50'de tanımlanmış, 33:52'de kapanıyor; tek istisna ikisinde de aynı: 'mâ meleket yemînuk' (nakarat3). Mühür rakîb TEKİL, geçerli (katalog-dışı ton). 'alâ kulli şey'in' formülü sûrede burada üçüncü kez (33:27 kadîr · 33:40 alîm · 33:52 rakîb). Tarayıcı v4 ADAY verdi — çıpa değil.",
 53: "◇ Sûrenin en uzun ayeti (n=69, n z=6,01 — 33:50'nin 61'ini geçiyor; ★★★ tek kaynak). Bir ADAB PROTOKOLÜ, adım adım: izinsiz girmeyin → çağrılınca girin → yiyince dağılın → sohbete dalmayın. Gerekçe iki yüzlü: Peygamber sizden UTANIYOR, Allah haktan UTANMAZ (istihyâ ×2) — kök glossu حيي 'diri olma, hayat' ve bu kullanımı taşımıyor (aday 987'ye eklendi; korpusta istihyâ 10). Perde (حجب sûrede tek) ve temizlik: 'kalpleriniz ve onların kalpleri' (قلب ×2, sûrede 8-9/11). Üç lafız, eziyet iki kez (أذي). Tarayıcı v4 ADAY verdi — çıpa değil.",
 54: "◇ 33:37'nin kalıbının genel hâli: orada 'içinde gizliyordun, Allah açığa çıkaracak' (tek kişi, tek olay) · burada 'açığa vursanız da gizleseniz de' (herkes, her şey). خفي 2/2 ve بدو 3/3 burada tamamlanıyor. 'bi-kulli şey'in alîmâ' — 33:40'ın kapanışı aynen (nakarat3).",
 55: "◇ 33:53'ün perde kuralının İSTİSNA KÜMESİ: yedi kategori — babalar · oğullar · erkek kardeşler · erkek kardeşlerin oğulları · kız kardeşlerin oğulları · kadınları · sahip oldukları. NEG 7: her kategori 'lâ' ile. 33:50'nin 2×2 tablosuyla karşılaştırılınca: orada amca/hala/dayı/teyze (evlenilebilenler), burada baba/oğul/kardeş/yeğen (mahremler) — iki liste birbirini dışlıyor. Mühür şehîd TEKİL, geçerli. كلل 6/6 ve شيأ 9/9 burada tamamlanıyor: 'her şey' formülü sûrede beşinci ve son kez (27 · 40 · 52 · 54 · 55).",
 56: "◇ 33:43'ün AYNASI: 33:43 'O ve melekleri SİZE salât eder' · 33:56 'Allah ve melekleri PEYGAMBER'E salât eder' — aynı fiil, aynı iki özne, nesne değişiyor (صلو 2-4/4). Ardından emir: 'siz de salât edin, teslîmen selâm verin' (mm2 yakaladı, bitişik; سلم 5-6/6 burada tamamlanıyor). Yâ eyyühe'llezîne âmenû ayetin ORTASINDA: sûrenin ilk 56 ayetinde bu kalıbın ayet başında olmadığı tek yer (33:13'teki orta-ayet nidâ bir alıntının içinde, başka kalıp).",
 57: "◇ İki paralel 'ellezîne yü'zûne' cümlesinin ilki: Allah'ı ve Resûlünü incitenler → lânet (dünya ve âhiret) + alçaltıcı azap. a'adde beşinci kez (say alanı beşinde de işaret koyuyor). Esmâ âhir yine âhiretin sıfatı ve son-üç içinde → §4.3 YANLIŞ MÜHÜR (sûrede sekizinci). لعن sûrede ilk kez.",
 58: "◇ İkinci 'ellezîne yü'zûne': mü'min erkek ve kadınları incitenler → bühtan ve apaçık günah. 33:57'de karşılık Allah'tan (lânet, azap), 33:58'de karşılık failin YÜKLENDİĞİ şey (ihtemelû) — ilkinde fail edilgen, ikincisinde yük taşıyan. mü'min + mü'mine eril-dişil çift yine. Esmâ mü'min (insan) ve mübîn (günahın sıfatı): lafızsız ayette e_oto sınıf E → e_el sınıf 0; §4.3 YANLIŞ MÜHÜR (dokuzuncu). أذي sûrede 5/7.",
 59: "◇ Emir üç halkaya: eşler · kızlar · mü'minlerin kadınları — 33:28'deki 'eşlerine de ki' kalıbı genişliyor (nakarat3). دنو ×2: yüdnîne (örtüyü yaklaştırsınlar) · ednâ (daha uygun) — aynı kök, fiil ve ölçü. 'zâlike ednâ en' 33:51'in kalıbı (nakarat3). İki edilgen yan yana: yu'rafne · yu'zeyne (tanınsınlar · incitilmesinler) → ★ pas z=1,95. أذي 6/7. Mühür gafûr-rahîm ÇİFT (sûrede dördüncü: 33:5 · 33:24 · 33:50 · 33:59).",
 60: "◇ 33:12'nin grubu geri dönüyor ve genişliyor: münafıklar + kalplerinde hastalık olanlar (nakarat3, 5 kelime) + ÜÇÜNCÜ grup: mürcifûn (şehirde kötü haber yayanlar, رجف sûrede tek). Şehrin adı: el-MEDÎNE (PN, yer) — sûrede şehir iki kez adlandırılıyor ve iki ayrı adla: 33:13 Yesrib (münafıkların ağzında) · 33:60 el-Medîne (Allah'ın sözünde). Kapanış qalîlâ — sûrede 4/4 ile tamamlanıyor (16 · 18 · 20 · 60). Lafız yok, konuşan 1P (le-nuğriyenneke).",
}
MEAL.update(MEAL6); M.update(M6)

MEAL7 = {
 61: "Lânetlenmiş olarak; nerede ele geçirilseler yakalanırlar ve öldürülüp giderler.",
 62: "Bu, Allah'ın daha önce gelip geçenler hakkındaki yasasıdır. Allah'ın yasasında hiçbir değişiklik bulamazsın.",
 63: "İnsanlar sana kıyamet saatini soruyorlar. De ki: 'Onun bilgisi yalnız Allah katındadır.' Ne bilirsin, belki de o saat yakındır.",
 64: "Şüphesiz Allah kâfirleri lânetlemiş ve onlara çılgın bir ateş hazırlamıştır.",
 65: "Orada ebedî kalacaklardır; ne bir dost ne bir yardımcı bulacaklardır.",
 66: "Yüzlerinin ateşte evrilip çevrileceği gün, 'Keşke Allah'a itaat etseydik, keşke Peygamber'e itaat etseydik!' derler.",
 67: "Ve derler ki: 'Rabbimiz! Biz efendilerimize ve büyüklerimize itaat ettik, onlar da bizi yoldan saptırdılar.'",
 68: "'Rabbimiz! Onlara azabın iki katını ver ve onları büyük bir lânetle lânetle.'",
 69: "Ey iman edenler! Mûsâ'ya eziyet edenler gibi olmayın; Allah onu onların söylediklerinden temize çıkardı. O, Allah katında itibarlı idi.",
 70: "Ey iman edenler! Allah'tan sakının ve doğru söz söyleyin.",
}
M7 = {
 61: "◇ Altı kelime, üç fiil, ÜÇÜ DE EDİLGEN (sükıfû · ühızû · kuttilû; pas z=5,38 → ★★★ tek kaynak) — 33:11'deki 'iki fiil iki edilgen' kalıbının üçlüsü; fail yine adlandırılmıyor. Ardından mef'ûl-i mutlak tektîlen (mm2 yakaladı, bitişik). قتل sûrede 6/6 ile tamamlanıyor. 33:60'ın cümlesinin devamı: ayet 'mel'ûnîne' (hâl) ile başlıyor, bağımsız değil.",
 62: "◇ 33:38'in formülü aynen (nakarat3, 7 kelime) ve bu kez bir ikinci cümleyle: 'Allah'ın sünnetinde değişme bulamazsın'. Fâsıla tebdîlâ — sûrede ikinci kez ve iki ayrı özneyle: 33:23 sadıklar 'hiç değiştirmediler' (beddelû tebdîlâ) · 33:62 Allah'ın yasasında değişme yok (بدل 4/4 burada tamamlanıyor). esit2 bu ayeti 48:23 ile BENZER kademede eşliyor (oran 0,854) — sûre 48 okunmadı. سنن 3/3 tamamlanıyor.",
 63: "◇ Sûrenin SORGU ipliğinin son halkası: سأل 7/7 burada tamamlanıyor — 33:8 (Allah sâdıklara sorar) · 33:14 (fitne istenir) · 33:15 (ahit sorulur) · 33:20 (haberleri sorarlar) · 33:53 ×2 (perde arkasından isteyin) · 33:63 (insanlar saati sorar). İlki Allah'ın sorusu, sonuncusu insanların Allah'a yönelttiği soru. Cevap bir sınır: 'bilgisi Allah katında' — علم 9/9 tamamlanıyor. Esmâ karîb saatin sıfatı (e_el=0) ama son-üç içinde → §4.3 YANLIŞ MÜHÜR.",
 64: "◇ Lânet ikinci kez Allah'ın fiili (33:57 · 33:64); a'adde altıncı ve son kez (عدد 8/8 tamamlanıyor): azap · ecir · mağfiret+ecir · kerîm ecir · alçaltıcı azap · saîr. Altı 'hazırladı'nın üçü karşılık-iyi, üçü karşılık-kötü. say alanı altısında da işaret koydu; aynı kökün tek doğru sayı kullanımı 33:49'du. كفر 5/5 tamamlanıyor. Yedi kelime bir lafız → ★★ allah z=2,33.",
 65: "◇ 33:17'nin kapanış formülü (lâ yecidûne ... veliyyen ve lâ nasîrâ; nakarat3) ve 33:17'deki gibi ÇİFT YANLIŞ MÜHÜR: velî + nasîr olumsuzlanan başkalarının sıfatı. Lafızsız ayette e_oto sınıfı E, e_el sınıfı 0. ولي 7/7 tamamlanıyor — kökün yedi geçişi üç anlama dağılıyor: dost/velî, 'daha yakın' (evlâ, 33:6 ×2), 'arka çevirmek' (33:15). أبد 2/2: 33:53 'asla evlenmeyin' · 33:65 'ebedî kalırlar'.",
 66: "◇ Yüzler ateşte ÇEVRİLİYOR (tukallebu): قلب sûrede 11/11 ile tamamlanıyor — on kez kalp (organ, niyet, korku, hastalık, temizlik, bilgi), sonuncusu fiil: çevirmek. Kök glossu 'çevirme; kalp' ikisini de taşıyor. Ama ateş (nâr) morfolojide نور kökünde ve kök glossu 'nûr, ışık' — envanterde nâr 145, nûr 43: gloss baskın lemmanın TERSİNİ gösteriyor (aday 987'ye eklendi). 'Keşke itaat etseydik' ×2 (طوع). Fâsıla er-rasûlâ: uzatma elifi (33:10 ez-zunûnâ ile ikinci).",
 67: "◇ Sûrenin RAB'ı 33:2'den beri İLK KEZ ve konuşan cehennemlikler: 'Rabbenâ'. Rab sûrede 3 kez (33:2 · 33:67 · 33:68): biri Peygamber'e vahyin kaynağı, ikisi mahkûmların yakarışı. Sınıf R (lafız yok, Rab var). İtaat ipliği tersine dönüyor: 'efendilerimize ve büyüklerimize itaat ettik' (طوع). Son kelime es-sebîlâ — 33:4'ün es-sebîl'i elifsizdi (sûrenin tek A-dışı fâsılası); burada aynı lemma uzatma elifiyle, tek kök ikiliği ضلل 3/3 'saptırdılar yolu'. 33:4'te Allah 'yola iletir', 33:67'de büyükler 'yoldan saptırdı'.",
 68: "◇ 'Onlara azabın İKİ KATINI ver' (di'fayn) — 33:30'daki 'azabı iki kat artırılır'ın aynı sözcüğü (ضعف 3/3 tamamlanıyor). say alanı üçüncü kez YAKALAMIYOR (33:30 · 33:31 · 33:68): sûredeki üç gerçek ikil sayı ifadesinin üçü de işaretsiz. mm2 la'nen kebîran yakaladı; لعن 5/5 tamamlanıyor. Esmâ kebîr lânetin sıfatı → §4.3 YANLIŞ MÜHÜR. Rab ikinci kez, sınıf R.",
 69: "◇ Adlı aktör Mûsâ — 33:7'deki beş peygamberden biri, sûrede ikinci anılışı. EZİYET ipliği burada kapanıyor: أذي 7/7, son geçiş bir tarihsel ÖRNEK: Mûsâ'yı incitenler gibi olmayın (33:57-58'in kuralının öncülü). Allah onu 'temize çıkardı' (برأ sûrede tek). وجه 2/2 ters yönde: 33:66 yüzleri ateşte çevrilenler · 33:69 Allah katında 'vecîh' (yüzü olan, itibarlı).",
 70: "◇ İki emir: sakının · doğru söz söyleyin (kavlen sedîdâ; mm2 yakaladı). قول 21/21 burada tamamlanıyor ve sûre sözü iki nitelikle bağlıyor: 33:32 kavlen ma'rûfâ (uygun söz) · 33:70 kavlen sedîdâ (doğru söz); arada 33:4 'ağızlarınızdaki söz'. وقي 5/5 tamamlanıyor: 33:1 'ittaki'llâh' ile açılan sakınma emri 33:70'te aynı fiille. أيي 13/13: 'yâ eyyühe' nidâsı sûrede burada son kez.",
}
MEAL.update(MEAL7); M.update(M7)

MEAL8 = {
 71: "Ki Allah işlerinizi düzeltsin ve günahlarınızı bağışlasın. Kim Allah'a ve Resûlüne itaat ederse, büyük bir başarıya ulaşmıştır.",
 72: "Biz emaneti göklere, yere ve dağlara sunduk; onu yüklenmekten kaçındılar ve ondan korktular. Onu insan yüklendi. Şüphesiz o çok zalim, çok cahildir.",
 73: "Ki Allah münafık erkeklere ve münafık kadınlara, müşrik erkeklere ve müşrik kadınlara azap etsin; mü'min erkeklerin ve mü'min kadınların tevbesini kabul etsin. Allah bağışlayandır, esirgeyendir.",
}
M8 = {
 71: "◇ 33:70'in iki emrinin karşılığı iki fiil: işleri düzeltmek (صلح 2/2) ve günahları bağışlamak. İtaat ipliği burada KAPANIYOR: طوع 7/7 — 33:1 'kâfirlere boyun eğme' ile açılmıştı, 33:71 'Allah'a ve Resûlüne itaat eden' ile bitiyor; arada cehennemliklerin 'keşke itaat etseydik' ve 'efendilerimize itaat ettik'i (33:66-67). fevzen azîmâ (mm2 yakaladı). رسل 17/17, عمل 5/5, عظم 4/4 tamamlanıyor. Son kelime azîm yine esmâ listesinde yok (katalogda denge).",
 72: "◇ Sûrenin tek kozmik sahnesi ve LAFIZSIZ, RAB'SIZ, ESMÂSIZ (sınıf 0): konuşan 1P (arâdnâ). Üç büyük varlık — gökler, yer, dağlar (سمو ve جبل sûrede tek, أرض 3/3) — emaneti yüklenmekten kaçınıyor ve korkuyor; tek bir varlık yükleniyor: insan (أنس 4/4). حمل ×2 (yüklenmek) ve 33:58'deki 'bühtanı yüklendiler' (ihtemelû) ile kök üçlüsü tamamlanıyor (3/3). Emanet أمن kökünden: iman ve mü'min ile AYNI KÖK — أمن 29/31 burada; sûrede 31 geçişin 30'u iman/mü'min, biri emanet. Kapanış iki yoğun sıfat: zalûm (ظلم 2/2: 33:43 karanlıklar · 33:72 çok zalim) · cehûl (جهل 2/2: 33:33 ilk câhiliye · 33:72 çok cahil). 🜁 kademe L0, olgu EVET (gök, yer, dağ adlandırılıyor; fiziksel iddia yok) — çıpa değil; tarayıcı aday vermedi.",
 73: "◇ Sûrenin son ayeti bir amaç lâmıyla açılıyor ve 33:24'ün cümlesini genişletiyor: 33:24 'Allah münafıklara dilerse azap etsin ya da tevbelerini kabul etsin' · 33:73 'münafık erkek VE KADINLARA, müşrik erkek VE KADINLARA azap etsin; mü'min erkek VE KADINLARIN tevbesini kabul etsin'. Şart kalkıyor, gruplar ayrılıyor ve üç ERİL-DİŞİL ÇİFT oluyor (33:35'in dili). توب 2/2: 33:24'te münafıklar için ihtimal, 33:73'te mü'minler için gerçekleşme. Üç lafız (★★★ allah z=3,47); lafız sûrede burada 90/90 — sûrenin toplam lafız sayısı 90 (TAM SAYIM). Mühür gafûr-rahîm ÇİFT, sûrede beşinci (33:5 · 24 · 50 · 59 · 73); sûre 33:1'de alîm-hakîm ile açılmış, rahîm ile kapanıyor. شرك 2/2 ve نفق 7/7 tamamlanıyor; أمن 31/31 son iki geçişi mü'min erkek ve kadın.",
}
MEAL.update(MEAL8); M.update(M8)
