# -*- coding: utf-8 -*-
"""ahzab_metin_1.py — sûre 33 (Ahzâb) meal ve matematikçi merceği, ayet 1-20.
Arapça sabit YOK: kökler yalnız korpus kök biçimiyle anılır, kelime biçimleri Latin harfle."""
MEAL = {
 1: "Ey Peygamber! Allah'tan sakın; kâfirlere ve münafıklara boyun eğme. Şüphesiz Allah bilendir, hikmet sahibidir.",
 2: "Rabbinden sana vahyolunana uy. Şüphesiz Allah yaptıklarınızdan haberdardır.",
 3: "Allah'a dayan; vekil olarak Allah yeter.",
 4: "Allah bir adamın göğsünde iki kalp yaratmadı. Zıhar yaptığınız eşlerinizi analarınız kılmadı, evlatlıklarınızı da oğullarınız kılmadı. Bu, sizin ağızlarınızdaki sözünüzdür. Allah ise gerçeği söyler ve O yola iletir.",
 5: "Onları babalarına nispet ederek çağırın; bu, Allah katında daha adildir. Babalarını bilmiyorsanız, onlar dinde kardeşleriniz ve dostlarınızdır. Yanıldığınız şeyde size bir günah yok; ama kalplerinizin kastettiğinde var. Allah bağışlayandır, esirgeyendir.",
 6: "Peygamber mü'minlere kendilerinden daha yakındır; eşleri onların analarıdır. Akrabalar, Allah'ın Kitabı'nda birbirlerine, mü'minlerden ve muhacirlerden daha yakındır — dostlarınıza bir iyilik yapmanız müstesna. Bu, Kitap'ta yazılmıştır.",
 7: "Hani peygamberlerden ahitlerini almıştık: senden, Nûh'tan, İbrâhîm'den, Mûsâ'dan ve Meryem oğlu Îsâ'dan. Onlardan ağır bir ahit almıştık —",
 8: "— doğrulara doğruluklarını sorsun diye. Kâfirlere de acıklı bir azap hazırladı.",
 9: "Ey iman edenler! Allah'ın üzerinizdeki nimetini anın: hani size ordular gelmişti; biz de üzerlerine bir rüzgâr ve sizin görmediğiniz ordular göndermiştik. Allah yaptıklarınızı görendir.",
 10: "Hani üstünüzden ve aşağınızdan size gelmişlerdi; hani gözler kaymış, yürekler gırtlaklara dayanmıştı ve Allah hakkında türlü zanlarda bulunuyordunuz.",
}
M = {
 1: "◇ Sûre nidâ ile açılıyor ve muhatap adıyla değil KONUMUYLA çağrılıyor (yâ eyyühe'n-nebiyy). Bir emir, bir yasak, sonra çift mühür (alîm-hakîm). ikili alanı bu ayette BEŞ köklü çift veriyor — blokun en yoğunu; ama beşinin ikisi kalıp: mühür formülü (kâne-Allah, 6 ayet) ve nidâ formülü (eyy-nebî, 5 ayet). Esmâ kaydı: a=1 · e_el=1 · mühür ÇİFT, ton cemâl.",
 2: "◇ Blokun TEK Rab'i ve tek edilgeni aynı kelimede değil ama aynı cümlede: 'sana vahyolunan' (edilgen) + 'Rabbinden'. Rab özel hitap (2MS) içinde, lafız ise genel hitap (2MP) içinde: 'Rabbin' sana, 'Allah' hepinizin yaptığına. Eski esma_k MÜHÜRSÜZ diyor (tek esmâ, çift yok); ön-kaydın §4.3 tanımıyla MÜHÜR — aday 961'in 'tekil gerçek esmâ' türü.",
 3: "◇ Altı kelime, iki lafız, iki وكل: ayet kendi içinde kapalı bir halka — tevekkül et → vekil olarak yeter. ★★★'ın TEK kaynağı allah z=6,14, yani 2/6 lafız yoğunluğu; kısa ayette oran büyür (içerik değil ölçek). nakarat3 'tam' türünde tüm ayeti 33:48 ile eşliyor (6 kelime / 2 ayet) — sûre bu formülü 45 ayet sonra aynen tekrarlıyor. Esmâ vekîl katalogda TON TAŞIMIYOR (aşağıda borç).",
 4: "◇ ÜÇ olumsuz kılma (mâ ce'ale ×3), aynı sözdizimi, üç ayrı alan: beden (bir göğüste iki kalp) · evlilik (zıhar edilen eş anne değil) · soy (evlatlık oğul değil). Matematikçi okuması: üç yeniden-etiketleme reddi — bir nesneye verilen AD onun sınıfını değiştirmiyor; kapanış bunu adıyla söylüyor: 'bu sizin ağızlarınızdaki sözünüz'. İlk önerme bedensel bir olgu (🜁 kademe L1, olgu EVET: sayı + organ + yer; mekanizma yok), ama ayet onu olgu olarak değil ANALOJİNİN TABANI olarak kullanıyor. Tarayıcı v4 aday vermedi — doğru negatif (L4 değil). ★★★: hapaks جوف (z=3,28); ayrıca n z=1,65 ve sûrenin TEK kafiye kırığı — üç bağımsız işaret, formül yalnız birini sayıyor (borç #15). Fâsıla ile ilgili TAM SAYIM aşağıda.",
 5: "◇ 33:4'ün soy yasağının pozitif karşılığı: 'babalarına nispet edin'. Baba bilinmiyorsa YENİ sınıf veriliyor: dinde kardeş ve mevlâ. Yani 33:4-5 birlikte bir sınıflama kuralı: soy etiketi yalnız soya verilir; soy bilinmezse başka bir ilişki adı kullanılır. Hata/kasıt ayrımı ('yanıldığınız' / 'kalplerinizin kastettiği') — sorumluluk niyete bağlanıyor. قلب ikinci kez (33:4 bedensel kalp · 33:5 niyet eden kalp · 33:10 gırtlağa dayanan kalp): üç ayette üç ayrı işlev.",
 6: "◇ 33:4'ün simetrik karşıtı: orada 'eşlerinizi ANALARINIZ kılmadı', burada Peygamber'in 'eşleri ONLARIN ANALARIDIR'. أمم kökü iki ayette iki kez ve iki kez ters yönde: aynı etiket bir yerde reddediliyor, bir yerde veriliyor. Fark etiketi kimin koyduğu: 33:4'te 'ağızlarınızdaki söz', 33:6'da 'Kitap'ta yazılmış'. Esmâ üç token (mü'min ×2, velî) ve ÜÇÜ DE ilâhî değil — mü'minler ve dostlar; e_oto=1, e_el=0. Sınama kümesine 32:4/32:18 ile aynı iki lemma ekleniyor.",
 7: "◇ Lafız YOK, Rab YOK, esmâ YOK — ama fiil 1P (almıştık): konuşan açık. Beş adlı peygamber ve ADSIZ bir altıncı: 'senden' (2MS) — muhatap adlı listenin başında ama adsız. mîsâkan galîzan: xref 4:21 ve 4:154 — aynı ifade korpusta üç ayrı ilişkiye veriliyor (evlilik ahdi · İsrâiloğulları · peygamberler); sûre 4 okunmadığı için bağ DOĞRULANMADI, yalnız kaydedildi.",
 8: "◇ Amaç cümlesi: ahit alınması bir sorgunun ÖN KOŞULU (doğrulara doğruluklarını sormak). صدق ×2 aynı cümlede (sâdıkîn / sıdk) — ölçen ve ölçülen aynı kök. say alanı a'adde fiilini sayı işareti diye yakalıyor: عدد kökü ama anlam 'hazırlamak' — yanlış pozitif (borç #13 ailesi).",
 9: "◇ Olay anlatısı başlıyor ve ilk anılan şey NİMET: 'anın'. İki ordu karşılaştırılıyor: size gelen ordular (جند ×2) ve sizin görmediğiniz ordular — aynı kelime, biri görülen biri görülmeyen. Rüzgâr: روح kökü (aday 946 onarımı burada doğru eşledi). 🜁 kademe L0, olgu evet (rüzgâr adlandırılıyor, başka iddia yok). Tarayıcı v4 bu ayeti G_bakış ile ADAY VERDİ ('görmediğiniz') — çıpa değil: kesinlik 0/1. Eski esma_k mühürsüz, §4.3 ile mühür (tekil basîr).",
 10: "◇ Kuşatma iki eksenle çiziliyor: üst/alt (fevk / esfel) ve dış/iç — dışarıda ordular geliyor, içeride gözler kayıyor, yürekler gırtlağa çıkıyor, zanlar çoğalıyor. Beden hareketi DİKEY: yürek aşağıdan yukarı. ظنن ×2 (fiil + aynı kökten belirli çoğul isim, ACC) — biçim olarak mef'ûl-i mutlak, ama mm2 YAKALAMIYOR: araya lafız giriyor, mm2 bitişiklik istiyor (27:58'deki bilinen negatifin ikinci vakası; araç açığı, metin hakkında bilgi değil — aday 924). Fâsıla 'ez-zunûnâ': sonda uzatma elifi.",
}
MEAL2 = {
 11: "Orada mü'minler imtihan edildi ve şiddetli bir sarsıntıyla sarsıldılar.",
 12: "Hani münafıklar ve kalplerinde hastalık olanlar, 'Allah ve Resûlü bize aldatmacadan başka bir şey vaat etmedi' diyorlardı.",
 13: "Hani onlardan bir grup, 'Ey Yesrib halkı! Sizin için durulacak yer yok, geri dönün' demişti. Onlardan bir kısmı da 'Evlerimiz korunmasız' diyerek Peygamber'den izin istiyordu; oysa evleri korunmasız değildi. Onlar yalnızca kaçmak istiyorlardı.",
 14: "Eğer (şehrin) çevresinden üzerlerine girilse, sonra kendilerinden fitne istenseydi, onu hemen yaparlardı ve bunda pek az dururlardı.",
 15: "Oysa daha önce arkalarını dönüp kaçmayacaklarına dair Allah'a ahit vermişlerdi. Allah'a verilen ahit sorulacaktır.",
 16: "De ki: 'Ölümden ya da öldürülmekten kaçıyorsanız, kaçmak size fayda vermez; o zaman da ancak az bir süre yararlandırılırsınız.'",
 17: "De ki: 'Allah size bir kötülük dilerse ya da size bir rahmet dilerse, sizi Allah'tan kim koruyabilir?' Kendileri için Allah'tan başka ne bir dost ne bir yardımcı bulurlar.",
 18: "Allah içinizden (savaştan) alıkoyanları ve kardeşlerine 'Bize gelin' diyenleri bilir. Onlar savaşa pek az gelirler.",
 19: "Size karşı cimridirler. Korku gelince, ölüm baygınlığı geçiren kimse gibi gözleri dönerek sana baktıklarını görürsün. Korku gidince de mala düşkünlükle sizi keskin dillerle incitirler. Onlar iman etmemişlerdir; Allah da amellerini boşa çıkarmıştır. Bu, Allah'a kolaydır.",
 20: "Ahzâb'ın gitmediğini sanıyorlar. Ahzâb yeniden gelse, bedevîler arasında çölde olup sizin haberlerinizi uzaktan sormayı isterler. Aranızda olsalardı da pek az savaşırlardı.",
}
M2 = {
 11: "◇ Altı kelime, iki fiil, ikisi de EDİLGEN (pas z=5,38 → ★★★'ın tek kaynağı): imtihan eden ve sarsan adlandırılmıyor. zülzilû zilzâlen — mm2 BURADA YAKALIYOR (fiil ve masdar bitişik). 33:10 ile yan yana: iki ardışık ayet, iki mef'ûl-i mutlak, alan birini görüyor birini görmüyor — fark metinde değil bitişiklik koşulunda. بلو kökünün glossu 'eskiyip yıpranma', ama burada ve kökün baskın lemmalarında anlam SINAMA (aşağıda borç). Esmâ mü'min yine insan: e_oto=1 → sınıf E, e_el=0 → sınıf 0; §4.3 son-üç tanımı bunu MÜHÜR sayıyor.",
 12: "◇ 33:1'in yasak muhataplarından münafıklar burada konuşuyor; bir grup ekleniyor: 'kalplerinde hastalık olanlar' (قلب dördüncü kez). Söz HASR kalıbında (mâ ... illâ): vaat = aldatmaca. xref 33:60 — aynı üçlü sûrede tekrar gelecek.",
 13: "◇ Sûrenin tek adlı yeri: Yesrib (PN, yer). İki grup iki eylem: biri 'geri dönün' diyor (tâife), öbürü izin istiyor (ferîk) — adsiz2 ikisini de yakalıyor. عور ×2, iddia ve düzeltme aynı ayette: 'evlerimiz korunmasız' / 'korunmasız değildi'. Beyan ile durum açıkça ayrılıyor; yapı L3'e (görünüş-durum) benziyor ama konu olgu değil niyet: 🜁 olgu HAYIR, çıpa değil. Kapanış niyeti adlandırıyor: firar.",
 14: "◇ Karşı-olgusal şart (lev): gerçekleşmemiş bir kuşatma ve gerçekleşmemiş bir itaat. İki edilgen (dühılet · süilû) → ★★'ın tek kaynağı pas z=2,52. سأل kökü sûrede ikinci kez ve ters yönde: 33:8'de sâdıklara sorulur, burada onlardan fitne istenir.",
 15: "◇ 33:7-8'in ahit-sorgu çiftinin geri dönüşü: orada peygamberlerden ahit alınıp sâdıklara sorulacaktı; burada bunlar Allah'a ahit vermiş ve 'Allah'ın ahdi sorulacak' (عهد ×2, سأل üçüncü kez). ولي kökü burada 'arka çevirmek' anlamında; gloss 'dost, veli' bu kullanımı taşımıyor. ★★: allah z=2,55.",
 16: "◇ Kaçış kendi başına ölçülüyor: fayda vermez, verse de 'az'. فرر ×2 ve 33:13'ün son kelimesi firârâ — iki ayet aynı kökle bağlı. Fâsıla qalîlâ bu blokta 16, 18 ve 20'de: ÇİFT sıradaki üç ayet aynı kelimeyle kapanıyor (TAM SAYIM bilançoda). Tarayıcı v4 A_şart ile aday verdi — çıpa değil.",
 17: "◇ Simetrik soru: kötülük de rahmet de aynı fiille (رود ×2) Allah'ın dilemesine bağlanıyor ve ikisinden de 'korunma' soruluyor. Esmâ velî + nasîr ÇİFT olarak ayet sonunda, ama olumsuzlanan 'Allah'tan başka' birinin sıfatı: e_el=0. §4.3 tanımı bunu ÇİFT MÜHÜR sayıyor — 32:4 velî vakasının çift hâli ve ön-kayıt sınama kümesi için şimdiye kadarki en temiz yanlış mühür.",
 18: "◇ Allah bilen — 33:1'in alîm'i burada fiil (ya'lemu). ★★★ hapaks عوق (mu'avvikîn, 'alıkoyanlar'); هلم sûrede tek ama korpusta iki kez, hapaks değil. Kapanış yine 'az'.",
 19: "◇ Blokun en uzun ayeti (n=35, n z=2,40) ve bir teşbih: gözleri 'ölüm baygınlığı geçiren gibi' dönüyor. Korku iki kez (خوف ×2), iki yönde: gelince bakakalıyorlar, gidince dil uzatıyorlar — iki davranış korkunun varlığına ve yokluğuna bağlanıyor. شحح ×2 çerçeve. ★★★ hapaks سلق; ikinci bağımsız ölçüt n z=2,40 de eşiği geçiyor ve formül eklemiyor (borç #15'in yeni vakası). دور glossu 'yurt, ev' — tedûru (dönmek) için yanlış. 🜁 kademe L1 (davranış + karşılaştırma), olgu HAYIR.",
 20: "◇ Sûrenin adı ilk kez burada: el-ahzâb ×2 (حزب sûrede 3 kez: 20'de iki, 22'de bir) — ad metinde 20. ayete kadar geçmiyor. İki karşı-olgusal şart daha: 'gelseler' / 'aranızda olsalardı'. عرب kökü (a'râb) sûrede tek. Blok üçüncü qalîlâ ile kapanıyor.",
}
MEAL.update(MEAL2); M.update(M2)
