# -*- coding: utf-8 -*-
"""blok_23_101_118.py — sûre 23 son blok kaydı. SÛRE TAM (118/118)."""
import json
DIK=json.load(open('blok_dikey_23_101_118.json',encoding='utf-8'))
veri=json.load(open('kuran_veri.json',encoding='utf-8'))
AR={}
for s in veri['sureler']:
    for a in s['ayetler']: AR[(s['no'],a['no'])]=a['ar']

MEAL={
101:"Sûra üflendiğinde, o gün aralarında soy bağı kalmaz; birbirlerini de sormazlar.",
102:"Tartıları ağır gelenler, işte onlar kurtuluşa erenlerdir.",
103:"Tartıları hafif gelenler, işte onlar kendilerini ziyana uğratanlardır; cehennemde kalıcıdırlar.",
104:"Ateş yüzlerini yalar; orada dişleri sırıtmış hâlde kalırlar.",
105:"Âyetlerim size okunmuyor muydu da siz onları yalanlıyordunuz?",
106:"Dediler ki: Rabbimiz, bedbahtlığımız bize galip geldi; sapkın bir kavimdik.",
107:"Rabbimiz, bizi buradan çıkar; bir daha dönersek gerçekten zalimleriz.",
108:"Buyurdu: Sinin orada, bana konuşmayın.",
109:"Kullarımdan bir bölük vardı, \"Rabbimiz, iman ettik; bizi bağışla, bize merhamet et; sen merhamet edenlerin en hayırlısısın\" derlerdi.",
110:"Siz onları alaya aldınız; öyle ki bu, size zikrimi unutturdu ve onlara gülüyordunuz.",
111:"Bugün ben onlara sabretmelerinin karşılığını verdim; kurtuluşa erenler işte onlardır.",
112:"Buyurdu: Yeryüzünde yıl sayısıyla ne kadar kaldınız?",
113:"Dediler ki: Bir gün ya da günün bir kısmı kadar kaldık; sayanlara sor.",
114:"Buyurdu: Ancak az bir süre kaldınız — keşke bilseydiniz.",
115:"Sizi boş yere yarattığımızı ve bize döndürülmeyeceğinizi mi sandınız?",
116:"Gerçek egemen olan Allah yücedir. O'ndan başka ilâh yoktur; şerefli arşın Rabbidir.",
117:"Kim Allah ile birlikte, hakkında hiçbir delili olmadığı başka bir ilâha yakarırsa, hesabı ancak Rabbinin katındadır. İnkârcılar kurtuluşa ermez.",
118:"De ki: Rabbim, bağışla ve merhamet et; sen merhamet edenlerin en hayırlısısın.",
}

OLCUM={
101:"eksen yok · aktör yok · edim haber, kip NEG ×2 · şahıs 3MS 1 · 3MP ×3 · n=10 mora=58 harf=44, fâsıla يَتَسَآءَلُونَ *(birbirlerine sorarlar)* → ن, N sınıfı; i'râb GEN 1 · ACC 2; bab I ×1 · bab VI ×1; zaman PERF 1 · IMPF 1; **edilgen 1 — pas z=2,52** · yıldız ★★ · kökler نفخ *(üfleme)* · صور *(sûr; biçim)* · نسب *(soy, nesep)* · بين *(arası; açıklama)* · يوم *(gün)* · سأل *(isteme, dileme)* · bağ: **23:14 ile ortak نفخ komşuluğu** — dikey ölçüm نفخ ▸önce طين *(çamur)* ×79,5 veriyor, yaratılış dizisiyle aynı alan (elle, L2)",
102:"eksen yok · aktör yok · edim haber · şahıs 3FS 1 · 3MS 1 · 3MP 1 · n=6 mora=36 harf=31, fâsıla ٱلْمُفْلِحُونَ *(kurtuluşa erenler)* → ن, N sınıfı; i'râb NOM 2; bab I ×1; zaman PERF 1; dış düğüm 1 · yıldız ★ yok · kökler ثقل *(ağırlık)* · وزن *(tartı, mîzan)* · فلح *(kurtuluşa erme, felâh)* · bağ: xref ثقلت *(ağır geldi)* + ميزان *(tartı)* + مفلح *(kurtuluşa eren)* → **7:8**; **23:1 ile SÛRENİN BÜYÜK HALKASI KAPANIYOR** — açılıştaki فلح kökü burada ism-i fâil çoğuluyla dönüyor (elle, L1, aday 491)",
103:"eksen yok · **aktör: adlı جَهَنَّم *(cehennem)* 9. sırada, tür 'yer', rol mecrur** · edim haber · şahıs 3FS 1 · 3MS 1 · 3MP ×3 · n=10 mora=59 harf=48, fâsıla خَٰلِدُونَ *(kalıcılar)* → ن, N sınıfı; i'râb NOM 2 · ACC 1 · GEN 1; bab I ×2; zaman PERF ×2; simetri [3,4,8,1]; dış düğüm 1 · yıldız ★ yok · kökler خفف *(hafifletme)* · وزن *(tartı, mîzan)* · خسر *(hüsran, ziyan)* · نفس *(nefis, can)* · خلد *(ebedî kalma)* · bağ: xref خفّت *(hafif geldi)* + ميزان + خسر *(ziyan)* → **7:9**; **23:11 ile ortak خلد** — orada Firdevs'te kalıcılık, burada cehennemde (elle, L1)",
104:"eksen yok · aktör yok · edim haber · şahıs 3FS ×2 · 3MP ×2 · n=6 mora=36 harf=27, fâsıla كَٰلِحُونَ *(yüzü buruşmuş olanlar)* → ن, N sınıfı; i'râb ACC 1 · NOM 2; bab I ×1; zaman IMPF 1; **hapaks ÇİFT: كلح *(dişleri sırıtacak biçimde yüzün buruşması)* ve لفح *(alevin yüzü yalaması)* — SÛRENİN TEK HAPAKS AYETİ ve iki hapaks bir arada; hapaks z=6,98: yıldızın tek kaynağı** (aday 440 kümesi) · yıldız ★★★ · kökler لفح · وجه *(yüz, yön)* · نور *(nûr, ışık; ateş)* · كلح · bağ yok",
105:"eksen yok · aktör yok · edim soru, kip INTG 1 · NEG 1 · şahıs 3FS ×3 · 2MP ×5 · 1S 1 · n=8 mora=42 harf=34, fâsıla تُكَذِّبُونَ *(yalanlarsınız)* → ن, N sınıfı; i'râb NOM 1; bab I ×3 · bab II ×1; zaman IMPF ×3 · PERF 1; edilgen 1; kök ikilemesi كون *(olmak)* ×2; simetri [3,1,5,1]; dış düğüm 1 · iç düğüm 1 · yıldız ★ yok · kökler كون · أيي *(âyet, işaret)* · تلو *(okuma, ardından gelme)* · كذب *(yalan; yalanlama)* · bağ: **23:66 ile sûre-içi bölüt ikizi** — ortak gövde beş kelime; iki uçta ayrışıyor: açılış CERT'ten INTG'ye, kapanış نكص *(geri dönme)*'den كذب'ya; sahne dünyadan âhirete (elle, L1, aday 492)",
106:"eksen: lafız yok · **Rab 2. sırada, رَبَّنَا *(Rabbimiz)* — n=8'de tek Rab, rab z=2,34** · aktör yok · edim haber · şahıs 3MP ×2 · 1P ×5 · 3FS 1 · n=8 mora=55 harf=39, fâsıla ضَآلِّينَ *(sapkınlar)* → ن, N sınıfı; i'râb ACC 3 · NOM 1; bab I ×3; zaman PERF ×3; dış düğüm 1 · yıldız ★★ · kökler قول *(söz söyleme)* · ربب *(rab, terbiye etme)* · غلب *(üstün gelme, galibiyet)* · شقو *(bedbahtlık)* · كون *(olmak)* · قوم *(kalkma; kavim; kıyamet)* · ضلل *(sapma, saptırma)* · bağ: xref كان *(idi)* + قوم *(kavim)* + ضالّ *(sapkın)* → 6:77; **رَبّ nidâ çağrısı sûrede sekizinci kez, İLK KEZ inkârcıların ağzından** (elle, L1, aday 493)",
107:"eksen: lafız yok · **Rab 1. sırada — ayetin İLK kelimesi; n=7'de tek Rab, rab z=2,72** · aktör yok · edim emir + şart, kip IMPV 1 · COND 1 · şahıs 1P ×5 · 2MS 1 · 3FS 1 · n=7 mora=43 harf=30, fâsıla ظَٰلِمُونَ *(zalimler)* → ن, N sınıfı; i'râb ACC 2 · NOM 1; bab I ×1 · bab IV ×1; zaman IMPV 1 · PERF 1 · yıldız ★★ · kökler ربب *(rab, terbiye etme)* · خرج *(çıkma, çıkarma)* · عود *(geri dönme)* · ظلم *(zulüm)* · bağ: **23:93-94 ile aynı çift yapısı** — iki ayet, ikisinde de رَبّ çağrısı, ikincisinde çağrı ayet başına geçiyor; içerik tersine ve ikisi de ظلم köküyle bitiyor (elle, L1, aday 493)",
108:"eksen yok · aktör yok · edim emir + yasak, kip IMPV 1 · PRO 1 · şahıs 3MS 1 · 2MP ×4 · 3FS 1 · 1S 1 · n=5 mora=29 harf=23, fâsıla تُكَلِّمُونِ *(bana konuşursunuz)* → ن, N sınıfı; **i'râb kaydı YOK — ayette îrablanan isim yok**; bab I ×2 · bab II ×1; zaman PERF 1 · IMPV 1 · IMPF 1; **biçim NEHY — sûrenin üç NEHY'inden sonuncusu** · yıldız ★ yok · kökler قول *(söz söyleme)* · خسأ *(aşağılanıp sinme, kovulma)* · كلم *(söz, konuşma)* · bağ: **23:36 ile aynı ölçüm boşluğu (aday 475)** — sûrede i'râb kaydı boş ikinci ve son ayet; **23:100 ile ortak كلم** — orada isteğin 'bir söz' sayılması, burada konuşmanın yasaklanması (elle, L1)",
109:"eksen: lafız yok · **Rab 7. sırada, رَبَّنَآ *(Rabbimiz)* — rab z=1,20** · **aktör: adsız ferîk *(bir bölük)* 3. sırada** · edim emir, kip IMPV ×2 · şahıs 3MS ×2 · 1S 1 · 3MP ×2 · 1P ×5 · 2MS ×3 · **n=14 mora=82 harf=63 — bloğun en uzun ikinci ayeti**, fâsıla ٱلرَّٰحِمِينَ *(merhamet edenler)* → ن, N sınıfı; i'râb ACC 2 · NOM 2 · GEN 2; bab I ×4 · bab IV ×1; zaman PERF ×2 · IMPF 1 · IMPV ×2; kök ikilemesi رحم *(rahmet, merhamet)* ×2; dış düğüm 3 · iç düğüm 1 · yıldız ★ yok · kökler كون *(olmak)* · فرق *(ayırma, parçalara bölme)* · عبد *(kul, kulluk)* · قول *(söz söyleme)* · ربب *(rab, terbiye etme)* · أمن *(güven; iman)* · غفر *(bağışlama, mağfiret)* · رحم · خير *(hayır, daha iyi)* · bağ: xref قال *(dedi)* + ربّ *(Rab)* + آمن *(iman etti)* → 3:16 · 5:83 · غفر + رحم + خير → **7:155 ve 23:118**; **23:118 ile sûre-içi bölüt ikizi — sûrenin SON ayetiyle** (elle, L1, aday 494)",
110:"eksen yok · aktör yok · edim haber · şahıs 2MP ×7 · 3MP ×4 · 1S 1 · n=8 mora=56 harf=43, fâsıla تَضْحَكُونَ *(gülersiniz)* → ن, N sınıfı; i'râb ACC 1 · NOM 1; bab I ×2 · bab IV ×1 · bab VIII ×1; zaman PERF ×3 · IMPF 1 · yıldız ★ yok · kökler أخذ *(alma, edinme)* · سخر *(boyun eğdirme; alay)* · نسي *(unutma)* · ذكر *(anma, zikir)* · كون *(olmak)* · ضحك *(gülme)* · bağ: **23:71 ile ortak ذكر** — orada zikirden yüz çevirmek, burada zikri unutmak (elle, L1)",
111:"eksen yok · aktör yok · edim haber · şahıs 1S ×3 · 3MP ×5 · n=8 mora=47 harf=37, fâsıla ٱلْفَآئِزُونَ *(kurtuluşa erenler)* → ن, N sınıfı; i'râb ACC 3 · NOM 1; bab I ×2; zaman PERF ×2 · yıldız ★ yok · kökler جزي *(karşılık verme)* · يوم *(gün)* · صبر *(sabır)* · فوز *(kurtuluş, fevz)* · bağ: **23:102 ile ortak kapanış işlevi** — orada ٱلْمُفْلِحُونَ *(kurtuluşa erenler)*, burada ٱلْفَآئِزُونَ; iki ayrı kök aynı sonucu adlandırıyor (elle, L1, aday 491)",
112:"eksen yok · aktör yok · edim soru, kip INTG 1 · şahıs 3MS 1 · 2MP ×2 · **n=7 mora=27 harf=23 — bloğun en kısa iki ayetinden biri**, fâsıla سِنِينَ *(yıllar)* → ن, N sınıfı; i'râb ACC 2 · GEN 2; bab I ×2; zaman PERF ×2; sayı sözcüğü عَدَد *(sayı)* · yıldız ★ yok · kökler قول *(söz söyleme)* · لبث *(kalma, durma)* · أرض *(yer, yeryüzü)* · عدد *(sayma, sayı)* · سنو *(yıl)* · bağ: **23:112-114 ölçüm diyaloğu başlıyor** (elle, L1, aday 495)",
113:"eksen yok · aktör yok · edim emir, kip IMPV 1 · şahıs 3MP ×2 · 1P ×2 · 2MS 1 · n=8 mora=48 harf=35, fâsıla ٱلْعَآدِّينَ *(sayanlar)* → ن, N sınıfı; i'râb ACC 3 · GEN 1; bab I ×3; zaman PERF ×2 · IMPV 1; kök ikilemesi يوم *(gün)* ×2; sayı sözcüğü عادّ *(sayan)*; dış düğüm 2 · yıldız ★ yok · kökler قول *(söz söyleme)* · لبث *(kalma, durma)* · يوم · بعض *(bir kısım)* · سأل *(isteme, dileme)* · عدد *(sayma, sayı)* · bağ: xref قال *(dedi)* + لبث *(kaldı)* + يوم → **2:259 · 18:19 — üç ayrı 3-gram, ikisi de aynı iki ayete** (elle, L1, aday 495)",
114:"eksen yok · aktör yok · edim şart, kip NEG 1 · RES 1 · COND 1 · şahıs 3MS 1 · 2MP ×7 · n=9 mora=49 harf=35, fâsıla تَعْلَمُونَ *(bilirsiniz)* → ن, N sınıfı; i'râb ACC 2; bab I ×4; zaman PERF ×3 · IMPF 1; sayı sözcüğü قَلِيل *(az)*; biçim HASR · yıldız ★ yok · kökler قول *(söz söyleme)* · لبث *(kalma, durma)* · قلل *(azlık)* · كون *(olmak)* · علم *(bilme)* · bağ: **23:84 · 23:88 · 23:114 — تَعْلَمُونَ fâsılası sûrede üçüncü kez**; ilk ikisi şartın koşulu, burada geçmişe dönük temenni (elle, L1)",
115:"eksen yok · aktör yok · edim soru, kip INTG 1 · NEG 1 · şahıs 2MP ×6 · 1P ×3 · n=8 mora=50 harf=40, fâsıla تُرْجَعُونَ *(döndürülürsünüz)* → ن, N sınıfı; **i'râb ACC 3 — tamamı mansûb**; bab I ×3; zaman PERF ×2 · IMPF 1; edilgen 1 (pas z=1,57) · yıldız ★ · kökler حسب *(hesap, sayma)* · خلق *(yaratma)* · عبث *(boş yere, amaçsız oyalanma)* · رجع *(dönme, geri döndürme)* · bağ: **23:12-14 ile ortak خلق** — orada 'nasıl', burada 'niçin' sorusu; **23:55 ile aynı fiil** أَيَحْسَبُونَ / أَفَحَسِبْتُمْ *(sandılar mı / sandınız mı)* (elle, L1, aday 496)",
116:"eksen: **Allah lafzı 2. sırada** (allah z=1,29) · **Rab 9. sırada** (rab z=1,62) — **sûrede lafız ve Rab'bin aynı ayette buluştuğu iki yerden biri** (öteki 23:117) · **esmâ مَلِك *(melik)* 3. sırada — GEÇERLİ** (lafza doğrudan sıfat); **esmâ كَرِيم *(kerîm)* 11. sırada — ÖLÇÜM ARTEFAKTI (aday 461)**: ٱلْعَرْشِ ٱلْكَرِيمِ *(şerefli arş)* tamlamasında arşı niteliyor, ölçüt (c) · aktör yok · edim haber, kip NEG 1 · RES 1 · şahıs 3MS ×2 · **iltifât 1 (12>3)** · n=11 mora=55 harf=42, **fâsıla ٱلْكَرِيمِ → م — sûrenin م ile biten dört ayetinden sonuncusu**, sınıf N; i'râb NOM 4 · ACC 1 · GEN 2; bab VI ×1; zaman PERF 1; kök ikilemesi أله *(ilâh; lafza-i celâl)* ×2; biçim HASR; dış düğüm 2 · yıldız ★ · kökler علو *(yücelik; böbürlenme)* · أله · ملك *(mülk; melik)* · حقق *(hak, gerçek)* · ربب *(rab, terbiye etme)* · عرش *(arş, taht)* · كرم *(üstün tutma, ikram)* · bağ: xref تعالى *(yücedir)* + اللّه *(Allah)* + ملك *(melik)* → **20:114**; **23:86 ile soru-cevap çifti** — ortak terkip رَبُّ ٱلْعَرْشِ, değişen yalnız sıfat (elle, L1, aday 497)",
117:"eksen: **Allah lafzı 4. sırada** (allah z=0,58) · **Rab 14. sırada** (rab z=0,86) — lafız ve Rab'bin buluştuğu ikinci ve son ayet · aktör yok · edim haber, kip NEG ×2 · şahıs 3MS ×7 · **n=18 mora=84 harf=68 — bloğun en uzun ayeti** (n z=0,59), fâsıla ٱلْكَٰفِرُونَ *(inkârcılar)* → ن, N sınıfı; **i'râb ACC 7 · GEN 2 · NOM 2 — blokta en yüksek mansûb oranı**; bab I ×1 · bab IV ×1; zaman IMPF ×2; kök ikilemesi أله *(ilâh; lafza-i celâl)* ×2; simetri [3,1,7,1] · yıldız ★ yok · kökler دعو *(çağırma, dua)* · أله · أخر *(geciktirme, sonraya bırakma)* · برهن *(burhan, kesin delil)* · حسب *(hesap, sayma)* · عند *(kat, yan)* · ربب *(rab, terbiye etme)* · فلح *(kurtuluşa erme, felâh)* · كفر *(inkâr, nankörlük)* · bağ: **23:1 · 23:102 · 23:117 — فلح kökü sûrede üçüncü ve son kez; ilk ikisi olumlu, bu OLUMSUZ; halka kapanıyor** (elle, L1, aday 491)",
118:"eksen: lafız yok · **Rab 2. sırada, رَّبِّ *(Rabbim)* — n=7'de tek Rab, rab z=2,72** · aktör yok · edim emir, **kip IMPV ×3 — sûrenin en yoğun emir ayeti** · şahıs 2MS ×4 · 1S 1 · **iltifât 1 (3>12) — sûrenin yedinci ve son iltifâtı** · n=7 mora=34 harf=28, fâsıla ٱلرَّٰحِمِينَ *(merhamet edenler)* → ن, N sınıfı; i'râb NOM 2 · GEN 1; bab I ×3; **zaman IMPV ×3 — üç fiilin üçü de emir**; kök ikilemesi رحم *(rahmet, merhamet)* ×2; dış düğüm 1 · iç düğüm 1 · yıldız ★★ · kökler قول *(söz söyleme)* · ربب *(rab, terbiye etme)* · غفر *(bağışlama, mağfiret)* · رحم · خير *(hayır, daha iyi)* · bağ: **23:109 ile sûre-içi bölüt ikizi** — altı kelime ortak; sûre kendi içinden bir alıntıyla kapanıyor (elle, L1, aday 494)",
}

MERCEK={
101:"Ayet iki bağı birden kesiyor ve ikisi de olumsuzlama ile: نسب *(soy, nesep)* ve karşılıklı sorma. İkincisi bab VI, yani karşılıklılık kalıbı — kesilen şey tam olarak karşılıklılık. نسب korpusta üç geçişli ve komşuluğunda eşik üstü hiçbir kavram yok. İlk fiil edilgen (نُفِخَ *(üflendi)*): üfleyen söylenmiyor, sûre boyunca süren fâil-silme deseninin son örneği.",
102:"Sûrenin büyük halkası burada kapanıyor. Açılış فلح *(kurtuluşa erme, felâh)* kökünü PERF ile veriyordu (أَفْلَحَ *(kurtuluşa erdi)*); burada aynı kök ism-i fâil çoğulu (ٱلْمُفْلِحُونَ *(kurtuluşa erenler)*). İki ayet aynı fâsıla yapısını taşıyor: belirli ism-i fâil çoğulu. Aradaki ölçülebilir fark ölçüt: 23:1'de kurtuluşun koşulu bir sıfat zinciriydi, burada bir tartı. Ve aynı işaret kalıbı üçüncü kez: أُو۟لَٰٓئِكَ هُمُ *(işte onlar)* — 23:7, 23:10 ve burada.",
103:"İki ayet bir ölçü ekseninde karşıtlanıyor ve karşıtlık iki fiille kuruluyor: ثَقُلَتْ *(ağır geldi)* / خَفَّتْ *(hafif geldi)*. Dikey ölçüm bu çiftin korpusta sabit olduğunu veriyor — خفف *(hafifletme)* ▸sonra وزن *(tartı, mîzan)* ×57,0. Ama simetri tam değil: kurtuluş ayeti altı kelime, ziyan ayeti on; ve ziyan tarafına bir yer adı ile bir süre eklenmiş. Ziyanın nesnesi de ölçülebilir biçimde dönüşlü: أَنفُسَهُمْ *(kendilerini)*.",
104:"118 ayetlik sûrenin tek hapaks ayeti ve ikisi bir arada — aday 440'ın çift-hapaks kümesinin bir vakası. İki hapaks da aynı beden bölgesine bağlı: biri ateşin yüze yaptığı, öteki yüzün aldığı biçim. Ve ikisi ayetin iki ucunda duruyor: لفح *(alevin yüzü yalaması)* ilk kelime, كلح *(dişleri sırıtacak biçimde yüzün buruşması)* fâsıla. Aradaki üç kelime bilinen sözlükten. Ayet sözlüğünü uçlara koyup ortasını yaygın kelimelerle dolduruyor.",
105:"23:66'nın haberi burada soruya çevriliyor ve iki uçta ayrışıyor: kip CERT'ten INTG'ye, kapanış fiili نكص *(geri dönme, ökçe üstü çekilme)*'den كذب *(yalan; yalanlama)*'ya. Ortadaki beş kelime birebir aynı. Ölçülebilir olan konum: birinci geçiş dünya sahnesinde (23:66), ikincisi âhiret sahnesinde. Aynı cümle iki kez, iki zamanda, iki kiple.",
106:"Sûrede sekiz kez رَبّ *(Rab)* çağrısı geçti; yedisi elçilerin ya da muhatabın ağzındaydı, bu ilk kez reddedenlerin. Savunma ölçülebilir biçimde fâili dışarı atıyor: غَلَبَتْ عَلَيْنَا شِقْوَتُنَا *(bedbahtlığımız bize galip geldi)* — özne kendi bedbahtlıkları, kendileri nesne. İkinci cümle özneyi geri alıyor ama nitelik olarak: كُنَّا قَوْمًۭا ضَآلِّينَ *(sapkın bir kavimdik)*. شقو *(bedbahtlık)* korpusta 12 geçişli ve komşuluğunda Rab ×2,5.",
107:"İkinci istek ve yapı 23:93-94 çiftinin aynısı: iki ayet, ikisinde de رَبّ *(Rab)* çağrısı, ikincisinde çağrı ayetin başına geçiyor. Ama içerik tersine — orada elçi zalimlerin arasına konmamayı istiyordu, burada zalimler oradan çıkmayı. Ve istek kendi cezasını içeriyor: şart cümlesi bir taahhüt kuruyor ve taahhüdün ihlâli için kullanılan kelime ظَٰلِمُونَ *(zalimler)*, yani 23:94'ün terkibiyle aynı kök.",
108:"Sûrenin 118 ayetinde i'râb kaydı boş olan iki ayetten ikincisi — beş kelimenin hepsi fiil ya da harf. Ölçülebilir bir kapanış var: 23:100'de istek 'bir söz' diye sınıflanmıştı, burada söz alışverişinin kendisi kesiliyor. خسأ *(aşağılanıp sinme, kovulma)* korpusta dört geçişli ve üçü ism-i fâil; emir kipindeki tek geçişi burada.",
109:"Alıntı içinde alıntı: konuşan birinci tekil, aktardığı bölük birinci çoğul konuşuyor. Ve aktarılan dua sûrenin son ayetinde aynen tekrarlanacak — 23:109'un son yedi kelimesi ile 23:118 arasında altı kelime ortak. Üstünlük tamlaması kalıbı sûrede dördüncü kez: خَيْرُ ٱلرَّٰحِمِينَ *(merhamet edenlerin en hayırlısı)*, öncekiler 23:14, 23:29, 23:72. Dördü de üstünlük ismi + belirli ism-i fâil çoğulu.",
110:"Ayet bir nedensellik zinciri kuruyor ve üç adımı üç ayrı fiille veriyor: alaya alma → unutturma → gülme. Ortadaki fiil ölçülebilir biçimde ilginç: أَنسَوْكُمْ *(size unutturdular)* — özne alay edilenler, yani alay konusu olanlar unutturanlara dönüşüyor. سخر *(boyun eğdirme)* kökü korpusta çoğunlukla 'musahhar kılma' işlevinde (▸sonra قمر *(ay)* ×51,0 · شمس *(güneş)* ×41,7); burada alay anlamında. ضحك *(gülme)* komşuluğunda بكي *(ağlama)* ×312,2 — çift korpusta neredeyse sabit, ama bu ayette ağlama yok.",
111:"Sûrenin son kurtuluş bildirimi ve bu kez kök değişiyor: 23:1 ve 23:102'de فلح *(kurtuluşa erme, felâh)*, burada فوز *(kurtuluş, fevz)*. Aynı sonuç üç ayette üç kez, ikisi bir kökten biri başka. Gerekçe ölçülebilir biçimde daraltılmış: tek bir nitelik, صبر *(sabır)* — açılıştaki altı halkalık sıfat zinciri burada tek kelimeye iniyor. Zaman da geçmiş: جَزَيْتُهُمُ *(karşılığını verdim)*, PERF, tıpkı 23:1'in أَفْلَحَ'si gibi.",
112:"Sûrenin son sahnesi bir ölçüm sorusuyla açılıyor ve soru iki kez birimlendirilmiş: عَدَدَ سِنِينَ *(yılların sayısı)* — hem sayı sözcüğü hem zaman birimi. Soru yalnız 'ne kadar' değil, hangi ölçekte sayılacağını da veriyor. لبث *(kalma, durma)* kökü sûrede ilk kez ve üç ayette üst üste geçecek; dikey ölçüm ▸sonra yıl ×65,3 veriyor, kök korpusta zaten süre birimiyle eşleşiyor.",
113:"Cevap sorunun ölçeğini reddediyor: soru yıl birimindeydi, cevap gün birimine iniyor ve orada da bölünüyor — يَوْمًا أَوْ بَعْضَ يَوْمٍ *(bir gün ya da günün bir kısmı)*. Cevabın belirsizliği iki katmanlı: hangi birim ve o birimin ne kadarı. Kapanış sorumluluğu devrediyor: فَسْـَٔلِ ٱلْعَآدِّينَ *(sayanlara sor)* — aynı kök عدد *(sayma, sayı)* sorudaki 'sayı'dan buradaki 'sayanlar'a geçiyor.",
114:"Düzeltme cevabın belirsizliğini bir HASR ile bağlıyor: إِن … إِلَّا قَلِيلًا *(ancak az)*. Birimi tartışmıyor, ölçüyü tartışıyor — gün de yıl da az. Kapanış sûrenin üçüncü kez aynı fâsılasını getiriyor ama kipi değiştirerek: iki kez şart, burada temenni. Ölçüm sorusunun kapanışı bilgiye, bilgi de geçmişe kaydırılıyor.",
115:"Sûrenin yaratma teması son kez ve ilk kez amaç üzerinden dönüyor: 23:12-14 nasıl yaratıldığını sayıyordu, bu ayet niçin yaratılmadığını soruyor. عبث *(boş yere, amaçsız oyalanma)* korpusta iki geçişli ve komşuluğunda eşik üstü kavram yok. İki iddia tek soruya bağlanmış ve ikisi de أَنَّ ile: amaçsızlık ve dönüşsüzlük. Ölçülebilir bir bağ: ikinci iddia edilgen (لَا تُرْجَعُونَ *(döndürülmezsiniz)*), yani reddedilen şey bir edilgin konum.",
116:"23:86'nın sorusu otuz ayet sonra cevaplanıyor ve terkip neredeyse aynı: رَبُّ ٱلْعَرْشِ *(arşın Rabbi)* + sıfat. Yalnız sıfat değişiyor — ٱلْعَظِيمِ *(büyük)* → ٱلْكَرِيمِ *(şerefli)*. İki ayet de م fâsılası taşıyor; sûrenin dört م ayetinin ikisi bu çift. أله *(ilâh; lafza-i celâl)* kökü yine iki işlevde: özel ad ve cins isim, aralarında HASR. علو *(yücelik; böbürlenme)* kökü bab VI'da — 23:92'deki kalıbın aynısı.",
117:"Halkanın kapanışı burada tamamlanıyor. Sûre قَدْ أَفْلَحَ ٱلْمُؤْمِنُونَ *(mü'minler kurtuluşa erdi)* ile açıldı; 23:102 aynı kökü ism-i fâille geri getirdi; bu ayet aynı kökü olumsuzlayarak kapatıyor: لَا يُفْلِحُ ٱلْكَٰفِرُونَ *(inkârcılar kurtuluşa ermez)*. Üç geçişin üçünde de fâsıla belirli bir ism-i fâil çoğulu. Ölçülebilir bir asimetri: iki olumlu geçişte kök fâsılanın kendisi, olumsuz geçişte fâsıla كَٰفِرُونَ *(inkârcılar)* ve فلح *(kurtuluşa erme, felâh)* fiile geçmiş. Ayet ayrıca on sekiz kelimede yedi mansûb taşıyor — blokta en yüksek ACC oranı.",
118:"Sûre kendi içinden bir alıntıyla kapanıyor. 23:109'da geçmişte bir bölüğün söylediği dua aktarılmıştı; son ayet aynı duayı muhataba emir olarak veriyor. Fark ölçülebilir: orada birinci çoğul (ٱغْفِرْ لَنَا وَٱرْحَمْنَا *(bizi bağışla, bize merhamet et)*), burada nesnesiz (ٱغْفِرْ وَٱرْحَمْ *(bağışla ve merhamet et)*) — zamir düşüyor, dua genelleşiyor. Üstünlük tamlaması sûrede beşinci ve son kez, aynı yapıda. Yedi kelimede üç emir: sûrenin en yoğun emir ayeti, ve son fiil yine bir ism-i fâil çoğuluna bağlanıyor — 118 ayetin fâsıla deseni sona kadar bozulmuyor.",
}

ATLAMA={
 "23:104":"★★★ ayet. 🜁 biyolog YAZILMADI — ayette bir beden bölgesi adı var (وجه *(yüz, yön)*) ama iki hapaksın hiçbiri fizyolojik bir süreç adlandırmıyor: لفح *(alevin yüzü yalaması)* alevin dokunuşunu, كلح *(dişleri sırıtacak biçimde yüzün buruşması)* yüzün aldığı görünümü veriyor; ikisi de betimleyici, anatomik ya da fizyolojik mekanizma çıpası yok. Yüz adının varlığı tek başına yeterli çıpa sayılmadı. 🜂 uzay YAZILMADI — نور *(nûr, ışık)* kökü burada ateş anlamında ve gönderge azap; ışık/ışıma okumasını seçmek yasaklı 'bilimsel izdüşüm' olurdu.",
 "_blok_notu_101_118":"Blok 23:101-118'de tek ★★★ ayet: 23:104, ve kaynağı hapaks z=6,98 (sûrenin tek hapaks ayeti). İki mercek de atlandı. SÛRE TOPLAMI: 118 ayette on altı ★★★; **on beşinde iki mercek de atlandı**, yalnız 23:86'da bir mercek (🜂 uzay) yazılabildi. **Biyolog merceği sûre 23'te HİÇ yazılmadı** — sûrenin biyolojik olarak en yoğun ayetleri (23:12-14 yaratılış zinciri, 23:21 davar/karın/süt, 23:78 duyular, 23:104 yüz) ★★★ almadı ya da çıpasız kaldı. Adaylar 468 ve 472 için sûre çapında kanıt.",
}

p='/home/claude/repo/notlar/okuma_metni.json'
OM=json.load(open(p,encoding='utf-8'))
for n in range(101,119):
    OM['23']["23:%d"%n]={"ar":AR[(23,n)],"meal":MEAL[n],"olcum":OLCUM[n],
                         "mercek":MERCEK[n],"dikey":DIK["23:%d"%n]}
OM['23']['_mercek_atlama_notu'].update(ATLAMA)
OM['ilerleme']['tam']=[1,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23]
OM['ilerleme']['not']=("Sûre 22 TAM (78/78). **Sûre 23 TAM (118/118).** "
                       "Devam: sûre 24 (Nûr) — makro profilden başla, sonra 24:1'den oku.")
OM['ilerleme']['kismi']={"2":"1-20 ayet düzeyinde"}
OM['ilerleme']['okunan_ayet']=1581
json.dump(OM,open(p,'w',encoding='utf-8'),ensure_ascii=False,indent=1)
print('okuma_metni: sûre 23 →',len([k for k in OM['23'] if not k.startswith('_')]),'ayet')

pm='/home/claude/repo/notlar/mercek_kayit.json'
MK=json.load(open(pm,encoding='utf-8'))
for n in range(101,119): MK['23']["23:%d"%n]=MERCEK[n]
MK['23_atlama'].update(ATLAMA)
json.dump(MK,open(pm,'w',encoding='utf-8'),ensure_ascii=False,indent=1)
print('mercek_kayit: sûre 23 →',len(MK['23']),'mercek')
