# -*- coding: utf-8 -*-
"""blok_21_21_40.py — Enbiyâ 21-40 bloğunun okuma kaydını dosyalara yazar."""
import json

DIK = json.load(open('blok_dikey_21_21_40.json', encoding='utf-8'))
veri = json.load(open('kuran_veri.json', encoding='utf-8'))
AR = {}
for s in veri['sureler']:
    for a in s['ayetler']:
        AR[(s['no'], a['no'])] = a['ar']

MEAL = {
21: "Yoksa yerden birtakım ilâhlar edindiler de, diriltenler onlar mı?",
22: "O ikisinde Allah'tan başka ilâhlar olsaydı, ikisi de bozulup giderdi. Arşın Rabbi Allah, onların nitelemelerinden münezzehtir.",
23: "O, yaptığından sorulmaz; onlar ise sorulurlar.",
24: "Yoksa O'ndan başka ilâhlar mı edindiler? De ki: Getirin kesin delilinizi. Bu, benimle beraber olanların zikri ve benden öncekilerin zikridir. Hayır, onların çoğu hakkı bilmiyor; bu yüzden yüz çeviriyorlar.",
25: "Senden önce hiçbir elçi göndermedik ki ona, 'Benden başka ilâh yoktur, öyleyse bana kulluk edin' diye vahyetmiş olmayalım.",
26: "\"Rahmân çocuk edindi\" dediler. O münezzehtir. Hayır, onlar ikram edilmiş kullardır.",
27: "Sözle O'nun önüne geçmezler; onlar yalnız O'nun buyruğuyla iş görürler.",
28: "Önlerindekini de arkalarındakini de bilir; O'nun razı olduğundan başkasına şefaat etmezler ve O'nun haşyetinden titrerler.",
29: "İçlerinden kim, 'Ben O'nun dışında bir ilâhım' derse, işte onu cehennemle karşılarız. Zalimleri böyle karşılarız.",
30: "İnkâr edenler görmediler mi ki gökler ve yer bitişikti, biz onları ayırdık; ve diri olan her şeyi sudan kıldık. Hâlâ inanmayacaklar mı?",
31: "Yerde, onları sarsmasın diye sabit dağlar var ettik; orada geniş yollar açtık — belki yollarını bulurlar.",
32: "Göğü de korunmuş bir tavan kıldık. Onlar ise onun işaretlerinden yüz çeviriyorlar.",
33: "Geceyi ve gündüzü, güneşi ve ayı yaratan O'dur; her biri bir felekte yüzmektedir.",
34: "Senden önce hiçbir beşere ölümsüzlük vermedik. Sen ölürsen onlar ebedî mi kalacak?",
35: "Her nefis ölümü tadıcıdır. Sizi bir sınama olarak şerle de hayırla da yoklarız; ve bize döndürülürsünüz.",
36: "İnkâr edenler seni gördüklerinde, seni ancak alaya alırlar: \"İlâhlarınızı diline dolayan bu mu?\" derler. Oysa Rahmân'ın zikrini asıl onlar inkâr edenlerdir.",
37: "İnsan aceleden yaratıldı. Size işaretlerimi göstereceğim; benden acele istemeyin.",
38: "\"Doğru söyleyenlerseniz, bu vaat ne zaman?\" diyorlar.",
39: "İnkâr edenler, ateşi yüzlerinden de sırtlarından da savamayacakları ve yardım görmeyecekleri o vakti bir bilselerdi…",
40: "Hayır, o ansızın gelir de onları şaşkına çevirir; artık onu geri çevirmeye güçleri yetmez, kendilerine mühlet de verilmez.",
}

OLCUM = {
21: "eksen: lafız yok, Rab yok, esmâ yok · aktör: yok · edim haber, kip boş — ayet أَمِ *(yoksa)* ile açıldığı hâlde defter soru kipi vermiyor (ÖLÇÜM ARTEFAKTI, aday 438) · şahıs 3MP ×5, iltifât yok · n=7 mora=37 harf=30, fâsıla يُنشِرُونَ *(diriltiyorlar)* → ن, N sınıfı; i'râb ACC 1 · GEN 1; bab VIII ×1 ٱتَّخَذُوٓا۟ *(edindiler)* ve bab IV ×1 يُنشِرُونَ *(diriltiyorlar)*; zaman PERF 1 · IMPF 1; kök ikilemesi yok, hapaks yok · kökler أخذ *(alma, edinme)* · أله *(ilâh)* · أرض *(yer, yeryüzü)* · نشر *(yayma, açma; diriltme)* · bağ: xref yok",
22: "eksen: **Allah lafzı ayet-içi 6. ve 9. sırada — İKİ geçiş** · Rab 10. sırada رَبّ *(Rab)*, رَبِّ ٱلْعَرْشِ *(arşın Rabbi)* terkîbinde · esmâ yok · aktör: yok · edim şart, kip COND 1 · RES 1 · EMPH 1 (لَـ) · şahıs 3MS 1 · 3D 1 · 3FD 2 · 3MP 2, iltifât yok · n=13 mora=71 harf=53, fâsıla يَصِفُونَ *(niteliyorlar)* → ن, N sınıfı; i'râb NOM 2 · ACC 1 · GEN 3; bab I ×3; kök ikilemesi أله *(ilâh)* ×3; biçim HASR (إِلَّا *(ancak, -den başka)*); yıldız ★★ (lafız yoğunluğu z=2.55) · bağ: xref سُبْحَٰنَ ٱللَّهِ رَبِّ *(Allah münezzehtir, Rabbi…)* → 27:8 · رَبِّ ٱلْعَرْشِ … يَصِفُونَ *(arşın Rabbi… niteliyorlar)* → 43:82; SÛRENİN LAFIZ VE RAB'I BİR ARADA TAŞIYAN TEK AYETİ",
23: "eksen: yok · aktör: yok · edim haber, kip NEG 1 · şahıs 3MS ×2 · 3MP ×3, iltifât yok · n=6 mora=26 harf=22 — bloğun en kısa ayeti, fâsıla يُسْـَٔلُونَ *(sorulurlar)* → ن, N sınıfı; i'râb işaretsiz; bab I ×3; **edilgen 2 (n=6'da, z=3.48)**; kök ikilemesi سأل *(sorma, isteme)* ×2 — ikisi de edilgen; zaman IMPF ×3 · yıldız ★★★ (edilgen yoğunluğu) · bağ: 34:25 (elle kurulan, L1)",
24: "eksen: yok · aktör: yok · edim emir, kip IMPV 2 · NEG 1 · şahıs 3MP ×6 · 3MS 1 · 2MS 1 · 2MP ×3 · 1S ×2, iltifât yok · n=22 mora=101 harf=90 — bloğun en uzun ikinci ayeti, fâsıla يَعْلَمُونَ *(biliyorlar)*… fâsıla kelimesi مُّعْرِضُونَ *(yüz çevirenler)* → ن, N sınıfı; i'râb GEN 1 · ACC 4 · NOM 4; bab I ×3 · bab VIII ×1; kök ikilemesi ذكر *(anma, zikir)* ×2; sayı sözcüğü أَكْثَر *(daha çok, çoğu)*; biçim IDRAB (بَلْ *(hayır, bilakis)*) + DIKKAT; simetri [3,1,9,1] · kökler أخذ *(alma, edinme)* · دون *(beriki, başkası)* · أله *(ilâh)* · قول *(söz söyleme)* · هات *(getirin (getirme emri))* · برهن *(burhan, kesin delil)* · ذكر *(anma, zikir)* · قبل *(ön, önce; kabul)* · كثر *(çokluk)* · علم *(bilme)* · حقق *(hak, gerçek)* · عرض *(sunma; yüz çevirme)* · bağ: xref دُونِهِۦٓ … إِلَٰهًۭا … قُلْ *(O'ndan başka… ilâh… de ki)* → 18:14",
25: "eksen: yok — ayette إِلَٰهَ إِلَّآ أَنَا۠ *(benden başka ilâh yok)* var ama lafız yok · aktör: yok · edim emir, kip NEG 2 · RES 2 · IMPV 1 · şahıs 1P ×3 · 2MS 1 · 3MS ×2 · 1S ×2 · 2MP ×2 — beş ayrı şahıs, iltifât alanı boş · n=15 mora=77 harf=55, fâsıla فَٱعْبُدُونِ *(öyleyse bana kulluk edin)* → ن, N sınıfı; i'râb GEN 2 · ACC 2; bab I ×1 · bab IV ×2; kök ikilemesi رسل *(gönderme, elçi)* ×2; biçim HASR; simetri [4,7,11,1] · kökler رسل *(gönderme, elçi)* · قبل *(ön, önce; kabul)* · وحي *(vahiy, gizli bildirim)* · أله *(ilâh)* · عبد *(kul, kulluk)* · bağ: xref yok",
26: "eksen: lafız yok, Rab yok · **esmâ رَحْمٰن *(Rahmân)* 3. sırada — orta konum, mühür değil** (bağlam denetlendi: ilâhî ad, aday 414 yanlış pozitifi DEĞİL) · aktör: yok · edim haber, kip boş · şahıs 3MP ×2 · 3MS ×2, iltifât yok · n=8 mora=50 harf=43, fâsıla مُّكْرَمُونَ *(ikram edilmişler)* → ن, N sınıfı; i'râb NOM 3 · ACC 2; bab I ×1 · bab VIII ×1; biçim IDRAB (بَلْ *(hayır, bilakis)*) · kökler قول *(söz söyleme)* · أخذ *(alma, edinme)* · رحم *(rahmet, merhamet)* · ولد *(doğurma, çocuk)* · سبح *(tesbih, tenzih)* · عبد *(kul, kulluk)* · كرم *(üstün tutma, ikram)* · bağ: xref قَالُوا۟ ٱتَّخَذَ ٱلرَّحْمَٰنُ وَلَدًۭا *(Rahmân çocuk edindi dediler)* → 19:88 (Meryem'de aynı cümle ayetin TAMAMI)",
27: "eksen: yok · aktör: yok · edim haber, kip NEG 1 · şahıs 3MP ×5 · 3MS ×2, iltifât yok · n=6 mora=34 harf=31, fâsıla يَعْمَلُونَ *(iş görürler)* → ن, N sınıfı; i'râb GEN 2; bab I ×2; zaman IMPF ×2 · kökler سبق *(geçme, öne geçme)* · قول *(söz söyleme)* · أمر *(emir; iş)* · عمل *(iş, amel)* · bağ: xref yok",
28: "eksen: yok · aktör: yok · edim haber, kip NEG 1 · RES 1 · şahıs 3MS ×3 · 3MP ×5, iltifât yok · n=15 mora=71 harf=60, fâsıla مُشْفِقُونَ *(titreyenler)* → ن, N sınıfı; i'râb ACC 2 · NOM 2 · GEN 1; bab I ×2 · bab VIII ×1; biçim HASR (إِلَّا *(ancak)*); simetri [3,5,10,1] · kökler علم *(bilme)* · بين *(arası; açıklama)* · يدي *(el)* · خلف *(ayrılığa düşme; ardından gelme)* · شفع *(şefaat, çift kılma)* · رضو *(razı olma, hoşnutluk)* · خشي *(haşyet, saygıyla korkma)* · شفق *(şafak; işfak, içi titreyerek korkma)* · bağ: xref yok",
29: "eksen: yok · aktör: adlı جَهَنَّم *(cehennem)* 10. sırada, tür 'yer', rol mecrur · edim haber, kip boş · şahıs 3MS ×3 · 3MP 1 · 1S 1 · 1P ×2, iltifât yok · n=13 mora=66 harf=54, fâsıla ٱلظَّٰلِمِينَ *(zalimler)* → ن, N sınıfı; i'râb ACC 2 · NOM 1 · GEN 2; bab I ×3; kök ikilemesi جزي *(karşılık verme)* ×2; simetri [4,1,8,1]; ayet ۞ hizb işaretiyle açılıyor · kökler قول *(söz söyleme)* · أله *(ilâh)* · دون *(beriki, başkası)* · جزي *(karşılık verme)* · ظلم *(zulüm)* · bağ: xref yok",
30: "eksen: yok · aktör: yok · edim soru, kip INTG 2 · NEG 2 — ayet İKİ soruyla çerçeveleniyor (أَوَلَمْ *(görmediler mi)* … أَفَلَا *(hâlâ… mı)*) · şahıs 3MS 1 · 3MP ×4 · 3FD ×2 · 1P ×4 · 3D 1, iltifât yok · n=18 mora=103 harf=81 — bloğun en uzun ayeti (mora), fâsıla يُؤْمِنُونَ *(iman ederler)* → ن, N sınıfı; i'râb ACC 4 · GEN 4; bab I ×5 · bab IV ×1; **hapaks İKİ TANE: رتق *(bitişik olma, ratk)* ve فتق *(ayırma, yarma (fatk))* — ikisi de korpusta tek geçişli, ikisi de bu ayette (hapaks z=6.98)**; yıldız ★★★ · kökler رأي *(görme)* · كفر *(inkâr, nankörlük)* · سمو *(ad; gök)* · أرض *(yer, yeryüzü)* · كون *(olmak)* · رتق *(bitişik olma, ratk)* · فتق *(ayırma, yarma (fatk))* · جعل *(kılma, var etme)* · موه *(su)* · كلل *(hep, bütün)* · شيأ *(dileme; şey)* · حيي *(diri olma, hayat)* · أمن *(güven; iman)* · bağ: xref yok",
31: "eksen: yok · aktör: yok · edim haber, kip boş · şahıs 1P ×4 · 3FS ×2 · 3MP ×4, iltifât yok · n=13 mora=76 harf=58, fâsıla يَهْتَدُونَ *(yollarını bulurlar)* → ن, N sınıfı; i'râb GEN 1 · ACC 4; bab I ×3 · bab VIII ×1; kök ikilemesi جعل *(kılma, var etme)* ×2; simetri [3,1,8,1] · kökler جعل *(kılma, var etme)* · أرض *(yer, yeryüzü)* · رسو *(sabit dağ)* · ميد *(sarsılma, yalpalama)* · فجج *(geniş yol, dağ geçidi (fecc))* · سبل *(yol)* · هدي *(yol gösterme)* · bağ: xref أَرْض … رَوَٰسِىَ … تَمِيدَ *(yer… sabit dağlar… sarsılma)* → 16:15 ve 31:10",
32: "eksen: yok · aktör: yok · edim haber, kip boş · şahıs 1P ×2 · 3MP 1 · 3FS 1, iltifât yok · n=8 mora=60 harf=42, fâsıla مُعْرِضُونَ *(yüz çevirenler)* → ن, N sınıfı; i'râb ACC 3 · GEN 1 · NOM 1; bab I ×1; ism-i mef'ûl مَّحْفُوظًۭا *(korunmuş)* · kökler جعل *(kılma, var etme)* · سمو *(ad; gök)* · سقف *(tavan, çatı)* · حفظ *(koruma)* · أيي *(âyet, işaret)* · عرض *(sunma; yüz çevirme)* · bağ: xref yok",
33: "eksen: yok · aktör: yok · edim haber, kip boş · şahıs 3MS ×2 · 3MP ×2, iltifât yok · n=11 mora=57 harf=49, fâsıla يَسْبَحُونَ *(yüzerler)* → ن, N sınıfı; i'râb ACC 4 · NOM 1 · GEN 1; bab I ×2; DÖRT ardışık ACC: ٱلَّيْلَ وَٱلنَّهَارَ وَٱلشَّمْسَ وَٱلْقَمَرَ *(geceyi ve gündüzü, güneşi ve ayı)* · kökler خلق *(yaratma)* · ليل *(gece)* · نهر *(ırmak; gündüz)* · شمس *(güneş)* · قمر *(ay)* · كلل *(hep, bütün)* · فلك *(gemi, felek)* · سبح *(tesbih, tenzih; yüzme)* · bağ: xref ٱلَّيْل … ٱلنَّهَار … ٱلشَّمْس … ٱلْقَمَر *(gece… gündüz… güneş… ay)* → 16:12 ve 41:37 · كُلٌّۭ فِى فَلَكٍۢ يَسْبَحُونَ *(her biri bir felekte yüzer)* → 36:40",
34: "eksen: yok · aktör: yok · edim soru + şart, kip NEG 1 · INTG 1 · COND 1 · şahıs 1P ×2 · 2MS ×3 · 3MP 1, iltifât yok · n=10 mora=49 harf=43, fâsıla ٱلْخَٰلِدُونَ *(ebedî kalanlar)* → ن, N sınıfı; i'râb GEN 2 · ACC 1 · NOM 1; bab I ×2; kök ikilemesi خلد *(ebedî kalma)* ×2 — biri masdar ٱلْخُلْدَ *(ölümsüzlük)*, öteki ism-i fâil ٱلْخَٰلِدُونَ *(ebedî kalanlar)* · kökler جعل *(kılma, var etme)* · بشر *(müjde; beşer)* · قبل *(ön, önce; kabul)* · خلد *(ebedî kalma)* · موت *(ölüm)* · bağ: xref yok",
35: "eksen: yok · aktör: yok · edim haber, kip boş · şahıs 1P ×2 · 2MP ×3, iltifât yok · n=10 mora=62 harf=53, fâsıla تُرْجَعُونَ *(döndürülürsünüz)* → ن, N sınıfı; i'râb NOM 2 · GEN 4 · ACC 1; bab I ×2; edilgen 1 (تُرْجَعُونَ, z=2.52); yıldız ★★ · kökler كلل *(hep, bütün)* · نفس *(nefis, can)* · ذوق *(tatma)* · موت *(ölüm)* · بلو *(eskiyip yıpranma; sınama)* · شرر *(şer, kötülük)* · خير *(hayır, daha iyi)* · فتن *(sınama, fitne)* · رجع *(dönme, geri döndürme)* · bağ: xref كُلُّ نَفْسٍۢ ذَآئِقَةُ ٱلْمَوْتِ *(her nefis ölümü tadıcıdır)* → 3:185 ve 29:57",
36: "eksen: lafız yok · **esmâ رَحْمٰن *(Rahmân)* 15. sırada** (bağlam denetlendi: ilâhî ad, yanlış pozitif DEĞİL) — mühür değil, sondan üçüncü · aktör: yok · edim soru, kip NEG 1 · RES 1 · INTG 1 · şahıs 3MS ×2 · 2MS ×2 · 3MP ×6 · 2MP 1, iltifât yok · n=17 mora=97 harf=74, fâsıla كَٰفِرُونَ *(inkâr edenler)* → ن, N sınıfı; i'râb ACC 2 · GEN 2 · NOM 1; bab I ×3 · bab VIII ×1; kök ikilemesi كفر *(inkâr, nankörlük)* ×2 ve ذكر *(anma, zikir)* ×2; biçim HASR + DIKKAT; simetri [3,1,5,1] · kökler رأي *(görme)* · كفر *(inkâr, nankörlük)* · أخذ *(alma, edinme)* · هزأ *(alay etme)* · ذكر *(anma, zikir)* · أله *(ilâh)* · رحم *(rahmet, merhamet)* · bağ: xref yok",
37: "eksen: yok · aktör: yok · edim yasak, kip FUT 1 (سَـ) · PRO 1 · şahıs 3MS 1 · 1S ×3 · 2MP ×3, iltifât yok · n=8 mora=45 harf=40, fâsıla تَسْتَعْجِلُونِ *(benden acele istemeyin)* → ن, N sınıfı; i'râb NOM 2 · GEN 1; bab I ×1 · bab IV ×1 · bab X ×1; edilgen 1 (خُلِقَ *(yaratıldı)*, z=1.57); kök ikilemesi عجل *(acele)* ×2 — biri isim عَجَل *(acele)*, öteki bab X fiil تَسْتَعْجِلُونِ *(acele istiyorsunuz)*; biçim NEHY; yıldız ★ · kökler خلق *(yaratma)* · أنس *(insan)* · عجل *(acele)* · رأي *(görme)* · أيي *(âyet, işaret)* · bağ: xref yok",
38: "eksen: yok · aktör: yok · edim soru + şart, kip INTG 1 · COND 1 · şahıs 3MP ×2 · 2MP ×2, iltifât yok · n=7 mora=38 harf=29, fâsıla صَٰدِقِينَ *(doğru söyleyenler)* → ن, N sınıfı; i'râb NOM 1 · ACC 1; bab I ×2; biçim DIKKAT · **tam-ayet ikizi BEŞ: 10:48 · 27:71 · 34:29 · 36:48 · 67:25 — küme boyutu 6, okumada görülen en geniş küme (aday 429)** · kökler قول *(söz söyleme)* · وعد *(vaat)* · كون *(olmak)* · صدق *(doğruluk)* · bağ: dış düğüm 5",
39: "eksen: yok · aktör: yok · edim şart, kip COND 1 · NEG 3 — üç olumsuzlama tek ayette · şahıs 3MS 1 · 3MP ×9, iltifât yok · n=16 mora=76 harf=62, fâsıla يُنصَرُونَ *(yardım görürler)* → ن, N sınıfı; i'râb ACC 2 · GEN 2; bab I ×4; edilgen 1 (يُنصَرُونَ); simetri [3,1,6,1]; **cevabı düşmüş şart (لَوْ *(keşke, -sa)* var, cevap yok)** · kökler علم *(bilme)* · كفر *(inkâr, nankörlük)* · حين *(vakit)* · كفف *(alıkoyma; avuç)* · وجه *(yüz, yön)* · نور *(nûr, ışık; ateş)* · ظهر *(sırt; zuhur, açığa çıkma)* · نصر *(yardım)* · bağ: xref yok",
40: "eksen: yok · aktör: yok · edim haber, kip NEG 2 · şahıs 3FS ×3 · 3MP ×7, iltifât yok · n=10 mora=56 harf=46, fâsıla يُنظَرُونَ *(mühlet verilirler)* → ن, N sınıfı; i'râb ACC 2; bab I ×2 · bab IV ×1 · bab X ×1; edilgen 1 (يُنظَرُونَ); zaman IMPF ×4 — ayette PERF hiç yok; biçim IDRAB (بَلْ *(hayır, bilakis)*) · kökler أتي *(gelme, getirme)* · بغت *(ansızın gelme)* · بهت *(şaşkına çevirme; bühtan)* · طوع *(güç yetirme, itaat)* · ردد *(geri döndürme, dönüş)* · نظر *(bakma; mühlet verme)* · bağ: 21:39 ile ortak özne (o vakit) — şartın düşmüş cevabı buraya taşınıyor",
}

MERCEK = {
21: "Ayet bir malzemeyi bir işlevle çakıştırıyor: ilâhlar مِّنَ ٱلْأَرْضِ *(yerden)*, iddia edilen işleri ise يُنشِرُونَ *(diriltiyorlar)* — نشر *(yayma, açma; diriltme)* kökü hem yayıp açmayı hem yerden çıkarmayı taşıyor. Yani iddia, kökün kendi anlam alanında geri dönüyor. Zaman da bölünmüş: edinme PERF (bitmiş, insanın işi), diriltme IMPF (sürekli, ilâha atfedilen iş).",
22: "Şart cümlesinin öznesi ayette görünmüyor: فِيهِمَآ *(o ikisinde)* zamiri boşta duruyor, karşılığı bir önceki bloğun 21:19'undaki سَّمَٰوَٰت وَٱلْأَرْض *(gökler ve yer)*. Ayet ikiliyi morfolojiden taşıyor: هِمَآ 3D (eril ikil zamir) → فَسَدَتَا 3FD (dişil ikil fiil). Aynı gönderge içinde cins değişiyor, sayı değişmiyor. İkinci yarı ise ikiliği bırakıp tekile geçiyor: رَبِّ ٱلْعَرْشِ *(arşın Rabbi)* — bozulacak olan iki, bozulmayı önleyen bir.",
23: "Aynı kök iki kez, ikisi de edilgen, ama dağılım tam ters: لَا يُسْـَٔلُ *(sorulmaz)* olumsuz + tekil, وَهُمْ يُسْـَٔلُونَ *(onlar sorulurlar)* olumlu + çoğul. Üçüncü asimetri tümleçte: birinci edilgenin عَمَّا يَفْعَلُ *(yaptığından)* diye bir kapsamı var, ikincisinin hiç yok — soru sınırsız bırakılıyor. Altı kelimede üç fiil, üçü de IMPF; failin hiçbiri anılmıyor.",
24: "Ayet bir delil istiyor (هَاتُوا۟ بُرْهَٰنَكُمْ *(getirin kesin delilinizi)*) ve karşılık olarak delilin kendisini bir zikir olarak sunuyor: ذِكْرُ مَن مَّعِىَ وَذِكْرُ مَن قَبْلِى *(benimle olanların zikri ve benden öncekilerin zikri)*. ذكر *(anma, zikir)* iki kez, ikisi de izafet başı; ayıran tek şey zaman zarfı: مَعِىَ *(benimle)* ↔ قَبْلِى *(benden önce)*. Yani istenen belge, iki zaman diliminin aynı metni olarak veriliyor. بَلْ *(hayır, bilakis)* ile gelen kapanış talebi bilgiye değil bilmemeye bağlıyor.",
25: "İki olumsuzlama iç içe: وَمَآ أَرْسَلْنَا … إِلَّا نُوحِىٓ *(göndermedik ki… vahyetmiş olmayalım)*, ve vahyin içeriği kendisi de olumsuz-istisnalı: لَآ إِلَٰهَ إِلَّآ أَنَا۠ *(benden başka ilâh yok)*. Aynı HASR kalıbı iki katmanda: bir kez elçilerin gönderilişi hakkında, bir kez gönderilenin sözü hakkında. Şahıs da iç içe: dış çerçeve 1P (أَرْسَلْنَا, نُوحِىٓ *(gönderdik, vahyediyoruz)*), iç söz 1S (أَنَا۠ *(ben)*), muhatap 2MP (فَٱعْبُدُونِ *(bana kulluk edin)*).",
26: "Ayet, alıntılanan cümleyi 19:88'den olduğu gibi alıp üzerine iki hamle ekliyor: سُبْحَٰنَهُۥ *(O münezzehtir)* ve بَلْ عِبَادٌۭ مُّكْرَمُونَ *(hayır, ikram edilmiş kullardır)*. İkinci hamlede iddia edilen ilişki (وَلَد *(çocuk)*) yerine başka bir ilişki konuyor: عِباد *(kullar)*. İkisi de bağ adı, biri nesep biri kulluk. مُّكْرَمُونَ *(ikram edilmişler)* ism-i mef'ûl — kul edilgen konumda kalıyor, ikramın kaynağı anılmıyor.",
27: "İki cümle bir ilişkinin iki ucu: söz ve iş. لَا يَسْبِقُونَهُۥ بِٱلْقَوْلِ *(sözle önüne geçmezler)* — olumsuz, بِٱلْقَوْلِ *(sözle)* vasıta; وَهُم بِأَمْرِهِۦ يَعْمَلُونَ *(buyruğuyla iş görürler)* — olumlu, بِأَمْرِهِۦ *(buyruğuyla)* yine vasıta. Aynı harf-i cerle iki zıt kip. سبق *(geçme, öne geçme)* olumsuzlanınca geriye yalnız takip kalıyor.",
28: "Bilgi ile eylem arasına bir izin katmanı giriyor. Bilgi tam: مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ *(önlerindekini ve arkalarındakini)* — mekân deyimiyle kurulmuş bir zaman kapsamı, ikisi de ACC zarf. Eylem ise sınırlı: وَلَا يَشْفَعُونَ إِلَّا لِمَنِ ٱرْتَضَىٰ *(razı olduğundan başkasına şefaat etmezler)*, HASR. Kapanış iki yakın kökü yan yana getiriyor: خشي *(haşyet, saygıyla korkma)* ve شفق *(şafak; işfak, içi titreyerek korkma)* — biri isim biri ism-i fâil, ikisi de aynı duygu alanında.",
29: "Şart cümlesi bir sözü suça çeviriyor: إِنِّىٓ إِلَٰهٌۭ مِّن دُونِهِۦ *(ben O'nun dışında bir ilâhım)*. Karşılık iki kez ve aynı kökle veriliyor: نَجْزِيهِ … نَجْزِى *(karşılarız… karşılarız)*, birincisi tekil-zamirli somut, ikincisi ٱلظَّٰلِمِينَ *(zalimler)* ile genel. Yani hüküm önce kişiye, sonra sınıfa yazılıyor; كَذَٰلِكَ *(işte böyle)* ikisini birbirine bağlayan tek kelime.",
30: "Ayet iki soru arasına sıkışmış bir bildirim. Çerçeve: أَوَلَمْ يَرَ *(görmediler mi)* … أَفَلَا يُؤْمِنُونَ *(hâlâ inanmazlar mı)* — ikisi de INTG, ikisi de olumsuz. İçerideki iki hapaks bir dilbilgisi karşıtlığı taşıyor: رَتْقًۭا *(bitişik)* isim ve haber, yani bir DURUM; فَفَتَقْنَٰهُمَا *(onları ayırdık)* fiil ve 1P, yani bir EYLEM. Durumun faili yok, eylemin faili var. İkinci cümle aynı kalıbı sürdürüyor: جَعَلْنَا *(kıldık)* yine 1P, ve كُلَّ شَىْءٍ حَىٍّ *(diri olan her şey)* tümleci kapsamı istisnasız yapıyor.",
31: "Üç aşamalı bir düzenleme: sabitleme (رَوَٰسِىَ *(sabit dağlar)*), sabitlemenin gerekçesi (أَن تَمِيدَ *(sarsılmasın diye)*), sonra açıklık (فِجَاجًۭا سُبُلًۭا *(geniş yollar)*). جعل *(kılma, var etme)* iki kez, her ikisinde de nesne ACC. Kapanış لَّعَلَّهُمْ يَهْتَدُونَ *(belki yollarını bulurlar)* — سبل *(yol)* ile هدي *(yol gösterme)* aynı ayette, biri somut yol biri yön bulma; yerdeki geçit ile hidayet aynı cümlede birbirine bağlanıyor.",
32: "İki ism-i mef'ûl karşı karşıya: سَقْفًۭا مَّحْفُوظًۭا *(korunmuş tavan)* — gök edilgen, korunan; ve مُعْرِضُونَ *(yüz çevirenler)* ism-i fâil — insan etken, çeviren. Nesne korunuyor, özne uzaklaşıyor. ءَايَٰتِهَا *(onun âyetleri)* zamiri سَّمَآء *(gök)*'e dönüyor, yani yüz çevrilen şey göğün kendisi değil işaretleri.",
33: "Dört ACC art arda: ٱلَّيْلَ وَٱلنَّهَارَ وَٱلشَّمْسَ وَٱلْقَمَرَ *(geceyi ve gündüzü, güneşi ve ayı)* — iki çift, birincisi süre, ikincisi cisim. Sonra tekil bir كُلٌّۭ *(her biri)* dördünü toplayıp çoğul fiile bağlıyor: يَسْبَحُونَ *(yüzerler)*. Dikkat çeken şey fiil seçimi: سبح *(tesbih, tenzih; yüzme)* kökü bu sûrede 21:20 ve 21:26'da tesbih anlamında geçmişti; burada aynı kök hareket anlamında. Aynı ses, iki iş.",
34: "Aynı kök iki kez, iki ayrı sözcük türünde: ٱلْخُلْدَ *(ölümsüzlük)* masdar ve verilmeyen şey; ٱلْخَٰلِدُونَ *(ebedî kalanlar)* ism-i fâil ve varsayılan durum. Cümle ikisini bir şartla bağlıyor: أَفَإِي۟ن مِّتَّ *(sen ölürsen)*. Yani muhatabın ölümü bir öncül, muhataplarınki bir sonuç olarak kuruluyor; ikinci yarının cevabı verilmeden bırakılıyor.",
35: "Üç cümle, üç ayrı kip: haber (ذَآئِقَةُ ٱلْمَوْتِ *(ölümü tadıcı)*, ism-i fâil — sürekli hâl), etken sınama (نَبْلُوكُم *(sizi yoklarız)* 1P), edilgen dönüş (تُرْجَعُونَ *(döndürülürsünüz)*). Sınamanın malzemesi çift ve simetrik: بِٱلشَّرِّ وَٱلْخَيْرِ *(şerle ve hayırla)* — ikisi de aynı harf-i cerle, ikisi de aynı işlevde. فِتْنَةًۭ *(bir sınama olarak)* ise ikisini birden niteliyor, yani ikisi ayrı muamele değil tek ölçüt.",
36: "İki görme, iki alay. Görme dıştan: إِذَا رَءَاكَ *(seni gördüklerinde)*; alay HASR ile sınırlanıyor: إِن يَتَّخِذُونَكَ إِلَّا هُزُوًا *(seni ancak alaya alırlar)*. Sonra iki zikir karşı karşıya: birincisi onların ağzından ve nesnesi ءَالِهَتَكُمْ *(ilâhlarınız)*, ikincisi cümlenin kendi hükmü ve nesnesi ذِكْرِ ٱلرَّحْمَٰنِ *(Rahmân'ın zikri)*. Aynı kök ذكر *(anma, zikir)*, iki karşıt yön; كفر *(inkâr, nankörlük)* de iki kez, biri özneyi tanımlıyor biri hükmü kuruyor.",
37: "خُلِقَ ٱلْإِنسَٰنُ مِنْ عَجَلٍۢ *(insan aceleden yaratıldı)* — edilgen fiil, fail anılmıyor, malzeme مِنْ *(-den)* ile veriliyor. Aynı kök ayetin sonunda bu kez muhatabın fiili olarak dönüyor: فَلَا تَسْتَعْجِلُونِ *(benden acele istemeyin)*, bab X, yani 'kendisi için isteme'. Malzeme olan şey yasaklanan davranışa dönüşüyor. Arada duran سَأُو۟رِيكُمْ ءَايَٰتِى *(size âyetlerimi göstereceğim)* geleceğe bağlanıyor (سَـ), yani yasak bir gecikmeyle karşılanıyor.",
38: "Ayet bir soru ile bir şartı üst üste koyuyor: مَتَىٰ هَٰذَا ٱلْوَعْدُ *(bu vaat ne zaman)* + إِن كُنتُمْ صَٰدِقِينَ *(doğru söyleyenlerseniz)*. Soru zamanı, şart ise muhatabın sıfatını hedefliyor; ikisi birleşince cümle bilgi istemekten çıkıp meydan okumaya dönüyor. Ayetin kendisi korpusta altı kez birebir aynı; yani kalıp bir sûreye bağlı değil, tekrarlanan bir söz biçimi.",
39: "لَوْ *(keşke, -sa)* var, cevabı yok. Şartın gövdesi ise üç olumsuzlamayla dolduruluyor: لَا يَكُفُّونَ … وَلَا … وَلَا هُمْ يُنصَرُونَ *(savamazlar… ne de… ne de yardım görürler)*. Savulamayan şey iki yönden anılıyor: وُجُوهِهِمُ *(yüzleri)* ve ظُهُورِهِمْ *(sırtları)* — ön ve arka, aynı gövdenin iki yüzü. Cümle tamamlanmadığı için üç olumsuzlama havada kalıyor; kapanışı 21:40 devralıyor.",
40: "Ayette PERF hiç yok; dört fiilin dördü de IMPF. Zaman böylece kapanmıyor. Gelişin niteliği zarfla veriliyor: بَغْتَةًۭ *(ansızın)*, ardından بغت *(ansızın gelme)* ile بهت *(şaşkına çevirme; bühtan)* yan yana — ses olarak yakın, anlamda neden-sonuç. Kapanışta iki güçsüzlük: kendi güçleri yetmiyor (لَا يَسْتَطِيعُونَ *(güç yetiremezler)*, bab X) ve dışarıdan mühlet verilmiyor (يُنظَرُونَ *(mühlet verilirler)*, edilgen). Biri içeriden biri dışarıdan kapanan iki kapı.",
}

BIYOLOG = {
30: "Ayetin çıpası üç öğe: مَآء *(su)* · حَىٍّ *(diri)* · كُلَّ شَىْءٍ *(her şey)*. Cümle diriliği tek bir maddeye bağlıyor ve كُلّ *(hep, bütün)* ile istisnasız yapıyor — yani kapsam kısmî değil. Dilbilgisi de bunu destekliyor: حَىٍّ *(diri)* sıfat olarak شَىْء *(şey)*'e bağlı, ayrı bir sınıf adı değil; diri olmak bir tür değil bir nitelik olarak kuruluyor. Ölçümde görünen şey: bu ayette حيي *(diri olma, hayat)* kökünün olağan komşuları (دنيا *(dünya)* ve موت *(ölüm)*) yok, yerinde موه *(su)* var — kökün bu ayetteki bağlamı korpustaki tipik bağlamından farklı.",
}

UZAY = {
30: "Çıpa: ٱلسَّمَٰوَٰتِ وَٱلْأَرْضَ *(gökler ve yer)* + كَانَتَا *(ikisi idi)* + رَتْقًۭا / فَتَقْنَٰهُمَا *(bitişik / onları ayırdık)*. Ayetin morfolojisi gök ile yeri TEK bir nesne gibi tutuyor: çoğul سَمَٰوَٰت *(gökler)* ile tekil أَرْض *(yer)* birleşip ikil oluyor (كَانَتَا 3FD, هُمَا *(o ikisi)* ikil zamir). Yani sayı bakımından ikiye indirgenmiş bir bütün. Anlatılan da bir DURUM değişimi: bitişiklik geçmiş zamanlı bir hâl (كَانَ *(idi)* + haber), ayrılma ise failli bir olay. Ölçüm sınırı: ayet ne zamanı ne de mekanizmayı veriyor; verdiği tek şey sıra — önce bitişik, sonra ayrık.",
}

# --- yazım ---
om = json.load(open('okuma_metni.json', encoding='utf-8'))
mk = json.load(open('mercek_kayit.json', encoding='utf-8'))

for n in range(21, 41):
    key = "21:%d" % n
    om['21'][key] = {
        'ar': AR[(21, n)],
        'meal': MEAL[n],
        'olcum': OLCUM[n],
        'mercek': MERCEK[n],
        'dikey': DIK[key],
    }
    if n in BIYOLOG: om['21'][key]['biyolog'] = BIYOLOG[n]
    if n in UZAY: om['21'][key]['uzay'] = UZAY[n]
    mk['21'].append([key, MERCEK[n]])

for n, t in BIYOLOG.items(): mk.setdefault('21_biyolog', []).append(["21:%d" % n, t])
for n, t in UZAY.items():    mk.setdefault('21_uzay', []).append(["21:%d" % n, t])

om['ilerleme']['kismi']['21'] = "1-40 ayet düzeyinde"
om['ilerleme']['bekleyen']['21'] = "41-112"
om['ilerleme']['not'] = ("Sûre 20 TAM (135/135). Sûre 21 (Enbiyâ) makro + 21:1-40. Devam: 21:41. "
                         "Dikey katman A parçası (komşuluk zenginleşmesi) birincil, B etiketsiz.")
om['ilerleme']['okunan_ayet'] = 1313
om['ilerleme']['son_oturum'] = "OTURUM_2026-08-27_KAPANIS.md"

json.dump(om, open('okuma_metni.json', 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
json.dump(mk, open('mercek_kayit.json', 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
print("yazıldı: okuma_metni 21:21-40 ·", len(mk['21']), "mercek · biyolog", len(mk['21_biyolog']), "· uzay", len(mk['21_uzay']))
