# -*- coding: utf-8 -*-
"""blok_23_81_100.py — sûre 23 beşinci blok kaydı."""
import json
DIK=json.load(open('blok_dikey_23_81_100.json',encoding='utf-8'))
veri=json.load(open('kuran_veri.json',encoding='utf-8'))
AR={}
for s in veri['sureler']:
    for a in s['ayetler']: AR[(s['no'],a['no'])]=a['ar']

MEAL={
81:"Hayır, öncekilerin söylediğinin aynısını söylediler.",
82:"Dediler ki: Ölüp toprak ve kemik olduğumuzda mı, gerçekten diriltilecek miyiz?",
83:"Andolsun, bize de daha önce atalarımıza da bu vaat edilmişti. Bu, öncekilerin masallarından başka bir şey değil.",
84:"De ki: Yer ve içindekiler kimindir, biliyorsanız?",
85:"\"Allah'ındır\" diyecekler. De ki: Düşünmez misiniz?",
86:"De ki: Yedi göğün Rabbi ve büyük arşın Rabbi kimdir?",
87:"\"Allah'ındır\" diyecekler. De ki: Sakınmaz mısınız?",
88:"De ki: Her şeyin egemenliği elinde olan, koruyan ama kendisine karşı korunulamayan kimdir, biliyorsanız?",
89:"\"Allah'ındır\" diyecekler. De ki: Öyleyse nasıl büyüleniyorsunuz?",
90:"Hayır, onlara hakkı getirdik; onlar ise yalancıdırlar.",
91:"Allah çocuk edinmedi; O'nunla birlikte başka bir ilâh da yok. Öyle olsaydı her ilâh yarattığını alıp götürür, kimi kimine üstün gelirdi. Allah, nitelendirdiklerinden yücedir.",
92:"Gaybı ve görüneni bilendir; ortak koştuklarından yücedir.",
93:"De ki: Rabbim, onlara vaat edileni bana göstereceksen —",
94:"— Rabbim, beni zalim kavmin içinde bırakma.",
95:"Onlara vaat ettiğimizi sana göstermeye elbette gücümüz yeter.",
96:"Kötülüğü en güzel olanla sav. Biz onların nitelendirdiklerini daha iyi biliriz.",
97:"De ki: Rabbim, şeytanların kışkırtmalarından sana sığınırım.",
98:"Yanımda bulunmalarından da sana sığınırım Rabbim.",
99:"Nihayet onlardan birine ölüm geldiğinde der ki: Rabbim, beni geri döndürün —",
100:"— belki geride bıraktığımda iyi bir iş yaparım. Hayır! O, onun söylediği bir sözden ibaret. Önlerinde ise diriltilecekleri güne kadar bir berzah vardır.",
}

OLCUM={
81:"eksen yok · aktör yok · edim haber · şahıs 3MP ×2 · 3MS 1 · n=6 mora=29 harf=23, fâsıla ٱلْأَوَّلُونَ *(öncekiler)* → ن, N sınıfı; i'râb ACC 1 · NOM 1; bab I ×2; zaman PERF ×2; kök ikilemesi قول *(söz söyleme)* ×2; biçim IDRAB; simetri [3,1,4,1] · yıldız ★ yok · kökler قول · مثل *(benzer, mesel)* · أول *(ilk, evvel)* · bağ: **23:24 · 23:68 · 23:81 — أول *(ilk, evvel)* sûrede üçüncü kez, üçünde de itirazın atalarla bağı** (elle, L1)",
82:"eksen yok · aktör yok · edim soru, **kip INTG ×2 — bloğun tek çift-INTG ayeti** · EMPH 1 · şahıs 1P ×5 · 3MP ×2 · n=8 mora=60 harf=41, fâsıla لَمَبْعُوثُونَ *(diriltilecek olanlar)* → ن, N sınıfı; i'râb ACC 3 · NOM 1; bab I ×3; zaman PERF ×3; edilgen 1 (pas z=1,57); dış düğüm 3 · iç düğüm 1 · yıldız ★ · kökler قول *(söz söyleme)* · موت *(ölüm)* · كون *(olmak)* · ترب *(toprak)* · عظم *(büyüklük, azamet; kemik)* · بعث *(gönderme; diriltme)* · bağ: xref كان *(oldu)* + تراب *(toprak)* + عظام *(kemikler)* → **23:35 · 37:16 · 37:53 · 56:47**; **23:35 ile sûre-içi ikiz** — orada üçüncü şahıs alay, burada birinci çoğul itiraz; fâsıla مُّخْرَجُونَ *(çıkarılacaklar)* → مَبْعُوثُونَ (elle, L1)",
83:"eksen yok · aktör yok · edim haber, kip EMPH 1 · CERT 1 · NEG 1 · RES 1 · şahıs 1P ×4 · n=12 mora=69 harf=47, fâsıla ٱلْأَوَّلِينَ *(öncekiler)* → ن, N sınıfı; i'râb NOM 2 · GEN 2; bab I ×1; zaman PERF 1; **edilgen 1 — n=12'de tek fiil ve o fiil edilgen, pas z=5,38: yıldızın tek kaynağı (aday 472)**; biçim HASR · DIKKAT; simetri [3,1,6,1]; dış düğüm 1 · yıldız ★★★ · kökler وعد *(vaat)* · أبو *(baba)* · قبل *(ön, önce; kabul)* · سطر *(satır, yazma; esâtîr (masallar))* · أول *(ilk, evvel)* · bağ: xref وعد + آباء *(atalar)* + قبل *(önce)* + أساطير *(masallar)* → **27:68 — dört ayrı 3-gram, hepsi tek ayete**",
84:"eksen yok · aktör yok · edim emir + şart, kip IMPV 1 · COND 1 · şahıs 2MP ×4 · 2MS 1 · 3FS 1 · **iltifât 1 (1>23)** · n=8 mora=37 harf=29, fâsıla تَعْلَمُونَ *(bilirsiniz)* → ن, N sınıfı; i'râb NOM 1; bab I ×3; zaman IMPV 1 · PERF 1 · IMPF 1 · yıldız ★ yok · kökler قول *(söz söyleme)* · أرض *(yer, yeryüzü)* · كون *(olmak)* · علم *(bilme)* · bağ: **23:84-89 üçlü soru-cevap nakaratının birinci sorusu**; **23:88 ile aynı şart kapanışı** إِن كُنتُمْ تَعْلَمُونَ *(biliyorsanız)* (elle, L1, aday 486)",
85:"eksen: **Allah lafzı 2. sırada — n=5'te tek lafız, allah z=3,47: yıldızın tek kaynağı (aday 472)** · aktör yok · edim soru + emir, kip FUT 1 · IMPV 1 · INTG 1 · NEG 1 · şahıs 3MP ×2 · 2MP ×2 · 2MS 1 · n=5 mora=30 harf=23, fâsıla تَذَكَّرُونَ *(düşünürsünüz)* → ن, N sınıfı; i'râb GEN 1; bab I ×2 · bab V ×1; zaman IMPF ×2 · IMPV 1; kök ikilemesi قول *(söz söyleme)* ×2 · yıldız ★★★ · kökler قول · أله *(ilâh; lafza-i celâl)* · ذكر *(anma, zikir)* · bağ: **23:87 · 23:89 ile üçlü nakarat** (aday 486); **KAYNAK NOTU (aday 487)**: korpus üç ayette de لِلَّهِ *(Allah'ındır)* okuyor; yaygın Hafs baskısında 23:87 ve 23:89 ٱللَّهُ *(Allah)* merfû okunur — DOĞRULANMADI (elle, L1)",
86:"eksen: lafız yok · **Rab İKİ geçiş — 3. ve 6. sırada; n=8'de iki Rab, rab z=5,01: SÛRENİN VE OKUMANIN EN YÜKSEK RAB YOĞUNLUĞU** · aktör yok · edim emir, kip IMPV 1 · **şahıs 2MS 1 — ayette tek şahıs** · n=8 mora=41 harf=31, **fâsıla ٱلْعَظِيمِ *(büyük)* → م — sûrenin م ile biten dört ayetinden biri**, sınıf N; i'râb GEN 4 · NOM 2; bab I ×1; zaman IMPV 1; kök ikilemesi ربب *(rab, terbiye etme)* ×2; sayı sözcüğü سَبْع *(yedi)*; **dış düğüm 4** · yıldız ★★★ · kökler قول *(söz söyleme)* · ربب · سمو *(ad; gök)* · سبع *(yedi)* · عرش *(arş, taht)* · عظم *(büyüklük, azamet; kemik)* · bağ: xref ربّ *(Rab)* + عرش *(arş)* + عظيم *(büyük)* → 9:129 · 27:26 · قال *(dedi)* + ربّ + سماء *(gök)* → 13:16 · 26:24; **23:17 ile ortak سَبْع *(yedi)*** — orada yedi yol, burada yedi gök (elle, L1)",
87:"eksen: **Allah lafzı 2. sırada — n=5'te tek lafız, allah z=3,47** · aktör yok · edim soru + emir, kip FUT 1 · IMPV 1 · INTG 1 · NEG 1 · şahıs 3MP ×2 · 2MP ×2 · 2MS 1 · n=5 mora=29 harf=22, fâsıla تَتَّقُونَ *(sakınırsınız)* → ن, N sınıfı; i'râb GEN 1; bab I ×2 · bab VIII ×1; zaman IMPF ×2 · IMPV 1; kök ikilemesi قول *(söz söyleme)* ×2; dış düğüm 1 · yıldız ★★★ · kökler قول · أله *(ilâh; lafza-i celâl)* · وقي *(sakınma, koruma)* · bağ: xref اللّه *(Allah)* + قال *(dedi)* + اتّقى *(sakındı)* → 10:31; **23:23 · 23:32 · 23:52 · 23:87 — أَفَلَا تَتَّقُونَ / فَٱتَّقُونِ kalıbı dördüncü kez**; **KAYNAK NOTU (aday 487)** geçerli (elle, L1)",
88:"eksen yok · aktör yok · edim emir + şart, kip IMPV 1 · NEG 1 · COND 1 · şahıs 3MS ×5 · 2MP ×4 · 2MS 1 · **n=14 mora=57 harf=51 — üç sorunun en uzunu**, fâsıla تَعْلَمُونَ *(bilirsiniz)* → ن, N sınıfı; i'râb GEN 3 · NOM 1; bab I ×3 · bab IV ×2; zaman IMPV 1 · IMPF ×3 · PERF 1; edilgen 1; **kök ikilemesi جور *(komşuluk; sığınak verme, koruma)* ×2 — biri etken biri edilgen (aday 489)**; dış düğüm 1 · yıldız ★ yok · kökler قول *(söz söyleme)* · يدي *(el)* · ملك *(mülk; melik)* · كلل *(hep, bütün)* · شيأ *(dileme; şey)* · جور · كون *(olmak)* · علم *(bilme)* · bağ: xref يد *(el)* + ملكوت *(egemenlik)* + كلّ *(her)* + شىء *(şey)* → **36:83**; **23:84 ile aynı şart kapanışı** (elle, L1)",
89:"eksen: **Allah lafzı 2. sırada — n=5'te tek lafız, allah z=3,47** · aktör yok · edim soru + emir, kip FUT 1 · IMPV 1 · INTG 1 · şahıs 3MP ×2 · 2MP ×2 · 2MS 1 · n=5 mora=30 harf=23, fâsıla تُسْحَرُونَ *(büyülenirsiniz)* → ن, N sınıfı; i'râb GEN 1 · ACC 1; bab I ×3; zaman IMPF ×2 · IMPV 1; **edilgen 1 — üçlünün tek edilgen kapanışı** (pas z=1,57); kök ikilemesi قول *(söz söyleme)* ×2 · yıldız ★★★ · kökler قول · أله *(ilâh; lafza-i celâl)* · سحر *(büyü, sihir)* · bağ: **23:85 · 23:87 ile üçlü nakarat kapanıyor** (aday 486); **KAYNAK NOTU (aday 487)** geçerli (elle, L1)",
90:"eksen yok · aktör yok · edim haber, kip EMPH 1 · şahıs 1P ×2 · 3MP ×2 · n=5 mora=31 harf=24, fâsıla لَكَٰذِبُونَ *(yalancılar)* → ن, N sınıfı; i'râb GEN 1 · ACC 1 · NOM 1; bab I ×1; zaman PERF 1; biçim IDRAB · yıldız ★ yok · kökler أتي *(gelme, getirme)* · حقق *(hak, gerçek)* · كذب *(yalan; yalanlama)* · bağ: **23:70 · 23:71 · 23:90 — بَلْ *(hayır)* + getirme kalıbı üçüncü kez**; nesne değişiyor: hak · kendi zikirleri · hak (elle, L1)",
91:"eksen: **Allah lafzı İKİ geçiş — 3. ve 22. sırada** (allah z=1,14); **kök ikilemesi أله *(ilâh; lafza-i celâl)* ×4 — ikisi lafız, ikisi cins isim; sûrenin en yoğun أله ayeti** · aktör yok · edim haber, kip NEG ×2 · EMPH ×2 · şahıs 3MS ×6 · 3MP ×3 · **n=24 mora=108 harf=86 — bloğun en uzun ayeti** (n z=1,23), fâsıla يَصِفُونَ *(nitelendirirler)* → ن, N sınıfı; i'râb GEN 5 · NOM 3 · ACC 2; bab I ×5 · bab VIII ×1; zaman PERF ×5 · IMPF 1; kök ikilemesi بعض *(bir kısım)* ×2; simetri [3,3,22,1]; dış düğüm 1 · yıldız ★ yok · kökler أخذ *(alma, edinme)* · أله · ولد *(doğurma, çocuk)* · كون *(olmak)* · ذهب *(gitme, götürme)* · كلل *(hep, bütün)* · خلق *(yaratma)* · علو *(yücelik; böbürlenme)* · بعض · سبح *(tesbih, tenzih)* · وصف *(niteleme, vasıf)* · bağ: xref سبحان *(tenzih)* + اللّه *(Allah)* + يصف *(nitelendirir)* → **37:159**; **23:46 ile ortak علو *(yücelik; böbürlenme)*** — orada Firavun'un kavmi, burada varsayılan ilâhlar (elle, L1)",
92:"eksen: lafız yok · **esmâ عالِم *(bilen)* 1. sırada = ayetin ilk kelimesi — GEÇERLİ**: bir önceki ayetin lafzına bağlı sıfat tamlaması; sûrenin üç geçerli esmâsından biri · aktör yok · edim haber · şahıs 3MS 1 · 3MP ×2 · n=6 mora=39 harf=29, fâsıla يُشْرِكُونَ *(ortak koşarlar)* → ن, N sınıfı; **i'râb GEN 3 — tamamı mecrur**; bab IV ×1 · bab VI ×1; zaman PERF 1 · IMPF 1 · yıldız ★ yok · kökler علم *(bilme)* · غيب *(gayb, görünmeyen)* · شهد *(şahitlik)* · علو *(yücelik; böbürlenme)* · شرك *(ortak koşma)* · bağ: **23:91 ile bitişik ikiz kapanış** — iki ayet de yücelik terimi + عَمَّا *(…den)* + üçüncü çoğul IMPF ile bitiyor (elle, L1)",
93:"eksen: lafız yok · **Rab 2. sırada, رَّبِّ *(Rabbim)* — n=6'da tek Rab, rab z=3,23** · aktör yok · edim emir + şart, kip IMPV 1 · COND 1 · EMPH 1 · şahıs 2MS ×2 · 1S ×2 · 3MP ×2 · n=6 mora=30 harf=20, fâsıla يُوعَدُونَ *(vaat edilirler)* → ن, N sınıfı; i'râb NOM 1; bab I ×2 · bab IV ×1; zaman IMPV 1 · IMPF ×2; edilgen 1 (pas z=1,57); dış düğüm 2 · yıldız ★★★ · kökler قول *(söz söyleme)* · ربب *(rab, terbiye etme)* · رأي *(görme)* · وعد *(vaat)* · bağ: xref قال *(dedi)* + ربّ *(Rab)* + أرى *(gösterdi)* → 2:260 · 7:143; **23:94 ile tek cümle**; **23:93-98 dört رَبِّ çağrısının ilki** (elle, L1, aday 488)",
94:"eksen: lafız yok · **Rab 1. sırada — ayetin İLK kelimesi; n=6'da tek Rab, rab z=3,23** · aktör yok · edim yasak, kip PRO 1 · şahıs 1S ×2 · 2MS 1 · n=6 mora=31 harf=25, fâsıla ٱلظَّٰلِمِينَ *(zalimler)* → ن, N sınıfı; i'râb NOM 1 · GEN 2; bab I ×1; zaman IMPF 1; **biçim NEHY — sûrenin üç NEHY'inden biri**; dış düğüm 2 · yıldız ★★★ · kökler ربب *(rab, terbiye etme)* · جعل *(kılma, var etme)* · قوم *(kalkma; kavim; kıyamet)* · ظلم *(zulüm)* · bağ: xref ربّ *(Rab)* + جعل *(kıldı)* + قوم *(kavim)* → 7:47 · جعل + قوم + ظالم *(zalim)* → 7:47 · 7:150; **23:28 ile ortak ٱلْقَوْمِ ٱلظَّٰلِمِينَ *(zalim kavim)*** — orada kurtuluşun hamdinde, burada korunma isteğinde (elle, L1)",
95:"eksen yok · aktör yok · edim haber, kip EMPH 1 · şahıs 1P ×3 · 2MS 1 · 3MP 1 · n=7 mora=37 harf=26, fâsıla لَقَٰدِرُونَ *(güç yetirenler)* → ن, N sınıfı; i'râb ACC 1 · NOM 1; bab I ×1 · bab IV ×1; zaman IMPF ×2 · yıldız ★ yok · kökler رأي *(görme)* · وعد *(vaat)* · قدر *(ölçü, güç yetirme)* · bağ: **23:93 ile aynı iki kök ters çatıda** — orada gösterme istenen ve vaat edilgen, burada gösterme vaat edilen ve vaat etken; **23:18 ile aynı fâsıla kelimesi** لَقَٰدِرُونَ (elle, L1)",
96:"eksen yok · aktör yok · edim emir, kip IMPV 1 · şahıs 2MS 1 · 3FS 1 · 1P 1 · 3MP ×2 · n=9 mora=43 harf=37, fâsıla يَصِفُونَ *(nitelendirirler)* → ن, N sınıfı; i'râb NOM 2 · ACC 1; bab I ×2; zaman IMPV 1 · IMPF 1 · yıldız ★ yok · kökler دفع *(savma, def etme)* · حسن *(güzellik, iyilik)* · سوأ *(kötülük)* · علم *(bilme)* · وصف *(niteleme, vasıf)* · bağ: **23:91 ile aynı fâsıla kelimesi** يَصِفُونَ, beş ayet arayla — orada tenzih formülünün nesnesi, burada bilginin nesnesi (elle, L1)",
97:"eksen: lafız yok · **Rab 2. sırada, رَّبِّ *(Rabbim)* — n=7'de tek Rab, rab z=2,72** · **aktör: adlı شَيْطان *(şeytan)* 7. sırada, tür 'gayb', rol mecrur** · edim emir, kip IMPV 1 · şahıs 2MS ×2 · 1S ×2 · n=7 mora=33 harf=24, fâsıla ٱلشَّيَٰطِينِ *(şeytanlar)* → ن, N sınıfı; i'râb NOM 1 · GEN 2; bab I ×2; zaman IMPV 1 · IMPF 1; dış düğüm 1 · yıldız ★★ · kökler قول *(söz söyleme)* · ربب *(rab, terbiye etme)* · عوذ *(sığınma)* · همز *(dürtme, kışkırtma (hemz))* · شطن *(şeytan)* · bağ: xref قال *(dedi)* + ربّ *(Rab)* + عاذ *(sığındı)* → 11:47; **23:98 ile bitişik ikiz** (elle, L1, aday 488)",
98:"eksen: lafız yok · **Rab 3. sırada, رَبِّ *(Rabbim)* — n=5'te tek Rab, rab z=3,94: yıldızın tek kaynağı (aday 472)** · aktör yok · edim haber · şahıs 1S ×3 · 3MP ×2 · 2MS 1 · **n=5 mora=22 harf=17 — bloğun en kısa ayeti**, fâsıla يَحْضُرُونِ *(yanımda bulunurlar)* → ن, N sınıfı; i'râb NOM 1; bab I ×2; zaman IMPF ×2 · yıldız ★★★ · kökler عوذ *(sığınma)* · ربب *(rab, terbiye etme)* · حضر *(hazır bulundurma)* · bağ: **23:97 ile bitişik ikiz** — aynı fiil عوذ tekrarlanıyor, Rab çağrısı cümle başından ortasına kayıyor (elle, L1, aday 488)",
99:"eksen: lafız yok · **Rab 7. sırada, رَبِّ *(Rabbim)* — rab z=2,34** · **esmâ أَحَد *(bir, biri)* 4. sırada — ÖLÇÜM ARTEFAKTI (aday 461)**: أَحَدَهُمُ *(onlardan biri)*, sayı sözcüğü; defter `say` alanında da sayıyor · aktör yok · edim emir, kip IMPV 1 · şahıs 3MS ×2 · 1S ×2 · 2MP ×2 · 3MP 1 · n=8 mora=43 harf=30, fâsıla ٱرْجِعُونِ *(beni geri döndürün)* → ن, N sınıfı; i'râb ACC 1 · NOM 2; bab I ×3; zaman PERF ×2 · IMPV 1; sayı sözcüğü أَحَد *(bir)*; dış düğüm 3 · yıldız ★★ · kökler جيأ *(gelme)* · أحد *(bir, hiç kimse)* · موت *(ölüm)* · قول *(söz söyleme)* · ربب *(rab, terbiye etme)* · رجع *(dönme, geri döndürme)* · bağ: xref أحد + موت + قال → 4:18 · 63:10 · جاء *(geldi)* + أحد + موت → 6:61; **23:64 · 23:77 · 23:99 — حَتَّىٰٓ إِذَا *(nihayet … dığında)* kalıbı üçüncü kez** (elle, L1)",
100:"eksen yok · aktör yok · edim haber · şahıs 1S ×4 · 3MP ×3 · 3FS ×2 · 3MS 1 · **n=16 mora=92 harf=68 — bloğun en uzun ikinci ayeti** (n z=0,38), fâsıla يُبْعَثُونَ *(diriltilirler)* → ن, N sınıfı; i'râb ACC 3 · NOM 3 · GEN 2; bab I ×3; zaman IMPF ×2 · PERF 1; edilgen 1 (pas z=1,57); **biçim KELLA — sûrenin TEK KELLA'sı (aday 490)**; simetri [3,4,7,1] · yıldız ★ · kökler عمل *(iş, amel)* · صلح *(iyi, elverişli olma; ıslah)* · ترك *(bırakma, terk)* · كلم *(söz, konuşma)* · قول *(söz söyleme)* · وري *(arka, öte; gizleme)* · برزخ *(berzah, iki şeyi ayıran engel)* · يوم *(gün)* · بعث *(gönderme; diriltme)* · bağ: **23:51 ile ortak عمل + صلح** — orada elçilere emir, burada geciktirilmiş dilek; **23:7 ile ortak وري** — orada sınırın ötesi, burada önlerindeki engel (elle, L1)",
}

MERCEK={
81:"Altı kelimede aynı kök iki kez ve ikisi de PERF: قَالُوا۟ *(söylediler)* ve قَالَ *(söyledi)*. Aradaki tek şey bir benzerlik terimi. Cümle bir tekrarı tekrarla anlatıyor — sözdizimi anlattığı şeyi yapıyor. مثل *(benzer, mesel)* kökü sûrede beşinci kez ve ilk dördü hep بَشَرٌ مِّثْلُكُم *(sizin gibi bir beşer)* kalıbındaydı; burada nesne kişi değil söz.",
82:"23:35'in itirazı burada ağız değiştiriyor: orada elçi hakkında konuşuluyordu (üçüncü şahıs), burada itiraz edenler kendilerini özne yapıyor — beş birinci-çoğul şahıs eki. Soru iki kez sorulmuş: أَءِذَا *(…dığımızda mı)* ve أَءِنَّا *(gerçekten biz mi)* — aynı cümlede iki INTG, blokta başka örneği yok. Maddeler aynı sırada kalıyor (toprak → kemik) ama fâsıla değişiyor: 23:35 مُّخْرَجُونَ *(çıkarılacaklar)*, burada مَبْعُوثُونَ *(diriltilecekler)*.",
83:"İtiraz iki cümleye bölünüyor ve ikisi de birinci çoğul: biri geçmişi, öteki hükmü veriyor. Fiil edilgen — وُعِدْنَا *(bize vaat edildi)*: vaat edenin adı hiç geçmiyor, on iki kelimede fâil silinmiş. İkinci cümle HASR ile bir tür indirgemesi yapıyor ve indirgenen şey bir yazı terimine: أَسَٰطِير *(masallar)*, سطر *(satır, yazma)* kökünden. Dikey ölçüm bu kelimenin bağını veriyor — سطر ▸sonra evvel ×49,7, yani kök korpusta neredeyse yalnız 'öncekilerin' tamlamasıyla görünüyor.",
84:"Üç kez tekrarlanacak bir yapı burada kuruluyor: قُلْ *(de ki)* + soru → سَيَقُولُونَ *(diyecekler)* + cevap → قُلْ + azarlayıcı soru. Birinci sorunun ekseni mülkiyet ve edatla kuruluyor: لِـ *(kimin)*. Şart cümlesi de eklenmiş — إِن كُنتُمْ تَعْلَمُونَ *(biliyorsanız)* — yani soru bilgiye koşullanıyor; üç sorudan yalnız ikisi bu koşulu taşıyor.",
85:"Cevap ölçülebilir biçimde kısa: beş kelimenin ikisi soru, ikisi emir, biri lafız. Cevabı verenler karşı taraf — sûrede ilk kez inkârcıların ağzından lafız çıkıyor. Gelecek zaman eki سَـ *(-ecek)* cevabı önceden yazıyor: soru sorulmadan cevabı biliniyor. Kapanış bir zihin fiiliyle: ذكر *(anma, zikir)* bab V.",
86:"Üç sorunun ortancası ve tek fiilsiz-cevaplı olanı: ayette yüklem yok, iki tamlama var ve ikisinin de baş kelimesi aynı — رَبّ *(Rab)*. Ölçülebilir bir genişleme: birinci soru yeri sormuştu, bu gökleri ve arşı soruyor; kapsam yerden yukarı çıkıyor. Sayı da burada: yedi. Fâsıla ن'dan م'ye kayıyor ama sınıf değişmiyor.",
87:"İkinci cevap birincinin harfi harfine aynısı, yalnız son fiil değişiyor: تَذَكَّرُونَ *(düşünürsünüz)* → تَتَّقُونَ *(sakınırsınız)*. İki fâsıla arasında ölçülebilir bir bab farkı da var — bab V ve bab VIII. Seçilen fiil sûrenin kıssa bölümüne bağlanıyor: iki elçi de çağrısını أَفَلَا تَتَّقُونَ *(sakınmaz mısınız)* ile bitirmişti (23:23, 23:32), 23:52'de aynı kök emir kipindeydi. Şimdi aynı soru muhataba doğrudan soruluyor.",
88:"Üçüncü soru kapsamı en geniş tutuyor: yer, sonra gökler ve arş, şimdi كُلِّ شَىْءٍ *(her şey)*. İlk kez soru bir sıfat cümlesiyle uzatılıyor. Asıl ölçülebilir hamle burada: aynı kök hem etken hem edilgen çatıda ve iki çatı zıt yönde — يُجِيرُ *(korur)* ve لَا يُجَارُ عَلَيْهِ *(kendisine karşı korunulmaz)*. Tek kökün iki biçimi bir asimetriyi kuruyor: koruma tek yönlü.",
89:"Üçüncü ve son cevap: kalıp aynı, ama kapanış üçünden farklı üç şey yapıyor. (1) Olumsuzlama düşüyor — ilk ikisi أَفَلَا *(…mez misiniz)* idi, bu فَأَنَّىٰ *(nasıl)*. (2) Fiil edilgene geçiyor: تُسْحَرُونَ *(büyülenirsiniz)*, üçlünün tek edilgeni. (3) Soru bir yeti değil bir hâl soruyor — düşünme ve sakınma yapılabilecek şeylerdi, büyülenme başa gelen bir şey. Dizinin sonunda muhatap özne olmaktan çıkıyor.",
90:"Soru dizisinin ardından gelen cevap üçüncü kez aynı IDRAB kalıbıyla: بَلْ *(hayır)*. Ölçülebilir bir kısalma var — 23:70 on kelime, 23:71 on altı, bu beş. Dizi daralarak bitiyor. İkinci cümle bir nitelik veriyor, olay değil: كَٰذِبُونَ *(yalancılar)*, ism-i fâil çoğulu — yalan söylemek değil, yalancı olmak.",
91:"Ayet iki olumsuzlama kurup sonra bir varsayım açıyor ve varsayımın sonucunu iki fiille ölçüyor: ذَهَبَ *(alıp götürürdü)* ve عَلَا *(üstün gelirdi)* — biri ayrılma, öteki hiyerarşi. Çokluk varsayımı iki ayrı biçimde bozuluyor: parçalanma ve sıralanma. أله *(ilâh; lafza-i celâl)* kökü dört kez ve dağılım ölçülebilir: iki kez özel ad (baş ve son), iki kez cins isim (ortada). Kapanış bir tenzih formülü ve nesnesi yine söz: عَمَّا يَصِفُونَ *(nitelendirdiklerinden)*.",
92:"Ayet bir önceki ayetin son kelimesine dilbilgisel olarak bağlı: عَٰلِمِ *(bilen)* mecrur, çünkü lafza sıfat. Altı kelimenin üçü mecrur ve ayet kendi başına cümle kurmuyor. İki karşıt terim tek tamlamada: غَيْب *(görünmeyen)* ve شَهَٰدَة *(görünen)* — bilme alanı iki uçla tanımlanıyor. Kapanış علو *(yücelik; böbürlenme)* kökünden bab VI, yani 23:91'in عَلَا *(üstün geldi)* bab I'inin karşıtı: orada varsayılan ilâhların birbirine üstünlüğü, burada tek tarafın aşkınlığı.",
93:"Sûrede dördüncü kez bir ağızdan رَبِّ *(Rabbim)* çağrısı geliyor ama bu kez muhatap adlandırılmış elçi değil, doğrudan hitap edilen kişi ve önünde قُلْ *(de ki)* var. Dua önce yazılıyor, sonra söyleniyor. Şart edatı pekiştirilmiş: إِمَّا *(eğer … ise)*, üstüne fiile te'kid nûnu eklenmiş (تُرِيَنِّى *(bana gösterirsen)*). Cümle kendi ayetinde kapanmıyor.",
94:"Şartın cevabı ve ölçülebilir biçimde tuhaf: şart 'göstereceksen' idi, cevap 'gösterme' değil 'beni onların içinde bırakma'. Cevap şartın konusunu değil, şart gerçekleştiğinde konuşanın konumunu düzenliyor. Çağrı ikinci kez tekrarlanıyor — 23:93'te ikinci kelime, burada birinci. Yasak جعل *(kılma, var etme)* fiiliyle: istenmeyen şey bir eylem değil bir yerleştirme.",
95:"İki ayet arayla aynı iki kök geri geliyor ve iki yerde de çatı tersine dönüyor: dua tarafında gösterme istenen ve vaat edilgen; cevap tarafında gösterme vaat edilen ve vaat etken. Duanın dilbilgisi cevapta aynalanıyor. Fâsıla sûrede ikinci kez لَقَٰدِرُونَ *(güç yetirenler)* — ilki 23:18'de suyun giderilmesi bağlamındaydı; iki yerde de aynı kelime bir yetiyi kapanışa koyuyor.",
96:"Emir bir yer değiştirme kuruyor: kötülük savılacak ama savma aracı yine bir nitelik, kötülüğün cinsinden değil — أَحْسَنُ *(en güzel olan)*, üstünlük ismi. İki üstünlük ismi aynı ayette: أَحْسَنُ ve أَعْلَمُ *(daha iyi bilen)*; biri muhataba verilen araç, öteki konuşanın niteliği. سوأ *(kötülük)* ile حسن *(güzellik, iyilik)* karşıtlığı doğrudan i'râbla ayrılıyor: biri mansûb nesne, öteki mecrur araç.",
97:"İkinci dua bloğu ve yapı birincinin aynısı: قُلْ *(de ki)* + رَبِّ *(Rabbim)* + istek. Ama istek yönü değişiyor — birincisi gelecekteki bir olay hakkındaydı, bu şimdiki bir tehdit hakkında. هَمَزَٰت *(kışkırtmalar)* çoğul: tehdit tek bir olay değil, yinelenen dürtüler olarak adlandırılıyor. Dikey ölçüm عوذ *(sığınma)* kökünün komşuluğunda ilk sırada نزغ *(dürtme, vesvese)* ×281,6 veriyor — sığınma fiili korpusta neredeyse hep bir dürtme terimiyle eşleşiyor.",
98:"İki sığınma isteği arasındaki fark yalnız nesnede değil, konumda: 23:97'de رَبِّ *(Rabbim)* ikinci kelime ve isteğin önünde, burada üçüncü ve isteğin ortasında — çağrı cümlenin içine gömülüyor. Nesne de değişiyor: orada kışkırtma (bir eylem), burada حُضُور *(yanında bulunma)*, yani varlık. Tehdit eylemden mevcudiyete kayıyor ve fiil sûrenin en kısa ayetlerinden birinde bunu tek kelimeyle veriyor.",
99:"Üçüncü ve son حَتَّىٰٓ إِذَا *(nihayet … dığında)* eşiği. İlk ikisi topluluk hakkındaydı (23:64 azap, 23:77 kapı), bu tek kişiye iniyor: أَحَدَهُم *(onlardan biri)*. Ölçülebilir bir şahıs uyumsuzluğu var: çağrı tekil (رَبِّ *(Rabbim)*) ama emir çoğul (ٱرْجِعُونِ *(beni döndürün)*) — tek muhataba çoğul fiille sesleniliyor. رجع *(dönme, geri döndürme)* kökü sûrede üçüncü kez ve ilk ikisi mü'minlerin dönüşüydü; burada geri dönme isteği.",
100:"İstek ve reddi aynı ayette ve red tek kelimeyle: كَلَّآ *(hayır)* — sûrenin tek KELLA'sı, 118 ayette bir kez. Reddin gerekçesi ölçülebilir biçimde dil üzerinden veriliyor: كَلِمَةٌ هُوَ قَآئِلُهَا *(onun söylediği bir söz)* — istek eylem olarak değil, söz olarak sınıflanıyor ve söyleyeni ism-i fâille işaretleniyor. Kapanış bir engel terimiyle: بَرْزَخ *(iki şeyi ayıran engel)*, korpusta üç geçişli. Yön kelimesi de ters: وَرَآئِهِم *(önlerinde / arkalarında)*, وري *(arka, öte; gizleme)* kökü — aynı kelime 23:7'de sınırın ötesini adlandırıyordu.",
}

ATLAMA={
 "23:83":"★★★ ayet. 🜁 biyolog YAZILMADI — beş kökün hiçbiri (وعد *(vaat)* · أبو *(baba)* · قبل *(önce)* · سطر *(yazı)* · أول *(evvel)*) canlıya, organa ya da sürece bağlanmıyor; أبو burada soy değil gelenek zinciri olarak kullanılıyor. 🜂 uzay YAZILMADI — gök öğesi, cisim adı ya da zaman ölçüsü terimi yok.",
 "23:85":"★★★ ayet. 🜁 biyolog ve 🜂 uzay YAZILMADI — üç kök (قول *(söz söyleme)* · أله *(lafza-i celâl)* · ذكر *(zikir)*) hiçbir çıpa vermiyor. NOT: 23:84'ün أرض *(yer, yeryüzü)* çıpası KOMŞU ayette, bu ayette değil.",
 "23:86":"★★★ ayet. 🜁 biyolog YAZILMADI — عظم *(büyüklük, azamet; kemik)* kökü korpusta 'kemik' işlevi de taşıyor ama burada ٱلْعَرْشِ ٱلْعَظِيمِ *(büyük arş)* tamlamasında sıfat, gönderge açık; anatomik okuma yasaklı 'bilimsel izdüşüm' olurdu. 🜂 uzay YAZILDI — çıpa ٱلسَّمَٰوَٰتِ ٱلسَّبْعِ *(yedi gök)*, kök سمو *(ad; gök)* + sayı sözcüğü سَبْع *(yedi)*. Mercek satırı yalnız ölçülebilir olanla sınırlı tutuldu: gök sayılmış bir çokluk olarak veriliyor, sayı marife tamlamada sıfat konumunda, aynı kök çifti 23:17'de طَرَآئِق *(yollar)* ile eşleşiyor. Ayet gök cismi, hareket, yörünge ya da ölçü terimi VERMİYOR; sayının neye karşılık geldiği metinden çıkarılamaz ve fiziksel katman modeli kurulmadı.",
 "23:87":"★★★ ayet. 🜁 biyolog ve 🜂 uzay YAZILMADI — üç kök (قول · أله · وقي *(sakınma, koruma)*) çıpa vermiyor; gök çıpası bir önceki ayette (23:86), bu ayette değil.",
 "23:89":"★★★ ayet. 🜁 biyolog ve 🜂 uzay YAZILMADI — üç kök (قول · أله · سحر *(büyü, sihir)*) hiçbir biyolojik ya da astronomik öğe taşımıyor.",
 "23:93":"★★★ ayet. 🜁 biyolog YAZILMADI — رأي *(görme)* burada bab IV ettirgen ve nesnesi bir olay; duyu organı adlandırılmıyor. 🜂 uzay YAZILMADI — gök öğesi ya da zaman ölçüsü yok.",
 "23:94":"★★★ ayet. 🜁 biyolog ve 🜂 uzay YAZILMADI — dört kök (ربب *(rab)* · جعل *(kılma)* · قوم *(kavim)* · ظلم *(zulüm)*) çıpa vermiyor; فِى ٱلْقَوْمِ *(kavmin içinde)* topluluk, mekân değil.",
 "23:98":"★★★ ayet. 🜁 biyolog ve 🜂 uzay YAZILMADI — üç kök (عوذ *(sığınma)* · ربب *(rab)* · حضر *(hazır bulundurma)*) çıpa vermiyor; حضر mekân değil bulunuş bildiriyor.",
 "_blok_notu_81_100":"Blok 23:81-100'de YEDİ ★★★ ayet var (83, 85, 86, 87, 89, 93, 94, 98 = sekiz). Bunlardan YALNIZ BİRİNDE (23:86) bir uzman merceği yazılabildi — 🜂 uzay, çıpası ٱلسَّمَٰوَٰتِ ٱلسَّبْعِ *(yedi gök)*. Sûre 23'te bugüne dek okunan 100 ayetin on beş ★★★'ından on dördünde iki mercek de atlandı; ilk mercek 23:86'da yazıldı. Biyolog merceği sûrede HÂLÂ HİÇ yazılmadı — 23:12-14'ün yaratılış zinciri ★ almamıştı (adaylar 468, 472).",
}

p='/home/claude/repo/notlar/okuma_metni.json'
OM=json.load(open(p,encoding='utf-8'))
for n in range(81,101):
    OM['23']["23:%d"%n]={"ar":AR[(23,n)],"meal":MEAL[n],"olcum":OLCUM[n],
                         "mercek":MERCEK[n],"dikey":DIK["23:%d"%n]}
OM['23']['_mercek_atlama_notu'].update(ATLAMA)
OM['ilerleme']['not']=("Sûre 22 TAM (78/78). Sûre 23 (Mü'minûn) makro profil + 23:1-100 okundu. "
                       "Devam: 23:101. Sûrede 18 ayet kaldı.")
OM['ilerleme']['kismi']={"2":"1-20 ayet düzeyinde","23":"1-100 ayet düzeyinde"}
OM['ilerleme']['okunan_ayet']=1563
json.dump(OM,open(p,'w',encoding='utf-8'),ensure_ascii=False,indent=1)
print('okuma_metni: sûre 23 →',len([k for k in OM['23'] if not k.startswith('_')]),'ayet')

pm='/home/claude/repo/notlar/mercek_kayit.json'
MK=json.load(open(pm,encoding='utf-8'))
for n in range(81,101): MK['23']["23:%d"%n]=MERCEK[n]
MK['23_atlama'].update(ATLAMA)
json.dump(MK,open(pm,'w',encoding='utf-8'),ensure_ascii=False,indent=1)
print('mercek_kayit: sûre 23 →',len(MK['23']),'mercek')
