# -*- coding: utf-8 -*-
"""blok_24_31_40.py — sûre 24 blok 24:31-40 (Nûr âyeti dâhil)."""
import json
DIK=json.load(open('blok_dikey_24_21_40.json',encoding='utf-8'))
veri=json.load(open('kuran_veri.json',encoding='utf-8'))
AR={}
for s in veri['sureler']:
    for a in s['ayetler']: AR[(s['no'],a['no'])]=a['ar']

MEAL={
31:"Mü'min kadınlara da söyle: bakışlarını indirsinler, ırzlarını korusunlar, kendiliğinden görünen dışında süslerini açığa vurmasınlar; başörtülerini yakalarının üzerine salsınlar. Süslerini kocaları, babaları, kocalarının babaları, oğulları, kocalarının oğulları, kardeşleri, kardeşlerinin oğulları, kız kardeşlerinin oğulları, kendi kadınları, ellerinin altındakiler, erkeklerden şehvet duymayan hizmetliler ve kadınların mahremini henüz bilmeyen çocuklar dışında kimseye açmasınlar. Gizledikleri süsleri bilinsin diye ayaklarını yere vurmasınlar. Ey mü'minler, hep birlikte Allah'a dönün ki kurtuluşa eresiniz.",
32:"İçinizden eşsiz olanları ve kölelerinizden, câriyelerinizden elverişli olanları evlendirin. Yoksul iseler Allah onları lütfundan zenginleştirir. Allah geniştir, bilendir.",
33:"Evlenmeye imkân bulamayanlar, Allah lütfundan zenginleştirinceye kadar iffetli kalsınlar. Ellerinizin altındakilerden özgürlük sözleşmesi isteyenlerle, onlarda bir hayır biliyorsanız sözleşme yapın ve Allah'ın size verdiği maldan onlara verin. Câriyelerinizi, iffetli kalmak isterlerken dünya hayatının geçici kazancını arayarak fuhşa zorlamayın. Kim onları zorlarsa, Allah zorlanmalarının ardından bağışlayandır, merhamet edendir.",
34:"Andolsun, size açıklayıcı âyetler, sizden önce gelip geçenlerden bir örnek ve sakınanlar için bir öğüt indirdik.",
35:"Allah göklerin ve yerin nûrudur. O'nun nûrunun örneği, içinde kandil bulunan bir yuva gibidir; kandil bir cam içindedir, cam sanki inci gibi parlayan bir yıldızdır. Doğuya da batıya da ait olmayan bereketli bir zeytin ağacından tutuşturulur; yağı, ateş değmese bile neredeyse ışık verecek. Nûr üstüne nûr. Allah dilediğini nûruna eriştirir. Allah insanlara örnekler verir. Allah her şeyi bilendir.",
36:"Allah'ın yükseltilmesine ve içlerinde adının anılmasına izin verdiği evlerde; sabah akşam O'nu tesbih eden…",
37:"— öyle adamlar ki ne ticaret ne alışveriş onları Allah'ı anmaktan, namazı kılmaktan, zekâtı vermekten alıkoyar. Kalplerin ve gözlerin döneceği bir günden korkarlar.",
38:"Allah onlara yaptıklarının en güzeliyle karşılık versin ve lütfundan artırsın diye. Allah dilediğine hesapsız rızık verir.",
39:"İnkâr edenlerin amelleri, düz bir arazideki serap gibidir; susamış kimse onu su sanır, yanına vardığında hiçbir şey bulamaz; Allah'ı ise yanında bulur ve O hesabını tam olarak görür. Allah hesabı çabuk görendir.",
40:"Ya da engin bir denizdeki karanlıklar gibidir: üstünü bir dalga, onun üstünü başka bir dalga, onun üstünü de bulut örter. Karanlıklar üst üste. Elini çıkarsa neredeyse göremez. Allah kime nûr vermemişse, onun için nûr yoktur.",
}

OLCUM={
31:"eksen: **Allah lafzı 73. sırada — n=78'de tek lafız, allah z=−0,27** · **esmâ مُؤْمِن *(mü'min)* 76. sırada — ÖLÇÜM ARTEFAKTI (aday 461)** · aktör yok · edim emir + yasak, kip IMPV ×3 · PRO ×3 · RES ×2 · NEG 1 · **şahıs 3FP ×32 — okumada görülen en yoğun dişil çoğul** · 2MP ×5 · 2MS 1 · 3MS ×2 · 3FS ×2 · 3MP ×2 · **n=78 mora=443 harf=351 — SÛRENİN VE OKUMANIN EN UZUN AYETİ** (n z=6,96: yıldızın tek kaynağı, adaylar 472/503), fâsıla تُفْلِحُونَ *(kurtuluşa erersiniz)* → ن, N sınıfı; **i'râb GEN 28 · ACC 6 · NOM 2**; bab I ×10 · bab IV ×4; zaman IMPV ×2 · IMPF ×10 · PERF ×2; **kök ikilemesi on bir kök birden: أمن *(güven; iman)* ×2 · بدو *(açığa çıkma, görünme)* ×2 · زين *(süsleme)* ×3 · ظهر *(sırt; zuhur, açığa çıkma)* ×2 · ضرب *(vurma; mesel getirme)* ×2 · بعل *(koca; Baʼl)* ×3 · أبو *(baba)* ×2 · بني *(bina, yapma; evlat)* ×4 · أخو *(kardeş)* ×3 · نسو *(kadınlar)* ×2 · رجل *(adam; yaya)* ×2**; biçim HASR · NEHY · DIKKAT; simetri [7,11,57,2]; dış düğüm 2 · yıldız ★★★ · kökler قول *(söz söyleme)* · أمن · غضض *(indirme, kısma)* · بصر *(görme)* · حفظ *(koruma)* · فرج *(ırz; yarık, aralık)* · بدو · زين · ظهر · ضرب · خمر *(şarap, örtü)* · جيب *(yaka, göğüs yarığı)* · بعل · أبو · بني · أخو · نسو · ملك *(mülk; melik)* · يمن *(sağ el, sağ yan)* · تبع *(uyma, ardından gitme)* · غير *(başka)* · أرب *(ihtiyaç, gereksinim)* · رجل · طفل *(çocuk, bebek)* · عور *(mahrem yer, avret; gedik)* · علم *(bilme)* · خفي *(gizleme, gizli olan)* · توب *(tevbe, dönüş)* · أله *(ilâh; lafza-i celâl)* · جمع *(toplama)* · أيي *(âyet, işaret; hangi)* · فلح *(kurtuluşa erme, felâh)* · bağ: xref نساء *(kadınlar)* + ملكت *(sahip oldu)* + يمين *(sağ el)* → **4:24 · 33:55**; **24:30 ile ikiz açılış** — ilk üç buyruk aynı kök ve aynı sırada (elle, L1, aday 506)",
32:"eksen: **Allah lafzı 12. ve 15. sırada — n=17'de İKİ lafız, allah z=1,82** · **esmâ واسِع *(vâsiʼ)* 16. + عَلِيم *(alîm)* 17. sırada — MÜHÜR, çift kapanış; GEÇERLİ** · aktör yok · edim emir + şart, kip IMPV 1 · COND 1 · şahıs 2MP ×5 · 3MP ×3 · 3MS ×2 · n=17 mora=100 harf=86, **fâsıla عَلِيمٌۭ → م**, N sınıfı; i'râb ACC 3 · GEN 3 · NOM 4; bab I ×1 · bab IV ×2; zaman IMPV 1 · IMPF ×2; kök ikilemesi أله *(ilâh; lafza-i celâl)* ×2; **hapaks: أيم *(eşsiz, dul ya da bekâr (eyyim))* — korpusta TEK geçiş, hapaks z=3,38: yıldızın tek kaynağı**; **dış düğüm 4** · iç düğüm 1 · yıldız ★★★ · kökler نكح *(nikâh, evlenme)* · أيم · صلح *(iyi, elverişli olma; ıslah)* · عبد *(kul, kulluk)* · أمو *(câriye, hizmetçi kadın (eme))* · كون *(olmak)* · فقر *(fakirlik)* · غني *(zenginlik, ganî olma)* · أله · فضل *(üstün kılma, lütuf)* · وسع *(genişlik, kuşatma)* · علم *(bilme)* · bağ: xref فضل *(lütuf)* + اللّه *(Allah)* + واسع *(geniş)* → 2:268 · أغنت *(zenginleştirdi)* + اللّه + فضل → **9:28 ve 24:33** (elle, L1)",
33:"eksen: **Allah lafzı 8., 25. ve 43. sırada — üç geçiş** (allah z=0,72) · **esmâ غَفُور *(gafûr)* 47. + رَحِيم *(rahîm)* 48. sırada — MÜHÜR, çift kapanış; GEÇERLİ** · aktör yok · edim emir + yasak + şart, kip IMPV ×3 · NEG 1 · COND ×2 · PRO 1 · şahıs 3MS ×5 · 3MP ×8 · 3FS 1 · 2MP ×13 · 3FP ×4 · **n=48 mora=279 harf=227** (n z=3,78: yıldızın tek kaynağı), **fâsıla رَّحِيمٌۭ → م**, N sınıfı; i'râb ACC 7 · NOM 4 · GEN 9; **bab I ×3 · III ×1 · IV ×6 · VIII ×2 · X ×1 — altı ayrı bab**; zaman IMPF ×7 · PERF ×4 · IMPV ×2; kök ikilemesi أله ×3 · بغي *(iffetsizlik; azgınlık; arama)* ×3 · كتب *(yazma, kitap)* ×2 · أتي *(gelme, getirme)* ×2 · كره *(zorlama; hoşlanmama)* ×3; biçim NEHY; simetri [6,6,23,2]; dış düğüm 2 · iç düğüm 1 · yıldız ★★★ · kökler عفف *(iffet, sakınma)* · وجد *(bulma)* · نكح *(nikâh, evlenme)* · غني *(zenginlik, ganî olma)* · أله *(ilâh; lafza-i celâl)* · فضل *(üstün kılma, lütuf)* · بغي · كتب · ملك *(mülk; melik)* · يمن *(sağ el, sağ yan)* · علم *(bilme)* · خير *(hayır, daha iyi)* · أتي · مول *(mal)* · كره · فتي *(genç, delikanlı; fetva)* · رود *(isteme, dileme)* · حصن *(koruma, sağlamlaştırma; iffet)* · عرض *(sunma; yüz çevirme)* · حيي *(diri olma, hayat)* · دنو *(yakınlık; dünya)* · بعد *(sonra; uzaklık)* · غفر *(bağışlama, mağfiret)* · رحم *(rahmet, merhamet)* · bağ: xref أغنت + اللّه + فضل → **9:28 ve 24:32** — bir önceki ayetle aynı üçlü; xref ابتغى *(aradı)* + عرض *(dünyalık)* + حياة *(hayat)* → 4:94 (elle, L1)",
34:"eksen: lafız yok · aktör yok · edim haber, kip EMPH 1 · CERT 1 · şahıs 1P ×2 · 2MP ×2 · 3MP ×2 · n=13 mora=84 harf=65, fâsıla لِّلْمُتَّقِينَ *(sakınanlar için)* → ن, N sınıfı; i'râb ACC 4 · GEN 2; bab I ×1 · bab IV ×1; zaman PERF ×2; simetri [3,1,8,1]; dış düğüm 1 · yıldız ★ yok · kökler نزل *(inme, indirme)* · أيي *(âyet, işaret)* · بين *(arası; açıklama)* · مثل *(benzer, mesel)* · خلو *(boş kalma, baş başa kalma)* · قبل *(ön, önce; kabul)* · وعظ *(öğüt, vaʼz)* · وقي *(sakınma, koruma)* · bağ: xref مثل *(mesel)* + خلا *(geçip gitti)* + قبل *(önce)* → 2:214; **24:1 · 24:18 · 24:34 — نزل + أيي + بين üçlüsü üçüncü kez, âyetlerin konumu açık → açıklanan → açıklayan** (elle, L1, aday 507)",
35:"eksen: **Allah lafzı 1., 37., 42. ve 45. sırada — DÖRT geçiş, ayet lafızla açılıyor** (allah z=1,14) · **esmâ نُور *(nûr)* 2., 6., 33., 35. ve 38. sırada — BEŞ TOKEN; ÖLÇÜM ARTEFAKTI VE SINIR VAKASI (adaylar 461, 508)**: ilk geçiş (نُورُ ٱلسَّمَٰوَٰتِ *(göklerin nûru)*) doğrudan lafzın yüklemi ve geçerli sayılabilir; kalan dördü iyelikli tamlama ya da NEKRE — ölçüt (b) gereği esmâ sayılamaz. Ayrıca **esmâ عَلِيم *(alîm)* 48. sırada = fâsıla — GEÇERLİ** · aktör yok · edim şart, kip NEG ×3 · COND 1 · şahıs 3MS ×9 · 3FS ×4 · **n=48 mora=265 harf=220** (n z=3,78: yıldızın tek kaynağı), **fâsıla عَلِيمٌۭ → م**, N sınıfı; **i'râb NOM 15 · GEN 15 · ACC 2**; bab I ×5 · bab IV ×2; **zaman IMPF ×7 — yedi fiilin yedisi de muzâri, tek PERF yok**; edilgen 1 (pas z=0,48); **kök ikilemesi أله ×4 · نور *(nûr, ışık)* ×6 · مثل *(benzer, mesel)* ×2 · صبح *(sabah; kandil)* ×2 · زجج *(cam, sırça)* ×2 · زيت *(zeytin, zeytinyağı)* ×2 · شيأ *(dileme; şey)* ×2**; simetri [3,1,37,1]; dış düğüm 2 · yıldız ★★★ · kökler أله *(ilâh; lafza-i celâl)* · نور · سمو *(ad; gök)* · أرض *(yer, yeryüzü)* · مثل · شكو *(şikâyet; kandil yuvası (mişkât))* · صبح · زجج · كوكب *(yıldız (kevkeb))* · درر *(inci gibi parlama; bol yağan)* · وقد *(tutuşturma)* · شجر *(ağaç)* · برك *(bereket)* · زيت · شرق *(doğu, tan)* · غرب *(batma (güneş))* · كود *(neredeyse olma)* · ضوأ *(ışık, aydınlık)* · مسس *(dokunma, temas)* · هدي *(yol gösterme)* · شيأ · ضرب *(vurma; mesel getirme)* · أنس *(insan)* · كلل *(hep, bütün)* · علم *(bilme)* · bağ: xref اللّه *(Allah)* + مثل + ناس *(insanlar)* → 14:25 · سماء *(gök)* + أرض *(yer)* + مثل → 65:12; **24:40 ile karşıt mesel çifti** (elle, L1, aday 510)",
36:"eksen: **Allah lafzı 4. sırada** (allah z=0,90) · aktör yok · edim haber · şahıs 3MS ×5 · 3FS ×3 · n=14 mora=69 harf=58, **fâsıla ٱلْءَاصَالِ *(akşam vakitleri)* → ل, ل sınıfı — SÛRENİN TEK ل FÂSILALI AYETİ ve N-koşusunun ilk kırılması (aday 509)**; i'râb GEN 3 · NOM 2; bab I ×3 · bab II ×1; zaman PERF 1 · IMPF ×3; **edilgen 2 — pas z=2,52** · yıldız ★★ · kökler بيت *(ev, mesken)* · أذن *(izin verme; kulak)* · أله *(ilâh; lafza-i celâl)* · رفع *(yükseltme)* · ذكر *(anma, zikir)* · سمو *(ad; gök)* · سبح *(tesbih, tenzih)* · غدو *(sabah; azık)* · أصل *(kök, asıl; akşamüstü (asîl))* · bağ: **24:27-29 · 24:36 — بيت *(ev)* kökü sûrenin en zengin kökü (×11,21), burada beşinci geçişi; ev artık yasak konusu değil, tesbih yeri** (elle, L1)",
37:"eksen: **Allah lafzı 9. sırada** (allah z=0,52) · **aktör: adsız racül *(bir adam)* 1. sırada** · edim haber, kip NEG ×2 · şahıs 3FS ×2 · 3MP ×3 · 3MS 1 · n=19 mora=114 harf=89, **fâsıla ٱلْأَبْصَٰرُ *(gözler)* → ر, R sınıfı**; i'râb NOM 5 · GEN 6 · ACC 1; bab I ×1 · bab IV ×1 · bab V ×1; zaman IMPF ×3; kök ikilemesi قلب *(çevirme; kalp)* ×2 — biri fiil biri isim; dış düğüm 1 · yıldız ★ yok · kökler رجل *(adam; yaya)* · لهو *(oyalanma, eğlence)* · تجر *(ticaret)* · بيع *(alışveriş; kilise, biya)* · ذكر *(anma, zikir)* · أله *(ilâh; lafza-i celâl)* · قوم *(kalkma; kavim; kıyamet)* · صلو *(namaz, salât)* · أتي *(gelme, getirme)* · زكو *(arınma, temizlik)* · خوف *(korku)* · يوم *(gün)* · قلب · بصر *(görme)* · bağ: xref إقام *(ikame)* + صلاة *(namaz)* + إيتاء *(verme)* + زكاة *(zekât)* → **21:73**; **23:4 ile karşıt örnek** — orada زكو + فعل *(yapma)* eşleşmesi korpusta tekti (aday 471), burada olağan إيتاء kalıbı (elle, L1)",
38:"eksen: **Allah lafzı 2. ve 9. sırada — n=14'te İKİ lafız, allah z=2,33** · aktör yok · edim haber · şahıs 3MS ×5 · 3MP ×4 · n=14 mora=70 harf=62, **fâsıla حِسَابٍۢ → ب, ب sınıfı**; i'râb NOM 2 · ACC 1 · GEN 3; **bab I ×5**; zaman IMPF ×4 · PERF 1; kök ikilemesi أله *(ilâh; lafza-i celâl)* ×2; simetri [3,2,9,1]; **dış düğüm 4** · yıldız ★★ · kökler جزي *(karşılık verme)* · أله · حسن *(güzellik, iyilik)* · عمل *(iş, amel)* · زيد *(artırma)* · فضل *(üstün kılma, lütuf)* · رزق *(rızık)* · شيأ *(dileme; şey)* · غير *(başka)* · حسب *(hesap, sayma)* · bağ: xref اللّه + رزق *(rızık verir)* + شاء *(diledi)* → **2:212 · 3:37**; جزى *(karşılık verdi)* + اللّه + أحسن *(en güzel)* → 9:121",
39:"eksen: **Allah lafzı 16. ve 20. sırada — iki geçiş** (allah z=1,29) · aktör yok · edim haber, kip NEG 1 · şahıs 3MP ×3 · 3MS ×11 · n=22 mora=131 harf=107 (n z=1,02), **fâsıla ٱلْحِسَابِ *(hesap)* → ب, ب sınıfı**; i'râb NOM 4 · GEN 3 · ACC 5; bab I ×5 · bab II ×1; zaman PERF ×4 · IMPF ×2; **kök ikilemesi حسب *(hesap, sayma)* ×3 — biri 'sanma', ikisi 'hesap'; وجد *(bulma)* ×2 · أله ×2** · yıldız ★ yok · kökler كفر *(inkâr, nankörlük)* · عمل *(iş, amel)* · سرب *(yol alma; serap; yeraltı geçidi)* · قوع *(düz arazi, çukursuz yer)* · حسب · ظمأ *(susama)* · موه *(su)* · جيأ *(gelme)* · وجد · شيأ *(dileme; şey)* · أله *(ilâh; lafza-i celâl)* · عند *(kat, yan)* · وفي *(tam verme, vefa; vefat ettirme)* · سرع *(hız, sürat)* · bağ: **24:35 ve 24:40 ile üçlü mesel dizisi** — nûr, serap, karanlık (elle, L1, aday 510)",
40:"eksen: **Allah lafzı 27. sırada** (allah z=0,08) · **esmâ نُور *(nûr)* 29. ve 33. sırada — ÖLÇÜM ARTEFAKTI (adaylar 461, 508)**: ikisi de NEKRE ve olumsuzlanmış bir verilişin nesnesi; ölçüt (b) nekre biçimi dışlıyor · aktör yok · edim haber, kip NEG ×3 · şahıs 3MS ×11 · 3FS ×2 · **n=33 mora=140 harf=121** (n z=2,19), **fâsıla نُّورٍ → ر, R sınıfı**; i'râb GEN 7 · NOM 6 · ACC 3; bab I ×4 · bab IV ×1; zaman IMPF ×4 · PERF 1; **kök ikilemesi ظلم *(zulüm; karanlık)* ×2 · موج *(dalga)* ×2 · فوق *(üst, üstünde)* ×3 · بعض *(bir kısım)* ×2 · نور ×2**; simetri [3,1,28,1]; **dış düğüm 4** · yıldız ★★ · kökler ظلم · بحر *(deniz)* · لجج *(derin su, engin; direnip dalma)* · غشو *(bürüme, kaplama)* · موج · فوق · سحب *(bulut; sürükleme)* · بعض · خرج *(çıkma, çıkarma)* · يدي *(el)* · كود *(neredeyse olma)* · رأي *(görme)* · جعل *(kılma, var etme)* · أله *(ilâh; lafza-i celâl)* · نور · bağ: xref بعض + فوق + بعض → 6:165 · 43:32; **24:35 ile tam karşıtlık** — orada iç içe ışık zinciri, burada üst üste karanlık zinciri; ikisi de نور köküyle kapanıyor (elle, L1, aday 510)",
}

MERCEK={
31:"Okumanın en uzun ayeti ve ölçüm katmanlarının çoğu burada uçlarda. İlk üç buyruk 24:30'un birebir dişil karşılığı: غضض *(indirme, kısma)* + بصر *(görme)* + حفظ *(koruma)* + فرج *(ırz; yarık, aralık)*, aynı sırada. Sonrasında ayet tek bir sözdizimsel işleme dönüyor: on bir üyeli bir istisna listesi, ve liste akrabalık terimleriyle örülü — بعل *(koca; Baʼl)* üç kez, بني *(evlat)* dört kez, أخو *(kardeş)* üç kez, أبو *(baba)* iki kez. Ölçülebilir sonuç: yetmiş sekiz kelimede yirmi sekiz mecrur isim; ayet dilbilgisel olarak bir tamlama zinciri. Kapanış şahsı çeviriyor — otuz iki dişil çoğul ekten sonra son üç kelime eril çoğula geçiyor, ama iltifât işaretlenmiyor. عور *(mahrem yer, avret)* korpusta dört, أرب *(ihtiyaç, gereksinim)* iki, جيب *(yaka, göğüs yarığı)* üç geçişli — üç seyrek kök tek ayette.",
32:"Sûrenin dört hapaksından ilki ve konumu erken: ٱلْأَيَٰمَىٰ *(eşsizler)* ayetin ikinci kelimesi. Kök korpusta tek geçişli, dolayısıyla dikey komşuluğu boş. Ayet bir karşıt çiftle kuruluyor: فقر *(fakirlik)* / غني *(zenginlik, ganî olma)*; dikey ölçüm çiftin korpusta sabit olduğunu veriyor (فقر ▸önce غني ×28,1, ▸sonra غني ×21,1). Ölçülebilir bir mantık sırası: engel öne sürülüyor, şartla kaldırılıyor, sonra iki esmâ ile mühürleniyor — biri genişlik, öteki bilgi.",
33:"Aynı kök üç kez ve üç ayrı işlevde: بغي *(iffetsizlik; azgınlık; arama)* önce 'istemek', sonra 'fuhuş', sonra yine 'aramak'. Yani ayetin yasakladığı şeyle emrettiği şey aynı kökten adlandırılıyor ve aralarında yalnız kalıp farkı var. Ölçülebilir bir bab dağılımı: altı ayrı bab, sekiz kelimeye bir yeni kalıp. Ve كره *(zorlama; hoşlanmama)* üç kez — biri yasak, biri şart, biri masdar. 24:32'nin son üçlüsü (lafız + lütuf + zenginleştirme) burada ilk sekiz kelimede aynen dönüyor.",
34:"Sûrenin açılış üçlüsü üçüncü kez ve her seferinde âyetlerin konumu değişiyor: 24:1'de بَيِّنَٰت *(apaçık)* sıfat — âyetler AÇIK; 24:18'de يُبَيِّنُ *(açıklar)* fiil — âyetler AÇIKLANAN; burada مُّبَيِّنَٰت *(açıklayıcı)* ism-i fâil — âyetler AÇIKLAYAN. İndirilen üç şey sayılıyor, üçü de mansûb ve üçü de ayrı türden: âyet, örnek, öğüt.",
35:"Ayet bir yerleştirme zinciri kuruyor ve her halka bir öncekinin içinde: مِشْكَاة *(kandil yuvası)* içinde مِصْبَاح *(kandil)*, kandil زُجَاجَة *(cam)* içinde, cam bir yıldıza benzetiliyor. Ölçülebilir bir sözdizimsel örgü: her halka önce nekre olarak tanıtılıyor, sonra marife olarak geri alınıyor — 23:14'ün yaratılış zincirindeki aynı işlem. Zincir bir noktada yönünü çeviriyor: benzetme camdan yıldıza çıkıyor, sonra yıldızdan ağaca iniyor. Yedi fiilin yedisi de muzâri; ayet hiçbir yerde geçmiş zamana geçmiyor. نور *(nûr, ışık)* altı kez ve dağılımı simetrik: iki uçta lafza bağlı, ortada üç kez benzetme içinde.",
36:"Sûrenin fâsıla düzeni burada kırılıyor. Otuz beş ayet boyunca ن ya da م ile biten dizi ilk kez ل ile kapanıyor, ve bu kırılma tek başına değil: 24:36-45 arasında on ayet üst üste N sınıfının dışına çıkıyor. Sûrenin dört kafiye sınıfı rastgele dağılmıyor, tek bir bitişik kuşakta toplanıyor; kuşağın açıldığı yer tam olarak Nûr âyetinin ardı. İki edilgen fiil arka arkaya — تُرْفَعَ *(yükseltilir)* ve يُذْكَرَ *(anılır)*: izin veren adlandırılmış, yükselten ve anan adlandırılmamış. غدو *(sabah; azık)* ile أصل *(akşamüstü (asîl))* çifti dikey ölçümde sabit (غدو ▸sonra akşam-vakti ×172,3).",
37:"Aday 471'in ölçtüğü şey burada karşıt örneğini buluyor: 23:4'te zekât doğrudan فعل *(yapma, işleme)* fiiline bağlanmıştı ve bu korpusta tekti; burada olağan kalıp — إِيتَآءِ ٱلزَّكَوٰةِ *(zekât verme)*, ve xref bunun 21:73 ile birebir aynı üçlü olduğunu veriyor. Ayetin kendi ekseni bir alıkoyma yapısı: iki ticaret terimi üç ibadet terimini engelleyemiyor. Kapanışta aynı kök iki biçimde: تَتَقَلَّبُ *(döner)* fiil, ٱلْقُلُوبُ *(kalpler)* isim — dönmek ve kalp aynı kökten.",
38:"Karşılık iki adımda veriliyor ve ikinci adım birinciyi aşıyor: أَحْسَنَ مَا عَمِلُوا۟ *(yaptıklarının en güzeli)* zaten üst sınır, sonra وَيَزِيدَهُم *(ve artırır)* bu sınırı kaldırıyor. Ölçülebilir bir kapanış: بِغَيْرِ حِسَابٍ *(hesapsız)* — sûrede حسب *(hesap, sayma)* kökü daha önce 'sanmak' işlevindeydi; burada 'hesap'. Fâsıla ikinci kez N sınıfının dışında.",
39:"Aynı kök üç kez ve tam olarak ayetin ekseninde: حسب *(hesap, sayma)* önce yanılgı (يَحْسَبُهُ *(onu sanır)*), sonra iki kez ölçü. Yani sanının yerini hesap alıyor ve ikisi aynı sözcükten. Ve وجد *(bulma)* iki kez, biri olumsuz biri olumlu: aranan bulunmuyor, aranmayan bulunuyor. İki seyrek kök yan yana: سرب *(serap)* dört, قوع *(düz arazi, çukursuz yer)* iki geçişli; ikisinin de dikey komşuluğu boş ve Allah medyan mesafeleri sûrenin en yüksekleri arasında (83 ve 72).",
40:"24:35'in ayna görüntüsü. Orada zincir içeriye doğru gidiyordu; burada yukarıya doğru katmanlanıyor — dalga, dalga, bulut, ve فوق *(üst, üstünde)* üç kez. Orada her halka bir öncekini aydınlatıyordu; burada her halka bir öncekini örtüyor (يَغْشَىٰهُ *(örter)*). Ölçülebilir bir bitiş simetrisi: 24:35 نُّورٌ عَلَىٰ نُورٍ *(nûr üstüne nûr)* ile ortalanıyor, 24:40 ظُلُمَٰتٌۢ بَعْضُهَا فَوْقَ بَعْضٍ *(karanlıklar üst üste)* ile — aynı 'üst üste' yapısı, karşıt madde. İki seyrek kök: لجج *(derin su, engin)* dört, سحب *(bulut; sürükleme)* on bir geçişli.",
}

ATLAMA={
 "24:31":"★★★ ayet. 🜁 biyolog YAZILMADI — beden terimleri var (بصر *(görme)* · فرج *(ırz)* · جيب *(yaka)* · رجل *(ayak)* · عور *(avret)*) ama hiçbiri fizyolojik bir süreç ya da yapı adlandırmıyor; hepsi görünürlük ve mahremiyet sınıfları. Tek fizyolojik yakın terim أرب *(ihtiyaç, gereksinim)*, o da olumsuzlanmış bir nitelik ve organ ya da mekanizma vermiyor. Beden adının varlığı tek başına yeterli çıpa sayılmadı — 23:104'teki gerekçenin aynısı. 🜂 uzay YAZILMADI — gök öğesi, cisim adı, yön ya da ölçü terimi yok.",
 "24:32":"★★★ ayet. 🜁 biyolog ve 🜂 uzay YAZILMADI — on iki kökün hiçbiri canlıya, organa, fizyolojik sürece ya da gök öğesine bağlanmıyor; نكح *(nikâh, evlenme)* burada hukukî bir işlem adı, وسع *(genişlik, kuşatma)* bir esmâ ve mekân göndergesi taşımıyor.",
 "24:33":"★★★ ayet. 🜁 biyolog ve 🜂 uzay YAZILMADI — yirmi dört kökün hiçbiri fizyolojik yapı/süreç ya da gök öğesi adlandırmıyor; حصن *(iffet)*, عفف *(iffet, sakınma)* ve بغي *(fuhuş)* toplumsal-hukukî sınıflar, دنو *(dünya)* âhiretin karşıtı.",
 "24:35":"★★★ ayet. **SÛRE 23'TEN BERİ İLK KEZ İKİ MERCEK DE YAZILDI.** 🜁 biyolog — çıpa: شَجَرَةٍ مُّبَٰرَكَةٍ زَيْتُونَةٍ *(bereketli bir zeytin ağacı)*, kökler زيت *(zeytin, zeytinyağı)* ve شجر *(ağaç)*. Ölçülen: sûrede adı verilen tek bitki türü; tür konumla değil KONUMUN REDDİYLE niteleniyor (لَّا شَرْقِيَّةٍ وَلَا غَرْبِيَّةٍ *(ne doğuya ne batıya ait)*), yani seçilen değişken toprak/su/meyve değil IŞIK MARUZİYETİ; ve yüklemin öznesi ağaç değil ürünü (زَيْت *(yağ)*), yükleme bir eşik atfediliyor (يَكَادُ … يُضِىٓءُ *(neredeyse ışık verecek)*). Dikey: زيت ▸sonra شبه *(benzeşme, müteşâbih)* ×270,3. SINIR: ayet yağın bileşimi, ağacın büyümesi ya da herhangi bir fizyolojik mekanizma hakkında hiçbir şey söylemiyor; bitki fizyolojisi ÇIKARILMADI. 🜂 uzay — çıpa: كَوْكَبٌ دُرِّىٌّ *(inci gibi parlayan yıldız)*, kökler كوكب *(yıldız (kevkeb))* n=5 ve درر *(inci gibi parlama)* n=4. Ölçülen: yıldız PARLAKLIK için çağrılıyor, konum ya da hareket için değil; ikinci öğe bir yön ekseni (شرق *(doğu, tan)* / غرب *(batma (güneş))*, dikey: شرق ▸sonra batı ×226,0) ama eksen OLUMLU KULLANILMIYOR, iki ucu birden reddediliyor. SINIR: yörünge, ölçü, sayı ya da hareket terimi YOK; gök modeli KURULMADI.",
 "24:36":"★★ ayet — mercek eşiği ★★★ olduğu için zorunlu değil, yine de not: 🜂 uzay YAZILMADI — غُدُوّ *(sabah)* ve ءَاصَال *(akşam vakitleri)* günlük zaman dilimleri ama ayet hiçbir gök cismi, hareket ya da ölçü terimi vermiyor; vakitler ibadet zamanı olarak adlandırılıyor, gök olayı olarak değil.",
 "24:40":"★★ ayet. 🜁 biyolog YAZILMADI — يدي *(el)* ve رأي *(görme)* geçiyor ama ikisi de bir görünürlük ölçüsünün parçası; fizyolojik yapı ya da süreç adlandırılmıyor. 🜂 uzay YAZILMADI — ışık yokluğu var ama gök cismi, hareket, yön ya da ölçü terimi yok; سحب *(bulut; sürükleme)* atmosferik bir örtü ve dikey komşusu rüzgâr ×54,7 (meteorolojik bağlam, astronomik değil).",
 "_blok_notu_24_31_40":"Blok 24:31-40'ta dört ★★★ ayet (31, 32, 33, 35). Üçünde iki mercek de atlandı; **24:35'te İKİSİ DE YAZILDI — sûre 23 boyunca hiç yazılamayan biyolog merceği burada ilk kez çıpa buldu.** Yıldız kaynakları: 24:31 n=6,96 · 24:32 hapaks=3,38 · 24:33 n=3,78 · 24:35 n=3,78 — dördünden üçü UZUNLUK kaynaklı, aday 503'ün (472 düzeltmesi) doğrudan verisi.",
}

p='/home/claude/repo/notlar/okuma_metni.json'
OM=json.load(open(p,encoding='utf-8'))
for n in range(31,41):
    OM['24']["24:%d"%n]={"ar":AR[(24,n)],"meal":MEAL[n],"olcum":OLCUM[n],
                         "mercek":MERCEK[n],"dikey":DIK["24:%d"%n]}
OM['24']['_mercek_atlama_notu'].update(ATLAMA)
OM['ilerleme']['not']=("Sûre 23 TAM (118/118). Sûre 24 (Nûr) makro profil + 24:1-40 okundu. "
                       "Devam: 24:41. Kafiye kuşağı 24:36-45 sürüyor; 24:41 kafiye kırık işaretli.")
OM['ilerleme']['kismi']={"2":"1-20 ayet düzeyinde","24":"1-40 ayet düzeyinde"}
OM['ilerleme']['okunan_ayet']=1621
json.dump(OM,open(p,'w',encoding='utf-8'),ensure_ascii=False,indent=1)
print('okuma_metni: sûre 24 →',len([k for k in OM['24'] if not k.startswith('_')]),'ayet')

pm='/home/claude/repo/notlar/mercek_kayit.json'
MK=json.load(open(pm,encoding='utf-8'))
for n in range(31,41): MK['24']["24:%d"%n]=MERCEK[n]
MK['24_atlama'].update(ATLAMA)
json.dump(MK,open(pm,'w',encoding='utf-8'),ensure_ascii=False,indent=1)
print('mercek_kayit: sûre 24 →',len(MK['24']),'mercek')
