# -*- coding: utf-8 -*-
"""blok_24_53_60.py — sûre 24 blok 24:53-60."""
import json
DIK=json.load(open('blok_dikey_24_46_64.json',encoding='utf-8'))
veri=json.load(open('kuran_veri.json',encoding='utf-8'))
AR={}
for s in veri['sureler']:
    for a in s['ayetler']: AR[(s['no'],a['no'])]=a['ar']

MEAL={
53:"Emredersen mutlaka çıkacaklarına dair var güçleriyle Allah'a yemin ettiler. De ki: Yemin etmeyin; bilinen bir itaat yeter. Allah yaptıklarınızdan haberdardır.",
54:"De ki: Allah'a itaat edin, Elçi'ye itaat edin. Yüz çevirirseniz, ona yüklenen ona, size yüklenen sizedir. Ona itaat ederseniz doğru yolu bulursunuz. Elçi'ye düşen ancak apaçık tebliğdir.",
55:"Allah, içinizden inanıp iyi işler yapanlara vaat etti: onları yeryüzünde, kendilerinden öncekileri halef kıldığı gibi halef kılacak; onlar için hoşnut olduğu dinlerini sağlamlaştıracak; korkularının ardından onlara güvenlik verecek. Bana kulluk ederler, bana hiçbir şeyi ortak koşmazlar. Bundan sonra kim inkâr ederse, işte onlar fâsıklardır.",
56:"Namazı kılın, zekâtı verin, Elçi'ye itaat edin; belki merhamet olunursunuz.",
57:"İnkâr edenlerin yeryüzünde âciz bırakabileceklerini sanma. Varacakları yer ateştir; ne kötü varış!",
58:"Ey inananlar, ellerinizin altındakiler ve içinizden ergenliğe ermemiş olanlar üç vakitte sizden izin istesinler: sabah namazından önce, öğle sıcağında elbiselerinizi çıkardığınız vakit ve yatsı namazından sonra. Bu üçü sizin mahrem vakitlerinizdir. Bunların dışında ne size ne onlara bir vebal var; birbirinizin yanına girip çıkarsınız. Allah size âyetleri böyle açıklıyor. Allah bilendir, hikmet sahibidir.",
59:"Çocuklarınız ergenliğe erdiğinde, kendilerinden öncekilerin izin istediği gibi onlar da izin istesinler. Allah size âyetlerini böyle açıklıyor. Allah bilendir, hikmet sahibidir.",
60:"Evlenme umudu kalmamış yaşlı kadınlara gelince: süslerini göstermeden dış elbiselerini bırakmalarında onlara bir vebal yoktur. Sakınmaları ise onlar için daha hayırlıdır. Allah işitendir, bilendir.",
}
OLCUM={
53:"eksen: **Allah lafzı 2. ve 14. sırada — iki geçiş** (allah z=1,82) · **esmâ خَبِير *(habîr)* 15. sırada — GEÇERLİ** · aktör yok · edim emir + yasak + şart, kip EMPH ×3 · COND 1 · IMPV 1 · PRO 1 · şahıs 3MP ×5 · 2MS ×3 · 2MP ×4 · n=17 mora=93 harf=83, fâsıla تَعْمَلُونَ *(yaparsınız)* → ن, N sınıfı; i'râb GEN 2 · ACC 3 · NOM 3; bab I ×4 · bab IV ×2; zaman PERF ×2 · IMPF ×3 · IMPV 1; **kök ikilemesi قسم *(paylaştırma; yemin)* ×2 — biri haber biri yasak · أله *(ilâh; lafza-i celâl)* ×2**; **biçim NEHY · QASEM — SÛRENİN TEK QASEM'İ**; **hizb işareti ۞** · yıldız ★ · kökler قسم · أله · جهد *(cihad, çaba harcama)* · يمن *(sağ el, sağ yan)* · أمر *(emir; iş)* · خرج *(çıkma, çıkarma)* · قول *(söz söyleme)* · طوع *(güç yetirme, itaat)* · عرف *(tanıma)* · خبر *(haber; haberdar olma)* · عمل *(iş, amel)* · bağ: **24:47 ile aynı yapı** — orada söz verilip yüz çevrilmişti, burada yemin edilip yemin reddediliyor; **24:53 · 24:54 · 24:56 — طوع dizisi** (elle, L1, aday 516)",
54:"eksen: **Allah lafzı 3. sırada** (allah z=0,34) · **esmâ مُبِين *(apaçık)* 23. sırada = fâsıla — ÖLÇÜM ARTEFAKTI (aday 461)**: ٱلْبَلَٰغُ ٱلْمُبِينُ *(apaçık tebliğ)* tamlamasında niteleyen · aktör yok · edim emir + şart, kip IMPV ×3 · COND ×2 · NEG 1 · RES 1 · şahıs 2MS 1 · 2MP ×13 · 3MS ×3 · n=23 mora=125 harf=108, fâsıla ٱلْمُبِينُ → ن, N sınıfı; i'râb ACC 3 · GEN 1 · NOM 2; **bab I ×1 · II ×2 · IV ×3 · V ×1 · VIII ×1 — beş ayrı bab**; zaman IMPV ×3 · IMPF ×3 · PERF ×2; **edilgen 2 — حُمِّلَ / حُمِّلْتُمْ, aynı kök iki şahısta** (pas z=1,10); **kök ikilemesi طوع *(güç yetirme, itaat)* ×3 · رسل *(gönderme, elçi)* ×2 · حمل *(yüklenme, taşıma)* ×2**; biçim HASR; simetri [4,6,10,1]; **dış düğüm 3** · yıldız ★ yok · kökler قول *(söz söyleme)* · طوع · أله *(ilâh; lafza-i celâl)* · رسل · ولي *(dost, veli; velâyet)* · حمل · هدي *(yol gösterme)* · بلغ *(ulaşma, tebliğ)* · بين *(arası; açıklama)* · bağ: xref قال *(dedi)* + أطاع *(itaat etti)* + اللّه *(Allah)* → **3:32 · 33:66**; أطاع + رسول *(elçi)* + تولّى *(yüz çevirdi)* → **64:12** (elle, L1, aday 516)",
55:"eksen: **Allah lafzı 2. sırada** (allah z=0,00) · aktör yok · edim haber, **kip EMPH ×6 — üç te'kid nûnu** · NEG 1 · şahıs 3MS ×7 · 3MP ×16 · 2MP 1 · **1S ×2 — lafızla aynı ayette birinci tekil, iltifât işaretlenmemiş (aday 517)** · **n=38 mora=202 harf=179** (n z=2,72), fâsıla ٱلْفَٰسِقُونَ *(fâsıklar)* → ن, N sınıfı; i'râb NOM 2 · GEN 5 · ACC 4; **bab I ×4 · II ×2 · IV ×2 · VIII ×1 · X ×2 — beş ayrı bab**; zaman PERF ×6 · IMPF ×5; **kök ikilemesi أمن *(güven; iman)* ×2 — biri iman biri güvenlik · خلف *(ayrılığa düşme; ardından gelme)* ×2 · بعد *(sonra; uzaklık)* ×2**; simetri [3,3,9,1]; dış düğüm 2 · yıldız ★★ · kökler وعد *(vaat)* · أله *(ilâh; lafza-i celâl)* · أمن · عمل *(iş, amel)* · صلح *(iyi, elverişli olma; ıslah)* · خلف · أرض *(yer, yeryüzü)* · قبل *(ön, önce; kabul)* · مكن *(yerleştirme, imkân)* · دين *(din; borç)* · رضو *(razı olma, hoşnutluk)* · بدل *(değiştirme)* · بعد · خوف *(korku)* · عبد *(kul, kulluk)* · شرك *(ortak koşma)* · شيأ *(dileme; şey)* · كفر *(inkâr, nankörlük)* · فسق *(fâsıklık)* · bağ: xref وعد *(vaat etti)* + اللّه + آمن *(iman etti)* → **5:9 · 48:29**; **24:4 ile aynı fâsıla** ٱلْفَٰسِقُونَ (elle, L1)",
56:"eksen yok · aktör yok · edim emir, kip IMPV ×3 · şahıs 2MP ×9 · **n=8 mora=62 harf=52 — bloğun en kısa ayeti**, fâsıla تُرْحَمُونَ *(merhamet olunursunuz)* → ن, N sınıfı; **i'râb ACC 4 — dördü mansûb**; bab I ×1 · bab IV ×3; **zaman IMPV ×3 · IMPF 1**; edilgen 1 (pas z=1,10); **lafızsız** · yıldız ★ yok · kökler قوم *(kalkma; kavim; kıyamet)* · صلو *(namaz, salât)* · أتي *(gelme, getirme)* · زكو *(arınma, temizlik)* · طوع *(güç yetirme, itaat)* · رسل *(gönderme, elçi)* · رحم *(rahmet, merhamet)* · bağ: **24:37 ile aynı üçlü** — orada masdar, burada emir; **21:73 · 23:4 ile zekât zinciri** (aday 471) (elle, L1, aday 516)",
57:"eksen yok · aktör yok · edim yasak, kip PRO 1 · EMPH ×2 · şahıs 2MS 1 · 3MP ×3 · 3MS 1 · n=11 mora=64 harf=56, **fâsıla ٱلْمَصِيرُ *(varış)* → ر, R sınıfı — KAFİYE KIRIK işaretli; sûrenin ikinci ve son kırığı (aday 509)**; i'râb ACC 1 · GEN 2 · NOM 2; bab I ×3; zaman IMPF 1 · PERF ×2; **biçim NEHY — sûrenin on iki NEHY'inden sonuncusu**; **lafızsız**; dış düğüm 2 · yıldız ★ · kökler حسب *(hesap, sayma)* · كفر *(inkâr, nankörlük)* · عجز *(âciz bırakma; acizlik)* · أرض *(yer, yeryüzü)* · أوي *(sığınma)* · نور *(nûr, ışık; ateş)* · بأس *(şiddet, azap; savaş gücü)* · صير *(dönüşme, varış)* · bağ: xref نار *(ateş)* + بئس *(ne kötü)* + مصير *(varış)* → **2:126**; **24:42 ile aynı fâsıla kelimesi** ٱلْمَصِيرُ — orada Allah'a varış, burada ateşe (elle, L1, aday 518)",
58:"eksen: **Allah lafzı 44. ve 47. sırada — iki geçiş** (allah z=0,29) · **esmâ عَلِيم *(alîm)* 48. + حَكِيم *(hakîm)* 49. sırada — MÜHÜR; GEÇERLİ** · aktör yok · edim emir + nida, kip VOC 1 · IMPV 1 · NEG ×2 · şahıs 3MP ×5 · 3MS ×3 · 2MP ×11 · 3FS 1 · 3FP 1 · **n=49 mora=264 harf=227** (n z=3,88: yıldızın tek kaynağı, aday 503), **fâsıla حَكِيمٌۭ → م**, N sınıfı; i'râb ACC 6 · NOM 9 · GEN 11; bab I ×4 · II ×1 · IV ×1 · X ×1; zaman PERF ×3 · IMPF ×4; **kök ikilemesi أيي *(âyet, işaret; hangi)* ×2 · ثلث *(üç; üçte bir)* ×2 · صلو *(namaz, salât)* ×2 · بعد *(sonra; uzaklık)* ×2 · بعض *(bir kısım)* ×2 · أله *(ilâh; lafza-i celâl)* ×2**; **sayı sözcüğü ثَلاث *(üç)* ×2**; biçim DIKKAT; simetri [3,8,32,1]; iç düğüm 2 · yıldız ★★★ · kökler أيي · أمن *(güven; iman)* · أذن *(izin verme; kulak)* · ملك *(mülk; melik)* · يمن *(sağ el, sağ yan)* · بلغ *(ulaşma, tebliğ)* · حلم *(rüya; ergenlik, hilm)* · ثلث · مرر *(kere, defa)* · قبل *(ön, önce; kabul)* · صلو · فجر *(fışkırtma; fecir)* · حين *(vakit)* · وضع *(koyma, indirme)* · ثوب *(elbise; karşılık)* · ظهر *(sırt; zuhur, açığa çıkma)* · بعد · عشو *(akşam)* · عور *(mahrem yer, avret; gedik)* · ليس *(değil)* · جنح *(kanat; yan taraf)* · طوف *(dolaşma, tavaf)* · بعض · بين *(arası; açıklama)* · أله · علم *(bilme)* · حكم *(hüküm verme, hikmet)* · bağ: xref اللّه *(Allah)* + آية *(âyet)* + اللّه → **22:52 · 24:18 · 24:59**; **24:31 ile ortak عور** — orada bedenin mahremi, burada zamanın (elle, L1, aday 519)",
59:"eksen: **Allah lafzı 14. ve 17. sırada — iki geçiş** (allah z=1,58) · **esmâ عَلِيم *(alîm)* 18. + حَكِيم *(hakîm)* 19. sırada — MÜHÜR; GEÇERLİ — 24:58 ile ARDIŞIK AYNI MÜHÜR** · aktör yok · edim emir, kip IMPV 1 · şahıs 3MS ×4 · 2MP ×2 · 3MP ×3 · n=19 mora=101 harf=91, **fâsıla حَكِيمٌۭ → م**, N sınıfı; i'râb NOM 5 · ACC 1 · GEN 2; bab I ×1 · bab II ×1 · bab X ×2; zaman PERF ×2 · IMPF ×2; kök ikilemesi أذن *(izin verme; kulak)* ×2 · أله *(ilâh; lafza-i celâl)* ×2; simetri [3,7,10,1]; iç düğüm 2 · yıldız ★ · kökler بلغ *(ulaşma, tebliğ)* · طفل *(çocuk, bebek)* · حلم *(rüya; ergenlik, hilm)* · أذن · قبل *(ön, önce; kabul)* · بين *(arası; açıklama)* · أله · أيي *(âyet, işaret)* · علم *(bilme)* · حكم *(hüküm verme, hikmet)* · bağ: **24:58 ile bitişik ikiz kapanış** — son yedi kelime birebir, tek fark ٱلْءَايَٰتِ → ءَايَٰتِهِ (elle, L1, aday 519)",
60:"eksen: **Allah lafzı 21. sırada** (allah z=0,34) · **esmâ سَمِيع *(semîʼ)* 22. + عَلِيم *(alîm)* 23. sırada — MÜHÜR; GEÇERLİ — sûrenin on ikinci ve SON mühürü** · aktör yok · edim haber, kip NEG 1 · şahıs 3MP ×2 · 3MS 1 · **3FP ×7** · n=23 mora=130 harf=106, **fâsıla عَلِيمٌۭ → م**, N sınıfı; i'râb NOM 6 · GEN 3 · ACC 3; bab I ×3 · bab X ×1; zaman IMPF ×3 · PERF 1; simetri [3,2,9,1] · yıldız ★ yok · kökler قعد *(oturma; temel; oturup kalan kadın)* · نسو *(kadınlar)* · رجو *(umma; erteleme; yan taraf)* · نكح *(nikâh, evlenme)* · ليس *(değil)* · جنح *(kanat; yan taraf)* · وضع *(koyma, indirme)* · ثوب *(elbise; karşılık)* · غير *(başka)* · برج *(burç, kule; süslenip açılma (teberrüc))* · زين *(süsleme)* · عفف *(iffet, sakınma)* · خير *(hayır, daha iyi)* · أله *(ilâh; lafza-i celâl)* · سمع *(işitme)* · علم *(bilme)* · bağ: **24:31 ile ters yönlü muafiyet — aynı زين kökü, iki yön**; **24:33 ile ortak عفف** (elle, L1, aday 520)",
}
MERCEK={
53:"Sûrenin tek yemin ayeti ve yeminin kendisi reddediliyor: أَقْسَمُوا۟ *(yemin ettiler)* → لَّا تُقْسِمُوا۟ *(yemin etmeyin)*, aynı kök, biri haber biri yasak. Ölçülebilir olan yerine konan şey: طَاعَةٌ مَّعْرُوفَةٌ *(bilinen bir itaat)* — iki nekre isim, fiilsiz bir cümle; yemin bir söz edimiydi, karşılığı bir nitelik. Dikey ölçüm قسم *(paylaştırma; yemin)* ▸sonra çaba ×171,7 veriyor — جَهْدَ أَيْمَٰنِهِمْ *(var güçleriyle)* terkibi korpusta sabit.",
54:"İtaat kökü tek ayette üç kez ve üçü de farklı nesneyle: Allah, Elçi, zamir. Ölçülebilir bir simetri: aynı edilgen fiil iki şahısta arka arkaya — حُمِّلَ *(ona yüklendi)* / حُمِّلْتُمْ *(size yüklendi)*; yükleyen adlandırılmıyor, yüklenen ikiye bölünüyor. Ayet bir HASR ile kapanıyor: elçinin işi tek şeye indirgeniyor. Beş fiil, beş ayrı bab — 24:27'de de aynı dağılım vardı.",
55:"Vaat üç te'kid nûnuyla üç kez pekiştiriliyor ve üç fiil üç ayrı kalıpta: لَيَسْتَخْلِفَنَّهُمْ *(halef kılacak)* bab X, لَيُمَكِّنَنَّ *(sağlamlaştıracak)* bab II, لَيُبَدِّلَنَّهُم *(değiştirecek)* bab II. Ölçülebilir bir kök çevrimi: أمن *(güven; iman)* iki kez ve iki anlamda — ءَامَنُوا۟ *(inandılar)* koşul, أَمْنًا *(güvenlik)* sonuç; aynı kökten giriş ve çıkış. Ayetin ortasında şahıs birinci tekile geçiyor (يَعْبُدُونَنِى *(bana kulluk ederler)*), lafız üçüncü şahısta açmıştı — ölçüm katmanı bunu iltifât saymıyor.",
56:"Üç emir, üç nesne, üç mansûb; ve dördüncü mansûb dilek cümlesinin öznesi. Ölçülebilir bir tekrar: 24:37 aynı iki ibadeti masdar biçiminde saymıştı, burada emir biçiminde; ve 24:53-54-56 üçlüsü طوع *(güç yetirme, itaat)* kökünü üç ayette beş kez geçiriyor. Kapanış edilgen — تُرْحَمُونَ *(merhamet olunursunuz)* — merhamet edenin adı bu ayette geçmiyor; sûrede lafız taşımayan on dört ayetten biri.",
57:"Sûrenin iki kafiye kırığından ikincisi ve 24:42'nin fâsıla kelimesini geri getiriyor: ٱلْمَصِيرُ *(varış)*, ama yönü ters — orada إِلَى ٱللَّهِ *(Allah'a)*, burada ٱلنَّارُ *(ateş)*. Ölçülebilir bir bağ: iki ayet de R sınıfında, 24:42 kuşağın içinde, 24:57 kuşağın dışında ve tek başına — sûrenin R sınıfı yedi ayetinin altısı kuşakta, yedincisi bu. حسب *(hesap, sayma)* kökü sûrede beşinci kez ve yine 'sanma' işlevinde.",
58:"Sûrenin dördüncü en uzun ayeti ve yıldız kaynağı yine uzunluk. Üç vakit sayılıyor ve sayı sözcüğü iki kez — önce ثَلَٰثَ مَرَّٰتٍ *(üç kez)*, sonra ثَلَٰثُ عَوْرَٰتٍ *(üç mahrem vakit)*; ilki sayım, ikincisi sınıflandırma. Ölçülebilir bir günlük eksen: فَجْر *(fecir)* → ظَهِيرَة *(öğle sıcağı)* → عِشَاء *(yatsı)*. Ve عور *(mahrem yer, avret; gedik)* kökü 24:31'de bedene, burada zamana ait — aynı kelime iki ölçekte. طَوَّٰفُونَ *(girip çıkanlar)* korpusta tavaf köküyle aynı, burada ev içi dolaşım.",
59:"24:58'in eşiği burada geçiliyor: orada ergenliğe ermemiş olanların üç vakitlik yükümlülüğü vardı, burada ermiş olanlar genel kurala giriyor. Ölçülebilir bir bağ: iki ayetin son yedi kelimesi birebir aynı, tek fark bir zamir — ٱلْءَايَٰتِ *(âyetleri)* / ءَايَٰتِهِ *(âyetlerini)*. Aynı esmâ çifti iki ardışık ayette; sûrede عَلِيم|حَكِيم mühürü böylece 24:18, 24:58, 24:59'da üç kez. أذن *(izin verme; kulak)* kökü ayette iki kez ve iki kipte: emir ve geçmiş — aynı fiil, kural ve örnek.",
60:"24:31'in kuralı burada bir istisna buluyor ve istisna aynı kökle çevreleniyor: زين *(süsleme)* orada gizlenecek şey, burada gösterilmeyecek şey — aynı kelime, ters işaretli iki koşul. Ölçülebilir bir kapanış: sûrenin on iki mühründen sonuncusu buradaki سَمِيع|عَلِيم; 24:21'de aynı çift vardı. قعد *(oturma; temel; oturup kalan kadın)* kökü burada 'evlenme umudu kalmamış kadın' anlamında, korpusta 31 geçişli ve baskın işlevi 'oturma'. Bloğun iki muafiyet ayeti (24:58 ve bu) aynı kalıbı kullanıyor: لَيْسَ … جُنَاحٌ *(vebal yok)*.",
}
ATLAMA={
 "24:58":"★★★ ayet. 🜁 biyolog YAZILMADI — حلم *(rüya; ergenlik, hilm)* bir gelişim eşiği adlandırıyor ama ayette biyolojik süreç değil hukukî sınır (izin yükümlülüğünün başlangıcı); dikey komşuluğu ضغث *(karışık demet)* ×356,5, kök korpusta baskın olarak 'rüya' işlevinde. Gelişim okumasını seçmek yasaklı 'bilimsel izdüşüm' olurdu. 🜂 uzay YAZILMADI — üç vakit adı ibadet/ev düzeni zamanı; gök cismi, hareket ya da ölçü terimi yok (24:36 gerekçesi).",
 "_blok_notu_24_53_60":"Blok 24:53-60'ta tek ★★★ ayet (24:58, n kaynaklı z=3,88) ve iki mercek atlandı. Sûre 24 toplamı: on beş ★★★, on dördünde mercek atlandı, yalnız 24:35'te yazıldı — sûre bitmeden bu sayım kesinleşti (kalan 61-64'te ★★★ yalnız 24:61 ve 24:63).",
}
p='/home/claude/repo/notlar/okuma_metni.json'
OM=json.load(open(p,encoding='utf-8'))
for n in range(53,61):
    OM['24']["24:%d"%n]={"ar":AR[(24,n)],"meal":MEAL[n],"olcum":OLCUM[n],"mercek":MERCEK[n],"dikey":DIK["24:%d"%n]}
OM['24']['_mercek_atlama_notu'].update(ATLAMA)
OM['ilerleme']['not']=("Sûre 23 TAM (118/118). Sûre 24 (Nûr) makro profil + 24:1-60 okundu. "
                       "Devam: 24:61 (n=76, sûrenin ikinci en uzun ayeti). Sûrede 4 ayet kaldı.")
OM['ilerleme']['kismi']={"2":"1-20 ayet düzeyinde","24":"1-60 ayet düzeyinde"}
OM['ilerleme']['okunan_ayet']=1641
json.dump(OM,open(p,'w',encoding='utf-8'),ensure_ascii=False,indent=1)
print('okuma_metni: sûre 24 →',len([k for k in OM['24'] if not k.startswith('_')]),'ayet')
pm='/home/claude/repo/notlar/mercek_kayit.json'
MK=json.load(open(pm,encoding='utf-8'))
for n in range(53,61): MK['24']["24:%d"%n]=MERCEK[n]
MK['24_atlama'].update(ATLAMA)
json.dump(MK,open(pm,'w',encoding='utf-8'),ensure_ascii=False,indent=1)
pb='/home/claude/repo/notlar/okuma_baglantilari.json'
d=json.load(open(pb,encoding='utf-8'))
d['AD_nur'] += [
 {"bag":"24:47 ↔ 24:53","kural":"L1","not":"Aynı yapı: söz verilip yüz çevrilmesi (24:47) / yemin edilip yeminin reddedilmesi (24:53). İkisinde de itaat sözü (وَأَطَعْنَا / طَاعَةٌ مَّعْرُوفَةٌ) ve ikisinde de karşı hüküm."},
 {"bag":"24:53 ↔ 24:54 ↔ 24:56","kural":"L1","not":"طوع *(güç yetirme, itaat)* kökü üç ardışık ayette beş kez: nitelik (24:53, isim) → eylem (24:54 ×3, 24:56). Nesne ağırlıkla Elçi (aday 516)."},
 {"bag":"24:37 ↔ 24:56","kural":"L1","not":"Aynı ibadet çifti: إِقَامِ ٱلصَّلَوٰةِ وَإِيتَآءِ ٱلزَّكَوٰةِ masdar (24:37) / أَقِيمُوا۟ ٱلصَّلَوٰةَ وَءَاتُوا۟ ٱلزَّكَوٰةَ emir (24:56)."},
 {"bag":"24:4 ↔ 24:55","kural":"L2","not":"Aynı fâsıla ٱلْفَٰسِقُونَ *(fâsıklar)*: 24:4'te tanıklığı reddedilenler, 24:55'te vaatten sonra inkâr edenler."},
 {"bag":"24:42 ↔ 24:57","kural":"L1","not":"Aynı fâsıla kelimesi ٱلْمَصِيرُ *(varış)*, iki yön: إِلَى ٱللَّهِ / ٱلنَّارُ. İkisi de R sınıfı; 24:42 kuşakta, 24:57 tek başına ve kırık işaretli (aday 518)."},
 {"bag":"24:58 ↔ 24:59","kural":"L1","not":"Bitişik ikiz kapanış: son yedi kelime birebir, tek fark ٱلْءَايَٰتِ → ءَايَٰتِهِ. Ardışık aynı mühür عَلِيم|حَكِيم. Eşik حلم *(ergenlik)* ilkinde olumsuz, ikincide olumlu (aday 519)."},
 {"bag":"24:31 ↔ 24:58","kural":"L2","not":"عور *(mahrem yer, avret; gedik)* iki ölçekte: 24:31'de beden (عَوْرَٰتِ ٱلنِّسَآءِ), 24:58'de zaman (ثَلَٰثُ عَوْرَٰتٍ)."},
 {"bag":"24:31 ↔ 24:60","kural":"L1","not":"زين *(süsleme)* kökü kural ve istisnada: 24:31 gizlenecek şey (yasak), 24:60 gösterilmeyecek şey (muafiyet koşulu). Aynı kelime, ters işaretli iki koşul (aday 520)."},
 {"bag":"24:21 ↔ 24:60","kural":"L2","not":"Aynı mühür سَمِيع|عَلِيم: sûrenin on iki mühründen üçüncüsü ve on ikincisi (sonuncusu)."},
 {"bag":"24:29 ↔ 24:58 ↔ 24:60 ↔ 24:61","kural":"L1","not":"لَيْسَ … جُنَاحٌ *(vebal yok)* muafiyet kalıbı sûrede dört kez."},
]
json.dump(d,open(pb,'w',encoding='utf-8'),ensure_ascii=False,indent=1)
print('AD_nur',len(d['AD_nur']),'bağ')
