# -*- coding: utf-8 -*-
"""blok_23_41_60.py — sûre 23 üçüncü blok kaydı."""
import json
DIK=json.load(open('blok_dikey_23_41_60.json',encoding='utf-8'))
veri=json.load(open('kuran_veri.json',encoding='utf-8'))
AR={}
for s in veri['sureler']:
    for a in s['ayetler']: AR[(s['no'],a['no'])]=a['ar']

MEAL={
41:"Onları hak ile o çığlık aldı; biz de onları sel süprüntüsü kıldık. Uzak olsun zalim kavim!",
42:"Sonra onların ardından başka nesiller inşa ettik.",
43:"Hiçbir ümmet ecelini ne öne alabilir ne erteleyebilir.",
44:"Sonra elçilerimizi ard arda gönderdik. Bir ümmete elçisi her geldiğinde onu yalanladılar. Biz de onları birbiri ardınca getirdik ve onları anlatılara çevirdik. Uzak olsun inanmayan kavim!",
45:"Sonra Mûsâ'yı ve kardeşi Hârûn'u âyetlerimizle ve apaçık bir delille gönderdik.",
46:"Firavun'a ve onun ileri gelenlerine. Ama büyüklendiler; üstünlük taslayan bir kavimdiler.",
47:"Dediler ki: Kavmi bize kulluk edip dururken, kendimiz gibi iki beşere mi inanacağız?",
48:"İkisini de yalanladılar; böylece helâk edilenlerden oldular.",
49:"Andolsun, Mûsâ'ya Kitab'ı verdik — belki doğru yolu bulurlar diye.",
50:"Meryem oğlunu ve annesini bir âyet kıldık; ikisini de oturmaya elverişli, akarsulu bir tepeye yerleştirdik.",
51:"Ey elçiler, temiz şeylerden yiyin ve iyi iş yapın. Ben yaptıklarınızı bilirim.",
52:"Bu sizin ümmetiniz, tek bir ümmet; ben de sizin Rabbinizim. Öyleyse benden sakının.",
53:"Ama işlerini aralarında parçalara böldüler; her hizip kendi elindekiyle sevinmekte.",
54:"Onları bir süreye kadar gafletleri içinde bırak.",
55:"Kendilerine mal ve oğullardan verdiklerimizle onları desteklediğimizi mi sanıyorlar —",
56:"— onlara hayırlarda koşuyoruz diye? Hayır, farkında değiller.",
57:"Onlar ki Rablerinin haşyetinden titrerler —",
58:"— onlar ki Rablerinin âyetlerine inanırlar —",
59:"— onlar ki Rablerine ortak koşmazlar —",
60:"— onlar ki verdiklerini, Rablerine döneceklerinden ötürü kalpleri ürpererek verirler.",
}

OLCUM={
41:"eksen yok · aktör yok · edim haber · şahıs 3MP ×2 · 1P ×2 · 3FS 1 · n=8 mora=64 harf=49, fâsıla ٱلظَّٰلِمِينَ *(zalimler)* → ن, N sınıfı; i'râb GEN 3 · ACC 2 · NOM 1; bab I ×2; zaman PERF ×2; dış düğüm 1 · yıldız ★ yok · kökler أخذ *(alma, edinme)* · صيح *(çığlık, sayha)* · حقق *(hak, gerçek)* · جعل *(kılma, var etme)* · غثو *(sel süprüntüsü, çerçöp)* · بعد *(sonra; uzaklık)* · قوم *(kalkma; kavim; kıyamet)* · ظلم *(zulüm)* · bağ: xref بعد *(uzaklık)* + قوم *(kavim)* + ظالم *(zalim)* → **11:44**; **23:44 ile aynı kapanış kalıbı** فَبُعْدًۭا لِّـ *(uzak olsun)*, sûrede iki kez (elle, L1)",
42:"eksen yok · aktör yok · edim haber · şahıs 1P ×2 · 3MP 1 · n=6 mora=37 harf=27, fâsıla ءَاخَرِينَ *(başkaları)* → ن, N sınıfı; i'râb GEN 1 · ACC 2; bab IV ×1; zaman PERF 1; dış düğüm 1 · iç düğüm 1 · yıldız ★ yok · kökler نشأ *(inşâ etme, yeni bir şey var etme)* · بعد *(sonra; uzaklık)* · قرن *(nesil, çağ)* · أخر *(geciktirme, sonraya bırakma)* · bağ: **23:31 ile sûre-içi bölüt ikizi — BEKLEYEN BAĞ KAPANDI**; tek fark قَرْنًا *(bir nesil)* tekil → قُرُونًا *(nesiller)* çoğul; xref أنشأ *(inşa etti)* + بعد + قرن → **6:6 ve 23:31** (elle, L1)",
43:"eksen yok · aktör yok · edim haber, kip NEG ×2 · şahıs 3FS ×2 · 3MP ×2 · n=7 mora=34 harf=27, fâsıla يَسْتَـْٔخِرُونَ *(ertelerler)* → ن, N sınıfı; i'râb GEN 1 · ACC 1; bab I ×1 · bab X ×1; zaman IMPF ×2; dış düğüm 1 · yıldız ★ yok · kökler سبق *(geçme, öne geçme)* · أمم *(ümmet, topluluk)* · أجل *(ecel, süre)* · أخر *(geciktirme, sonraya bırakma)* · bağ: **tam-ayet ikizi 15:5** — tek harf farkla (orada مَّا, burada مَا); xref سبق + أمّة *(ümmet)* + أجل *(ecel)* → 15:5 (elle, L1)",
44:"eksen yok · aktör yok · edim haber, kip NEG 1 · şahıs 1P ×7 · 3MP ×6 · 3MS ×2 · 3FS 1 · **n=19 mora=119 harf=91 — bloğun en uzun ayeti** (n z=0,70), fâsıla يُؤْمِنُونَ *(inanırlar)* → ن, N sınıfı; i'râb ACC 8 · NOM 1 · GEN 1; bab I ×2 · bab II ×1 · bab IV ×3; zaman PERF ×5 · IMPF 1; **kök ikilemesi رسل *(gönderme, elçi)* ×3 · بعض *(bir kısım)* ×2** · yıldız ★ yok · kökler رسل · وتر *(ard arda gelme; tek sayı, vitir)* · كلل *(hep, bütün)* · جيأ *(gelme)* · أمم *(ümmet, topluluk)* · كذب *(yalan; yalanlama)* · تبع *(uyma, ardından gitme)* · بعض · جعل *(kılma, var etme)* · حدث *(söz, haber; anlatı)* · بعد *(sonra; uzaklık)* · قوم *(kalkma; kavim; kıyamet)* · أمن *(güven; iman)* · bağ: **23:41 ile aynı kapanış kalıbı** فَبُعْدًۭا لِّـ *(uzak olsun)* — sıfat değişiyor: orada ٱلظَّٰلِمِينَ *(zalimler)*, burada لَّا يُؤْمِنُونَ *(inanmayanlar)* (elle, L1)",
45:"eksen yok · **esmâ مُبِين *(apaçık)* 8. sırada — ÖLÇÜM ARTEFAKTI (aday 461)**: سُلْطَٰنٍۢ مُّبِينٍ *(apaçık delil)* tamlamasında niteleyen konumda; onarım ölçütü (c) · **aktör: adlı مُوسَى *(Mûsâ)* 3. sırada (fâil) ve هارُون *(Hârûn)* 5. sırada (mef'ûl)** · edim haber · şahıs 1P ×3 · 3MS 1 · n=8 mora=53 harf=38, fâsıla مُّبِينٍ → ن, N sınıfı; i'râb GEN 3 · NOM 2 · ACC 1; bab IV ×1; zaman PERF 1; dış düğüm 2 · yıldız ★ yok · kökler رسل *(gönderme, elçi)* · أخو *(kardeş)* · أيي *(âyet, işaret)* · سلط *(yetki, delil (sultan))* · بين *(arası; açıklama)* · bağ: xref آية *(âyet)* + سلطان *(delil)* + مبين *(apaçık)* → 11:96 · 40:23",
46:"eksen yok · **aktör: adlı فِرْعَوْن *(Firavun)* 2. sırada, tür 'kisi', rol mecrur** · edim haber · şahıs 3MP ×4 · 3MS 1 · n=7 mora=45 harf=42, fâsıla عَالِينَ *(üstünlük taslayanlar)* → ن, N sınıfı; i'râb GEN 2 · ACC 2; bab I ×1 · bab X ×1; zaman PERF ×2 · yıldız ★ yok · kökler ملأ *(ileri gelenler (meleʼ); doldurma)* · كبر *(büyüklük; büyüklenme)* · كون *(olmak)* · قوم *(kalkma; kavim; kıyamet)* · علو *(yücelik; böbürlenme)* · bağ: **23:24 · 23:33 · 23:46 — ملأ sûrede üçüncü kez, üçünde de karşı taraf, üçünde de aktör tablosuna girmiyor (aday 462)** (elle, L1)",
47:"eksen yok · aktör yok · edim soru, kip INTG 1 · şahıs 1P ×3 · 3MP ×2 · **3D 1 — sûrede ilk kez ikil şahıs** · n=7 mora=47 harf=38, fâsıla عَٰبِدُونَ *(kulluk edenler)* → ن, N sınıfı; i'râb GEN 2 · NOM 2; bab I ×1 · bab IV ×1; zaman PERF 1 · IMPF 1 · yıldız ★ yok · kökler قول *(söz söyleme)* · أمن *(güven; iman)* · بشر *(müjde; beşer)* · مثل *(benzer, mesel)* · قوم *(kalkma; kavim; kıyamet)* · عبد *(kul, kulluk)* · bağ: **23:24 · 23:33 · 23:34 · 23:47 — بشر مثل *(bizim gibi beşer)* kalıbı dördüncü kez, burada İKİL (بَشَرَيْنِ)**; ilk üçünde tekil (elle, L1, aday 473 kümesi)",
48:"eksen yok · aktör yok · edim haber · şahıs 3MP ×4 · 3D 1 · **n=4 mora=31 harf=25 — bloğun en kısa ayeti**, fâsıla ٱلْمُهْلَكِينَ *(helâk edilenler)* → ن, N sınıfı; i'râb GEN 1; bab I ×1 · bab II ×1; zaman PERF ×2 · yıldız ★ yok · kökler كذب *(yalan; yalanlama)* · كون *(olmak)* · هلك *(helâk)* · bağ: **23:41 ile iki helâk sonucu** — birincisi maddeyle (غُثَاء *(sel süprüntüsü)*), ikincisi sınıf adıyla (ٱلْمُهْلَكِينَ) (elle, L1)",
49:"eksen yok · **aktör: adlı مُوسَى *(Mûsâ)* 3. sırada, tür 'kisi', rol fâil** · edim haber, kip EMPH 1 · CERT 1 · şahıs 3MP ×3 · 1P ×2 · n=6 mora=39 harf=30, fâsıla يَهْتَدُونَ *(doğru yolu bulurlar)* → ن, N sınıfı; i'râb ACC 2 · NOM 1; bab IV ×1 · bab VIII ×1; zaman PERF 1 · IMPF 1 · yıldız ★ yok · kökler أتي *(gelme, getirme)* · كتب *(yazma, kitap)* · هدي *(yol gösterme)* · bağ: **23:12 · 23:17 · 23:23 · 23:49 — وَلَقَدْ *(andolsun)* açılışı sûrede dördüncü kez; nesneler: insan, konum, kişi, kitap** (elle, L1)",
50:"eksen yok · **aktör: adlı مَرْيَم *(Meryem)* 3. sırada, tür 'kisi', rol mef'ûl** · edim haber · şahıs 1P ×4 · 3MS 1 · 3D 1 · n=11 mora=70 harf=54, fâsıla مَعِينٍۢ *(akan su)* → ن, N sınıfı; i'râb ACC 4 · GEN 3 · NOM 1; bab I ×1 · bab IV ×1; zaman PERF ×2 · yıldız ★ yok · kökler جعل *(kılma, var etme)* · بني *(bina, yapma; evlat)* · أمم *(ümmet, topluluk; anne)* · أيي *(âyet, işaret)* · أوي *(sığınma)* · ربو *(artma, kabarma; tepe)* · قرر *(karar kılma; göz aydınlığı)* · عين *(göz; pınar)* · bağ: **23:13 ile ortak قرر** — orada قَرَارٍۢ مَّكِينٍ *(sağlam karargâh)* rahim bağlamında, burada ذَاتِ قَرَارٍۢ *(oturmaya elverişli)* tepe bağlamında (elle, L2)",
51:"eksen: lafız yok · **esmâ عَلِيم *(alîm)* 11. sırada = fâsıla — GEÇERLİ**: birinci tekil konuşanın kendi niteliği (إِنِّى … عَلِيمٌ *(ben bilenim)*); sûrenin üç geçerli esmâsından biri · aktör yok · edim emir + nida, kip VOC 1 · IMPV ×2 · şahıs 2MP ×6 · 1S 1 · n=11 mora=70 harf=53, **fâsıla عَلِيمٌۭ → م — sûrenin م ile biten dört ayetinden biri, sınıf yine N**; i'râb ACC 3 · NOM 2 · GEN 1; bab I ×3; zaman IMPV ×2 · IMPF 1; kök ikilemesi عمل *(iş, amel)* ×2 — biri emir biri muhatabın fiili; biçim DIKKAT; simetri [3,4,8,1]; dış düğüm 1 · yıldız ★ yok · kökler أيي *(âyet, işaret; hangi)* · رسل *(gönderme, elçi)* · أكل *(yeme)* · طيب *(temiz, hoş)* · عمل · صلح *(iyi, elverişli olma; ıslah)* · علم *(bilme)* · bağ: xref عمل + صالح *(iyi)* + عمل → 34:11; **23:33 ile ortak أكل** — orada yemek elçiliğe itiraz gerekçesiydi, burada elçilere emir (elle, L1)",
52:"eksen: lafız yok · **Rab 7. sırada, رَبُّكُمْ *(Rabbiniz)* — n=8'de tek Rab, rab z=2,34: yıldızın kaynağı** · aktör yok · edim emir, kip IMPV 1 · şahıs 2MP ×4 · 1S ×2 · n=8 mora=46 harf=36, fâsıla فَٱتَّقُونِ *(benden sakının)* → ن, N sınıfı; i'râb ACC 3 · NOM 2; bab VIII ×1; zaman IMPV 1; kök ikilemesi أمم *(ümmet, topluluk)* ×2; sayı sözcüğü وَاحِدَة *(bir)*; biçim DIKKAT; dış düğüm 1 · yıldız ★★ · kökler أمم · وحد *(bir olma, teklik)* · ربب *(rab, terbiye etme)* · وقي *(sakınma, koruma)* · bağ: **21:92 ile bölüt ikizi — BEKLEYEN BAĞ (aday 456) ÖLÇÜLDÜ ve ÖN-KAYIT DÜZELTİLDİ (aday 476)**: gövde altı kelime birebir aynı, iki uçta ayrışıyor — açılışta bağlaç (إِنَّ / وَإِنَّ), kapanışta imperatif (فَٱعْبُدُونِ *(bana kulluk edin)*, عبد bab I / فَٱتَّقُونِ, وقي bab VIII). Ön-kayıt 'fark TAM OLARAK imperatifte' diyordu; ölçüm İKİ fark verdi (elle, L1)",
53:"eksen yok · aktör yok · edim haber · şahıs 3MP ×5 · **iltifât 1 (12>3)** · n=9 mora=50 harf=43, fâsıla فَرِحُونَ *(sevinenler)* → ن, N sınıfı; i'râb ACC 3 · NOM 2 · GEN 1; bab V ×1; zaman PERF 1; dış düğüm 2 · yıldız ★ yok · kökler قطع *(kesme)* · أمر *(emir; iş)* · بين *(arası; açıklama)* · زبر *(yazılı parça, Zebûr)* · كلل *(hep, bütün)* · حزب *(hizip, taraf tutan grup)* · فرح *(sevinç, şımarma)* · bağ: **21:93 ile bölüt ikizi (adaylar 456, 476)** — ortak gövde yalnız أَمْرَهُم بَيْنَهُمْ *(işlerini aralarında)*, زُبُرًۭا *(parçalara)* eklenmiş, ikinci yarılar tamamen farklı; xref تقطّع + أمر + بين → 21:93 · كلّ حزب *(her hizip)* + فرح *(sevinç)* → **30:32** (elle, L1)",
54:"eksen yok · aktör yok · edim emir, kip IMPV 1 · şahıs 3MP ×2 · 2MS 1 · n=5 mora=25 harf=19, fâsıla حِينٍ *(bir vakit)* → ن, N sınıfı; i'râb GEN 2; bab I ×1; zaman IMPV 1 · yıldız ★ yok · kökler وذر *(bırakma)* · غمر *(gaflet dalgası; batıp örtülme)* · حين *(vakit)* · bağ: **23:25 ile aynı zaman kalıbı** حَتَّىٰ حِينٍ *(bir süreye kadar)* — orada itiraz edenlerin elçi hakkındaki buyruğu, burada elçiye verilen buyruk; kalıp taraf değiştiriyor (elle, L1, aday 479)",
55:"eksen yok · aktör yok · edim soru, kip INTG 1 · şahıs 3MP ×3 · 1P 1 · 3MS 1 · n=7 mora=38 harf=30, fâsıla بَنِينَ *(oğullar)* → ن, N sınıfı; i'râb ACC 1 · GEN 2; bab I ×1 · bab IV ×1; zaman IMPF ×2; dış düğüm 2 · yıldız ★ yok · kökler حسب *(hesap, sayma)* · مدد *(uzatma, destekleme)* · مول *(mal)* · بني *(bina, yapma; evlat)* · bağ: xref أمدّ *(destekledi)* + مال *(mal)* + بنين *(oğullar)* → **17:6 · 71:12**; **23:56 ile tek cümle** — soru bir sonraki ayette tamamlanıyor (elle, L1)",
56:"eksen yok · aktör yok · edim haber, kip NEG 1 · şahıs 3MP ×3 · 1P 1 · n=7 mora=33 harf=27, fâsıla يَشْعُرُونَ *(farkına varırlar)* → ن, N sınıfı; i'râb GEN 1; bab I ×1 · bab III ×1; zaman IMPF ×2; **biçim IDRAB** — sûrenin altı IDRAB'ından biri; simetri [3,2,5,1] · yıldız ★ yok · kökler سرع *(hız, sürat)* · خير *(hayır, daha iyi)* · شعر *(şair; farkında olma)* · bağ: **23:61 ile karşıtlık** — aynı سرع kökü orada dönüyor ve koşanlar mü'minler (elle, L1)",
57:"eksen: lafız yok · **Rab 6. sırada, رَبِّهِم *(Rableri)* — n=7'de tek Rab, rab z=2,72** · aktör yok · edim haber · şahıs 3MP ×2 · n=7 mora=34 harf=25, fâsıla مُّشْفِقُونَ *(içi titreyerek korkanlar)* → ن, N sınıfı; i'râb GEN 2 · ACC 1 · NOM 1; **fiil yok** · yıldız ★★ · kökler خشي *(haşyet, saygıyla korkma)* · ربب *(rab, terbiye etme)* · شفق *(şafak; işfak, içi titreyerek korkma)* · bağ: **23:2-9 ile aynı zincir kalıbı — SÛRENİN İKİNCİ SIFAT ZİNCİRİ AÇILIYOR** (elle, L1, aday 477)",
58:"eksen: lafız yok · **Rab 4. sırada, رَبِّهِمْ *(Rableri)* — n=5'te tek Rab, rab z=3,94: yıldızın tek kaynağı (aday 472)** · aktör yok · edim haber · şahıs 3MP ×4 · n=5 mora=30 harf=23, fâsıla يُؤْمِنُونَ *(inanırlar)* → ن, N sınıfı; i'râb GEN 2; bab IV ×1; zaman IMPF 1 · yıldız ★★★ · kökler أيي *(âyet, işaret)* · ربب *(rab, terbiye etme)* · أمن *(güven; iman)* · bağ: **23:1 ile ortak أمن** — orada ism-i fâil çoğulu ve niteleme, burada çekimli fiil; **23:59 ile bitişik ikiz kalıp** (elle, L1, aday 477)",
59:"eksen: lafız yok · **Rab 3. sırada, بِرَبِّهِمْ *(Rablerine)* — n=5'te tek Rab, rab z=3,94: yıldızın tek kaynağı (aday 472)** · aktör yok · edim haber, kip NEG 1 · şahıs 3MP ×4 · n=5 mora=28 harf=21, fâsıla يُشْرِكُونَ *(ortak koşarlar)* → ن, N sınıfı; i'râb GEN 1; bab IV ×1; zaman IMPF 1 · yıldız ★★★ · kökler ربب *(rab, terbiye etme)* · شرك *(ortak koşma)* · bağ: **23:58 ile bitişik ikiz kalıp** — aynı uzunluk (n=5), aynı bab (IV), aynı zaman (IMPF); tek fark لَا *(değil)* parçacığı (elle, L1, aday 477)",
60:"eksen: lafız yok · **Rab 9. sırada, رَبِّهِمْ *(Rableri)* — rab z=1,81** · aktör yok · edim haber · şahıs 3MP ×7 · n=10 mora=61 harf=46, fâsıla رَٰجِعُونَ *(dönenler)* → ن, N sınıfı; i'râb NOM 3 · ACC 1 · GEN 1; bab IV ×2; zaman IMPF 1 · PERF 1; **kök ikilemesi أتي *(gelme, getirme; verme)* ×2 — biri IMPF biri PERF** · yıldız ★ · kökler أتي · قلب *(çevirme; kalp)* · وجل *(ürperme, korku)* · ربب *(rab, terbiye etme)* · رجع *(dönme, geri döndürme)* · bağ: **21:93 ile ortak رجع** — orada كُلٌّ إِلَيْنَا رَٰجِعُونَ *(hepsi bize dönecek)*, burada إِلَىٰ رَبِّهِمْ رَٰجِعُونَ *(Rablerine dönecekler)*; 23:53'te düşen ikinci yarı yedi ayet sonra geri geliyor (elle, L1, aday 478)",
}

MERCEK={
41:"İkinci döngünün sonucu üç fiille veriliyor ve fâil ikisinde farklı: alan ٱلصَّيْحَة *(çığlık)*, kılan birinci çoğul. Araya bir aracı konuyor ve aracı bir sestir. Sonuç maddesi ölçülebilir biçimde seyrek: غُثَاء *(sel süprüntüsü)* korpusta iki geçişli — burada ve 87:5 — ve komşuluğunda eşik üstü hiçbir kavram yok, yalıtık duruyor. Kapanış çekimsiz: فَبُعْدًۭا *(uzak olsun)*, masdar-ı mansûb, fiilsiz bir beddua kalıbı.",
42:"Bekleyen bağ ölçüldü ve fark tek bir yerde: 23:31 قَرْنًا *(bir nesil)* tekil, 23:42 قُرُونًا *(nesiller)* çoğul. Kalan beş kelime harfi harfine aynı; mora 35 → 37 ve harf 26 → 27 farkı da yalnız bu çoğullaştırmadan geliyor. Birinci geçişte tek bir topluluk anlatılacaktı ve anlatıldı (23:31-41); ikinci geçişte kalan bütün topluluklar tek çoğulda toplanıyor ve tek tek anlatılmıyor. Sayı eki anlatının ölçeğini değiştiriyor.",
43:"Yedi kelimede iki olumsuzlama ve iki karşıt fiil: سبق *(geçme, öne geçme)* ve أخر *(erteleme)*. İkisi de aynı olumsuz kalıpla bağlandığı için zaman iki yönde birden kapatılıyor. Bab seçimi ölçülebilir bir asimetri taşıyor: birinci fiil bab I ve dişil tekil (ümmete uyuyor), ikincisi bab X ve eril çoğul (ümmetin bireylerine geçiyor) — özne aynı cümlede tekil topluluktan çoğul kişilere kayıyor.",
44:"Ayet, önceki on ayetin tek tek anlattığını bir formüle indiriyor: elçi gelir, yalanlanır, topluluk anlatıya dönüşür. Ardıllık üç ayrı sözcükle üst üste işaretleniyor — تَتْرَا *(ard arda)*, فَأَتْبَعْنَا *(peşi sıra getirdik)*, بَعْضَهُم بَعْضًۭا *(kimini kiminin ardından)*. Son dönüşüm ölçülebilir biçimde tuhaf: topluluklar أَحَادِيث *(anlatılar)* kılınıyor, yani helâk bir yok oluş değil bir tür değişimi olarak yazılıyor — varlıktan söze.",
45:"Üçüncü döngü ثُمَّ أَرْسَلْنَا *(sonra gönderdik)* ile açılıyor — 23:44'ün de açılışı. Ama bu kez elçi hem adlandırılıyor hem ikileniyor: sûrede ilk kez iki kişi adı aynı ayette. İkincisi birinciye bir akrabalık terimiyle bağlanıyor (أَخَاهُ *(kardeşi)*), yani ad tek başına değil ilişkiyle veriliyor. Gönderilenin yanına iki araç konuyor ve ikisi çoğul/tekil karşıtlığında: ءَايَٰت *(âyetler)* çoğul, سُلْطَٰن *(delil)* tekil.",
46:"Muhatap bu kez adlandırılıyor ve yanına aynı topluluk terimi konuyor: مَلَإِي۟ه *(onun ileri gelenleri)*. ملأ *(ileri gelenler (meleʼ); doldurma)* kökü sûrede üçüncü ve üçünde de itiraz eden taraf. Tepki iki kökle veriliyor ve ikisi de yükseklik alanından: كبر *(büyüklük; büyüklenme)* bab X'te, yani 'kendini büyük görmek', ve علو *(yücelik; böbürlenme)* ism-i fâil çoğulunda. 23:24'ün فضل *(üstün kılma, lütuf)* bab V'i de aynı hamleydi: üstünlük her seferinde bir dönüşlü ya da istek kalıbıyla adlandırılıyor.",
47:"İtiraz kalıbı üçüncü döngüde de aynı, ama iki ölçülebilir değişiklikle: (1) sayı — بَشَرَيْنِ *(iki beşer)*, tesniye, çünkü bu kez elçi iki kişi; kalıp gönderdiğine göre çekimleniyor. (2) karşılaştırma yönü — önceki itirazlarda 'bizim gibi' bir eşitlik iddiasıydı, burada eşitliğin yanına bir üstünlük iddiası ekleniyor: وَقَوْمُهُمَا لَنَا عَٰبِدُونَ *(kavimleri bize kulluk ediyor)*. عبد *(kul, kulluk)* kökü sûrede ilk kez ilâhî olmayan bir muhataba yöneliyor — 23:23 ve 23:32'de ٱعْبُدُوا۟ ٱللَّهَ *(Allah'a kulluk edin)* idi.",
48:"Dört kelime, iki fiil, ve fiiller arasında tek bir bağlaç: yalanlama ile helâk arasına hiçbir aşama konmuyor. Üçüncü döngü bu yüzden ölçülebilir biçimde en kısası — birinci döngü sekiz ayet (23:23-30), ikinci on bir (23:31-41), üçüncüsü dört (23:45-48). Sonuç ism-i mef'ûl çoğuluyla veriliyor: مُهْلَكِينَ *(helâk edilenler)*, fâil yine silinmiş, ama bu kez bir sınıfa üyelik olarak yazılıyor (مِنَ *(...dan)* ile).",
49:"Açılış formülü dördüncü kez ve her seferinde başka bir nesne alıyor: insan (23:12), konum (23:17), kişi (23:23), şimdi kitap. Aynı üç kelimelik giriş bedeni, göğü, elçiyi ve metni aynı düzleme koyuyor. Ve bu ayet döngü şemasını kırıyor: helâk 23:48'de kapanmıştı, ardından gelen cümle geriye dönüyor ve aynı elçiye ikinci kez, farklı bir araçla veriliyor. Sonuç cümlesi de kesin değil, umut kipinde: لَعَلَّ *(belki)*.",
50:"Anlatının en kısa kıssası: bir ayet, iki kişi, hiç konuşma yok. İkisi de adlandırılmıyor — biri ilişkiyle (ٱبْنَ مَرْيَمَ *(Meryem oğlu)*), öteki akrabalıkla (أُمَّهُۥ *(annesi)*); adı verilen tek kişi ikisinin de bağlandığı kadın. İkisi birlikte tekil bir yükleme bağlanıyor: ءَايَةًۭ *(bir âyet)* — iki kişi, tek işaret. Yerin niteliği iki tamlamayla veriliyor ve ikisi de barınma koşulu: قَرَار *(durulacak yer)* ve مَعِين *(akan su)*. 23:13'te aynı قرر *(karar kılma; göz aydınlığı)* kökü rahmi adlandırıyordu; iki yerde de kök bir korunma yerini niteliyor.",
51:"Nidâ ölçülebilir biçimde tuhaf bir muhataba yöneliyor: ٱلرُّسُل *(elçiler)*, çoğul ve belirli — kıssalar boyunca tek tek anlatılan elçiler tek seslenişte toplanıyor. Emir tam olarak itirazın konusunu tekrarlıyor: 23:33'te 'yiyor, içiyor' diye kusur sayılan şey burada buyruk oluyor. İki emir arasında bir işbölümü var: biri alma (كُلُوا۟ *(yiyin)*), öteki yapma (ٱعْمَلُوا۟ *(işleyin)*); ikisi de bab I. Ve kapanışta konuşan ilk kez birinci tekile geçiyor — sûre boyunca hep birinci çoğuldu.",
52:"Bekleyen bağın ölçümü ön-kaydı düzeltiyor. Gövde altı kelime boyunca 21:92 ile özdeş: هَٰذِهِۦٓ أُمَّتُكُمْ أُمَّةًۭ وَٰحِدَةًۭ وَأَنَا۠ رَبُّكُمْ *(bu sizin ümmetiniz, tek bir ümmet; ben de sizin Rabbinizim)*. Ayrışma iki uçta: açılışta bir bağlaç (إِنَّ / وَإِنَّ *(muhakkak / ve muhakkak)*), kapanışta imperatif — فَٱعْبُدُونِ *(bana kulluk edin)*, عبد *(kul, kulluk)* bab I / فَٱتَّقُونِ *(benden sakının)*, وقي *(sakınma, koruma)* bab VIII. Ön-kayıt farkın 'tam olarak imperatifte' olmasını bekliyordu; ölçüm iki fark verdi.",
53:"İkinci ayette ayrışma çok daha geniş: ortak gövde yalnız أَمْرَهُم بَيْنَهُمْ *(işlerini aralarında)*, açılış bağlacı değişiyor (وَ / فَ), 23:53'e زُبُرًۭا *(parçalara)* ekleniyor ve ikinci yarılar tamamen ayrılıyor. Ama kalıp korunuyor: iki ikinci yarı da كُلّ *(her)* ile başlıyor ve ism-i fâil çoğuluyla bitiyor — biri dönüşü (رَٰجِعُونَ *(dönenler)*), öteki yerinde kalmayı (فَرِحُونَ *(sevinenler)*) bildiriyor. Ve iltifât tam burada: 23:52 birinci tekilken 23:53 üçüncü çoğula geçiyor.",
54:"Aynı üç kelimelik zaman kalıbı sûrede ikinci kez ve tam tersine dönmüş: 23:25'te reddedenler 'bir süreye kadar onu gözetleyin' diyordu, burada elçiye 'onları bir süreye kadar bırak' deniyor. Fiiller de karşıt yönde — تَرَبَّصُوا۟ *(gözetleyin)* bab V ve dikkat gerektiriyor, ذَرْ *(bırak)* bab I ve dikkati kesiyor. غَمْرَة *(gaflet dalgası)* korpusta dört geçişli, ikisi bu sûrede (23:54 ve 23:63); komşuluğunda eşik üstü kavram yok.",
55:"Soru cümlesi bir sonraki ayete taşıyor — bu blokta kendi ayetiyle kapanmayan tek yapı. مال *(mal)* ve بنون *(oğullar)* çifti korpusta üç yerde birlikte ve üçünde de aynı fiil kökü: مدد *(uzatma, destekleme)* bab IV. Mal-evlât ikilisi bir 'uzatma' fiiliyle adlandırılıyor, verme fiiliyle değil.",
56:"Sorunun ikinci yarısı ve reddi tek ayette. Red بَلْ *(hayır)* ile yapılıyor — cümlenin doğruluğu değil, sanılan şeyin yönü tersine çevriliyor. سرع *(hız, sürat)* kökü bab III'te, yani karşılıklılık kalıbında: koşma bir yarış gibi adlandırılıyor. Kökün komşuluğu ölçümde hesapla eşleşiyor (hesap ×51,4) ve sorunun ilk kelimesi zaten أَيَحْسَبُونَ *(sanıyorlar mı)* — aynı alan, iki ayet arayla, biri sanı biri hesap.",
57:"Sûrenin açılış zinciri burada ikinci kez kuruluyor ve kalıp birebir aynı: إِنَّ ٱلَّذِينَ هُم *(onlar ki)* + mecrur + ism-i fâil, fiil yok. Ama ölçülebilir bir eksen değişimi var: birinci zincirin halkaları eylemlere bağlıydı (namaz, boş söz, zekât, ırz, emanet), bu zincirin halkaları Rab'be bağlanıyor — üç ardışık ayette üç kez رَبّ *(Rab)*. İki eş kök yan yana: خشي *(haşyet, saygıyla korkma)* ve شفق *(içi titreyerek korkma)*, ve dikey ölçüm ikisinin korpusta zaten eşleştiğini veriyor (خشي ▸sonra işfak-korku ×45,3).",
58:"İkinci zincirin ikinci halkası ve kalıp ilk zincirdeki gibi kırılıyor: yüklem ism-i fâil olmaktan çıkıp çekimli fiile geçiyor (يُؤْمِنُونَ *(inanırlar)*, IMPF, bab IV). Birinci zincirde bu geçiş kapanışta olmuştu (23:9); burada ikinci halkada oluyor. Zincirin sözlüğü ölçülebilir biçimde daralıyor: beş kelimede iki isim, biri âyet biri Rab, ikisi de tamlamada.",
59:"Üçüncü halka ikinciyle neredeyse özdeş ve fark tek bir parçacıkta: لَا *(değil)*. İki ayet aynı kalıbı, aynı uzunluğu (n=5), aynı babı (IV) ve aynı zamanı taşıyor; biri kabul biri ret bildiriyor. Zincir bir olumlu-olumsuz çifti kuruyor ve bunu en küçük dilsel birimle yapıyor. Ayet sûrenin en az köklü ayetlerinden: iki kök, biri Rab.",
60:"Dördüncü halka kalıbı ilk kez uzatıyor: n=10, öncekilerin ikisinden fazla, ve ٱلَّذِينَ *(onlar ki)* ardından هُم *(onlar)* pekiştirmesi düşüyor. Aynı kök iki zamanda geçiyor — يُؤْتُونَ *(verirler)* IMPF, ءَاتَوا۟ *(verdikleri)* PERF: verme hem sürüyor hem olmuş sayılıyor. Gerekçe bir beden terimiyle veriliyor: قُلُوبُهُمْ وَجِلَةٌ *(kalpleri ürperir)*. وجل *(ürperme, korku)* bu zincirde خشي *(haşyet)* ve شفق *(içi titreyerek korkma)* ile birlikte üçüncü korku kökü — dört halkanın üçü aynı duygu alanından.",
}

ATLAMA={
 "23:58":"★★★ ayet. 🜁 biyolog YAZILMADI — üç kökün hiçbiri (أيي *(âyet, işaret)* · ربب *(rab, terbiye etme)* · أمن *(güven; iman)*) canlıya, organa ya da sürece bağlanmıyor. 🜂 uzay YAZILMADI — أيي korpusta hem 'gök işareti' hem 'metin âyeti' işlevinde; burada رَبِّهِمْ *(Rableri)* tamlaması ve أمن eşleşmesi göndergeyi işaret/vahiy tarafına sabitliyor. Gönderge belirliyken astronomik okumayı seçmek yasaklı 'bilimsel izdüşüm' olurdu.",
 "23:59":"★★★ ayet. 🜁 biyolog ve 🜂 uzay YAZILMADI — iki kök (ربب *(rab, terbiye etme)* · شرك *(ortak koşma)*) hiçbir biyolojik ya da astronomik çıpa vermiyor.",
 "_blok_notu_41_60":"Blok 23:41-60'ta iki ★★★ ayet (58, 59), ikisinde de iki uzman merceği atlandı; ikisinin de yıldız kaynağı rab z=3,94 ve ikisi de n=5. Sûre 23'te bugüne dek okunan yedi ★★★ ayetin YEDİSİNDE de biyolog ve uzay atlandı. Buna karşılık blokta biyolojik/coğrafî öğe taşıyan ayetler ★ almadı: 23:50 (رَبْوَة *(tepe)* · مَعِين *(akan su)*) ★ yok, 23:41 (غُثَاء *(sel süprüntüsü)*) ★ yok. Adaylar 468 ve 472.",
}

p='/home/claude/repo/notlar/okuma_metni.json'
OM=json.load(open(p,encoding='utf-8'))
for n in range(41,61):
    OM['23']["23:%d"%n]={"ar":AR[(23,n)],"meal":MEAL[n],"olcum":OLCUM[n],
                         "mercek":MERCEK[n],"dikey":DIK["23:%d"%n]}
OM['23']['_mercek_atlama_notu'].update(ATLAMA)
OM['ilerleme']['not']=("Sûre 22 TAM (78/78). Sûre 23 (Mü'minûn) makro profil + 23:1-60 okundu. "
                       "Devam: 23:61. İkinci sıfat zinciri 23:57'de açıldı, kapanışı 23:61'de ölçülecek.")
OM['ilerleme']['kismi']={"2":"1-20 ayet düzeyinde","23":"1-60 ayet düzeyinde"}
OM['ilerleme']['okunan_ayet']=1523
json.dump(OM,open(p,'w',encoding='utf-8'),ensure_ascii=False,indent=1)
print('okuma_metni: sûre 23 →',len([k for k in OM['23'] if not k.startswith('_')]),'ayet')

pm='/home/claude/repo/notlar/mercek_kayit.json'
MK=json.load(open(pm,encoding='utf-8'))
for n in range(41,61): MK['23']["23:%d"%n]=MERCEK[n]
MK['23_atlama'].update(ATLAMA)
json.dump(MK,open(pm,'w',encoding='utf-8'),ensure_ascii=False,indent=1)
print('mercek_kayit: sûre 23 →',len(MK['23']),'mercek')
