# -*- coding: utf-8 -*-
"""blok_23_21_40.py — sûre 23 ikinci blok kaydı."""
import json
DIK=json.load(open('blok_dikey_23_21_40.json',encoding='utf-8'))
veri=json.load(open('kuran_veri.json',encoding='utf-8'))
AR={}
for s in veri['sureler']:
    for a in s['ayetler']: AR[(s['no'],a['no'])]=a['ar']

MEAL={
21:"Davarlarda da sizin için bir ibret var: karınlarındakinden size içiriyoruz; onlarda sizin için çok fayda var, onlardan yiyorsunuz.",
22:"Onların üzerinde de geminin üzerinde de taşınıyorsunuz.",
23:"Andolsun, Nûh'u kavmine gönderdik. Dedi ki: Ey kavmim, Allah'a kulluk edin; sizin için O'ndan başka ilâh yok. Sakınmaz mısınız?",
24:"Kavminden inkâr eden ileri gelenler dedi ki: Bu ancak sizin gibi bir beşer; size üstün gelmek istiyor. Allah dileseydi melekler indirirdi. Biz bunu önceki atalarımızda işitmedik.",
25:"O, kendisinde delilik olan bir adamdan başkası değil. Bir süreye kadar onu gözetleyin.",
26:"Dedi ki: Rabbim, beni yalanlamalarına karşı bana yardım et.",
27:"Ona vahyettik: Gözlerimizin önünde ve vahyimizle gemiyi yap. Buyruğumuz gelip tandır kaynadığında, her türden ikişer eş ile aileni ona sok — aleyhlerine söz geçmiş olanlar dışında. Zulmedenler hakkında bana hitap etme; onlar boğulacaklardır.",
28:"Sen ve seninle olanlar gemiye yerleştiğinizde de ki: Hamd, bizi zalim kavimden kurtaran Allah'a aittir.",
29:"Ve de ki: Rabbim, beni bereketli bir konağa indir; sen indirenlerin en hayırlısısın.",
30:"Bunda elbette âyetler var. Biz gerçekten sınayanlarız.",
31:"Sonra onların ardından başka bir nesil inşa ettik.",
32:"Onların içinde, kendilerinden bir elçi gönderdik: Allah'a kulluk edin; sizin için O'ndan başka ilâh yok. Sakınmaz mısınız?",
33:"Kavminden inkâr eden, âhirete kavuşmayı yalanlayan ve dünya hayatında refaha boğduğumuz ileri gelenler dedi ki: Bu ancak sizin gibi bir beşer; sizin yediğinizden yiyor, içtiğinizden içiyor.",
34:"Kendiniz gibi bir beşere itaat ederseniz, o zaman elbette hüsrandasınız.",
35:"Size, öldüğünüzde toprak ve kemik olduğunuzda çıkarılacağınızı mı vaat ediyor?",
36:"Ne uzak, ne uzak size vaat edilen şey!",
37:"O, dünya hayatımızdan başkası değil; ölürüz ve yaşarız, biz diriltilecek de değiliz.",
38:"O, Allah'a karşı yalan uyduran bir adamdan başkası değil; biz ona inanacak değiliz.",
39:"Dedi ki: Rabbim, beni yalanlamalarına karşı bana yardım et.",
40:"Dedi ki: Az sonra pişman olacaklar.",
}

OLCUM={
21:"eksen yok · aktör yok · edim haber, kip EMPH 1 · şahıs 2MP ×5 · 3FS ×3 · 1P 1 · n=15 mora=83 harf=67, fâsıla تَأْكُلُونَ *(yersiniz)* → ن, N sınıfı; i'râb ACC 2 · GEN 2 · NOM 2; bab I ×1 · bab IV ×1; zaman IMPF ×2; sayı sözcüğü كَثِيرَة *(çok)*; simetri [3,1,7,1]; dış düğüm 1 · yıldız ★ yok · kökler نعم *(nimet; davar)* · عبر *(ibret; geçme, tabir etme)* · سقي *(sulama)* · بطن *(karın, iç)* · نفع *(fayda)* · كثر *(çokluk)* · أكل *(yeme)* · bağ: xref نعم *(davar)* + عبرة *(ibret)* + أسقي *(içirdi)* → **16:66**; **23:19 ile ortak kapanış** — iki ayet de وَمِنْهَا تَأْكُلُونَ *(onlardan yersiniz)* ile bitiyor (elle, L1)",
22:"eksen yok · aktör yok · edim haber · şahıs 2MP ×2 · 3FS 1 · **n=4 mora=26 harf=21 — bloğun en kısa iki ayetinden biri**, fâsıla تُحْمَلُونَ *(taşınırsınız)* → ن, N sınıfı; i'râb GEN 1; bab I ×1; zaman IMPF 1; **edilgen 1 — n=4'te tek fiil ve o fiil edilgen, pas z=5,38: yıldızın tek kaynağı (aday 472)** · yıldız ★★★ · kökler فلك *(gemi, felek)* · حمل *(yüklenme, taşıma)* · bağ yok",
23:"eksen: **Allah lafzı 9. sırada** (allah z=0,72) · **aktör: adlı نُوح *(Nûh)* 3. sırada, tür 'kisi', rol mef'ûl — sûrenin ilk kişi adı** · edim soru + emir + nida, kip EMPH 1 · CERT 1 · VOC 1 · IMPV 1 · NEG 2 · INTG 1 · şahıs 2MP ×5 · 3MS ×3 · 1P ×2 · 1S 1 · n=16 mora=84 harf=66, fâsıla تَتَّقُونَ *(sakınırsınız)* → ن, N sınıfı; i'râb ACC 2 · GEN 2 · NOM 2; bab I ×2 · bab IV ×1 · bab VIII ×1; zaman PERF ×2 · IMPV 1 · IMPF 1; **kök ikilemesi قوم *(kalkma; kavim; kıyamet)* ×2 · أله *(ilâh; lafza-i celâl)* ×2 — ikincisi lafız + cins isim**; simetri [3,1,10,1]; **dış düğüm 8 — bloğun en bağlı ayeti** · yıldız ★ yok · kökler رسل *(gönderme, elçi)* · قوم · قول *(söz söyleme)* · عبد *(kul, kulluk)* · أله · غير *(başka)* · وقي *(sakınma, koruma)* · bağ: xref عبد *(kulluk)* + اللّه *(Allah)* + إله *(ilâh)* + غير *(başka)* → **7:59 · 7:65 · 7:73 · 7:85 · 11:50 · 11:61 · 11:84 ve 23:32**; **23:32 ile sûre-içi bölüt ikizi** (elle, L1, aday 473)",
24:"eksen: **Allah lafzı 18. sırada** (allah z=0,24) · aktör yok — ٱلْمَلَؤُا۟ *(ileri gelenler)* aktör tablosuna girmiyor (**aday 462 kapsamında**) · edim şart, kip NEG 2 · RES 1 · COND 1 · EMPH 1 · şahıs 3MS ×6 · 1P ×3 · 3MP ×2 · 2MP ×2 · **n=26 mora=143 harf=110 — bloğun en uzun ikinci ayeti** (n z=1,44), fâsıla ٱلْأَوَّلِينَ *(öncekiler)* → ن, N sınıfı; i'râb NOM 4 · GEN 3 · ACC 1; bab I ×4 · bab IV ×2 · bab V ×1; zaman PERF ×5 · IMPF ×2; biçim HASR · DIKKAT; simetri [4,5,13,1]; dış düğüm 5 · yıldız ★ yok · kökler قول *(söz söyleme)* · ملأ *(ileri gelenler (meleʼ); doldurma)* · كفر *(inkâr, nankörlük)* · قوم *(kalkma; kavim; kıyamet)* · بشر *(müjde; beşer)* · مثل *(benzer, mesel)* · رود *(isteme, dileme)* · فضل *(üstün kılma, lütuf)* · شيأ *(dileme; şey)* · أله *(ilâh; lafza-i celâl)* · نزل *(inme, indirme)* · ملك *(mülk; melik)* · سمع *(işitme)* · أبو *(baba)* · أول *(ilk, evvel)* · bağ: xref قال *(dedi)* + ملأ *(ileri gelenler)* + كفر *(inkâr)* → 7:66 · 7:90 · 11:27; **23:33 ile sûre-içi bölüt ikizi** (elle, L1, aday 473)",
25:"eksen yok · **aktör: adsız racül *(bir adam)* 4. sırada** · edim emir, kip NEG 1 · RES 1 · IMPV 1 · şahıs 3MS ×3 · 2MP ×2 · n=10 mora=42 harf=36, fâsıla حِينٍۢ *(bir vakit)* → ن, N sınıfı; i'râb NOM 2 · GEN 1; bab V ×1; zaman IMPV 1; biçim HASR; simetri [3,1,8,1] · yıldız ★ yok · kökler رجل *(adam; yaya)* · جنن *(örtme, gizleme; cennet; cin)* · ربص *(bekleyip gözetme)* · حين *(vakit)* · bağ: **ÖLÇÜM ARTEFAKTI (aday 474, 452 sınıfı)** — kavram katmanı جنن *(örtme, gizleme; cennet; cin)* için 'cennet' veriyor, oysa lemma جِنَّة *(delilik)*; aynı hata 7:184'te belgeliydi",
26:"eksen: lafız yok · **Rab 2. sırada, رَبِّ *(Rabbim)* — n=5'te tek Rab, rab z=3,94: yıldızın tek kaynağı (aday 472)** · aktör yok · edim emir, kip IMPV 1 · şahıs 1S ×3 · 3MP ×2 · 3MS 1 · 2MS 1 · n=5 mora=26 harf=19, fâsıla كَذَّبُونِ *(beni yalanladılar)* → ن, N sınıfı; i'râb NOM 1; bab I ×2 · bab II ×1; zaman PERF ×2 · IMPV 1; **nakarat 2**; dış düğüm 1 · yıldız ★★★ · kökler قول *(söz söyleme)* · ربب *(rab, terbiye etme)* · نصر *(yardım)* · كذب *(yalan; yalanlama)* · bağ: **tam-ayet ikizi 23:39** — sûre içi; xref قال *(dedi)* + ربّ *(Rab)* + نصر *(yardım)* → 23:39 ve **29:30** (aday 473)",
27:"eksen yok · aktör yok · edim emir, kip IMPV 2 · RES 1 · NEG 1 · şahıs 1P ×5 · 3MS ×5 · 3MP ×4 · 2MS ×3 · 3FS ×2 · 1S 1 · **n=32 mora=168 harf=142 — SÛRENİN EN UZUN AYETİ** (n z=2,08), fâsıla مُّغْرَقُونَ *(boğulacak olanlar)* → ن, N sınıfı; i'râb NOM 6 · ACC 3 · GEN 3; bab I ×6 · bab III ×1 · bab IV ×1; zaman PERF ×5 · IMPV ×2 · IMPF 1; kök ikilemesi وحي *(vahiy, gizli bildirim)* ×2 — biri fiil biri isim; sayı sözcüğü زَوْج *(eş, çift)* ve اثْنَيْن *(iki)*; biçim HASR; simetri [4,12,23,1]; dış düğüm 2 · yıldız ★★ · kökler وحي · صنع *(yapma, işleme)* · فلك *(gemi, felek)* · عين *(göz; pınar)* · جيأ *(gelme)* · أمر *(emir; iş)* · فور *(kaynama, fışkırma; hemen)* · سلك *(sokma, yola girme)* · كلل *(hep, bütün)* · زوج *(eş, çift)* · ثني *(iki; yan çevirme)* · أهل *(halk, aile)* · سبق *(geçme, öne geçme)* · قول *(söz söyleme)* · خطب *(mesele, iş; hitap)* · ظلم *(zulüm)* · غرق *(boğulma)* · bağ: **xref sekiz ayrı 3-gram, ikisi 11:37'ye üçü 11:40'a** — صنع *(yapma)* + فلك *(gemi)* + عين *(göz)* → 11:37 · جاء *(geldi)* + أمر *(emir)* + فار *(kaynadı)* → 11:40 · كلّ *(hep)* + زوج *(çift)* + اثنين *(iki)* → 11:40",
28:"eksen: **Allah lafzı 10. sırada** (allah z=0,81) · aktör yok · edim emir, kip IMPV 1 · şahıs 2MS ×5 · 3MS 1 · 1P 1 · n=15 mora=73 harf=61, fâsıla ٱلظَّٰلِمِينَ *(zalimler)* → ن, N sınıfı; i'râb GEN 4 · ACC 1 · NOM 1; bab I ×1 · bab II ×1 · bab VIII ×1; zaman PERF ×2 · IMPV 1; simetri [3,1,4,1]; dış düğüm 2 · yıldız ★ yok · kökler سوي *(düzenleme, denk kılma)* · فلك *(gemi, felek)* · قول *(söz söyleme)* · حمد *(hamd, övgü)* · أله *(ilâh; lafza-i celâl)* · نجو *(kurtulma, kurtarma)* · قوم *(kalkma; kavim; kıyamet)* · ظلم *(zulüm)* · bağ: xref نجّى *(kurtardı)* + قوم *(kavim)* + ظالم *(zalim)* → 28:21 · 66:11",
29:"eksen: lafız yok · **Rab 2. sırada, رَّبِّ *(Rabbim)* — n=8'de tek Rab, rab z=2,34: yıldızın kaynağı** · aktör yok · edim emir, kip IMPV ×2 · şahıs 2MS ×3 · 1S ×2 · n=8 mora=52 harf=39, fâsıla ٱلْمُنزِلِينَ *(indirenler)* → ن, N sınıfı; i'râb ACC 3 · NOM 1 · GEN 1; bab I ×1 · bab IV ×1; zaman IMPV ×2; **kök ikilemesi نزل *(inme, indirme)* ×3 — n=8'de üç kez: fiil, ism-i mekân, ism-i fâil çoğulu**; dış düğüm 1 · yıldız ★★ · kökler قول *(söz söyleme)* · ربب *(rab, terbiye etme)* · نزل · برك *(bereket)* · خير *(hayır, daha iyi)* · bağ: xref قال *(dedi)* + ربّ *(Rab)* + أنزل *(indirdi)* → 28:24",
30:"eksen yok · aktör yok · edim haber, kip EMPH ×2 · CERT 1 · şahıs 1P ×2 · n=7 mora=35 harf=26, fâsıla لَمُبْتَلِينَ *(sınayanlar)* → ن, N sınıfı; i'râb ACC 2 · GEN 1; bab I ×1; zaman PERF 1 · yıldız ★ yok · kökler أيي *(âyet, işaret)* · كون *(olmak)* · بلو *(eskiyip yıpranma; sınama)* · bağ yok",
31:"eksen yok · aktör yok · edim haber · şahıs 1P ×2 · 3MP 1 · n=6 mora=35 harf=26, fâsıla ءَاخَرِينَ *(başkaları)* → ن, N sınıfı; i'râb GEN 1 · ACC 2; bab IV ×1; zaman PERF 1; dış düğüm 1 · iç düğüm 1 · yıldız ★ yok · kökler نشأ *(inşâ etme, yeni bir şey var etme)* · بعد *(sonra; uzaklık)* · قرن *(nesil, çağ)* · أخر *(geciktirme, sonraya bırakma)* · bağ: xref أنشأ *(inşa etti)* + بعد *(sonra)* + قرن *(nesil)* → **6:6 ve 23:42**; **23:42 ile sûre-içi bölüt ikizi** (elle, L1)",
32:"eksen: **Allah lafzı 7. sırada** (allah z=0,90) · aktör yok — elçi adsız · edim soru + emir, kip IMPV 1 · NEG 2 · INTG 1 · şahıs 2MP ×5 · 1P ×2 · 3MP ×2 · 3MS 1 · n=14 mora=78 harf=59, fâsıla تَتَّقُونَ *(sakınırsınız)* → ن, N sınıfı; i'râb ACC 2 · GEN 1 · NOM 1; bab I ×1 · bab IV ×1 · bab VIII ×1; zaman PERF 1 · IMPV 1 · IMPF 1; **kök ikilemesi رسل *(gönderme, elçi)* ×2 · أله *(ilâh; lafza-i celâl)* ×2**; simetri [3,2,8,1]; **dış düğüm 8 — 23:23 ile aynı değer** · yıldız ★ yok · kökler رسل · عبد *(kul, kulluk)* · أله · غير *(başka)* · وقي *(sakınma, koruma)* · bağ: **23:23 ile sûre-içi bölüt ikizi — sekiz kelime birebir** (elle, L1, aday 473)",
33:"eksen yok · **esmâ آخِر *(son)* 9. sırada — ÖLÇÜM ARTEFAKTI (aday 461)**: ٱلْءَاخِرَة *(âhiret)*, dünya/âhiret çift ucunun bir ucu; onarım ölçütü (d) · aktör yok — ٱلْمَلَأُ *(ileri gelenler)* yine kaydedilmiyor (aday 462) · edim haber, kip NEG 1 · RES 1 · şahıs 3MS ×5 · 3MP ×5 · 2MP ×5 · 1P ×2 · **n=25 mora=140 harf=114 — bloğun en uzun üçüncü ayeti** (n z=1,34), fâsıla تَشْرَبُونَ *(içersiniz)* → ن, N sınıfı; i'râb GEN 5 · NOM 3; bab I ×6 · bab II ×1 · bab IV ×1; zaman PERF ×4 · IMPF ×4; **kök ikilemesi أكل *(yeme)* ×2 · شرب *(içme)* ×2 — ikisi de birer kez üçüncü, birer kez ikinci şahısta**; biçim HASR · DIKKAT; simetri [3,3,14,1]; dış düğüm 3 · yıldız ★ yok · kökler قول *(söz söyleme)* · ملأ *(ileri gelenler (meleʼ); doldurma)* · قوم *(kalkma; kavim; kıyamet)* · كفر *(inkâr, nankörlük)* · كذب *(yalan; yalanlama)* · لقي *(karşılaşma, kavuşma; atma)* · أخر *(geciktirme, sonraya bırakma)* · ترف *(refah içinde şımartma)* · حيي *(diri olma, hayat)* · دنو *(yakınlık; dünya)* · بشر *(müjde; beşer)* · مثل *(benzer, mesel)* · أكل · شرب · bağ: **23:24 ile sûre-içi bölüt ikizi**; xref قال *(dedi)* + ملأ *(ileri gelenler)* + قوم *(kavim)* → 7:60 · 7:109 · 7:127 (elle, L1, aday 473)",
34:"eksen yok · aktör yok · edim şart, kip EMPH ×2 · COND 1 · şahıs 2MP ×4 · n=7 mora=50 harf=33, fâsıla لَّخَٰسِرُونَ *(hüsrana uğrayanlar)* → ن, N sınıfı; i'râb ACC 3 · NOM 1; bab IV ×1; zaman PERF 1 · yıldız ★ yok · kökler طوع *(güç yetirme, itaat)* · بشر *(müjde; beşer)* · مثل *(benzer, mesel)* · خسر *(hüsran, ziyan)* · bağ: **23:33 ile ortak بَشَرٌۭ مِّثْلُكُمْ *(sizin gibi bir beşer)*** — orada bildirim, burada şartın öznesi; i'râb merfûdan mansûba geçiyor (elle, L1)",
35:"eksen yok · aktör yok · edim soru, kip INTG 1 · şahıs 2MP ×7 · 3MS 1 · n=9 mora=57 harf=42, fâsıla مُّخْرَجُونَ *(çıkarılacak olanlar)* → ن, N sınıfı; i'râb ACC 4 · NOM 1; bab I ×3; zaman IMPF 1 · PERF ×2; edilgen 1 (pas z=1,57); dış düğüm 3 · yıldız ★ · kökler وعد *(vaat)* · موت *(ölüm)* · كون *(olmak)* · ترب *(toprak)* · عظم *(büyüklük, azamet; kemik)* · خرج *(çıkma, çıkarma)* · bağ: xref كان *(oldu)* + تراب *(toprak)* + عظام *(kemikler)* → **23:82 · 37:16 · 37:53 · 56:47**; **23:16 ile karşıtlık** — orada تُبْعَثُونَ *(diriltilirsiniz)* haber kipinde, burada aynı olay soru kipinde (elle, L1)",
36:"eksen yok · aktör yok · edim haber · şahıs 2MP ×2 · **n=4 mora=26 harf=20**, fâsıla تُوعَدُونَ *(size vaat edilir)* → ن, N sınıfı; **i'râb kaydı YOK — ayette îrablanan isim yok (aday 475)**; bab I ×1; zaman IMPF 1; **edilgen 1 — n=4'te tek fiil ve o fiil edilgen, pas z=5,38: yıldızın tek kaynağı (aday 472)**; **ayet hizb işareti ۞ taşıyor** · yıldız ★★★ · kök yalnız وعد *(vaat)* — **bloğun tek-köklü tek ayeti** · bağ: **23:35 ile ortak وعد** — orada fiil etken ve fâili elçi, burada edilgen ve fâil silinmiş (elle, L1)",
37:"eksen yok · aktör yok · edim haber, kip NEG ×2 · RES 1 · şahıs 1P ×4 · 3FS 1 · **iltifât 1 (2>13)** · n=10 mora=55 harf=42, fâsıla بِمَبْعُوثِينَ *(diriltilecek olanlar)* → ن, N sınıfı; i'râb NOM 2 · GEN 1; bab I ×2; zaman IMPF ×2; **kök ikilemesi حيي *(diri olma, hayat)* ×2 — biri isim biri fiil, arada موت *(ölüm)***; biçim HASR; simetri [3,1,8,1]; dış düğüm 1 · yıldız ★ yok · kökler حيي · دنو *(yakınlık; dünya)* · موت · بعث *(gönderme; diriltme)* · bağ: xref حياة *(hayat)* + دنيا *(dünya)* + مات *(öldü)* → **45:24**; **23:16 ile doğrudan karşıtlık** — aynı kök بعث, orada edilgen haber, burada olumsuzlanmış ism-i mef'ûl (elle, L1)",
38:"eksen: **Allah lafzı 7. sırada** (allah z=1,14) · **esmâ مُؤْمِن *(mü'min)* 12. sırada — ÖLÇÜM ARTEFAKTI (aday 461)**: بِمُؤْمِنِينَ *(inananlar)* olumsuzlanmış çoğul, göndergesi itiraz edenler; sûrenin iki مُؤْمِن tokeninin ikisi de yanlış · **aktör: adsız racül *(bir adam)* 4. sırada** · edim haber, kip NEG ×2 · RES 1 · şahıs 3MS ×3 · 1P 1 · n=12 mora=53 harf=43, fâsıla بِمُؤْمِنِينَ → ن, N sınıfı; i'râb NOM 1 · GEN 2 · ACC 1; bab VIII ×1; zaman PERF 1; biçim HASR; simetri [4,1,9,1] · yıldız ★ yok · kökler رجل *(adam; yaya)* · فري *(uydurma, iftira)* · أله *(ilâh; lafza-i celâl)* · كذب *(yalan; yalanlama)* · أمن *(güven; iman)* · bağ: **23:25 ile sûre-içi kalıp ikizi** — إِنْ هُوَ إِلَّا رَجُلٌ *(o bir adamdan başkası değil)* birebir; devamı ayrışıyor (elle, L1, aday 473)",
39:"eksen: lafız yok · **Rab 2. sırada, رَبِّ *(Rabbim)* — rab z=3,94 (aday 472)** · aktör yok · edim emir, kip IMPV 1 · şahıs 1S ×3 · 3MP ×2 · 3MS 1 · 2MS 1 · n=5 mora=26 harf=19, fâsıla كَذَّبُونِ *(beni yalanladılar)* → ن, N sınıfı; i'râb NOM 1; bab I ×2 · bab II ×1; zaman PERF ×2 · IMPV 1; **nakarat 2 · temsil 23:26**; dış düğüm 1 · yıldız ★★★ · kökler قول *(söz söyleme)* · ربب *(rab, terbiye etme)* · نصر *(yardım)* · كذب *(yalan; yalanlama)* · bağ: **tam-ayet ikizi 23:26 — sûre içi, 13 ayet arayla** (aday 473)",
40:"eksen yok · aktör yok · edim haber, kip EMPH ×2 · şahıs 3MS 1 · 3MP 1 · n=5 mora=32 harf=22, fâsıla نَٰدِمِينَ *(pişman olanlar)* → ن, N sınıfı; i'râb GEN 1 · ACC 1; bab I ×1 · bab IV ×1; zaman PERF 1 · IMPF 1; sayı sözcüğü قَلِيل *(az)* · yıldız ★ yok · kökler قول *(söz söyleme)* · قلل *(azlık)* · صبح *(sabah; olmak (asbaha))* · ندم *(pişmanlık)* · bağ: **23:25 ile süre karşıtlığı** — orada حَتَّىٰ حِينٍۢ *(bir süreye kadar)*, burada عَمَّا قَلِيلٍۢ *(az sonra)*; ikisi de belirsiz süre, iki uçta (elle, L1)",
}

MERCEK={
21:"Ayet 23:19'un yapısını hayvana taşıyor ve kapanışını birebir tekrarlıyor. Ölçülebilir bir iç sıra var: önce ibret bildiriliyor, sonra üç fayda sayılıyor ve üçü giderek genelleşiyor — içmek (belirli), fayda (belirsiz çoğul), yemek (fiil). عِبْرَة *(ibret)* korpusta dokuz geçişli seyrek kök; komşuluğunda eşik üstü tek kavram بصر *(görme)* — terim bakışla eşleşiyor, düşünmeyle değil.",
22:"Ayet iki taşıyıcıyı tek edatla birleştiriyor: عَلَيْهَا *(onların üzerinde)* ve عَلَى ٱلْفُلْكِ *(geminin üzerinde)* — biri canlı biri değil, ama dilbilgisinde ayrılmıyorlar. Ve fiil edilgen: taşıyan söylenmiyor, taşınan söyleniyor. Bu 23:16'nın çatısıyla aynı hamle — orada diriltilme, burada taşınma; ikisi de dört-beş kelimelik ayette tek fiil, ikisi de aynı z değeriyle ★★★.",
23:"Ayet 23:12'nin ve 23:17'nin açılışını üçüncü kez getiriyor: وَلَقَدْ *(andolsun)* + PERF. Ama nesne yine değişiyor — insan, konum, şimdi kişi. İkinci yarıda çatı devrediliyor: fâil olan birinci çoğul konuşmayı üçüncü şahsa bırakıyor (فَقَالَ *(dedi ki)*), o da hemen ikinci çoğula sesleniyor. Üç şahıs katmanı bir ayette üst üste biniyor. أله *(ilâh; lafza-i celâl)* kökü aynı ayette hem özel ad hem cins isim olarak geçiyor; aradaki fark yalnız harf-i tarif ve i'râb.",
24:"İtiraz üç ayrı dayanağa yaslanıyor ve üçü üç ayrı dilbilgisi aracıyla veriliyor: (1) HASR ile tür indirgemesi — مَا … إِلَّا *(ancak … dır)*; (2) şart cümlesiyle beklenti — لَوْ شَآءَ … لَأَنزَلَ *(dileseydi … indirirdi)*, karşı taraf ilâhî fiilin nasıl olması gerektiğini kendisi kuruyor; (3) olumsuz PERF ile gelenek — مَّا سَمِعْنَا *(işitmedik)*. Ölçülebilir simetri: elçi bir emir + bir soru kurmuştu, itiraz bir sınırlama + bir şart + bir yokluk bildiriyor. Ve فضل *(üstün kılma, lütuf)* bab V'te — üstünlük iddia edilen bir şey olarak, verilen bir şey olarak değil.",
25:"İkinci itiraz birinciyi daraltıyor: 23:24 türü indirgemişti (بَشَر *(beşer)*), bu ayet bireyi indirgiyor (رَجُل *(adam)*) ve üstüne bir nitelik ekliyor. İkisi de aynı HASR kalıbıyla kuruluyor — مَا … إِلَّا, sonra إِنْ … إِلَّا. Kapanış bir emir ama eylemsiz bir emir: تَرَبَّصُوا۟ *(gözetleyin)*, bab V. Süre de belirsiz bırakılıyor: حَتَّىٰ حِينٍ *(bir süreye kadar)*, nekre.",
26:"Beş kelimede üç şahıs ve üç zaman var: emri veren birinci tekil, emrin muhatabı ikinci tekil, gerekçedeki fâil üçüncü çoğul. Gerekçe bir harf-i cerle bağlanıyor: بِمَا كَذَّبُونِ *(yalanlamalarına karşı)* — yardım isteği bir olaya değil bir fiile dayandırılıyor. Ayetin bütün ağırlığı ilk kelimeden sonra: رَبِّ *(Rabbim)* nidâ harfi düşürülmüş, doğrudan çağrı.",
27:"Ayet bir talimat dizisi ve her adım bir kısıtla geliyor: gemi yapılacak ama gözetim altında (بِأَعْيُنِنَا *(gözlerimizin önünde)*); yükleme yapılacak ama bir işarete bağlı (فَارَ ٱلتَّنُّورُ *(tandır kaynadı)*); aile alınacak ama bir istisnayla; son emir olumsuz — وَلَا تُخَٰطِبْنِى *(bana hitap etme)*. Dört buyruğun üçü sınırlayıcı, dördüncüsü doğrudan yasak. Sayı bilgisi iki kez pekiştiriliyor: زَوْجَيْنِ ٱثْنَيْنِ *(ikişer eş)* — hem tesniye eki hem sayı sözcüğü. Kapanış edilgen ism-i mef'ûl: مُّغْرَقُونَ *(boğulacak olanlar)*, sonuç fâilsiz bırakılıyor.",
28:"Emir bir zaman koşuluna bağlı ve koşul bir denge fiiliyle veriliyor: ٱسْتَوَيْتَ *(yerleştin, denge buldun)*, سوي *(düzenleme, denk kılma)* kökü. Söylenecek söz kalıp hâlinde yazılmış — kurtuluşun karşılığı önceden belirlenmiş bir cümle. Zaman ölçülebilir biçimde ters: emir gelecekte, emredilen cümlenin fiili geçmiş (نَجَّىٰنَا *(bizi kurtardı)*). Kurtuluş henüz olmadan olmuş gibi söylenecek — 23:1'in أَفْلَحَ *(kurtuluşa erdi)* hamlesiyle aynı zaman kaydırması.",
29:"Sekiz kelimede aynı kök üç ayrı biçimde: أَنزِلْنِى *(beni indir)* fiil, مُنزَلًا *(iniş yeri)* ism-i mekân, ٱلْمُنزِلِينَ *(indirenler)* ism-i fâil çoğulu. İstek, istenen şey ve isteneni verecek olan aynı kökten adlandırılıyor — dua kendi sözlüğünü tek kökten kuruyor. İkinci cümle bir üstünlük tamlamasıyla kapanıyor: خَيْرُ ٱلْمُنزِلِينَ *(indirenlerin en hayırlısı)*, yapıca 23:14'ün أَحْسَنُ ٱلْخَٰلِقِينَ *(yaratanların en güzeli)* kalıbının aynısı.",
30:"Kıssa bir kapanış formülüyle bitiyor ve formül iki kez pekiştirilmiş. İki cümlenin özneleri farklı katmanda: birincisinde özne olay (فِى ذَٰلِكَ *(bunda)*), ikincisinde anlatıcı (كُنَّا *(biz idik)*). Kıssa önce işaret olarak, sonra sınama olarak adlandırılıyor — aynı olay iki ayrı işlevle iki cümleye bölünüyor.",
31:"نشأ *(inşâ etme, yeni bir şey var etme)* kökü bu sûrede üçüncü kez ve üçünde de dizinin bir sonraki basamağına geçişi işaretliyor: 23:14 insanın son aşaması, 23:19 bahçeler, burada bir nesil. Aynı fiil bedeni, bitkiyi ve topluluğu aynı işlemle adlandırıyor. Ayet 23:14'ün son iki kelimesini de tekrarlıyor — خَلْقًا ءَاخَرَ *(bambaşka bir yaratılış)* ile قَرْنًا ءَاخَرِينَ *(başka bir nesil)* aynı sıfatı taşıyor, biri tekil biri çoğul.",
32:"İkinci döngü birincinin açılışını iki değişiklikle tekrarlıyor ve ikisi de ölçülebilir: (1) elçi adlandırılmıyor — 23:23'te نُوحًا *(Nûh'u)* vardı, burada رَسُولًۭا مِّنْهُمْ *(kendilerinden bir elçi)*, özel ad cins isme dönüşüyor; (2) hitap biçimi değişiyor — orada nidâ vardı (يَٰقَوْمِ *(ey kavmim)*), burada yok, sözü bağlayan yalnız أَنِ *(ki)*. Sekiz kelimelik çağrı kalıbı harfi harfine korunuyor: değişen çerçeve, sabit kalan söz.",
33:"İtiraz aynı kalıpla açılıyor ama gerekçesi değişiyor: 23:24 melek beklentisine dayanıyordu, burada yeme-içmeye. Gerekçe iki fiil çiftiyle simetrik kuruluyor — يَأْكُلُ مِمَّا تَأْكُلُونَ *(yediğinizden yiyor)*, وَيَشْرَبُ مِمَّا تَشْرَبُونَ *(içtiğinizden içiyor)*: her iki kök de bir kez üçüncü, bir kez ikinci şahısta. Ortaklık dilbilgisiyle gösteriliyor: aynı fiil, iki farklı şahıs eki. Öznenin niteliği üç sıfat cümlesiyle uzatılmış ve üçüncüsü anlatıcıya ait: أَتْرَفْنَٰهُمْ *(onları refaha boğduk)* — itiraz edenlerin durumu kendi cümlelerinden önce anlatıcı tarafından kayda geçiriliyor.",
34:"Önceki ayetin sonucu burada bir şart cümlesine dönüştürülüyor ve terkip aynen taşınıyor: بَشَرًۭا مِّثْلَكُمْ *(sizin gibi bir beşer)*, yalnız i'râbı değişiyor (merfû iken mansûb). Ölçülebilir bir vurgu yığılması var: yedi kelimede iki pekiştirme lâmı ve bir إِذًۭا *(o zaman)*. İtiraz, kanıttan tehdide geçerken dilbilgisi araçlarını çoğaltıyor.",
35:"İtiraz anlatıcının kendi terimlerini geri çeviriyor: 23:12-16'nın maddeleri (تُرَاب *(toprak)*, عِظَام *(kemik)*) itirazın malzemesi oluyor, ama dizinin yönü tersine — orada topraktan insana, burada insandan toprağa. Çatı yine edilgen: مُّخْرَجُونَ *(çıkarılacak olanlar)*, tıpkı 23:16'nın تُبْعَثُونَ'u gibi fâilsiz. Karşı taraf iddiayı reddederken iddianın dilbilgisini aynen kullanıyor; değişen tek şey kip: haber yerine soru.",
36:"Dört kelimenin ikisi aynı: هَيْهَاتَ هَيْهَاتَ *(ne uzak, ne uzak)*, isim-fiil, çekimsiz. Ayette çekimli tek öğe edilgen fiil. Cümlede i'râb alan hiçbir isim yok — ölçüm katmanında i'râb kaydı boş çıkıyor, bloğun tek örneği. Bir önceki ayette وعد *(vaat)* kökünün fâili elçiydi; burada aynı kök edilgene çevrilerek fâil siliniyor — iddia kaynağından koparılıyor. Ve mesafe bir uzaklık sözcüğüyle veriliyor: reddedilen şey yanlış değil, uzak sayılıyor.",
37:"Ayet üçüncü HASR kalıbını kuruyor (23:24 · 23:25 · burada) ve bu kez indirgenen şey kişi değil varlığın kapsamı: إِنْ هِىَ إِلَّا حَيَاتُنَا ٱلدُّنْيَا *(o dünya hayatımızdan başkası değil)*. Ortadaki iki fiil ölçülebilir bir sıra bozukluğu taşıyor: نَمُوتُ وَنَحْيَا *(ölürüz ve yaşarız)* — ölüm önce, hayat sonra, ikisi de IMPF; sıra bir dizi değil bir döngü kuruyor. Kapanış dizinin devamını kesiyor: بِمَبْعُوثِينَ *(diriltilecek olanlar)* olumsuzlanmış — 23:15-16'nın ölüm-diriliş dizisi burada ölüm-hayat döngüsüyle değiştiriliyor.",
38:"İki döngünün ikinci itirazı aynı beş kelimeyle açılıyor ve tam beşinci kelimede ayrışıyor. Fark ölçülebilir bir yer değiştirme: birinci döngüde suç zihinsel ve edilgin (kendisinde delilik var — bir hâl), ikincisinde iradî ve geçişli (yalan uydurdu — bir fiil, bab VIII). İkinci itiraz lafzı kendi cümlesine sokuyor: reddedilen kişi ٱللَّهِ *(Allah)* üzerinden suçlanıyor. Kapanış olumsuz ism-i fâil — inanmama da bir eylem değil bir nitelik olarak yazılıyor.",
39:"İki döngü aynı cümleyle kapanıyor ve cümlede tek harf değişmiyor. Ölçülebilir olan cümlenin konumu: birinci döngüde 23:26 üçüncü itirazdan sonra geliyor, ikincide 23:39 dördüncü itirazdan sonra. Araya giren itiraz sayısı artıyor, karşılık aynı kalıyor. İki döngünün elçileri farklı (biri adlı, biri adsız) ama ağızlarından çıkan son söz özdeş — sûre farkı fâilde değil, tekrarda kuruyor.",
40:"Cevabın ekseni zaman: itirazın belirsiz uzun süresine karşı belirsiz kısa süre konuyor. Fiil bir hâl değişimi fiili — يُصْبِحُ, صبح *(sabah; olmak (asbaha))* kökünden. 22:63'te aynı kök yerin yeşermesini adlandırıyordu; burada pişmanlığa geçişi. Pekiştirme çift: hem lâm hem te'kid nûnu (لَّيُصْبِحُنَّ *(elbette olacaklar)*). Beş kelimede iki vurgu aracı, bir zaman zarfı ve bir sonuç niteliği.",
}

ATLAMA={
 "23:22":"★★★ ayet. 🜁 biyolog YAZILMADI — ayetin iki kökü فلك *(gemi, felek)* ve حمل *(yüklenme, taşıma)*; taşınan öznenin canlılığı bu ayette dilsel olarak işaretlenmiyor, çıpa komşu ayette (23:21). 🜂 uzay YAZILMADI — فلك korpusta hem gemi hem yörünge işlevinde; burada göndergesi حمل ve أنعام *(davarlar)* ile eşleştiği için gemi. Gönderge açıkken astronomik okumayı seçmek yasaklı 'bilimsel izdüşüm' hamlesidir.",
 "23:26":"★★★ ayet. 🜁 biyolog ve 🜂 uzay YAZILMADI — ayetin dört kökü (قول *(söz söyleme)* · ربب *(rab, terbiye etme)* · نصر *(yardım)* · كذب *(yalan; yalanlama)*) biyolojik ya da astronomik hiçbir öğeye bağlanmıyor.",
 "23:36":"★★★ ayet. 🜁 biyolog YAZILMADI — tek kök وعد *(vaat)*. 🜂 uzay YAZILMADI — هَيْهَاتَ *(ne uzak)* bir uzaklık ünlemi ama mekân ya da gök cismi göndergesi taşımıyor; mesafeyi fiziksel uzaklığa çevirmek çıpasız kalırdı.",
 "23:39":"★★★ ayet. 23:26 ile aynı gerekçe — dört kökün hiçbiri biyolojik ya da astronomik çıpa vermiyor.",
 "_blok_notu":"Blok 23:21-40'ta dört ★★★ ayetin DÖRDÜNDE de iki uzman merceği atlandı; dördünün de yıldız kaynağı tek bir z sapması (pas ya da rab) ve dördü de n=4-5. Buna karşılık bloğun biyolojik öğe taşıyan ayetleri (23:21 davar/karın · 23:35 toprak/kemik) ★0 ve ★1. Adaylar 468 ve 472."
}

p='/home/claude/repo/notlar/okuma_metni.json'
OM=json.load(open(p,encoding='utf-8'))
for n in range(21,41):
    OM['23']["23:%d"%n]={"ar":AR[(23,n)],"meal":MEAL[n],"olcum":OLCUM[n],
                         "mercek":MERCEK[n],"dikey":DIK["23:%d"%n]}
OM['23']['_mercek_atlama_notu'].update(ATLAMA)
OM['ilerleme']['not']=("Sûre 22 TAM (78/78). Sûre 23 (Mü'minûn) makro profil + 23:1-40 okundu. "
                       "Devam: 23:41. Dikey katman A parçası birincil, B etiketsiz.")
OM['ilerleme']['kismi']={"2":"1-20 ayet düzeyinde","23":"1-40 ayet düzeyinde"}
OM['ilerleme']['okunan_ayet']=1503
json.dump(OM,open(p,'w',encoding='utf-8'),ensure_ascii=False,indent=1)
print('okuma_metni: sûre 23 →',len([k for k in OM['23'] if not k.startswith('_')]),'ayet')

pm='/home/claude/repo/notlar/mercek_kayit.json'
MK=json.load(open(pm,encoding='utf-8'))
for n in range(21,41): MK['23']["23:%d"%n]=MERCEK[n]
MK['23_atlama'].update(ATLAMA)
json.dump(MK,open(pm,'w',encoding='utf-8'),ensure_ascii=False,indent=1)
print('mercek_kayit: sûre 23 →',len(MK['23']),'mercek')
