# -*- coding: utf-8 -*-
"""blok_22_1_20.py — Hac sûresi makro profili + 22:1-20 okuma kaydı."""
import json, re

DIK = json.load(open('blok_dikey_22_1_20.json', encoding='utf-8'))
veri = json.load(open('kuran_veri.json', encoding='utf-8'))
AR = {}
for s in veri['sureler']:
    for a in s['ayetler']:
        AR[(s['no'], a['no'])] = a['ar']
# 22:1'in başındaki besmele okuma metninden ayrılır (defter n=9 zaten hariç tutuyor)
AR[(22, 1)] = re.sub(r'^بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ\s*', '', AR[(22, 1)])

MAKRO = {
 "ad": "HAC",
 "ayet": 78, "kelime": 1274, "ort_kelime": 16.33,
 "tip": "Medenî", "nuzul": "103 (BELLEKTEN, doğrulanmadı)",
 "eksen": ("**Allah 75 geçiş (0,0589 = 1,69x) · Rab 8 geçiş (0,0063 = 0,50x) · A/R = 9,38.** "
   "ENBİYÂ İLE TAM TERS: orada Allah 0,15x ve Rab 0,95x, A/R = 0,43 idi. Komşu iki sûre arasında "
   "lafız yoğunluğu **11 kat** artıyor, Rab yoğunluğu **yarıya** düşüyor, oran **22 kat** tersine dönüyor. "
   "Allah 50 ayette (78'in %64'ü), Rab yalnız 8 ayette: 1, 19, 30, 40, 47, 54, 67, 77."),
 "kafiye": ("**10 kafiye sınıfı — korpusun 20+ ayetlik sûreleri arasında ikinci en heterojen** "
   "(birinci: sûre 11 ile 11 sınıf). Son harf dağılımı: ر 25 · د 15 · م 12 · ن 12 · ق 6 · ب 2 · ز 2 · "
   "ج 1 · ظ 1 · ء 1 · ط 1. Sınıf: R 25 · N 24 · د 15 · ق 6 · ب 2 · ز 2 ve dört tekil. "
   "16 ayette kafiye kırılması işaretli. ENBİYÂ İLE TAM TERS: orada 112/112 tek sınıf (mümkün olan minimum), "
   "burada 10 sınıf (mümkün olanın üst ucu). İki komşu sûre kafiye çeşitliliğinin iki uç değeri."),
 "esma": ("**38 token / 22 ayet / mühür 11.** Enbiyâ'da 17 token ve 1 mühür vardı. "
   "مَوْلَى *(mevlâ)* ×3 · شَهِيد *(şahit)* ×3 · قَدِير *(kadîr)* ×2 · آخِر *(son)* ×2 · مُبِين *(apaçık)* ×2 · "
   "حَمِيد *(hamîd)* ×2 · قَوِيّ *(kavî)* ×2 · عَزِيز *(azîz)* ×2 · عَلِيم *(alîm)* ×2 · سَمِيع *(semî')* ×2 · "
   "بَصِير *(basîr)* ×2 · نَصِير *(nasîr)* ×2 ve on bir tanesi birer kez. "
   "MÜHÜRLÜ AYETLER: 40, 52, **59-60-61-62-63-64-65 (yedi ardışık)**, 74, 75. "
   "UYARI (aday 444): آخِر, مُبِين ve مَوْلَى bağlam denetimi gerektiriyor — مُبِين sûre 21'de yanlış pozitifti."),
 "soz_edimi": "haber 49 · emir 18 · soru 8 · şart 7 · nida 5 · yasak 1. Enbiyâ'da emir 15, burada 18 ama ayet sayısı 78 — oransal olarak buyurgan.",
 "fig": "DIKKAT 7 · HASR 4 · NEHY 1. Enbiyâ'nın 16 DIKKAT ve 10 IDRAB'ına karşı burada IDRAB HİÇ YOK.",
 "dilbilgisi": "i'râb GEN 255 · ACC 198 · NOM 164 · zaman IMPF 143 · PERF 110 · IMPV 27 · edilgen 27 fiil / 18 ayet · iltifât yalnız 1 (22:50, 12>3)",
 "yildiz": {"0": 29, "1": 20, "3": 18, "2": 11},
 "yildiz3": [2, 5, 9, 17, 20, 21, 24, 27, 29, 36, 39, 40, 45, 72, 73, 74, 75, 78],
 "hapaks": ("12 ayet / 14 kök: ذهل *(şaşkınlıkla unutma)*(2) · همد *(sönmüş, kupkuru)*(5) · "
   "عطف *(yan, böğür)*(9) · مجس *(Mecûsî)*(17) · قمع(21) · **ضمر + عمق(27 — tek ayette iki)** · "
   "تفث(29) · وجب(36) · **صمع + هدم(40 — tek ayette iki)** · بأر(45) · سطو(72) · سلب(73). "
   "Aday 440 kaydındaki 33 çift-hapaks ayetin İKİSİ bu sûrede (22:27 ve 22:40)."),
 "aktor": ("12 ad. YENİ TÜR: sûre ilk kez **inanç-topluluğu adlarını** aktör olarak kaydediyor — "
   "صابِئ *(Sâbiî)* · نَصْرانِيّ *(Hıristiyan)* · مَجُوس *(Mecûsî)* · مُسْلِم *(müslüman)*; "
   "yanında kavim adları عاد · ثَمُود · مَدْيَن. Kişi adları yalnız üç: إِبْراهِيم *(İbrâhim)* ×3 · "
   "نُوح *(Nûh)* ×1 · مُوسَى *(Mûsâ)* ×1; ve شَيْطان *(şeytan)* ×3. Enbiyâ'nın 19 kişi-adına karşı burada üç."),
 "esit": "**Tam-ayet ikizi HİÇ YOK.** Enbiyâ'da iki tane vardı.",
 "en_uzun_kisa": "En uzun **22:5 (n=69)** — okumada bugüne dek görülen en uzun ayet · en kısa 22:21 ve 22:43 (n=4).",
 "not": "Sûre 21 (Enbiyâ) TAM okundu (112/112). Blok akışı 20 ayet. Bu sûre Medenî; okumada Tevbe'den sonraki ilk uzun Medenî sûre."
}

MEAL = {
1: "Ey insanlar, Rabbinizden sakının. O saatin sarsıntısı büyük bir şeydir.",
2: "Onu göreceğiniz gün, her emziren emzirdiğinden şaşırıp geçer, her gebe yükünü bırakır. İnsanları sarhoş görürsün, oysa sarhoş değillerdir; ama Allah'ın azabı şiddetlidir.",
3: "İnsanlardan kimi, bir bilgisi olmaksızın Allah hakkında tartışır ve her azgın şeytanın ardına takılır.",
4: "Onun hakkında şöyle yazılmıştır: Kim onu dost edinirse, o kişiyi saptırır ve alevli azaba götürür.",
5: "Ey insanlar, diriltilmekten şüphedeyseniz — biz sizi topraktan, sonra nutfeden, sonra alakadan, sonra yaratılışı belli belirsiz bir çiğnem etten yarattık; size açıklayalım diye. Dilediğimizi belirli bir süreye kadar rahimlerde tutarız; sonra sizi bebek olarak çıkarırız, sonra olgunluk çağınıza erişesiniz diye. Kiminiz vefat ettirilir, kiminiz de bilgiden sonra hiçbir şey bilmez hâle gelsin diye ömrün en düşkün çağına döndürülür. Yeri de kupkuru görürsün; ama üzerine suyu indirdiğimizde kıpırdanır, kabarır ve her göz alıcı çiftten bitirir.",
6: "Bu böyledir; çünkü Allah hakkın kendisidir, ölüleri O diriltir ve O her şeye kadirdir.",
7: "Ve o saat gelicidir, onda şüphe yoktur; Allah kabirlerdekini diriltecektir.",
8: "İnsanlardan kimi de, ne bir bilgi ne bir yol gösterici ne de aydınlatıcı bir kitap olmaksızın Allah hakkında tartışır;",
9: "yanını büküp Allah yolundan saptırmak için. Dünyada ona bir rezillik vardır; kıyamet günü de ona yakıcı azabı tattırırız.",
10: "Bu, senin ellerinin önden gönderdiği yüzündendir; Allah kullara asla zulmedici değildir.",
11: "İnsanlardan kimi de Allah'a bir kenardan kulluk eder. Ona bir hayır isabet ederse onunla yatışır; bir sınama isabet ederse yüzüstü döner. Dünyayı da âhireti de yitirmiştir. İşte apaçık ziyan budur.",
12: "Allah'ı bırakıp kendisine ne zarar ne fayda verebilen şeye yalvarır. İşte uzak sapkınlık budur.",
13: "Zararı faydasından daha yakın olana yalvarır. Ne kötü bir mevlâ, ne kötü bir yoldaş!",
14: "Allah, iman edip salih işler yapanları, altlarından ırmaklar akan bahçelere sokar. Allah dilediğini yapar.",
15: "Kim Allah'ın ona dünyada da âhirette de yardım etmeyeceğini sanıyorsa, göğe bir ip uzatsın, sonra kessin; baksın, düzeni öfkelendiği şeyi giderebiliyor mu?",
16: "İşte onu böyle apaçık âyetler olarak indirdik. Allah dilediğini doğru yola iletir.",
17: "İman edenler, Yahudi olanlar, Sâbiîler, Hıristiyanlar, Mecûsîler ve ortak koşanlar — Allah kıyamet günü aralarını ayıracaktır. Allah her şeye şahittir.",
18: "Görmedin mi: göklerdekiler, yerdekiler, güneş, ay, yıldızlar, dağlar, ağaçlar, hayvanlar ve insanlardan birçoğu Allah'a secde eder. Birçoğuna da azap hak olmuştur. Allah kimi aşağılarsa, artık ona ikram edecek yoktur. Allah dilediğini yapar.",
19: "Şu ikisi, Rableri hakkında çekişen iki hasımdır. İnkâr edenler için ateşten elbiseler biçilmiştir; başlarının üstünden kaynar su dökülür.",
20: "Onunla karınlarındakiler ve deriler eritilir.",
}

OLCUM = {
1: "eksen: lafız yok · Rab 4. sırada, رَبَّكُمْ *(Rabbiniz)* (**rab z=2,05 — sûrenin 8 Rab geçişinden ilki**) · esmâ yok · aktör yok · edim emir + nida, kip VOC 1 · IMPV 1 · şahıs **2MP ×3 — ayette tek şahıs** · n=9 mora=56 harf=61, fâsıla عَظِيمٌۭ *(büyük)* → م, **N sınıfı**; i'râb ACC 4 · NOM 3 · GEN 1; bab VIII ×1 (tek fiil); zaman IMPV 1; biçim DIKKAT · yıldız ★★ · kökler أيي *(hangi; âyet)* · أنس *(insan)* · وقي *(sakınma, takvâ)* · ربب *(rab, terbiye etme)* · زلزل *(sarsıntı, zelzele)* · سوع *(saat, vakit)* · شيأ *(dileme; şey)* · عظم *(büyüklük, azamet; kemik)* · bağ: xref يَٰٓأَيُّهَا ٱلنَّاسُ ٱتَّقُوا۟ رَبَّكُمْ *(ey insanlar, Rabbinizden sakının)* → 4:1 ve 31:33 · NOT: besmele okuma metnine dâhil edilmedi; defter de saymıyor (n=9)",
2: "eksen: **Allah lafzı ayet-içi 21. sırada — sondan ikinci** (allah z=0,38) · Rab yok · aktör yok · edim haber, kip NEG 1 · şahıs 2MP ×2 · **3FS ×5** · 2MS 1 · 3MP 1 · n=22 mora=111 harf=85, fâsıla شَدِيدٌۭ *(şiddetli)* → د, **د sınıfı**; i'râb ACC 6 · NOM 3 · GEN 5; bab I ×4 · bab IV ×1; **kök ikilemesi BEŞ ayrı kök: رأي *(görme)* ×2 · كلل *(hep, bütün)* ×2 · رضع *(emzirme)* ×2 · حمل *(yüklenme, taşıma)* ×2 · سكر *(sarhoşluk; döndürülme)* ×2 — bloğun en yoğun ikileme ayeti**; **hapaks ذهل *(şaşkınlıkla unutma)* (z=3,38)**; simetri [3,15,18,1] · yıldız ★★★ · kökler يوم *(gün)* · رأي *(görme)* · ذهل *(şaşkınlıkla unutma)* · كلل *(hep, bütün)* · رضع *(emzirme)* · وضع *(koyma, indirme)* · حمل *(yüklenme, taşıma)* · أنس *(insan)* · سكر *(sarhoşluk; döndürülme)* · عذب *(azap)* · أله *(ilâh; lafza-i celâl)* · شدد *(şiddet, katılık)* · bağ: xref yok",
3: "eksen: **Allah lafzı 6. sırada** (allah z=1,14) · aktör yok · edim haber · şahıs 3MS ×2 · n=12 mora=56 harf=45, fâsıla مَّرِيدٍۢ *(azgın)* → د, د sınıfı; i'râb GEN 6 · ACC 1; bab III ×1 · bab VIII ×1; zaman IMPF ×2 · kökler أنس *(insan)* · جدل *(tartışma, cedel)* · أله *(ilâh; lafza-i celâl)* · غير *(başka)* · علم *(bilme)* · تبع *(uyma, izleme)* · كلل *(hep, bütün)* · شطن *(şeytan)* · مرد *(azgınlık, merîd)* · bağ: **22:8 ile bölüt ikizi** — وَمِنَ ٱلنَّاسِ مَن يُجَٰدِلُ فِى ٱللَّهِ بِغَيْرِ عِلْمٍۢ *(insanlardan kimi bilgisizce Allah hakkında tartışır)* birebir aynı, beş ayet arayla; xref 22:8 ve 31:20",
4: "eksen yok — **bloğun 20 ayetinden lafızsız olan yalnız beşi: 1, 4, 13, 19, 20** · aktör yok · edim haber · şahıs **3MS ×10 — ayette tek şahıs** · n=11 mora=56 harf=47, fâsıla ٱلسَّعِيرِ *(alevli ateş)* → ر, **R sınıfı**; i'râb ACC 2 · GEN 2; bab I ×2 · bab IV ×1 · bab V ×1; edilgen 1 (كُتِبَ *(yazılmıştır)*, z=1,1) · kökler كتب *(yazma, kitap)* · ولي *(dost, veli; velâyet)* · ضلل *(sapma, saptırma)* · هدي *(yol gösterme)* · عذب *(azap)* · سعر *(alevlenme, saîr)* · bağ: xref yok",
5: "eksen yok · aktör yok · edim nida + şart, kip VOC 1 · COND 1 · NEG 1 · şahıs 2MP ×10 · 1P ×9 · 3MS ×3 · 2MS 1 · 3FS ×4 · **n=69 mora=340 harf=281 — OKUMADA BUGÜNE DEK GÖRÜLEN EN UZUN AYET (z=6,01)**, fâsıla بَهِيجٍۢ *(göz alıcı)* → ج, **ج sınıfı, sûrede tek** (kafiye kırılması işaretli); i'râb GEN 19 · ACC 8 · NOM 1; bab I ×8 · bab IV ×4 · bab II ×1 · bab V ×1 · bab VIII ×1; edilgen 2; **hapaks همد *(sönmüş, kupkuru olma)* (z=3,38)**; kök ikilemesi خلق *(yaratma)* ×3 · شيأ ×2 · علم ×2; sayı sözcüğü زَوْج *(eş, çift)*; simetri [7,13,41,2]; biçim DIKKAT; **dış düğüm 5** · yıldız ★★★ · kökler أنس *(insan)* · كون *(olmak)* · ريب *(şüphe, kuşku)* · بعث *(diriltme, gönderme)* · خلق *(yaratma)* · ترب *(toprak)* · نطف *(nutfe, damla)* · علق *(ilişme, alaka; kan pıhtısı)* · مضغ *(çiğnemlik et parçası)* · بين *(arası; açıklama)* · قرر *(yerleşme, karar; ikrar)* · رحم *(rahmet, merhamet; rahim)* · أجل *(süre, ecel)* · سمو *(ad; gök)* · خرج *(çıkma, çıkarma)* · طفل *(çocuk, bebek)* · بلغ *(ulaşma, tebliğ)* · شدد *(şiddet, katılık)* · وفي *(tam verme, vefa; vefat ettirme)* · ردد *(geri döndürme, dönüş)* · رذل *(rezil, aşağılık)* · عمر *(ömür; imar etme)* · علم *(bilme)* · أرض *(yer, yeryüzü)* · همد *(sönmüş, kupkuru olma)* · نزل *(indirme)* · موه *(su)* · هزز *(sarsılma, kıpırdanma)* · ربو *(artma, kabarma; ribâ)* · نبت *(bitki, bitirme)* · زوج *(eş, çift)* · بهج *(göz alıcı güzellik)* · bağ: xref **on üç ayrı 3-gram, dört ayrı ayete**: 16:70 (yedi 3-gram — ömrün düşkün çağı) · 40:67 (üç 3-gram — yaratılış dizisi) · 41:39 (iki 3-gram — yerin kabarması) · 50:7 (bir 3-gram — göz alıcı çift) · 10:104",
6: "eksen: **Allah lafzı 3. sırada** (allah z=1,01) · **esmâ قَدِير *(kadîr)* 13. sırada — MÜHÜR konumunda ama esma_k mühür saymıyor (son_konum=n=13)**; bağlam denetlendi: ilâhî ad, geçerli · aktör yok · edim haber · şahıs 3MS ×4 · n=13 mora=59 harf=49, fâsıla قَدِيرٌۭ → ر, R sınıfı; i'râb ACC 5 · NOM 2 · GEN 2; bab IV ×1; simetri [3,1,9,1] · kökler أله *(ilâh; lafza-i celâl)* · حقق *(hak, gerçek)* · حيي *(diri olma, hayat)* · موت *(ölüm)* · كلل *(hep, bütün)* · شيأ *(dileme; şey)* · قدر *(ölçü, takdir; güç)* · bağ: xref أحيا *(diriltme)* + ميّت *(ölü)* + كلّ *(hep)* → 42:9 ve 46:33",
7: "eksen: **Allah lafzı 8. sırada** (allah z=1,14) · aktör yok · edim haber, kip NEG 1 · şahıs 3FS 1 · 3MS 1 · n=12 mora=58 harf=45, fâsıla ٱلْقُبُورِ *(kabirler)* → ر, R sınıfı; i'râb ACC 5 · NOM 1 · GEN 1; bab I ×1; simetri [3,6,10,1] · kökler سوع *(saat, vakit)* · أتي *(gelme, getirme)* · ريب *(şüphe, kuşku)* · أله *(ilâh; lafza-i celâl)* · بعث *(diriltme, gönderme)* · قبر *(kabir)* · bağ: xref ساعة *(saat)* + آتي *(gelici)* + ريب *(şüphe)* → 40:59; 22:1 ile ortak سوع (elle, L1)",
8: "eksen: **Allah lafzı 6. sırada** (allah z=1,01) · aktör yok · edim haber, kip NEG 2 · şahıs 3MS 1 · n=13 mora=59 harf=47, fâsıla مُّنِيرٍۢ *(aydınlatıcı)* → ر, R sınıfı; **i'râb GEN 7 — tamamı mecrur**; bab III ×1; simetri [3,1,9,1]; **dış düğüm 3** · kökler أنس *(insan)* · جدل *(tartışma, cedel)* · أله *(ilâh; lafza-i celâl)* · غير *(başka)* · علم *(bilme)* · هدي *(yol gösterme)* · كتب *(yazma, kitap)* · نور *(nûr, ışık; ateş)* · bağ: **22:3 ile bölüt ikizi**; xref 22:3 · 31:20 · 30:29 · 31:6",
9: "eksen: **Allah lafzı 6. sırada**, سَبِيلِ ٱللَّهِ *(Allah yolu)* terkîbinde (allah z=0,81) · aktör yok · edim haber · şahıs 3MS ×4 · 1P 1 · n=15 mora=73 harf=66, fâsıla ٱلْحَرِيقِ *(yakıcı)* → ق, **ق sınıfı**; i'râb ACC 3 · GEN 6 · NOM 1; bab IV ×2; **hapaks عطف *(yan, böğür; yönelme)* (z=3,38)**; sayı sözcüğü ثانِي *(ikinci; büken)* · yıldız ★★★ · kökler ثني *(iki; yan çevirme)* · عطف *(yan, böğür; yönelme)* · ضلل *(sapma, saptırma)* · سبل *(yol)* · أله *(ilâh; lafza-i celâl)* · دنو *(yakınlık; dünya)* · خزي *(rezil olma/etme)* · ذوق *(tatma)* · يوم *(gün)* · قوم *(kalkma; kavim; kıyamet)* · عذب *(azap)* · حرق *(yakma)* · bağ: 22:8 ile devam ilişkisi — ayet önceki ayetin öznesine hâl cümlesiyle bağlanıyor (elle, L1)",
10: "eksen: **Allah lafzı 6. sırada** (allah z=1,69) · aktör yok · edim haber · şahıs 3FS 1 · 2MS 1 · 3MS 1 · n=9 mora=46 harf=35, fâsıla لِّلْعَبِيدِ *(kullar için)* → د, د sınıfı; i'râb NOM 1 · ACC 2 · GEN 2; bab I ×1 · bab II ×1; zaman PERF ×2 — IMPF yok; ism-i mübalağa ظَلَّٰم *(çok zulmedici)* · yıldız ★ · kökler قدم *(öne geçirme, takdim)* · يدي *(el)* · أله *(ilâh; lafza-i celâl)* · ليس *(değil (olumsuzluk))* · ظلم *(zulüm)* · عبد *(kul, kulluk)* · bağ: xref يد *(el)* + اللّه + ليس + ظلّام *(çok zulmedici)* + عبد *(kul)* → 3:182 ve 8:51 (üç 3-gram, ikisi de aynı iki ayete)",
11: "eksen: **Allah lafzı 5. sırada** (allah z=0,27) · **esmâ İKİ token — آخِر *(son)* 21. sırada (orta) ve مُبِين *(apaçık)* 25. sırada (fâsıla)**; İKİSİ DE ÖLÇÜM ARTEFAKTI (aday 444): آخِر burada ٱلدُّنْيَا وَٱلْءَاخِرَةَ *(dünya ve âhiret)* çiftinin bir ucu, مُبِين ise ٱلْخُسْرَانُ ٱلْمُبِينُ *(apaçık ziyan)* terkîbinde sıfat — ikisi de ilâhî ad değil · aktör yok · edim şart, kip COND 2 · şahıs 3MS ×10 · 3FS 1 · n=25 mora=121 harf=109 — bloğun en uzun ikinci ayeti, fâsıla ٱلْمُبِينُ → ن, N sınıfı (kafiye kırılması işaretli); i'râb GEN 3 · ACC 2 · NOM 5; bab I ×2 · bab IV ×3 · bab VII ×1; kök ikilemesi صوب *(isabet etme, doğru olma)* ×2 ve خسر *(hüsran, ziyan)* ×2; simetri [3,1,6,1] · yıldız ★ · kökler أنس *(insan)* · عبد *(kul, kulluk)* · أله *(ilâh; lafza-i celâl)* · حرف *(kenar, uç; harf)* · صوب *(isabet etme, doğru olma)* · خير *(hayır, daha iyi)* · طمأن *(yatışma, huzur bulma)* · فتن *(sınama, fitne)* · قلب *(çevirme, kalp)* · وجه *(yüz, yön)* · خسر *(hüsran, ziyan)* · دنو *(yakınlık; dünya)* · أخر *(son, âhiret)* · بين *(arası; açıklama)* · bağ: 22:3 ve 22:8 ile üçüncü kez وَمِنَ ٱلنَّاسِ مَن *(insanlardan kimi)* açılışı (elle, L1)",
12: "eksen: **Allah lafzı 4. sırada**, مِن دُونِ ٱللَّهِ *(Allah'ı bırakıp)* kalıbında (allah z=0,90) — kalıp Enbiyâ'da üç kez geçmişti · aktör yok · edim haber, kip NEG 2 · şahıs 3MS ×6 · n=14 mora=61 harf=52, fâsıla ٱلْبَعِيدُ *(uzak)* → د, د sınıfı; i'râb GEN 2 · NOM 2; bab I ×3; zaman IMPF ×3; simetri [3,5,8,1] · kökler دعو *(çağırma, dua)* · دون *(beriki, başkası)* · أله *(ilâh; lafza-i celâl)* · ضرر *(zarar)* · نفع *(fayda)* · ضلل *(sapma, saptırma)* · بعد *(sonra; uzaklık)* · bağ: xref دون *(başkası)* + اللّه + ضرّ *(zarar)* + نفع *(fayda)* → 10:18; **21:66 ile aynı ضرر/نفع çifti** (elle, L2)",
13: "eksen yok · **esmâ مَوْلَى *(mevlâ)* 8. sırada — ÖLÇÜM ARTEFAKTI (aday 444)**: لَبِئْسَ ٱلْمَوْلَىٰ *(ne kötü bir mevlâ)*, göndergesi yalvarılan PUT, üstelik yergi kalıbında · aktör yok · edim haber, kip EMPH ×3 · şahıs 3MS ×5 · n=10 mora=51 harf=46, fâsıla ٱلْعَشِيرُ *(yoldaş)* → ر, R sınıfı (kafiye kırılması işaretli); i'râb NOM 3 · GEN 2; bab I ×3; kök ikilemesi بأس *(şiddet; ne kötü)* ×2; sayı sözcüğü عَشِير *(yoldaş; onda bir)* · yıldız ★ · kökler دعو *(çağırma, dua)* · ضرر *(zarar)* · قرب *(yakınlık)* · نفع *(fayda)* · بأس *(şiddet, azap; ne kötü)* · ولي *(dost, veli; velâyet)* · عشر *(on; yoldaş, aşiret)* · bağ: 22:12 ile ortak ضرر/نفع çifti, ters sıra (elle, L1)",
14: "eksen: **Allah lafzı İKİ geçiş — 2. ve 14. sırada** (allah z=1,82; kök ikilemesi أله ×2) · aktör yok · edim haber · şahıs 3MS ×3 · 3MP ×4 · 3FS ×2 · n=17 mora=86 harf=73, fâsıla يُرِيدُ *(diler)* → د, د sınıfı; i'râb ACC 4 · GEN 3 · NOM 1; bab I ×3 · bab IV ×3; simetri [4,1,13,1]; **dış düğüm 3** · kökler أله *(ilâh; lafza-i celâl)* · دخل *(girme, sokma)* · أمن *(güven; iman)* · عمل *(iş, amel)* · صلح *(iyi olma, salâh)* · جنن *(cin; örtme; cennet)* · جري *(akma, koşma)* · تحت *(alt, altında)* · نهر *(ırmak; gündüz)* · فعل *(yapma, işleme)* · رود *(isteme, irade)* · bağ: xref أدخل *(sokma)* + آمن *(iman)* + عمل *(amel)* → 14:23 · 22:23 · 47:12 · اللّه + فعل *(yapma)* + أراد *(dileme)* → 2:253",
15: "eksen: **Allah lafzı 7. sırada** (allah z=0,38) · **esmâ آخِر *(son)* 10. sırada — ÖLÇÜM ARTEFAKTI (aday 444)**: ٱلدُّنْيَا وَٱلْءَاخِرَةِ çiftinin bir ucu · aktör yok · edim soru + emir, kip NEG 1 · **IMPV 3** · INTG 1 · EMPH 1 · şahıs **3MS ×10 — ayette tek şahıs** · n=22 mora=105 harf=87, fâsıla يَغِيظُ *(öfkelendirir)* → ظ, **ظ sınıfı, sûrede tek** (kafiye kırılması işaretli); i'râb NOM 2 · GEN 4; bab I ×7 · bab IV ×1; zaman IMPF ×7 · PERF 1 · yıldız ★ · kökler كون *(olmak)* · ظنن *(zan, sanma)* · نصر *(yardım)* · أله *(ilâh; lafza-i celâl)* · دنو *(yakınlık; dünya)* · أخر *(son, âhiret)* · مدد *(uzatma, med)* · سبب *(sebep, uzatılan ip)* · سمو *(ad; gök)* · قطع *(kesme, parçalama)* · نظر *(bakma; mühlet verme)* · ذهب *(gitme; altın)* · كيد *(tuzak, düzen)* · غيظ *(öfke, gayz)* · bağ: xref اللّه + دنيا + آخر → 33:57",
16: "eksen: **Allah lafzı 6. sırada** (allah z=1,69) · aktör yok · edim haber · şahıs 1P ×2 · 3MS ×3 · n=9 mora=49 harf=38, fâsıla يُرِيدُ *(diler)* → د, د sınıfı — 22:14'ün fâsılasıyla aynı kelime, iki ayet arayla; i'râb GEN 2 · ACC 2; bab I ×1 · bab IV ×2 · yıldız ★ · kökler نزل *(indirme)* · أيي *(âyet, işaret)* · بين *(arası; açıklama)* · أله *(ilâh; lafza-i celâl)* · هدي *(yol gösterme)* · رود *(isteme, irade)* · bağ: xref بيّنة *(apaçık)* + اللّه + هدى *(yol gösterme)* → 3:86",
17: "eksen: **Allah lafzı İKİ geçiş — 12. ve 18. sırada** (allah z=1,29; kök ikilemesi أله ×2) · **esmâ شَهِيد *(şahit)* 22. sırada = fâsıla, mühür konumunda** (esma_k mühür saymıyor: son_konum=n); bağlam denetlendi: ilâhî ad, geçerli · aktör: adlı **ÜÇ topluluk adı** — صابِئ *(Sâbiî)* 6., نَصْرانِيّ *(Hıristiyan)* 7., مَجُوس *(Mecûsî)* 8. sırada, üçü de tür **'kavim'**, üçü de rol mef'ûl · edim haber · şahıs 3MP ×7 · 3MS 1 · n=22 mora=128 harf=105 — **bloğun en yüksek mora'lı ayeti**, fâsıla شَهِيدٌ → د, د sınıfı; **i'râb ACC 10** · GEN 3 · NOM 1; bab I ×2 · bab IV ×2; **hapaks مجس *(Mecûsî)* (z=3,38)**; simetri [3,2,9,1]; dış düğüm 3 · yıldız ★★★ · kökler أمن *(güven; iman)* · هود *(Yahudi olma; Hûd)* · صبأ *(Sâbiî)* · نصر *(yardım; Hıristiyan)* · مجس *(Mecûsî)* · شرك *(ortak koşma)* · أله *(ilâh; lafza-i celâl)* · فصل *(ayrıntılandırma, ayırma)* · بين *(arası; açıklama)* · يوم *(gün)* · قوم *(kalkma; kavim; kıyamet)* · كلل *(hep, bütün)* · شيأ *(dileme; şey)* · شهد *(şahitlik)* · bağ: xref آمن *(iman)* + هاد *(Yahudi)* + صابئ *(Sâbiî)* + نصرانيّ *(Hıristiyan)* → 5:69 · فصل *(ayırma)* + بين + يوم → 32:25 · قيامة + اللّه + كلّ → 58:7",
18: "eksen: **Allah lafzı ÜÇ geçiş — 4., 28. ve 34. sırada** (allah z=1,09; kök ikilemesi أله ×3 — **bloğun ve sûrenin en yüksek lafız yığılması**) · aktör yok · edim soru, kip INTG 1 · NEG 2 · şahıs 2MS 1 · 3MS ×8 · **n=37 mora=178 harf=149 — bloğun en uzun ikinci ayeti (n z=2,61)**, fâsıla يَشَآءُ *(diler)* → ء, **ء sınıfı, sûrede tek**; **i'râb NOM 10** · ACC 4 · GEN 4; bab I ×5 · bab IV ×1; kök ikilemesi أله ×3 ve كثر *(çokluk)* ×2; sayı sözcüğü كَثِير *(çok)* ×2; simetri [6,1,31,2]; **dış düğüm 5**; ayet secde işareti ۩ taşıyor · yıldız ★★ · kökler رأي *(görme)* · أله *(ilâh; lafza-i celâl)* · سجد *(secde)* · سمو *(ad; gök)* · أرض *(yer, yeryüzü)* · شمس *(güneş)* · قمر *(ay)* · نجم *(yıldız)* · جبل *(dağ)* · شجر *(ağaç)* · دبب *(yeryüzünde yürüyen canlı)* · كثر *(çokluk)* · أنس *(insan)* · حقق *(hak, gerçek)* · عذب *(azap)* · هون *(aşağılama, hor görme)* · كرم *(üstün tutma, ikram)* · فعل *(yapma, işleme)* · شيأ *(dileme; şey)* · bağ: xref شمس *(güneş)* + قمر *(ay)* + نجم *(yıldız)* → 7:54 ve 16:12 · اللّه + سجد *(secde)* + سماء *(gök)* + أرض *(yer)* → 13:15 ve 16:49 · اللّه + فعل + شاء → 3:40",
19: "eksen: lafız yok · Rab 5. sırada, رَبِّهِمْ *(Rableri)* (rab z=0,93) — **sûrenin ikinci Rab geçişi, 18 ayet sonra** · aktör yok · edim haber · şahıs 3MP ×7 · 3FS 1 · 3MS 1 · n=17 mora=87 harf=75, fâsıla ٱلْحَمِيمُ *(kaynar su)* → م, N sınıfı; i'râb NOM 3 · GEN 4; bab I ×2 · bab II ×1 · bab VIII ×1; **edilgen 2 (قُطِّعَتْ *(biçilmiştir)* · يُصَبُّ *(dökülür)*, z=2,52)**; kök ikilemesi خصم *(husumet, çekişme)* ×2 — biri isim biri fiil; biçim DIKKAT; simetri [3,4,9,1]; ayet ۞ hizb işaretiyle açılıyor · yıldız ★★ · kökler خصم *(husumet, çekişme)* · ربب *(rab, terbiye etme)* · كفر *(inkâr, nankörlük)* · قطع *(kesme, parçalama)* · ثوب *(elbise; sevap)* · نور *(nûr, ışık; ateş)* · صبب *(dökme)* · فوق *(üst, üstünde)* · رأس *(baş)* · حمم *(kaynar su, hamîm)* · bağ: xref صبّ *(dökme)* + فوق *(üst)* + رأس *(baş)* → 44:48",
20: "eksen yok · aktör yok · edim haber · şahıs 3MS ×2 · 3MP 1 · n=6 mora=28 harf=24 — **bloğun en kısa ayeti**, fâsıla ٱلْجُلُودُ *(deriler)* → د, د sınıfı; i'râb GEN 1 · NOM 1; bab I ×1 (tek fiil); **edilgen 1 — n=6'da tek edilgen, z=5,38: SÛRENİN VE OKUMANIN EN YÜKSEK EDİLGEN YOĞUNLUĞU** · yıldız ★★★ · kökler صهر *(eritme)* · بطن *(karın, iç)* · جلد *(deri; kırbaçlama)* · bağ: 22:19 ile tek cümle — özne (kaynar su) önceki ayetten devralınıyor (elle, L1)",
}

MERCEK = {
1: "Sûre bir emirle açılıyor ve emrin nesnesi Rab: ٱتَّقُوا۟ رَبَّكُمْ *(Rabbinizden sakının)*. Ardından gerekçe bir ölçü cümlesiyle veriliyor: زَلْزَلَةَ ٱلسَّاعَةِ شَىْءٌ عَظِيمٌۭ *(o saatin sarsıntısı büyük bir şeydir)* — nitelenen şey bir olay değil bir 'şey' (شَىْء), yani en genel ad. Ölçek bildiren tek kelime عَظِيم *(büyük)*; ne kadar, ne zaman, nasıl yok. Ayet dokuz kelimede tek şahıs taşıyor: 2MP ×3.",
2: "Beş ayrı kök ikilemesi tek ayette — bloğun en yoğun ikileme ayeti. İkilemeler ayrı ayrı çalışıyor: رضع *(emzirme)* ism-i fâil + fiil (مُرْضِعَةٍ … أَرْضَعَتْ *(emziren… emzirdiği)*), حمل *(yüklenme, taşıma)* iki kez isim (ذَاتِ حَمْلٍ … حَمْلَهَا *(gebe… yükünü)*), سكر *(sarhoşluk)* olumlu + olumsuz (سُكَٰرَىٰ وَمَا هُم بِسُكَٰرَىٰ *(sarhoş… ama sarhoş değil)*). Üçüncüsü bir benzetmeyi kurup hemen geri alıyor: hâl adlandırılıyor ama gerçek sebebi olumsuzlanıyor. Kapanış tek yüklemle bağlanıyor: عَذَابَ ٱللَّهِ شَدِيدٌۭ *(Allah'ın azabı şiddetlidir)* — lafız sondan ikinci sırada.",
3: "Ayet bir sınıf tanımı kuruyor: وَمِنَ ٱلنَّاسِ مَن *(insanlardan kimi)* — parça edatı, yani hepsi değil. Fiil çift: يُجَٰدِلُ *(tartışır)* bab III (karşılıklılık) ve يَتَّبِعُ *(ardına takılır)* bab VIII. Tartışmanın eksiği bir yokluk cümlesiyle veriliyor: بِغَيْرِ عِلْمٍۢ *(bilgisi olmaksızın)*. Ayetin i'râbı ağırlıkla mecrur (GEN 6): cümle bir eylem zinciri değil, bir aidiyet tablosu.",
4: "On bir kelimede tek şahıs: 3MS ×10, ve şahsın göndergesi ayet içinde iki kez değişiyor — bir kez şeytana, bir kez ona uyana. Fiil edilgen ve failsiz açılıyor: كُتِبَ عَلَيْهِ *(onun hakkında yazılmıştır)*. Sonra iki fiil zıt anlamda ama aynı yönde kullanılıyor: يُضِلُّهُۥ وَيَهْدِيهِ *(saptırır ve götürür)* — هدي *(yol gösterme)* kökü burada olumlu değil, varış yeri عَذَابِ ٱلسَّعِيرِ *(alevli azap)* olduğu için tersine çalışıyor.",
5: "Okumada görülen en uzun ayet (n=69). Yapısı iki paralel diziden oluşuyor. Birinci dizi insan: تُرَاب *(toprak)* → نُطْفَة *(nutfe)* → عَلَقَة *(alaka)* → مُضْغَة *(çiğnem et)* → طِفْل *(bebek)* → أَشُدّ *(olgunluk)* → ya vefat ya أَرْذَلِ ٱلْعُمُرِ *(ömrün en düşkün çağı)*. İkinci dizi yer: هَامِدَة *(kupkuru)* → ٱهْتَزَّتْ *(kıpırdandı)* → رَبَتْ *(kabardı)* → أَنۢبَتَتْ *(bitirdi)*. İki dizi aynı fiille bağlanmıyor; bağlayan şey konum: biri şüphenin cevabı, öteki aynı cevabın ikinci örneği. Ölçülebilir bir asimetri var: insan dizisi bir düşüşle bitiyor (bilgiden bilgisizliğe, لِكَيْلَا يَعْلَمَ مِنۢ بَعْدِ عِلْمٍۢ شَيْـًۭٔا *(bilgiden sonra hiçbir şey bilmesin diye)*), yer dizisi bir yükselişle. خلق *(yaratma)* kökü üç kez: bir fiil, iki sıfat (مُّخَلَّقَةٍۢ وَغَيْرِ مُخَلَّقَةٍۢ *(belirmiş ve belirmemiş)*).",
6: "Dört cümle, hepsi أَنَّ ile bağlı ve hepsi aynı özneye dönüyor. Birincisi bir özdeşlik: ٱللَّهَ هُوَ ٱلْحَقُّ *(Allah hakkın kendisidir)* — araya giren هُوَ ayırıcı zamir, yani haber sınırlandırılıyor. İkincisi bir fiil (يُحْىِ ٱلْمَوْتَىٰ *(ölüleri diriltir)*), üçüncüsü bir sıfat (قَدِيرٌۭ *(kadîr)*). İsim → fiil → sıfat sırası: aynı özne üç ayrı dilbilgisi kategorisinden tanımlanıyor.",
7: "Önceki ayetin üç أَنَّ'sine dördüncüsü ekleniyor, yani cümle 22:6'nın devamı. İçerik iki parçalı: bir gelme (ءَاتِيَةٌۭ *(gelici)*, ism-i fâil — henüz olmamış ama nitelik olarak kesin) ve bir diriltme (يَبْعَثُ مَن فِى ٱلْقُبُورِ *(kabirlerdekini diriltir)*). Şüphe arada olumsuzlanıyor: لَّا رَيْبَ فِيهَا *(onda şüphe yok)* — aynı kök ريب *(şüphe, kuşku)* iki ayet önce 22:5'te şartın konusuydu.",
8: "22:3 ile ilk sekiz kelimesi birebir aynı; fark ayetin ikinci yarısında. 22:3'te eksik olan şey tek (بِغَيْرِ عِلْمٍۢ *(bilgisiz)*) ve ardından bir eylem geliyordu (şeytana uyma); burada eksik olan şey üçe çıkıyor ve eylem yok: عِلْم *(bilgi)* · هُدًۭى *(yol gösterici)* · كِتَٰب مُّنِير *(aydınlatıcı kitap)*. Üçü de aynı harf-i cerle bağlı; ayetin i'râbı tamamen mecrur (GEN 7). Yani ilk ayet failin ne yaptığını, ikincisi neye sahip olmadığını sayıyor.",
9: "Ayet önceki ayetin öznesine bir hâl cümlesiyle bağlanıyor: ثَانِىَ عِطْفِهِۦ *(yanını büküp)*. عطف *(yan, böğür)* korpusta hapaks; duruş bir beden terimiyle adlandırılıyor ama beden hakkında hiçbir şey söylenmiyor. Karşılık iki zamana bölünüyor ve iki ayrı kelimeyle: دُنْيَا'da خِزْىٌۭ *(rezillik)*, kıyamette عَذَابَ ٱلْحَرِيقِ *(yakıcı azap)*. İkisi de mecrur zincirin içinde; ayetin altı GEN'i bu iki terkibi taşıyor.",
10: "Ayette IMPF hiç yok; iki fiil de PERF. Sorumluluk bir beden terimiyle veriliyor: بِمَا قَدَّمَتْ يَدَاكَ *(ellerinin önden gönderdiği)* — يدي *(el)* ikil ve fiilin öznesi, yani kişi değil elleri fâil. Kapanış bir olumsuzlama ve ism-i mübalağa taşıyor: لَيْسَ بِظَلَّٰمٍۢ لِّلْعَبِيدِ *(kullara asla zulmedici değildir)* — ظَلَّام *(çok zulmedici)* kalıbı olumsuzlanıyor, yani reddedilen şey zulmün kendisi değil onun yoğun biçimi. Bu ayrım korpusta üç kez aynı kalıpta geçiyor (3:182 · 8:51 · burada).",
11: "Kulluk bir konum sözcüğüyle nitelendiriliyor: عَلَىٰ حَرْفٍۢ *(bir kenardan)* — حرف *(kenar, uç; harf)*, yani merkezde değil sınırda. Ardından iki şart aynı fiille kuruluyor: أَصَابَهُۥ خَيْرٌ *(ona hayır isabet ederse)* ve أَصَابَتْهُ فِتْنَةٌ *(sınama isabet ederse)* — صوب *(isabet etme)* iki kez, biri eril biri dişil özneyle. İki sonuç zıt: ٱطْمَأَنَّ *(yatıştı)* ve ٱنقَلَبَ عَلَىٰ وَجْهِهِۦ *(yüzüstü döndü)*. Sonuçların ortak faturası tek kökle: خسر *(hüsran, ziyan)* iki kez, biri fiil biri isim.",
12: "Yalvarılan nesne iki olumsuzlamayla tanımlanıyor: مَا لَا يَضُرُّهُۥ وَمَا لَا يَنفَعُهُۥ *(ne zarar veren ne fayda veren)*. Aynı çift Enbiyâ 21:66'da da vardı ve orada da aynı sırayla: نفع *(fayda)* önce, ضرر *(zarar)* sonra — burada sıra TERS. İki kökün korpustaki komşuluk profili karşılıklı olarak birbirini ilk sıraya koyuyor; yani çift kalıplaşmış.",
13: "Bir önceki ayetin iki olumsuzlaması burada bir karşılaştırmaya dönüşüyor: ضَرُّهُۥٓ أَقْرَبُ مِن نَّفْعِهِۦ *(zararı faydasından daha yakın)* — ism-i tafdîl ve mesafe kelimesi قرب *(yakınlık)*. Yani 22:12'de ikisi de yok idi, burada biri var ve öteki daha uzak. Kapanış iki yergiyi aynı kalıpta sıralıyor: لَبِئْسَ ٱلْمَوْلَىٰ وَلَبِئْسَ ٱلْعَشِيرُ *(ne kötü mevlâ, ne kötü yoldaş)* — ikisi de ilişki adı, biri üstten biri yandan.",
14: "Lafız iki kez, ayetin iki ucunda: açılışta ve 14. sırada. Aradaki cümle bir yer tarifi: جَنَّٰتٍۢ تَجْرِى مِن تَحْتِهَا ٱلْأَنْهَٰرُ *(altlarından ırmaklar akan bahçeler)* — korpusun en sık kalıplarından. Kapanış ise kapsamı açık bırakıyor: يَفْعَلُ مَا يُرِيدُ *(dilediğini yapar)*. Yani belirli bir vaat ile sınırsız bir yetki aynı ayette; ikisini bağlayan şey lafzın tekrarı.",
15: "Üç emir art arda ve üçü de aynı kişiye: فَلْيَمْدُدْ … ثُمَّ لْيَقْطَعْ … فَلْيَنظُرْ *(uzatsın… sonra kessin… baksın)* — lâmü'l-emr ile kurulmuş üçlü zincir, bloğun tek IMPV yığılması. Zincirin nesnesi somut: بِسَبَبٍ إِلَى ٱلسَّمَآءِ *(göğe bir ip)*, سبب *(sebep, uzatılan ip)* — kelime hem 'ip' hem 'sebep'. Kapanış bir soru: هَلْ يُذْهِبَنَّ كَيْدُهُۥ مَا يَغِيظُ *(düzeni öfkelendiği şeyi giderir mi)*. Yirmi iki kelimede tek şahıs (3MS ×10).",
16: "Tek cümlede iki hamle: indirme (أَنزَلْنَٰهُ ءَايَٰتٍۭ بَيِّنَٰتٍۢ *(onu apaçık âyetler olarak indirdik)*, 1P) ve yöneltme (يَهْدِى مَن يُرِيدُ *(dilediğini iletir)*, 3MS). Özne değişiyor ama gönderge aynı. Fâsıla 22:14'ünkiyle aynı kelime: يُرِيدُ *(diler)* — orada yapmanın, burada iletmenin kapsamı aynı fiile bağlanıyor.",
17: "Altı grup art arda sıralanıyor ve altısı da aynı i'râbda (ACC 10 — bloğun en yüksek mansûb yığılması). Beşi ad, biri fiil cümlesi (ٱلَّذِينَ أَشْرَكُوٓا۟ *(ortak koşanlar)*). Ölçüm katmanı üçünü aktör olarak kaydediyor — صابِئ · نَصْرانِيّ · مَجُوس — ama ٱلَّذِينَ هَادُوا۟ *(Yahudi olanlar)* fiil cümlesi olduğu için kaydetmiyor: yani araç, ad ile fiil-tanımı arasında ayırıyor. Hüküm tek fiilde toplanıyor: يَفْصِلُ بَيْنَهُمْ *(aralarını ayırır)*, فصل *(ayırma)* — ve zamanı kıyamet gününe bırakılıyor.",
18: "Sûrenin en yoğun lafız ayeti: أله *(ilâh; lafza-i celâl)* üç kez. Secde edenlerin listesi yedi kalem: gökler ve yerdekiler, sonra beş cisim/varlık sınıfı (güneş, ay, yıldızlar, dağlar, ağaçlar, hayvanlar), sonra insanlardan bir bölüm. Listeyi kıran şey son kalem: كَثِيرٌۭ مِّنَ ٱلنَّاسِ *(insanlardan birçoğu)* — parça edatı, yani tam değil. Hemen ardından aynı kelime ikinci kez ve karşıt tarafta: وَكَثِيرٌ حَقَّ عَلَيْهِ ٱلْعَذَابُ *(birçoğuna da azap hak oldu)*. Aynı sayı sözcüğü listenin iki yakasında. Ayetin i'râbı ağırlıkla merfû (NOM 10) — liste bir eylem değil bir durum sayımı.",
19: "İkil ile açılıyor: هَٰذَانِ خَصْمَانِ *(şu ikisi iki hasım)*, ama fiil çoğul: ٱخْتَصَمُوا۟ *(çekiştiler)*, bab VIII. Sayı ikiden çoğula kayıyor — taraflar iki, kişiler çok. Çekişmenin konusu Rab: فِى رَبِّهِمْ *(Rableri hakkında)*, sûrenin ikinci Rab geçişi ve on sekiz ayet sonrası. İkinci yarı iki edilgenle kuruluyor: قُطِّعَتْ *(biçilmiştir)* ve يُصَبُّ *(dökülür)* — fâil anılmıyor, ve giysi ile su karşı karşıya: biri sarmalıyor, öteki yukarıdan geliyor.",
20: "Altı kelime, tek fiil, ve o fiil edilgen: يُصْهَرُ *(eritilir)*, صهر *(eritme)* korpusta iki geçişli. Edilgen yoğunluğu n=6'da 1 ile z=5,38 — okumada ölçülen en yüksek değer. Nesne iki uçtan alınıyor: مَا فِى بُطُونِهِمْ *(karınlarındakiler)* ve ٱلْجُلُودُ *(deriler)* — iç ve dış, aynı yükleme bağlı ve aralarında hiçbir ara terim yok. Ayet 22:19'un cümlesini tamamlıyor: eriten şeyin adı (ٱلْحَمِيمُ *(kaynar su)*) önceki ayette, eriyen şeyin adı burada.",
}

BIYOLOG = {
2: "Çıpa üç öğe: مُرْضِعَةٍ / أَرْضَعَتْ *(emziren / emzirdiği)*, ذَاتِ حَمْلٍ / حَمْلَهَا *(gebe / yükü)*, ve سُكَٰرَىٰ *(sarhoşlar)*. Ölçülebilir olan şu: her üç öğe de İKİLENMİŞ (kök ikilemesi رضع ×2 · حمل ×2 · سكر ×2) ve her ikilemede biçim değişiyor — ism-i fâil ↔ fiil, isim ↔ isim+zamir, olumlu ↔ olumsuz. Korpusta رضع *(emzirme)* 11 geçişli ve komşuluk profili anne (×54,1) ve حمل (×28,7) ağırlıklı; حمل ise ▸sonra 'sütten-kesme' ×111,2 ile geliyor. Yani iki kök korpusta zaten bir zincir oluşturuyor: gebelik → doğum → emzirme → sütten kesme. Bu ayet o zinciri KESİYOR: emzirme emzirdiğinden kopuyor, gebelik yükünü zamansız bırakıyor. **Ölçüm sınırı:** ayet ne bir süreç ne bir mekanizma tarif ediyor; ölçülebilen tek şey, korpusun kendi kolokasyon zincirinin bu ayette ters yönde kullanılması.",
5: "Çıpa: تُرَاب *(toprak)* → نُطْفَة *(nutfe, damla)* → عَلَقَة *(ilişen şey)* → مُضْغَة *(çiğnemlik et)* → طِفْل *(bebek)* → أَشُدّ *(olgunluk)* → أَرْذَلِ ٱلْعُمُرِ *(ömrün en düşkün çağı)*. Ölçülebilir olanlar: (a) Dizinin dört ilk halkası da isim, hiçbiri fiil — yani aşamalar süreç olarak değil DURUM adları olarak veriliyor; aralarındaki geçiş yalnız ثُمَّ *(sonra)* edatıyla işaretleniyor, hiçbir dönüşüm fiili yok. (b) Dördüncü halka tek nitelenen: مُّخَلَّقَةٍۢ وَغَيْرِ مُخَلَّقَةٍۢ *(belirmiş ve belirmemiş)* — bir ikili ayrım yalnız bu aşamaya konuyor. (c) خلق *(yaratma)* kökü ayette üç kez ve üçü de bu bölgede toplanıyor. (d) Dizinin dört halkası korpusta 40:67 ile ortak (üç ayrı 3-gram); yani sıralama bu ayete özgü değil, tekrarlanan bir kalıp. (e) Kapanış dizisi bitkiye geçiyor ve orada fiiller var: ٱهْتَزَّتْ وَرَبَتْ وَأَنۢبَتَتْ *(kıpırdandı, kabardı, bitirdi)* — yani insan dizisi isimlerle, bitki dizisi fiillerle kuruluyor. **Ölçüm sınırı:** ayet aşamaların süresi, mekanizması ya da sırasının nedeni hakkında hiçbir şey vermiyor; verdiği tek şey sıra ve o sıranın adları.",
20: "Çıpa: بُطُون *(karınlar)* ve جُلُود *(deriler)* — bedenin en iç ve en dış katmanı, aynı yükleme bağlı ve aralarında hiçbir ara terim yok. Ölçülebilir olan: (a) بطن *(karın, iç)* korpusta 25 geçişli ve komşuluk profili ▸önce 'zuhur' (yani ظهر *(sırt; zuhur)*) ×41,5 — kökün olağan karşıtı SIRT/dış yüzey; bu ayette o karşıt yok, yerine جلد *(deri)* var. (b) جلد korpusta 13 geçişli ve komşuluk profili ağırlıkla hukukî (zina ×174,5, şahitlik ×13,1) — yani kökün tipik bağlamı ceza hukuku, anatomi değil. Bu ayette o bağlam da yok. (c) Fiil صهر *(eritme)* korpusta iki geçişli ve maddenin hâl değiştirmesini bildiriyor; öznesi anılmıyor (edilgen). **Ölçüm sınırı:** ayet ne bir doku ne bir işlev tarif ediyor; ölçülebilen tek şey, iki beden teriminin kendi olağan korpus bağlamlarının dışında ve tek bir yüklemde eşitlenmesi.",
}

om = json.load(open('okuma_metni.json', encoding='utf-8'))
mk = json.load(open('mercek_kayit.json', encoding='utf-8'))

om['22'] = {'_makro': MAKRO}
mk['22'] = []
mk['22_biyolog'] = []
for n in range(1, 21):
    key = "22:%d" % n
    om['22'][key] = {'ar': AR[(22, n)], 'meal': MEAL[n], 'olcum': OLCUM[n],
                     'mercek': MERCEK[n], 'dikey': DIK[key]}
    if BIYOLOG.get(n): om['22'][key]['biyolog'] = BIYOLOG[n]
    mk['22'].append([key, MERCEK[n]])
for n, t in BIYOLOG.items():
    mk['22_biyolog'].append(["22:%d" % n, t])

om['22']['_mercek_atlama_notu'] = (
 "★★★ ayetlerde atlanan uzman mercekleri (OKUMA_STANDARDI 2026-08-24, madde 3): "
 "22:2 uzay ATLANDI (gök öğesi yok; زلزلة *(sarsıntı, zelzele)* 22:1'de ve o ayet ★★). "
 "22:5 uzay ATLANDI (ayet yer ve bitkiden söz ediyor, gök öğesi yok). "
 "22:9 biyolog ve uzay ATLANDI — عطف *(yan, böğür; yönelme)* bir beden terimi ama tamamen deyimsel "
 "kullanılıyor, ayette hiçbir canlılık içeriği yok; zorlama çıpa yapılmadı. "
 "22:17 biyolog ve uzay ATLANDI (topluluk adları; canlılık ya da gök çıpası yok). "
 "22:20 uzay ATLANDI. "
 "NOT: 22:18 güneş/ay/yıldız/dağ/ağaç/hayvan listesi taşıyor ama yıldız=2 olduğu için "
 "protokol gereği uzman merceği YAZILMADI.")

om['ilerleme']['kismi']['22'] = "1-20 ayet düzeyinde"
om['ilerleme']['bekleyen']['22'] = "21-78"
om['ilerleme']['not'] = ("Sûre 20 TAM (135/135). Sûre 21 TAM (112/112). Sûre 22 (Hac) makro + 22:1-20. "
                         "Devam: 22:21. Dikey katman A parçası birincil, B etiketsiz.")
om['ilerleme']['okunan_ayet'] = 1405

json.dump(om, open('okuma_metni.json', 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
json.dump(mk, open('mercek_kayit.json', 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
print("yazıldı · sûre 22 makro + 1-20 · mercek:", len(mk['22']), "· biyolog:", len(mk['22_biyolog']))
