# -*- coding: utf-8 -*-
"""blok_21_61_80.py — Enbiyâ 61-80 bloğunun okuma kaydını dosyalara yazar."""
import json

DIK = json.load(open('blok_dikey_21_61_80.json', encoding='utf-8'))
veri = json.load(open('kuran_veri.json', encoding='utf-8'))
AR = {}
for s in veri['sureler']:
    for a in s['ayetler']:
        AR[(s['no'], a['no'])] = a['ar']

MEAL = {
61: "\"Öyleyse onu insanların gözü önüne getirin; belki şahitlik ederler\" dediler.",
62: "\"Bunu ilâhlarımıza sen mi yaptın, ey İbrâhim?\" dediler.",
63: "Dedi ki: Hayır, şu büyükleri yapmıştır. Konuşabiliyorlarsa onlara sorun.",
64: "Bunun üzerine kendilerine döndüler ve \"Asıl zalim olan sizsiniz\" dediler.",
65: "Sonra yine baş aşağı döndürüldüler: \"Sen de bilirsin ki bunlar konuşmaz.\"",
66: "Dedi ki: Öyleyse Allah'ı bırakıp da size hiçbir fayda vermeyen, zarar da veremeyen şeylere mi tapıyorsunuz?",
67: "Yazıklar olsun size ve Allah'ı bırakıp taptıklarınıza! Hâlâ akletmez misiniz?",
68: "\"Onu yakın, bir şey yapacaksanız ilâhlarınıza yardım edin\" dediler.",
69: "Dedik ki: Ey ateş, İbrâhim'e serinlik ve esenlik ol.",
70: "Ona bir tuzak kurmak istediler; biz de onları en çok ziyana uğrayanlar kıldık.",
71: "Onu da Lût'u da, âlemler için bereketli kıldığımız yere kurtarıp çıkardık.",
72: "Ona İshâk'ı, üstüne fazladan Ya'kûb'u bağışladık; hepsini de salih kimseler kıldık.",
73: "Onları, buyruğumuzla yol gösteren önderler kıldık; onlara hayırlar işlemeyi, namazı kılmayı, zekâtı vermeyi vahyettik. Onlar bize kulluk edenlerdi.",
74: "Lût'a da hüküm ve ilim verdik; onu, pislikler işleyen o ülkeden kurtardık. Onlar gerçekten kötü, yoldan çıkmış bir kavimdi.",
75: "Onu rahmetimizin içine aldık. O, salihlerdendi.",
76: "Nûh'u da — hani daha önce seslenmişti de ona icabet etmiştik; onu ve ailesini o büyük sıkıntıdan kurtarmıştık.",
77: "Âyetlerimizi yalanlayan kavme karşı ona yardım ettik. Onlar gerçekten kötü bir kavimdi; biz de hepsini birden boğduk.",
78: "Dâvûd'u ve Süleymân'ı da — hani ekin hakkında hüküm veriyorlardı; kavmin davarı geceleyin oraya yayılmıştı. Biz onların hükmüne şahittik.",
79: "Onu Süleymân'a kavrattık. Her birine hüküm ve ilim verdik. Dâvûd ile birlikte tesbih eden dağları ve kuşları da boyun eğdirdik. Bunları yapan bizdik.",
80: "Ona, sizi kendi şiddetinizden koruyacak zırh yapma sanatını öğrettik. Şimdi şükrediyor musunuz?",
}

OLCUM = {
61: "eksen yok · aktör yok · edim emir, kip IMPV 1 · şahıs 3MP ×5 · 2MP ×2 · 3MS 1 · n=8 mora=45 harf=38, fâsıla يَشْهَدُونَ *(şahitlik ederler)* → ن, N; i'râb GEN 2 · ACC 1; bab I ×3; zaman PERF 1 · IMPV 1 · IMPF 1 — üç fiil, üç ayrı zaman · kökler قول *(söz söyleme)* · أتي *(gelme, getirme)* · عين *(göz; pınar)* · أنس *(insan)* · شهد *(şahitlik)* · bağ: xref yok",
62: "eksen yok · aktör: adlı إِبْراهِيم *(İbrâhim)* 6. sırada, rol **fâil VE muhatap** (nidâ ile çağrılıyor, aynı anda fiilin öznesi) · edim soru + nida, kip INTG 1 · VOC 1 · şahıs 3MP ×2 · 2MS ×3 · 1P 1 · n=6 mora=44 harf=32 — bloğun en kısa ikinci ayeti, **fâsıla يَٰٓإِبْرَٰهِيمُ *(ey İbrâhim)* → م, N sınıfı**; i'râb GEN 1 · NOM 1; bab I ×2; biçim DIKKAT · kökler قول *(söz söyleme)* · فعل *(yapma, işleme)* · أله *(ilâh)* · bağ: xref yok",
63: "eksen: lafız yok · **esmâ كَبِير *(büyük)* 4. sırada — ÖLÇÜM ARTEFAKTI (aday 444)**: كَبِيرُهُمْ *(onların büyüğü)*, yani putların en büyüğü; aynı yanlış pozitif 21:58'de de vardı, aday 444'te ÖNCEDEN İŞARETLENMİŞTİ · aktör yok · edim emir + şart, kip IMPV 1 · COND 1 · şahıs 3MS ×3 · 3MP ×6 · 2MP ×2 · n=9 mora=46 harf=40, fâsıla يَنطِقُونَ *(konuşurlar)* → ن, N; i'râb NOM 1; bab I ×5; zaman PERF ×3 · IMPV 1 · IMPF 1; biçim IDRAB (بَلْ *(hayır, bilakis)*) + DIKKAT · kökler قول *(söz söyleme)* · فعل *(yapma, işleme)* · كبر *(büyüklük; büyüklenme)* · سأل *(sorma, isteme)* · كون *(olmak)* · نطق *(konuşma, söz söyleme)* · bağ: xref yok",
64: "eksen yok · aktör yok · edim haber · şahıs 3MP ×5 · 2MP ×2 · n=7 mora=49 harf=38, fâsıla ٱلظَّٰلِمُونَ *(zalimler)* → ن, N; i'râb GEN 1 · ACC 1 · NOM 1; bab I ×2; zaman PERF ×2 · **fâsıla ٱلظَّٰلِمُونَ merfû — sûrede daha önce üç kez mansûb ٱلظَّٰلِمِينَ olarak geçmişti (21:29, 21:46, 21:59)** · kökler رجع *(dönme, geri döndürme)* · نفس *(nefis, can)* · قول *(söz söyleme)* · ظلم *(zulüm)* · bağ: 21:59 ile aynı kök, ters i'râb (elle, L2)",
65: "eksen yok · aktör yok · edim haber, kip EMPH 1 · CERT 1 · NEG 1 · şahıs 3MP ×5 · 2MS ×2 · n=9 mora=49 harf=37, fâsıla يَنطِقُونَ *(konuşurlar)* → ن, N — **21:63 ile aynı fâsıla kelimesi, iki ayet arayla**; i'râb GEN 1; bab I ×3; edilgen 1 (نُكِسُوا۟ *(baş aşağı döndürüldüler)*, z=1.57); biçim DIKKAT; simetri [3,1,5,1] · yıldız ★ · kökler نكس *(baş aşağı çevirme, ters döndürme)* · رأس *(baş)* · علم *(bilme)* · نطق *(konuşma, söz söyleme)* · bağ: 21:63 ile fâsıla ikizi (elle, L1)",
66: "eksen: **Allah lafzı ayet-içi 5. sırada**, مِن دُونِ ٱللَّهِ *(Allah'ı bırakıp)* kalıbında (allah z=1.29) · Rab yok · esmâ yok · aktör yok (konuşan İbrâhim, adı geçmiyor) · edim soru, kip INTG 1 · NEG 2 · şahıs 3MS ×3 · 2MP ×4 · n=11 mora=51 harf=43, **fâsıla يَضُرُّكُمْ *(size zarar verir)* → م, N sınıfı**; i'râb GEN 2 · ACC 1; bab I ×4; zaman PERF 1 · IMPF ×3 · kökler قول *(söz söyleme)* · عبد *(kul, kulluk)* · دون *(beriki, başkası)* · أله *(ilâh; lafza-i celâl)* · نفع *(fayda)* · شيأ *(dileme; şey)* · ضرر *(zarar)* · bağ: xref قول *(söz söyleme)* + عبد *(kul, kulluk)* + دون *(beriki, başkası)* → 5:76",
67: "eksen: **Allah lafzı ayet-içi 7. sırada**, yine مِن دُونِ ٱللَّهِ kalıbında (**allah z=1.69 — iki ayette üst üste lafız**) · aktör yok · edim soru, kip INTG 1 · NEG 1 · şahıs **2MP ×5 — ayette TEK şahıs, tamamı muhatap** · n=9 mora=45 harf=36, fâsıla تَعْقِلُونَ *(akledersiniz)* → ن, N; i'râb GEN 2; bab I ×2; zaman IMPF ×2 — PERF yok · yıldız ★ · kökler أفف *(öf (usanç ünlemi))* · عبد *(kul, kulluk)* · دون *(beriki, başkası)* · أله *(ilâh; lafza-i celâl)* · عقل *(akletme, akıl)* · bağ: 21:66 ile aynı kalıp (elle, L1)",
68: "eksen yok · aktör yok · edim emir + şart, kip IMPV 2 · COND 1 · şahıs 3MP ×2 · **2MP ×7** · 3MS 1 · n=7 mora=45 harf=37, fâsıla فَٰعِلِينَ *(yapanlar)* → ن, N; i'râb ACC 2; bab I ×3 · bab II ×1; zaman PERF ×2 · IMPV ×2 · kökler قول *(söz söyleme)* · حرق *(yakma)* · نصر *(yardım)* · أله *(ilâh)* · كون *(olmak)* · فعل *(yapma, işleme)* · bağ: xref yok",
69: "eksen: lafız yok · **esmâ سَلام *(esenlik)* 5. sırada — ÖLÇÜM ARTEFAKTI (aday 444)**: burada سَلَٰمًا *(esenlik)* ateşe verilen bir EMİR yükleminin parçası (بَرْدًۭا وَسَلَٰمًا *(serinlik ve esenlik)*), ilâhî ad değil · aktör: adlı إِبْراهِيم *(İbrâhim)* 7. sırada, rol mecrur · edim emir + nida, kip VOC 1 · IMPV 1 · şahıs 1P ×2 · **2FS ×2 — ateşe DİŞİL tekil hitap** · n=7 mora=46 harf=31, **fâsıla إِبْرَٰهِيمَ *(İbrâhim)* → م, N sınıfı**; i'râb NOM 1 · ACC 2 · GEN 1; bab I ×2 · kökler قول *(söz söyleme)* · نور *(nûr, ışık; ateş)* · كون *(olmak)* · برد *(soğukluk, serinlik)* · سلم *(esenlik; teslim olma)* · bağ: xref yok",
70: "eksen yok · aktör yok · edim haber · şahıs 3MP ×3 · 3MS 1 · 1P ×2 · n=5 mora=35 harf=31 — **bloğun en kısa ayeti**, fâsıla ٱلْأَخْسَرِينَ *(en çok ziyana uğrayanlar)* → ن, N; i'râb ACC 2; bab I ×1 · bab IV ×1; zaman PERF ×2; ism-i tafdîl ٱلْأَخْسَرِينَ · kökler رود *(isteme, irade)* · كيد *(tuzak, düzen)* · جعل *(kılma, var etme)* · خسر *(hüsran, ziyan)* · bağ: xref رود *(isteme, irade)* + كيد *(tuzak, düzen)* + جعل *(kılma, var etme)* → 37:98; 21:57 ile aynı kök كيد, ters fâil (elle, L1)",
71: "eksen yok · aktör: adlı لُوط *(Lût)* 2. sırada, rol mef'ûl · edim haber · şahıs 1P ×4 · 3MS 1 · 3FS 1 · n=8 mora=56 harf=39, fâsıla لِلْعَٰلَمِينَ *(âlemler için)* → ن, N; i'râb ACC 1 · GEN 2; bab II ×1 · bab III ×1 — **bloğun tek bab III'ü**; zaman PERF ×2 · kökler نجو *(kurtarma, necat)* · أرض *(yer, yeryüzü)* · برك *(bereket, mübarek kılma)* · علم *(bilme; âlem)* · bağ: 21:50 ile ortak برك (elle, L2)",
72: "eksen yok · aktör: adlı İKİ kişi — إِسْحاق *(İshâk)* 3. sırada ve يَعْقُوب *(Ya'kûb)* 4. sırada, ikisi de rol mecrur · edim haber · şahıs 1P ×4 · 3MS 1 · n=8 mora=53 harf=41, fâsıla صَٰلِحِينَ *(salih kimseler)* → ن, N; i'râb GEN 2 · ACC 3; bab I ×2; biçim KELLA (كُلًّۭا *(hepsini)*) · kökler وهب *(bağışlama, hibe)* · نفل *(fazladan verilen, nafile)* · كلل *(hep, bütün)* · جعل *(kılma, var etme)* · صلح *(iyi olma, salâh)* · bağ: xref yok",
73: "eksen yok · aktör yok · edim haber · şahıs **1P ×6 · 3MP ×6 — tam denge** · n=15 mora=104 harf=83 — **bloğun en uzun ayeti (mora)**, fâsıla عَٰبِدِينَ *(kulluk edenler)* → ن, N; i'râb ACC 5 · GEN 4; bab I ×3 · bab IV ×1; zaman PERF ×3 · IMPF 1 · kökler جعل *(kılma, var etme)* · أمم *(önder, imam; ümmet)* · هدي *(yol gösterme)* · أمر *(emir; iş)* · وحي *(vahiy, gizli bildirim)* · فعل *(yapma, işleme)* · خير *(hayır, daha iyi)* · قوم *(kalkma; kavim; kıyamet)* · صلو *(namaz, salât)* · أتي *(gelme, getirme; verme)* · زكو *(arınma, zekât)* · كون *(olmak)* · عبد *(kul, kulluk)* · bağ: xref جعل *(kılma)* + أمم *(önder)* + هدي *(yol gösterme)* → 32:24 · صلو *(namaz)* + أتي *(verme)* + زكو *(zekât)* → 24:37",
74: "eksen yok · aktör: adlı لُوط *(Lût)* 1. sırada — **ayetin İLK kelimesi**, rol mef'ûl · edim haber · şahıs 1P ×4 · 3MS ×2 · 3FS ×2 · 3MP ×3 · n=16 mora=98 harf=77, fâsıla فَٰسِقِينَ *(yoldan çıkmışlar)* → ن, N; i'râb ACC 7 · GEN 2; bab I ×3 · bab II ×1 · bab IV ×1; kök ikilemesi كون *(olmak)* ×2; simetri [3,8,12,1] · kökler أتي *(gelme, getirme; verme)* · حكم *(hüküm verme, hikmet)* · علم *(bilme)* · نجو *(kurtarma, necat)* · قري *(köy, kasaba)* · كون *(olmak)* · عمل *(iş, amel)* · خبث *(pislik, habislik)* · قوم *(kalkma; kavim; kıyamet)* · سوأ *(kötülük)* · فسق *(yoldan çıkma, fısk)* · bağ: xref ءَاتَيْنَا حُكْمًۭا وَعِلْمًۭا *(hüküm ve ilim verdik)* → 12:22 · 21:79 · 28:14",
75: "eksen yok · aktör yok · edim haber · şahıs 1P ×3 · 3MS ×2 · n=6 mora=36 harf=29, fâsıla ٱلصَّٰلِحِينَ *(salihler)* → ن, N — 21:72'nin fâsılası ile aynı kök, bu kez marife; i'râb GEN 2 · ACC 1; bab IV ×1 (tek fiil) · kökler دخل *(girme, sokma)* · رحم *(rahmet, merhamet)* · صلح *(iyi olma, salâh)* · bağ: 21:72 ile fâsıla kökü ortak (elle, L2)",
76: "eksen yok · aktör: adlı نُوح *(Nûh)* 1. sırada — ayetin İLK kelimesi, rol mef'ûl · edim haber · şahıs 3MS ×4 · 1P ×4 · n=12 mora=63 harf=52, **fâsıla ٱلْعَظِيمِ *(büyük)* → م, N sınıfı**; i'râb ACC 2 · GEN 3; bab II ×1 · bab III ×1 · bab X ×1 — **üç fiil, üçü de farklı bab, hiçbiri bab I**; zaman PERF ×3 · kökler ندي *(seslenme, nidâ)* · قبل *(ön, önce; kabul)* · جوب *(cevap verme, icabet)* · نجو *(kurtarma, necat)* · أهل *(ehil, aile)* · كرب *(sıkıntı, keder (kerb))* · عظم *(büyüklük, azamet; kemik)* · bağ: xref نجّى *(kurtarma)* + أهل *(aile)* + كرب *(sıkıntı)* → 37:76",
77: "eksen yok · aktör yok · edim haber · şahıs 1P ×5 · 3MS 1 · 3MP ×6 · n=12 mora=74 harf=63, fâsıla أَجْمَعِينَ *(hepsi birden)* → ن, N; i'râb GEN 3 · ACC 3; bab I ×2 · bab II ×1 · bab IV ×1; kök ikilemesi قوم *(kalkma; kavim; kıyamet)* ×2 — ikisi de 'kavim' anlamında; **dış düğüm 4 — bloğun en bağlantılı ayeti** · kökler نصر *(yardım)* · قوم *(kalkma; kavim; kıyamet)* · كذب *(yalanlama, tekzîb)* · أيي *(âyet, işaret)* · كون *(olmak)* · سوأ *(kötülük)* · غرق *(boğulma)* · جمع *(toplama)* · bağ: xref كذب *(yalanlama)* + أيي *(âyet)* + كون *(olmak)* → 7:64 · 7:72 · 7:136 · 7:146",
78: "eksen yok · aktör: adlı İKİ kişi — داوُد *(Dâvûd)* 1. sırada ve سُلَيْمان *(Süleymân)* 2. sırada, ikisi de rol mecrur · edim haber · şahıs **3MD 1 · 3D 1 · 3FS 1 · 3MS 1 · 1P ×2 · 3MP 1 — altı ayrı şahıs kategorisi, bloğun en dağınık şahıs profili** · n=14 mora=68 harf=59, fâsıla شَٰهِدِينَ *(şahitler)* → ن, N; i'râb GEN 5 · NOM 1 · ACC 1; bab I ×3; kök ikilemesi حكم *(hüküm verme, hikmet)* ×2 — biri **ikil fiil** يَحْكُمَانِ *(ikisi hüküm veriyordu)*, öteki **çoğul iyelik** حُكْمِهِمْ *(onların hükmü)*; simetri [3,1,5,1] · kökler حكم *(hüküm verme, hikmet)* · حرث *(ekin, tarla)* · نفش *(geceleyin ekine yayılma)* · غنم *(davar, koyun sürüsü)* · قوم *(kalkma; kavim; kıyamet)* · كون *(olmak)* · شهد *(şahitlik)* · bağ: xref yok",
79: "eksen yok · aktör: adlı İKİ kişi — سُلَيْمان *(Süleymân)* 2. sırada, داوُد *(Dâvûd)* 9. sırada, ikisi de mecrur; **21:78'de sıra Dâvûd→Süleymân, burada ters** · edim haber · şahıs **1P ×8** · 3FS 1 · 3FP ×2 · n=14 mora=96 harf=75, fâsıla فَٰعِلِينَ *(yapanlar)* → ن, N — 21:68'in fâsılası ile aynı kelime; i'râb GEN 2 · ACC 7; bab I ×1 · bab II ×3 · bab IV ×1; **hapaks فهم *(kavratma, anlatma (fehm))* — korpusta tek geçiş (z=3.38)**; biçim KELLA (وَكُلًّۭا *(her birine)*) · yıldız ★★★ · kökler فهم *(kavratma, anlatma (fehm))* · كلل *(hep, bütün)* · أتي *(gelme, getirme; verme)* · حكم *(hüküm verme, hikmet)* · علم *(bilme)* · سخر *(alay etme; boyun eğdirme)* · جبل *(dağ)* · سبح *(tesbih, tenzih; yüzme)* · طير *(kuş; uçma)* · كون *(olmak)* · فعل *(yapma, işleme)* · bağ: xref ءَاتَيْنَا حُكْمًۭا وَعِلْمًۭا → 12:22 · 21:74 · 28:14 · سخّر *(boyun eğdirme)* + جبل *(dağ)* + سبّح *(tesbih)* → 38:18",
80: "eksen: lafız yok · **esmâ شاكِر *(şükreden)* 10. sırada — ÖLÇÜM ARTEFAKTI (aday 444)**: أَنتُمْ شَٰكِرُونَ *(siz şükredenler misiniz)* — gönderge İNSANLAR, ilâhî ad değil; sûrede saptanan en açık yanlış pozitif · aktör yok · edim soru, kip INTG 1 · şahıs 1P ×2 · 3MS 1 · 2MP ×4 · 2MS 1 · n=10 mora=53 harf=46, fâsıla شَٰكِرُونَ *(şükredenler)* → ن, N; i'râb ACC 1 · GEN 2 · NOM 1; bab II ×1 · bab IV ×1 — bab I yok · kökler علم *(bilme)* · صنع *(yapma, işleme)* · لبس *(giyinme; karıştırma)* · حصن *(koruma, sağlamlaştırma; iffet)* · بأس *(şiddet, azap; savaş gücü)* · شكر *(şükür)* · bağ: xref yok",
}

MERCEK = {
61: "Üç fiil, üç ayrı zaman: قَالُوا۟ *(dediler)* PERF, فَأْتُوا۟ *(getirin)* IMPV, يَشْهَدُونَ *(şahitlik ederler)* IMPF. Cümle geçmişten emre, emirden umulan sonuca doğru kayıyor. Tanıklığın koşulu mekân olarak veriliyor: عَلَىٰٓ أَعْيُنِ ٱلنَّاسِ *(insanların gözü önünde)* — göz burada organ değil konum adı, عين *(göz; pınar)* kökü mecrur ve izafet başı.",
62: "Soru hemzesi öznenin üzerine biniyor: ءَأَنتَ فَعَلْتَ *(sen mi yaptın)* — fiil zaten 2MS şahıs taşıdığı hâlde ayrı zamir eklenmiş, yani soru eylemi değil FAİLİ hedefliyor. Ad ayetin sonunda ve nidâ hâlinde: يَٰٓإِبْرَٰهِيمُ *(ey İbrâhim)*. Böylece aynı kişi cümlenin hem öznesi hem çağrılanı; defter rol alanı da bunu ikili kaydediyor (fâil + muhatap).",
63: "Cevap fiili aynen tekrarlıyor (فَعَلَ *(yaptı)*) ama faili değiştiriyor: كَبِيرُهُمْ هَٰذَا *(şu, onların büyüğü)*. Ardından gelen emir cevabı bir sınamaya çeviriyor: فَسْـَٔلُوهُمْ *(onlara sorun)*, ve şart cümlesi sınamanın ölçütünü koyuyor: إِن كَانُوا۟ يَنطِقُونَ *(konuşabiliyorlarsa)*. Yani iddia bir deney önerisiyle birlikte veriliyor; ölçüt konuşma, kök نطق *(konuşma, söz söyleme)* korpusta yalnız 12 geçişli.",
64: "İki hareket: فَرَجَعُوٓا۟ إِلَىٰٓ أَنفُسِهِمْ *(kendilerine döndüler)* — dönüş yönü dışarıya değil içeriye. Sonra hüküm dışarıdan içeriye çevriliyor: إِنَّكُمْ أَنتُمُ ٱلظَّٰلِمُونَ *(asıl zalim sizsiniz)*. Fâsıla dikkat çekici: sûrede ٱلظَّٰلِمِينَ üç kez mansûb geçmişti (21:29, 46, 59); burada ilk kez merfû ٱلظَّٰلِمُونَ — çünkü artık bir fiilin nesnesi değil, cümlenin haberi.",
65: "Aynı fâsıla iki ayet arayla dönüyor (يَنطِقُونَ *(konuşurlar)*), ama işlevi tersine çevrilmiş: 21:63'te şartın ölçütüydü, burada olumsuzlanan bir bilgi. Aradaki dönüş edilgen bir fiille anlatılıyor: نُكِسُوا۟ عَلَىٰ رُءُوسِهِمْ *(başları üzerine ters çevrildiler)* — fâil anılmıyor. نكس *(baş aşağı çevirme, ters döndürme)* korpusta 3 geçişli.",
66: "Soru kulluğun nesnesini iki olumsuzlama ile tanımlıyor: لَا يَنفَعُكُمْ شَيْـًۭٔا وَلَا يَضُرُّكُمْ *(size hiçbir fayda vermez, zarar da veremez)*. نفع *(fayda)* ve ضرر *(zarar)* çifti korpusta birbirinin en güçlü komşusu — dikey katman ikisini karşılıklı olarak birinci sıraya koyuyor. Nesne böylece iki yönde de etkisiz tanımlanıyor: ne çekim ne itim.",
67: "Ayette PERF yok, yalnız iki IMPF var; ve şahıs alanı tek: 2MP ×5. Yani cümlenin tamamı muhataba dönük ve şimdiki zamanda. Açılış bir ünlem: أُفٍّۢ *(öf)*, أفف kökü korpusta 3 geçişli. Kapanış ise bir yeti sorusu: أَفَلَا تَعْقِلُونَ *(akletmez misiniz)*. Bir önceki ayetin lafız kalıbı (مِن دُونِ ٱللَّهِ) aynen tekrarlanıyor — iki ayet üst üste aynı terkip.",
68: "Emir iki fiile bölünüyor ve ikisi zıt yönde: حَرِّقُوهُ *(onu yakın)* yok etme, وَٱنصُرُوٓا۟ ءَالِهَتَكُمْ *(ilâhlarınıza yardım edin)* koruma. İkisi de 2MP. Şart cümlesi ise emri kendi failine geri döndürüyor: إِن كُنتُمْ فَٰعِلِينَ *(bir şey yapacaksanız)* — yani eylem yeteneği sorgulanan taraf artık putlar değil onlar. Şahıs dağılımı bunu gösteriyor: 2MP ×7, bloğun en yüksek muhatap yoğunluğu.",
69: "Emir bir nesneye veriliyor ve nesne dişil tekil olarak muhatap alınıyor: يَٰنَارُ كُونِى *(ey ateş, ol)*, 2FS. Emrin içeriği iki ACC isim: بَرْدًۭا وَسَلَٰمًا *(serinlik ve esenlik)* — biri fiziksel bir nitelik, öteki bir durum adı; ikisi de aynı yükleme bağlı. Kapanış adı fâsıla yapıyor: عَلَىٰٓ إِبْرَٰهِيمَ *(İbrâhim'e)*. Ateşe verilen emir ile adın kendisi aynı cümlede.",
70: "İki irade karşı karşıya ve ikisi de aynı yapıda: أَرَادُوا۟ بِهِۦ كَيْدًۭا *(ona tuzak kurmak istediler)* 3MP, فَجَعَلْنَٰهُمُ ٱلْأَخْسَرِينَ *(onları en çok ziyana uğrayanlar kıldık)* 1P. Nesne ve fâil yer değiştiriyor: tuzağı kuranlar sonuçta tuzağın nesnesi oluyor. كيد *(tuzak, düzen)* kökü sûrede 21:57'de İbrâhim'in fiiliydi (لَأَكِيدَنَّ *(tuzak kuracağım)*); burada aynı kök karşı tarafın fiili. Beş kelimede iki fiil.",
71: "Kurtarma bir yer adıyla tamamlanıyor: إِلَى ٱلْأَرْضِ ٱلَّتِى بَٰرَكْنَا فِيهَا *(bereketli kıldığımız yere)* — yerin kendisi adlandırılmıyor, yalnız niteliğiyle anılıyor. برك *(bereket, mübarek kılma)* kökü sûrede 21:50'de indirilen zikir için kullanılmıştı; burada bir mekân için. Aynı nitelik, biri söze biri toprağa. Kapanış kapsamı genişletiyor: لِلْعَٰلَمِينَ *(âlemler için)*.",
72: "Verilen iki ad art arda ama biri fazladan işaretli: إِسْحَٰقَ وَيَعْقُوبَ نَافِلَةًۭ *(İshâk'ı ve fazladan Ya'kûb'u)*. نفل *(fazladan verilen, nafile)* ACC ve hâl konumunda — yani ikinci ad, birinciden farklı bir statüde veriliyor. Sonra ikisi de tek bir hükümde toplanıyor: وَكُلًّۭا جَعَلْنَا صَٰلِحِينَ *(hepsini salih kıldık)*, KELLA.",
73: "Şahıs dağılımı tam dengeli: 1P ×6, 3MP ×6. Verilen ile alan aynı ağırlıkta. Vahyin içeriği üç masdar-izafet halinde sıralanıyor: فِعْلَ ٱلْخَيْرَٰتِ *(hayırlar işlemek)* · إِقَامَ ٱلصَّلَوٰةِ *(namazı kılmak)* · إِيتَآءَ ٱلزَّكَوٰةِ *(zekâtı vermek)*. Üçü de ACC, üçü de fiil değil isim — yani buyruk, eylem olarak değil eylemin adı olarak veriliyor. Kapanış ise geriye fiile dönüyor: وَكَانُوا۟ لَنَا عَٰبِدِينَ *(bize kulluk edenlerdi)*.",
74: "Ad ayetin ilk kelimesi ve mef'ûl: وَلُوطًا *(Lût'a da)* — fiil sonra geliyor. Verilen şey 21:79 ile birebir aynı ikili: حُكْمًۭا وَعِلْمًۭا *(hüküm ve ilim)*. Kurtarma bir yerden çıkarma olarak veriliyor (مِنَ ٱلْقَرْيَةِ *(o ülkeden)*), ve yer bir fiil cümlesiyle nitelenip fâil hâline getiriliyor: ٱلَّتِى كَانَت تَّعْمَلُ ٱلْخَبَٰٓئِثَ *(pislikler işleyen)* — 3FS, yani kasabanın kendisi. Sonra zamir çoğula geçiyor: إِنَّهُمْ كَانُوا۟ *(onlar… idiler)*. Yer tekil dişil, halkı çoğul eril.",
75: "Altı kelimede tek fiil: أَدْخَلْنَٰهُ فِى رَحْمَتِنَآ *(onu rahmetimizin içine aldık)*. Rahmet burada bir hâl değil bir KAP olarak kuruluyor — فِى *(içinde)* ile mekân edatı alıyor. Kapanış aidiyet cümlesi: إِنَّهُۥ مِنَ ٱلصَّٰلِحِينَ *(o salihlerdendir)*, üç ayet önceki 21:72'nin fâsılasıyla aynı kök, bu kez marife ve bir kümenin adı.",
76: "Üç fiil, üçü de farklı bab ve hiçbiri bab I: نَادَىٰ *(seslendi)* bab III, ٱسْتَجَبْنَا *(icabet ettik)* bab X, نَجَّيْنَا *(kurtardık)* bab II. Yani ayet bir çağrı-cevap-sonuç zincirini üç ayrı kalıpla kuruyor. Zaman geriye alınıyor: مِن قَبْلُ *(daha önce)* — aynı ifade 21:51'de İbrâhim için kullanılmıştı. Kurtarılan iki: kişi ve ehli.",
77: "Kavim iki kez, ikisi de aynı anlamda ama farklı i'râbda: مِنَ ٱلْقَوْمِ *(kavimden)* GEN ve قَوْمَ سَوْءٍۢ *(kötü bir kavim)* ACC. Birincisi karşı taraf, ikincisi onun niteliği. Kapanış tek kelimeyle kapsamı kapatıyor: أَجْمَعِينَ *(hepsi birden)* — istisna bırakmıyor. Ayet dış düğüm sayısıyla (4) bloğun en bağlantılı ayeti; bağların hepsi sûre 7'nin helâk anlatılarına.",
78: "Sayı sistemi ayet boyunca kayıyor: يَحْكُمَانِ *(ikisi hüküm veriyordu)* 3MD ikil → نَفَشَتْ *(yayıldı)* 3FS (davar) → حُكْمِهِمْ *(onların hükmü)* 3MP çoğul. Hüküm veren iki kişi, ama hükmün sahibi çoğul olarak anılıyor. Aynı kök حكم *(hüküm verme, hikmet)* iki kez, biri fiil biri isim. Kapanış tanıklığı anlatıcıya veriyor: وَكُنَّا لِحُكْمِهِمْ شَٰهِدِينَ *(hükümlerine şahittik)* — 21:56'da İbrâhim kendini şahit saymıştı, burada anlatıcı.",
79: "Ayet iki verişi ayırıyor. Biri tekil ve hapaks bir fiille: فَفَهَّمْنَٰهَا سُلَيْمَٰنَ *(onu Süleymân'a kavrattık)* — فهم *(kavratma, anlatma (fehm))* bab II, korpusta tek geçiş, nesnesi 3FS zamir (hüküm). Öteki çoğul ve ortak: وَكُلًّا ءَاتَيْنَا حُكْمًۭا وَعِلْمًۭا *(her birine hüküm ve ilim verdik)*. Yani belirli bir meselenin kavranışı birine, hüküm ve ilim ikisine. Üçüncü hamle başka bir sıraya geçiyor: سَخَّرْنَا *(boyun eğdirdik)* bab II, nesneleri ٱلْجِبَالَ *(dağlar)* ve ٱلطَّيْرَ *(kuşlar)*. Sekiz 1P — bloğun en yoğun anlatıcı ayeti.",
80: "Öğretilen şey bir ürün değil bir YAPMA biçimi: صَنْعَةَ لَبُوسٍۢ *(zırh yapma sanatı)* — صنع *(yapma, işleme)* masdar ve izafet başı. Amaç bir korumadır ve korunulacak şey muhatabın kendisinden geliyor: لِتُحْصِنَكُم مِّنۢ بَأْسِكُمْ *(sizi kendi şiddetinizden koruması için)* — بَأْس *(şiddet)* iyelik ekiyle muhataba bağlı. Ayette bab I hiç yok; iki fiil de artırılmış kalıpta (bab II ve bab IV). Kapanış soru şükre bağlanıyor.",
}

BIYOLOG = {
79: "Çıpa: ٱلطَّيْرَ *(kuşlar)* — ayetteki tek canlı öğe, ve ٱلْجِبَالَ *(dağlar)* ile aynı fiile bağlı. Ölçülebilir olan şudur: iki nesne aynı i'râbda (ikisi de ACC, aynı سَخَّرْنَا *(boyun eğdirdik)* fiilinin mef'ûlü) ama fiil uyumu yalnız birine gidiyor — يُسَبِّحْنَ *(tesbih ederler)* 3FP ve ٱلْجِبَالَ'e bağlı; kuşlar وَ ile sonradan ekleniyor ve kendi yüklemini almıyor. Yani canlı ile cansız aynı listede, aynı hâlde, ama fiil canlıya değil cansıza uyuyor. طير *(kuş; uçma)* kökü korpusta 29 geçiş; komşuluk profili bu ayetten bağımsız olarak şekil-biçim ve طين *(çamur)* ağırlıklı, yani kökün tipik bağlamı 'yaratma-biçim' alanı. Bu ayette o alan yok; yerinde جبل *(dağ)* ve سبح *(tesbih)* var.",
}
UZAY = {79: None}

om = json.load(open('okuma_metni.json', encoding='utf-8'))
mk = json.load(open('mercek_kayit.json', encoding='utf-8'))

for n in range(61, 81):
    key = "21:%d" % n
    om['21'][key] = {'ar': AR[(21, n)], 'meal': MEAL[n], 'olcum': OLCUM[n],
                     'mercek': MERCEK[n], 'dikey': DIK[key]}
    if BIYOLOG.get(n): om['21'][key]['biyolog'] = BIYOLOG[n]
    if UZAY.get(n):    om['21'][key]['uzay'] = UZAY[n]
    mk['21'].append([key, MERCEK[n]])
for n, t in BIYOLOG.items():
    if t: mk['21_biyolog'].append(["21:%d" % n, t])

om['21']['_mercek_atlama_notu'] += (
 " 21:79 biyolog YAZILDI (طير *(kuş; uçma)* çıpası); uzay ATLANDI — ayetteki جبل *(dağ)* "
 "yer bilimine ait, gök öğesi yok; zorlama çıpa yapılmadı.")

om['ilerleme']['kismi']['21'] = "1-80 ayet düzeyinde"
om['ilerleme']['bekleyen']['21'] = "81-112"
om['ilerleme']['not'] = ("Sûre 20 TAM (135/135). Sûre 21 (Enbiyâ) makro + 21:1-80. Devam: 21:81. "
                         "Dikey katman A parçası birincil, B etiketsiz.")
om['ilerleme']['okunan_ayet'] = 1353

json.dump(om, open('okuma_metni.json', 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
json.dump(mk, open('mercek_kayit.json', 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
print("yazıldı · mercek 21:", len(mk['21']), "· biyolog:", len(mk['21_biyolog']))
