# -*- coding: utf-8 -*-
"""blok_24_1_20.py — sûre 24 (Nûr) makro profili + blok 24:1-20."""
import json
DIK=json.load(open('blok_dikey_24_1_20.json',encoding='utf-8'))
veri=json.load(open('kuran_veri.json',encoding='utf-8'))
AR={}
for s in veri['sureler']:
    for a in s['ayetler']: AR[(s['no'],a['no'])]=a['ar']

MAKRO={
 "ad":"NÛR","ayet":64,"kelime":1316,"ort_kelime":20.56,"tip":"Medenî",
 "nuzul":"102 (BELLEKTEN, doğrulanmadı)",
 "eksen":"**Allah 80 geçiş (1,74x) · Rab SIFIR.** Sûre 24, korpusun **en uzun sıfır-Rab sûresi** — 64 ayet, 1316 kelime; Rab'bin sıfır olduğu 20 sûre var ama ikinci sıradaki 48 (Fetih) 560 kelime, üçüncüsü 58 (Mücâdele) 472. Öteki sıfır-Rab sûrelerin çoğu kısa Mekkî ve onlarda lafız da sıfıra yakın. TAM AYNA: sûre 55 (Rahmân) — Allah 0, Rab 36 (8,08x), 78 ayet, Medenî. Lafız 50 ayette; lafızsız 14 ayet: 1, 3, 4, 11, 12, 16, 23, 24, 26, 27, 34, 49, 56, 57. Rab-sessizliği sûrenin tamamı. Bir önceki sûre (23) A/R=0,57 ve Rab 1,72x idi. (aday 498)",
 "kafiye":"N 54 · R 7 · ب 2 · ل 1 — **dört sınıf**. Son harf ن 31 · م 23 · ر 7 · ب 2 · ل 1. Kırık işaretli 2 ayet. Mü'minûn 118/118 tek sınıftaydı; Nûr'un fâsıla düzeni ن ile م arasında salınıyor.",
 "esma":"**62 token / 36 ayet / MÜHÜR 12** — okumada görülen en yüksek mühür sayısı (Hac 11, Mü'minûn 0). عَلِيم *(alîm)* 10 · مُؤْمِن *(mü'min)* 9 · نُور *(nûr)* 7 · رَحِيم *(rahîm)* 5 · آخِر *(son; âhiret)* 4 · شَهِيد *(şahit)* 4 · غَفُور *(gafûr)* 4 · حَكِيم *(hakîm)* 4 · أَحَد *(bir)* 3 · مُبِين *(apaçık)* 3 · سَمِيع *(semîʼ)* 2 · خَبِير *(habîr)* 2 · تَوّاب · رَءُوف · كَرِيم · واسِع · قَدِير birer. **BAĞLAM DENETİMİ (adaylar 461, 501):** mühürlü konumların hepsi çift kapanış ve geçerli; mühürsüz konumlar sistematik kirli — مُؤْمِن'in dokuzu da çoğul ve insanlar, آخِر'in dördü âhiret, شَهِيد'in dördü tanıklar. Sûre 23'te mühür sıfır ve hata %67'ydi; burada mühür 12 ve mühürlü konumlarda hata görülmedi.",
 "soz_edimi":"haber 33 · **emir 16 · şart 15 · yasak 12** · soru 4 · nida 3 (Mü'minûn'da yasak 3'tü)",
 "fig":"**NEHY 12** · DIKKAT 7 · HASR 5 · IDRAB 2 · QASEM 1",
 "dilbilgisi":"i'râb GEN 248 · NOM 194 · ACC 174 · zaman **IMPF 177** · PERF 83 · IMPV 20 · bab I 176 · IV 51 · II 20 · X 12 · VIII 10 · V 9 · III 2 · edilgen 14 fiil / 11 ayet · **iltifât SIFIR** (Mü'minûn'da yedi vardı)",
 "yildiz":{"0":29,"1":11,"2":9,"3":15},
 "yildiz3":[10,18,20,25,31,32,33,35,42,49,50,52,58,61,63],
 "hapaks":"Dört ayette ve hepsi tekil: 24:32 أيم *(bekâr, eşsiz)* · 24:49 ذعن *(boyun eğerek koşma)* · 24:50 حيف *(haksızlık, meyletme)* · 24:63 لوذ *(sığınıp gizlenme)*.",
 "esit":"Tek tam-ayet ikizi: **24:5 ↔ 3:89**.",
 "aktor":"Adlı yalnız **شَيْطان *(şeytan)* ×2**; adsız ferîk *(bir bölük)* ×2, tâife *(bir grup)*, imrae *(bir kişi)*, racül *(bir adam)*. 64 ayette tek adlı aktör — okumada görülen en düşük adlı-aktör sayısı. **Aday 462 gereği aktör yoğunluğu KARŞILAŞTIRMASI yapılmadı.**",
 "sozluk":"285 farklı kök / 860 kök-token. Zenginleşme: **بيت *(ev)* ×11,21 · أذن *(izin; kulak)* ×5,16 · فضل *(üstün kılma, lütuf)* ×4,50 · شهد *(şahitlik)* ×4,02 · طوع *(güç yetirme, itaat)* ×3,62 · نور *(nûr, ışık)* ×2,71 · رحم *(rahmet, merhamet)* ×1,72 · أله *(ilâh; lafza-i celâl)* ×1,64.** Buna karşılık قول *(söz söyleme)* ×0,41 ve كون *(olmak)* ×0,46 — Mü'minûn'da قول baskındı (×1,60).",
 "en_uzun_kisa":"En uzun **24:31 (n=78)** — okumada görülen en uzun ayet. En kısa **24:18 (n=7)**.",
 "not":"Sûre 23 TAM okundu (118/118). Sûre 24 Medenî; Hac'tan (22) sonra okunan ikinci Medenî sûre, dolayısıyla A/R karşılaştırmasında (aday 470) tip-eşli ikinci veri noktası. 24:31 okunduğunda yıldız formülünün UZUN ayet davranışı ölçülecek (adaylar 468, 472)."
}

MEAL={
1:"Bir sûre — onu indirdik ve farz kıldık; içinde apaçık âyetler indirdik, belki düşünürsünüz diye.",
2:"Zina eden kadın ve zina eden erkek — her birine yüz değnek vurun. Allah'ın dininde onlara acımanız sizi tutmasın, Allah'a ve âhiret gününe inanıyorsanız. Cezalarına mü'minlerden bir grup da tanık olsun.",
3:"Zina eden erkek ancak zina eden ya da ortak koşan bir kadınla nikâhlanır; zina eden kadınla da ancak zina eden ya da ortak koşan bir erkek nikâhlanır. Bu, mü'minlere haram kılınmıştır.",
4:"İffetli kadınlara iftira atıp sonra dört tanık getirmeyenlere seksen değnek vurun ve onların tanıklığını bir daha asla kabul etmeyin. İşte onlar fâsıklardır.",
5:"Bundan sonra tevbe edip düzeltenler dışında; Allah bağışlayandır, merhamet edendir.",
6:"Eşlerine iftira atıp da kendilerinden başka tanıkları olmayanlara gelince: onlardan birinin tanıklığı, \"doğru söyleyenlerdenim\" diye Allah adına dört kez tanıklık etmektir.",
7:"Beşincisi de, yalan söyleyenlerdense Allah'ın lânetinin üzerine olmasıdır.",
8:"Kadından cezayı savan şey, \"o yalan söyleyenlerdendir\" diye Allah adına dört kez tanıklık etmesidir.",
9:"Beşincisi de, o doğru söyleyenlerdense Allah'ın gazabının üzerine olmasıdır.",
10:"Allah'ın size lütfu ve merhameti olmasaydı, ve Allah tevbeleri kabul eden, hikmet sahibi olmasaydı…",
11:"O iftirayı getirenler içinizden bir güruhtur. Onu kendiniz için kötü sanmayın; aksine sizin için hayırdır. Onlardan her kişiye kazandığı günah vardır; büyüğünü üstlenene ise büyük bir azap vardır.",
12:"Onu işittiğinizde mü'min erkekler ve mü'min kadınlar kendileri hakkında iyi düşünüp \"bu apaçık bir iftiradır\" deselerdi ya!",
13:"Buna dört tanık getirselerdi ya! Tanıkları getirmediklerine göre, işte onlar Allah katında yalancıların ta kendileridir.",
14:"Allah'ın dünyada ve âhirette size lütfu ve merhameti olmasaydı, daldığınız şey yüzünden size büyük bir azap dokunurdu.",
15:"Hani onu dillerinizle alıp veriyor, hakkında bilginiz olmayan şeyi ağızlarınızla söylüyor ve onu önemsiz sanıyordunuz; oysa o Allah katında büyüktür.",
16:"Onu işittiğinizde \"bunu konuşmak bize düşmez; seni tenzih ederiz, bu büyük bir iftiradır\" deseydiniz ya!",
17:"Mü'minseniz, bunun benzerine bir daha dönmemeniz için Allah size öğüt veriyor.",
18:"Allah size âyetleri açıklıyor; Allah bilendir, hikmet sahibidir.",
19:"İnananlar arasında hayâsızlığın yayılmasını isteyenlere dünyada da âhirette de acı bir azap vardır. Allah bilir, siz bilmezsiniz.",
20:"Allah'ın size lütfu ve merhameti olmasaydı, ve Allah çok şefkatli, çok merhametli olmasaydı…",
}

OLCUM={
1:"eksen: lafız yok · Rab yok · aktör yok · edim haber · şahıs 1P ×6 · 3FS ×3 · 2MP ×3 · n=9 mora=71 harf=69, fâsıla تَذَكَّرُونَ *(düşünürsünüz)* → ن, N sınıfı; i'râb NOM 1 · ACC 3; bab I ×1 · bab IV ×2 · bab V ×1; zaman PERF ×3 · IMPF 1; kök ikilemesi نزل *(inme, indirme)* ×2 · yıldız ★ yok · kökler سور *(bilezik; sur, sûre)* · نزل · فرض *(farz kılma, belirleme)* · أيي *(âyet, işaret)* · بين *(arası; açıklama)* · ذكر *(anma, zikir)* · bağ: **24:18 ile bölüm halkası** — orada âyetler indiriliyor (بَيِّنَٰت *(apaçık)*), 24:18'de açıklanıyor (يُبَيِّنُ *(açıklar)*); aynı kök بين iki uçta (elle, L1). NOT: besmele okuma metnine dâhil edilmedi (n=9).",
2:"eksen: **Allah lafzı 15. ve 19. sırada — iki geçiş** (allah z=1,01) · **esmâ آخِر *(son)* 21. sırada — ÖLÇÜM ARTEFAKTI (aday 461)**: ٱلْيَوْمِ ٱلْءَاخِرِ *(âhiret günü)*, ölçüt (d); **esmâ مُؤْمِن *(mü'min)* 26. sırada — ÖLÇÜM ARTEFAKTI**: çoğul ve göndergesi insanlar · **aktör: adsız tâife *(bir grup)* 24. sırada** · edim emir + yasak + şart, kip IMPV ×2 · PRO 1 · COND 1 · şahıs 2MP ×7 · 3D ×3 · 3FS 1 · 3MS 1 · **n=26 mora=149 harf=130** (n z=1,44), fâsıla ٱلْمُؤْمِنِينَ *(mü'minler)* → ن, N sınıfı; i'râb GEN 8 · NOM 4 · ACC 3; bab I ×4 · bab IV ×1; zaman IMPV 1 · IMPF ×3 · PERF 1; **kök ikilemesi زني *(zina)* ×2 · جلد *(deri; kırbaçlama)* ×2 · أله *(ilâh; lafza-i celâl)* ×2 · أمن *(güven; iman)* ×2 — dört kök birden**; sayı sözcüğü واحِد *(bir)*; biçim NEHY · yıldız ★ yok · kökler زني · جلد · كلل *(hep, bütün)* · وحد *(bir olma, teklik)* · مأي *(yüz (sayı))* · أخذ *(alma, edinme)* · رأف *(şefkat, raafet)* · دين *(din; borç)* · أله · كون *(olmak)* · أمن · يوم *(gün)* · أخر *(geciktirme, sonraya bırakma)* · شهد *(şahitlik)* · عذب *(azap)* · طوف *(dolaşma, tavaf)* · bağ yok",
3:"eksen: lafız yok · **esmâ مُؤْمِن *(mü'min)* 18. sırada — ÖLÇÜM ARTEFAKTI (aday 461)** · aktör yok · edim haber, kip NEG ×2 · RES ×2 · şahıs 3MS ×3 · 3FS 1 · n=18 mora=98 harf=76, fâsıla ٱلْمُؤْمِنِينَ → ن, N sınıfı; i'râb NOM 4 · ACC 2 · GEN 1; bab I ×2 · bab II ×1; zaman IMPF ×2 · PERF 1; edilgen 1 (pas z=1,57); **kök ikilemesi زني *(zina)* ×4 · نكح *(nikâh, evlenme)* ×2 · شرك *(ortak koşma)* ×2**; biçim HASR; simetri [6,2,9,2] · yıldız ★ · kökler زني · نكح · شرك · حرم *(haram kılma, yasak)* · أمن *(güven; iman)* · bağ: **24:2 ile ters cinsiyet sırası** — orada dişil önce, burada eril (elle, L1)",
4:"eksen: lafız yok · **esmâ شَهِيد *(şahit)* 8. sırada — ÖLÇÜM ARTEFAKTI (aday 461)**: شُهَدَآء çoğul ve insanlar · aktör yok · edim emir + yasak, kip NEG 1 · IMPV 1 · PRO 1 · şahıs 3MP ×7 · 2MP ×4 · n=19 mora=113 harf=96, fâsıla ٱلْفَٰسِقُونَ *(fâsıklar)* → ن, N sınıfı; i'râb ACC 5 · GEN 2 · NOM 1; bab I ×4; zaman IMPF ×3 · IMPV 1; **kök ikilemesi شهد *(şahitlik)* ×2 · جلد *(deri; kırbaçlama)* ×2**; sayı sözcüğü أَرْبَعَة *(dört)* ve ثَمانِين *(seksen)*; biçim NEHY; simetri [3,4,17,1] · yıldız ★ yok · kökler رمي *(atma)* · حصن *(koruma, sağlamlaştırma; iffet)* · أتي *(gelme, getirme)* · ربع *(dört; dörtte bir)* · شهد · جلد · ثمن *(bedel, fiyat; sekiz)* · قبل *(ön, önce; kabul)* · أبد *(ebedîlik)* · فسق *(fâsıklık)* · bağ: **24:2 ile ortak جلد** — sayı yüzden seksene iniyor, ama tanıklık reddi ekleniyor (elle, L1)",
5:"eksen: **Allah lafzı 9. sırada** (allah z=1,29) · **esmâ غَفُور *(gafûr)* 10. + رَحِيم *(rahîm)* 11. sırada — MÜHÜR, çift kapanış; sûrenin on iki mühründen ilki; GEÇERLİ (aday 501)** · aktör yok · edim haber, kip RES 1 · şahıs 3MP ×4 · n=11 mora=58 harf=48, **fâsıla رَّحِيمٌۭ → م**, N sınıfı; i'râb GEN 1 · ACC 2 · NOM 2; bab I ×1 · bab IV ×1; zaman PERF ×2; biçim HASR; simetri [3,2,6,1]; dış düğüm 1 · yıldız ★ yok · kökler توب *(tevbe, dönüş)* · بعد *(sonra; uzaklık)* · صلح *(iyi, elverişli olma; ıslah)* · أله *(ilâh; lafza-i celâl)* · غفر *(bağışlama, mağfiret)* · رحم *(rahmet, merhamet)* · bağ: **tam-ayet ikizi 3:89 — sûrenin tek tam ikizi**; xref بعد *(sonra)* + أصلح *(düzeltti)* + اللّه *(Allah)* → 3:89",
6:"eksen: **Allah lafzı 14. sırada** (allah z=0,65) · **esmâ شَهِيد *(şahit)* 7. + أَحَد *(bir)* 11. sırada — İKİSİ DE ÖLÇÜM ARTEFAKTI (aday 461)** · aktör yok · edim haber, kip NEG 1 · RES 1 · EMPH 1 · şahıs 3MP ×6 · 3MS ×2 · n=17 mora=98 harf=79, fâsıla ٱلصَّٰدِقِينَ *(doğru söyleyenler)* → ن, N sınıfı; i'râb NOM 4 · GEN 4 · ACC 2; bab I ×2; zaman IMPF ×2; **kök ikilemesi شهد *(şahitlik)* ×3 — n=17'de üç kez, üç ayrı biçimde**; sayı sözcüğü زَوْج *(eş)* · أَحَد *(bir)* · أَرْبَع *(dört)*; biçim HASR · yıldız ★ yok · kökler رمي *(atma)* · زوج *(eş, çift)* · كون *(olmak)* · شهد · نفس *(nefis, can)* · أحد *(bir, hiç kimse)* · ربع *(dört; dörtte bir)* · أله *(ilâh; lafza-i celâl)* · صدق *(doğruluk)* · bağ: **24:8 ile aynalı çift** — aynı sayı, aynı yemin, fâsılalar çaprazlanmış (elle, L1, aday 499)",
7:"eksen: **Allah lafzı 4. sırada — n=9'da tek lafız, allah z=1,69** · aktör yok · edim şart, kip COND 1 · şahıs 3MS ×2 · n=9 mora=43 harf=35, fâsıla ٱلْكَٰذِبِينَ *(yalancılar)* → ن, N sınıfı; i'râb NOM 1 · ACC 2 · GEN 2; bab I ×1; zaman PERF 1; sayı sözcüğü خامِسَة *(beşinci)* · yıldız ★ · kökler خمس *(beş)* · لعن *(lânet, kovma)* · أله *(ilâh; lafza-i celâl)* · كون *(olmak)* · كذب *(yalan; yalanlama)* · bağ: **24:9 ile DAR İKİZ — dokuz kelimenin yedisi birebir aynı** (aday 499); NOT: لعن korpusta Allah medyan mesafesi 2 — okumada görülen en düşük değerlerden biri (elle, L1)",
8:"eksen: **Allah lafzı 8. sırada** (allah z=1,29) · aktör yok · edim haber, kip EMPH 1 · şahıs 3MS ×2 · 3FS ×2 · n=11 mora=58 harf=52, fâsıla ٱلْكَٰذِبِينَ *(yalancılar)* → ن, N sınıfı; i'râb ACC 3 · GEN 3; bab I ×2; zaman IMPF ×2; kök ikilemesi شهد *(şahitlik)* ×2; sayı sözcüğü أَرْبَع *(dört)* · yıldız ★ yok · kökler درأ *(savma, def etme (dereʾ))* · عذب *(azap)* · شهد · ربع *(dört; dörtte bir)* · أله *(ilâh; lafza-i celâl)* · كذب *(yalan; yalanlama)* · bağ: **24:6 ile aynalı kalıp** — orada iddia ve fâsıla ٱلصَّٰدِقِينَ, burada savunma ve fâsıla ٱلْكَٰذِبِينَ (elle, L1, aday 499)",
9:"eksen: **Allah lafzı 4. sırada — n=9'da tek lafız, allah z=1,69** · aktör yok · edim şart, kip COND 1 · şahıs 3FS 1 · 3MS 1 · n=9 mora=46 harf=35, fâsıla ٱلصَّٰدِقِينَ *(doğru söyleyenler)* → ن, N sınıfı; i'râb ACC 3 · GEN 2; bab I ×1; zaman PERF 1; sayı sözcüğü خامِسَة *(beşinci)*; dış düğüm 1 · yıldız ★ · kökler خمس *(beş)* · غضب *(öfke, gazap)* · أله *(ilâh; lafza-i celâl)* · كون *(olmak)* · صدق *(doğruluk)* · bağ: xref غضب *(gazap)* + اللّه *(Allah)* + كان *(oldu)* → 2:61; **24:7 ile DAR İKİZ** — fark tam olarak iki kelimede: لَعْنَت *(lânet)* → غَضَب *(gazap)*, ٱلْكَٰذِبِينَ → ٱلصَّٰدِقِينَ; mora 43 → 46, harf 35 = 35 (elle, L1, aday 499)",
10:"eksen: **Allah lafzı 3. ve 7. sırada — n=9'da İKİ lafız, allah z=3,92: yıldızın tek kaynağı (aday 472)** · **esmâ تَوّاب *(tevvâb)* 8. + حَكِيم *(hakîm)* 9. sırada — MÜHÜR, çift kapanış; GEÇERLİ (aday 501)** · aktör yok · edim şart, kip COND 1 · şahıs 2MP 1 · 3MS 1 · n=9 mora=49 harf=39, **fâsıla حَكِيمٌ → م**, N sınıfı; i'râb NOM 4 · GEN 1 · ACC 2; **fiil yok**; kök ikilemesi أله *(ilâh; lafza-i celâl)* ×2; dış düğüm 2 · iç düğüm 1 · yıldız ★★★ · kökler فضل *(üstün kılma, lütuf)* · أله · رحم *(rahmet, merhamet)* · توب *(tevbe, dönüş)* · حكم *(hüküm verme, hikmet)* · bağ: xref اللّه + رحمة *(rahmet)* + اللّه → **9:99 · 11:73 · 24:20**; **24:14 ve 24:20 ile üçlü şart kalıbı; ŞARTIN CEVABI YOK** (elle, L1, aday 500)",
11:"eksen: lafız yok · **aktör: adsız imrae *(bir kişi)* 16. sırada** · edim yasak, kip PRO 1 · şahıs 3MP ×4 · 2MP ×5 · 3MS ×6 · **n=28 mora=136 harf=112 — bloğun en uzun ayeti** (n z=1,65), **fâsıla عَظِيمٌۭ → م**, N sınıfı; i'râb ACC 3 · GEN 4 · NOM 4; bab I ×2 · bab V ×1 · bab VIII ×1; zaman PERF ×3 · IMPF 1; biçim NEHY · IDRAB; simetri [4,11,17,1] · yıldız ★ · kökler جيأ *(gelme)* · أفك *(iftira, uydurma (ifk); döndürülme)* · عصب *(topluluk, güruh (usbe))* · حسب *(hesap, sayma)* · شرر *(şer, kötülük)* · خير *(hayır, daha iyi)* · كلل *(hep, bütün)* · مرأ *(kişi; kadın (imrae))* · كسب *(kazanma, kesb)* · أثم *(günah, ism)* · ولي *(dost, veli; velâyet)* · كبر *(büyüklük; büyüklenme)* · عذب *(azap)* · عظم *(büyüklük, azamet; kemik)* · bağ yok",
12:"eksen: lafız yok · **esmâ مُؤْمِن *(mü'min)* 5. + مُبِين *(apaçık)* 12. sırada — İKİSİ DE ÖLÇÜM ARTEFAKTI (aday 461)**: birincisi insanlar, ikincisi إِفْكٌ مُّبِينٌ *(apaçık iftira)* tamlamasında niteleyen, ölçüt (c) · aktör yok · edim haber · şahıs 2MP ×2 · 3MS ×2 · 3MP ×3 · n=12 mora=79 harf=62, fâsıla مُّبِينٌۭ → ن, N sınıfı; i'râb NOM 4 · GEN 1 · ACC 1; bab I ×3; zaman PERF ×3; kök ikilemesi أمن *(güven; iman)* ×2 — eril ve dişil çoğul; biçim DIKKAT · yıldız ★ yok · kökler سمع *(işitme)* · ظنن *(zan, sanma)* · أمن · نفس *(nefis, can)* · خير *(hayır, daha iyi)* · قول *(söz söyleme)* · أفك *(iftira, uydurma (ifk))* · بين *(arası; açıklama)* · bağ: **24:16 ile aynı açılış** لَّوْلَآ إِذْ سَمِعْتُمُوهُ *(onu işittiğinizde … deseydiniz ya)*, arada üç ayet (elle, L1)",
13:"eksen: **Allah lafzı 12. sırada** (allah z=0,90) · **esmâ شَهِيد *(şahit)* 5. ve 9. sırada — İKİSİ DE ÖLÇÜM ARTEFAKTI (aday 461)** · aktör yok · edim haber, kip NEG 1 · şahıs 3MP ×5 · 3MS 1 · n=14 mora=83 harf=66, fâsıla ٱلْكَٰذِبُونَ *(yalancılar)* → ن, N sınıfı; i'râb GEN 3 · ACC 2 · NOM 1; bab I ×2; zaman PERF 1 · IMPF 1; kök ikilemesi شهد *(şahitlik)* ×2; sayı sözcüğü أَرْبَعَة *(dört)*; simetri [4,3,7,1] · yıldız ★ yok · kökler جيأ *(gelme)* · ربع *(dört; dörtte bir)* · شهد · أتي *(gelme, getirme)* · عند *(kat, yan)* · أله *(ilâh; lafza-i celâl)* · كذب *(yalan; yalanlama)* · bağ: **24:4 ile aynı dört-tanık ölçütü** — orada hüküm, burada tespit aracı (elle, L1)",
14:"eksen: **Allah lafzı 3. sırada** (allah z=0,81) · **esmâ آخِر *(son)* 8. sırada — ÖLÇÜM ARTEFAKTI (aday 461)**: ٱلْءَاخِرَة *(âhiret)*, ölçüt (d) · aktör yok · edim şart, kip COND 1 · EMPH 1 · şahıs 2MP ×4 · 3MS ×3 · n=15 mora=80 harf=65, **fâsıla عَظِيمٌ → م**, N sınıfı; i'râb NOM 4 · GEN 3; bab I ×1 · bab IV ×1; zaman PERF ×2; simetri [3,4,11,1] · yıldız ★ yok · kökler فضل *(üstün kılma, lütuf)* · أله *(ilâh; lafza-i celâl)* · رحم *(rahmet, merhamet)* · دنو *(yakınlık; dünya)* · أخر *(geciktirme, sonraya bırakma)* · مسس *(dokunma, temas)* · فيض *(taşma, feyz)* · عذب *(azap)* · عظم *(büyüklük, azamet; kemik)* · bağ: **24:10 · 24:14 · 24:20 üçlü kalıbı — YALNIZ BU AYETTE ŞARTIN CEVABI VAR** (لَمَسَّكُمْ *(size dokunurdu)*) ve bu ayette esmâ mühürü YOK (elle, L1, aday 500)",
15:"eksen: **Allah lafzı 15. sırada** (allah z=0,72) · aktör yok · edim haber · şahıs 2MP ×9 · 3MS ×5 · n=16 mora=86 harf=76, **fâsıla عَظِيمٌۭ → م**, N sınıfı; i'râb GEN 3 · NOM 2 · ACC 2; bab I ×3 · bab V ×1; zaman IMPF ×3 · PERF 1; dış düğüm 2 · yıldız ★ yok · kökler لقي *(karşılaşma, kavuşma; atma)* · لسن *(dil (organ); lisan)* · قول *(söz söyleme)* · فوه *(ağız)* · ليس *(değil)* · علم *(bilme)* · حسب *(hesap, sayma)* · هون *(kolaylık, hafiflik)* · عند *(kat, yan)* · أله *(ilâh; lafza-i celâl)* · عظم *(büyüklük, azamet; kemik)* · bağ: xref قال *(dedi)* + أفواه *(ağızlar)* + ليس *(değil)* → 3:167 · عند + اللّه + عظيم *(büyük)* → 33:53; **24:11 ile ortak حسب** — orada kötü sanma, burada önemsiz sanma (elle, L1)",
16:"eksen: lafız yok · aktör yok · edim haber, kip NEG 1 · şahıs 2MP ×4 · 3MS ×2 · 1P ×2 · 2MS 1 · n=14 mora=77 harf=55, **fâsıla عَظِيمٌۭ → م**, N sınıfı; i'râb ACC 1 · NOM 2; bab I ×3 · bab V ×1; zaman PERF ×2 · IMPF ×2; biçim DIKKAT; simetri [3,1,7,1] · yıldız ★ yok · kökler سمع *(işitme)* · قول *(söz söyleme)* · كون *(olmak)* · كلم *(söz, konuşma)* · سبح *(tesbih, tenzih)* · بهت *(bühtan, şaşırtıcı iftira)* · عظم *(büyüklük, azamet; kemik)* · bağ: **24:12 ile aynı açılış**; terim değişiyor: إِفْك *(iftira)* → بُهْتَٰن *(bühtan)* (elle, L1)",
17:"eksen: **Allah lafzı 2. sırada — n=9'da tek lafız, allah z=1,69** · **esmâ مُؤْمِن *(mü'min)* 9. sırada — ÖLÇÜM ARTEFAKTI (aday 461)** · aktör yok · edim şart, kip COND 1 · şahıs 3MS ×2 · 2MP ×5 · n=9 mora=51 harf=40, fâsıla مُّؤْمِنِينَ → ن, N sınıfı; i'râb NOM 1 · GEN 1 · ACC 2; bab I ×3; zaman IMPF ×2 · PERF 1 · yıldız ★ · kökler وعظ *(öğüt, vaʼz)* · أله *(ilâh; lafza-i celâl)* · عود *(geri dönme)* · مثل *(benzer, mesel)* · أبد *(ebedîlik)* · كون *(olmak)* · أمن *(güven; iman)* · bağ: **24:4 ile ortak أَبَدًا *(asla)*** — orada tanıklığın süresiz reddi, burada tekrarın süresiz yasağı (elle, L1)",
18:"eksen: **Allah lafzı 2. ve 5. sırada — n=7'de İKİ lafız, allah z=5,18: SÛRENİN VE OKUMANIN EN YÜKSEK LAFIZ YOĞUNLUĞU; yıldızın tek kaynağı (aday 472)** · **esmâ عَلِيم *(alîm)* 6. + حَكِيم *(hakîm)* 7. sırada — MÜHÜR, çift kapanış; GEÇERLİ (aday 501)** · aktör yok · edim haber · şahıs 3MS 1 · 2MP 1 · **n=7 mora=42 harf=32 — SÛRENİN EN KISA AYETİ**, **fâsıla حَكِيمٌ → م**, N sınıfı; i'râb NOM 4 · ACC 1; bab II ×1; zaman IMPF 1; kök ikilemesi أله *(ilâh; lafza-i celâl)* ×2; dış düğüm 1 · iç düğüm 2 · yıldız ★★★ · kökler بين *(arası; açıklama)* · أله · أيي *(âyet, işaret)* · علم *(bilme)* · حكم *(hüküm verme, hikmet)* · bağ: xref اللّه + آية *(âyet)* + اللّه → **22:52 · 24:58 · 24:59**; **24:1 ile bölüm halkası** — orada بَيِّنَٰت *(apaçık)* sıfat, burada يُبَيِّنُ *(açıklar)* fiil (elle, L1)",
19:"eksen: **Allah lafzı 16. sırada** (allah z=0,47) · **esmâ آخِر *(son)* 15. sırada — ÖLÇÜM ARTEFAKTI (aday 461)** · aktör yok · edim haber, kip NEG 1 · şahıs 3MP ×5 · 3FS 1 · 3MS 1 · 2MP ×3 · n=20 mora=108 harf=89, fâsıla تَعْلَمُونَ *(bilirsiniz)* → ن, N sınıfı; i'râb NOM 4 · GEN 2 · ACC 1; bab I ×3 · bab IV ×2; zaman IMPF ×4 · PERF 1; kök ikilemesi علم *(bilme)* ×2 — biri olumlu biri olumsuz; simetri [4,1,7,1]; dış düğüm 2 · yıldız ★ yok · kökler حبب *(sevgi)* · شيع *(yayılma; şîa)* · فحش *(çirkinlik, hayâsızlık (fahşâ))* · أمن *(güven; iman)* · عذب *(azap)* · ألم *(elem, acı)* · دنو *(yakınlık; dünya)* · أخر *(geciktirme, sonraya bırakma)* · أله *(ilâh; lafza-i celâl)* · علم · bağ: xref عذاب *(azap)* + أليم *(acı)* + دنيا *(dünya)* → 9:74 · دنيا + آخر *(âhiret)* + اللّه → 16:107; **24:15 ile ortak علم** — orada bilginin yokluğu, burada bilgi asimetrisi (elle, L1)",
20:"eksen: **Allah lafzı 3. ve 7. sırada — n=9'da İKİ lafız, allah z=3,92: yıldızın tek kaynağı (aday 472)** · **esmâ رَءُوف *(raûf)* 8. + رَحِيم *(rahîm)* 9. sırada — MÜHÜR, çift kapanış; GEÇERLİ (aday 501)** · aktör yok · edim şart, kip COND 1 · şahıs 2MP 1 · 3MS 1 · n=9 mora=49 harf=41, **fâsıla رَّحِيمٌۭ → م**, N sınıfı; i'râb NOM 4 · GEN 1 · ACC 2; **fiil yok**; kök ikilemesi أله *(ilâh; lafza-i celâl)* ×2 · رحم *(rahmet, merhamet)* ×2; **dış düğüm 3** · iç düğüm 1 · yıldız ★★★ · kökler فضل *(üstün kılma, lütuf)* · أله · رحم · رأف *(şefkat, raafet)* · bağ: **24:10 ile sûre-içi bölüt ikizi — dokuz kelimenin yedisi birebir aynı; değişen yalnız esmâ çifti** (elle, L1, aday 500)",
}

MERCEK={
1:"Korpusta kendini 'sûre' diye adlandırarak açılan tek yer burası — سُورَةٌ nekre ve cümlenin ilk kelimesi. Metin önce kendi birimini adlandırıyor, sonra o birime iki işlem uyguluyor: أَنزَلْنَٰهَا *(indirdik)* ve فَرَضْنَٰهَا *(farz kıldık)*. İkinci fiil ölçülebilir biçimde seyrek bir yerde: فرض *(farz kılma, belirleme)* korpusta 18 geçişli ve dikey ölçüm komşuluğunda مسس *(dokunma, temas)* ×30,5 veriyor. İnme fiili iki kez ve nesnesi değişiyor: önce sûrenin kendisi, sonra içindeki âyetler.",
2:"Hüküm ayeti üç dilbilgisi kipini üst üste yığıyor: emir, yasak, şart — ve dördüncü olarak yine emir (وَلْيَشْهَدْ *(tanık olsun)*, lâm-ı emir). Ölçülebilir bir sıralama var: fiil → duygu yasağı → koşul → tanıklık. Ceza tek başına bırakılmıyor, üç katmanla çevreleniyor. Sözdiziminde bir sıra da işaretli: ٱلزَّانِيَةُ *(zina eden kadın)* önce, ٱلزَّانِى *(zina eden erkek)* sonra. Dikey ölçüm جلد *(kırbaçlama)* kökünün زني *(zina)* ile bağını veriyor: زني ▸sonra celde ×650,0.",
3:"Ayet iki kez aynı cümleyi kuruyor ve yalnız cinsiyeti çeviriyor — simetri ölçümü [6,2,9,2] bunu doğruluyor. Her yarıda aynı HASR kalıbı (لَا … إِلَّا *(ancak … dır)*) ve aynı ikili seçenek. Ölçülebilir bir sıra tersliği: 24:2'de dişil önce geliyordu, burada eril. Kapanış edilgen: حُرِّمَ *(haram kılındı)* — hükmü koyanın adı geçmiyor, oysa bir önceki ayette iki kez geçiyordu.",
4:"İki ceza arasındaki fark sayıya bağlanmış: 24:2'de مِا۟ئَةَ جَلْدَةٍ *(yüz değnek)*, burada ثَمَٰنِينَ جَلْدَةً *(seksen değnek)*. Ve ikinci cezaya bir ek konuyor: tanıklığın süresiz reddi — أَبَدًا *(asla)*. Bedensel ceza azalırken hukukî ceza ekleniyor. شهد *(şahitlik)* kökü ayette iki kez ve iki ayrı işlevde: eksik olan tanıklar, reddedilen tanıklık. Atma fiili رمي *(atma)* mecazî; korpusta dokuz geçişli ve komşuluğunda قتل *(öldürme)* ×16,7.",
5:"Üç ayetlik ceza dizisi bir istisnayla kapanıyor ve istisna aynı HASR kalıbıyla: إِلَّا *(ancak)*. Ölçülebilir olan konum: mühürlü esmâ çifti tam burada, yani cezanın değil affın yanında. Fâsıla ilk kez م — sûrenin ن/م salınımı burada başlıyor. توب *(tevbe, dönüş)* ile صلح *(iyi, elverişli olma; ıslah)* çifti dikey ölçümde de eşleşiyor: dönüş tek başına değil, bir düzeltmeyle birlikte adlandırılıyor.",
6:"24:4'ün koşulu burada bir dönüşüm geçiriyor ve dönüşüm sayıda değil öznede: dört tanık yerine dört kez tanıklık, ve tanık kendisi. شهد *(şahitlik)* kökü on yedi kelimede üç kez, üçünde de ayrı biçim: شُهَدَآء *(tanıklar)*, شَهَٰدَة *(tanıklık)*, شَهَٰدَٰت *(tanıklıklar)*. Sayı sözcükleri de yığılıyor: üç ayrı sayı terimi tek ayette. Tanıklık lafzın adına bağlanıyor — بِٱللَّهِ *(Allah adına)*.",
7:"Dört tanıklığın üstüne beşinci ekleniyor ve beşinci ötekilerden farklı: ilk dördü olumlama, bu bir şarta bağlı bedduâ. Sayı sıralaması ölçülebilir biçimde işaretlenmiş — أَرْبَع *(dört)* asıl sayı, خَامِسَة *(beşinci)* sıra sayısı; kalıp saymadan sıralamaya geçiyor. لعن *(lânet, kovma)* korpusta 41 geçişli ve Allah medyan mesafesi 2 — kök korpusta neredeyse hep lafzın yanında.",
8:"Karşı taraf aynı yapıyı ters yönde kuruyor: dört tanıklık, aynı yemin, aynı fâsıla sınıfı. Fark tek bir fiilde — درأ *(savma, def etme (dereʾ))*, korpusta beş geçişli ve komşuluğunda eşik üstü hiçbir kavram yok. İki ayetin fâsılaları çaprazlanmış: 24:6 ٱلصَّٰدِقِينَ *(doğru söyleyenler)* ile bitiyor, bu ٱلْكَٰذِبِينَ *(yalancılar)* ile — iddia doğruluk iddiasıyla, savunma yalancılık isnadıyla kapanıyor.",
9:"Dört ayetlik yapının kapanışı ve 24:7 ile arasındaki fark tam olarak iki kelimede: لَعْنَت *(lânet)* → غَضَب *(gazap)*, ve ٱلْكَٰذِبِينَ *(yalancılar)* → ٱلصَّٰدِقِينَ *(doğru söyleyenler)*. Kalan yedi kelime birebir aynı, mora 43 → 46 farkı da bu iki değişimden geliyor, harf sayısı ise ikisinde de 35. Bu blokta ölçülen en dar ikiz.",
10:"Şart cümlesinin cevabı yok — لَوْلَا *(olmasaydı)* açılıyor ama sonucu yazılmıyor. Ölçülebilir bir eksiklik: dokuz kelimede tek çekimli fiil yok, dört merfû isim var. Ayet dilbilgisel olarak askıda kalıyor ve okur cevabı kendisi tamamlıyor. Aynı yapı 24:14 ve 24:20'de de dönecek; ikisinde bir cevap var, birinde yok.",
11:"Yeni bölüm bir olayla değil bir sınıflandırmayla açılıyor: عُصْبَة *(güruh)*, korpusta beş geçişli ve komşuluğunda eşik üstü kavram yok. Ayetin ekseni bir değerlendirme tersine çevirmesi: شَرًّا *(kötü)* → بَلْ … خَيْرٌ *(aksine hayır)*, IDRAB ile. Ölçülebilir bir dağıtım da var — sorumluluk önce herkese ayrı ayrı bölünüyor (لِكُلِّ ٱمْرِئٍ *(her kişiye)*), sonra bir kişide toplanıyor. Aynı ayette كبر *(büyüklük)* ve عظم *(azamet)* yan yana: suçun büyüklüğü ve cezanın büyüklüğü ayrı köklerle adlandırılıyor.",
12:"Kınama bir kaçırılmış eylem üzerinden kuruluyor: لَوْلَا *(deseydiniz ya)* + geçmiş zaman, yani olmayan bir şey anlatılıyor. أمن *(güven; iman)* kökü ayette iki kez, ikisi de çoğul ama cinsiyetleri ayrı — ٱلْمُؤْمِنُونَ ve ٱلْمُؤْمِنَٰت. Bu ikili adlandırma sûrenin genel deseninin parçası: 24:2-3'te de hüküm iki cinsiyet için ayrı yazılmıştı. Kaçırılan eylem de ikili: bir zan ve bir söz.",
13:"Dört-tanık ölçütü sûrede üçüncü kez ve bu kez bir sonuç çıkarma aracı olarak: koşul yerine gelmediyse hüküm otomatik. İki gelme fiili ayrı köklerden — جَآءُو *(getirdiler)* ve لَمْ يَأْتُوا۟ *(getirmediler)*; aynı eylem olumlu ve olumsuz iki sözcükle. Hüküm bir konum belirtecine bağlanıyor: عِندَ ٱللَّهِ *(Allah katında)*.",
14:"Üç kez tekrarlanan altı kelimelik açılışın tek tamamlanmış örneği. Ölçülebilir fark: 24:10 ve 24:20 bir esmâ çiftiyle kapanıp cevabı yazmıyor, bu ayet ise لَمَسَّكُمْ *(size dokunurdu)* ile cevabı veriyor ve esmâ taşımıyor. Üçlünün ortası anlam olarak tamamlanmış, iki ucu askıda. Kapanışı 24:11 ile aynı: عَذَابٌ عَظِيمٌ *(büyük azap)*.",
15:"Ayet iki konuşma organını art arda adlandırıyor: أَلْسِنَة *(diller)* ve أَفْوَاه *(ağızlar)* — ikisi de çoğul, ikisi de harf-i cerle araç konumunda. Gereksiz gibi görünen bu ikileme bir ayrım kuruyor: birincisi aktarma (تَلَقَّوْنَهُ *(alıp veriyorsunuz)*, bab V), ikincisi söyleme. Karşıtlık bir ölçü sözcüğüyle kapanıyor: هَيِّنًا *(önemsiz)* / عَظِيم *(büyük)*, aralarındaki fark konumla belirleniyor — عِندَ ٱللَّهِ *(Allah katında)*, 24:13'ün de kullandığı ifade.",
16:"İkinci kaçırılmış söz ve birincisinden farkı ölçülebilir: 24:12'de söylenmesi gereken bir hüküm vardı, burada önce bir çekimserlik (مَّا يَكُونُ لَنَآ أَن نَّتَكَلَّمَ *(bunu konuşmak bize düşmez)*), sonra bir tenzih, sonra hüküm. İkinci kalıp üç adımlı ve hüküm sona bırakılmış. Terim de değişiyor: إِفْك *(iftira)* → بُهْتَٰن *(bühtan)*.",
17:"Yedi ayetlik kınama bölümü bir öğütle toparlanıyor ve öğüdün öznesi ilk kez doğrudan lafız: يَعِظُكُمُ ٱللَّهُ *(Allah size öğüt veriyor)*. وعظ *(öğüt, vaʼz)* korpusta 25 geçişli. Süre belirteci ikinci kez: أَبَدًا *(asla)*, 24:4'te de vardı — iki yasak da süresiz. Kapanış koşulu bir kimliğe bağlıyor.",
18:"Sûrenin en kısa ayeti aynı zamanda lafız yoğunluğunun tepesi: yedi kelimede iki lafız. Ayet 24:1'in kapanışını tamamlıyor — orada âyetler indirilmişti (أَنزَلْنَا … ءَايَٰتٍۭ بَيِّنَٰتٍ *(apaçık âyetler indirdik)*), burada açıklanıyor, ve aynı kök بين *(arası; açıklama)* ikisinde de var: orada sıfat, burada fiil. Bölüm kendi açılış terimiyle kapanıyor.",
19:"Suç burada eylemden isteğe kaydırılıyor: يُحِبُّونَ أَن تَشِيعَ *(yayılmasını isterler)* — ceza yayanlara değil, yayılmasını isteyenlere bağlanıyor. Kapanış aynı kökü iki kez, karşıt öznelerle kullanıyor: وَٱللَّهُ يَعْلَمُ وَأَنتُمْ لَا تَعْلَمُونَ *(Allah bilir, siz bilmezsiniz)* — bilgi asimetrisi tek kökün olumlu ve olumsuz çekimiyle veriliyor. Bu, 24:15'in مَّا لَيْسَ لَكُم بِهِۦ عِلْمٌ *(hakkında bilginiz olmayan)* ifadesinin dördüncü ayet sonra dönüşü.",
20:"Üçlü kalıbın son üyesi ve 24:10 ile arasındaki fark iki kelimeye inmiş. İki ayet aynı uzunlukta (n=9), aynı fiilsizlikte, aynı z değerinde (3,92) ve aynı yıldızda; ikisinde de şartın cevabı yazılmıyor. Kök ikilemesi ölçümü bir ek veriyor: burada رحم *(rahmet, merhamet)* iki kez — biri isim (رَحْمَتُهُ *(merhameti)*), biri esmâ (رَحِيم). 24:10'da bu tekrar yoktu.",
}

ATLAMA={
 "24:10":"★★★ ayet. 🜁 biyolog ve 🜂 uzay YAZILMADI — beş kökün hiçbiri (فضل *(lütuf)* · أله *(lafza-i celâl)* · رحم *(rahmet)* · توب *(tevbe)* · حكم *(hikmet)*) canlıya, organa, sürece ya da gök öğesine bağlanmıyor.",
 "24:18":"★★★ ayet. 🜁 biyolog YAZILMADI — beş kökün hiçbiri biyolojik çıpa vermiyor. 🜂 uzay YAZILMADI — أيي *(âyet, işaret)* korpusta 'gök işareti' işlevi de taşıyor, ama burada gönderge 24:1'de indirildiği söylenen metin âyetleri; gönderge belirliyken astronomik okumayı seçmek yasaklı 'bilimsel izdüşüm' olurdu.",
 "24:20":"★★★ ayet. 🜁 biyolog ve 🜂 uzay YAZILMADI — dört kök (فضل *(lütuf)* · أله *(lafza-i celâl)* · رحم *(rahmet)* · رأف *(şefkat)*) hiçbir çıpa vermiyor.",
 "_blok_notu_24_1_20":"Blok 24:1-20'de üç ★★★ ayet (10, 18, 20) ve ÜÇÜNDE DE iki mercek atlandı. Üçünün de yıldız kaynağı allah z (3,92 · 5,18 · 3,92) ve üçü de n=7-9. Sûre 23'te on altı ★★★'ın on beşinde iki mercek atlanmıştı; desen sûre 24'te de sürüyor, ama kaynak değişti: 23'te baskın kaynak rab z, burada allah z. Adaylar 468, 472. NOT: sûrenin en uzun ayeti 24:31 (n=78) henüz okunmadı — yıldız formülünün UZUN ayet davranışı orada ölçülecek.",
}

p='/home/claude/repo/notlar/okuma_metni.json'
OM=json.load(open(p,encoding='utf-8'))
OM.setdefault('24',{})
OM['24']['_makro']=MAKRO
OM['24']['_mercek_atlama_notu']=ATLAMA
for n in range(1,21):
    ar=AR[(24,n)]
    if n==1: ar=' '.join(ar.split()[4:])   # besmele (4 kelime) çıkarıldı
    OM['24']["24:%d"%n]={"ar":ar,"meal":MEAL[n],"olcum":OLCUM[n],
                         "mercek":MERCEK[n],"dikey":DIK["24:%d"%n]}
OM['ilerleme']['not']=("Sûre 23 TAM (118/118). Sûre 24 (Nûr) makro profil + 24:1-20 okundu. "
                       "Devam: 24:21. Sûre 24 Medenî; Rab lafzı sûrede HİÇ geçmiyor (aday 498).")
OM['ilerleme']['kismi']={"2":"1-20 ayet düzeyinde","24":"1-20 ayet düzeyinde"}
OM['ilerleme']['okunan_ayet']=1601
json.dump(OM,open(p,'w',encoding='utf-8'),ensure_ascii=False,indent=1)
print('okuma_metni: sûre 24 →',len([k for k in OM['24'] if not k.startswith('_')]),'ayet')

pm='/home/claude/repo/notlar/mercek_kayit.json'
MK=json.load(open(pm,encoding='utf-8'))
MK.setdefault('24',{})
for n in range(1,21): MK['24']["24:%d"%n]=MERCEK[n]
MK['24_atlama']=ATLAMA
json.dump(MK,open(pm,'w',encoding='utf-8'),ensure_ascii=False,indent=1)
print('mercek_kayit: sûre 24 →',len(MK['24']),'mercek')
