# -*- coding: utf-8 -*-
"""blok_21_81_100.py — Enbiyâ 81-100 bloğunun okuma kaydını dosyalara yazar."""
import json

DIK = json.load(open('blok_dikey_21_81_100.json', encoding='utf-8'))
veri = json.load(open('kuran_veri.json', encoding='utf-8'))
AR = {}
for s in veri['sureler']:
    for a in s['ayetler']:
        AR[(s['no'], a['no'])] = a['ar']

MEAL = {
81: "Süleymân'a da, buyruğuyla bereketli kıldığımız yere doğru esip giden fırtınalı rüzgârı verdik. Biz her şeyi bilenleriz.",
82: "Şeytanlardan da onun için dalgıçlık yapan ve bundan başka işler görenleri. Onları gözetip duran bizdik.",
83: "Eyyûb'u da — hani Rabbine seslenmişti: \"Bana bu dert dokundu; sen merhametlilerin en merhametlisisin.\"",
84: "Ona icabet ettik de kendisindeki derdi giderdik. Katımızdan bir rahmet ve kulluk edenler için bir hatırlatma olarak, ona ailesini ve onlarla birlikte bir mislini daha verdik.",
85: "İsmâîl'i, İdrîs'i ve Zülkifl'i de — hepsi sabredenlerdendi.",
86: "Onları rahmetimizin içine aldık. Onlar salihlerdendi.",
87: "Zünnûn'u da — hani öfkelenip gitmişti de kendisini sıkıştırmayacağımızı sanmıştı. Sonra karanlıklar içinde seslendi: \"Senden başka ilâh yok, seni tenzih ederim; ben gerçekten zalimlerden oldum.\"",
88: "Ona icabet ettik ve onu gamdan kurtardık. Müminleri işte böyle kurtarırız.",
89: "Zekeriyyâ'yı da — hani Rabbine seslenmişti: \"Rabbim, beni tek başıma bırakma; sen vârislerin en hayırlısısın.\"",
90: "Ona icabet ettik, ona Yahyâ'yı bağışladık ve eşini kendisi için ıslah ettik. Onlar hayırlarda yarışır, umarak ve korkarak bize dua ederlerdi; bize karşı huşû içindeydiler.",
91: "Irzını koruyanı da — ona ruhumuzdan üfledik; onu da oğlunu da âlemler için bir âyet kıldık.",
92: "İşte bu, tek bir ümmet olarak sizin ümmetinizdir; ben de sizin Rabbinizim. Öyleyse bana kulluk edin.",
93: "Ama işlerini aralarında parça parça ettiler. Hepsi bize dönecektir.",
94: "Kim mümin olarak salih işlerden yaparsa, çabası nankörlükle karşılanmaz; biz onu yazanlarız.",
95: "Helâk ettiğimiz bir ülkeye, dönmemeleri haram kılınmıştır.",
96: "Nihayet Ye'cûc ve Me'cûc açıldığında, onlar her tepeden akın ederler.",
97: "Gerçek vaat yaklaşmıştır. İşte o zaman inkâr edenlerin gözleri donup kalır: \"Eyvah bize! Biz bundan gaflet içindeydik; hayır, biz zalimdik.\"",
98: "Siz de, Allah'ı bırakıp taptıklarınız da cehennemin yakıtısınız; siz oraya varacaksınız.",
99: "Bunlar ilâh olsalardı oraya varmazlardı. Hepsi orada kalıcıdır.",
100: "Orada onlara ağır bir soluk vardır; onlar orada işitmezler.",
}

OLCUM = {
81: "eksen: lafız yok, Rab yok · **esmâ عالِم *(bilen)* 14. sırada — ŞÜPHELİ** (عَٰلِمِينَ 1P çoğul haber; 21:51 ile aynı desen, aday 444 doğrulama kümesinde) · aktör: adlı سُلَيْمان *(Süleymân)* 1. sırada — ayetin İLK kelimesi, rol mecrur · edim haber · şahıs 3FS ×2 · 3MS 1 · 1P ×4 · n=14 mora=84 harf=65, fâsıla عَٰلِمِينَ *(bilenler)* → ن, N; i'râb GEN 5 · ACC 3; bab I ×2 · bab III ×1; **dış düğüm 5 — sûrenin en bağlantılı ayetlerinden** · kökler روح *(ruh; rüzgâr)* · عصف *(fırtına, savurma)* · جري *(akma, koşma)* · أمر *(emir; iş)* · أرض *(yer, yeryüzü)* · برك *(bereket, mübarek kılma)* · كون *(olmak)* · كلل *(hep, bütün)* · شيأ *(dileme; şey)* · علم *(bilme)* · bağ: xref كون *(olmak)* + كلل *(hep, bütün)* + شيأ *(dileme; şey)* → 4:32 · 4:33 · 4:86 · 33:54 · 33:55; **21:71 ile aynı nitelik terkîbi** ٱلْأَرْضِ ٱلَّتِى بَٰرَكْنَا فِيهَا *(bereketli kıldığımız yer)* (elle, L1)",
82: "eksen yok · aktör: adlı شَيْطان *(şeytan)* 2. sırada, tür **gayb**, rol mecrur — sûrenin tek gayb aktörü (öteki: 21:96) · edim haber · şahıs 3MP ×5 · 3MS 1 · 1P ×2 · n=12 mora=65 harf=52, fâsıla حَٰفِظِينَ *(gözetenler)* → ن, N; i'râb GEN 1 · ACC 3; bab I ×3; kök ikilemesi عمل *(iş, amel)* ×2 — biri fiil biri mef'ûl-i mutlak (يَعْمَلُونَ عَمَلًۭا *(iş görürler, bir iş)*); simetri [3,1,9,1] · kökler شطن *(şeytan)* · غوص *(dalma (suya))* · عمل *(iş, amel)* · دون *(beriki, başkası)* · كون *(olmak)* · حفظ *(koruma)* · bağ: xref yok",
83: "eksen: lafız yok · Rab 4. sırada, رَبَّهُۥ *(Rabbine)* (rab z=1.81) · esmâ yok · aktör: adlı أَيُّوب *(Eyyûb)* 1. sırada — ayetin İLK kelimesi, rol mecrur · edim haber · şahıs 3MS ×3 · 1S ×2 · 2MS 1 · n=10 mora=56 harf=42, fâsıla ٱلرَّٰحِمِينَ *(merhametliler)* → ن, N; i'râb GEN 2 · ACC 2 · NOM 2; bab I ×1 · bab III ×1; kök ikilemesi رحم *(rahmet, merhamet)* ×2 — biri ism-i tafdîl أَرْحَمُ *(en merhametli)*, öteki ism-i fâil çoğul ٱلرَّٰحِمِينَ; ayet ۞ hizb işaretiyle açılıyor · yıldız ★ · kökler ندي *(seslenme, nidâ)* · ربب *(rab, terbiye etme)* · مسس *(dokunma, temas)* · ضرر *(zarar)* · رحم *(rahmet, merhamet)* · bağ: xref ندي *(seslenme)* + ربب *(Rab)* + مسس *(dokunma)* → 38:41",
84: "eksen yok · aktör yok · edim haber · şahıs **1P ×7** · 3MS ×4 · 3MP ×2 · n=16 mora=84 harf=74, fâsıla لِلْعَٰبِدِينَ *(kulluk edenler için)* → ن, N; i'râb GEN 3 · ACC 4 · NOM 1; bab I ×1 · bab IV ×1 · bab X ×1 — **üç fiil, üçü de ayrı bab**; simetri [3,2,11,1] · kökler جوب *(cevap verme, icabet)* · كشف *(giderme, açma)* · ضرر *(zarar)* · أتي *(gelme, getirme; verme)* · أهل *(ehil, aile)* · مثل *(benzer, misil; heykel)* · رحم *(rahmet, merhamet)* · عند *(yan, katında)* · ذكر *(anma, zikir)* · عبد *(kul, kulluk)* · bağ: xref أهل *(aile)* + مثل *(misil)* + رحم *(rahmet)* → 38:43; 21:76 ile aynı فَٱسْتَجَبْنَا لَهُۥ *(ona icabet ettik)* kalıbı (elle, L1)",
85: "eksen yok · aktör: adlı İKİ kişi — إِسْماعِيل *(İsmâîl)* 1. sırada (rol mef'ûl), إِدْرِيس *(İdrîs)* 2. sırada (rol mecrur); üçüncü kişi ذَا ٱلْكِفْلِ *(Zülkifl)* künye olarak geçiyor ve aktör tablosuna GİRMİYOR · edim haber · şahıs **alan BOŞ — ayette hiç fiil yok** · n=7 mora=43 harf=34, fâsıla ٱلصَّٰبِرِينَ *(sabredenler)* → ن, N; i'râb ACC 2 · GEN 3 · NOM 1; **bab alanı boş, zaman alanı boş — sûrede fiilsiz tek ayet** · kökler كفل *(kefil olma; Zülkifl)* · كلل *(hep, bütün)* · صبر *(sabır)* · bağ: xref yok",
86: "eksen yok · aktör yok · edim haber · şahıs 1P ×3 · 3MP ×2 · n=6 mora=39 harf=30, fâsıla ٱلصَّٰلِحِينَ *(salihler)* → ن, N; i'râb GEN 2 · ACC 1; bab IV ×1 (tek fiil) · **21:75 ile NEREDEYSE ÖZDEŞ — tek fark zamir sayısı: orada tekil (أَدْخَلْنَٰهُ … إِنَّهُۥ), burada çoğul (أَدْخَلْنَٰهُمْ … إِنَّهُم)** · kökler دخل *(girme, sokma)* · رحم *(rahmet, merhamet)* · صلح *(iyi olma, salâh)* · bağ: 21:75 ile bölüt ikizi (elle, L1)",
87: "eksen: lafız yok, Rab yok — ama لَّآ إِلَٰهَ إِلَّآ أَنتَ *(senden başka ilâh yok)* var · aktör: künye ذَا ٱلنُّونِ *(Zünnûn, balık sahibi)* — aktör tablosuna girmiyor · edim haber, kip NEG 2 · RES 1 · şahıs 3MS ×4 · 1P 1 · 2MS ×2 · 1S ×3 · n=23 mora=108 harf=80 — **sûrenin en uzun ayeti (kelime)**, fâsıla ٱلظَّٰلِمِينَ *(zalimler)* → ن, N; i'râb ACC 5 · GEN 3; bab I ×4 · bab III ×1; **hapaks نون *(balık (nûn))* — korpusta tek geçiş (z=3.38)**; kök ikilemesi ظلم ×2 — **biri 'karanlık' (ٱلظُّلُمَٰتِ), öteki 'zulüm' (ٱلظَّٰلِمِينَ), aynı kök iki anlamda**; biçim HASR; simetri [6,7,17,2] · yıldız ★★★ · kökler نون *(balık (nûn))* · ذهب *(gitme; altın)* · غضب *(gazap, öfke)* · ظنن *(zan, sanma)* · قدر *(ölçü, takdir; güç)* · ندي *(seslenme, nidâ)* · ظلم *(zulüm; karanlık)* · أله *(ilâh)* · سبح *(tesbih, tenzih)* · كون *(olmak)* · bağ: xref yok",
88: "eksen: lafız yok · **esmâ مُؤْمِن *(mümin)* 8. sırada — ÖLÇÜM ARTEFAKTI (aday 444)**: ٱلْمُؤْمِنِينَ *(müminler)*, göndergesi İNSANLAR ve fiilin mef'ûlü · aktör yok · edim haber · şahıs 1P ×5 · 3MS ×2 · n=8 mora=46 harf=41, fâsıla ٱلْمُؤْمِنِينَ → ن, N; i'râb GEN 1 · ACC 1; bab II ×1 · bab IV ×1 · bab X ×1 — üç fiil, üçü de ayrı bab; kök ikilemesi نجو *(kurtarma, necat)* ×2 — biri PERF tekil, öteki IMPF genel · kökler جوب *(cevap verme, icabet)* · نجو *(kurtarma, necat)* · غمم *(gam, tasa; bürüme)* · أمن *(güven; iman)* · bağ: 21:76 ve 21:84 ile aynı kalıp (elle, L1)",
89: "eksen: lafız yok · **Rab İKİ geçiş, 4. ve 5. sırada — رَبَّهُۥ رَبِّ *(Rabbine… Rabbim)*, biri mef'ûl biri nidâ (rab z=3.55 — SÛRENİN EN YÜKSEK RAB YOĞUNLUĞU)** · **esmâ وارِث *(vâris)* 11. sırada — GEÇERLİ**: خَيْرُ ٱلْوَٰرِثِينَ *(vârislerin en hayırlısı)*, doğrudan Rabbe hitapta, ism-i tafdîl terkîbi · aktör: adlı زَكَرِيّا *(Zekeriyyâ)* 1. sırada — ayetin İLK kelimesi, rol mecrur · edim haber, kip NEG 1 · şahıs 3MS ×2 · 1S ×2 · 3FS 1 · 2MS 1 · n=11 mora=57 harf=44, fâsıla ٱلْوَٰرِثِينَ *(vârisler)* → ن, N; i'râb GEN 2 · ACC 2 · NOM 2; bab I ×1 · bab III ×1; kök ikilemesi ربب ×2 · yıldız ★★★ · kökler ندي *(seslenme, nidâ)* · ربب *(rab, terbiye etme)* · وذر *(bırakma, terk)* · فرد *(tek, yalnız)* · خير *(hayır, daha iyi)* · ورث *(miras, vâris olma)* · bağ: 21:83 ile aynı açılış kalıbı (elle, L1)",
90: "eksen yok · aktör: adlı يَحْيَى *(Yahyâ)* 5. sırada, rol fâil · edim haber · şahıs **1P ×8 · 3MP ×9 · 3MS ×4 — bloğun en yoğun şahıs ayeti** · n=19 mora=113 harf=99 — **bloğun en uzun ayeti (mora ve harf)**, fâsıla خَٰشِعِينَ *(huşû duyanlar)* → ن, N; i'râb NOM 1 · ACC 5 · GEN 1; bab I ×4 · bab III ×1 · bab IV ×1 · bab X ×1 — **dört ayrı bab**; kök ikilemesi كون ×2; sayı sözcüğü زَوْج *(eş, çift)* · kökler جوب *(cevap verme, icabet)* · وهب *(bağışlama, hibe)* · حيي *(diri olma, hayat; Yahyâ)* · صلح *(iyi olma, salâh)* · زوج *(eş, çift)* · كون *(olmak)* · سرع *(hız, sürat)* · خير *(hayır, daha iyi)* · دعو *(çağırma, dua)* · رغب *(rağbet, istekle yönelme)* · رهب *(korku, çekinme)* · خشع *(huşû, boyun eğme)* · bağ: 21:84 ve 21:88 ile aynı kalıp (elle, L1)",
91: "eksen yok · aktör yok — **kişi adsız, yalnız bir sıfat cümlesiyle anılıyor: ٱلَّتِىٓ أَحْصَنَتْ فَرْجَهَا *(ırzını koruyan kadın)*, 3FS** · edim haber · şahıs 3FS ×5 · 1P ×5 — **tam denge** · n=11 mora=79 harf=57, fâsıla لِّلْعَٰلَمِينَ *(âlemler için)* → ن, N — 21:71'in fâsılasıyla aynı; i'râb ACC 3 · GEN 2; bab I ×2 · bab IV ×1 · kökler حصن *(koruma, sağlamlaştırma; iffet)* · فرج *(ırz; yarık, aralık)* · نفخ *(üfleme)* · روح *(ruh; rüzgâr)* · جعل *(kılma, var etme)* · بني *(oğul, evlat; bina)* · أيي *(âyet, işaret)* · علم *(bilme; âlem)* · bağ: xref حصن *(koruma)* + فرج *(ırz)* + نفخ *(üfleme)* → 66:12 · نفخ + روح *(ruh)* + جعل *(kılma)* → 32:9",
92: "eksen: lafız yok · Rab 7. sırada, رَبُّكُمْ *(Rabbiniz)* (rab z=2.34) · aktör yok · edim emir, kip IMPV 1 · şahıs 2MP ×4 · 1S ×2 · n=8 mora=45 harf=36, fâsıla فَٱعْبُدُونِ *(bana kulluk edin)* → ن, N — **21:25'in fâsılasıyla aynı kelime**; i'râb ACC 3 · NOM 2; bab I ×1 (tek fiil); kök ikilemesi أمم *(önder, imam; ümmet)* ×2; sayı sözcüğü وَٰحِدَة *(bir, tek)*; biçim DIKKAT · yıldız ★★ · kökler أمم *(önder, imam; ümmet)* · وحد *(bir olma, teklik)* · ربب *(rab, terbiye etme)* · عبد *(kul, kulluk)* · bağ: xref أمّة + واحدة + ربّ → **23:52** (bkz. aday 456)",
93: "eksen yok · aktör yok · edim haber · şahıs 3MP ×4 · 1P 1 · n=6 mora=39 harf=31, fâsıla رَٰجِعُونَ *(dönenler)* → ن, N; i'râb ACC 2 · NOM 2; bab V ×1 — **sûrede bab V taşıyan tek ayet**; zaman PERF 1 · kökler قطع *(kesme, parçalama)* · أمر *(emir; iş)* · بين *(arası; açıklama)* · كلل *(hep, bütün)* · رجع *(dönme, geri döndürme)* · bağ: xref تقطّع *(parçalanma)* + أمر *(iş)* + بين *(ara)* → **23:53** (bkz. aday 456)",
94: "eksen: lafız yok · **esmâ مُؤْمِن *(mümin)* 6. sırada, orta konum — ÖLÇÜM ARTEFAKTI (aday 444)**: وَهُوَ مُؤْمِنٌۭ *(o mümin olarak)*, göndergesi salih iş yapan İNSAN · aktör yok · edim haber, kip NEG 1 · şahıs 3MS ×4 · 1P 1 · n=12 mora=57 harf=49, fâsıla كَٰتِبُونَ *(yazanlar)* → ن, N; i'râb GEN 2 · NOM 2 · ACC 2; bab I ×1 (tek fiil); simetri [3,1,5,1] · kökler عمل *(iş, amel)* · صلح *(iyi olma, salâh)* · أمن *(güven; iman)* · كفر *(inkâr, nankörlük)* · سعي *(çaba, koşuşturma)* · كتب *(yazma, kitap)* · bağ: xref عمل *(amel)* + صلح *(salâh)* + أمن *(iman)* → 20:112",
95: "eksen yok · aktör yok · edim haber, kip NEG 1 · şahıs 1P ×2 · 3FS 1 · 3MP ×3 · n=7 mora=43 harf=30, fâsıla يَرْجِعُونَ *(dönerler)* → ن, N — 21:93'ün fâsılasıyla aynı kök, iki ayet arayla; i'râb NOM 1 · GEN 1 · ACC 1; bab I ×1 · bab IV ×1 · kökler حرم *(haram kılma, yasak)* · قري *(köy, kasaba)* · هلك *(helâk, yok olma)* · رجع *(dönme, geri döndürme)* · bağ: 21:74 ile ortak قري (elle, L2)",
96: "eksen yok · aktör: adlı İKİ **gayb** aktörü — يَأْجُوج *(Ye'cûc)* 4. ve مَأْجُوج *(Me'cûc)* 5. sırada, ikisi de rol fâil · edim haber · şahıs 3FS 1 · 3MP ×3 · n=10 mora=50 harf=38, fâsıla يَنسِلُونَ *(akın ederler)* → ن, N; i'râb NOM 2 · GEN 2; bab I ×2; **hapaks حدب *(tepe, yüksek yer)* — korpusta tek geçiş (z=3.38)**; edilgen 1 (فُتِحَتْ *(açıldı)*, z=2.52); simetri [3,1,4,1] · yıldız ★★★ · kökler فتح *(açma, fetih)* · كلل *(hep, bütün)* · حدب *(tepe, yüksek yer)* · نسل *(hızla akın etme; nesil)* · bağ: xref yok",
97: "eksen yok · aktör yok · edim nida, kip VOC 1 · CERT 1 · şahıs 3MS 1 · 3FS 1 · 3MP ×2 · 1P ×5 · n=19 mora=92 harf=73, fâsıla ظَٰلِمِينَ *(zalimler)* → ن, N; i'râb NOM 5 · GEN 1 · ACC 1; bab I ×3 · bab VIII ×1; kök ikilemesi كون ×2; biçim IDRAB (بَلْ *(hayır, bilakis)*) + DIKKAT; simetri [4,8,13,1]; zaman PERF ×4 — IMPF yok · kökler قرب *(yakınlık)* · وعد *(vaat)* · حقق *(hak, gerçek)* · شخص *(dikilip kalma (bakış))* · بصر *(görme, basiret)* · كفر *(inkâr, nankörlük)* · كون *(olmak)* · غفل *(gaflet, habersizlik)* · ظلم *(zulüm)* · bağ: **21:14 ve 21:46 ile üçüncü kez يَٰوَيْلَنَا … كُنَّا ظَٰلِمِينَ *(eyvah bize… zalimmişiz)*** (elle, L1)",
98: "eksen: **Allah lafzı ayet-içi 6. sırada**, üçüncü kez مِن دُونِ ٱللَّهِ *(Allah'ı bırakıp)* kalıbında (allah z=1.29) — **sûrenin SON lafzı** · Rab yok · esmâ yok · aktör: adlı جَهَنَّم *(cehennem)* 8. sırada, tür 'yer', rol mecrur · edim haber · şahıs 2MP ×4 · 3FS 1 · n=11 mora=52 harf=41, fâsıla وَٰرِدُونَ *(varacak olanlar)* → ن, N; i'râb ACC 1 · GEN 3 · NOM 2; bab I ×1 (tek fiil); simetri [3,1,8,1] · kökler عبد *(kul, kulluk)* · دون *(beriki, başkası)* · أله *(ilâh; lafza-i celâl)* · حصب *(çakıl; ateş yakıtı)* · ورد *(varma, suya gelme)* · bağ: 21:66 ve 21:67 ile aynı kalıp, ters muhatap (elle, L1)",
99: "eksen yok · aktör yok · edim şart, kip COND 1 · NEG 1 · şahıs 3MS 1 · 3MP ×2 · 3FS ×2 · n=9 mora=56 harf=38, fâsıla خَٰلِدُونَ *(kalıcılar)* → ن, N — 21:34'ün fâsılasıyla aynı kök; i'râb ACC 1 · NOM 2; bab I ×2; biçim DIKKAT; kök ورد *(varma, suya gelme)* 21:98'den devralınıyor · kökler كون *(olmak)* · أله *(ilâh)* · ورد *(varma, suya gelme)* · كلل *(hep, bütün)* · خلد *(ebedî kalma)* · bağ: **21:22 ile aynı şart kalıbı** لَوْ كَانَ … ءَالِهَةٌ *(ilâhlar olsaydı)* (elle, L1)",
100: "eksen yok · aktör yok · edim haber, kip NEG 1 · şahıs 3MP ×4 · 3FS ×2 · n=7 mora=36 harf=27 — **bloğun en kısa ayeti**, fâsıla يَسْمَعُونَ *(işitirler)* → ن, N; i'râb NOM 1; bab I ×1 (tek fiil); simetri [3,1,4,1] · kökler زفر *(derin soluk, inleme)* · سمع *(işitme)* · bağ: 21:45 ile ortak سمع, ters yön (elle, L2)",
}

MERCEK = {
81: "Rüzgâr bir kişiye tahsis ediliyor (لِسُلَيْمَٰنَ *(Süleymân'a)*, lâm-ı temlîk) ve iki nitelikle veriliyor: عَاصِفَةًۭ *(fırtınalı)* hâl, تَجْرِى بِأَمْرِهِۦٓ *(buyruğuyla akan)* sıfat cümlesi. Varış noktası bir önceki bloğun 21:71'inde geçen terkiple aynı: ٱلْأَرْضِ ٱلَّتِى بَٰرَكْنَا فِيهَا *(bereketli kıldığımız yer)* — orada kurtarılanların gittiği yer, burada rüzgârın gittiği yer. Aynı hedef, iki ayrı hareket.",
82: "Şeytanlar bir işlev listesiyle tanımlanıyor: يَغُوصُونَ *(dalarlar)* ve يَعْمَلُونَ عَمَلًۭا دُونَ ذَٰلِكَ *(bundan başka işler görürler)*. İkinci fiil kendi masdarını mef'ûl alıyor (mef'ûl-i mutlak) ve ardından دُونَ ذَٰلِكَ *(bundan başkası)* ile sınır çiziliyor — yani iş sayılmıyor, kapsamı veriliyor. Kapanış gözetimi anlatıcıya devrediyor: وَكُنَّا لَهُمْ حَٰفِظِينَ *(onları gözetenler bizdik)*, حفظ *(koruma)*.",
83: "Nidâ ile başlayan üç kıssanın (83, 87, 89) ilki. Şikâyet en kısa hâlde veriliyor: مَسَّنِىَ ٱلضُّرُّ *(bana dert dokundu)* — fiil مسس *(dokunma, temas)*, aynı kök 21:46'da azabın 'bir esintisi' için kullanılmıştı. Karşılık ise bir sıfat cümlesiyle: أَرْحَمُ ٱلرَّٰحِمِينَ *(merhametlilerin en merhametlisi)* — aynı kök iki kez, biri ism-i tafdîl biri çoğul ism-i fâil, yani bir kümenin içinden en üst öğe seçiliyor.",
84: "Üç fiil, üç ayrı bab: ٱسْتَجَبْنَا *(icabet ettik)* bab X, كَشَفْنَا *(giderdik)* bab I, ءَاتَيْنَٰهُ *(verdik)* bab IV. Verilen şey iki katına çıkarılıyor: أَهْلَهُۥ وَمِثْلَهُم مَّعَهُمْ *(ailesi ve onlarla birlikte bir misli)* — مثل *(benzer, misil; heykel)* burada sayı işlevinde. Kapanış iki ACC ile amaç veriyor: رَحْمَةًۭ … وَذِكْرَىٰ *(bir rahmet… ve bir hatırlatma)*, biri alana biri başkalarına.",
85: "Sûrenin **fiilsiz tek ayeti**: bab alanı boş, zaman alanı boş, şahıs alanı boş. Üç ad art arda sıralanıyor ve tek bir haberle toplanıyor: كُلٌّۭ مِّنَ ٱلصَّٰبِرِينَ *(hepsi sabredenlerden)*. Üçüncü ad bir künye (ذَا ٱلْكِفْلِ *(Zülkifl)*) ve aktör tablosuna girmiyor — yani ölçüm katmanı özel ad ile künyeyi ayırıyor. Aynı ayrım 21:87'de de görünecek.",
86: "21:75 ile neredeyse özdeş; tek fark zamir sayısı: orada tekil (أَدْخَلْنَٰهُ … إِنَّهُۥ *(onu… o)*), burada çoğul (أَدْخَلْنَٰهُمْ … إِنَّهُم *(onları… onlar)*). Aynı cümle, iki kez, on bir ayet arayla, bir kez Lût için bir kez üç kişi için. Kalıp değişmiyor; değişen yalnız kaç kişiye uygulandığı.",
87: "Sûrenin en uzun ayeti ve aynı kökün iki anlamını yan yana taşıyor: ٱلظُّلُمَٰتِ *(karanlıklar)* ve ٱلظَّٰلِمِينَ *(zalimler)* — ظلم kökü bir kez mekân, bir kez ahlâk bildiriyor. Anlatı üç adımda kuruluyor: gitme (ذَهَبَ مُغَٰضِبًۭا *(öfkeli gitti)*), yanlış tahmin (فَظَنَّ أَن لَّن نَّقْدِرَ عَلَيْهِ *(kendisini sıkıştırmayacağımızı sandı)*), seslenme (فَنَادَىٰ *(seslendi)*). Seslenmenin içeriği HASR kalıbı: لَّآ إِلَٰهَ إِلَّآ أَنتَ *(senden başka ilâh yok)* — sûrede aynı kalıp 21:25'te vahyin içeriğiydi, burada bir kulun sözü.",
88: "Kalıp üçüncü kez: فَٱسْتَجَبْنَا لَهُۥ *(ona icabet ettik)* — 21:76 (Nûh), 21:84 (Eyyûb), burada. Aynı kök نجو *(kurtarma, necat)* iki kez ve zamanı değişiyor: نَجَّيْنَٰهُ *(onu kurtardık)* PERF ve tekil, نُۨجِى ٱلْمُؤْمِنِينَ *(müminleri kurtarırız)* IMPF ve çoğul. Yani tekil bir olay bir kurala genişletiliyor; كَذَٰلِكَ *(işte böyle)* iki cümleyi bağlayan tek kelime.",
89: "Sûrenin en yüksek Rab yoğunluğu, ve iki geçiş iki ayrı işlevde: رَبَّهُۥ *(Rabbine)* anlatıcının sözünde ve mef'ûl, رَبِّ *(Rabbim)* kulun sözünde ve nidâ. Bir kelime, iki ses. İstek olumsuz kuruluyor: لَا تَذَرْنِى فَرْدًۭا *(beni tek başıma bırakma)* — istenen şey adlandırılmıyor, yalnız istenmeyen hâl (فرد *(tek, yalnız)*, korpusta 5 geçiş) adlandırılıyor. Kapanış yine ism-i tafdîl: خَيْرُ ٱلْوَٰرِثِينَ *(vârislerin en hayırlısı)* — 21:83'ün أَرْحَمُ ٱلرَّٰحِمِينَ kalıbıyla aynı yapı.",
90: "Cevap üç fiille geliyor ve üçü de üç ayrı yöne bakıyor: ٱسْتَجَبْنَا *(icabet ettik)* isteğe, وَهَبْنَا *(bağışladık)* çocuğa, وَأَصْلَحْنَا لَهُۥ زَوْجَهُۥ *(eşini ıslah ettik)* eşe. Sonra gerekçe geriye dönük veriliyor ve çoğula geçiyor (3MP ×9). Dua iki zıt duyguyla nitelendiriliyor: رَغَبًۭا وَرَهَبًۭا *(umarak ve korkarak)* — ikisi de ACC, ikisi de hâl, ve ses olarak yakın (رغب / رهب).",
91: "Kişi adlandırılmıyor; yalnız bir fiille anılıyor: ٱلَّتِىٓ أَحْصَنَتْ فَرْجَهَا *(ırzını koruyan)*. Bu, bloğun öteki kıssalarından ayrılan tek yer — hepsinde ad var, burada yok. Şahıs dağılımı tam dengeli: 3FS ×5, 1P ×5. Sonuç ikili ama tek bir ACC ile toplanıyor: وَجَعَلْنَٰهَا وَٱبْنَهَآ ءَايَةًۭ *(onu ve oğlunu bir âyet kıldık)* — âyet tekil, gönderge iki kişi.",
92: "Kıssa dizisi burada kesiliyor ve muhataba dönülüyor. Cümle bir eşitleme: هَٰذِهِۦٓ أُمَّتُكُمْ أُمَّةًۭ وَٰحِدَةًۭ *(bu, tek bir ümmet olarak sizin ümmetiniz)* — aynı kelime iki kez, biri iyelikli haber biri hâl. Sonra konuşan kendini adlandırıyor: وَأَنَا۠ رَبُّكُمْ *(ben sizin Rabbinizim)*, 1S. Fâsıla فَٱعْبُدُونِ *(bana kulluk edin)* sûrede 21:25'te de vardı — orada bütün elçilere vahyedilen söz, burada doğrudan hitap.",
93: "Önceki ayetin 'tek ümmet'i burada parçalanıyor: تَقَطَّعُوٓا۟ أَمْرَهُم بَيْنَهُمْ *(işlerini aralarında parça parça ettiler)*, bab V (dönüşlü-karşılıklı) — sûrede bab V taşıyan tek ayet. Sonra parçalanma tek bir hükümle kapatılıyor: كُلٌّ إِلَيْنَا رَٰجِعُونَ *(hepsi bize dönecek)* — كُلّ *(hep, bütün)* parçalananı yeniden toplayan kelime.",
94: "Şart cümlesi bir koşul ekliyor: وَهُوَ مُؤْمِنٌۭ *(o mümin olarak)*, hâl cümlesi. Karşılık olumsuzla veriliyor: فَلَا كُفْرَانَ لِسَعْيِهِۦ *(çabası nankörlükle karşılanmaz)* — كفر *(inkâr, nankörlük)* burada 'inkâr' değil 'emeği görmezden gelme' anlamında ve masdar biçiminde. Kapanış kayda bağlanıyor: وَإِنَّا لَهُۥ كَٰتِبُونَ *(biz onu yazanlarız)*, كتب *(yazma, kitap)*.",
95: "Yedi kelimede bir yasak kuruluyor ve yasağın konusu bir dönüş: أَنَّهُمْ لَا يَرْجِعُونَ *(dönmemeleri)*. Aynı kök رجع *(dönme, geri döndürme)* iki ayet önce (21:93) bütün insanlığın dönüşü içindi; burada olumsuzlanmış ve tek bir ülkeye bağlanmış. حرم *(haram kılma, yasak)* burada NOM ve haber konumunda.",
96: "Zaman edatı ile açılıyor (حَتَّىٰٓ إِذَا *(nihayet… -diği zaman)*) ve fiil edilgen: فُتِحَتْ *(açıldı)* — ne açıldığı, kimin açtığı söylenmiyor, yalnız açılma anı veriliyor. İki ad fâil konumunda ve ikisi de gayb türünde. Hareket iki kelimeyle tarif ediliyor: مِّن كُلِّ حَدَبٍۢ *(her tepeden)* — حدب *(tepe, yüksek yer)* korpusta tek geçişli — ve يَنسِلُونَ *(akın ederler)*.",
97: "Ayette IMPF hiç yok; dört fiilin dördü de PERF. Yaklaşma bile geçmiş zamanda veriliyor: ٱقْتَرَبَ ٱلْوَعْدُ ٱلْحَقُّ *(gerçek vaat yaklaştı)* — 21:1'in açılışıyla aynı kök قرب *(yakınlık)*. Bakışın hâli tek kelimeyle: شَٰخِصَةٌ *(donup kalmış)*, شخص korpusta seyrek. Kapanış sûrede ÜÇÜNCÜ kez aynı itirafı getiriyor: يَٰوَيْلَنَا … كُنَّا ظَٰلِمِينَ — 21:14'te helâk anında, 21:46'da şartlı, burada kıyamet sahnesinde.",
98: "Kalıp üçüncü ve son kez: مِن دُونِ ٱللَّهِ *(Allah'ı bırakıp)*. Ama muhatap tersine dönmüş: 21:66-67'de İbrâhim kavmine söylüyordu, burada söz doğrudan muhataba yöneliyor (2MP ×4). Ve tapan ile tapılan aynı yükleme bağlanıyor: إِنَّكُمْ وَمَا تَعْبُدُونَ … حَصَبُ جَهَنَّمَ *(siz ve taptıklarınız… cehennemin yakıtı)* — ikisi de aynı ACC haber. Ayrım kalkıyor.",
99: "Şart kalıbı sûrenin 22. ayetiyle aynı: لَوْ كَانَ … ءَالِهَةٌۭ *(ilâhlar olsaydı)*. Orada varsayım gökler ve yer hakkındaydı ve sonucu bozulma; burada varsayım putlar hakkında ve sonucu ateşe girmemek. Aynı mantık iki ölçekte: bir kez kozmik, bir kez nesnel. Kapanış ayrımı yine kaldırıyor: وَكُلٌّۭ فِيهَا خَٰلِدُونَ *(hepsi orada kalıcıdır)*.",
100: "Yedi kelime, tek fiil, tek NOM: زَفِيرٌۭ *(ağır soluk)*, زفر korpusta seyrek. Cümle bir sesi var edip aynı anda işitmeyi kaldırıyor: لَهُمْ فِيهَا زَفِيرٌۭ وَهُمْ فِيهَا لَا يَسْمَعُونَ *(orada onlara bir soluk vardır; orada işitmezler)*. فِيهَا *(orada)* iki kez, aynı yerde iki karşıt durum. سمع *(işitme)* kökü sûrede 21:45'te de olumsuzdu, orada sağırlar için, burada bir yer için.",
}

BIYOLOG = {
87: "Çıpa: نون *(balık (nûn))* — korpusta TEK geçiş ve yalnız bu künyede (ذَا ٱلنُّونِ *(balık sahibi)*). Ölçülebilir olan şudur: korpusun 'balık' için olağan kelimesi نون değil حوت *(balık)* — 5 geçiş: 7:163 · 18:61 · 18:63 · 37:142 · 68:48. Ve 68:48 AYNI kişiyi anıyor, bu kez olağan kökle: صَاحِبِ ٱلْحُوتِ *(balık sahibi)*. Yani aynı gönderge iki ayrı künyeyle ve iki ayrı kökle adlandırılıyor; biri korpusta beş kez kullanılan sıradan bir hayvan adı, öteki tek kullanımlık. Ayette hayvanın kendisi hakkında hiçbir şey yok: ne türü, ne davranışı, ne yutma olayı anlatılıyor — 37:142'de anlatılan yutma burada geçmiyor. **Ölçüm sınırı:** bu mercek yalnız sözcük dağılımını ölçüyor; ayetin hayvana dair bir bilgi vermediği de bir ölçümdür.",
96: "Çıpa: يَنسِلُونَ *(akın ederler)*, kök نسل. Korpusta 4 geçiş ve TAM İKİYE bölünüyor: 2:205 (نَّسْلَ *(nesil, döl)*) ve 32:8 (نَسْلَهُۥ مِن سُلَٰلَةٍۢ مِّن مَّآءٍۢ مَّهِينٍۢ *(onun neslini basit bir sudan)*) — üreme/soy anlamında; 21:96 ve 36:51 (يَنسِلُونَ) — hızlı toplu hareket anlamında. Aynı kök hem 'çoğalarak devam etme' hem 'akın ederek yayılma' bildiriyor, ve ikisi de bir yayılma hareketidir: biri zamanda biri mekânda. Ayette hareket eden özneler hakkında hiçbir biyolojik bilgi yok — sayı, tür, nitelik verilmiyor; verilen tek şey çıkış noktası (كُلِّ حَدَبٍۢ *(her tepe)*) ve hareket biçimi. **Ölçüm sınırı:** kökün iki anlamının ilişkili olduğu bir ÖLÇÜM DEĞİL, sözlük gözlemidir; kök-anlam ayrımı tablosuna aday olarak yazıldı.",
}
UZAY = {87: None, 89: None, 96: None}

om = json.load(open('okuma_metni.json', encoding='utf-8'))
mk = json.load(open('mercek_kayit.json', encoding='utf-8'))

for n in range(81, 101):
    key = "21:%d" % n
    om['21'][key] = {'ar': AR[(21, n)], 'meal': MEAL[n], 'olcum': OLCUM[n],
                     'mercek': MERCEK[n], 'dikey': DIK[key]}
    if BIYOLOG.get(n): om['21'][key]['biyolog'] = BIYOLOG[n]
    mk['21'].append([key, MERCEK[n]])
for n, t in BIYOLOG.items():
    if t: mk['21_biyolog'].append(["21:%d" % n, t])

om['21']['_mercek_atlama_notu'] += (
 " 21:87 biyolog YAZILDI (نون *(balık (nûn))* / حوت *(balık)* sözcük dağılımı); uzay ATLANDI "
 "(ٱلظُّلُمَٰت *(karanlıklar)* mekân bildiriyor ama gök öğesi değil). "
 "21:89 biyolog ve uzay ATLANDI (فرد *(tek, yalnız)* ve ورث *(miras, vâris olma)*; canlılık ya da gök çıpası yok). "
 "21:96 biyolog YAZILDI (نسل *(hızla akın etme; nesil)* kök ayrımı); uzay ATLANDI "
 "(حدب *(tepe, yüksek yer)* yer bilimine ait).")

om['ilerleme']['kismi']['21'] = "1-100 ayet düzeyinde"
om['ilerleme']['bekleyen']['21'] = "101-112"
om['ilerleme']['not'] = ("Sûre 20 TAM (135/135). Sûre 21 (Enbiyâ) makro + 21:1-100. Devam: 21:101. "
                         "Dikey katman A parçası birincil, B etiketsiz.")
om['ilerleme']['okunan_ayet'] = 1373

json.dump(om, open('okuma_metni.json', 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
json.dump(mk, open('mercek_kayit.json', 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
print("yazıldı · mercek 21:", len(mk['21']), "· biyolog:", len(mk['21_biyolog']))
