# -*- coding: utf-8 -*-
"""blok_23_61_80.py — sûre 23 dördüncü blok kaydı."""
import json
DIK=json.load(open('blok_dikey_23_61_80.json',encoding='utf-8'))
veri=json.load(open('kuran_veri.json',encoding='utf-8'))
AR={}
for s in veri['sureler']:
    for a in s['ayetler']: AR[(s['no'],a['no'])]=a['ar']

MEAL={
61:"İşte onlar hayırlarda koşarlar; onlara koşanların önündedirler.",
62:"Hiçbir nefse gücünün üstünde yük yüklemeyiz. Yanımızda hakkı söyleyen bir kitap var; onlara haksızlık edilmez.",
63:"Hayır, kalpleri bundan yana gaflet içinde. Onların bundan başka işleri de var; onları işleyip duruyorlar.",
64:"Nihayet refaha boğulmuşlarını azapla yakaladığımızda, işte o zaman feryat ederler.",
65:"Bugün feryat etmeyin; bizden yardım görmeyeceksiniz.",
66:"Âyetlerim size okunuyordu da siz ökçeleriniz üzerinde geri dönüyordunuz —",
67:"— ona karşı büyüklenerek, gece sohbetlerinde saçmalayarak.",
68:"Sözü düşünmediler mi? Yoksa onlara, önceki atalarına gelmeyen bir şey mi geldi?",
69:"Yoksa elçilerini tanımadılar da onu mu inkâr ediyorlar?",
70:"Yoksa \"onda delilik var\" mı diyorlar? Hayır, onlara hakkı getirdi; ama çoğu haktan hoşlanmıyor.",
71:"Hak onların heveslerine uysaydı, gökler, yer ve içindekiler bozulup giderdi. Hayır, onlara kendi zikirlerini getirdik; ama onlar zikirlerinden yüz çeviriyorlar.",
72:"Yoksa onlardan bir ücret mi istiyorsun? Rabbinin ücreti daha hayırlıdır; O, rızık verenlerin en hayırlısıdır.",
73:"Sen onları elbette dosdoğru bir yola çağırıyorsun.",
74:"Âhirete inanmayanlar ise yoldan sapmaktadırlar.",
75:"Onlara merhamet etsek ve başlarındaki sıkıntıyı gidersek, azgınlıkları içinde direnip bocalamayı sürdürürlerdi.",
76:"Andolsun, onları azapla yakaladık; ama Rablerine boyun eğmediler, yalvarmadılar da.",
77:"Nihayet üzerlerine şiddetli azap taşıyan bir kapı açtığımızda, işte o zaman umutlarını yitirirler.",
78:"O'dur sizin için işitmeyi, gözleri ve gönülleri inşa eden. Ne az şükrediyorsunuz!",
79:"O'dur sizi yeryüzünde yaratıp yayan; O'na toplanacaksınız.",
80:"O'dur dirilten ve öldüren; gece ile gündüzün değişmesi O'nundur. Akletmez misiniz?",
}

OLCUM={
61:"eksen yok · aktör yok · edim haber · şahıs 3MP ×3 · 3FS 1 · n=7 mora=40 harf=31, fâsıla سَٰبِقُونَ *(öne geçenler)* → ن, N sınıfı; i'râb GEN 1 · NOM 1; bab III ×1; zaman IMPF 1 · yıldız ★ yok · kökler سرع *(hız, sürat)* · خير *(hayır, daha iyi)* · سبق *(geçme, öne geçme)* · bağ: **İKİNCİ SIFAT ZİNCİRİNİN KAPANIŞI (aday 477)** — kalıp ٱلَّذِينَ هُم *(onlar ki)* burada أُو۟لَٰٓئِكَ *(işte onlar)* ile kapanıyor, tıpkı birinci zincirin kapanışı 23:10 gibi; **23:56 ile aynı kök çifti ters kutupta** (aday 481) (elle, L1)",
62:"eksen yok · aktör yok · edim haber, kip NEG ×2 · RES 1 · şahıs 3MP ×3 · 1P ×2 · 3MS 1 · 3FS 1 · n=12 mora=65 harf=51, fâsıla يُظْلَمُونَ *(haksızlığa uğrarlar)* → ن, N sınıfı; i'râb ACC 2 · NOM 1 · GEN 1; bab I ×2 · bab II ×1; zaman IMPF ×3; edilgen 1 (pas z=1,57); biçim HASR; dış düğüm 1 · yıldız ★ · kökler كلف *(yükümlülük, külfet)* · نفس *(nefis, can)* · وسع *(genişlik, kuşatma)* · كتب *(yazma, kitap)* · نطق *(konuşma, söz söyleme)* · حقق *(hak, gerçek)* · ظلم *(zulüm)* · bağ: xref كتاب *(kitap)* + ينطق *(konuşur)* + حقّ *(hak)* → **45:29**",
63:"eksen yok · aktör yok · edim haber · şahıs 3MP ×3 · 3FS 1 · n=14 mora=60 harf=47, fâsıla عَٰمِلُونَ *(işleyenler)* → ن, N sınıfı; i'râb NOM 3 · GEN 2; **fiil yok**; kök ikilemesi عمل *(iş, amel)* ×2; biçim IDRAB · DIKKAT; simetri [6,1,7,2] · yıldız ★ yok · kökler قلب *(çevirme; kalp)* · غمر *(gaflet dalgası; batıp örtülme)* · عمل · دون *(beriki, başkası)* · bağ: **23:54 ile ortak غمر** — orada emirdeki mecrur, burada haberin öznesi; **23:60 ile ortak قلب** — orada kalpler ürperiyor, burada gaflette (elle, L1)",
64:"eksen yok · aktör yok · edim haber · şahıs 3MP ×4 · 1P ×2 · n=8 mora=49 harf=36, fâsıla يَجْـَٔرُونَ *(feryat ederler)* → ن, N sınıfı; i'râb NOM 1 · GEN 1; bab I ×2; zaman PERF 1 · IMPF 1; simetri [3,1,6,1] · yıldız ★ yok · kökler أخذ *(alma, edinme)* · ترف *(refah içinde şımartma)* · عذب *(azap)* · جأر *(feryat etme, yalvarıp bağırma)* · bağ: **23:33 ile ortak ترف** — orada أَتْرَفْنَٰهُمْ *(onları refaha boğduk)* fiil, burada مُتْرَفِيهِم *(refaha boğulmuşları)* ism-i mef'ûl ve azabın nesnesi; **23:77 ile aynı حَتَّىٰٓ إِذَا … إِذَا هُمْ kalıbı** (elle, L1)",
65:"eksen yok · aktör yok · edim yasak, kip PRO 1 · NEG 1 · şahıs 2MP ×5 · 1P 1 · n=7 mora=36 harf=30, fâsıla تُنصَرُونَ *(yardım edilirsiniz)* → ن, N sınıfı; i'râb ACC 2; bab I ×2; zaman IMPF ×2; **edilgen 1 — pas z=2,52**; **biçim NEHY — sûrenin üç NEHY'inden biri** · yıldız ★★ · kökler جأر *(feryat etme, yalvarıp bağırma)* · يوم *(gün)* · نصر *(yardım)* · bağ: **23:64 ile bitişik ortak جأر** — orada haber ve üçüncü şahıs, burada yasak ve muhatap; **23:26 · 23:39 ile نصر karşıtlığı** (elle, L1, aday 482)",
66:"eksen yok · aktör yok · edim haber, kip CERT 1 · şahıs 2MP ×6 · 3FS ×2 · 1S 1 · n=9 mora=51 harf=40, fâsıla تَنكِصُونَ *(geri dönersiniz)* → ن, N sınıfı; i'râb NOM 1 · GEN 1; bab I ×4; zaman PERF ×2 · IMPF ×2; edilgen 1; kök ikilemesi كون *(olmak)* ×2; simetri [3,1,5,1]; dış düğüm 1 · iç düğüm 1 · yıldız ★ yok · kökler كون · أيي *(âyet, işaret)* · تلو *(okuma, ardından gelme)* · عقب *(sonuç, âkıbet; ökçe)* · نكص *(geri dönme, ökçe üstü çekilme)* · bağ: xref كان *(idi)* + آية *(âyet)* + تلى *(okundu)* → **23:105 · 45:31**; **23:58 ile ters kutup** — orada Rablerinin âyetlerine inanırlar, burada âyetler okunurken geri dönerler (elle, L1)",
67:"eksen yok · aktör yok · edim haber · şahıs 2MP ×2 · 3MS 1 · **n=4 mora=27 harf=22 — bloğun en kısa ayeti**, fâsıla تَهْجُرُونَ *(terk edersiniz / saçmalarsınız)* → ن, N sınıfı; i'râb ACC 2; bab I ×1; zaman IMPF 1 · yıldız ★ yok · kökler كبر *(büyüklük; büyüklenme)* · سمر *(Sâmirî; gece sohbeti (sâmir))* · هجر *(hicret, terk etme)* · bağ: **KARŞILIK DÜZELTMESİ (aday 480)** — kok_turkce سمر için yalnız 'Sâmirî' veriyordu; kökün dört geçişinin üçü 20:85/87/95'te سَامِرِيّ *(Sâmirî)*, biri burada سَامِر *(gece sohbeti eden)*; karşılık genişletildi",
68:"eksen yok · aktör yok · **edim soru, kip INTG 1 · NEG 2 — INTG'yi أَفَلَمْ *(…mediler mi)* açılışı veriyor, أَمْ değil (aday 483)** · şahıs 3MP ×4 · 3MS ×2 · n=10 mora=58 harf=44, fâsıla ٱلْأَوَّلِينَ *(öncekiler)* → ن, N sınıfı; i'râb ACC 3; bab I ×2 · bab V ×1; zaman IMPF ×2 · PERF 1 · yıldız ★ yok · kökler دبر *(arka; tedebbür)* · قول *(söz söyleme)* · جيأ *(gelme)* · أتي *(gelme, getirme)* · أبو *(baba)* · أول *(ilk, evvel)* · bağ: **23:24 ile ortak ءَابَآءِ … ٱلْأَوَّلِينَ *(önceki atalar)*** — orada itirazın dayanağı, burada itiraza karşı soru; **23:68-72 dört أَمْ dizisinin ilki** (elle, L1, aday 483)",
69:"eksen yok · aktör yok — elçi adsız · **edim 'haber', kip NEG 1 — ÖLÇÜM ARTEFAKTI (adaylar 438, 483)**: ayet أَمْ ile açılıyor ve soru anlamı taşıyor, ama INTG etiketi almıyor · şahıs 3MP ×4 · 3MS 1 · n=7 mora=31 harf=29, fâsıla مُنكِرُونَ *(inkâr edenler)* → ن, N sınıfı; i'râb ACC 1 · NOM 1; bab I ×1; zaman IMPF 1; simetri [3,1,5,1] · yıldız ★ yok · kökler عرف *(tanıma)* · رسل *(gönderme, elçi)* · نكر *(tanımama, inkâr; çirkin)* · bağ: **dört أَمْ dizisinin ikincisi** (elle, L1, aday 483)",
70:"eksen yok · aktör yok · **edim 'haber' — ÖLÇÜM ARTEFAKTI (adaylar 438, 483)**: أَمْ ile açılıyor, INTG yok · şahıs 3MP ×4 · 3MS ×2 · n=10 mora=54 harf=44, fâsıla كَٰرِهُونَ *(hoşlanmayanlar)* → ن, N sınıfı; i'râb NOM 3 · GEN 2; bab I ×2; zaman IMPF 1 · PERF 1; kök ikilemesi حقق *(hak, gerçek)* ×2; sayı sözcüğü أَكْثَر *(çoğu)*; biçim IDRAB; dış düğüm 1 · yıldız ★ yok · kökler قول *(söz söyleme)* · جنن *(örtme, gizleme; cennet; cin)* · جيأ *(gelme)* · حقق · كثر *(çokluk)* · كره *(zorlama; hoşlanmama)* · bağ: **23:25 ile ortak جِنَّة *(delilik)*** — orada birinci döngüde söylenmişti, burada muhataba soruluyor; xref جاء *(geldi)* + حقّ *(hak)* + أكثر *(çoğu)* → **43:78**; **ÖLÇÜM ARTEFAKTI (aday 474)**: kavram katmanı جنن için yine 'cennet' veriyor (elle, L1)",
71:"eksen yok · aktör yok · edim şart, kip COND 1 · EMPH 1 · şahıs 3MP ×5 · 1P ×2 · 3MS 1 · 3FS 1 · **3FP 1 — sûrede tek dişil çoğul şahıs** · **n=16 mora=87 harf=73 — bloğun en uzun ayeti** (n z=0,38), fâsıla مُّعْرِضُونَ *(yüz çevirenler)* → ن, N sınıfı; i'râb NOM 4 · GEN 2 · ACC 1; bab I ×2 · bab VIII ×1; zaman PERF ×3; kök ikilemesi ذكر *(anma, zikir)* ×2; biçim IDRAB; simetri [3,8,13,1]; dış düğüm 2 · yıldız ★ yok · kökler تبع *(uyma, ardından gitme)* · حقق *(hak, gerçek)* · هوي *(heves, arzu; düşme)* · فسد *(bozgunculuk, fesat)* · سمو *(ad; gök)* · أرض *(yer, yeryüzü)* · أتي *(gelme, getirme)* · ذكر · عرض *(sunma; yüz çevirme)* · bağ: xref سماء *(gök)* + أرض *(yer)* + أتى *(getirdi)* → 7:187 · 31:16; **23:3 ile ortak عرض** — orada boş sözden yüz çevirmek övgü, burada zikirden yüz çevirmek yergi (elle, L1)",
72:"eksen: lafız yok · **Rab 5. sırada, رَبِّكَ *(Rabbin)* — n=9'da tek Rab, rab z=2,05** · aktör yok · **edim 'haber' — ÖLÇÜM ARTEFAKTI (adaylar 438, 483)**: أَمْ ile açılıyor, INTG yok · şahıs 2MS ×2 · 3MP 1 · 3MS 1 · n=9 mora=44 harf=39, fâsıla ٱلرَّٰزِقِينَ *(rızık verenler)* → ن, N sınıfı; i'râb NOM 3 · GEN 2 · ACC 1; bab I ×1; zaman IMPF 1; **kök ikilemesi خرج *(çıkma, çıkarma)* ×2 · خير *(hayır, daha iyi)* ×2** · yıldız ★★ · kökler سأل *(isteme, dileme)* · خرج · ربب *(rab, terbiye etme)* · خير · رزق *(rızık)* · bağ: **23:14 · 23:29 · 23:72 — üstünlük tamlaması kalıbı üçüncü kez** (aday 484); dizinin dördüncü ve son أَمْ'i, muhatap ilk kez elçi (elle, L1)",
73:"eksen yok · aktör yok · edim haber, kip EMPH 1 · şahıs 2MS ×2 · 3MP 1 · n=5 mora=33 harf=25, **fâsıla مُّسْتَقِيمٍۢ *(dosdoğru)* → م — sûrenin م ile biten dört ayetinden biri**, sınıf N; i'râb ACC 1 · GEN 2; bab I ×1; zaman IMPF 1 · yıldız ★ yok · kökler دعو *(çağırma, dua)* · صرط *(yol, sırât)* · قوم *(kalkma; kavim; kıyamet)* · bağ: **23:74 ile bitişik صرط çifti** — burada yol çağrının hedefi (إِلَىٰ *(...e)*), orada sapılan şey (عَنِ *(...den)*) (elle, L1)",
74:"eksen yok · **esmâ آخِر *(son)* 5. sırada — ÖLÇÜM ARTEFAKTI (aday 461)**: ٱلْءَاخِرَة *(âhiret)*, dünya/âhiret çift ucu; onarım ölçütü (d); **sûredeki iki آخِر tokeninin ikisi de yanlış** · aktör yok · edim haber, kip NEG 1 · EMPH 1 · şahıs 3MP ×2 · n=8 mora=49 harf=37, fâsıla لَنَٰكِبُونَ *(sapanlar)* → ن, N sınıfı; i'râb GEN 2 · ACC 1 · NOM 1; bab IV ×1; zaman IMPF 1 · yıldız ★ yok · kökler أمن *(güven; iman)* · أخر *(geciktirme, sonraya bırakma)* · صرط *(yol, sırât)* · نكب *(sapma, yoldan çıkma; omuz)* · bağ: **23:58 ile tam karşıtlık** — orada Rablerinin âyetlerine inanırlar, burada inanmayanlar; aynı kök, aynı bab, aynı zaman, olumsuzlanmış (elle, L1)",
75:"eksen yok · aktör yok · edim şart, kip COND 1 · EMPH 1 · şahıs 3MP ×7 · 1P ×4 · n=11 mora=55 harf=46, fâsıla يَعْمَهُونَ *(bocalarlar)* → ن, N sınıfı; i'râb GEN 2; bab I ×4; zaman PERF ×3 · IMPF 1; **ayet hizb işareti ۞ taşıyor — sûrenin ikinci hizb işareti** (öteki 23:36) · yıldız ★ yok · kökler رحم *(rahmet, merhamet)* · كشف *(giderme, açma)* · ضرر *(zarar)* · لجج *(derin su, engin; direnip dalma)* · طغي *(tuğyan, azgınlık)* · عمه *(körlük, şaşkınlık)* · bağ: **23:71 ile ikinci ters şart** — orada hak heveslere uysaydı kozmos bozulurdu, burada merhamet edilseydi azgınlık sürerdi (elle, L1)",
76:"eksen: lafız yok · **Rab 6. sırada, لِرَبِّهِمْ *(Rablerine)* — n=8'de tek Rab, rab z=2,34** · aktör yok · edim haber, kip EMPH 1 · CERT 1 · NEG ×2 · şahıs 3MP ×6 · 1P ×2 · n=8 mora=53 harf=44, fâsıla يَتَضَرَّعُونَ *(yalvarırlar)* → ن, N sınıfı; i'râb GEN 2; bab I ×1 · bab V ×1 · bab X ×1; zaman PERF ×2 · IMPF 1 · yıldız ★★ · kökler أخذ *(alma, edinme)* · عذب *(azap)* · كين *(boyun eğme, istikânet)* · ربب *(rab, terbiye etme)* · ضرع *(yalvarma, tazarru)* · bağ: **وَلَقَدْ *(andolsun)* açılışı sûrede beşinci kez** (23:12 · 23:17 · 23:23 · 23:49 · 23:76); **23:64 ile ortak أَخَذْنَا … بِٱلْعَذَابِ *(azapla yakaladık)*** — orada sonuç feryat, burada boyun eğmeme (elle, L1)",
77:"eksen yok · aktör yok · edim haber · şahıs 1P ×2 · 3MP ×2 · 3MS 1 · n=12 mora=63 harf=46, fâsıla مُبْلِسُونَ *(umudunu yitirenler)* → ن, N sınıfı; i'râb ACC 2 · GEN 2 · NOM 1; bab I ×1; zaman PERF 1; simetri [3,1,9,1] · yıldız ★ yok · kökler فتح *(açma)* · بوب *(kapı)* · عذب *(azap)* · شدد *(şiddet, katılık)* · بلس *(ümidini kesme)* · bağ: **23:64 ile aynı kalıp** حَتَّىٰٓ إِذَا … إِذَا هُمْ *(nihayet … dığında, işte o zaman)*, sûrede iki kez; sonuç değişiyor: orada feryat (يَجْـَٔرُونَ), burada umut kesme (مُبْلِسُونَ) (elle, L1)",
78:"eksen yok · aktör yok · edim haber · şahıs 3MS ×2 · 2MP ×3 · n=10 mora=64 harf=49, fâsıla تَشْكُرُونَ *(şükredersiniz)* → ن, N sınıfı; **i'râb ACC 4 — tamamı mansûb**; bab I ×1 · bab IV ×1; zaman PERF 1 · IMPF 1; sayı sözcüğü قَلِيل *(az)*; dış düğüm 2 · yıldız ★ yok · kökler نشأ *(inşâ etme, yeni bir şey var etme)* · سمع *(işitme)* · بصر *(görme)* · فأد *(gönül, fuâd)* · قلل *(azlık)* · شكر *(şükür)* · bağ: xref بصر *(görme)* + فؤاد *(gönül)* + قليل *(az)* + شكر *(şükür)* → **32:9 · 67:23**; **نشأ sûrede dördüncü kez** (23:14 · 23:19 · 23:31 · 23:78); **23:78-80 üç ardışık وَهُوَ ٱلَّذِى açılışı** (elle, L1, aday 485)",
79:"eksen yok · aktör yok · edim haber · şahıs 3MS ×3 · 2MP ×3 · n=7 mora=34 harf=30, fâsıla تُحْشَرُونَ *(toplanırsınız)* → ن, N sınıfı; i'râb GEN 1; bab I ×2; zaman PERF 1 · IMPF 1; **edilgen 1 — pas z=2,52**; dış düğüm 1 · yıldız ★★ · kökler ذرأ *(yaratıp yayma, üretme)* · أرض *(yer, yeryüzü)* · حشر *(toplama, mahşer)* · bağ: xref ذرأ *(yaratıp yaydı)* + أرض *(yer)* + حشر *(toplandı)* → **67:24**; üç ardışık وَهُوَ ٱلَّذِى dizisinin ikincisi (elle, L1, aday 485)",
80:"eksen yok · aktör yok · edim soru, kip INTG 1 · NEG 1 · şahıs 3MS ×4 · 2MP ×2 · n=10 mora=54 harf=46, fâsıla تَعْقِلُونَ *(akledersiniz)* → ن, N sınıfı; i'râb NOM 1 · GEN 2; bab I ×1 · bab IV ×2; zaman IMPF ×3 · yıldız ★ yok · kökler حيي *(diri olma, hayat)* · موت *(ölüm)* · خلف *(ayrılığa düşme; ardından gelme)* · ليل *(gece)* · نهر *(ırmak; gündüz)* · عقل *(akletme, akıl)* · bağ: **23:37 ile ters kutup** — orada نَمُوتُ وَنَحْيَا *(ölürüz ve yaşarız)* insana ait ve diriliş reddediliyor, burada aynı iki kök ilâhî fiil ve sıra tersine; **22:61 ile ortak ليل/نهار çifti**; üç ardışık وَهُوَ ٱلَّذِى dizisinin üçüncüsü (elle, L1, aday 485)",
}

MERCEK={
61:"İkinci sıfat zincirinin kapanışı. Kalıp burada terk ediliyor: dört halka ٱلَّذِينَ هُم *(onlar ki)* ile açılıyordu, kapanış أُو۟لَٰٓئِكَ *(işte onlar)* ile — tam olarak birinci zincirin kapanışındaki hamle (23:10). İki zincir de ilgi zamiri dizisini işaret zamiriyle kapatıyor. Ve kapanış önceki bölüme bağlanıyor: 23:56'nın iki kökü (سرع *(hız, sürat)* ve خير *(hayır, daha iyi)*) beş ayet sonra aynı sırayla dönüyor, ama fiil birinci çoğuldan üçüncü çoğula geçiyor — koşan taraf değişiyor. Kapanışta Rab da düşüyor: dört halkanın dördünde vardı, burada yok.",
62:"Zincirin ardından gelen ilk cümle bir ölçü koyuyor ve ölçüyü HASR ile sınırlıyor: إِلَّا وُسْعَهَا *(gücünün dışında değil)*. Dikey ölçüm bu eşleşmenin korpusta zaten sabit olduğunu veriyor — كلف *(yükümlülük, külfet)* ▸sonra وسع *(genişlik, kuşatma)* ×145,5, yani sekiz geçişli bir kök neredeyse yalnız bu terimle görünüyor. Kayıt bir konuşma fiiliyle adlandırılıyor: كِتَٰبٌۭ يَنطِقُ *(konuşan bir kitap)* — نطق *(konuşma, söz söyleme)* korpusta 12 geçişli ve burada özne insan değil.",
63:"İki zincir arasındaki karşıtlık beden terimiyle kuruluyor: 23:60'ta قُلُوبُهُمْ وَجِلَةٌ *(kalpleri ürperir)*, burada قُلُوبُهُمْ فِى غَمْرَةٍ *(kalpleri gaflet içinde)*. Aynı organ, iki hâl, üç ayet arayla. Ayet fiilsiz — on dört kelimede tek çekimli fiil yok, üç isim cümlesi arka arkaya. عمل *(iş, amel)* kökü iki kez ve ikisi de isim tarafında: أَعْمَٰل *(işler)* ve عَٰمِلُونَ *(işleyenler)*.",
64:"حَتَّىٰٓ إِذَا *(nihayet … dığında)* kalıbı bir zaman eşiği koyuyor ve eşiğin iki yanı ölçülebilir biçimde ayrı: öncesi PERF ve birinci çoğul (yakalama), sonrası IMPF ve üçüncü çoğul (feryat). Eylem tamamlanmış, tepki sürüyor. جأر *(feryat etme, yalvarıp bağırma)* korpusta üç geçişli ve ikisi bu sûrede bitişik iki ayette; üçüncüsü 16:53. Kök komşuluğunda eşik üstü hiçbir kavram yok — yalıtık.",
65:"Bir önceki ayetin fiili burada olumsuz emre çevriliyor ve şahıs değişiyor: يَجْـَٔرُونَ *(feryat ederler)* → لَا تَجْـَٔرُوا۟ *(feryat etmeyin)*. Anlatı ortasında doğrudan hitaba geçiliyor, iltifât işaretlenmeden. İkinci cümle isteği reddediyor ve reddi edilgenle veriyor: لَا تُنصَرُونَ *(yardım edilmezsiniz)* — kimin etmeyeceği söylenmiyor, ama مِّنَّا *(bizden)* ile kaynak zaten belirtilmiş. نصر *(yardım)* kökü sûrede üçüncü kez: iki kez elçinin ağzında istek (23:26, 23:39), burada reddediliş.",
66:"İki كون *(olmak)* birbirine bağlı iki sürekli hâl kuruyor: biri okumanın, öteki geri dönmenin, ve ikisi de PERF + IMPF birleşimiyle geçmişte sürerlilik veriyor. Geri dönme bir beden terimiyle somutlanıyor: عَلَىٰٓ أَعْقَٰبِكُمْ *(ökçeleriniz üzerinde)* — yön değişimi topuğa bağlanıyor. نكص *(geri dönme, ökçe üstü çekilme)* korpusta iki geçişli; öteki 8:48. Konuşan burada birinci tekil (ءَايَٰتِى *(âyetlerim)*) — 23:51'de başlayan birinci tekil sürüyor.",
67:"Dört kelime, üç hâl bildiriyor ve üçü de bir öncekine bağlı: büyüklenme, gece sohbeti, saçmalama. Yüklem seçimi ölçülebilir biçimde çok anlamlı: هجر *(hicret, terk etme)* kökü hem 'terk etmek' hem 'hezeyan söylemek'; ayette hangisinin geçerli olduğu dilbilgisinden çıkarılamıyor — سَٰمِرًۭا *(gece sohbeti hâlinde)* hâl olduğu için ikisi de mümkün. Kök korpusta 31 geçişli ve ▸sonra cihad ×40,6 veriyor, yani baskın kullanım hicret.",
68:"Dört ayet boyunca sürecek soru dizisinin ilki ve tek INTG etiketli olanı. Yapı bir seçenek çifti kuruyor: ya düşünmediler, ya da beklenmedik bir şey geldi. İkinci seçenek iki gelme fiiliyle veriliyor ve fiiller ayrı köklerden — جَآءَهُم *(onlara geldi)* ve لَمْ يَأْتِ *(gelmedi)*: aynı olayın olumlu ve olumsuz yüzü iki ayrı sözcükle adlandırılıyor. دبر *(arka; tedebbür)* bab V'te, yani sözü çevirip arkasına bakma.",
69:"Soru iki karşıt kökü tek cümlede eşleştiriyor: عرف *(tanıma)* ve نكر *(tanımama, inkâr; çirkin)*. Dikey ölçüm bu çiftin korpusta zaten sabit olduğunu veriyor — عرف ▸sonra نكر ×29,5 ve نكر ▸önce tanıma ×26,0, yani iki yönde de eşleşiyorlar. Cümle bir nedensellik kuruyor: tanımama inkârın gerekçesi olarak sunuluyor, فَـ *(bu yüzden)* ile.",
70:"Üçüncü soru bir alıntı içeriyor ve alıntı sûrenin başındaki itirazın birebir tekrarı — 23:25'te بِهِۦ جِنَّةٌۭ *(kendisinde delilik var)* denmişti. Kıssalardaki itiraz burada muhataba geri dönüyor. Red بَلْ *(hayır)* ile ve iki kez حقق *(hak, gerçek)* ile veriliyor: biri getirilen şey, öteki hoşlanılmayan şey — aynı kelime iki kez mecrur ama biri fiile biri ism-i fâile bağlı.",
71:"Şart cümlesi bir ters kurgu kuruyor ve kurgunun sonucu kozmik ölçekte veriliyor: gökler, yer ve içindekiler. Fiil تبع *(uyma, ardından gitme)* — hak, uyulan değil uyan konuma konuyor ve bu tersleme bir bozulma üretiyor. İkinci yarı ölçülebilir bir tekrar taşıyor: ذكر *(anma, zikir)* iki kez ve ikisi de aynı iyelik ekiyle (بِذِكْرِهِمْ … عَن ذِكْرِهِمْ *(kendi zikirleriyle … kendi zikirlerinden)*), yani verilen ile yüz çevrilen aynı şey.",
72:"Dördüncü ve son أَمْ *(yoksa)* sorusu, ve bu kez muhatap değişiyor: üç soru inkârcılar hakkındaydı, bu doğrudan elçiye. Aynı kök iki biçimde ve karşıt yönde: خَرْجًۭا *(bir ücret)* istenen, خَرَاجُ رَبِّكَ *(Rabbinin ücreti)* verilen. خير *(hayır, daha iyi)* de iki kez, ikincisi üstünlük tamlamasında. Bu kalıp sûrede üçüncü kez ve üçü de aynı yapıda: üstünlük ismi + ism-i fâil çoğulu — yaratmada, indirmede, rızıkta.",
73:"Soru dizisi kapandıktan sonra ilk olumlu bildirim ve muhatap yine elçi. Pekiştirme iki katmanlı: إِنَّ + لَـ. Yol iki kelimeyle niteleniyor ve ikincisi قوم *(kalkma; kavim; kıyamet)* kökünden bab X ism-i fâili — 'doğruluk' ayakta durma kökünden türetiliyor. Aynı kök bu sûrede on üç kez geçti ve baskın anlamı 'kavim' idi; burada üçüncü işlevinde.",
74:"Ayet 23:73'ün olumlu bildirimini olumsuz karşılığıyla eşliyor ve iki ayet aynı pekiştirmeyi taşıyor (إِنَّ + لَـ). صرط *(yol, sırât)* iki ayette de var ama i'râbı değişiyor: 23:73'te إِلَىٰ *(...e)* ile hedef, burada عَنِ *(...den)* ile terk edilen. Aynı yol iki edatla iki yöne çevriliyor. نكب *(sapma, yoldan çıkma; omuz)* korpusta iki geçişli; öteki 67:15'te 'omuz' anlamında — kök burada tamamen ayrı işlevde.",
75:"İkinci ters şart cümlesi ve yapısı birincinin aynısı: لَوْ *(eğer)* + PERF, cevapta لَـ + PERF. İki şart da bir 'olmayan'ı kurup sonucunu ölçüyor. Kapanış iki fiili üst üste bindiriyor ve ikincisi birincinin hâli: لَّجُّوا۟ … يَعْمَهُونَ *(direnirler … bocalayarak)*. Dikey ölçüm bu çiftin sabitliğini veriyor — طغي *(tuğyan, azgınlık)* ▸sonra عمه *(körlük, şaşkınlık)* ×132,0 ve عمه ▸önce tuğyan ×159,0; yedi geçişli bir kök neredeyse yalnız bu terimin yanında görünüyor.",
76:"Aynı olay iki kez ve iki ayrı sonuçla: 23:64'te azap yakalayınca feryat ediliyordu, burada yakalıyor ama boyun eğilmiyor. İki ayrı boyun eğme kökü olumsuzlanıyor ve ikisi de dönüşlü kalıplarda — ٱسْتَكَانُوا۟ *(boyun eğdiler)* bab X, يَتَضَرَّعُونَ *(yalvarırlar)* bab V. كين *(boyun eğme, istikânet)* korpusta iki geçişli; öteki 3:146. Zaman ikisi arasında ayrılıyor: biri PERF biri IMPF — olmadı ve olmuyor.",
77:"İkinci حَتَّىٰٓ إِذَا *(nihayet … dığında)* eşiği ve yapısı birincinin aynısı: PERF + birinci çoğul, sonra إِذَا هُمْ + ism-i fâil. Ama sonuç sese değil sessizliğe çıkıyor — 23:64'te bağırma, burada umudun kesilmesi. Azap bu kez bir mekân terimiyle veriliyor: بَابًۭا *(bir kapı)*; dikey ölçüm فتح *(açma)* ▸sonra بوب *(kapı)* ×63,0 veriyor, kök çifti korpusta zaten sabit.",
78:"نشأ *(inşâ etme, yeni bir şey var etme)* kökü dördüncü kez ve nesnesi yine değişiyor: insanın son aşaması (23:14), bahçeler (23:19), bir nesil (23:31), şimdi duyular. Üç duyu ölçülebilir bir sayı asimetrisi taşıyor: ٱلسَّمْعَ *(işitme)* tekil, ٱلْأَبْصَٰرَ *(gözler)* ve ٱلْأَفْـِٔدَةَ *(gönüller)* çoğul. Bu üçlü korpusta üç ayette birlikte ve üçünde de aynı azlık kalıbıyla kapanıyor.",
79:"Yedi kelimede bir yayılma ve bir toplanma karşı karşıya konuyor: ذَرَأَ *(yaratıp yaydı)* ve تُحْشَرُونَ *(toplanırsınız)*. Yön iki edatla ayrılıyor — فِى ٱلْأَرْضِ *(yeryüzünde)* dağılma alanı, إِلَيْهِ *(O'na)* toplanma noktası. Çatı da ayrılıyor: birincisi etken ve fâili adlandırılmış, ikincisi edilgen ve fâili silinmiş. ذرأ korpusta altı geçişli; komşuluğunda eşik üstü tek kavram أرض *(yer, yeryüzü)* ×8,8 — kök zaten yeryüzüne bağlı.",
80:"Üçüncü وَهُوَ ٱلَّذِى *(O'dur ki)* ve içinde iki karşıt çift: hayat-ölüm, gece-gündüz. Birinci çift fiillerle (bab IV ×2, ikisi de ettirgen), ikincisi bir masdarla — ٱخْتِلَٰفُ *(değişme, birbiri ardınca gelme)*, خلف *(ayrılığa düşme; ardından gelme)* kökünden bab VIII. Sıra ölçülebilir biçimde 23:37'nin tersi: orada نَمُوتُ وَنَحْيَا *(ölürüz ve yaşarız)* ile ölüm önce yazılmıştı, burada diriltme önce.",
}

p='/home/claude/repo/notlar/okuma_metni.json'
OM=json.load(open(p,encoding='utf-8'))
for n in range(61,81):
    OM['23']["23:%d"%n]={"ar":AR[(23,n)],"meal":MEAL[n],"olcum":OLCUM[n],
                         "mercek":MERCEK[n],"dikey":DIK["23:%d"%n]}
OM['23']['_mercek_atlama_notu']["_blok_notu_61_80"]=(
 "Blok 23:61-80'de ★★★ ayet YOK — sûrede bugüne dek okunan 80 ayetin yedi ★★★'ı "
 "23:16, 22, 26, 36, 39, 58, 59; bu blokta en yüksek yıldız ★★ (23:65, 23:72, 23:76, 23:79). "
 "Dolayısıyla biyolog ve uzay merceği bu blokta hiç devreye girmedi. NOT: blokta biyolojik "
 "öğe taşıyan 23:78 (سمع *(işitme)* · بصر *(görme)* · فأد *(gönül, fuâd)*) ve 23:66 "
 "(عقب *(ökçe)*) ★ ALMADI; adaylar 468 ve 472.")
OM['ilerleme']['not']=("Sûre 22 TAM (78/78). Sûre 23 (Mü'minûn) makro profil + 23:1-80 okundu. "
                       "Devam: 23:81. İki sıfat zinciri de kapandı (23:2-10 ve 23:57-61).")
OM['ilerleme']['kismi']={"2":"1-20 ayet düzeyinde","23":"1-80 ayet düzeyinde"}
OM['ilerleme']['okunan_ayet']=1543
json.dump(OM,open(p,'w',encoding='utf-8'),ensure_ascii=False,indent=1)
print('okuma_metni: sûre 23 →',len([k for k in OM['23'] if not k.startswith('_')]),'ayet')

pm='/home/claude/repo/notlar/mercek_kayit.json'
MK=json.load(open(pm,encoding='utf-8'))
for n in range(61,81): MK['23']["23:%d"%n]=MERCEK[n]
MK['23_atlama']["_blok_notu_61_80"]=OM['23']['_mercek_atlama_notu']["_blok_notu_61_80"]
json.dump(MK,open(pm,'w',encoding='utf-8'),ensure_ascii=False,indent=1)
print('mercek_kayit: sûre 23 →',len(MK['23']),'mercek')
