# -*- coding: utf-8 -*-
"""blok_22_21_40.py — Hac 21-40 bloğunun okuma kaydı."""
import json

DIK = json.load(open('blok_dikey_22_21_40.json', encoding='utf-8'))
veri = json.load(open('kuran_veri.json', encoding='utf-8'))
AR = {}
for s in veri['sureler']:
    for a in s['ayetler']:
        AR[(s['no'], a['no'])] = a['ar']

MEAL = {
21: "Onlar için demirden topuzlar vardır.",
22: "Ne zaman oradan, o gamdan çıkmak isteseler, oraya geri döndürülürler: \"Yakıcı azabı tadın.\"",
23: "Allah, iman edip salih işler yapanları, altlarından ırmaklar akan bahçelere sokar. Orada altın bileziklerle ve incilerle süslenirler; oradaki giysileri de ipektir.",
24: "Sözün temizine iletilmişlerdir; övgüye lâyık olanın yoluna iletilmişlerdir.",
25: "İnkâr edenler, Allah'ın yolundan ve yerli ile dışarıdan gelen için eşit kıldığımız Mescid-i Harâm'dan alıkoyanlar… Kim orada zulümle bir sapma dilerse, ona acı bir azaptan tattırırız.",
26: "Hani İbrâhim'e o Ev'in yerini hazırlamıştık: Bana hiçbir şeyi ortak koşma; evimi tavaf edenler, kıyama duranlar, rükû ve secde edenler için temizle.",
27: "İnsanlar arasında haccı ilân et; sana yaya olarak ve her uzak yoldan gelen zayıflamış binekler üstünde gelsinler.",
28: "Kendileri için birtakım yararlara tanık olsunlar ve belirli günlerde, kendilerine rızık olarak verdiği hayvanlar üzerine Allah'ın adını ansınlar. Onlardan yiyin, darda kalmış yoksula da yedirin.",
29: "Sonra kirlerini gidersinler, adaklarını yerine getirsinler ve o Eski Ev'i tavaf etsinler.",
30: "İşte böyle. Kim Allah'ın saygıya değer kıldıklarını yüceltirse, bu Rabbi katında kendisi için hayırlıdır. Size okunacak olanlar dışında hayvanlar helâl kılınmıştır. Öyleyse putların pisliğinden kaçının, yalan sözden de kaçının.",
31: "Allah'a yönelmiş, O'na ortak koşmayanlar olarak. Kim Allah'a ortak koşarsa, sanki gökten düşmüş de kendisini kuşlar kapıyor ya da rüzgâr onu uzak bir yere sürüklüyordur.",
32: "İşte böyle. Kim Allah'ın işaretlerini yüceltirse, bu kalplerin takvâsındandır.",
33: "Onlarda sizin için belirli bir süreye kadar yararlar vardır; sonra varacakları yer o Eski Ev'dir.",
34: "Her ümmet için bir kurban ibadeti kıldık ki, kendilerine rızık olarak verdiği hayvanlar üzerine Allah'ın adını ansınlar. İlâhınız tek bir ilâhtır; öyleyse O'na teslim olun. Ve alçakgönüllüleri müjdele.",
35: "Onlar ki Allah anıldığında kalpleri ürperir; başlarına gelene sabreder, namazı kılar ve kendilerine verdiğimiz rızıktan infak ederler.",
36: "Kurbanlık develeri de sizin için Allah'ın işaretlerinden kıldık; onlarda sizin için hayır vardır. Saf hâlde dururken üzerlerine Allah'ın adını anın. Yanları yere düştüğünde onlardan yiyin; kanaat edene de isteyene de yedirin. Onları size böyle boyun eğdirdik ki şükredesiniz.",
37: "Onların etleri de kanları da Allah'a ulaşmaz; ama sizden O'na takvâ ulaşır. Size doğru yolu gösterdiği için Allah'ı yüceltesiniz diye onları böyle boyun eğdirdi. İyilik edenleri müjdele.",
38: "Allah iman edenleri savunur. Allah hiçbir hain nankörü sevmez.",
39: "Kendilerine savaş açılanlara, zulme uğradıkları için izin verilmiştir. Allah onlara yardım etmeye elbette kadirdir.",
40: "Onlar, \"Rabbimiz Allah'tır\" demelerinden başka bir hak sebep olmaksızın yurtlarından çıkarıldılar. Eğer Allah insanların bir kısmını diğerleriyle savmasaydı, içlerinde Allah'ın adının çokça anıldığı manastırlar, kiliseler, havralar ve mescitler yıkılıp giderdi. Allah kendisine yardım edene mutlaka yardım eder. Allah gerçekten güçlüdür, üstündür.",
}

OLCUM = {
21: "eksen yok · aktör yok · edim haber · şahıs 3MP 1 · **n=4 mora=20 harf=15 — SÛRENİN EN KISA AYETİ (n z=-0,89)**, fâsıla حَدِيدٍۢ *(demir)* → د, د sınıfı; i'râb NOM 1 · GEN 1; **fiil yok, bab ve zaman alanları boş**; **hapaks قمع *(demir topuz, mıkma)* (z=3,38)** · yıldız ★★★ · kökler قمع *(demir topuz, mıkma)* · حدد *(demir; sınır koyma)* · bağ: 22:19-20 ile tek sahne (elle, L1)",
22: "eksen yok · aktör yok · edim emir, kip IMPV 1 · şahıs 3MP ×6 · 3FS ×2 · 2MP ×2 · n=12 mora=70 harf=56, fâsıla ٱلْحَرِيقِ *(yakıcı)* → ق, ق sınıfı — 22:9'un fâsılasıyla aynı kelime; i'râb GEN 2 · ACC 1; bab I ×2 · bab IV ×2; edilgen 1 (أُعِيدُوا۟ *(döndürülürler)*, z=1,1); **dış düğüm 3** · kökler كلل *(hep, bütün)* · رود *(isteme, irade)* · خرج *(çıkma, çıkarma)* · غمم *(gam, tasa; bürüme)* · عود *(dönme, tekrarlama)* · ذوق *(tatma)* · عذب *(azap)* · حرق *(yakma)* · bağ: xref ذاق *(tatma)* + عذاب *(azap)* + حريق *(yakıcı)* → 3:181 ve 8:50 · كلّما *(ne zaman)* + أراد *(dileme)* + خرج *(çıkma)* → 32:20",
23: "eksen: **Allah lafzı 2. sırada** (allah z=0,38) · aktör yok · edim haber · şahıs 3MS 1 · 3MP ×7 · 3FS ×4 · n=22 mora=120 harf=102, fâsıla حَرِيرٌۭ *(ipek)* → ر, R sınıfı; i'râb ACC 3 · GEN 5 · NOM 3; bab I ×2 · bab II ×1 · bab IV ×2; edilgen 1 (يُحَلَّوْنَ *(süslenirler)*); **dış düğüm 4** · kökler أله *(ilâh; lafza-i celâl)* · دخل *(girme, sokma)* · أمن *(güven; iman)* · عمل *(iş, amel)* · صلح *(iyi olma, salâh)* · جنن *(cin; örtme; cennet)* · جري *(akma, koşma)* · تحت *(alt, altında)* · نهر *(ırmak; gündüz)* · حلي *(süs, ziynet takma)* · سور *(bilezik; sur, sûre)* · ذهب *(gitme; altın)* · لؤلؤ *(inci)* · لبس *(giyinme; karıştırma)* · حرر *(ipek; azat etme; sıcaklık)* · bağ: **22:14 ile bölüt ikizi** — إِنَّ ٱللَّهَ يُدْخِلُ … ٱلْأَنْهَٰرُ *(Allah… sokar… ırmaklar)* birebir aynı, dokuz ayet arayla; xref 14:23 · 47:12 · 18:31 · 35:33",
24: "eksen yok · **esmâ حَمِيد *(hamîd)* 9. sırada = fâsıla**; bağlam denetlendi: صِرَٰطِ ٱلْحَمِيدِ *(hamîdin yolu)* — izafet muzâf-ileyhi, ilâhî ad, **geçerli** · aktör yok · edim haber · şahıs 3MP ×4 · n=9 mora=49 harf=39, fâsıla ٱلْحَمِيدِ → د, د sınıfı; **i'râb GEN 4 — tamamı mecrur**; bab I ×2; **edilgen 2 — n=9'da iki edilgen, z=5,38: bloğun en yüksek edilgen yoğunluğu**; kök ikilemesi هدي *(yol gösterme)* ×2 — **ikisi de edilgen, ikisi de PERF**; simetri [3,1,6,1] · yıldız ★★★ · kökler هدي *(yol gösterme)* · طيب *(temiz, hoş)* · قول *(söz söyleme)* · صرط *(yol, sırât)* · حمد *(hamd, övgü)* · bağ: xref yok",
25: "eksen: **Allah lafzı 7. sırada**, سَبِيلِ ٱللَّهِ *(Allah yolu)* terkîbinde (allah z=0,27) · aktör yok — ٱلْمَسْجِدِ ٱلْحَرَامِ *(Mescid-i Harâm)* aktör tablosuna GİRMİYOR (terkip, tek lemma değil; aday 462) · edim haber · şahıs 3MP ×4 · 1P ×3 · 3MS ×5 · **n=25 mora=136 harf=111 — bloğun en uzun üçüncü ayeti**, fâsıla أَلِيمٍۢ *(acı)* → م, N sınıfı (kafiye kırılması işaretli); **i'râb GEN 10**; bab I ×3 · bab IV ×2 · yıldız ★ · kökler كفر *(inkâr, nankörlük)* · صدد *(alıkoyma, çevirme)* · سبل *(yol)* · أله *(ilâh; lafza-i celâl)* · سجد *(secde; mescid)* · حرم *(haram kılma, yasak)* · جعل *(kılma, var etme)* · أنس *(insan)* · سوي *(denk, düzleme)* · عكف *(başında durma, ikâf)* · بدو *(çöl, bedevî; görünme)* · رود *(isteme, irade)* · لحد *(sapma, ilhâd; lahit)* · ظلم *(zulüm)* · ذوق *(tatma)* · عذب *(azap)* · ألم *(elem, acı)* · bağ: xref ظلم *(zulüm)* + أذاق *(tattırma)* + عذاب *(azap)* → 25:19",
26: "eksen yok · aktör: adlı إِبْراهِيم *(İbrâhim)* 3. sırada, rol mecrur — **sûrenin üç İbrâhim geçişinden ilki** · edim emir + yasak, kip PRO 1 · IMPV 1 · şahıs 1P ×2 · 2MS ×2 · 1S ×2 · n=16 mora=99 harf=76, fâsıla ٱلسُّجُودِ *(secde edenler)* → د, د sınıfı; i'râb GEN 6 · ACC 2 · NOM 1; bab II ×2 · bab IV ×1; kök ikilemesi بيت *(ev, mesken)* ×2 — biri مَكَانَ ٱلْبَيْتِ *(Ev'in yeri)*, öteki بَيْتِىَ *(evim)*, yani iyelik değişiyor; biçim NEHY; simetri [3,1,7,1] · kökler بوأ *(yerleştirme, mekân hazırlama)* · كون *(olmak; mekân)* · بيت *(ev, mesken)* · شرك *(ortak koşma)* · شيأ *(dileme; şey)* · طهر *(temizlenme, tahâret)* · طوف *(dolaşma, tavaf)* · قوم *(kalkma; kavim; kıyamet)* · ركع *(rükû)* · سجد *(secde)* · bağ: xref طهّر *(temizleme)* + بيت *(ev)* + طائف *(tavaf eden)* → 2:125",
27: "eksen yok · aktör: **adsız aktör 'racül' 6. sırada** — sûrede ilk adsız aktör kaydı · edim emir, kip IMPV 1 · şahıs 2MS ×2 · 3MP ×2 · **3FP ×2 — fiil dişil çoğul, göndergesi binekler** · n=14 mora=71 harf=54, fâsıla عَمِيقٍۢ *(derin, uzak)* → ق, ق sınıfı; i'râb GEN 7 · ACC 1; bab I ×2 · bab II ×1; **hapaks İKİ TANE: ضمر *(zayıflamış (deve))* ve عمق *(derinlik, uzaklık)* — ikisi de korpusta tek geçişli (hapaks z=6,98)**; kök ikilemesi أتي *(gelme, getirme)* ×2 ve كلل *(hep, bütün)* ×2; simetri [3,7,11,1] · yıldız ★★★ · kökler أذن *(izin; bildirme; kulak)* · أنس *(insan)* · حجج *(hac; delil, hüccet)* · أتي *(gelme, getirme)* · رجل *(adam; yaya)* · كلل *(hep, bütün)* · ضمر *(zayıflamış (deve))* · فجج *(geniş yol, dağ geçidi (fecc))* · عمق *(derinlik, uzaklık)* · bağ: **21:31 ile ortak فجج** — orada yerdeki geçitler, burada gelinen yollar (elle, L2)",
28: "eksen: **Allah lafzı 6. sırada**, ٱسْمَ ٱللَّهِ *(Allah'ın adı)* terkîbinde (allah z=0,47) · aktör yok · edim emir, kip IMPV 2 · şahıs 3MP ×6 · 3MS 1 · 2MP ×4 · 3FS 1 · n=20 mora=116 harf=98, fâsıla ٱلْفَقِيرَ *(fakir)* → ر, R sınıfı (kafiye kırılması işaretli); i'râb ACC 4 · GEN 5; bab I ×4 · bab IV ×1; **dış düğüm 5 · iç düğüm 3** · yıldız ★ · kökler شهد *(şahitlik)* · نفع *(fayda)* · ذكر *(anma, zikir)* · سمو *(ad; gök)* · أله *(ilâh; lafza-i celâl)* · يوم *(gün)* · علم *(bilme)* · رزق *(rızık)* · بهم *(dilsiz hayvan)* · نعم *(nimet; davar)* · أكل *(yeme)* · طعم *(yedirme, yemek)* · بأس *(şiddet, azap; yoksulluk)* · فقر *(fakirlik)* · bağ: **ذِكْرُ ٱسْمِ ٱللَّهِ *(Allah'ın adının anılması)* nakaratı — korpusta 9 ayette, DÖRDÜ bu blokta** (22:28 · 22:34 · 22:36 · 22:40); öteki beşi 5:4 · 6:118 · 6:119 · 6:121 · 6:138 (bkz. aday 463)",
29: "eksen yok · aktör yok · edim emir, kip IMPV 2 · şahıs **3MP ×8 — ayette tek şahıs** · n=8 mora=54 harf=49, fâsıla ٱلْعَتِيقِ *(eski)* → ق, ق sınıfı (kafiye kırılması işaretli); i'râb ACC 2 · GEN 2; bab I ×1 · bab IV ×1 · bab V ×1 — üç fiil, üçü de ayrı bab; **hapaks تفث *(hac kirini giderme, tefes)* (z=3,38)**; **üç lâmü'l-emr** (لْيَقْضُوا۟ · وَلْيُوفُوا۟ · وَلْيَطَّوَّفُوا۟) · yıldız ★★★ · kökler قضي *(hükmetme, bitirme)* · تفث *(hac kirini giderme, tefes)* · وفي *(tam verme, vefa; vefat ettirme)* · نذر *(uyarı; adak)* · طوف *(dolaşma, tavaf)* · بيت *(ev, mesken)* · عتق *(eski, atîk; azat)* · bağ: 22:33 ile aynı fâsıla terkîbi ٱلْبَيْتِ ٱلْعَتِيقِ *(Eski Ev)* (elle, L1); **22:15 ile aynı dilbilgisi kalıbı — üç lâmü'l-emr** (aday 460)",
30: "eksen: **Allah lafzı 5. sırada** (allah z=0,31) · Rab 10. sırada, عِندَ رَبِّهِۦ *(Rabbi katında)* (rab z=0,57) · aktör yok · edim emir, kip RES 1 · IMPV 2 · şahıs 3MS ×5 · 3FS 1 · 2MP ×6 · n=24 mora=116 harf=104, fâsıla ٱلزُّورِ *(yalan)* → ر, R sınıfı (kırılma işaretli); i'râb GEN 5 · NOM 2 · ACC 3; bab I ×1 · bab II ×1 · bab IV ×1 · bab VIII ×2; edilgen 2 (أُحِلَّتْ *(helâl kılındı)* · يُتْلَىٰ *(okunur)*, z=1,95); kök ikilemesi جنب *(yan, taraf; kaçınma)* ×2 — ikisi de emir; biçim HASR; simetri [3,1,14,1] · yıldız ★ · kökler عظم *(büyüklük, azamet; kemik)* · حرم *(haram kılma, yasak)* · أله *(ilâh; lafza-i celâl)* · خير *(hayır, daha iyi)* · عند *(yan, katında)* · ربب *(rab, terbiye etme)* · حلل *(helâl; çözme)* · نعم *(nimet; davar)* · تلو *(okuma, tilâvet)* · جنب *(yan, taraf; kaçınma)* · رجس *(pislik, rics)* · وثن *(put, vesen)* · قول *(söz söyleme)* · زور *(yalan, uydurma)* · bağ: **22:32 ile bölüt ikizi** — ذَٰلِكَ وَمَن يُعَظِّمْ *(işte böyle; kim yüceltirse)* birebir aynı, iki ayet arayla, sonra ayrılıyor; xref خير *(hayır)* + عند *(kat)* + ربّ *(Rab)* → 18:46 ve 19:76",
31: "eksen: **Allah lafzı İKİ geçiş — 2. ve 8. sırada** (allah z=1,38; kök ikilemesi أله ×2) · aktör yok · edim haber · şahıs 3MS ×5 · 3FS ×2 · n=21 mora=103 harf=85, fâsıla سَحِيقٍۢ *(uzak)* → ق, ق sınıfı; i'râb ACC 3 · GEN 6 · NOM 2; bab I ×3 · bab IV ×1; kök ikilemesi شرك *(ortak koşma)* ×2 — biri ism-i fâil çoğul, öteki fiil; simetri [3,9,15,1] · kökler حنف *(hanîf, dosdoğru)* · أله *(ilâh; lafza-i celâl)* · غير *(başka)* · شرك *(ortak koşma)* · خرر *(yıkılıp düşme)* · سمو *(ad; gök)* · خطف *(kapıp götürme)* · طير *(kuş; uçma)* · هوي *(düşme; hevâ)* · روح *(ruh; rüzgâr)* · كون *(olmak; mekân)* · سحق *(uzaklık; ezip un etme)* · bağ: xref yok",
32: "eksen: **Allah lafzı 5. sırada** (allah z=1,69) · aktör yok · edim haber · şahıs 3MS 1 · 3FS 1 · n=9 mora=47 harf=35, **fâsıla ٱلْقُلُوبِ *(kalpler)* → ب, ب sınıfı — sûrede yalnız iki ayet bu sınıfta (22:32 ve 22:73)** (kırılma işaretli); i'râb ACC 2 · GEN 3; bab II ×1 (tek fiil); simetri [3,1,6,1] · yıldız ★ · kökler عظم *(büyüklük, azamet; kemik)* · شعر *(şuur; şeâir; şiir)* · أله *(ilâh; lafza-i celâl)* · وقي *(sakınma, takvâ)* · قلب *(çevirme, kalp)* · bağ: **22:30 ile bölüt ikizi** (elle, L1)",
33: "eksen yok · aktör yok · edim haber · şahıs 2MP 1 · 3FS ×2 · n=11 mora=62 harf=44, fâsıla ٱلْعَتِيقِ *(eski)* → ق, ق sınıfı — 22:29'un fâsılasıyla aynı; i'râb NOM 2 · GEN 4; **fiil yok, bab ve zaman alanları boş — 22:21 ile birlikte bloğun iki fiilsiz ayetinden biri**; simetri [3,2,7,1] · kökler نفع *(fayda)* · أجل *(süre, ecel)* · سمو *(ad; gök)* · حلل *(helâl; kurban yeri)* · بيت *(ev, mesken)* · عتق *(eski, atîk; azat)* · bağ: 22:28 ile ortak نفع *(fayda)* (elle, L2)",
34: "eksen: **Allah lafzı 7. sırada**, yine ٱسْمَ ٱللَّهِ terkîbinde (allah z=0,47) · aktör yok · edim emir, kip IMPV 2 · şahıs 1P ×2 · 3MP ×3 · 3MS ×2 · 2MP ×3 · 2MS 1 · n=20 mora=116 harf=97, fâsıla ٱلْمُخْبِتِينَ *(alçakgönüllüler)* → ن, N sınıfı; i'râb GEN 5 · ACC 3 · NOM 3; bab I ×3 · bab II ×1 · bab IV ×1; **kök ikilemesi أله ×3 — biri lafız, ikisi 'ilâh'**; sayı sözcüğü واحِد *(bir, tek)*; **dış düğüm 5 · iç düğüm 3** · kökler كلل *(hep, bütün)* · أمم *(önder, imam; ümmet)* · جعل *(kılma, var etme)* · نسك *(kurban ibadeti, nüsük)* · ذكر *(anma, zikir)* · سمو *(ad; gök)* · أله *(ilâh; lafza-i celâl)* · رزق *(rızık)* · بهم *(dilsiz hayvan)* · نعم *(nimet; davar)* · وحد *(bir olma, teklik)* · سلم *(esenlik; teslim olma)* · بشر *(müjde; beşer)* · خبت *(alçakgönüllü olma, ihbât)* · bağ: **22:108 kalıbı burada tekrar** — إِلَٰهُكُمْ إِلَٰهٌۭ وَٰحِدٌۭ *(ilâhınız tek bir ilâhtır)*, 22:108'de de aynen vardı (elle, L1); nakarat ذِكْرُ ٱسْمِ ٱللَّهِ (aday 463)",
35: "eksen: **Allah lafzı 4. sırada** (allah z=0,81) · aktör yok · edim haber · şahıs 3MS ×2 · 3FS 1 · 3MP ×5 · 1P ×2 · n=15 mora=95 harf=74, fâsıla يُنفِقُونَ *(infak ederler)* → ن, N sınıfı; i'râb NOM 2 · ACC 2 · GEN 1; bab I ×3 · bab IV ×2; edilgen 1 (ذُكِرَ *(anıldı)*); simetri [3,1,8,1]; **dış düğüm 3** · kökler ذكر *(anma, zikir)* · أله *(ilâh; lafza-i celâl)* · وجل *(ürperme, korku)* · قلب *(çevirme, kalp)* · صبر *(sabır)* · صوب *(isabet etme, doğru olma)* · قوم *(kalkma; kavim; kıyamet)* · صلو *(namaz, salât)* · رزق *(rızık)* · نفق *(infak, harcama; nifak)* · bağ: xref صلاة *(namaz)* + رزق *(rızık)* + أنفق *(infak)* → 2:3 ve 8:3 · ذكر *(zikir)* + اللّه + وجلت *(ürperdi)* → 8:2",
36: "eksen: **Allah lafzı İKİ geçiş — 6. ve 12. sırada** (allah z=0,95; kök ikilemesi أله ×2) · aktör yok · edim emir, kip IMPV 3 · şahıs 1P ×4 · 3FS ×7 · **2MP ×12 — bloğun en yüksek muhatap yoğunluğu** · **n=27 mora=157 harf=132 — bloğun en uzun ikinci ayeti (n z=1,55)**, fâsıla تَشْكُرُونَ *(şükredersiniz)* → ن, N sınıfı; i'râb ACC 6 · GEN 3 · NOM 2; bab I ×5 · bab II ×1 · bab IV ×1; **hapaks وجب *(düşüp yere yıkılma; gerekli olma)* (z=3,38)**; simetri [3,3,7,1]; **dış düğüm 5 · iç düğüm 3** · yıldız ★★★ · kökler بدن *(kurbanlık deve (büdn); beden)* · جعل *(kılma, var etme)* · شعر *(şuur; şeâir; şiir)* · أله *(ilâh; lafza-i celâl)* · خير *(hayır, daha iyi)* · ذكر *(anma, zikir)* · سمو *(ad; gök)* · صفف *(saf tutma, sıra)* · وجب *(düşüp yere yıkılma; gerekli olma)* · جنب *(yan, taraf; kaçınma)* · أكل *(yeme)* · طعم *(yedirme, yemek)* · قنع *(kanaat etme; el açma)* · عرر *(sıkıntı içinde bekleyen)* · سخر *(boyun eğdirme)* · شكر *(şükür)* · bağ: nakarat ذِكْرُ ٱسْمِ ٱللَّهِ (aday 463); **21:79 ile ortak سخر *(boyun eğdirme)*** — orada dağlar ve kuşlar, burada kurbanlıklar (elle, L2)",
37: "eksen: **Allah lafzı İKİ geçiş — 3. ve 15. sırada** (allah z=1,47; kök ikilemesi أله ×2) · aktör yok · edim emir, kip NEG 2 · IMPV 1 · şahıs 3MS ×5 · 3FS ×3 · 2MP ×5 · 2MS 1 · n=20 mora=114 harf=92, fâsıla ٱلْمُحْسِنِينَ *(iyilik edenler)* → ن, N sınıfı; i'râb ACC 3 · NOM 3; bab I ×3 · bab II ×3; kök ikilemesi نيل *(erişme, nail olma)* ×2 — **biri olumsuz biri olumlu, aynı fiil iki karşıt öznede**; simetri [3,1,7,1] · kökler نيل *(erişme, nail olma)* · أله *(ilâh; lafza-i celâl)* · لحم *(et)* · دمو *(kan)* · وقي *(sakınma, takvâ)* · سخر *(boyun eğdirme)* · كبر *(büyüklük; büyüklenme)* · هدي *(yol gösterme)* · بشر *(müjde; beşer)* · حسن *(güzellik, iyilik)* · bağ: xref كبّر *(yüceltme)* + اللّه + هدى *(yol gösterme)* → 2:185; 22:36 ile ortak سخر (elle, L1)",
38: "eksen: **Allah lafzı İKİ geçiş — 2. ve 8. sırada (allah z=2,55 — bloğun en yüksek lafız yoğunluğu)**; kök ikilemesi أله ×2 · aktör yok · edim haber, kip NEG 1 · şahıs 3MS ×2 · 3MP ×2 · n=13 mora=64 harf=48, fâsıla كَفُورٍ *(nankör)* → ر, R sınıfı; i'râb ACC 5 · GEN 2; bab III ×1 · bab IV ×2; simetri [3,1,7,1]; ۞ hizb işaretiyle açılıyor · yıldız ★★ · kökler أله *(ilâh; lafza-i celâl)* · دفع *(savma, def etme)* · أمن *(güven; iman)* · حبب *(sevgi; tane)* · كلل *(hep, bütün)* · خون *(hıyanet)* · كفر *(inkâr, nankörlük)* · bağ: 22:40 ile ortak دفع *(savma, def etme)* (elle, L1)",
39: "eksen: **Allah lafzı 7. sırada** (allah z=1,47) · **esmâ قَدِير *(kadîr)* 10. sırada = fâsıla**; bağlam denetlendi: عَلَىٰ نَصْرِهِمْ لَقَدِيرٌ *(onlara yardıma kadirdir)*, ilâhî ad, **geçerli** · aktör yok · edim haber, kip EMPH 1 · şahıs 3MS 1 · 3MP ×6 · n=10 mora=56 harf=46, fâsıla لَقَدِيرٌ → ر, R sınıfı; i'râb ACC 3 · GEN 1 · NOM 1; bab I ×2 · bab III ×1; **edilgen 3 — n=10'da üç edilgen, z=5,38: 22:24 ile birlikte bloğun rekoru** (أُذِنَ *(izin verildi)* · يُقَٰتَلُونَ *(savaşılırlar)* · ظُلِمُوا۟ *(zulme uğradılar)*); simetri [3,2,6,1] · yıldız ★★★ · kökler أذن *(izin; bildirme; kulak)* · قتل *(öldürme)* · ظلم *(zulüm)* · أله *(ilâh; lafza-i celâl)* · نصر *(yardım)* · قدر *(ölçü, takdir; güç)* · bağ: 22:40 ile tek cümle — ٱلَّذِينَ ile devam ediyor (elle, L1)",
40: "eksen: **Allah lafzı BEŞ geçiş — 11., 14., 26., 29. ve 33. sırada (allah z=2,33); kök ikilemesi أله ×5 — SÛRENİN VE OKUMANIN EN YÜKSEK TEK-AYET LAFIZ YIĞILMASI** · Rab 10. sırada, رَبُّنَا ٱللَّهُ *(Rabbimiz Allah'tır)* içinde (rab z=0,29) — **lafız ile Rab'ın bir arada geçtiği tek ayet** · **esmâ İKİ token ve MÜHÜR: قَوِيّ|عَزِيز *(kavî|azîz)* 34. ve 35. sırada — sûrenin ilk mühürü**; bağlam denetlendi, ikisi de geçerli · aktör yok · edim şart, kip RES 1 · COND 1 · **EMPH ×4** · şahıs 3MP ×6 · 1P 1 · 3FS ×2 · 3MS ×4 · **n=35 mora=188 harf=154 — bloğun en uzun ayeti (n z=2,4)**, fâsıla عَزِيزٌ *(azîz)* → ز, **ز sınıfı — sûrede yalnız iki ayet** (22:40 ve 22:74) (kırılma işaretli); **i'râb NOM 11** · GEN 6 · ACC 5; bab I ×4 · bab II ×1 · bab IV ×1; edilgen 3 (أُخْرِجُوا۟ *(çıkarıldılar)* · هُدِّمَتْ *(yıkılırdı)* · يُذْكَرُ *(anılır)*, z=2,52); **hapaks İKİ TANE: صمع *(manastır, savmaa)* ve هدم *(yıkma)* (hapaks z=6,98)**; kök ikilemesi بعض *(bir kısım)* ×2 ve نصر *(yardım)* ×2; sayı sözcüğü كَثِير *(çok)*; biçim HASR; simetri [3,1,30,1]; **dış düğüm 9 — okumada görülen en bağlantılı ayet** · yıldız ★★★ · kökler خرج *(çıkma, çıkarma)* · دور *(yurt, ev; devir)* · غير *(başka)* · حقق *(hak, gerçek)* · قول *(söz söyleme)* · ربب *(rab, terbiye etme)* · أله *(ilâh; lafza-i celâl)* · دفع *(savma, def etme)* · أنس *(insan)* · بعض *(bir kısım)* · هدم *(yıkma)* · صمع *(manastır, savmaa)* · بيع *(alışveriş; kilise, biya)* · صلو *(namaz, salât)* · سجد *(secde; mescid)* · ذكر *(anma, zikir)* · سمو *(ad; gök)* · كثر *(çokluk)* · نصر *(yardım)* · قوي *(kuvvet)* · عزز *(izzet, güç ve üstünlük)* · bağ: xref دفع *(savma)* + اللّه + ناس *(insanlar)* + بعض *(kısım)* → 2:251 · اللّه + نصر *(yardım)* ×2 → 2:214 · غير *(başka)* + حقّ *(hak)* + قال *(söyleme)* → 3:181 ve 41:15 · nakarat ذِكْرُ ٱسْمِ ٱللَّهِ (aday 463)",
}

MERCEK = {
21: "Sûrenin en kısa ayeti: dört kelime, hiç fiil yok, ve tek nesne adı hapaks — مَّقَٰمِعُ *(topuzlar)*, kök قمع *(demir topuz, mıkma)*, korpusta tek geçişli. İkinci isim malzemeyi veriyor: مِنْ حَدِيدٍۢ *(demirden)*. Yani ayet bir eylem değil bir envanter kalemi kuruyor. 22:19-20'nin cümlesi burada üçüncü parçayı alıyor: giysi (ateşten), su (kaynar), alet (demirden).",
22: "Döngü كُلَّمَآ *(ne zaman)* ile kuruluyor: her çıkış girişimi bir geri döndürmeyle karşılanıyor. Fiiller bunu taşıyor: أَرَادُوٓا۟ *(istediler)* PERF ve etken, أُعِيدُوا۟ *(döndürüldüler)* PERF ve edilgen — irade failli, sonuç failsiz. Çıkılmak istenen şey mekân değil hâl: مِنْ غَمٍّ *(o gamdan)*, غمم *(gam, tasa; bürüme)* — sûrede ikinci kez, 22:15'te de vardı. Kapanış bir emirle şahsı 2MP'ye kaydırıyor.",
23: "22:14 ile ilk on üç kelimesi birebir aynı; ayrılma noktası fâsıladan önce. 22:14 soyut bir yetkiyle kapanıyordu (يَفْعَلُ مَا يُرِيدُ *(dilediğini yapar)*), bu ayet somut bir donanımla: أَسَاوِرَ مِن ذَهَبٍۢ *(altın bilezikler)* · لُؤْلُؤًۭا *(inci)* · حَرِيرٌۭ *(ipek)*. Aynı giriş, iki ayrı kapanış — biri iradeye biri nesneye. Süslenme fiili edilgen: يُحَلَّوْنَ *(süslenirler)*, süsleyen anılmıyor.",
24: "Dokuz kelimede iki edilgen ve ikisi de aynı fiil: هُدُوٓا۟ *(iletildiler)* — kök هدي *(yol gösterme)*, ikisi de PERF ve 3MP. Değişen yalnız varış: birincisi bir söze (ٱلطَّيِّبِ مِنَ ٱلْقَوْلِ *(sözün temizi)*), ikincisi bir yola (صِرَٰطِ ٱلْحَمِيدِ *(hamîdin yolu)*). Ayetin i'râbı tamamen mecrur; cümlede bir tane bile mansûb ya da merfû yok. Yani hareket var ama nesne yok: iki ulaşma, iki varış noktası, hiçbir mef'ûl.",
25: "Uzun bir sıfat zinciri açılıyor ama haberi gelmiyor — إِنَّ ٱلَّذِينَ كَفَرُوا۟ … *(inkâr edenler…)* diye başlayan cümle tamamlanmadan ikinci bir cümleye geçiyor (وَمَن يُرِدْ *(kim dilerse)*). Bu bir ölçüm: ayetin on GEN'i tek bir uzun terkip zinciri kuruyor. Arada bir eşitlik hükmü var: سَوَآءً ٱلْعَٰكِفُ فِيهِ وَٱلْبَادِ *(orada yerleşik olan da dışarıdan gelen de eşit)* — عكف *(başında durma, ikâf)* kökü sûre 21:52'de putların başında durmak içindi, burada Mescid'de bulunmak için. Aynı kök, iki karşıt bağlam.",
26: "Aynı kök iki kez ve iyeliği değişiyor: مَكَانَ ٱلْبَيْتِ *(Ev'in yeri)* — belirli ama sahipsiz; بَيْتِىَ *(evim)* — 1S iyelik. Yer önce tarif ediliyor, sonra sahiplenilerek emir veriliyor. Emir de ikili: bir yasak (لَّا تُشْرِكْ بِى شَيْـًۭٔا *(bana hiçbir şeyi ortak koşma)*) ve bir buyruk (وَطَهِّرْ *(temizle)*). Temizlenecek olanın kimler için olduğu üç ism-i fâille sayılıyor: طَآئِفِين *(tavaf edenler)* · قَآئِمِين *(kıyama duranlar)* · رُكَّعِ ٱلسُّجُودِ *(rükû ve secde edenler)* — üçü de duruş adı, üçü de GEN.",
27: "İlân ve varış tek cümlede zincirleniyor: أَذِّن *(ilân et)* IMPV, يَأْتُوكَ *(sana gelsinler)* cevap. Geliş iki kiple veriliyor: رِجَالًۭا *(yaya olarak)* hâl ve çoğul eril; وَعَلَىٰ كُلِّ ضَامِرٍۢ *(her zayıf binek üstünde)* mecrur. İkinci fiil dişil çoğul: يَأْتِينَ *(gelirler)* 3FP — yani ikinci gelişin öznesi insanlar değil BİNEKLER. Uzaklık iki hapaksla ölçülüyor: ضمر *(zayıflamış (deve))* yolun bedende bıraktığı iz, عمق *(derinlik, uzaklık)* yolun kendisi. İki hapaks, biri sonuç biri sebep.",
28: "Amaç iki fiille veriliyor ve ikisi de لِـ ile: لِّيَشْهَدُوا۟ *(tanık olsunlar)* ve وَيَذْكُرُوا۟ *(ansınlar)*. Birincisinin nesnesi belirsiz bırakılıyor — مَنَٰفِعَ لَهُمْ *(kendileri için yararlar)*, hangi yararlar söylenmiyor. İkincisininki tam belirli: ٱسْمَ ٱللَّهِ *(Allah'ın adı)*. Kapanış şahsı 3MP'den 2MP'ye kaydırıyor ve iki emir veriyor: yemek ve yedirmek. Yedirilecek kişi iki sıfatla: ٱلْبَآئِسَ ٱلْفَقِيرَ *(darda kalmış yoksul)*.",
29: "Üç lâmü'l-emr art arda — sûre 22'de ikinci kez (öteki 22:15). Ama işlev tam ters: 22:15'te zincir yapılamayacak bir işi buyuruyordu, burada yapılacak bir ibadeti sıralıyor. Üç fiil üç ayrı babdan: يَقْضُوا۟ bab I, يُوفُوا۟ bab IV, يَطَّوَّفُوا۟ bab V. Ortadaki nesne hapaks: تَفَثَهُمْ *(kirleri)*, kök تفث korpusta tek geçişli ve komşuluk katmanı hiçbir şey vermiyor — kelimenin karşılığı metinden ölçülemiyor.",
30: "İki ayet arayla tekrarlanacak bir kalıpla açılıyor: ذَٰلِكَ وَمَن يُعَظِّمْ *(işte böyle; kim yüceltirse)*. Yüceltilecek olan burada حُرُمَٰتِ ٱللَّهِ *(Allah'ın haram kıldıkları)*, 22:32'de شَعَٰٓئِرَ ٱللَّهِ *(Allah'ın işaretleri)* olacak. Aynı fiil, iki nesne. İkinci yarı bir izin ve iki yasak taşıyor; iki yasak aynı fiille: ٱجْتَنِبُوا۟ *(kaçının)* iki kez, biri nesneye (ٱلرِّجْسَ مِنَ ٱلْأَوْثَٰنِ *(putların pisliği)*) biri söze (قَوْلَ ٱلزُّورِ *(yalan söz)*).",
31: "Ayet bir benzetme kuruyor ve benzetmenin iki kolu var, ikisi de düşüşle başlıyor: خَرَّ مِنَ ٱلسَّمَآءِ *(gökten düştü)*. Sonra iki ayrı son: ya فَتَخْطَفُهُ ٱلطَّيْرُ *(kuşlar kapar)* — canlı ve seçici, ya تَهْوِى بِهِ ٱلرِّيحُ *(rüzgâr sürükler)* — cansız ve rastgele. İkisi de aynı düşüşten çıkıyor. Fâsıla mesafeyi veriyor: مَكَانٍۢ سَحِيقٍۢ *(uzak bir yer)*, سحق *(uzaklık; ezip un etme)*.",
32: "22:30 ile ilk dört kelimesi birebir aynı. Fark nesnede ve sonuçta: orada yüceltmenin karşılığı bir yarar (خَيْرٌۭ لَّهُۥ *(kendisi için hayır)*), burada bir konum (مِن تَقْوَى ٱلْقُلُوبِ *(kalplerin takvâsından)*). Yani biri sonucu, öteki kaynağı veriyor. Fâsıla harfi ب — sûrenin 78 ayetinden yalnız ikisi bu sınıfta.",
33: "Fiilsiz ayet: on bir kelime, sıfır fiil. İki cümle de isim cümlesi ve ikisi de bir sınır çiziyor — biri zamanda (إِلَىٰٓ أَجَلٍۢ مُّسَمًّۭى *(belirli bir süreye kadar)*), biri mekânda (إِلَى ٱلْبَيْتِ ٱلْعَتِيقِ *(Eski Ev'e)*). Aynı harf-i cer إِلَىٰ iki kez, iki ayrı boyutta. Fâsıla 22:29'unkiyle aynı terkip.",
34: "İbadet biçimi çoğullaştırılıyor: وَلِكُلِّ أُمَّةٍۢ جَعَلْنَا مَنسَكًۭا *(her ümmet için bir kurban ibadeti kıldık)* — yani biçim değişken, amaç sabit (ذِكْرُ ٱسْمِ ٱللَّهِ). Sonra çokluktan tekliğe geçiliyor: فَإِلَٰهُكُمْ إِلَٰهٌۭ وَٰحِدٌۭ *(ilâhınız tek bir ilâhtır)* — 22:108'in cümlesi burada aynen. Kök أله ayette üç kez: biri lafız, ikisi 'ilâh'. Kapanış müjde ve muhatap: ٱلْمُخْبِتِينَ *(alçakgönüllüler)*, خبت *(alçakgönüllü olma, ihbât)*.",
35: "Bir önceki ayetin muhatabı burada dört sıfatla tanımlanıyor ve dördü de farklı dilbilgisi kalıbında: bir şart cümlesi (إِذَا ذُكِرَ ٱللَّهُ وَجِلَتْ قُلُوبُهُمْ *(Allah anıldığında kalpleri ürperir)*), bir ism-i fâil çoğul (ٱلصَّٰبِرِينَ *(sabredenler)*), bir izafet (ٱلْمُقِيمِى ٱلصَّلَوٰةِ *(namazı kılanlar)*), bir fiil (يُنفِقُونَ *(infak ederler)*). Tek sınıf, dört ayrı sözdizimi. Anma edilgen: ذُكِرَ, anan anılmıyor.",
36: "Hayvan iki duruşla izleniyor ve ikisi de tek kelimeyle: صَوَآفَّ *(saf hâlde)* — ayakta ve dizili; وَجَبَتْ جُنُوبُهَا *(yanları düştü)* — yerde. وجب *(düşüp yere yıkılma; gerekli olma)* korpusta hapaks. Aradaki geçişte hiçbir fiil yok; iki hâl adı yan yana konuyor ve fark فَإِذَا *(olduğunda)* ile işaretleniyor. Emirler duruşlara bağlanıyor: ilki ayaktayken (ذكر *(anma, zikir)*), ikincisi yerdeyken (yemek ve yedirmek). Kapanış سخر *(boyun eğdirme)* ile — sûre 21:79'da aynı fiil dağlar ve kuşlar içindi.",
37: "Aynı fiil iki kez ve özneleri karşıt: لَن يَنَالَ ٱللَّهَ لُحُومُهَا وَلَا دِمَآؤُهَا *(etleri ve kanları ulaşmaz)* — olumsuz, özne madde; وَلَٰكِن يَنَالُهُ ٱلتَّقْوَىٰ مِنكُمْ *(ama sizden takvâ ulaşır)* — olumlu, özne bir hâl. نيل *(erişme, nail olma)* kökü ikisini de taşıyor; ayrım fiilde değil öznede. Ölçülebilir bir asimetri: olumsuz tarafta iki somut isim (لحم *(et)* ve دمو *(kan)*), olumlu tarafta tek soyut isim.",
38: "On üç kelimede lafız iki kez ve ikisi de إِنَّ ile — bloğun en yüksek lafız yoğunluğu. İki cümle iki yönde: biri olumlu ve savunma (يُدَٰفِعُ عَنِ ٱلَّذِينَ ءَامَنُوٓا۟ *(iman edenleri savunur)*, bab III), öteki olumsuz ve red (لَا يُحِبُّ *(sevmez)*). Sevilmeyen taraf iki ism-i mübalağayla: خَوَّانٍۢ كَفُورٍ *(çok hain, çok nankör)* — ikisi de yoğunluk kalıbı, yani reddedilen şey davranışın kendisi değil süreklileşmiş biçimi. Aynı ayrımı 22:10'da ظَلَّٰم *(çok zulmedici)* ile görmüştük.",
39: "On kelimede üç edilgen: أُذِنَ *(izin verildi)* · يُقَٰتَلُونَ *(kendilerine savaş açılır)* · ظُلِمُوا۟ *(zulme uğradılar)*. Üçünün de faili anılmıyor. İzin verenin kim olduğu ancak ikinci cümlede lafızla ortaya çıkıyor. Edilgenlerin sırası bir mantık taşıyor: önce izin, sonra izne konu olan durum, sonra izni gerektiren sebep — yani sıralama zaman değil gerekçe sırası. Kapanış tek te'kidle: لَقَدِيرٌ.",
40: "Okumada görülen en bağlantılı ayet (dış düğüm 9) ve en yoğun lafız yığılması (beş geçiş). Yapı üç katmanlı. Birincisi bir gerekçe: çıkarılmanın tek sebebi bir söz — إِلَّآ أَن يَقُولُوا۟ رَبُّنَا ٱللَّهُ *(Rabbimiz Allah demelerinden başka)*, HASR. İkincisi bir varsayım: وَلَوْلَا دَفْعُ ٱللَّهِ *(Allah'ın savması olmasaydı)* ve sonucu dört yapı adı — صَوَٰمِعُ *(manastırlar)* · بِيَعٌۭ *(kiliseler)* · صَلَوَٰتٌۭ *(havralar)* · مَسَٰجِدُ *(mescitler)*; ikisi hapaks, dördü de NOM ve tek edilgen fiile bağlı (لَّهُدِّمَتْ *(yıkılırdı)*). Dördünü tek bir nitelik birleştiriyor: يُذْكَرُ فِيهَا ٱسْمُ ٱللَّهِ كَثِيرًۭا *(içlerinde Allah'ın adı çokça anılır)* — sûrenin nakaratı burada edilgen biçimde. Üçüncüsü karşılıklılık: وَلَيَنصُرَنَّ ٱللَّهُ مَن يَنصُرُهُۥ *(kendisine yardım edene yardım eder)*, aynı kök iki kez, iki yönde.",
}

BIYOLOG = {
27: "Çıpa: ضَامِرٍۢ *(zayıflamış binek)*, kök ضمر — korpusta HAPAKS. Ölçülebilir olanlar: (a) Kelime bir hayvanı adlandırmıyor, hayvanın DURUMUNU adlandırıyor — ism-i fâil, 'zayıflamış olan'. Ayette hayvanın türü hiç geçmiyor. (b) Cümlenin ikinci fiili dişil çoğul: يَأْتِينَ *(gelirler)* 3FP; ilk fiil ise eril çoğul يَأْتُوكَ *(sana gelirler)* 3MP. Yani aynı geliş iki kez anlatılıyor ve ikincisinin öznesi insanlar değil binekler — dilbilgisi hayvana ayrı bir fâillik veriyor. (c) İki geliş biçimi karşıtlanıyor: رِجَالًۭا *(yaya)* ve binekli; ilki kök رجل *(adam; yaya)* ile, yani yürüyüş de bir beden terimiyle adlandırılıyor. (d) Zayıflama bir sebeple eşleşiyor ve o sebep ikinci hapaks: مِن كُلِّ فَجٍّ عَمِيقٍۢ *(her uzak geçitten)*, عمق *(derinlik, uzaklık)*. **Ölçüm sınırı:** ayet ne türü, ne süreyi, ne mesafeyi veriyor; ölçülebilen tek şey, yolun bedende bıraktığı izin bir hapaksla adlandırılması ve fiil uyumunun hayvana geçmesi.",
36: "Çıpa: صَوَآفَّ *(saf hâlde)* ve وَجَبَتْ جُنُوبُهَا *(yanları düştü)*. Ölçülebilir olanlar: (a) Hayvanın hâli iki DURUŞ adıyla veriliyor, hiçbir eylem fiiliyle değil — biri ayakta ve dizili (صفف *(saf tutma, sıra)*, korpusta 14 geçiş ve komşuluk profili ağırlıkla melekler ve saf tutma), öteki yerde (جنب *(yan, taraf)*, 33 geçiş). İki hâl arasındaki geçiş anlatılmıyor; yalnız فَإِذَا *(olduğunda)* ile işaretleniyor. (b) Geçişi bildiren fiil hapaks: وجب *(düşüp yere yıkılma; gerekli olma)*, korpusta tek geçiş, komşuluk katmanı boş. (c) İnsan eylemleri hayvanın duruşuna bağlanıyor: ayaktayken anma, yerdeyken yeme ve yedirme — yani ölçüt hayvanın konumu. (d) Kapanış fiili سخر *(boyun eğdirme)*; aynı fiil 21:79'da dağlar ve kuşlar için kullanılmıştı, yani korpus cansız, canlı ve kurbanlığı aynı fiile bağlıyor. **Ölçüm sınırı:** ayet hiçbir fizyolojik süreç tarif etmiyor; ölçülebilen tek şey, hayvanın iki duruş adıyla izlenmesi ve aradaki geçişin hapaks bir fiile bırakılması.",
}

om = json.load(open('okuma_metni.json', encoding='utf-8'))
mk = json.load(open('mercek_kayit.json', encoding='utf-8'))

for n in range(21, 41):
    key = "22:%d" % n
    om['22'][key] = {'ar': AR[(22, n)], 'meal': MEAL[n], 'olcum': OLCUM[n],
                     'mercek': MERCEK[n], 'dikey': DIK[key]}
    if BIYOLOG.get(n): om['22'][key]['biyolog'] = BIYOLOG[n]
    mk['22'].append([key, MERCEK[n]])
for n, t in BIYOLOG.items():
    mk['22_biyolog'].append(["22:%d" % n, t])

om['22']['_mercek_atlama_notu'] += (
 " 22:21 biyolog ve uzay ATLANDI (قمع *(demir topuz, mıkma)* ve حدد *(demir; sınır koyma)*; "
 "canlılık ya da gök çıpası yok — demirin kozmik kökeni ayetin KENDİ malzemesi değil, zorlama olurdu). "
 "22:24 biyolog ve uzay ATLANDI. "
 "22:27 biyolog YAZILDI (ضمر *(zayıflamış (deve))* hapaksı ve 3FP fiil uyumu); uzay ATLANDI "
 "(عمق *(derinlik, uzaklık)* mesafe bildiriyor ama gök öğesi değil). "
 "22:29 biyolog ve uzay ATLANDI — تفث *(hac kirini giderme, tefes)* bedene ait olabilir ama korpus "
 "kelimeye hiçbir bağlam vermiyor (hapaks, komşuluk boş); ölçülecek malzeme yok. "
 "22:36 biyolog YAZILDI (صفف *(saf tutma, sıra)* / جنب *(yan, taraf)* duruş çifti ve وجب hapaksı); uzay ATLANDI. "
 "22:39 biyolog ve uzay ATLANDI. "
 "22:40 biyolog ve uzay ATLANDI (yapı adları ve yardım; ne canlılık ne gök çıpası).")

om['ilerleme']['kismi']['22'] = "1-40 ayet düzeyinde"
om['ilerleme']['bekleyen']['22'] = "41-78"
om['ilerleme']['not'] = ("Sûre 20 TAM. Sûre 21 TAM (112/112). Sûre 22 (Hac) makro + 22:1-40. "
                         "Devam: 22:41. Dikey katman A parçası birincil, B etiketsiz.")
om['ilerleme']['okunan_ayet'] = 1425

json.dump(om, open('okuma_metni.json', 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
json.dump(mk, open('mercek_kayit.json', 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
print("yazıldı · mercek 22:", len(mk['22']), "· biyolog:", len(mk['22_biyolog']))
