# -*- coding: utf-8 -*-
"""blok_22_61_78.py — Hac'ın kapanış bloğu + sûre kapanış kaydı."""
import json

DIK = json.load(open('blok_dikey_22_61_78.json', encoding='utf-8'))
veri = json.load(open('kuran_veri.json', encoding='utf-8'))
AR = {}
for s in veri['sureler']:
    for a in s['ayetler']:
        AR[(s['no'], a['no'])] = a['ar']

MEAL = {
61: "Bu böyledir; çünkü Allah geceyi gündüze, gündüzü de geceye katar. Allah işitendir, görendir.",
62: "Bu böyledir; çünkü Allah hakkın kendisidir; O'nu bırakıp çağırdıkları ise bâtılın kendisidir. Allah yücedir, büyüktür.",
63: "Görmedin mi, Allah gökten bir su indirdi de yer yemyeşil oluverdi. Allah lütuf sahibidir, haberdardır.",
64: "Göklerde ve yerde ne varsa O'nundur. Allah zengindir, övgüye lâyıktır.",
65: "Görmedin mi, Allah yerdekileri ve buyruğuyla denizde akıp giden gemileri size boyun eğdirdi; göğü de, izni olmadıkça yerin üzerine düşmesin diye tutuyor. Allah insanlara karşı çok şefkatlidir, çok merhametlidir.",
66: "Sizi dirilten, sonra öldüren, sonra yine diriltecek olan O'dur. İnsan gerçekten çok nankördür.",
67: "Her ümmet için, uyguladıkları bir kurban ibadeti kıldık. Öyleyse bu iş hakkında seninle çekişmesinler. Sen Rabbine çağır. Sen elbette dosdoğru bir hidayet üzeresin.",
68: "Seninle tartışırlarsa de ki: Yaptıklarınızı en iyi Allah bilir.",
69: "Ayrılığa düştüğünüz şeyler hakkında Allah kıyamet günü aranızda hükmedecektir.",
70: "Bilmedin mi, Allah gökte ve yerde olanı bilir. Bu bir kitaptadır. Bu Allah'a kolaydır.",
71: "Allah'ı bırakıp, hakkında hiçbir delil indirmediği ve kendilerinin de bir bilgisi olmadığı şeylere tapıyorlar. Zalimler için hiçbir yardımcı yoktur.",
72: "Kendilerine apaçık âyetlerimiz okunduğunda, inkâr edenlerin yüzlerinde hoşnutsuzluğu tanırsın; neredeyse âyetlerimizi onlara okuyanların üzerine saldıracaklar. De ki: Size bundan daha kötüsünü haber vereyim mi? Ateş! Allah onu inkâr edenlere vaat etti. Ne kötü bir varış!",
73: "Ey insanlar, bir mesel verildi; onu dinleyin. Allah'ı bırakıp çağırdıklarınız, bir araya gelseler bile bir sinek yaratamazlar. Sinek onlardan bir şey kapsa, onu ondan kurtaramazlar. İsteyen de âciz, istenen de.",
74: "Allah'ı gereği gibi takdir edemediler. Allah gerçekten güçlüdür, üstündür.",
75: "Allah meleklerden de insanlardan da elçiler seçer. Allah işitendir, görendir.",
76: "Önlerindekini de arkalarındakini de bilir. İşler Allah'a döndürülür.",
77: "Ey iman edenler, rükû edin, secde edin, Rabbinize kulluk edin ve hayır işleyin ki kurtuluşa eresiniz.",
78: "Allah uğrunda hakkıyla cihad edin. O sizi seçti ve dinde size hiçbir zorluk yüklemedi — babanız İbrâhim'in dini. O, daha önce de bunda da size müslümanlar adını verdi; elçi size şahit olsun, siz de insanlara şahit olun diye. Öyleyse namazı kılın, zekâtı verin ve Allah'a sarılın. O sizin mevlânızdır. Ne güzel mevlâ, ne güzel yardımcı!",
}

OLCUM = {
61: "eksen: **Allah lafzı İKİ geçiş — 3. ve 13. sırada** (allah z=2,14; kök ikilemesi أله *(ilâh; lafza-i celâl)* ×2) · **esmâ MÜHÜR ÇİFTİ: سَمِيع|بَصِير *(semî'|basîr)* 14. ve 15. sırada — yedi ardışık mühürün üçüncüsü**; ikisi de geçerli · aktör yok · edim haber · şahıs 3MS ×2 · n=15 mora=77 harf=60, fâsıla بَصِيرٌۭ → ر, R sınıfı; i'râb ACC 6 · GEN 2 · NOM 2; bab IV ×2; **kök ikilemesi DÖRT ayrı kök: أله ×2 · ولج *(girme, girdirme)* ×2 · ليل *(gece)* ×2 · نهر *(ırmak; gündüz)* ×2**; simetri [3,2,6,1] · yıldız ★★ · kökler أله *(ilâh; lafza-i celâl)* · ولج *(girme, girdirme)* · ليل *(gece)* · نهر *(ırmak; gündüz)* · سمع *(işitme)* · بصر *(görme, basiret)* · bağ: xref اللّه + يولج + ليل → **31:29**; **21:20 · 21:33 · 21:42 ile ليل/نهر çiftinin dördüncü rolü** — burada karşılıklı mef'ûl (aday 445)",
62: "eksen: **Allah lafzı İKİ geçiş — 3. ve 14. sırada** (allah z=1,82) · **esmâ MÜHÜR ÇİFTİ: عَلِيّ|كَبِير *(alî|kebîr)* 16. ve 17. sırada**; ikisi de geçerli — **NOT: كَبِير burada GEÇERLİ, oysa 20:71 · 21:58 · 21:63'te yanlış pozitifti** · aktör yok · edim haber · şahıs 3MS ×4 · 3MP ×2 · n=17 mora=74 harf=60, fâsıla ٱلْكَبِيرُ → ر, R sınıfı; i'râb ACC 5 · NOM 4 · GEN 1; bab I ×1 (tek fiil); simetri [4,1,6,1] · yıldız ★ · kökler أله · حقق *(hak, gerçek)* · دعو *(çağırma, dua)* · دون *(beriki, başkası)* · بطل *(bâtıl, boş)* · علو *(yücelik, üstünlük)* · كبر *(büyüklük; büyüklenme)* · bağ: **xref BEŞ 3-gram, hepsi 31:30'a** (+40:12); 22:6 ile aynı ٱللَّهَ هُوَ ٱلْحَقُّ *(Allah hakkın kendisidir)* cümlesi (elle, L1)",
63: "eksen: **Allah lafzı İKİ geçiş — 4. ve 13. sırada** (allah z=2,14) · **esmâ MÜHÜR ÇİFTİ: لَطِيف|خَبِير *(latîf|habîr)*** · aktör yok · edim soru, kip INTG 1 · NEG 1 · şahıs 2MS 1 · 3MS 1 · 3FS 1 · n=15 mora=75 harf=58, fâsıla خَبِيرٌۭ → ر, R sınıfı; i'râb ACC 6 · GEN 1 · NOM 3; bab I ×1 · bab IV ×2; simetri [3,3,12,1]; dış düğüm 3 · yıldız ★★ · kökler رأي *(görme)* · أله · نزل *(indirme)* · سمو *(ad; gök)* · موه *(su)* · صبح *(sabah; olmak (asbaha))* · أرض *(yer, yeryüzü)* · خضر *(yeşillik)* · لطف *(lütuf, incelik)* · خبر *(haber; haberdar olma)* · bağ: xref رأى + اللّه + أنزل → 35:27 ve 39:21 · اللّه + لطيف + خبير → **31:16**; **22:5 ile ortak dizi** — su iner, yer canlanır (elle, L1)",
64: "eksen: **Allah lafzı 9. sırada** (allah z=1,14) · **esmâ MÜHÜR ÇİFTİ: غَنِيّ|حَمِيد *(ganî|hamîd)*** · aktör yok · edim haber, kip EMPH 1 · şahıs 3MS ×2 · n=12 mora=55 harf=45, fâsıla ٱلْحَمِيدُ → د, د sınıfı; i'râb GEN 2 · ACC 2 · NOM 2; **fiil yok — sûrenin dördüncü fiilsiz ayeti** (21, 33, 43, 64); simetri [3,1,5,1] · kökler سمو *(ad; gök)* · أرض *(yer, yeryüzü)* · أله · غني *(zenginlik, ganî olma)* · حمد *(hamd, övgü)* · bağ: xref أرض + اللّه + غنيّ → **31:26**",
65: "eksen: **Allah lafzı İKİ geçiş — 4. ve 24. sırada** (allah z=0,95; kök ikilemesi أله ×2) · **esmâ MÜHÜR ÇİFTİ: رَءُوف|رَحِيم *(raûf|rahîm)* — yedi ardışık mühür kümesinin SONUNCUSU** · aktör yok · edim soru, kip INTG 1 · NEG 1 · RES 1 · EMPH 1 · şahıs 2MS 1 · 3MS ×4 · 2MP 1 · 3FS ×2 · **n=27 mora=127 harf=106 — bloğun en uzun ikinci ayeti**, fâsıla رَّحِيمٌۭ → م, N sınıfı; i'râb ACC 6 · GEN 6 · NOM 2; bab I ×3 · bab II ×1 · bab IV ×1; kök ikilemesi أرض *(yer, yeryüzü)* ×2; biçim HASR; simetri [4,1,21,1]; dış düğüm 3 · yıldız ★ · kökler رأي · أله · سخر *(boyun eğdirme)* · أرض · فلك *(gemi, felek)* · جري *(akma, koşma)* · بحر *(deniz)* · أمر *(emir; iş)* · مسك *(tutma, alıkoyma)* · سمو *(ad; gök)* · وقع *(düşme, vuku bulma)* · أذن *(izin; bildirme; kulak)* · أنس *(insan)* · رأف *(şefkat, raafet)* · رحم *(rahmet, merhamet)* · bağ: xref اللّه + ناس + رءوف + رحيم → 2:143 · جري + بحر + أمر → 14:32 · رأى + اللّه + سخّر → **31:20**; **21:33 ile ortak فلك *(gemi, felek)*** — orada gök cisimlerinin yörüngesi, burada deniz gemisi (elle, L2)",
66: "eksen yok · aktör yok · edim haber, kip EMPH 1 · şahıs 3MS ×4 · 2MP ×3 · n=10 mora=57 harf=44, fâsıla كَفُورٌۭ *(nankör)* → ر, R sınıfı (kafiye kırılması işaretli); i'râb ACC 2 · NOM 1; **bab IV ×3 — üç fiil, üçü de bab IV**; kök ikilemesi حيي *(diri olma, hayat)* ×2 — biri PERF biri IMPF, arada موت *(ölüm)*; simetri [4,2,6,1] · yıldız ★ · kökler حيي *(diri olma, hayat)* · موت *(ölüm)* · أنس *(insan)* · كفر *(inkâr, nankörlük)* · bağ: xref أحيا + أمات + أحيا → 2:28; 22:6 ile ortak حيي/موت çifti (elle, L2)",
67: "eksen: lafız yok · Rab 13. sırada, إِلَىٰ رَبِّكَ *(Rabbine)* (rab z=0,93) · aktör yok · edim emir, kip NEG 1 · EMPH 2 · IMPV 1 · şahıs 1P ×2 · 3MP 1 · 3MS ×2 · 2MS ×4 · n=17 mora=93 harf=72, fâsıla مُّسْتَقِيمٍۢ *(dosdoğru)* → م, N sınıfı; i'râb GEN 6 · ACC 2 · NOM 1; bab I ×2 · bab III ×1; kök ikilemesi نسك *(kurban ibadeti, nüsük)* ×2 — biri mef'ûl biri ism-i fâil; simetri [3,5,12,1] · kökler كلل *(hep, bütün)* · أمم *(önder, imam; ümmet)* · جعل *(kılma, var etme)* · نسك *(kurban ibadeti, nüsük)* · نزع *(çekip alma; çekişme)* · أمر *(emir; iş)* · دعو *(çağırma, dua)* · ربب *(rab, terbiye etme)* · هدي *(yol gösterme)* · قوم *(kalkma; kavim; kıyamet)* · bağ: **22:34 ile bölüt ikizi** — لِكُلِّ أُمَّةٍۢ جَعَلْنَا مَنسَكًۭا *(her ümmet için bir menâsik kıldık)*, 33 ayet arayla (elle, L1)",
68: "eksen: **Allah lafzı 4. sırada** (allah z=2,33) · aktör yok · edim emir + şart, kip COND 1 · IMPV 1 · şahıs 3MP ×2 · 2MS ×2 · 2MP ×2 · **n=7 mora=35 harf=28 — bloğun en kısa ayeti**, fâsıla تَعْمَلُونَ *(yaparsınız)* → ن, N sınıfı; i'râb NOM 2; bab I ×2 · bab III ×1; **zaman PERF 1 · IMPV 1 · IMPF 1 — üç fiil, üç ayrı zaman** · yıldız ★★ · kökler جدل *(tartışma, cedel)* · قول *(söz söyleme)* · أله · علم *(bilme)* · عمل *(iş, amel)* · bağ: xref قال + اللّه + أعلم → 18:26; **22:3 · 22:8 ile üçüncü kez جدل** — orada tartışanlar üçüncü şahıstı, burada muhatap (elle, L1)",
69: "eksen: **Allah lafzı 1. sırada — ayetin İLK kelimesi** (allah z=1,69) · aktör yok · edim haber · şahıs 3MS ×2 · 2MP ×5 · n=9 mora=48 harf=40, fâsıla تَخْتَلِفُونَ *(ayrılığa düşersiniz)* → ن, N sınıfı; i'râb NOM 1 · ACC 2 · GEN 1; bab I ×2 · bab VIII ×1 · yıldız ★ · kökler أله · حكم *(hüküm verme, hikmet)* · بين *(arası; açıklama)* · يوم *(gün)* · قوم *(kalkma; kavim; kıyamet)* · كون *(olmak)* · خلف *(ayrılığa düşme; cayma)* · bağ: **22:17 ile aynı yüklem** — يَفْصِلُ / يَحْكُمُ بَيْنَهُمْ يَوْمَ ٱلْقِيَٰمَةِ *(kıyamet günü aralarında ayırır/hükmeder)*, orada altı topluluk arasında burada muhataplar arasında (elle, L1)",
70: "eksen: **Allah lafzı İKİ geçiş — 4. ve 17. sırada** (allah z=1,69; kök ikilemesi أله ×2) · aktör yok · edim soru, kip INTG 1 · NEG 1 · şahıs 2MS 1 · 3MS 1 · n=18 mora=78 harf=62, fâsıla يَسِيرٌۭ *(kolay)* → ر, R sınıfı; i'râb ACC 4 · GEN 4 · NOM 1; bab I ×2; kök ikilemesi علم *(bilme)* ×2 — biri muhatabın bilmesi, öteki lafzın bilmesi; simetri [4,1,14,1] · yıldız ★ · kökler علم · أله · سمو *(ad; gök)* · أرض *(yer, yeryüzü)* · كتب *(yazma, kitap)* · يسر *(kolaylık)* · bağ: xref سماء + أرض + كتاب → 27:75 · كتاب + اللّه + يسير → 35:11; 22:63 · 22:65 ile aynı أَلَمْ تَرَ/تَعْلَمْ *(görmedin/bilmedin mi)* açılışı — **sûrede üçüncü kez** (elle, L1)",
71: "eksen: **Allah lafzı 4. sırada**, مِن دُونِ ٱللَّهِ *(Allah'ı bırakıp)* kalıbında (allah z=0,58) — **sûrede ikinci kez** (öteki 22:12) · **esmâ نَصِير *(yardımcı)* 18. sırada = fâsıla — ÖLÇÜM ARTEFAKTI (aday 444)**: وَمَا لِلظَّٰلِمِينَ مِن نَّصِيرٍۢ *(zalimler için hiçbir yardımcı yok)* — olumsuzlanmış belirsiz isim, ilâhî ad değil · aktör yok · edim haber, kip NEG 2 · şahıs 3MP ×3 · 3MS ×4 · n=18 mora=79 harf=67, fâsıla نَّصِيرٍۢ → ر, R sınıfı; i'râb GEN 4 · ACC 1 · NOM 1; bab I ×2 · bab II ×1; simetri [6,5,12,2] · kökler عبد *(kul, kulluk)* · دون *(beriki, başkası)* · أله · نزل *(indirme)* · سلط *(yetki, delil (sultan))* · ليس *(değil (olumsuzluk))* · علم *(bilme)* · ظلم *(zulüm)* · نصر *(yardım)* · bağ: xref علم + ظالم + نصير → 2:270; **21:66-67 · 22:12 ile aynı kalıp** (elle, L1)",
72: "eksen: **Allah lafzı 25. sırada** (allah z=0,16) · aktör yok · edim soru + emir, kip IMPV 1 · INTG 1 · şahıs **3FS ×2 · 3MP ×12 · 1P ×2 · 2MS ×2 · 1S 1 · 2MP 1 · 3MS ×2 — YEDİ ayrı şahıs kategorisi, sûrenin en dağınık şahıs profili** · **n=29 mora=169 harf=143 — bloğun en uzun ikinci ayeti (n z=1,76)**, fâsıla ٱلْمَصِيرُ *(varış)* → ر, R sınıfı; i'râb NOM 4 · GEN 4 · ACC 1; **bab I ×10** · bab II ×1; edilgen 1 (تُتْلَىٰ *(okunur)*); **hapaks سطو *(saldırma, üzerine yürüme)* (z=3,38)**; kök ikilemesi تلو *(okuma, tilâvet)* ×2 · أيي *(âyet, işaret)* ×2 · كفر *(inkâr, nankörlük)* ×2; simetri [6,1,14,2] · yıldız ★★★ · kökler تلو · أيي · بين *(arası; açıklama)* · عرف *(tanıma, maruf)* · وجه *(yüz, yön)* · كفر · نكر *(tanımama, inkâr; münker)* · كود *(neredeyse olma)* · سطو *(saldırma, üzerine yürüme)* · قول *(söz söyleme)* · نبأ *(haber; nebî)* · شرر *(şer, kötülük)* · نور *(nûr, ışık; ateş)* · وعد *(vaat)* · بأس *(şiddet, azap; ne kötü)* · صير *(varış, dönüş)* · bağ: xref قال + نبّأ + شرّ → 5:60; 22:48 ile aynı fâsıla ٱلْمَصِيرُ (elle, L2)",
73: "eksen: **Allah lafzı 12. sırada**, مِن دُونِ ٱللَّهِ kalıbında (allah z=0,19) — sûrede üçüncü kez · aktör yok · edim emir + nida + şart, kip VOC 1 · IMPV 1 · NEG 2 · COND 2 · şahıs 3MS ×7 · 2MP ×4 · 3MP ×7 · **n=28 mora=156 harf=132 — bloğun en uzun üçüncü ayeti (n z=1,65)**, **fâsıla ٱلْمَطْلُوبُ *(istenen)* → ب, ب sınıfı — sûrede yalnız iki ayet** (öteki 22:32); i'râb ACC 4 · NOM 5 · GEN 2; bab I ×5 · bab VIII ×2 · bab X ×1; edilgen 1 (ضُرِبَ *(verildi)*); **hapaks سلب *(kapıp alma)* (z=3,38)**; kök ikilemesi ذبب *(sinek)* ×2 ve طلب *(isteme, talep)* ×2; biçim DIKKAT; simetri [3,6,16,1] · yıldız ★★★ · kökler أيي *(hangi; âyet)* · أنس *(insan)* · ضرب *(vurma; mesel getirme)* · مثل *(benzer, misil; heykel)* · سمع *(işitme)* · دعو *(çağırma, dua)* · دون *(beriki, başkası)* · أله · خلق *(yaratma)* · ذبب *(sinek)* · جمع *(toplama)* · سلب *(kapıp alma)* · شيأ *(dileme; şey)* · نقذ *(kurtarma, kurtarıp alma)* · ضعف *(kat; zayıflık)* · طلب *(isteme, talep)* · bağ: xref دون + اللّه + خلق → 16:20",
74: "eksen: **Allah lafzı İKİ geçiş — 3. ve 7. sırada; n=9'da iki lafız → allah z=3,92: SÛRENİN VE OKUMANIN EN YÜKSEK LAFIZ YOĞUNLUĞU**; kök ikilemesi أله ×2 · **esmâ MÜHÜR ÇİFTİ: قَوِيّ|عَزِيز — 22:40'ın mühürüyle AYNI ÇİFT**; ikisi de geçerli · aktör yok · edim haber, kip NEG 1 · EMPH 1 · şahıs 3MP ×2 · 3MS 1 · n=9 mora=45 harf=34, fâsıla عَزِيزٌ → ز, ز sınıfı — sûrede yalnız iki ayet (öteki 22:40); i'râb ACC 4 · GEN 1 · NOM 2; bab I ×1 (tek fiil); kök ikilemesi قدر *(ölçü, takdir; güç)* ×2 — biri fiil biri masdar (مَا قَدَرُوا۟ … حَقَّ قَدْرِهِۦ *(takdir edemediler… hakkıyla takdirini)*) · yıldız ★★★ · kökler قدر · أله · حقق *(hak, gerçek)* · قوي *(kuvvet)* · عزز *(izzet, güç ve üstünlük)* · bağ: xref قدر + اللّه + حقّ → 6:91 ve 39:67; **22:40 ile mühür ikizi ve fâsıla sınıfı ikizi** (elle, L1)",
75: "eksen: **Allah lafzı İKİ geçiş — 1. ve 9. sırada; ayetin İLK kelimesi lafız (allah z=3,11 — sûrenin ikinci en yüksek yoğunluğu)** · **esmâ MÜHÜR ÇİFTİ: سَمِيع|بَصِير — 22:61'in mühürüyle AYNI ÇİFT** · aktör yok — مَلَٰٓئِكَة *(melekler)* aktör tablosuna girmiyor · edim haber · **şahıs 3MS 1 — ayette tek şahıs** · n=11 mora=60 harf=48, fâsıla بَصِيرٌۭ → ر, R sınıfı; i'râb NOM 3 · GEN 2 · ACC 3; bab VIII ×1 (tek fiil) · yıldız ★★★ · kökler أله · صفو *(seçme, ıstıfâ; safâ)* · ملك *(melek; mülk, sahiplik)* · رسل *(gönderme, elçi)* · أنس *(insan)* · سمع *(işitme)* · بصر *(görme, basiret)* · bağ: xref ناس + اللّه + سميع → 2:224; **22:61 ile mühür ikizi** (elle, L1)",
76: "eksen: **Allah lafzı 8. sırada** (allah z=1,47) · aktör yok · edim haber · şahıs 3MS 1 · 3MP ×2 · 3FS 1 · n=10 mora=49 harf=42, fâsıla ٱلْأُمُورُ *(işler)* → ر, R sınıfı — 22:41'in fâsılasıyla aynı kelime; i'râb ACC 2 · NOM 2 · GEN 1; bab I ×2; **edilgen 1 — n=10'da tek edilgen, z=2,52** · yıldız ★★ · kökler علم *(bilme)* · بين *(arası; açıklama)* · يدي *(el)* · خلف *(ayrılığa düşme; arka)* · أله · رجع *(dönme, geri döndürme)* · أمر *(emir; iş)* · bağ: **21:28 ile bölüt ikizi** — يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ *(önlerindekini ve arkalarındakini bilir)* birebir aynı; orada meleklerin bilgisi bağlamında, burada elçi seçiminin ardından (elle, L1)",
77: "eksen: lafız yok · Rab 7. sırada, رَبَّكُمْ *(Rabbiniz)* (**rab z=1,62 — bloğun en yüksek Rab yoğunluğu**) · aktör yok · edim emir + nida, kip VOC 1 · **IMPV 4** · şahıs 3MP ×2 · **2MP ×12** · n=11 mora=76 harf=69, fâsıla تُفْلِحُونَ *(kurtuluşa erersiniz)* → ن, N sınıfı (kafiye kırılması işaretli); **i'râb ACC 4 — tamamı mansûb**; bab I ×4 · bab IV ×2; biçim DIKKAT; **ayet secde işareti ۩ taşıyor — sûrenin ikinci secdesi (öteki 22:18)** · yıldız ★ · kökler أيي *(hangi; âyet)* · أمن *(güven; iman)* · ركع *(rükû)* · سجد *(secde)* · عبد *(kul, kulluk)* · ربب *(rab, terbiye etme)* · فعل *(yapma, işleme)* · خير *(hayır, daha iyi)* · فلح *(kurtuluş, felâh)* · bağ: **22:26 ile ortak ركع/سجد çifti** — orada İbrâhim'e Ev'i temizleme buyruğunda, burada doğrudan muhataba (elle, L1)",
78: "eksen: **Allah lafzı İKİ geçiş — 3. ve 38. sırada** (allah z=0,38; kök ikilemesi أله ×2) · **esmâ BEŞ token — sûrenin en yoğun esmâ ayeti**: شَهِيد *(şahit)* 27. ve 30., مَوْلَى *(mevlâ)* 40. ve 42., نَصِير *(yardımcı)* 44. sırada; **mühür YOK** (esma_k: muhur=False) · **BAĞLAM DENETİMİ (aday 444): شَهِيد ×2 YANLIŞ POZİTİF** — biri ٱلرَّسُولُ *(elçi)* için biri muhataplar için; مَوْلَى ×2 ve نَصِير geçerli (üçü de Allah'a) · aktör: adlı إِبْراهِيم *(İbrâhim)* 17. sırada (mecrur) ve مُسْلِم *(müslüman)* 20. sırada (mef'ûl, tür 'kavim') — **sûrenin son iki aktörü** · edim emir, kip IMPV 4 · NEG 1 · şahıs **2MP ×16 · 3MS ×10** · **n=44 mora=243 harf=210 — SÛRENİN EN UZUN İKİNCİ AYETİ (n z=3,35), harf bakımından en uzunu** , fâsıla ٱلنَّصِيرُ → ر, R sınıfı; i'râb GEN 11 · ACC 7 · NOM 2; bab I ×5 · bab II ×1 · bab III ×1 · bab IV ×2 · bab VIII ×2 — **beş ayrı bab**; **kök ikilemesi ALTI ayrı kök: جهد *(cihad, çaba harcama)* ×2 · أله ×2 · كون *(olmak)* ×2 · شهد *(şahitlik)* ×2 · ولي *(dost, veli; velâyet)* ×2 · نعم *(nimet; ne güzel)* ×2**; biçim DIKKAT; simetri [4,8,21,1] · yıldız ★★★ · kökler جهد · أله · حقق *(hak, gerçek)* · جبي *(seçip toplama, ictibâ)* · جعل *(kılma, var etme)* · دين *(din; borç)* · حرج *(sıkıntı, darlık)* · ملل *(millet, din; usanma)* · أبو *(baba)* · سمو *(ad; gök)* · سلم *(esenlik; teslim olma)* · قبل *(ön, önce; kabul)* · كون · رسل *(gönderme, elçi)* · شهد · أنس *(insan)* · قوم *(kalkma; kavim; kıyamet)* · صلو *(namaz, salât)* · أتي *(gelme, getirme; verme)* · زكو *(arınma, zekât)* · عصم *(tutunma, korunma)* · ولي · نعم · نصر *(yardım)* · bağ: xref كان + شهيد + ناس → 2:143 · **اللّه + مولى + نعم dizisi DÖRT 3-gram, hepsi 8:40'a**; **22:41 ile ortak صلو/زكو çifti** — orada şartın cevabı, burada doğrudan emir (elle, L1)",
}

MERCEK = {
61: "Dört ayrı kök ikilemesi tek ayette ve ikisi karşılıklı: يُولِجُ ٱلَّيْلَ فِى ٱلنَّهَارِ وَيُولِجُ ٱلنَّهَارَ فِى ٱلَّيْلِ *(geceyi gündüze, gündüzü geceye katar)* — aynı fiil iki kez, ve iki isim yer değiştiriyor. Yani cümle bir simetriyi sözdiziminde gösteriyor: ilk yarının mef'ûlü ikinci yarının mecruru oluyor. ليل *(gece)* / نهر *(ırmak; gündüz)* çifti bu okumada dördüncü rolünü alıyor (21:20 zarf, 21:33 mef'ûl, 21:42 mecrur, burada karşılıklı). Mühür iki duyu adı.",
62: "Ayet iki özdeşlik kuruyor ve ikisi de ayırıcı zamirle: ٱللَّهَ هُوَ ٱلْحَقُّ *(Allah hakkın kendisidir)* ve مَا يَدْعُونَ … هُوَ ٱلْبَٰطِلُ *(çağırdıkları bâtılın kendisidir)*. İki haber karşıt: حقق *(hak, gerçek)* ve بطل *(bâtıl, boş)*. Sonra üçüncü bir özdeşlik ve yine هُوَ ile: mühür çifti. Yani ayette üç kez aynı yapı, üçüncüsü mühre çıkıyor. İlk cümle 22:6'nın birebir tekrarı.",
63: "Soru bir gözleme çağırıyor ve gözlemin iki ucu var: gökten inen su, yerde beliren yeşillik. Aradaki dönüşüm tek fiille: فَتُصْبِحُ *(oluverir)*, صبح *(sabah; olmak (asbaha))* — kök hem 'sabah olmak' hem 'bir hâle gelmek'. Yani değişim bir zaman kelimesiyle anlatılıyor. Renk tek kelimeyle: مُخْضَرَّةً *(yemyeşil)*. Aynı dizi 22:5'in ikinci yarısında da vardı, ama orada dört fiille, burada bir fiille.",
64: "On iki kelime, hiç fiil — sûrenin dördüncü fiilsiz ayeti. Sahiplik tek harf-i cerle açılıyor: لَّهُۥ *(O'nundur)*, ve kapsam iki mekânla veriliyor. Mühür çifti bir yokluk ile bir doluluk: غَنِيّ *(zengin, muhtaç olmayan)* ve حَمِيد *(övgüye lâyık)* — biri almayı reddediyor, öteki vermeyi karşılıyor.",
65: "Üç iş sayılıyor ve üçü de farklı yönde: boyun eğdirme (yerdekiler), akıtma (denizdeki gemiler), tutma (gök). Son işin şartı bir istisnayla veriliyor: أَن تَقَعَ عَلَى ٱلْأَرْضِ إِلَّا بِإِذْنِهِۦٓ *(izni olmadıkça yerin üzerine düşmesin)* — HASR, yani tutma mutlak değil izne bağlı. فلك *(gemi, felek)* kökü 21:33'te gök cisimlerinin yörüngesiydi; burada deniz gemisi. Aynı kök, gökten denize.",
66: "Üç fiil, üçü de bab IV ve üçü aynı kökten değil ama tek diziden: أَحْيَاكُمْ ثُمَّ يُمِيتُكُمْ ثُمَّ يُحْيِيكُمْ *(diriltti, sonra öldürür, sonra diriltir)*. حيي *(diri olma, hayat)* iki kez, arada موت *(ölüm)*. Zaman da diziyi izliyor: PERF → IMPF → IMPF. Kapanış diziye bir hüküm ekliyor ve özneyi değiştiriyor: إِنَّ ٱلْإِنسَٰنَ لَكَفُورٌۭ *(insan gerçekten çok nankördür)* — ism-i mübalağa, yani süreklileşmiş biçim.",
67: "22:34'ün açılışını 33 ayet sonra tekrarlıyor: لِكُلِّ أُمَّةٍۢ جَعَلْنَا مَنسَكًۭا *(her ümmet için bir menâsik kıldık)*. Ama devamı ayrılıyor: orada tevhide, burada çekişmenin yasaklanmasına gidiyor. Aynı kök نسك *(kurban ibadeti, nüsük)* iki kez, biri mef'ûl biri ism-i fâil (هُمْ نَاسِكُوهُ *(onlar onu uygulayanlardır)*) — yani ibadet hem verilen hem uygulanan olarak iki kez adlandırılıyor.",
68: "Yedi kelime, üç fiil, üç ayrı zaman: جَٰدَلُوكَ PERF, فَقُلِ IMPV, تَعْمَلُونَ IMPF. Cevap bir bilgi iddiası değil bir bilgi devri: ٱللَّهُ أَعْلَمُ بِمَا تَعْمَلُونَ *(yaptıklarınızı en iyi Allah bilir)* — ism-i tafdîl. جدل *(tartışma, cedel)* kökü sûrede üçüncü kez (22:3, 22:8, burada); ilk ikisinde tartışanlar üçüncü şahıstı, burada doğrudan muhatap.",
69: "Lafız ayetin ilk kelimesi — sûrede bu konumda tek. Cümle bir yargı yeri kuruyor: hüküm (حكم *(hüküm verme, hikmet)*), zaman (يَوْمَ ٱلْقِيَٰمَةِ *(kıyamet günü)*), konu (فِيمَا كُنتُمْ فِيهِ تَخْتَلِفُونَ *(ayrılığa düştüğünüz şey)*). Aynı yüklem 22:17'de altı topluluk arasındaydı; burada doğrudan muhataplar arasında.",
70: "Aynı kök iki kez ve iki ayrı özneye: أَلَمْ تَعْلَمْ *(bilmedin mi)* muhataba, أَنَّ ٱللَّهَ يَعْلَمُ *(Allah bilir)* lafza. Yani bilme muhataptan istenip lafza atfediliyor. Sonra bilgi bir nesneye bağlanıyor: إِنَّ ذَٰلِكَ فِى كِتَٰبٍ *(bu bir kitaptadır)* — yani bilgi saklanan bir şey olarak. Kapanış zorluk ölçüsünü kaldırıyor: عَلَى ٱللَّهِ يَسِيرٌۭ *(Allah'a kolaydır)*, يسر *(kolaylık)*.",
71: "Tapılan şey iki eksiklikle tanımlanıyor ve ikisi de bilgiye ait: مَا لَمْ يُنَزِّلْ بِهِۦ سُلْطَٰنًۭا *(hakkında delil indirmediği)* — dışarıdan gelen yetki yok; وَمَا لَيْسَ لَهُم بِهِۦ عِلْمٌۭ *(kendilerinin de bilgisi olmadığı)* — içeriden gelen bilgi yok. Aynı yapı 22:8'de tartışanlar için kullanılmıştı. Kapanış bir üçüncü yokluk ekliyor: yardımcının yokluğu.",
72: "Yedi ayrı şahıs kategorisi — sûrenin en dağınık şahıs profili. Ayet bir tepkiyi yüzde okuyor: تَعْرِفُ فِى وُجُوهِ … ٱلْمُنكَرَ *(yüzlerinde hoşnutsuzluğu tanırsın)* — عرف *(tanıma, maruf)* ve نكر *(tanımama, inkâr; münker)* aynı ayette karşıt köklerden. 22:41'de bu iki kök bir emir çiftiydi (marufu buyur, münkerden alıkoy); burada biri okuma eylemi öteki okunan yüz ifadesi. Saldırı hapaks bir fiille ve gerçekleşmemiş olarak veriliyor: يَكَادُونَ يَسْطُونَ *(neredeyse saldıracaklar)*.",
73: "Mesel edilgenle açılıyor: ضُرِبَ مَثَلٌۭ *(bir mesel verildi)* — veren anılmıyor. Sonra iki aşamalı bir imkânsızlık kuruluyor. Birinci aşama üretim: لَن يَخْلُقُوا۟ ذُبَابًۭا وَلَوِ ٱجْتَمَعُوا۟ لَهُۥ *(bir araya gelseler bile bir sinek yaratamazlar)* — لَن ile kesin olumsuzluk, ve ortaklık şartı bile eklenmiş. İkinci aşama geri alma: وَإِن يَسْلُبْهُمُ ٱلذُّبَابُ شَيْـًۭٔا لَّا يَسْتَنقِذُوهُ *(sinek onlardan bir şey kapsa geri alamazlar)* — burada sinek fâil oluyor. Kapanış iki ism-i fâil/mef'ûlle her iki tarafı da aynı sıfata bağlıyor: ضَعُفَ ٱلطَّالِبُ وَٱلْمَطْلُوبُ *(isteyen de âciz, istenen de)*.",
74: "Dokuz kelimede iki lafız — sûrenin ve okumanın en yüksek lafız yoğunluğu (z=3,92). Aynı kök iki kez ve türü değişiyor: مَا قَدَرُوا۟ *(takdir edemediler)* fiil, حَقَّ قَدْرِهِۦٓ *(hakkıyla takdirini)* masdar. Yani eksiklik ölçmede ve ölçülen şey ölçmenin kendisi. Mühür çifti 22:40'ınkiyle aynı — ve iki ayet aynı fâsıla sınıfını da paylaşıyor (ز, sûrede yalnız iki ayet).",
75: "Ayetin ilk kelimesi lafız ve on bir kelimede iki geçiş. Seçme iki kaynaktan yapılıyor ve ikisi de مِنَ ile: مِنَ ٱلْمَلَٰٓئِكَةِ *(meleklerden)* ve وَمِنَ ٱلنَّاسِ *(insanlardan)* — parça edatı, yani her ikisinden de bir kısım. Ayette tek şahıs kategorisi var (3MS) ve tek fiil (يَصْطَفِى, bab VIII). Mühür 22:61'inkiyle aynı çift.",
76: "21:28'in ilk beş kelimesi burada birebir dönüyor: يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ *(önlerindekini ve arkalarındakini bilir)*. Orada bu cümle meleklerin bilgi sınırını çiziyordu; burada bir önceki ayetin elçi seçiminin ardından geliyor. Kapanış edilgen ve yönü tersine çeviriyor: وَإِلَى ٱللَّهِ تُرْجَعُ ٱلْأُمُورُ *(işler Allah'a döndürülür)* — fâsıla 22:41'inkiyle aynı kelime, ve o ayette de işlerin sonu lafza bağlanıyordu.",
77: "On bir kelimede dört emir ve on iki 2MP — sûrenin en yoğun muhatap ayeti. Emirler duruştan eyleme genişliyor: ٱرْكَعُوا۟ وَٱسْجُدُوا۟ *(rükû edin, secde edin)* iki beden duruşu, وَٱعْبُدُوا۟ رَبَّكُمْ *(Rabbinize kulluk edin)* bir yöneliş, وَٱفْعَلُوا۟ ٱلْخَيْرَ *(hayır işleyin)* bir davranış. İ'râbı tamamen mansûb: dört emrin dört nesnesi. Ayet secde işaretiyle kapanıyor — sûrenin ikinci secdesi.",
78: "Sûrenin en uzun ikinci ayeti ve altı ayrı kök ikilemesi taşıyor. Yapı üç katmanlı. Birincisi bir emir ve gerekçesi: جَٰهِدُوا۟ فِى ٱللَّهِ حَقَّ جِهَادِهِۦ *(hakkıyla cihad edin)* — 22:74'ün حَقَّ قَدْرِهِۦ kalıbıyla aynı yapı, iki kez 'hakkıyla'. İkincisi bir adlandırma zinciri: مِّلَّةَ أَبِيكُمْ إِبْرَٰهِيمَ … هُوَ سَمَّىٰكُمُ ٱلْمُسْلِمِينَ *(babanız İbrâhim'in dini… size müslümanlar adını verdi)*. Üçüncüsü karşılıklı şahitlik: elçi muhataplara, muhataplar insanlara — aynı kök شهد *(şahitlik)* iki kez, iki yönde. Kapanış dört emirle ve iki yergi-övgü kalıbıyla: فَنِعْمَ ٱلْمَوْلَىٰ وَنِعْمَ ٱلنَّصِيرُ *(ne güzel mevlâ, ne güzel yardımcı)* — 22:13'ün لَبِئْسَ ٱلْمَوْلَىٰ *(ne kötü mevlâ)* kalıbının tam karşıtı, aynı kelime.",
}

BIYOLOG = {
73: "Çıpa: ذُبَاب *(sinek)*, kök ذبب — korpusta TOPLAM İKİ geçiş ve **ikisi de bu ayette**; yani kök Kur'an'da yalnız burada var. Ölçülebilir olanlar: (a) Hayvan iki kez ve iki ayrı rolde geçiyor — birincide fiilin MEF'ÛLÜ (yaratılamayan şey), ikincide FÂİL (kapıp alan). Yani aynı canlı bir cümlede nesne, bir sonrakinde özne. (b) Hayvan hakkında hiçbir nitelik verilmiyor: ne boyut, ne davranış, ne tür; ölçek yalnız KONUMDAN çıkarılıyor — 'bir araya gelseler bile yaratamazlar' ile 'kapsa geri alamazlar' arasındaki iki imkânsızlık. (c) Alma fiili hapaks: سلب *(kapıp alma)*, korpusta tek geçiş; geri alma fiili ise seyrek: نقذ *(kurtarma, kurtarıp alma)*, 5 geçiş. Yani hem alış hem geri alış nadir kelimelerle adlandırılıyor. (d) Kapanış her iki tarafı aynı sıfata bağlıyor (ضعف *(kat; zayıflık)*), yani karşılaştırma canlı ile cansız arasında değil, iki âcizlik arasında kuruluyor. **Ölçüm sınırı:** ayet ne bir tür ne bir davranış tarif ediyor; ölçülebilen tek şey, korpusta tek bir ayete sıkışmış bir hayvan adının iki dilbilgisel rolde kullanılması.",
}

om = json.load(open('okuma_metni.json', encoding='utf-8'))
mk = json.load(open('mercek_kayit.json', encoding='utf-8'))

for n in range(61, 79):
    key = "22:%d" % n
    om['22'][key] = {'ar': AR[(22, n)], 'meal': MEAL[n], 'olcum': OLCUM[n],
                     'mercek': MERCEK[n], 'dikey': DIK[key]}
    if BIYOLOG.get(n): om['22'][key]['biyolog'] = BIYOLOG[n]
    mk['22'].append([key, MERCEK[n]])
for n, t in BIYOLOG.items():
    mk['22_biyolog'].append(["22:%d" % n, t])

om['22']['_mercek_atlama_notu'] += (
 " 22:72 biyolog ve uzay ATLANDI (سطو *(saldırma)* ve yüz ifadesi; canlılık ya da gök çıpası yok). "
 "22:73 biyolog YAZILDI (ذبب *(sinek)* — korpusta yalnız bu ayette); uzay ATLANDI. "
 "22:74 · 22:75 · 22:78 biyolog ve uzay ATLANDI. "
 "**SÛRE 22 TOPLAMI: 18 ★★★ ayetin 4'ünde biyolog yazıldı (2, 5, 20, 27, 36, 73 — altı), "
 "UZAY MERCEĞİ HİÇBİRİNDE YAZILMADI.** Sûre 22'de gök öğesi taşıyan ayetler var "
 "(22:18 · 22:61 · 22:63 · 22:65 · 22:70) ama hiçbiri ★★★ değil; protokol gereği o ayetlerde "
 "uzman merceği yazılmadı ve ★★★ ayetlerin hiçbirinde gök çıpası bulunmadı.")

om['22']['_kapanis'] = {
 "durum": "TAM — 78/78",
 "kafiye": ("**10 sınıf** — R 25 · N 24 · د 15 · ق 6 · ب 2 · ز 2 · ج 1 · ظ 1 · ء 1 · ط 1. "
   "16 ayette kırılma işaretli. Enbiyâ 1 sınıflıydı; iki komşu sûre kafiye çeşitliliğinin iki ucu."),
 "eksen": {"allah_token": 75, "allah_yogunluk": "1,69x", "rab_token": 8, "rab_yogunluk": "0,50x",
   "A_R_orani": 9.38,
   "allah_tepe": [[74, 3.92], [75, 3.11], [58, 2.80], [38, 2.55], [59, 2.33], [68, 2.33]],
   "rab_ayetleri": [1, 19, 30, 40, 47, 54, 67, 77],
   "en_cok_lafiz_tek_ayette": [40, 5],
   "min_duni_llah": [12, 71, 73],
   "not": "Enbiyâ ile TAM TERS: orada A=0,15x R=0,95x A/R=0,43; burada A=1,69x R=0,50x A/R=9,38."},
 "esma": {"ham_token": 38, "muhur_ayet": 11,
   "muhur_listesi": [40, 52, 59, 60, 61, 62, 63, 64, 65, 74, 75],
   "hepsi_cift": True,
   "cift_tekrarlari": {"قَوِيّ|عَزِيز": [40, 74], "سَمِيع|بَصِير": [61, 75]},
   "ardisik_kume": [59, 65],
   "denetim_sonucu": {"gecerli": 27, "yanlis_pozitif": 11},
   "yanlis_pozitifler": [[11, "آخِر"], [11, "مُبِين"], [13, "مَوْلَى"], [15, "آخِر"],
     [49, "مُبِين"], [50, "كَرِيم"], [71, "نَصِير"], [78, "شَهِيد"], [78, "شَهِيد"]],
   "not": "Okunan 38 tokenin 11'i yanlış pozitif = %29. Sûre 21'de %47, sûre 20'de %38 idi. "
          "Fark sebebi: bu sûrede esmâların çoğu MÜHÜR konumunda ve mühür konumu bağlamı sabitliyor "
          "(aday 461 onarım ölçütlerine 'mühür konumu' ayrı bir sinyal olarak eklendi)."},
 "olcumler": {"ayet": 78, "kelime": 1274, "mora": 6748, "ort_kelime": 16.33,
   "hapaks_ayet": 12, "hapaks_kok": 14,
   "cift_hapaks_ayet": [27, 40],
   "edilgen_ayet": 18, "edilgen_fiil": 27,
   "yildiz": {"3": 18, "2": 11, "1": 20, "0": 29},
   "iltifat": 1, "iltifat_ayet": 50,
   "fiilsiz_ayet": [21, 33, 43, 64],
   "adli_aktor_token": 16,
   "en_uzun": [5, 69], "en_kisa": [[21, 4], [43, 4]],
   "dis_dugum_max": [40, 9],
   "secde": [18, 77],
   "esit": "Tam-ayet ikizi HİÇ YOK."},
 "ic_yapi": ("Sûre içi bölüt ikizleri yoğun: 22:3 ↔ 22:8 · 22:14 ↔ 22:23 · 22:30 ↔ 22:32 ↔ 22:60 "
   "(ذَٰلِكَ وَمَنْ) · 22:34 ↔ 22:67 · 22:44 ↔ 22:48 · 22:45 ↔ 22:48 · 22:50 ↔ 22:51 · "
   "22:56 ↔ 22:57 · 22:40 ↔ 22:74 (mühür) · 22:61 ↔ 22:75 (mühür). "
   "Nakarat ذِكْرُ ٱسْمِ ٱللَّهِ dört kez (28, 34, 36, 40 — aday 463)."),
 "dis_yapi": ("22:61-65 BEŞ ARDIŞIK AYETİN HER BİRİNİN sûre 31'e (Lokman) xref'i var: "
   "31:29 · 31:30 (beş 3-gram) · 31:16 · 31:26 · 31:20. Aday 464."),
 "acik_borclar": "Esmâ tablosu onarılmadan (aday 444/461) sûrenin esmâ profili kullanılamaz."
}

om['ilerleme']['tam'].append(22)
om['ilerleme']['kismi'].pop('22', None)
om['ilerleme']['bekleyen'].pop('22', None)
om['ilerleme']['not'] = ("Sûre 20 TAM. Sûre 21 TAM (112/112). **Sûre 22 TAM (78/78)**. "
                         "Devam: sûre 23 (Mü'minûn). Dikey katman A parçası birincil, B etiketsiz.")
om['ilerleme']['okunan_ayet'] = 1463

json.dump(om, open('okuma_metni.json', 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
json.dump(mk, open('mercek_kayit.json', 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
print("SÛRE 22 TAM · mercek:", len(mk['22']), "· biyolog:", len(mk['22_biyolog']))
