# -*- coding: utf-8 -*-
"""blok_22_41_60.py — Hac 41-60 bloğunun okuma kaydı."""
import json

DIK = json.load(open('blok_dikey_22_41_60.json', encoding='utf-8'))
veri = json.load(open('kuran_veri.json', encoding='utf-8'))
AR = {}
for s in veri['sureler']:
    for a in s['ayetler']:
        AR[(s['no'], a['no'])] = a['ar']

MEAL = {
41: "Onlar ki, kendilerine yeryüzünde imkân versek namazı kılar, zekâtı verir, marufu buyurur, münkerden alıkoyarlar. İşlerin sonu Allah'a aittir.",
42: "Seni yalanlıyorlarsa, onlardan önce Nûh kavmi, Âd ve Semûd da yalanlamıştı.",
43: "İbrâhim'in kavmi ve Lût'un kavmi de.",
44: "Medyen halkı da. Mûsâ da yalanlandı. Ben de inkârcılara mühlet verdim, sonra onları yakaladım. Beni inkâr etmek nasılmış!",
45: "Nice ülkeyi, zulmederken helâk ettik; şimdi çatıları üzerine çökmüş durumda. Nice atıl kuyu, nice yüksek köşk!",
46: "Yeryüzünde gezmediler mi ki, akledecekleri kalpleri, işitecekleri kulakları olsun? Doğrusu gözler kör olmaz; asıl göğüslerdeki kalpler kör olur.",
47: "Senden azabı acele istiyorlar. Allah vaadinden caymaz. Rabbinin katında bir gün, sizin saydıklarınızdan bin yıl gibidir.",
48: "Nice ülkeye, zulmederken mühlet verdim; sonra onu yakaladım. Dönüş banadır.",
49: "De ki: Ey insanlar, ben sizin için ancak apaçık bir uyarıcıyım.",
50: "İman edip salih işler yapanlar için bağışlanma ve değerli bir rızık vardır.",
51: "Âyetlerimizi geçersiz kılmak için çabalayanlar ise, işte onlar cehennemliktir.",
52: "Senden önce hiçbir elçi ve hiçbir nebî göndermedik ki, o bir şey temenni ettiğinde şeytan onun temennisine bir şey atmış olmasın. Ama Allah şeytanın attığını siler, sonra Allah kendi âyetlerini sağlamlaştırır. Allah bilendir, hikmet sahibidir.",
53: "Şeytanın attığını, kalplerinde hastalık olanlar ve kalpleri katılaşmış olanlar için bir sınama kılsın diye. Zalimler gerçekten uzak bir ayrılık içindedir.",
54: "Bir de kendilerine ilim verilenler onun Rabbinden gelen hak olduğunu bilsinler, ona iman etsinler ve kalpleri ona saygıyla yatışsın diye. Allah, iman edenleri elbette dosdoğru bir yola iletir.",
55: "İnkâr edenler, o saat ansızın gelinceye ya da kısır bir günün azabı gelinceye kadar ondan şüphe içinde kalmayı sürdürürler.",
56: "O gün mülk Allah'ındır; aralarında O hükmeder. İman edip salih işler yapanlar nimet bahçelerindedir.",
57: "İnkâr edip âyetlerimizi yalanlayanlar için ise aşağılayıcı bir azap vardır.",
58: "Allah yolunda hicret edip sonra öldürülen ya da ölenleri Allah elbette güzel bir rızıkla rızıklandırır. Allah rızık verenlerin en hayırlısıdır.",
59: "Onları hoşnut olacakları bir yere elbette sokar. Allah bilendir, halîmdir.",
60: "İşte böyle. Kim kendisine yapılan cezanın misliyle karşılık verir de sonra yine kendisine haksızlık edilirse, Allah ona mutlaka yardım eder. Allah çok affedicidir, çok bağışlayıcıdır.",
}

OLCUM = {
41: "eksen: **Allah lafzı 15. sırada — sondan üçüncü** (allah z=0,65) · aktör yok · edim şart, kip COND 1 · şahıs 1P ×2 · 3MP ×9 · n=17 mora=99 harf=89, fâsıla ٱلْأُمُورِ *(işler)* → ر, R sınıfı; i'râb GEN 5 · ACC 2 · NOM 1; bab I ×2 · bab II ×1 · bab IV ×2; **zaman PERF ×5 — IMPF yok**; kök ikilemesi أمر *(emir; iş)* ×2 — biri fiil (buyurma), öteki isim (işler) · kökler مكن *(yerleştirme, imkân verme)* · أرض *(yer, yeryüzü)* · قوم *(kalkma; kavim; kıyamet)* · صلو *(namaz, salât)* · أتي *(gelme, getirme; verme)* · زكو *(arınma, zekât)* · أمر *(emir; iş)* · عرف *(tanıma, maruf)* · نهي *(nehiy, yasaklama)* · نكر *(tanımama, inkâr; münker)* · أله *(ilâh; lafza-i celâl)* · عقب *(ardından gelme; ceza; âkıbet)* · bağ: xref اللّه + عاقبة *(âkıbet)* + أمر *(iş)* → 31:22; 22:35 ile ortak صلو (elle, L2)",
42: "eksen yok · aktör: adlı ÜÇ ad — نُوح *(Nûh)* 7. (mecrur), عاد *(Âd)* 8. (fâil), ثَمُود *(Semûd)* 9. (fâil) · edim şart, kip COND 1 · CERT 1 · şahıs 3MP ×3 · 2MS 1 · 3FS 1 · n=9 mora=46 harf=38, fâsıla ثَمُودُ *(Semûd)* → د, د sınıfı — **fâsıla bir özel ad**; i'râb ACC 1 · NOM 3 · GEN 1; bab II ×2; kök ikilemesi كذب *(yalanlama, tekzîb)* ×2 — biri IMPF 2MS'e yönelik, öteki PERF geçmişe; simetri [3,1,7,1] · kökler كذب *(yalanlama, tekzîb)* · قبل *(ön, önce; kabul)* · قوم *(kalkma; kavim; kıyamet)* · عود *(dönme, tekrarlama; Âd)* · bağ: xref كذّب + كذّب + قبل → 35:25",
43: "eksen yok · aktör: adlı İKİ kişi — إِبْراهِيم *(İbrâhim)* 2. ve لُوط *(Lût)* 4. sırada, ikisi de mecrur · edim haber · **şahıs alanı BOŞ — ayette hiç fiil yok** · **n=4 mora=23 harf=18 — 22:21 ile birlikte sûrenin en kısa ayeti**, fâsıla لُوطٍۢ *(Lût)* → ط, **ط sınıfı — sûrede tek**; i'râb NOM 2 · GEN 2; **bab ve zaman alanları boş**; kök ikilemesi قوم *(kalkma; kavim; kıyamet)* ×2 — **dört kelimenin ikisi aynı kök** · kökler قوم *(kalkma; kavim; kıyamet)* · bağ: 22:42 ile tek liste (elle, L1)",
44: "eksen yok · aktör: adlı İKİ ad — مَدْيَن *(Medyen)* 2. (mecrur, tür 'kavim') ve مُوسَى *(Mûsâ)* 4. (fâil, tür 'kişi') · edim soru, kip INTG 1 · şahıs 3MS ×2 · **1S ×5** · 3MP 1 · n=11 mora=60 harf=51, fâsıla نَكِيرِ *(inkârım)* → ر, R sınıfı; i'râb NOM 3 · GEN 2; bab I ×2 · bab II ×1 · bab IV ×1; edilgen 1 (كُذِّبَ *(yalanlandı)*, z=1,1); **zaman PERF ×4 — IMPF yok** · kökler صحب *(arkadaşlık, sahiplik)* · مدن *(Medyen; şehir)* · كذب *(yalanlama, tekzîb)* · ملو *(mühlet verme, imlâ)* · كفر *(inkâr, nankörlük)* · أخذ *(alma, edinme)* · كيف *(nasıl)* · كون *(olmak)* · نكر *(tanımama, inkâr; münker)* · bağ: xref أخذ *(yakalama)* + كيف *(nasıl)* + كان *(oldu)* → 13:32 ve 40:5; **22:48 ile bölüt ikizi** — أَمْلَيْتُ … ثُمَّ أَخَذْتُ *(mühlet verdim… sonra yakaladım)* (elle, L1)",
45: "eksen yok · aktör yok · edim haber · şahıs 1P ×2 · 3FS ×4 · n=14 mora=82 harf=64, fâsıla مَّشِيدٍ *(yüksek, sağlam)* → د, د sınıfı (kafiye kırılması işaretli); **i'râb GEN 6** · NOM 3; bab IV ×1 (tek fiil); **hapaks بأر *(kuyu)* (z=3,38)** · yıldız ★★★ · kökler قري *(köy, kasaba)* · هلك *(helâk, yok olma)* · ظلم *(zulüm)* · خوي *(ıssız, çökmüş)* · عرش *(arş, taht; çatı)* · بأر *(kuyu)* · عطل *(atıl bırakma, terk edilmiş)* · قصر *(köşk; kısaltma)* · شيد *(sağlam yapı, yükseltme)* · bağ: **22:48 ile açılış ikizi** — فَكَأَيِّن مِّن قَرْيَةٍ / وَكَأَيِّن مِّن قَرْيَةٍ *(nice ülke)* (elle, L1)",
46: "eksen yok · aktör yok · edim soru, kip INTG 1 · NEG 2 · şahıs 3MP ×7 · 3FS ×6 · n=23 mora=123 harf=101 — bloğun en uzun ikinci ayeti, fâsıla ٱلصُّدُورِ *(göğüsler)* → ر, R sınıfı; i'râb GEN 2 · NOM 4 · ACC 1; **bab I ×6 — altı fiil, hepsi bab I ve hepsi IMPF**; kök ikilemesi قلب *(çevirme, kalp)* ×2 ve عمي *(körlük)* ×2 — **عمي biri olumsuz biri olumlu, aynı fiil iki karşıt öznede**; simetri [3,1,13,1] · kökler سير *(yürüme, seyir)* · أرض *(yer, yeryüzü)* · كون *(olmak)* · قلب *(çevirme, kalp)* · عقل *(akletme, akıl)* · أذن *(izin; bildirme; kulak)* · سمع *(işitme)* · عمي *(körlük)* · بصر *(görme, basiret)* · صدر *(göğüs; çıkma)* · bağ: xref yok · **NOT: ayet dört organ adı taşıyor (kalp · kulak · göz · göğüs) ama yıldız=0 olduğu için protokol gereği uzman merceği YAZILMADI**",
47: "eksen: **Allah lafzı 5. sırada** (allah z=0,90) · Rab 10. sırada, عِندَ رَبِّكَ *(Rabbinin katında)* (**rab z=1,20 — bloğun en yüksek Rab yoğunluğu**) · aktör yok · edim haber, kip NEG 1 · şahıs 3MP ×2 · 2MS ×2 · 3MS ×2 · 2MP ×2 — **dört şahıs kategorisi eşit dağılmış** · n=14 mora=75 harf=63, fâsıla تَعُدُّونَ *(sayarsınız)* → ن, N sınıfı (kırılma işaretli); i'râb GEN 4 · NOM 1 · ACC 4; bab I ×1 · bab IV ×1 · bab X ×1 — üç fiil, üçü ayrı bab; **sayı sözcüğü İKİ TANE: أَلْف *(bin)* ve عَدَّ *(saymak)*** · yıldız ★ · kökler عجل *(acele)* · عذب *(azap)* · خلف *(ayrılığa düşme; cayma)* · أله *(ilâh; lafza-i celâl)* · وعد *(vaat)* · يوم *(gün)* · عند *(yan, katında)* · ربب *(rab, terbiye etme)* · ألف *(bin (sayı); ülfet)* · سنو *(yıl; parlama)* · عدد *(sayma, sayı)* · bağ: xref أخلف *(cayma)* + اللّه + وعد → 9:77 ve 30:6 · ألف *(bin)* + سنة *(yıl)* + عدّ *(sayma)* → 32:5; **21:37 ile ortak عجل *(acele)*** (elle, L2)",
48: "eksen yok · aktör yok · edim haber · şahıs **1S ×5** · 3FS ×3 · n=11 mora=57 harf=46, fâsıla ٱلْمَصِيرُ *(varış)* → ر, R sınıfı (kırılma işaretli); i'râb NOM 3 · GEN 1; bab I ×1 · bab IV ×1; **zaman PERF ×2 — IMPF yok**; simetri [3,1,5,1] · yıldız ★ · kökler قري *(köy, kasaba)* · ملو *(mühlet verme, imlâ)* · ظلم *(zulüm)* · أخذ *(alma, edinme)* · صير *(varış, dönüş)* · bağ: **22:45 ile açılış ikizi ve 22:44 ile gövde ikizi** — üç ayet iki ayrı kalıbı paylaşıyor (elle, L1)",
49: "eksen yok · **esmâ مُبِين *(apaçık)* 8. sırada = fâsıla — ÖLÇÜM ARTEFAKTI (aday 444)**: نَذِيرٌۭ مُّبِينٌۭ *(apaçık uyarıcı)*, göndergesi PEYGAMBER; sûrede üçüncü مُبِين yanlış pozitifi · aktör yok · edim emir + nida, kip IMPV 1 · VOC 1 · şahıs 2MS 1 · 1S 1 · 2MP 1 · n=8 mora=47 harf=33, fâsıla مُّبِينٌۭ → ن, N sınıfı; i'râb ACC 2 · NOM 3; bab I ×1 (tek fiil); biçim DIKKAT · kökler قول *(söz söyleme)* · أيي *(hangi; âyet)* · أنس *(insan)* · نذر *(uyarı; adak)* · بين *(arası; açıklama)* · bağ: 22:1 ve 22:5 ile ortak يَٰٓأَيُّهَا ٱلنَّاسُ *(ey insanlar)* açılışı — sûrede üçüncü kez (elle, L1)",
50: "eksen yok · **esmâ كَرِيم *(değerli, cömert)* 8. sırada = fâsıla — ÖLÇÜM ARTEFAKTI (aday 444)**: رِزْقٌۭ كَرِيمٌۭ *(değerli bir rızık)* terkîbinde SIFAT, ilâhî ad değil · aktör yok · edim haber · şahıs 3MP ×5 · **iltifât VAR: 12>3 — SÛRENİN TEK İLTİFÂTI** · n=8 mora=52 harf=45, fâsıla كَرِيمٌۭ → م, N sınıfı; i'râb GEN 1 · NOM 3; bab I ×1 · bab IV ×1 · kökler أمن *(güven; iman)* · عمل *(iş, amel)* · صلح *(iyi olma, salâh)* · غفر *(bağışlama, mağfiret)* · رزق *(rızık)* · كرم *(üstün tutma, ikram)* · bağ: xref صالحة *(salih)* + مغفرة *(bağışlanma)* + رزق *(rızık)* → 34:4",
51: "eksen yok · aktör yok · edim haber · şahıs 3MP ×2 · 1P 1 · n=8 mora=54 harf=41, fâsıla ٱلْجَحِيمِ *(alevli ateş)* → م, N sınıfı; i'râb GEN 2 · ACC 1 · NOM 1; bab I ×1 (tek fiil); dış düğüm 2 · kökler سعي *(çaba, koşuşturma)* · أيي *(âyet, işaret)* · عجز *(âciz bırakma; acizlik)* · صحب *(arkadaşlık, sahiplik)* · جحم *(alevli ateş, cahîm)* · bağ: xref سعى *(çaba)* + آية *(âyet)* + معاجز *(âciz bırakmaya çalışan)* → 34:5 ve 34:38; **22:50 ile karşıt ikiz** — aynı yapı, ters hüküm (elle, L1)",
52: "eksen: **Allah lafzı ÜÇ geçiş — 17., 23. ve 25. sırada** (allah z=1,69; kök ikilemesi أله ×3) · **esmâ İKİ token ve MÜHÜR: عَلِيم|حَكِيم *(alîm|hakîm)* 26. ve 27. sırada — sûrenin ikinci mühürü**; ikisi de geçerli · aktör: adlı شَيْطان *(şeytan)* 13. ve 20. sırada, tür 'gayb', **rol fâil — sûrede şeytanın fâil olduğu ilk ayet** · edim haber, kip NEG 2 · RES 1 · şahıs 1P ×2 · 2MS 1 · 3MS ×7 · **n=27 mora=145 harf=109 — bloğun en uzun ayeti (n z=1,55)**, fâsıla حَكِيمٌۭ *(hakîm)* → م, N sınıfı; i'râb GEN 5 · NOM 7; bab I ×2 · bab IV ×4; **kök ikilemesi ALTI ayrı kök: رسل ×2 · مني ×2 · لقي ×2 · شطن ×2 · أله ×3 · حكم ×2 — bloğun ve sûrenin en yoğun ikileme ayeti**; biçim HASR; simetri [4,12,19,1]; dış düğüm 3 · yıldız ★ · kökler رسل *(gönderme, elçi)* · قبل *(ön, önce; kabul)* · نبأ *(haber; nebî)* · مني *(temenni, kuruntu; meni)* · لقي *(atma, bırakma; karşılaşma)* · شطن *(şeytan)* · نسخ *(silme, nesih; nüsha)* · أله *(ilâh; lafza-i celâl)* · حكم *(hüküm verme, hikmet)* · أيي *(âyet, işaret)* · علم *(bilme)* · bağ: **21:25 ile aynı açılış kalıbı** — وَمَآ أَرْسَلْنَا مِن قَبْلِكَ مِن رَّسُولٍ *(senden önce hiçbir elçi göndermedik)*, orada da HASR vardı (elle, L1); xref 24:18 · 24:58 · 24:59",
53: "eksen yok · aktör: adlı شَيْطان 4. sırada, tür 'gayb', rol fâil · edim haber, kip EMPH 1 · şahıs 3MS ×2 · 3MP ×2 · n=16 mora=94 harf=77, fâsıla بَعِيدٍۢ *(uzak)* → د, د sınıfı (kırılma işaretli); i'râb NOM 3 · ACC 3 · GEN 4; bab I ×1 · bab IV ×1; kök ikilemesi قلب *(çevirme, kalp)* ×2 — **ikisi de iyelikli çoğul, ikisi de bir kusurla nitelenmiş** · yıldız ★ · kökler جعل *(kılma, var etme)* · لقي *(atma, bırakma)* · شطن *(şeytan)* · فتن *(sınama, fitne)* · قلب *(çevirme, kalp)* · مرض *(hastalık)* · قسو *(katılık, kasvet)* · ظلم *(zulüm)* · شقق *(ayrılık, şikak; yarma)* · بعد *(sonra; uzaklık)* · bağ: 22:52 ile tek cümle — لِـ ile amaç bağı (elle, L1); 22:11 ile ortak فتن *(sınama, fitne)* (elle, L2)",
54: "eksen: **Allah lafzı 15. sırada** (allah z=0,42) · Rab 8. sırada, مِن رَّبِّكَ *(Rabbinden)* (rab z=0,69) · aktör yok · edim haber, kip EMPH 1 · şahıs 3MS ×4 · 3MP ×7 · 2MS 1 · 3FS 1 · n=21 mora=113 harf=97, fâsıla مُّسْتَقِيمٍۢ *(dosdoğru)* → م, N sınıfı; i'râb ACC 4 · NOM 3 · GEN 3; bab I ×1 · bab IV ×4; edilgen 1 (أُوتُوا۟ *(verildiler)*); kök ikilemesi علم *(bilme)* ×2 — biri fiil biri mef'ûl, ve أمن *(güven; iman)* ×2; simetri [3,1,4,1]; dış düğüm 3 · kökler علم *(bilme)* · أتي *(gelme, getirme; verme)* · حقق *(hak, gerçek)* · ربب *(rab, terbiye etme)* · أمن *(güven; iman)* · خبت *(alçakgönüllü olma, ihbât)* · قلب *(çevirme, kalp)* · أله *(ilâh; lafza-i celâl)* · هدي *(yol gösterme)* · صرط *(yol, sırât)* · قوم *(kalkma; kavim; kıyamet)* · bağ: 22:52-53 ile üçlü amaç zinciri — üç ayet üst üste لِـ ile bağlanıyor (elle, L1); xref علم + حقّ + ربّ → 2:26 ve 2:144 · حقّ + ربّ + آمن → 4:170",
55: "eksen yok · aktör yok · edim haber, kip NEG 1 · şahıs 3MS ×3 · 3MP ×4 · 3FS 1 · n=16 mora=81 harf=66, fâsıla عَقِيمٍ *(kısır)* → م, N sınıfı; i'râb GEN 3 · NOM 2 · ACC 1; bab I ×4; kök ikilemesi أتي *(gelme, getirme)* ×2 — biri dişil (saat), öteki eril (azap); simetri [3,1,5,1] · kökler زيل *(ayrılma, zeval)* · كفر *(inkâr, nankörlük)* · مري *(şüphe, mirye)* · أتي *(gelme, getirme)* · سوع *(saat, vakit)* · بغت *(ansızın gelme)* · عذب *(azap)* · يوم *(gün)* · عقم *(kısırlık; kısır (gün))* · bağ: xref أتى *(gelme)* + ساعة *(saat)* + بغتة *(ansızın)* → 12:107; **21:40 ile ortak بغت *(ansızın gelme)*** (elle, L2)",
56: "eksen: **Allah lafzı 3. sırada** (allah z=1,14) · aktör yok · edim haber · şahıs 3MS 1 · 3MP ×5 · n=12 mora=70 harf=61, fâsıla ٱلنَّعِيمِ *(nimet)* → م, N sınıfı; i'râb NOM 1 · GEN 4 · ACC 1; bab I ×2 · bab IV ×1; dış düğüm 2 · kökler ملك *(melek; mülk, sahiplik)* · يوم *(gün)* · أله *(ilâh; lafza-i celâl)* · حكم *(hüküm verme, hikmet)* · بين *(arası; açıklama)* · أمن *(güven; iman)* · عمل *(iş, amel)* · صلح *(iyi olma, salâh)* · جنن *(cin; örtme; cennet)* · نعم *(nimet; davar)* · bağ: xref ملك *(mülk)* + يوم *(gün)* + اللّه → 40:16 · صالحة + جنّة + نعيم → 31:8; **22:14 · 22:23 · 22:50 ile aynı ءَامَنُوا۟ وَعَمِلُوا۟ ٱلصَّٰلِحَٰتِ dizisi — sûrede dördüncü kez** (elle, L1)",
57: "eksen yok · aktör yok · edim haber · şahıs 3MP ×5 · 1P 1 · n=8 mora=55 harf=46, fâsıla مُّهِينٌۭ *(aşağılayıcı)* → ن, N sınıfı; i'râb GEN 1 · NOM 2; bab I ×1 · bab II ×1; zaman PERF ×2 · kökler كفر *(inkâr, nankörlük)* · كذب *(yalanlama, tekzîb)* · أيي *(âyet, işaret)* · عذب *(azap)* · هون *(aşağılama, hor görme)* · bağ: **22:56 ile karşıt ikiz** — aynı yapı (ٱلَّذِينَ + fiil + هُم), ters hüküm (elle, L1); 22:18 ile ortak هون (elle, L2)",
58: "eksen: **Allah lafzı ÜÇ geçiş — 5., 11. ve 15. sırada (allah z=2,80 — BLOĞUN VE SÛRENİN EN YÜKSEK LAFIZ YOĞUNLUĞU)**; kök ikilemesi أله ×3 · aktör yok · edim haber, kip EMPH ×3 · şahıs 3MP ×7 · 3MS ×2 · n=18 mora=97 harf=81, fâsıla ٱلرَّٰزِقِينَ *(rızık verenler)* → ن, N sınıfı; i'râb GEN 3 · NOM 2 · ACC 4; bab I ×3 · bab III ×1; edilgen 1 (قُتِلُوٓا۟ *(öldürüldüler)*, z=1,1); **kök ikilemesi رزق *(rızık)* ×3 — fiil, mef'ûl-i mutlak ve ism-i fâil çoğul olarak üç ayrı biçimde**; simetri [3,1,6,1]; **dış düğüm 6 — bloğun en bağlantılı ayeti** · yıldız ★★ · kökler هجر *(hicret, terk etme)* · سبل *(yol)* · أله *(ilâh; lafza-i celâl)* · قتل *(öldürme)* · موت *(ölüm)* · رزق *(rızık)* · حسن *(güzellik, iyilik)* · خير *(hayır, daha iyi)* · bağ: xref سبيل *(yol)* + اللّه + قتل *(öldürme)* → 4:74 ve 9:111 · هاجر *(hicret)* + سبيل + اللّه → 4:89 ve 4:100 · اللّه + خير *(hayır)* + رازق *(rızık veren)* → 62:11",
59: "eksen: **Allah lafzı 5. sırada** (allah z=2,33) · **esmâ İKİ token ve MÜHÜR: عَلِيم|حَلِيم *(alîm|halîm)* 6. ve 7. sırada — sûrenin YEDİ ARDIŞIK MÜHÜR kümesinin (22:59-65) ilki**; ikisi de geçerli · aktör yok · edim haber, kip EMPH ×3 · şahıs 3MS ×2 · 3MP ×3 · **n=7 mora=47 harf=39 — bloğun en kısa ayeti**, fâsıla حَلِيمٌۭ *(halîm)* → م, N sınıfı; i'râb ACC 3 · NOM 2; bab I ×1 · bab IV ×1; kök ikilemesi دخل *(girme, sokma)* ×2 — fiil + mef'ûl-i mutlak (لَيُدْخِلَنَّهُم مُّدْخَلًۭا *(elbette sokar, bir sokuşla)*) · yıldız ★★ · kökler دخل *(girme, sokma)* · رضو *(razı olma, hoşnutluk)* · أله *(ilâh; lafza-i celâl)* · علم *(bilme)* · حلم *(hilm, yumuşaklık)* · bağ: xref اللّه + عليم + حليم → 4:12 ve 33:51; 22:58 ile tek cümle (elle, L1)",
60: "eksen: **Allah lafzı İKİ geçiş — 12. ve 14. sırada** (allah z=1,97; kök ikilemesi أله ×2) · **esmâ İKİ token ve MÜHÜR: عَفُوّ|غَفُور *(afüvv|gafûr)* 15. ve 16. sırada — ardışık mühür kümesinin ikincisi**; ikisi de geçerli · aktör yok · edim haber, kip EMPH ×3 · şahıs **3MS ×7 — ayette tek şahıs** · n=16 mora=71 harf=60, fâsıla غَفُورٌۭ *(gafûr)* → ر, R sınıfı; i'râb GEN 1 · NOM 3 · ACC 2; bab I ×2 · bab III ×2; **edilgen 2 (عُوقِبَ *(cezalandırıldı)* · بُغِىَ *(haksızlık edildi)*, z=2,52)**; kök ikilemesi عقب *(ceza; âkıbet)* ×2 — **biri etken biri edilgen, aynı fiil iki yönde**; simetri [3,1,7,1]; ۞ hizb işaretiyle açılıyor · yıldız ★★ · kökler عقب *(ardından gelme; ceza; âkıbet)* · مثل *(benzer, misil; heykel)* · بغي *(azgınlık, haddi aşma)* · نصر *(yardım)* · أله *(ilâh; lafza-i celâl)* · عفو *(af, bağışlama)* · غفر *(bağışlama, mağfiret)* · bağ: xref اللّه + عفوّ + غفور → 4:99 ve 58:2 · عاقب + مثل + عاقب → 16:126; **22:30 ve 22:32 ile aynı ذَٰلِكَ وَمَنْ *(işte böyle; kim)* açılışı — sûrede üçüncü kez** (elle, L1)",
}

MERCEK = {
41: "Şart cümlesinin cevabı dört fiille veriliyor ve dördü de PERF: أَقَامُوا۟ · ءَاتَوُا۟ · أَمَرُوا۟ · نَهَوْا۟ *(kıldılar · verdiler · buyurdular · alıkoydular)*. Yani gelecekteki bir imkânın karşılığı geçmiş zamanla anlatılıyor — koşul IMPF (مَّكَّنَّٰهُمْ), sonuç PERF. Dört fiil ikişerli iki çift: ilk ikisi ibadet, son ikisi yön verme; son çift zıt yönlü (buyurma / alıkoyma). Kapanış sahipliği tek harf-i cerle veriyor: وَلِلَّهِ عَٰقِبَةُ ٱلْأُمُورِ *(işlerin sonu Allah'ındır)*.",
42: "Aynı kök iki kez ve zamanı değişiyor: يُكَذِّبُوكَ *(seni yalanlarlar)* IMPF ve muhataba, كَذَّبَتْ *(yalanladı)* PERF ve geçmişe. Yani şimdiki bir olay bir dizinin son halkası olarak kuruluyor. Dizi üç adla açılıyor ve fâsıla bir özel ad: ثَمُودُ. Üç adın ikisi kavim adı, biri kişi adı ve o da izafetle bağlı (قَوْمُ نُوحٍۢ *(Nûh kavmi)*) — yani sayılan şey kişiler değil topluluklar.",
43: "Dört kelime, hiç fiil, ve dördün ikisi aynı kelime: قَوْمُ *(kavim)*. Ayet bir öncekinin listesini sürdürüyor ve tek başına cümle bile değil. Sûrede fiilsiz üçüncü ayet (22:21, 22:33, 22:43). Fâsıla harfi ط — sûrenin 78 ayetinde bir kez.",
44: "Liste bitiyor ve şahıs 1S'e geçiyor: أَمْلَيْتُ … أَخَذْتُهُمْ *(mühlet verdim… yakaladım)*. Yani anlatıcı üçüncü şahıslı liste boyunca görünmüyor, listenin sonunda birdenbire beş kez beliriyor. İki fiil arasında ثُمَّ *(sonra)* var: mühlet ile yakalama arasına bir süre konuyor. Kapanış bir soru ama cevap beklemiyor: فَكَيْفَ كَانَ نَكِيرِ *(inkârım nasılmış)* — نكر *(tanımama, inkâr; münker)* kökü 22:41'de münker (kötülük) anlamındaydı, burada anlatıcının reddi.",
45: "Ayet bir sayı sözcüğüyle açılıyor ama sayı verilmiyor: فَكَأَيِّن *(nice)*. Üç yıkıntı sıralanıyor ve üçü de farklı yapı türü: قَرْيَة *(ülke, yerleşim)* — insan topluluğu; بِئْر مُّعَطَّلَة *(atıl kuyu)* — su yapısı; قَصْر مَّشِيد *(yüksek köşk)* — yükseklik yapısı. Üçünün de hâli bir sıfatla veriliyor, hiçbirinin yıkılışı anlatılmıyor. خَاوِيَةٌ عَلَىٰ عُرُوشِهَا *(çatıları üzerine çökmüş)* — عرش *(arş, taht; çatı)* kökü sûre 21:22'de arş anlamındaydı, burada çatı. Aynı kök, en yüksekten en yıkığa.",
46: "Altı fiil, hepsi bab I ve hepsi IMPF — ayette tek bir PERF yok. Organ adları dört: قُلُوب *(kalpler)* · ءَاذَان *(kulaklar)* · أَبْصَٰر *(gözler)* · صُدُور *(göğüsler)*. Yapı bir düzeltme kuruyor: körlük gözden alınıp kalbe veriliyor, ve aynı fiil iki kez — لَا تَعْمَى ٱلْأَبْصَٰرُ وَلَٰكِن تَعْمَى ٱلْقُلُوبُ *(gözler kör olmaz, kalpler kör olur)*. Kalp iki kez geçiyor ve ikincisi bir yer belirtimiyle sabitleniyor: ٱلَّتِى فِى ٱلصُّدُورِ *(göğüslerdeki)*.",
47: "Üç fiil, üçü ayrı bab: يَسْتَعْجِلُونَكَ bab X (kendileri için isteme), يُخْلِفَ bab IV, تَعُدُّونَ bab I. İlk ikisi karşı karşıya: acele isteme ile caymama. Sonra ölçek değişiyor ve iki sayı sözcüğü giriyor: كَأَلْفِ سَنَةٍۢ مِّمَّا تَعُدُّونَ *(saydıklarınızdan bin yıl gibi)* — ölçen taraf açıkça belirtiliyor (مِّمَّا تَعُدُّونَ), yani sayı mutlak değil muhataba göreli. عجل *(acele)* kökü 21:37'de insanın malzemesiydi; burada insanın davranışı.",
48: "22:45'in açılışını (كَأَيِّن مِّن قَرْيَةٍ) ve 22:44'ün gövdesini (أَمْلَيْتُ … ثُمَّ أَخَذْتُ) birleştiriyor — yani üç ayet iki ayrı kalıbı paylaşıyor. Fark tekilleşme: 22:45'te üç yapı türü sayılıyordu, burada tek ülke ve tek zamir (أَخَذْتُهَا). Kapanış yönü tersine çeviriyor: وَإِلَىَّ ٱلْمَصِيرُ *(dönüş banadır)* — 1S, mühlet verenin kendisi.",
49: "Sekiz kelimede üç şahıs (2MS · 1S · 2MP) ve bir HASR benzeri sınırlama: إِنَّمَآ أَنَا۠ لَكُمْ نَذِيرٌۭ مُّبِينٌۭ *(ben sizin için ancak apaçık bir uyarıcıyım)*. Görev tek sıfata indirgeniyor. Sûrede üçüncü kez يَٰٓأَيُّهَا ٱلنَّاسُ *(ey insanlar)* açılışı (22:1, 22:5, burada) — üçünde de muhatap tüm insanlık.",
50: "Sekiz kelime, tek yapı, iki karşılık: مَّغْفِرَةٌۭ *(bağışlanma)* ve رِزْقٌۭ كَرِيمٌۭ *(değerli rızık)* — biri geçmişe ait bir silme, öteki geleceğe ait bir verme. Sûrenin TEK iltifâtı burada (12>3): bir önceki ayetin 1S/2MP hitabından üçüncü şahsa geçiliyor.",
51: "22:50 ile karşıt ikiz: aynı yapı (ٱلَّذِينَ + PERF fiil + أُو۟لَٰٓئِكَ/لَهُم), ters hüküm. Çaba bir hedefle nitelendiriliyor: سَعَوْا۟ فِىٓ ءَايَٰتِنَا مُعَٰجِزِينَ *(âyetlerimizi geçersiz kılmaya çalışarak)* — عجز *(âciz bırakma)* bab III ism-i fâil, yani karşılıklılık kalıbında. Karşı tarafın kim olduğu söylenmiyor.",
52: "Bloğun en yoğun ikileme ayeti: altı ayrı kök tekrarlanıyor. Yapı bir HASR ile kuruluyor — وَمَآ أَرْسَلْنَا … إِلَّآ إِذَا *(göndermedik ki… olmasın)*, aynı kalıp 21:25'te de vardı. Ama orada istisna vahyin içeriğiydi, burada bir olaydır. Zincir dört adımlı ve her adım bir kök ikilemesini kullanıyor: temenni (مني *(temenni, kuruntu)*) → atma (لقي *(atma, bırakma)*) → silme (نسخ *(silme, nesih)*) → sağlamlaştırma (حكم *(hüküm verme, hikmet)*). Son iki adımın fâili lafız, ilk ikisininki şeytan. Fâsıla mühür: kök حكم hem üçüncü adımda fiil hem mühürde sıfat.",
53: "Bir önceki ayete لِـ ile bağlanıyor — amaç cümlesi. Aynı nesne (مَا يُلْقِى ٱلشَّيْطَٰنُ *(şeytanın attığı)*) 22:52'de silinen şeydi, burada sınama malzemesi. Yani aynı öğe iki ayrı işlevde. Hedef iki grupla veriliyor ve ikisi de kalple tanımlanıyor: فِى قُلُوبِهِم مَّرَضٌۭ *(kalplerinde hastalık)* ve ٱلْقَاسِيَةِ قُلُوبُهُمْ *(kalpleri katılaşmış)* — biri içerik, öteki kıvam.",
54: "Üçüncü لِـ cümlesi: 22:52 → 53 → 54 üç ayet üst üste amaç zinciriyle bağlı. Bu ayette zincir ters yöne dönüyor — 53'ün sınaması burada bilgiye çevriliyor. Üç aşama sıralanıyor ve üçü de ayrı fiille: يَعْلَمَ *(bilsin)* → يُؤْمِنُوا۟ *(iman etsinler)* → تُخْبِتَ لَهُۥ قُلُوبُهُمْ *(kalpleri saygıyla yatışsın)*. Bilgi, inanç, hâl. Son aşamanın öznesi kişi değil kalp.",
55: "Şüphe süreklilik fiiliyle kuruluyor: وَلَا يَزَالُ *(sürdürürler)* — zeval bulmayan bir hâl. Bitiş iki seçenekle veriliyor ve ikisi de aynı fiille: تَأْتِيَهُمُ ٱلسَّاعَةُ *(saat gelir)* 3FS ve يَأْتِيَهُمْ عَذَابُ يَوْمٍ *(bir günün azabı gelir)* 3MS — aynı kök, iki cins. Son sıfat dikkat çekici: يَوْمٍ عَقِيمٍ *(kısır gün)*, عقم *(kısırlık)* — zaman bir doğurganlık terimiyle nitelendiriliyor, yani ardından hiçbir şey gelmeyen gün.",
56: "Mülk zamanla sınırlanıyor: ٱلْمُلْكُ يَوْمَئِذٍۢ لِّلَّهِ *(o gün mülk Allah'ındır)* — يَوْمَئِذٍ araya girerek sahipliği bir güne bağlıyor. Sonra hüküm ve ayrım geliyor. İkinci yarı sûrede dördüncü kez aynı diziyi kullanıyor: ءَامَنُوا۟ وَعَمِلُوا۟ ٱلصَّٰلِحَٰتِ *(iman edip salih işler yaptılar)* — 22:14, 22:23, 22:50 ve burada.",
57: "22:56 ile karşıt ikiz ve ikisi arasındaki fark tek bir yapıda: orada ٱلَّذِينَ ءَامَنُوا۟ وَعَمِلُوا۟, burada ٱلَّذِينَ كَفَرُوا۟ وَكَذَّبُوا۟ *(inkâr edip yalanladılar)*. İki fiil ikişerli ve karşıt. Karşılık da simetrik: orada جَنَّٰتِ ٱلنَّعِيمِ *(nimet bahçeleri)*, burada عَذَابٌۭ مُّهِينٌۭ *(aşağılayıcı azap)* — هون *(aşağılama, hor görme)* kökü sûrede 22:18'de de vardı.",
58: "Sûrenin en yoğun lafız ayeti: üç geçiş, on sekiz kelimede. Aynı kök رزق *(rızık)* de üç kez ve her seferinde başka biçimde: fiil (لَيَرْزُقَنَّهُمُ), mef'ûl-i mutlak (رِزْقًا), ism-i fâil çoğul (ٱلرَّٰزِقِينَ). İki ölüm biçimi ayrılıyor: قُتِلُوٓا۟ *(öldürüldüler)* edilgen ve dışarıdan, أَوْ مَاتُوا۟ *(ya da öldüler)* etken ve kendiliğinden — ama karşılık ikisinde de aynı.",
59: "Yedi kelime, üç te'kid (لَـ + نَّ + إِنَّ) ve bir mef'ûl-i mutlak: لَيُدْخِلَنَّهُم مُّدْخَلًۭا *(elbette sokar, bir sokuşla)* — aynı kök fiil ve nesne olarak. Sokulacak yer adlandırılmıyor; yalnız bir sıfat cümlesiyle nitelendiriliyor: يَرْضَوْنَهُۥ *(hoşnut olacakları)*. Yani mekân değil, mekâna karşı duyulan hâl veriliyor. Mühür çifti sûrenin yedi ardışık mühür kümesini açıyor.",
60: "Aynı kök iki kez ve çatısı ters: عَاقَبَ *(karşılık verdi)* etken, عُوقِبَ *(cezalandırıldı)* edilgen — misliyle karşılık verme bu iki biçimin eşitlenmesiyle tanımlanıyor (بِمِثْلِ مَا *(mislince)*). Sonra üçüncü bir edilgen ekleniyor: ثُمَّ بُغِىَ عَلَيْهِ *(sonra ona haksızlık edildi)*, yani denklem bir kez daha bozuluyor. Vaat bu ikinci bozulmaya bağlanıyor. Mühür çifti iki af kelimesi: عفو *(af, bağışlama)* ve غفر *(bağışlama, mağfiret)* — cezalandırma ayetinin sonunda iki bağışlama adı.",
}

om = json.load(open('okuma_metni.json', encoding='utf-8'))
mk = json.load(open('mercek_kayit.json', encoding='utf-8'))

for n in range(41, 61):
    key = "22:%d" % n
    om['22'][key] = {'ar': AR[(22, n)], 'meal': MEAL[n], 'olcum': OLCUM[n],
                     'mercek': MERCEK[n], 'dikey': DIK[key]}
    mk['22'].append([key, MERCEK[n]])

om['22']['_mercek_atlama_notu'] += (
 " 22:45 biyolog ve uzay ATLANDI — بأر *(kuyu)* · قصر *(köşk; kısaltma)* · شيد *(sağlam yapı)* "
 "yapı adları; ne canlılık ne gök çıpası var. "
 "NOT: 22:46 dört organ adı taşıyor (قلب *(çevirme, kalp)* · أذن *(izin; bildirme; kulak)* · "
 "بصر *(görme, basiret)* · صدر *(göğüs; çıkma)*) ama yıldız=0 olduğu için protokol gereği "
 "uzman merceği YAZILMADI — 22:18 ile aynı durum.")

om['ilerleme']['kismi']['22'] = "1-60 ayet düzeyinde"
om['ilerleme']['bekleyen']['22'] = "61-78"
om['ilerleme']['not'] = ("Sûre 20 TAM. Sûre 21 TAM (112/112). Sûre 22 (Hac) makro + 22:1-60. "
                         "Devam: 22:61. Dikey katman A parçası birincil, B etiketsiz.")
om['ilerleme']['okunan_ayet'] = 1445

json.dump(om, open('okuma_metni.json', 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
json.dump(mk, open('mercek_kayit.json', 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
print("yazıldı · mercek 22:", len(mk['22']))
