# -*- coding: utf-8 -*-
"""blok_24_21_30.py — sûre 24 blok 24:21-30 (yarım blok; gerekçe kayıtta)."""
import json
DIK=json.load(open('blok_dikey_24_21_40.json',encoding='utf-8'))
veri=json.load(open('kuran_veri.json',encoding='utf-8'))
AR={}
for s in veri['sureler']:
    for a in s['ayetler']: AR[(s['no'],a['no'])]=a['ar']

MEAL={
21:"Ey inananlar, şeytanın adımlarına uymayın. Kim şeytanın adımlarına uyarsa, o hayâsızlığı ve kötülüğü buyurur. Allah'ın size lütfu ve merhameti olmasaydı, içinizden hiçbiri asla arınamazdı; ama Allah dilediğini arındırır. Allah işitendir, bilendir.",
22:"İçinizden lütuf ve genişlik sahipleri, yakınlara, yoksullara ve Allah yolunda hicret edenlere vermemeye yemin etmesinler. Affetsinler, hoş görsünler. Allah'ın sizi bağışlamasını istemez misiniz? Allah bağışlayandır, merhamet edendir.",
23:"İffetli, habersiz, mü'min kadınlara iftira atanlar dünyada da âhirette de lânetlenmişlerdir; onlara büyük bir azap vardır.",
24:"O gün dilleri, elleri ve ayakları yaptıklarına karşı onların aleyhine tanıklık eder.",
25:"O gün Allah onlara hak ettikleri karşılığı tam verir; bilirler ki Allah apaçık gerçeğin ta kendisidir.",
26:"Kötü kadınlar kötü erkeklere, kötü erkekler kötü kadınlara; temiz kadınlar temiz erkeklere, temiz erkekler temiz kadınlara. İşte onlar, söylenenlerden uzaktırlar; onlara bağışlanma ve cömert bir rızık vardır.",
27:"Ey inananlar, kendi evlerinizden başka evlere, izin isteyip halkına selâm vermeden girmeyin. Bu sizin için daha hayırlıdır, belki düşünürsünüz.",
28:"Orada kimseyi bulamazsanız, size izin verilinceye kadar girmeyin. Size \"dönün\" denirse dönün; bu sizin için daha arıtıcıdır. Allah yaptıklarınızı bilir.",
29:"İçinde eşyanız bulunan, oturulmayan evlere girmenizde size bir vebal yoktur. Allah açığa vurduğunuzu da gizlediğinizi de bilir.",
30:"Mü'min erkeklere söyle: bakışlarını indirsinler ve ırzlarını korusunlar. Bu onlar için daha arıtıcıdır. Allah yaptıklarından haberdardır.",
}

OLCUM={
21:"eksen: **Allah lafzı 18., 28. ve 32. sırada — üç geçiş** (allah z=1,24) · **esmâ سَمِيع *(semîʼ)* 33. + عَلِيم *(alîm)* 34. sırada — MÜHÜR, çift kapanış; GEÇERLİ**; **esmâ أَحَد *(bir)* 25. sırada — ÖLÇÜM ARTEFAKTI (aday 461)**: مِّنْ أَحَدٍ *(hiçbiri)*, sayı sözcüğü · **aktör: adlı شَيْطان *(şeytan)* 7. ve 11. sırada, tür 'gayb', rol mecrur — sûrenin tek adlı aktörü, iki geçişi de bu ayette** · edim yasak + nida + şart, kip VOC 1 · PRO 1 · COND ×2 · NEG 1 · şahıs 3MP ×2 · 2MP ×4 · 3MS ×7 · **n=34 mora=189 harf=156 — bloğun en uzun ayeti** (n z=2,29), **fâsıla عَلِيمٌۭ → م**, N sınıfı; i'râb ACC 6 · GEN 7 · NOM 5; bab I ×3 · II ×1 · IV ×1 · VIII ×2; zaman PERF ×2 · IMPF ×5; **kök ikilemesi تبع *(uyma, ardından gitme)* ×2 · خطو *(adım)* ×2 · شطن *(şeytan)* ×2 · أله *(ilâh; lafza-i celâl)* ×3 · زكو *(arınma, temizlik)* ×2 — beş kök birden**; biçim NEHY · DIKKAT; simetri [4,6,10,1]; **dış düğüm 4** · yıldız ★★ · kökler أيي *(âyet, işaret; hangi)* · أمن *(güven; iman)* · تبع · خطو · شطن · أمر *(emir; iş)* · فحش *(çirkinlik, hayâsızlık (fahşâ))* · نكر *(tanımama, inkâr; çirkin)* · فضل *(üstün kılma, lütuf)* · أله · رحم *(rahmet, merhamet)* · زكو · أحد *(bir, hiç kimse)* · أبد *(ebedîlik)* · شيأ *(dileme; şey)* · سمع *(işitme)* · علم *(bilme)* · bağ: xref اتّبع *(uydu)* + خطوة *(adım)* + شيطان *(şeytan)* → **2:168 · 2:208 · 6:142**; **24:10 · 24:14 · 24:20 · 24:21 — kalıp DÖRDÜNCÜ kez ve cevap VAR** (elle, L1, aday 505)",
22:"eksen: **Allah lafzı 15., 22. ve 24. sırada — üç geçiş** (allah z=1,78) · **esmâ غَفُور *(gafûr)* 25. + رَحِيم *(rahîm)* 26. sırada — MÜHÜR, çift kapanış; GEÇERLİ** · aktör yok · edim soru + emir + yasak, kip PRO 1 · IMPV ×2 · INTG 1 · NEG 1 · şahıs 3MS ×2 · 2MP ×4 · 3MP ×6 · n=26 mora=143 harf=130 (n z=1,44), **fâsıla رَّحِيمٌ → م**, N sınıfı; i'râb NOM 5 · GEN 5 · ACC 3; bab I ×3 · IV ×2 · VIII ×1; **zaman IMPF ×6 — ayetin altı fiili de muzâri**; kök ikilemesi أله *(ilâh; lafza-i celâl)* ×3 · غفر *(bağışlama, mağfiret)* ×2; biçim NEHY; simetri [3,1,5,1]; dış düğüm 1 · yıldız ★ · kökler ألو *(yemin etme; kusur etme; nimetler (âlâ))* · فضل *(üstün kılma, lütuf)* · وسع *(genişlik, kuşatma)* · أتي *(gelme, getirme)* · قرب *(yakınlık)* · سكن *(sükûn; mesken, konut)* · هجر *(hicret, terk etme)* · سبل *(yol)* · أله · عفو *(af)* · صفح *(hoşgörü, bağışlama)* · حبب *(sevgi, sevme)* · غفر · رحم *(rahmet, merhamet)* · bağ: xref غفر + اللّه *(Allah)* + اللّه → 63:6; **24:21 ile ortak فضل** — orada lafzın lütfu, burada insanın (elle, L1)",
23:"eksen: lafız yok · **esmâ آخِر *(son)* 10. sırada — ÖLÇÜM ARTEFAKTI (aday 461)** · aktör yok · edim haber · şahıs 3MP ×5 · n=13 mora=82 harf=67, **fâsıla عَظِيمٌۭ → م**, N sınıfı; i'râb ACC 4 · GEN 2 · NOM 2; bab I ×2; zaman IMPF 1 · PERF 1; **edilgen 1 — pas z=2,52** · yıldız ★★ · kökler رمي *(atma)* · حصن *(koruma, sağlamlaştırma; iffet)* · غفل *(gaflet, habersizlik)* · أمن *(güven; iman)* · لعن *(lânet, kovma)* · دنو *(yakınlık; dünya)* · أخر *(geciktirme, sonraya bırakma)* · عذب *(azap)* · عظم *(büyüklük, azamet; kemik)* · bağ: xref دنيا *(dünya)* + آخر *(âhiret)* + عذاب *(azap)* → 5:33 · 59:3; **24:4 ile ortak رمي + حصن**; **24:7 ile ortak لعن** — orada şarta bağlı bedduâ, burada gerçekleşmiş hüküm (elle, L1)",
24:"eksen: lafız yok · aktör yok · edim haber · şahıs 3FS 1 · 3MP ×8 · n=9 mora=53 harf=48, fâsıla يَعْمَلُونَ *(yaparlar)* → ن, N sınıfı; i'râb ACC 1 · NOM 3; bab I ×3; zaman IMPF ×2 · PERF 1 · yıldız ★ yok · kökler يوم *(gün)* · شهد *(şahitlik)* · لسن *(dil)* · يدي *(el)* · رجل *(adam; yaya)* · كون *(olmak)* · عمل *(iş, amel)* · bağ: **24:15 ile ortak لسن** — orada dil iftiranın aracı (بِأَلْسِنَتِكُمْ *(dillerinizle)*), burada tanıklığın öznesi (elle, L1)",
25:"eksen: **Allah lafzı 3. ve 8. sırada — n=11'de İKİ lafız, allah z=3,11: yıldızın tek kaynağı (aday 472/503)** · **esmâ مُبِين *(apaçık)* 11. sırada = fâsıla — GEÇERLİ**: ٱلْحَقُّ ٱلْمُبِينُ *(apaçık gerçek)*, doğrudan lafzın yüklemi · aktör yok · edim haber · şahıs 3MS ×2 · 3MP ×4 · n=11 mora=62 harf=50, fâsıla ٱلْمُبِينُ → ن, N sınıfı; i'râb NOM 3 · ACC 4; bab I ×1 · bab II ×1; zaman IMPF ×2; kök ikilemesi أله *(ilâh; lafza-i celâl)* ×2 · حقق *(hak, gerçek)* ×2; simetri [3,3,8,1]; dış düğüm 1 · yıldız ★★★ · kökler يوم *(gün)* · وفي *(tam verme, vefa; vefat ettirme)* · أله · دين *(din; borç)* · حقق · علم *(bilme)* · بين *(arası; açıklama)* · bağ: xref اللّه + حقّ *(hak)* + مبين *(apaçık)* → 27:79; **24:2 ile ortak دين** — orada دِينِ ٱللَّهِ *(Allah'ın dini)*, burada دِينَهُمُ ٱلْحَقَّ *(hak ettikleri karşılık)* (elle, L1)",
26:"eksen: lafız yok · **esmâ كَرِيم *(kerîm)* 16. sırada — ÖLÇÜM ARTEFAKTI (aday 461)**: رِزْقٌ كَرِيمٌ *(cömert rızık)* tamlamasında niteleyen, ölçüt (c) · aktör yok · edim haber · şahıs 3MP ×3 · n=16 mora=130 harf=102, **fâsıla كَرِيمٌۭ → م**, N sınıfı; **i'râb NOM 8 · GEN 4 — on iki isimden hiçbiri mansûb değil**; bab I ×1; zaman IMPF 1; **kök ikilemesi خبث *(pislik, habislik)* ×4 · طيب *(temiz, hoş)* ×4 — n=16'da sekiz token iki kökten** · yıldız ★ yok · kökler خبث · طيب · برأ *(uzak durma, berî olma; yaratma)* · قول *(söz söyleme)* · غفر *(bağışlama, mağfiret)* · رزق *(rızık)* · كرم *(üstün tutma, ikram)* · bağ: **24:3 ile aynı sözdizim** — orada iki eşleştirme ve HASR, burada dört eşleştirme ve fiilsiz (elle, L1, aday 504)",
27:"eksen: lafız yok · aktör yok · edim yasak + nida, kip VOC 1 · PRO 1 · şahıs 3MP ×2 · 2MP ×11 · 3FS 1 · n=18 mora=113 harf=91, fâsıla تَذَكَّرُونَ *(düşünürsünüz)* → ن, N sınıfı; i'râb ACC 4 · GEN 2 · NOM 1; **bab I ×1 · II ×1 · IV ×1 · V ×1 · X ×1 — beş ayrı bab, her biri bir kez**; zaman PERF 1 · IMPF ×4; kök ikilemesi بيت *(ev, mesken)* ×2; biçim NEHY · DIKKAT; simetri [3,2,12,1]; dış düğüm 2 · yıldız ★ yok · kökler أيي *(âyet, işaret; hangi)* · أمن *(güven; iman)* · دخل *(girme)* · بيت · غير *(başka)* · أنس *(insan; ünsiyet)* · سلم *(esenlik; teslim olma)* · أهل *(halk, aile)* · خير *(hayır, daha iyi)* · ذكر *(anma, zikir)* · bağ: xref آمن *(iman etti)* + دخل *(girdi)* + بيت *(ev)* → **33:53**; **24:1 ile aynı fâsıla** تَذَكَّرُونَ — sûrenin açılış ayeti ve bu ayet aynı kelimeyle bitiyor (elle, L1)",
28:"eksen: **Allah lafzı 19. sırada** (allah z=0,38) · **esmâ عَلِيم *(alîm)* 22. sırada = fâsıla — GEÇERLİ**; **esmâ أَحَد *(bir)* 5. sırada — ÖLÇÜM ARTEFAKTI (aday 461)** · aktör yok · edim emir + yasak + şart, kip COND ×2 · NEG 1 · PRO 1 · IMPV ×2 · şahıs 2MP ×13 · 3FS ×2 · 3MS ×3 · n=22 mora=108 harf=95 (n z=1,02), **fâsıla عَلِيمٌۭ → م**, N sınıfı; i'râb ACC 1 · NOM 3; **bab I ×7 — yedi fiilin yedisi de birinci bab**; zaman IMPF ×4 · PERF 1 · IMPV ×2; **edilgen 2** (pas z=1,30); kök ikilemesi رجع *(dönme, geri döndürme)* ×2; biçim NEHY; simetri [4,1,10,1]; dış düğüm 1 · yıldız ★ yok · kökler وجد *(bulma)* · أحد *(bir, hiç kimse)* · دخل *(girme)* · أذن *(izin verme; kulak)* · قول *(söz söyleme)* · رجع · زكو *(arınma, temizlik)* · أله *(ilâh; lafza-i celâl)* · عمل *(iş, amel)* · علم *(bilme)* · bağ: xref اللّه + عمل *(amel)* + عليم *(bilen)* → 2:283; **24:21 ile ortak زكو** — orada lafız arındırıyor, burada bir davranış 'daha arıtıcı' sayılıyor (elle, L1)",
29:"eksen: **Allah lafzı 12. sırada** (allah z=0,65) · aktör yok · edim haber · şahıs 3MS ×2 · 2MP ×8 · 3FS 1 · n=17 mora=89 harf=73, fâsıla تَكْتُمُونَ *(gizlersiniz)* → ن, N sınıfı; i'râb NOM 3 · ACC 2 · GEN 1; bab I ×4 · bab IV ×1; zaman PERF 1 · IMPF ×4; simetri [3,2,9,1]; dış düğüm 1 · yıldız ★ yok · kökler ليس *(değil)* · جنح *(kanat; yan taraf)* · دخل *(girme)* · بيت *(ev, mesken)* · غير *(başka)* · سكن *(sükûn; mesken, konut)* · متع *(faydalanma, geçimlik)* · أله *(ilâh; lafza-i celâl)* · علم *(bilme)* · بدو *(açığa çıkma, görünme)* · كتم *(gizleme)* · bağ: xref اللّه + علم *(bildi)* + يبدي *(açığa vurur)* → 5:99; **24:27 ile istisna** — aynı üç kök (دخل · بيت · غير), orada yasak burada muafiyet (elle, L1)",
30:"eksen: **Allah lafzı 12. sırada** (allah z=0,81) · **esmâ خَبِير *(habîr)* 13. sırada — GEÇERLİ**: doğrudan lafzın yüklemi; **esmâ مُؤْمِن *(mü'min)* 2. sırada — ÖLÇÜM ARTEFAKTI (aday 461)** · aktör yok · edim emir, kip IMPV 1 · şahıs 2MS 1 · 3MP ×9 · n=15 mora=80 harf=70, fâsıla يَصْنَعُونَ *(yaparlar)* → ن, N sınıfı; i'râb GEN 2 · ACC 3 · NOM 2; bab I ×4; zaman IMPV 1 · IMPF ×3 · yıldız ★ yok · kökler قول *(söz söyleme)* · أمن *(güven; iman)* · غضض *(indirme, kısma)* · بصر *(görme)* · حفظ *(koruma)* · فرج *(ırz; yarık, aralık)* · زكو *(arınma, temizlik)* · أله *(ilâh; lafza-i celâl)* · خبر *(haber; haberdar olma)* · صنع *(yapma, işleme)* · bağ: **23:5 ile ortak حفظ + فرج** — orada sıfat zincirinin halkası ve ism-i fâil, burada buyruk; kip dönüşümü nitelik → talimat (elle, L1, aday 506)",
}

MERCEK={
21:"Üçlü sandığımız şart kalıbı dördüncü kez dönüyor ve bu kez cevap yazılıyor — مَا زَكَىٰ مِنكُم مِّنْ أَحَدٍ أَبَدًا *(içinizden hiçbiri asla arınamazdı)*. Kalıp 24:10 · 24:14 · 24:20 · 24:21 dizisinde iki kez cevapsız, iki kez cevaplı. Ölçülebilir yeni ayrım: cevaplı iki örnekte fiil var, cevapsız ikisinde yok. Şeytan iki kez ve ikisi de aynı terkiple: خُطُوَٰتِ ٱلشَّيْطَٰنِ *(şeytanın adımları)*; dikey ölçüm çiftin korpusta sabit olduğunu veriyor (خطو ▸sonra شطن ×97,9). Arınma kökü de iki kez, biri olumsuz biri olumlu: insanın yapamadığı, lafzın yaptığı.",
22:"İki ayet arka arkaya aynı kökle açılıyor ama yön değişiyor: 24:21'de فَضْلُ ٱللَّهِ *(Allah'ın lütfu)*, burada أُو۟لُوا۟ ٱلْفَضْلِ *(lütuf sahipleri)* — aynı sözcük ilâhî ve beşerî konumda. İnsanın affetmesi ile bağışlanması aynı zincire bağlanıyor; dikey ölçüm zinciri veriyor: عفو *(af)* ▸sonra صفح *(hoşgörü, bağışlama)* ×112,7, صفح ▸sonra غفر *(bağışlama, mağfiret)* ×12,6. Yasak da olağandışı: yasaklanan şey vermemek değil, vermemeye YEMİN ETMEK.",
23:"Nesne üç sıfatla üst üste niteleniyor: ٱلْمُحْصَنَٰت *(iffetli)* · ٱلْغَٰفِلَٰت *(habersiz)* · ٱلْمُؤْمِنَٰت *(mü'min)* — üçü de dişil çoğul ve belirli. 24:4'te tek sıfat vardı. Fiil edilgen: لُعِنُوا۟ *(lânetlendiler)* — 24:7'de lânet bir şartın sonucuydu ve fâili lafızdı, burada fâil silinmiş ve olay olmuş bitmiş. لعن *(lânet, kovma)* kökünün Allah medyan mesafesi 2, ama bu ayette lafız hiç geçmiyor.",
24:"Tanıklık teması sûrede beşinci kez ve bu kez tanık insan değil, organ. Üç organ sayılıyor ve sıra yukarıdan aşağı: dil, el, ayak. Dikey ölçüm يدي *(el)* ▸sonra ayak ×30,6 veriyor — son ikisi korpusta zaten bitişik; dilin öne eklenmesi bu ayete özgü. 24:15'te aynı organ iftiranın aracıydı; burada aleyhe tanık.",
25:"Aynı kök on bir kelimede iki kez ve iki ayrı işlevde: حقق *(hak, gerçek)* önce verilen karşılığın sıfatı, sonra lafzın yüklemi. Ve دين *(din; borç)* kökü sûrede ikinci kez, burada 'karşılık, hesap' anlamında — 24:2'de 'din' anlamındaydı. Ölçülebilir bir kapanış: ayet bir ödeme fiiliyle açılıp bir bilme fiiliyle bitiyor.",
26:"On altı kelimenin sekizi iki kökten ve dört kez cinsiyet çevriliyor. Dikey ölçüm bu iki kökün korpusta zaten karşıt çift olduğunu veriyor — خبث *(pislik, habislik)* ▸sonra طيب *(temiz, hoş)* ×167,6 ve طيب ▸önce خبث ×157,5, iki yönde de. İlk on iki kelimede TEK FİİL YOK; ayet dört isim cümlesini yan yana koyup bağlaç bile kullanmıyor. Bu, 24:3'ün yapısının genişletilmiş hâli: orada iki eşleştirme, burada dört.",
27:"Sûrenin en zengin kökü burada başlıyor: بيت *(ev, mesken)* korpus payına göre ×11,21 ile sûrenin en zenginleşmiş kökü, ve ilk iki geçişi bu ayette — biri belirsiz, biri iyelikli. Ölçülebilir bir bab dağılımı: beş fiil, beş ayrı bab, her biri bir kez; blokta başka örneği yok. Fâsıla 24:1'in fâsılasını tekrarlıyor.",
28:"İzin kökü sûrenin ikinci en zengin kökü olarak burada başlıyor: أذن *(izin verme; kulak)* ×5,16. İki edilgen fiil arka arkaya — يُؤْذَنَ *(izin verilir)* ve قِيلَ *(denir)*: izin verenin ve söyleyenin adı geçmiyor, oysa ayet lafızla kapanıyor. Ölçülebilir bir tekrar: aynı kök emir kipinde iki kez üst üste (ٱرْجِعُوا۟ فَٱرْجِعُوا۟ *(dönün, dönün)*) — biri aktarılan söz, öteki buyruk.",
29:"Yasak iki ayet sonra bir istisnayla dengeleniyor ve istisna aynı üç kökü kullanıyor: girme, ev, başka. Fark tek bir sıfatta — غَيْرَ مَسْكُونَةٍ *(oturulmayan)*, سكن *(sükûn; mesken, konut)* kökünden ism-i mef'ûl. Muafiyetin ölçütü mülkiyet değil, ikamet. Kapanış bir karşıt çiftle: بدو *(açığa çıkma, görünme)* / كتم *(gizleme)*; dikey ölçüm ikisinin korpusta zaten eşleştiğini veriyor (بدو ▸sonra كتم ×35,9).",
30:"İki sûre arayla aynı kök çifti dönüyor: 23:5'te حفظ *(koruma)* + فرج *(ırz; yarık, aralık)* bir sıfat zincirinin halkasıydı ve ism-i fâildi; burada emir kipinde bir buyruk. Kip dönüşümü: nitelik → talimat. Göz için seçilen fiil غضض *(indirme, kısma)*, korpusta dört geçişli; dikey ölçüm ▸sonra صوت *(ses)* ×837,8 veriyor — kök korpusta neredeyse yalnız sesin kısılmasıyla eşleşiyor, burada bakışa aktarılmış. Ayrıca kısmî bir sınır: مِنْ أَبْصَٰرِهِمْ *(bakışlarından)*, harf-i cer ile — tamamı değil, bir kısmı.",
}

ATLAMA={
 "24:25":"★★★ ayet. 🜁 biyolog ve 🜂 uzay YAZILMADI — yedi kökün hiçbiri (يوم *(gün)* · وفي *(tam verme)* · أله *(lafza-i celâl)* · دين *(din)* · حقق *(hak)* · علم *(bilme)* · بين *(açıklama)*) canlıya, organa, sürece ya da gök öğesine bağlanmıyor; يوم burada يَوْمَئِذٍ *(o gün)* biçiminde bir olay zamanı.",
 "_blok_notu_24_21_30":"Blok 24:21-30'da tek ★★★ ayet (24:25) ve iki mercek de atlandı; kaynağı allah z=3,11. NOT: 24:24 ve 24:30 beden terimleri taşıyor (لسن *(dil)* · يدي *(el)* · رجل *(ayak)* · بصر *(görme)* · فرج *(ırz)*) ama ikisi de ★ almadı — biyolog merceği yine devreye giremedi. Blok 24:31-40'ta 24:35 (زيتونة *(zeytin ağacı)* · كوكب *(yıldız)*) hem biyolog hem uzay için çıpa taşıyor; orada ölçülecek.",
}

p='/home/claude/repo/notlar/okuma_metni.json'
OM=json.load(open(p,encoding='utf-8'))
for n in range(21,31):
    OM['24']["24:%d"%n]={"ar":AR[(24,n)],"meal":MEAL[n],"olcum":OLCUM[n],
                         "mercek":MERCEK[n],"dikey":DIK["24:%d"%n]}
OM['24']['_mercek_atlama_notu'].update(ATLAMA)
OM['24']['_blok_bolme_notu']=("Blok 24:21-40 İKİYE BÖLÜNDÜ (24:21-30 ve 24:31-40). Gerekçe ölçüm: "
  "ikinci yarıda üç ayet korpusun en uzunları arasında — 24:31 (n=78, okumada görülen en uzun ayet), "
  "24:33 (n=48), 24:35 (n=48); üçü birlikte 174 kelime. Tam kip her ayette korunsun diye bölündü. "
  "Blok akışı 20 ayet kuralı okuma HIZI kuralıdır, biçim kuralı değil; ölçüm ve kayıt biçimi değişmedi.")
OM['ilerleme']['not']=("Sûre 23 TAM (118/118). Sûre 24 (Nûr) makro profil + 24:1-30 okundu. "
                       "Devam: 24:31. UYARI: 24:31 n=78, okumada görülen en uzun ayet; "
                       "24:33 ve 24:35 n=48. 24:35'te hem biyolog hem uzay merceği için çıpa var.")
OM['ilerleme']['kismi']={"2":"1-20 ayet düzeyinde","24":"1-30 ayet düzeyinde"}
OM['ilerleme']['okunan_ayet']=1611
json.dump(OM,open(p,'w',encoding='utf-8'),ensure_ascii=False,indent=1)
print('okuma_metni: sûre 24 →',len([k for k in OM['24'] if not k.startswith('_')]),'ayet')

pm='/home/claude/repo/notlar/mercek_kayit.json'
MK=json.load(open(pm,encoding='utf-8'))
for n in range(21,31): MK['24']["24:%d"%n]=MERCEK[n]
MK['24_atlama'].update(ATLAMA)
json.dump(MK,open(pm,'w',encoding='utf-8'),ensure_ascii=False,indent=1)
print('mercek_kayit: sûre 24 →',len(MK['24']),'mercek')
