# -*- coding: utf-8 -*-
"""fatir_metin_1.py — sûre 35 (Fâtır) meal ve matematikçi merceği, ayet 1-45.
Arapça sabit YOK: kökler yalnız korpus kök biçimiyle anılır, kelime biçimleri Latin harfle."""
MEAL = {
 1: "Hamd, gökleri ve yeri yoktan yaratan, melekleri ikişer, üçer, dörder kanatlı elçiler kılan Allah'adır. Yaratmada dilediğini artırır. Şüphesiz Allah her şeye gücü yetendir.",
 2: "Allah insanlara bir rahmet açarsa onu tutabilecek yoktur; neyi tutarsa ondan sonra onu salıverecek yoktur. O, mutlak güç sahibidir, hikmet sahibidir.",
 3: "Ey insanlar! Allah'ın üzerinizdeki nimetini anın. Sizi gökten ve yerden rızıklandıran Allah'tan başka bir yaratıcı var mı? O'ndan başka ilâh yoktur. Öyleyse nasıl (haktan) çevriliyorsunuz?",
 4: "Seni yalanlıyorlarsa, senden önce de elçiler yalanlandı. Bütün işler Allah'a döndürülür.",
 5: "Ey insanlar! Allah'ın vaadi gerçektir. Dünya hayatı sizi aldatmasın; o aldatıcı da sizi Allah hakkında aldatmasın.",
 6: "Şeytan size düşmandır; siz de onu düşman edinin. O, taraftarlarını yalnızca alevli ateşin halkından olmaları için çağırır.",
 7: "İnkâr edenler için çetin bir azap vardır; iman edip salih ameller işleyenler için ise bağışlanma ve büyük bir ödül vardır.",
 8: "Kötü ameli kendisine süslü gösterilip de onu güzel gören kimse mi (doğru yolda olan gibidir)? Şüphesiz Allah dilediğini saptırır, dilediğini doğru yola iletir. Onlar için üzülerek kendini helâk etme. Allah onların yaptıklarını hakkıyla bilendir.",
 9: "Allah, rüzgârları gönderendir; onlar bulutu kabartır, biz de onu ölü bir beldeye sürer, onunla yeri ölümünden sonra diriltiriz. Diriliş de böyledir.",
 10: "Kim izzet istiyorsa, bilsin ki izzetin tamamı Allah'ındır. Güzel söz O'na yükselir; salih ameli de O yükseltir. Kötülükleri tuzak kuranlar için çetin bir azap vardır; onların tuzağı boşa çıkacaktır.",
}
M = {
 1: "◇ Sûre hamd ile açılıyor: ilk kelimesi hamd kökü olan sûre açılışları korpusta dört — 6, 18, 34, 35 (TAM SAYIM, morfoloji ilk kelime) — ve son ikisi ARDIŞIK: Sebe' ile Fâtır art arda hamdla açılıyor. Fâtır lemması korpusta 6 ayet, altısı da 'gökleri ve yeri yaratan' tamlamasında; bir sûreyi açan tek geçiş burası. Ayetin ikinci yarısı bir SAYI DİZİSİ: mesnâ · sülâs · rubâ' (ikişer, üçer, dörder) — ثني ثلث ربع üçü de [1/1]. Bu üçlü korpusta YALNIZ iki ayette: 4:3 (nikâh sayısı) ve 35:1 (meleklerin kanatları), xref de 4:3'ü veriyor; mesnâ ayrıca 34:46'da (ikişer ve teker teker) — bitişik sûrenin son blokundan. Aynı sayı dizisi iki ayrı alana uygulanıyor: insan ilişkisi / melek yapısı. Kanat lemması korpusta 7 ayet; yalnız burada meleklerin. Dizinin sonu açık: 'yaratmada dilediğini artırır' — sayılı küme sınırlanmıyor. say alanı üçünü yakaladı: DOĞRU POZİTİF ×3 (981 ailesinin karşı vakası). Esmâ: qadîr inne haberi, ilâhî; §4.3 mühür EVET, ton celâl. Ölçüm satırı 'MÜHÜRSÜZ' diyor — eski token düzeyi alan (#9/#12, aday 908/930), §4.3 kaydı esas. 🜁 L0, olgu evet (gökler ve yer adlanıyor); sayılar meleklere ait, doğal olgu değil. TARAYICI v4 ADAY VERDİ (F_ölçü — sayı kelimeleri), çıpa değil.",
 2: "◇ Bir AYNA, tek ayette: açarsa → tutan yok | tutarsa → salıveren yok. İki şart, iki 'fe-lâ' olumsuzluğu (kip NEG 2), ikinci yarı birincinin tersi. مسك [1,2/4] ve فتح [1/1] — bu iki kök korpusta YALNIZ bu ayette birlikte (TAM SAYIM). İkinci olumsuzun fiili gönderme kökünden (mursil): رسل [2/6] — 35:1'de meleklerin elçiliği, burada rahmetin salıverilmesi. Mühür azîz-hakîm ÇİFT, geçerli (huve'nin haberi), ton celâl. Bağ YOK (esit2, nakarat3, xref üçü de boş): sûrenin ikinci ayeti korpusta eşsiz bir terkip.",
 3: "◇ Sûrenin ilk nidâsı: 'ey insanlar' (biçim DIKKAT). Soru-HASR: 'Allah'tan başka yaratıcı var mı?' → 'O'ndan başka ilâh yok'. Lafız iki token, kök satırında أله [4,5,6/37] — ayette üç anma (lafız ×2 + ilâh). خلق [2/5]: 35:1'de yaratmada artırma, burada yaratıcının tekliği. Rızık gökten ve yerden — سمو [2/9] ve أرض [2/10] 35:1'deki çiftin ikinci anması. Esmâ hâlık: 'Allah'tan başka' olumsuzlanan konumda → değil (e_oto 1, e_el 0). ★ tek kaynak pas z=1,57 (tü'fekûn, 1/3). 🜁 L0, olgu evet (gök ve yer adlanıyor, süreç yok). TARAYICI v4 ADAY VERDİ (D_yeti), çıpa değil.",
 4: "◇ İki kez yalanlama: yükezzibûke (seni yalanlarlarsa, etken) → küzzibet (elçiler yalanlandı, EDİLGEN) — كذب [1,2/4], aynı kök şimdiki muhataptan geçmiş elçilere. Ayet 11 kelime ve 3 fiilin 2'si edilgen: küzzibet, turja'u ('işler döndürülür', döndüren adsız). ★★★ tek kaynak pas z=3,48 — hapaks DEĞİL, uzunluk değil: ★★★ sûre 34'te 4/4 hapakstan geliyordu (aday 983), burada edilgenden. رسل [3/6]: 35:1 melek elçiler, 35:2 rahmetin salıverilmesi, 35:4 peygamber elçiler. nakarat3 'in kezzebe fe-qad kezzebe' sûre içi, eşi 35:25 (defterden: kalıp → 35:4, 35:25) — henüz okunmadı. xref 3:184 ve 6:34 (önceki elçilerin yalanlanması).",
 5: "◇ İkinci nidâ, yine 'ey insanlar' — 35:3 ile aynı hitap, iki ayet arayla. غرر [1,2,3/4]: aldatma kökü tek ayette ÜÇ kez — iki fiil (teğurrannekum, yeğurrannekum) + bir isim (el-ğarûr). İlk aldatıcı 'dünya hayatı', ikincisi adsız 'o aldatıcı'; ğarûr lemması korpusta 3 ayet (31:33, 35:5, 57:14). Ayetin ikinci cümlesi 31:33'ün son cümlesiyle aynı (xref beş üçlünün beşi de 31:33'e) — sûre 31 okundu, bağ kaydedildi. Allah lafzı iki token 14 kelimede: ★★ tek kaynak allah z=2,33.",
 6: "◇ Ayette lafız YOK, Rab YOK, esmâ yok — sınıf 0. Tek adlı aktör şeytan (rol meful). عدو [1,2/2] aynı ayette açılıp kapanıyor: 'size düşmandır' → 'onu düşman edinin' — düşmanlık karşılıklı kılınıyor, ilişki iki yönlü. Ters yönlü ikinci yapı: şeytan 'çağırır' (yed'û), çağrının amacı alevli ateşin halkı (ashâbu's-sa'îr; xref 67:10). 35:5'teki adsız aldatıcı burada adıyla (komşu ayet okuması; ölçüm bu bağı kurmuyor).",
 7: "◇ AYNA ÇİFTİ tek ayette: inkâr edenler → çetin azap | iman edip salih amel işleyenler → bağışlanma + büyük ödül. 34:4-5'te aynı ayna İKİ ayete yayılıyordu, burada tek ayette. Lafız YOK, Rab YOK. Esmâ kebîr ödülün sıfatı → değil; §4.3 mühür e_oto ile EVET ama e_el ile YOK (sınıf oto E, el 0) — YANLIŞ MÜHÜR, sûrede ilk. Bağlar: nakarat3 'ellezîne keferû lehüm' sûre içi, eşi 35:36; nakarat3 'lehüm azâbün şedîd' sûre içi, eşi 35:10 (kalıp korpusta ayrıca 42:16, 42:26). xref 11:11, 67:12 (mağfiret + büyük ödül).",
 8: "◇ Algı ile durum ayrılıyor: kötü ameli 'süslü gösterilmiş' (zuyyine, EDİLGEN, süsleyen adsız) ve onu 'güzel görüyor' (raâhu hasenâ) — سوأ ile حسن aynı nesne için, biri durum biri görünüş. Süsleme + kötülük + amel kökleri birlikte korpusta 4 ayette (9:37, 35:8, 40:37, 47:14). İkinci yapı simetrik: dilediğini saptırır / dilediğini doğru yola iletir — ضلل [1/1] ve هدي [1/2] aynı 'men yeşâ'' ile, شيأ [3,4/8]. Hitap tek kez 2MS'ye dönüyor: 'kendini helâk etme' (nefsüke) — muhatap Peygamber. Fâsıla يصنعون (ن): blokun TEK kafiye kırığı (ölçüm; 35:3 de ن ile bitiyor ama kırık sayılmıyor). ★ KAYNAĞI KAFİYE KIRIĞI: diğer bileşenlerin hepsi 1,5'in altında (n 1,34 · allah 1,07 · pas 0,38) — bilanço bunu yanlış etiketleyecek (aday 1001). Esmâ alîm inne haberi, ilâhî; §4.3 mühür EVET, ton denge (ölçüm satırının 'MÜHÜRSÜZ'ü eski alan).",
 9: "◇ Dört aşamalı bir süreç, her aşama 'fe' ile bağlı: rüzgârları gönderir → bulutu kabartır → ölü bir beldeye süreriz → onunla yeri diriltiriz. Fail ayet içinde değişiyor: Allah (3MS, ersele) → biz (1P, suqnâhu, ahyeynâ) — ölçüm iltifât 0 diyor; lafız→zamir geçişi bilinen tagger açığı (aday 517 ailesi), metin hakkında kanıt değil. موت [1,2/4] iki kez: ölü belde, yerin ölümü. Ayet bir benzetmeyle kapanıyor: 'diriliş de böyledir' — doğal süreç diriliş iddiasının modeli. Aynı olgu 30:48'de (xref üç üçlü) beş aşamalı ve ara durumlar adlı (bulut, parça, yağmur, çıkış yeri) → L4'tü; 30:24'te iki aşama → L2. Burada yağmur adlanmıyor ('onunla' buluta dönüyor), yalnız bulut ara durum: 🜁 L2, olgu evet, çıpa değil. Aynı olgu üç ayette üç kademe: aşama sayısı kademeyi belirliyor. Tarayıcı aday vermedi.",
 10: "◇ İki yön, iki ayrı fiil: güzel söz O'na YÜKSELİR (yas'adu) — salih ameli O YÜKSELTİR (yerfa'uhû). صعد ve رفع korpusta YALNIZ bu ayette birlikte. Karşı kutup: kötülük tuzağı kuranlar (yemkurûne) → tuzakları BOŞA ÇIKAR (yebûr) — مكر [1,2/4] iki kez, مكر ile بور da korpusta YALNIZ bu ayette birlikte. Yukarı giden söz/amel | çürüyen tuzak. عزز [2,3/5]: izzet ayette iki kez (isteyen / izzetin tamamı Allah'ın); [1/5] 35:2'deki azîz. nakarat3 'lehüm azâbün şedîd' 35:7 ile (sûre içi, defterden doğrulandı). Yeni kök صعد: korpusta 9 ayet, baskın lemma sa'îd ('toprak yüzeyi', 4); burada fiil. بور [1/2] — ikinci anma ileride.",
}
MEAL2 = {
 11: "Allah sizi topraktan, sonra nutfeden yarattı, sonra sizi çiftler kıldı. O'nun bilgisi dışında hiçbir dişi ne gebe kalır ne doğurur. Ömrü uzatılanın ömrü uzatılması da, ömründen eksiltilmesi de mutlaka bir kitaptadır. Şüphesiz bu Allah'a kolaydır.",
 12: "İki deniz bir değildir: şu tatlıdır, susuzluğu giderir, içimi kolaydır; şu tuzludur, acıdır. Her birinden taze et yersiniz, takındığınız süs eşyası çıkarırsınız. Gemilerin orada suyu yararak gittiğini görürsün; O'nun lütfundan arayasınız ve şükredesiniz diye.",
 13: "Geceyi gündüze katar, gündüzü geceye katar; güneşi ve ayı boyun eğdirmiştir, her biri belirli bir süreye kadar akar. İşte Rabbiniz Allah budur; mülk O'nundur. O'nu bırakıp çağırdıklarınız bir hurma çekirdeğinin zarına bile sahip değildir.",
 14: "Onları çağırsanız çağrınızı işitmezler; işitseler de size cevap veremezler. Kıyamet günü de ortak koşmanızı inkâr ederler. Sana hiç kimse, her şeyden haberdar olan gibi haber veremez.",
 15: "Ey insanlar! Sizler Allah'a muhtaçsınız; Allah ise zengin olandır, övgüye lâyık olandır.",
 16: "Dilerse sizi giderir, yeni bir halk getirir.",
 17: "Bu, Allah'a güç değildir.",
 18: "Hiçbir günahkâr başkasının günah yükünü yüklenmez. Yükü ağır gelen biri onu taşımak için (birini) çağırsa, yakını da olsa ondan hiçbir şey yüklenilmez. Sen ancak görmedikleri hâlde Rablerinden korkan ve namazı dosdoğru kılanları uyarırsın. Kim arınırsa ancak kendisi için arınır. Dönüş Allah'adır.",
 19: "Körle gören bir olmaz.",
 20: "Karanlıklarla aydınlık da (bir olmaz).",
}
M2 = {
 11: "◇ Yaratılış dizisi 'sonra' (summe) ile üç halka: toprak → nutfe → çiftler (ezvâc). ترب [1/1], نطف [1/1], زوج [1/1]. Ara durum adı yok (alaka, mudğa 22:5 ve 23:14'te var, burada yok). Ardından ayet bilgiye geçiyor: dişinin gebeliği ve doğumu O'nun bilgisiyle. Sonra ömür: عمر [1,2,3/4] tek ayette ÜÇ kez — ömrü uzatılan (yu'ammaru min mu'ammar) / ömründen eksiltilen (yunqasu) — iki fiil de EDİLGEN ve karşıt yönlü: uzatma | eksiltme, ikisi de 'kitapta'. نقص [1/1]. EDİLGEN 2/6, pas z=1,57; n=34 (n z=2,29): ★★ iki kaynak, n + pas. say alanı zevc'i sayı işareti saydı — 'çiftler' cins adı, sayı değil (981 yanlış pozitif). nakarat3 'zâlike ale'llâh' sûre içi, eşi 35:17 (defterden). xref 41:47 (dişinin gebeliği ve doğumu bilgide) ve 22:70 (kitapta, Allah'a kolay). 🜁 L1, olgu evet: madde ve aşama adlandırma, nedensellik yok — 32:7 emsali (L1). Tarayıcı aday vermedi.",
 12: "◇ İkili bir SINIFLAMA: 'iki deniz bir değil' — biri tatlı + susuzluk giderici + içimi kolay (üç sıfat), öteki tuzlu + acı (iki sıfat). سوغ, فرت, أجج hepsi [1/1]; سوغ, طرو, مخر bu blokta eklenen kökler. Sonra ORTAK küme: 'her birinden' taze et ve süs — farkı kurulan iki sınıfın kesişimi de veriliyor. بحر + عذب + ملح korpusta YALNIZ iki ayette: 25:53 ve 35:12 (TAM SAYIM); 25:53'te iki deniz arasına engel konuyor, burada iki deniz farklı ama aynı ürünleri veriyor. Ayetin ikinci yarısı 16:14 ile neredeyse aynı: xref dokuz üçlünün dokuzu da 16:14'e — sûre 16 okundu. عذب [3/4] burada 'tatlı su' anlamında; 35:7 ve 35:10'daki iki anma 'azap' — tek kök, iki anlam, aynı iplikte; gloss 'azap' tatlı su anlamını taşımıyor (aday 1000 ailesi). Lafız YOK, Rab YOK, esmâ yok: sınıf 0. Fâsıla تشكرون (ن) KAFİYE KIRIĞI; ★ kaynağı n z=1,65 (kırık toplanmıyor). 🜁 L1, olgu evet: iki su sınıfı nitelikleriyle, mekanizma yok; sınıflama ikili ve ölçütsüz — 27:61 emsali (L1). L4 sınıflama koluna sınırda. TARAYICI v4 ADAY VERDİ (ta'lîl, recâ), çıpa değil.",
 13: "◇ İki karşılıklı geçiş: geceyi gündüze katar / gündüzü geceye katar — ولج [1,2/2], ليل [1,2/2], نهر [1,2/2]: üç kök de ayette iki kez ve iki yönde. ولج + ليل + نهر + سخر korpusta YALNIZ 31:29 ve 35:13'te (TAM SAYIM); 31:29 okundu, orada L1. Güneş ve ay 'her biri belirli süreye akar' — أجل [1/3]. Sonra kimlik cümlesi: 'İşte Rabbiniz Allah' — lafız ve Rab aynı ayette yan yana (17. ve 18. sıra), sınıf AR. Karşıt: O'na mülk (ملك [2,3/3] iki kez, kök tamam) / çağrılanlar kıtmîr'e bile sahip değil. قطمر korpusta YALNIZ bu ayette: ★★★ kaynak hapaks z=3,28 (n 1,65 de eşik üstü) — 983 birikimi: sûre 34'te ★★★ 4/4 hapakstı; sûre 35'te şimdiye dek kaynaklar pas (35:4), hapaks (35:13), allah (35:15, 35:17). Ölçek en küçük birimle kuruluyor — 34:3 ve 34:22'deki zerre ölçeğinin karşılığı, ama burada sahiplik için. nakarat3 'ellezîne ted'ûne min dûnih' sûre içi, eşi 35:40 (defterden). 🜁 L1, olgu evet (31:29 emsali). Tarayıcı vermedi — 31:29'da 'e lem tera' (bakış) işaretiyle aday vermişti; burada işaret yok, aynı terkip.",
 14: "◇ Çağrılanların üç yetersizliği art arda: işitmezler → işitseler cevap veremezler → kıyamet günü ortaklığı inkâr ederler. سمع [1,2/4] iki kez (işitmezler / işitseler), دعو [3,4/6]. İki şart (COND 2), üç olumsuz (NEG 3). Lafız YOK, Rab YOK; ayetin sonunda tek esmâ: 'habîr gibi kimse sana haber veremez' — habîr yüklem değil, mislu'nun muzâfun ileyhi (tamlama içinde ad), göndergesi Allah: e_el 'ilahi', aday 999'un İKİNCİ vakası (ilki 34:6). نبأ ile خبر aynı cümlede: haber vermek / haberdar olan. §4.3 mühür EVET, ton denge.",
 15: "◇ Sûrenin üçüncü ve son nidâsı (35:3, 35:5, 35:15): أيي [3/3] — kökün sûredeki üç anmasının üçü de 'ey insanlar'; 'âyet' kelimesi Fâtır'da hiç geçmiyor. İki karşıt yüklem: siz FUKARÂ (Allah'a muhtaç) | Allah GANÎ. Aynı yapı 47:38'de (ganî / fukarâ); 3:181'de TERS yönde, iddia olarak ('Allah fakir, biz zenginiz'). فقر [1/1], غني [1/1]. Mühür ganî-hamîd ÇİFT, geçerli; حمد [2/3] — 35:1'deki hamd ile kök iplikte. 10 kelimede iki lafız: ★★★ tek kaynak allah z=3,47. Fâsıla د.",
 16: "◇ 6 kelime, iki fiil: giderir (yüzhib) / getirir (ye'ti) — giden 'siz', gelen 'yeni bir halk'. خلق [4/5]. Lafız YOK, Rab YOK, esmâ yok — sınıf 0; özne 35:15'teki lafza dönen zamir. xref üç üçlünün üçü de 14:19'a: 35:16 = 14:19'un son cümlesi. TARAYICI v4 ADAY VERDİ (şart), doğal olgu yok, merdiven uygulanmadı.",
 17: "◇ 5 kelime: 'Bu, Allah'a güç değildir.' esit2 14:20 ile TAM (oran 1,0000). 35:16-17 birlikte 14:19-20'nin son cümlesi + tamamı: iki ardışık ayetlik bir blok iki sûrede aynı sırayla. nakarat3 'zâlike ale'llâh' 35:11 ile (sûre içi): 35:11 'bu Allah'a kolay' (yesîr) / 35:17 'bu Allah'a güç değil' (bi-azîz) — aynı çerçeve, olumlu ve olumsuz. Esmâ azîz burada işin sıfatı ('zor, güç'), Allah'ın değil → değil; §4.3 mühür e_oto ile EVET, e_el ile YOK — YANLIŞ MÜHÜR. عزز [4/5]. 5 kelimede bir lafız: ★★★ tek kaynak allah z=3,47 — blokta ikinci kısa-ayet lafız ★★★'ı (35:15 ile).",
 18: "◇ وزر [1,2,3/3] tek ayette ÜÇ kez: 'hiçbir yük taşıyan başkasının yükünü taşımaz' (vâzira · vizr). vâzira lemması korpusta 5 ayet (6:164, 17:15, 35:18, 39:7, 53:38), hepsi bu kalıpta. Ağırlık ve taşıma ikinci kez: musqala (ağır yüklü) çağırır, ondan 'hiçbir şey taşınmaz' — حمل [2,3/3] (tamam), ثقل [1/1]. Akrabalık bile aktarımı kırmıyor (zâ qurbâ, قرب [1/1]). Sonra uyarının kapsamı daraltılıyor: 'ancak' (innemâ) gaybda Rablerinden korkanlar — Rab bu kez 'onların Rabbi'. زكو [1,2/2]: arınan ancak kendisi için arınır — yük aktarılmıyor, arınma da aktarılmıyor; ayetin iki ucu aynı ilke. n=34 (n z=2,29): ★★ tek kaynak n. Lafız (33.) ve Rab (23.) aynı ayette — sınıf AR. xref 21:49 ve 67:12 (gaybda Rabbinden korkanlar).",
 19: "◇ 4 kelime: 'kör ile gören bir olmaz.' سوي [2/3] — [1/3] 35:12'deki 'iki deniz bir olmaz'. Aynı 'eşit değil' çerçevesi sûrede ikinci kez, bu kez insan için. عمي + بصر + سوي korpusta 5 ayette (6:50, 11:24, 13:16, 35:19, 40:58). Esmâ basîr gören insanın sıfatı → değil; §4.3 mühür e_oto EVET, e_el YOK — YANLIŞ MÜHÜR. Lafız YOK, Rab YOK, sınıf oto E → el 0. Bağ YOK (esit2, nakarat3, xref boş).",
 20: "◇ 4 kelime, fiil yok: 'karanlıklar ile ışık da' — 35:19'un eşitsizlik yüklemine bağlı (eksiltili). Kör/gören → karanlık/ışık: ikinci karşıt çift. ظلم + نور + سوي korpusta YALNIZ 13:16'da birlikte (orada aynı iki çift tek ayette); burada iki ayete bölünmüş. Esmâ nûr ışığın kendisi → değil; YANLIŞ MÜHÜR (blokta üçüncü: 35:17, 35:19, 35:20). Gloss: ظلم 'zulüm' — kökün zulumât lemması (karanlık) 23 ayet, gloss'ta yok (aday 1000 ailesi). ظلم [1/4] iplikte karanlık ile haksızlık aynı sayımda. Bağ YOK.",
}
MEAL.update(MEAL2); M.update(M2)
MEAL3 = {
 21: "Gölge ile sıcak da (bir olmaz).",
 22: "Dirilerle ölüler de bir olmaz. Şüphesiz Allah dilediğine işittirir; sen kabirdekilere işittirecek değilsin.",
 23: "Sen ancak bir uyarıcısın.",
 24: "Biz seni hak ile müjdeleyici ve uyarıcı olarak gönderdik. İçinden bir uyarıcı gelip geçmemiş hiçbir ümmet yoktur.",
 25: "Seni yalanlıyorlarsa, onlardan öncekiler de yalanlamıştı. Elçileri onlara apaçık delillerle, sahifelerle ve aydınlatıcı kitapla gelmişti.",
 26: "Sonra inkâr edenleri yakaladım; inkârım nasıl oldu!",
 27: "Görmedin mi, Allah gökten su indirdi; biz onunla renkleri farklı ürünler çıkardık. Dağlardan da beyaz ve kırmızı, renkleri farklı yollar (çizgiler) ve simsiyah olanlar vardır.",
 28: "İnsanlardan, yürüyen canlılardan ve davarlardan da böyle renkleri farklı olanlar vardır. Allah'tan, kulları içinden ancak âlimler korkar. Şüphesiz Allah mutlak güç sahibidir, çok bağışlayandır.",
 29: "Allah'ın kitabını okuyanlar, namazı dosdoğru kılanlar ve kendilerine verdiğimiz rızıktan gizli ve açık harcayanlar, asla boşa çıkmayacak bir ticaret umarlar;",
 30: "Allah onlara ödüllerini tam versin ve lütfundan onlara fazlasını versin diye. Şüphesiz O çok bağışlayandır, şükrün karşılığını verendir.",
}
M3 = {
 21: "◇ 4 kelime: 'gölge ile sıcak da' — eşitsizlik dizisinin üçüncü çifti (35:19 kör/gören · 35:20 karanlık/ışık · 35:21 gölge/sıcak · 35:22 diri/ölü). ظلل [1/1], حرر [1/2]; ikisi birlikte korpusta 2 ayette (16:81, 35:21). 35:19, 35:20, 35:21 ve 35:23 dördü de n=4: beş ayet içinde dört dört-kelimelik ayet. Gloss: ظلل 'sürüp gitme, olmayı sürdürme' — kökün baskın lemması zıll 'gölge' (14; fiil zalle 9), gölge anlamı gloss'ta YOK; burada okunan anlam tam da eksik olan (aday 1000 ailesi). Lafız YOK, Rab YOK, sınıf 0. Bağ YOK.",
 22: "◇ Dördüncü ve son çift: 'diriler ile ölüler bir olmaz' — سوي [3/3] burada kapanıyor: iki deniz (35:12) → kör/gören (35:19) → diri/ölü (35:22). حيي [3/3] da kapanıyor (dünya hayatı 35:5 · yeri diriltme 35:9 · diriler 35:22). Dört çiftin ilk ikisi 13:16'da tek ayette; dört çift birlikte yalnız burada. حيي + موت + سوي korpusta 2 ayet (35:22, 45:21). İkinci cümle bir AYNA: Allah dilediğine İŞİTTİRİR / sen kabirdekilere işittiremezsin — سمع [3,4/4] kapanıyor (35:14'te çağrılanlar işitmiyordu). Esmâ hayy burada 'diriler' (insan) → değil; sınıf oto A → el A (lafız var). Fâsıla kubûr; قبر [1/1].",
 23: "◇ 4 kelime, HASR: 'sen ancak bir uyarıcısın'. نذر [2/7] (35:18 'tunziru' [1/7]). Lafız YOK, Rab YOK, sınıf 0. Fâsıla nezîr — 35:24 de nezîr ile bitiyor: ardışık iki ayet aynı kelimeyle.",
 24: "◇ Konuşan 1P: 'Biz seni gönderdik' — رسل [5/6]. İkili görev: müjdeleyici (بشر [1/1]) ve uyarıcı. İkinci cümle HASR ile bir evrensel önerme: 'içinden bir uyarıcı geçmemiş ümmet yok' — her ümmet ↔ bir nezîr. نذر [3,4/7] ayette iki kez; 35:23 + 35:24'te üç nezîr. xref 2:119 (hak ile müjdeleyici ve uyarıcı). Lafız YOK, Rab YOK.",
 25: "◇ 35:4'ün eşi: nakarat3 'in kezzebe fe-qad kezzebe' sûre içi, defterden 35:4 ↔ 35:25 — 35:4'te 'senden önce elçiler yalanlandı' (EDİLGEN), burada 'onlardan öncekiler yalanladı' (ETKEN, özne yalanlayanlar). كذب [3,4/4] kapanıyor; رسل [6/6] kapanıyor — kök sûrede altı anma, beş gönderge: melek elçiler, rahmetin salıverilmesi, elçiler, rüzgâr, 'seni gönderdik', elçiler. Elçilerin getirdiği üçlü: beyyinât · zübür · kitâb münîr — xref 3:184 aynı üçlü; زبر + بين + نور korpusta 3 ayet (3:184, 18:96, 35:25), 18:96'da zübür 'demir kütleleri'. نور [2/3]: 35:20 ışık → 35:25 aydınlatıcı kitap. İkinci nakarat3 'ellezîne min qablihim' sûre içi, eşi 35:44. TARAYICI v4 ADAY VERDİ (şart), doğal olgu yok, merdiven uygulanmadı.",
 26: "◇ 7 kelime ve konuşan TEKİL: 'yakaladım' (ehaztu, 1S). 35:24'te 1P (erselnâke), iki ayet sonra 1S — birinci şahsın sayısı değişiyor (sahset 1S 3). Ölçüm iltifât 0. Kapanış sorusu 'inkârım nasıl oldu' (fe-keyfe kâne nekîr): nekîr lemması korpusta 5 ayet; 'keyfe kâne nekîr' kalıbı 4'ünde (22:44, 34:45, 35:26, 67:18 — kelime düzeyinde sayıldı), 42:47'de başka kalıp ('mâ lekum min nekîr'). 34:45 bitişik sûrenin son blokunda. نكر [1/1], كفر [3/11]. Lafız YOK, Rab YOK, sınıf 0.",
 27: "◇ Bakışla açılış: 'görmedin mi' (G_bakış — tarayıcının tetiği). Fail ayet içinde değişiyor: Allah (3MS, enzele) → biz (1P, ahracnâ); iltifât 0 — 517 ailesi, sûrede ikinci vaka (ilki 35:9). Nedensellik: gökten su → 'onunla' renkleri farklı ürünler. Sonra dağlar: çizgiler (cudad) BEYAZ · KIRMIZI · renkleri farklı · ve SİMSİYAH (ğarâbîbu sûd). بيض + حمر + سود korpusta YALNIZ bu ayette (TAM SAYIM). 'Renkleri farklı' (muhtelifun elvânuh) ayette İKİ kez, 35:28'de üçüncü: خلف + لون korpusta 6 ayet (16:13, 16:69, 30:22, 35:27, 35:28, 39:21), üçü bu sûrede iki ayette. لون [1,2/3], خلف [1,2/4]. جدد [2/2]: 35:16'da 'yeni' (cedîd), burada 'yollar, çizgiler' (cudad) — gloss 'yenilik' ikinci anlamı taşımıyor (1000 ailesi). Fâsıla سود (د): KAFİYE KIRIĞI; ★ kaynağı kırık — diğer bileşenler 1,5 altı (n 1,02 · allah 0,38): bilanço yanlış etiketleyebilir (1001). 🜁 L2, olgu evet: su → ürünler nedenselliği (27:60 emsali L2). Sınıflama: renk sınıfları ADLI (beyaz, kırmızı, siyah) — 30:22'den ileri — ama sınıflara üye eşlenmiyor (29:40 ölçütü) → L4 sınıflama kolu değil (aday 1014). TARAYICI v4 ADAY VERDİ (G_bakış), çıpa değil.",
 28: "◇ Renk çeşitliliği üçüncü alana taşınıyor: insanlar, yürüyen canlılar, davarlar — 'böyle' (kezâlik) ile 35:27'ye bağlı. لون [3/3] kapanıyor: ürünler → dağlar → canlılar. Sonra HASR: 'kulları içinden Allah'tan ancak âlimler korkar' — خشي [2/2] kapanıyor (35:18 'Rablerinden korkanlar' / 35:28 'Allah'tan korkanlar'). Esmâ alîm burada 'ulemâ (âlimler, insan) → değil; azîz-ğafûr inne haberi, ilâhî: §4.3 mühür ÇİFT geçerli, ton karma. عزز [5/5] kapanıyor (azîz 35:2 · izzet ×2 35:10 · bi-azîz 35:17 · azîz 35:28). Renk çeşitliliğinden bilgiye ve korkuya: ayetin iki yarısı. ★ tek kaynak allah z=1,82. 🜁 L1, olgu evet: çeşitliliğin varlığı, sınıf adı yok (30:22 emsali L1). Bağ YOK.",
 29: "◇ Üç fiil, üç eylem: kitabı okurlar · namazı kılarlar · rızıktan gizli ve açık harcarlar → 'asla boşa çıkmayacak bir ticaret' umarlar. 'Namazı dosdoğru kıldılar' 35:18'de de vardı: صلو [2/2] kapanıyor. بور [2/2] kapanıyor ve bir AYNA kuruyor: 35:10 'onların tuzağı boşa çıkar' (yebûr) / 35:29 'boşa çıkmayacak ticaret' (len tebûr). تجر ile بور korpusta YALNIZ bu ayette birlikte. سرر + علن + نفق korpusta 4 ayet (2:274, 13:22, 14:31, 35:29); xref 13:22 ve 14:31. Rızık 1P'den: 'verdiğimiz' (razaqnâhum) — رزق [2/2] kapanıyor (35:3 'sizi rızıklandıran'). Lafız (5.), Rab YOK.",
 30: "◇ 35:29'un devamı (li- ta'lîl): tam verme + artırma. وفي [1/1], أجر [2/2] kapanıyor (35:7 'büyük ödül'), زيد [2/5] (35:1 'yaratmada dilediğini artırır'), فضل [2/4] (35:12 'lütfundan arayasınız'). شكر [2/3]: 35:12'de insanlar şükreder (teşkurûn), burada Allah şekûr — aynı kök iki yönde. Mühür ğafûr-şekûr ÇİFT, O'na dönen zamirin haberi, geçerli, ton cemâl. Lafız YOK, Rab YOK; sınıf E (esmâ zamirle). xref 4:173.",
}
MEAL.update(MEAL3); M.update(M3)
MEAL4 = {
 31: "Sana kitaptan vahyettiğimiz, önündekini doğrulayan haktır. Şüphesiz Allah kullarından haberdardır, onları görendir.",
 32: "Sonra kitabı kullarımızdan seçtiklerimize miras bıraktık. Onlardan kimi kendine zulmeder, kimi orta yolu tutar, kimi de Allah'ın izniyle hayırlarda öne geçer. İşte bu, büyük lütuftur.",
 33: "Adn cennetlerine girerler; orada altından bilezikler ve incilerle süslenirler, oradaki giysileri ipektir.",
 34: "Derler ki: Hamd, bizden hüznü gideren Allah'adır. Şüphesiz Rabbimiz çok bağışlayandır, şükrün karşılığını verendir.",
 35: "O, lütfundan bizi kalınacak yurda yerleştirdi; orada bize ne bir yorgunluk dokunur ne de bir bitkinlik dokunur.",
 36: "İnkâr edenler için cehennem ateşi vardır. Onlara hükmedilmez ki ölsünler, azabından da onlardan hafifletilmez. Her nankörü böyle cezalandırırız.",
 37: "Orada çığlık çığlığa bağırırlar: Rabbimiz! Bizi çıkar, yaptığımızdan başka salih amel işleyelim. — Sizi, düşünecek olanın düşünebileceği kadar yaşatmadık mı? Size uyarıcı da gelmişti. Tadın öyleyse; zalimler için hiçbir yardımcı yoktur.",
 38: "Şüphesiz Allah göklerin ve yerin gaybını bilendir. O, göğüslerde olanı hakkıyla bilendir.",
 39: "Sizi yeryüzünde halifeler kılan O'dur. Kim inkâr ederse inkârı kendi aleyhinedir. İnkârcıların inkârı, Rableri katında onlara gazaptan başka bir şey artırmaz; inkârcıların inkârı onlara ziyandan başka bir şey artırmaz.",
 40: "De ki: Allah'ı bırakıp çağırdığınız ortaklarınızı gördünüz mü? Gösterin bana, yerden neyi yarattılar? Yoksa göklerde bir ortaklıkları mı var? Yoksa onlara bir kitap verdik de ondan açık bir delil üzerinde mi bulunuyorlar? Hayır, zalimler birbirlerine aldatmacadan başka bir şey vaat etmiyorlar.",
}
M4 = {
 31: "◇ Konuşan 1P: 'sana vahyettiğimiz' (evhaynâ). Kitap 'önündekini doğrulayan hak' — حقق [3/3] kapanıyor, صدق [1/1], وحي [1/1]. Ayet 'kullarından haberdar, gören' ile kapanıyor: خبر [2/2] kapanıyor (35:14 'mislu habîr' / 35:31 'le-habîrun'). عبد + خبر + بصر korpusta 5 ayet (17:17, 17:30, 17:96, 35:31, 42:27) — xref dördünü veriyor. بصر [2/3]: AYNI KELİME iki ayrı göndergede — 35:19'da basîr gören insan (e_el değil), 35:31'de Allah (e_el ilâhî). Mühür habîr-basîr ÇİFT, geçerli, ton denge.",
 32: "◇ Bir SINIFLAMA, ölçütüyle ve üyeleriyle: seçilmiş kullar → 'onlardan' (minhum) ×3 üç sınıf: kendine zulmeden · orta yolda olan · hayırlarda öne geçen. Üç sınıf da ADLI ve küme üç parçaya BÖLÜNÜYOR — aday 1014'ün eşleme ölçütü (29:40) burada tam doluyor; ama konu doğal olgu değil, insan sınıfları: 27:17 emsali ('sınıflama var ama olgu değil'), merdiven uygulanmadı. قصد [1/1], سبق [1/1], خير [1/1], ظلم [2/4] (35:20 'karanlıklar' [1/4] — aynı iplik). Konuşan 1P (evrasnâ, istafaynâ, ibâdinâ) → 'Allah'ın izniyle' lafız: ölçüm iltifât 0 (517 ailesi, ters yön). Esmâ kebîr 'büyük lütuf' — lütfun sıfatı → değil; §4.3 mühür e_oto EVET, e_el YOK: YANLIŞ MÜHÜR — 35:7 'ecrun kebîr' ile aynı kalıp (كبر [2/3]). xref 33:47 (Allah'tan büyük lütuf).",
 33: "◇ Cennet tasviri, üç madde: altın bilezik · inci · ipek giysi. Ayette çok anmalı üç iplik kapanıyor ve ikisi 35:12'ye dönüyor: حلي [2/2] (35:12 denizden süs çıkarırsınız → 35:33 orada süslenirler), لبس [2/2] (35:12 takındığınız → 35:33 giysileri). حرر [2/2]: 35:21 harûr 'sıcak' → 35:33 harîr 'ipek'. ذهب [3/4] burada zeheb 'altın' — gloss 'gitme, götürme', altın anlamı yok (zeheb lemması 8; aday 1015'e ek). EDİLGEN 1/2 (yuhallevne, süsleyen adsız): ★★ tek kaynak pas z=2,52. xref 22:23 dört üçlü (bilezik, altın, inci, ipek giysi), 18:31. Adlı yer: Adn. Lafız YOK, Rab YOK.",
 34: "◇ Cennet ehlinin sözü: 'Hamd, bizden hüznü gideren Allah'a' — حمد [3/3] KAPANIYOR: sûre hamd ile açıldı (35:1), ganî-hamîd mührü (35:15), cennet ehlinin hamdı (35:34). ذهب [4/4] kapanıyor: 35:8 gitme, 35:16 giderme, 35:33 altın, 35:34 giderme — tek kökte üç anlam. Mühür ğafûr-şekûr ÇİFT: 35:30'daki çiftin AYNISI dört ayet sonra, bu kez 'inne rabbenâ' ile; شكر [3/3] kapanıyor (insan şükreder 35:12 · şekûr 35:30 · şekûr 35:34). Lafız ve Rab aynı ayette, sınıf AR. ★ tek kaynak rab z=1,62 — sûrede ilk Rab kaynaklı yıldız. Bağ YOK.",
 35: "◇ İki paralel olumsuz: 'orada bize yorgunluk dokunmaz / orada bize bitkinlik dokunmaz' — مسس [1,2/2] iki kez, aynı kalıp; نصب [1/1] ve لغب [1/1] iki yakın anlam. مسس + نصب + لغب korpusta YALNIZ bu ayette. 'Kalınacak yurt' (dâru'l-muqâme): قوم [4/4] kapanıyor; فضل [4/4] kapanıyor (lütfundan arayasınız 35:12 · lütfundan artırır 35:30 · büyük lütuf 35:32 · lütfundan yerleştirdi 35:35). Fâsıla لغوب (ب): KAFİYE KIRIĞI; ★ kaynağı kırık — diğer bileşenler 1,5 altı (n 0,17): bilanço yanlış etiketleyebilir (1001). Lafız YOK, Rab YOK.",
 36: "◇ 35:35'in AYNASI: cennette 'dokunmaz ×2' (NEG 2) / cehennemde 'hükmedilmez ki ölsünler × hafifletilmez' (NEG 2) — iki ayet, ikişer olumsuz, karşı yerlerde. Cennette yorgunluk yok; cehennemde ölüm de yok, hafifleme de. İki olumsuzun ikisi de EDİLGEN (yuqdâ, yuhaffefu): pas z=1,95, ★ tek kaynak pas. nakarat3 'ellezîne keferû lehüm' 35:7 ile (sûre içi, defterden). Bu ayette çok anmalı dört iplik kapanıyor (tek anmalılarla yedi): نور [3/3] (ışık 35:20 · aydınlatıcı 35:25 · ATEŞ 35:36), موت [4/4], عذب [4/4] (azap · azap · tatlı su · azap), كلل [4/4]. 1P 'cezalandırırız' (neczî). Adlı yer: cehennem.",
 37: "◇ Cehennem ehlinin sözü — 35:34'teki cennet ehlinin sözünün karşısı: ikisi de 'Rabbimiz' diye konuşuyor; biri hamd ediyor (35:34), öteki çığlık atıyor (yastarihûn; صرخ [1/1], korpusta 4 ayet). İstek: 'çıkar, yaptığımızdan başka salih amel yapalım' — عمل [4,5/5] iki kez, kapanıyor. Cevap 1P: 'sizi yaşatmadık mı' — عمر [4/4] kapanıyor: 35:11'deki ömür uzatma/eksiltme ipliği burada 'düşünecek kadar ömür' olarak kapanıyor. ذكر [2,3/3] iki kez, kapanıyor (35:3 'nimetini anın'). نذر [5/7] nezîr. Esmâ nasîr 'zalimler için yardımcı yok' — olumsuzlanan, insan göndergeli → değil; §4.3 mühür e_oto EVET, e_el YOK: YANLIŞ MÜHÜR. ظلم [3/4]. Sahset karışık (1P 7): konuşan biz hem cehennem ehli hem Allah — şahıs sayımı konuşmacıyı ayırmıyor.",
 38: "◇ İki bilgi cümlesi: göklerin ve yerin gaybını BİLEN (âlim) / göğüslerdekini hakkıyla BİLEN (alîm) — علم [4,5/6] iki kez, iki ölçek: kozmik gayb / iç dünya. غيب [2/2] kapanıyor (35:18 'gaybda Rablerinden korkanlar' / 35:38 'göklerin ve yerin gaybı'). Esmâ âlim ve alîm, ikisi inne haberi → ilâhî; §4.3 mühür EVET (ölçüm satırının MÜHÜRSÜZ'ü eski alan, #9/#12). 10 kelime, bağ YOK. 🜁 L0, olgu evet (gökler ve yer adlanıyor, 35:3 emsali).",
 39: "◇ كفر [6,7,8,9,10,11/11]: tek ayette ALTI kez ve sûre içi ipliği burada kapanıyor. Korpusta كفر kökünün bir ayette geçtiği en yüksek sayı bu (TAM SAYIM, morfoloji tokenleri: 35:39 = 6; sonraki 3 — 2:89, 2:102, 4:137, 9:37). Yapı iki paralel cümle: 'inkârcıların inkârı onlara ... başka bir şey artırmaz' ×2 — ilkinde 'Rableri katında gazap' (مقت [1/1]), ikincisinde 'ziyan' (خسر [1/1]); زيد [3,4/5] iki kez, HASR ×2. Rab [5/5] kapanıyor. خلف [4/4] kapanıyor: 35:27-28'de 'renkleri farklı' ×3, burada 'halifeler' — gloss iki anlamı da taşıyor. Fâsıla hasârâ (ا, A sınıfı). 🜁 L0, olgu evet (yeryüzü adlanıyor).",
 40: "◇ 'De ki' ile üç soru (em … em): ortaklar yerden neyi yarattı? göklerde ortaklıkları mı var? onlara bir kitap mı verdik? Gök ve yer 35:3'teki tek-yaratıcı sorusunun karşısı: orada 'Allah'tan başka yaratıcı var mı', burada 'onlar ne yarattı'. nakarat3 'ellezîne ted'ûne min dûnih' 35:13 ile (sûre içi, defterden). Kapanış IDRAB (bel): 'zalimler birbirlerine aldatmacadan başka bir şey vaat etmez'. Bu cümle 35:5'in AYNASI: 35:5 'Allah'ın VAADİ hak, aldatıcı sizi ALDATMASIN' / 35:40 zalimlerin VAADİ ALDATMACA — وعد [2/2] ve غرر [4/4] ikisi de burada kapanıyor; وعد + غرر korpusta 6 ayet (4:120, 17:64, 31:33, 33:12, 35:5, 35:40), ikisi bu sûrenin iki ucunda. Ayette 13 kök ipliği kapanıyor (ölçüm satırı): قول, رأي, شرك, دعو, دون, خلق, أتي, كتب, بين, وعد, ظلم, بعض, غرر — sûrenin ortak kökleri burada toplanıyor. 1S 'gösterin bana' (erûnî, emreden Peygamber) ve 1P 'verdik'. n=33: ★★ tek kaynak n z=2,19. 🜁 L0, olgu evet (gök ve yer). TARAYICI v4 ADAY VERDİ (G_bakış: 'gördünüz mü'), çıpa değil — olgu değil, ortaklara meydan okuma.",
}
MEAL.update(MEAL4); M.update(M4)
MEAL5 = {
 41: "Şüphesiz Allah, gökleri ve yeri yerlerinden kaymasınlar diye tutar. Eğer kayarlarsa, O'ndan sonra onları kimse tutamaz. O, halîmdir, çok bağışlayandır.",
 42: "Kendilerine bir uyarıcı gelirse ümmetlerin herhangi birinden daha doğru yolda olacaklarına dair Allah'a bütün güçleriyle yemin ettiler. Fakat onlara bir uyarıcı gelince, bu onlara nefretten başka bir şey artırmadı;",
 43: "yeryüzünde büyüklenmeleri ve kötü tuzak kurmaları yüzünden. Kötü tuzak ancak sahibini kuşatır. Öncekilerin başına gelen kanundan başkasını mı bekliyorlar? Allah'ın kanununda asla bir değişme bulamazsın; Allah'ın kanununda asla bir sapma bulamazsın.",
 44: "Yeryüzünde gezip kendilerinden öncekilerin sonunun nasıl olduğuna bakmadılar mı? Onlar bunlardan daha güçlüydü. Göklerde ve yerde Allah'ı âciz bırakacak hiçbir şey yoktur. O, hakkıyla bilendir, gücü yetendir.",
 45: "Allah insanları kazandıkları yüzünden hemen sorguya çekseydi, yeryüzünün sırtında hiçbir canlı bırakmazdı. Fakat onları belirli bir süreye kadar erteler. Süreleri gelince, şüphesiz Allah kullarını görendir.",
}
M5 = {
 41: "◇ Gökler ve yer ÇİFT olarak tutuluyor: şahıs 2D/3D/3FD — 'kaymasınlar' (en tezûlâ), 'kayarlarsa' (zâletâ) ikil. Yeni kök زول [1,2/2] iki kez. مسك [3,4/4] iki kez ve kapanıyor: 35:2 rahmeti TUTMA / 35:41 gökleri ve yeri TUTMA — kök sûrede iki ayette, ikişer anma. İkinci cümle bir YETİ SINIRI: 'kayarlarsa O'ndan sonra kimse tutamaz'. say alanı ehad'i ('kimse') sayı saydı — olumsuz bağlamda belirsiz zamir, sayı değil (981 yanlış pozitif); esmâ olarak da e_oto'ya girdi, e_el değil. Mühür halîm-ğafûr ÇİFT, kâne haberi, geçerli, ton cemâl; غفر [5/5] kapanıyor. xref 17:44 (kâne halîmen ğafûrâ). Fâsıla ğafûrâ: ا sınıfı. 🜁 L2, olgu evet: gök ve yer + yeti sınırı (L2 tanımının 'yeti sınırı' kolu, 27:60 emsali). TARAYICI v4 ADAY VERDİ (şart, D_yeti), çıpa değil.",
 42: "◇ YEMİN (QASEM): 'Allah'a bütün güçleriyle yemin ettiler' — uyarıcı gelirse herhangi bir ümmetten daha doğru yolda olacaklar. Gelince: 'nefretten başka bir şey artırmadı' (HASR). نذر [6,7/7] iki kez, kapanıyor; أمم [2/2] kapanıyor (35:24 'her ümmete bir uyarıcı' / 35:42 'ümmetlerin herhangi biri'). زيد [5/5] kapanıyor ve iplik iki yöne ayrılıyor: Allah artırır — yaratmada (35:1), lütfundan (35:30) / inkâra ve uyarıya karşı 'ancak … artırır' — gazap, ziyan (35:39 ×2), nefret (35:42). هدي [2/2] (35:8 'dilediğini doğru yola iletir'). say: ihdâ ('herhangi biri') sayı işareti — sınırda. xref 6:109 (güçleriyle yemin). Fâsıla nufûrâ: ا.",
 43: "◇ 35:42'nin devamı (nedeni): yeryüzünde büyüklenme ve KÖTÜ TUZAK. مكر [3,4/4] ve سوأ [3,4/4] iki kez, ikisi de kapanıyor — 35:10'da da مكر iki kez + kötülükler (yemkurûne's-seyyiât): tuzak kökü sûrede yalnız iki ayette, ikişer anma. 35:10 'tuzakları boşa çıkar' / 35:43 'kötü tuzak ancak sahibini kuşatır' (حيق [1/1]). Sonra iki paralel olumsuz: 'Allah'ın sünnetinde değişme BULAMAZSIN / sapma BULAMAZSIN' — سنن [1,2,3/3] tek ayette üç kez, وجد [1,2/2], بدل [1/1], حول [1/1]. xref 33:62, 48:23 (değişme bulamazsın). كبر [3/3] kapanıyor: kebîr (ödül 35:7, lütuf 35:32) → istikbâr (büyüklenme). Lafız iki token, iki 'sünnetullah'. TARAYICI v4 ADAY VERDİ (G_bakış: 'beklemiyorlar mı'), doğal olgu yok; 🜁 L0 (yeryüzü adlanıyor, 35:39 emsali).",
 44: "◇ 'Yeryüzünde gezip bakmadılar mı' — نظر [2/2] (35:43 'beklemiyorlar mı' / 35:44 'bakmadılar mı', aynı kök iki anlam). كيف [2/2]: 35:26 'inkârım nasıl oldu' / 35:44 'sonları nasıl oldu'. Öncekiler 'daha güçlüydü' (eşedde) — شدد [3/3] kapanıyor (çetin azap 35:7, 35:10 → daha güçlü). nakarat3 'ellezîne min qablihim' sûre içi, eşi 35:25 (defter listesinde iki sûre-içi geçiş). Kapanış: göklerde ve yerde Allah'ı âciz bırakacak hiçbir şey yok — قدر [2/2] ve شيأ [8/8] kapanıyor: 35:1 'her ŞEYE GÜCÜ YETEN' (qadîr) → 35:44 'hiçbir ŞEY âciz bırakamaz … gücü yeten' (qadîr). Sûrenin ilk ayetiyle aynı iki kök ve aynı esmâ. أرض [9,10/10] kapanıyor. Mühür alîm-qadîr ÇİFT, kâne haberi, geçerli, ton karma. n=30: ★ tek kaynak n z=1,87. TARAYICI v4 ADAY VERDİ (ta'lîl), çıpa değil; 🜁 L0 (gök ve yer).",
 45: "◇ Sûrenin son ayeti 16:61 ile neredeyse aynı: lemma dizisinde 32 segmentin 22'si hizalı (difflib, morfoloji); farklar 'zulümleri yüzünden' → 'kazandıkları yüzünden', 'üzerinde' → 'SIRTINDA' (ظهر [1/1]), ve kapanış: 16:61 'ne geri kalırlar ne öne geçerler' / 35:45 'Allah kullarını görendir'. 'Belirli süre' (ecel müsemmâ): أجل [2,3/3] — 35:13'te güneş ve ay belirli süreye akıyordu, burada insanlar belirli süreye erteleniyor; aynı terim gök cisimleri ve insanlar için. Bu ayette 14 kök ipliği kapanıyor (ölçüm satırı); lafız أله [36,37/37] dahil — sûrenin son lafzı. 'bi-ibâdihî basîrâ': 35:31 'bi-ibâdihî le-habîrun basîr' ile aynı bağlam, بصر [3/3] kapanıyor (gören insan 35:19 · Allah 35:31 · Allah 35:45). Mühür basîr, kâne haberi, geçerli. Fâsıla basîrâ (ا): sûrenin son YEDİ ayeti (39-45) kesintisiz ا sınıfı; 35:1-38'de ا fâsıla YOK (ölçüm satırları, 45/45); kafiye kırığı alanı yedisini de işaretlemiyor. TARAYICI v4 ADAY VERDİ (şart); 🜁 L0, olgu evet (yeryüzünde yürüyen canlı adlanıyor), çıpa değil.",
}
MEAL.update(MEAL5); M.update(M5)
