# -*- coding: utf-8 -*-
"""kok_ekle_okunan.py — okunmuş ayetlerde geçen ama kok_turkce.json'da karşılığı olmayan 145 + 1 kök (P1 borcu,
aralık oturumu 2026-10-05'te ölçüldü: ciktilar/karsiliksiz_kokler_okunan.json). Kullanıcı kararı 2026-10-06 (sûre 37 oturumu).
Gloss ÇOK ANLAMLI yazılır; baskın lemma (morph.txt sayımı) ÖNCE, parantezde okunuşu.
ANAHTAR KURALI: anahtar ELLE YAZILMAZ — kok_envanteri.json içinden NFC eşlemesiyle KOPYALANIR; eşleşmezse koşu DURUR."""
import json, unicodedata
env = json.load(open('kok_envanteri.json', encoding='utf-8'))
kt = json.load(open('kok_turkce.json', encoding='utf-8'))
ISTEK = [
 ('مسح', 'Mesih (mesîh); meshetme, sıvazlama (imsah)'),
 ('قرض', 'ödünç verme, borç (karz, akraza); kesip geçme, sıyırıp geçme (takridu)'),
 ('حور', 'havari (havâriyy); ahu gözlü (hûr); karşılıklı konuşma (yuhâviru, tehâvür); dönme (yehûra)'),
 ('سفه', 'beyinsiz, akılsız (sefîh); beyinsizlik (sefâhe, sefeh)'),
 ('أيد', 'destekleme, güçlendirme (eyyede); güç, kuvvet (eyd)'),
 ('صعق', 'yıldırım, helak eden çarpma (sâika); bayılıp düşme (saika)'),
 ('همم', 'kastetme, niyetlenme (hemme); kaygılandırma (ehemmet)'),
 ('فضض', 'gümüş (fidda); dağılıp gitme (infaddû)'),
 ('أون', 'şimdi (el-âne)'),
 ('وعي', 'kap (vi\'â); biriktirme (ev\'â); belleme, koruma (te\'iye, vâiye)'),
 ('حصر', 'engellenme, kuşatılma (uhsira); daralma (hasirat); nefsine hâkim (hasûr); zindan (hasîr)'),
 ('رصد', 'gözetleme, pusu (rasad, mirsâd, marsad)'),
 ('حمي', 'kızdırılma (yuhmâ); kızgın (hâmiye); cahiliye taassubu (hamiyye); korunan hayvan (hâm)'),
 ('خلط', 'karışma (ihtelata); karıştırma (halata); ortaklar (hulatâ)'),
 ('كظم', 'öfkesini yutan, kederle dolu (kezîm, kâzım, mekzûm)'),
 ('كهف', 'mağara (kehf)'),
 ('مهل', 'erimiş maden, tortu (muhl); mühlet verme (mehhil, emhil)'),
 ('ذمم', 'kınanmış (mezmûm); ahit, güvence (zimme)'),
 ('قرف', 'işleme, kazanma — çoğu kötülük (iktirâf, muktarif)'),
 ('عنت', 'sıkıntı, meşakkat (anet); zorlama (a\'nete)'),
 ('حرص', 'hırs, düşkünlük, çok isteme (harasa, harîs, ahras)'),
 ('جوز', 'geçme, aşma (câveze); bağışlayıp geçme (netecâvezu)'),
 ('قدد', 'yırtma, yarma (qudde); farklı yollar, gruplar (qıded)'),
 ('عصر', 'sıkma, şıra çıkarma (ya\'sıru); kasırga (i\'sâr); yağmur bulutu (mu\'sırât); asır, zaman (asr)'),
 ('قرع', 'kapıyı çalan felaket, kıyamet (kâria)'),
 ('حيص', 'kaçacak yer, kurtuluş (mahîs)'),
 ('كمل', 'tamamlama, kemâle erdirme (ekmele); tam, eksiksiz (kâmil)'),
 ('هلل', 'adı anılarak kesilme (uhille); hilaller, yeni aylar (ehille)'),
 ('رفق', 'dayanak, yaslanılacak yer (murtafak); arkadaş (refîk); dirsek (mirfak)'),
 ('صدف', 'yüz çevirme (sadefe); iki dağ yamacı (sadefeyn)'),
 ('رحب', 'genişlik — genişken (rahubet); merhaba (marhaben)'),
 ('غور', 'yere çekilmiş su (gavr); mağara (gâr, meğâre)'),
 ('لمز', 'kusur arama, dil uzatma (yelmizu, lumeze)'),
 ('سخط', 'hoşnutsuzluk, gazap (sahita, sahat, eshata)'),
 ('جدر', 'duvar (cidâr, cudur); daha layık (ecder)'),
 ('زخرف', 'yaldız, süs, altın (zuhruf)'),
 ('مجد', 'şanlı, yüce (mecîd)'),
 ('ركن', 'dayanak, sağlam yan (rukn); meyletme, dayanma (terkenû)'),
 ('تبب', 'kurumak, helak olmak (tebbet); hüsran (tetbîb, tebâb)'),
 ('دلو', 'kova (delv); sarkıtma, aşağı salma (edlâ); sarkma, yaklaşma (tedellâ)'),
 ('سمم', 'zehirli sıcak rüzgâr (semûm); iğne deliği (semm)'),
 ('زلل', 'kayma, sürçme (zelle, ezelle, istezelle)'),
 ('غسق', 'gecenin karanlığı (gasak, gâsik); irin, soğuk ve kokuşmuş su (gassâk)'),
 ('هيأ', 'şekil, biçim (hey\'e); hazırlama, kolaylaştırma (yuhey\'i\')'),
 ('أمد', 'süre, zaman aralığı (emed)'),
 ('شور', 'danışma, istişare (şûrâ, teşâvür, şâvir); işaret etme (eşârat)'),
 ('سيح', 'gezip dolaşma (sîhû); oruç tutan, dolaşan (sâih, sâiha)'),
 ('لجأ', 'sığınak (melce\')'),
 ('أسس', 'temel atma (essese)'),
 ('لفت', 'dönüp bakma (yeltefit); çevirme, döndürme (telfite)'),
 ('نضد', 'dizi dizi, üst üste (mendûd, nadîd)'),
 ('حوج', 'ihtiyaç, istek (hâce)'),
 ('عير', 'kervan (îr)'),
 ('حرض', 'teşvik etme, coşturma (harrid); erime, çökme (harad)'),
 ('زبد', 'köpük (zebed)'),
 ('هطع', 'boynunu uzatıp koşan (muhti\')'),
 ('جزأ', 'parça, pay (cuz\')'),
 ('رغد', 'bolluk, rahat (rağad)'),
 ('ستر', 'örtü, perde (sitr); örtülü (mestûr); gizlenme (testetirûn)'),
 ('نأي', 'uzaklaşma, yan çizme (neâ)'),
 ('رقم', 'yazılmış, işaretlenmiş (merkûm); yazıt, kitabe (rakîm)'),
 ('شطط', 'haddi aşma, saçma söz (şetat); ölçüyü kaçırma (tuşdit)'),
 ('وصد', 'kapatılmış (mu\'sade); eşik, giriş (vasîd)'),
 ('ذرو', 'savurma (tezrû); savuran rüzgârlar (zâriyât)'),
 ('نقب', 'temsilci, önder (nakîb); delme, delik (nakb); dolaşıp araştırma (nakkabû)'),
 ('ألل', 'akrabalık bağı, ahit (ill)'),
 ('طعن', 'dil uzatma, saldırı (ta\'n, ta\'anû)'),
 ('عيل', 'yoksulluk (ayle); yoksul (âil)'),
 ('خبل', 'bozgunculuk, fesat (habâl)'),
 ('كسل', 'tembeller, üşenerek (kusâlâ)'),
 ('دمع', 'gözyaşı (dem\')'),
 ('شفو', 'kenar, uç (şefâ)'),
 ('هور', 'yıkılmak üzere (hâr); çöküp yıkılma (inhâra)'),
 ('أوه', 'çok içli, yumuşak kalpli (evvâh)'),
 ('خمص', 'açlık (mahmasa)'),
 ('حبس', 'alıkoyma (yahbisu)'),
 ('غيض', 'çekilme, eksilme — su (gîda); azalma'),
 ('جود', 'Cûdî dağı (cûdiyy); asil atlar (ciyâd)'),
 ('رفد', 'yardım, bağış (rifd); verilen (merfûd)'),
 ('سعد', 'mutlu (saîd, suidû)'),
 ('شهق', 'hıçkırık, inleme (şehîk)'),
 ('جبب', 'kuyu (cubb)'),
 ('حوش', 'hâşâ, uzak tutma (hâşe)'),
 ('بعر', 'deve, yük hayvanı (baîr)'),
 ('صنو', 'tek kökten çıkan gövdeler (sınvân)'),
 ('رعد', 'gök gürültüsü (ra\'d)'),
 ('جزع', 'sızlanma, feryat (cezi\'a, cezû\')'),
 ('صفد', 'zincirler, bukağılar (asfâd)'),
 ('أمل', 'umut, emel (emel)'),
 ('وسم', 'feraset sahibi, işaretlerden anlayan (mutevessim); damgalama (nesimu)'),
 ('لبن', 'süt (leben)'),
 ('نحل', 'gönül hoşluğuyla verilen hediye, mehir (nihle); arı (nahl)'),
 ('لمح', 'göz açıp kapama (lemh)'),
 ('حظر', 'yasaklanmış, engellenmiş (mahzûr); ağıl yapan (muhtezir)'),
 ('كلو', 'her ikisi (kilâ, kiltâ)'),
 ('رفت', 'ufalanmış kemik, toz (rufât)'),
 ('وسل', 'vesile, yaklaşma aracı (vesîle)'),
 ('شكل', 'yaratılış, mizaç (şâkile); benzer, tür (şekl)'),
 ('نبع', 'pınar, kaynak (yenbû\')'),
 ('عثر', 'farkına varılma, rastlanma (usira); haberdar etme (a\'sera)'),
 ('شوي', 'kavurma, haşlama (yeşvî); deri, kafa derisi (şevâ)'),
 ('حفف', 'kuşatma (hafefnâ); çevreleyen (hâff)'),
 ('زلق', 'kaygan, çıplak toprak (zelak); devirme, gözle yıkma (yuzlik)'),
 ('هشم', 'kuru ot, çer çöp (heşîm)'),
 ('غدر', 'geride bırakma, atlamama (yuğâdiru)'),
 ('وبق', 'helak yeri, uçurum (mevbik); helak etme (yûbik)'),
 ('حقب', 'uzun zaman, çağ (hukub, ahkâb)'),
 ('غطو', 'örtü, perde (ğıtâ\')'),
 ('رطب', 'yaş, nemli (ratb); taze hurma (rutab)'),
 ('جني', 'devşirilecek meyve (cenâ); taze devşirilmiş (ceniyy)'),
 ('ربح', 'kâr etme, kazanma (rabihat)'),
 ('كسد', 'kesatlık, sürümsüzlük (kesâd)'),
 ('وطن', 'yerler, savaş alanları (mevâtın)'),
 ('نجس', 'pislik, necis (necas)'),
 ('ضهأ', 'benzetme, taklit etme (yudâhi\')'),
 ('كوي', 'dağlanma (tukvâ)'),
 ('جبه', 'alınlar (cibâh)'),
 ('ثبط', 'alıkoyma, isteksiz kılma (sebbete)'),
 ('جمح', 'gemi azıya alarak koşma (yecmahûn)'),
 ('جرف', 'yar, çökmekte olan kenar (curuf)'),
 ('زري', 'hor görme, küçümseme (tezderî)'),
 ('بلع', 'yutma (ible\'î)'),
 ('قلع', 'durma, vazgeçme — yağmur (akli\'î)'),
 ('حنذ', 'kızartılmış, közlenmiş (hanîz)'),
 ('روع', 'korku, ürperti (rav\')'),
 ('طرح', 'atma, bırakma (itrahû)'),
 ('رتع', 'gezip eğlenme, otlanma (yerta\')'),
 ('درهم', 'dirhemler, gümüş paralar (derâhim)'),
 ('زهد', 'değer vermeyen, ilgisiz (zâhid)'),
 ('غلق', 'kapıları kilitleme (ğallakat)'),
 ('هيت', 'haydi gel (heyte)'),
 ('شغف', 'yüreğine işleme, tutku (şeğafe)'),
 ('خبز', 'ekmek (hubz)'),
 ('حصحص', 'ortaya çıkma, belirginleşme (hasbase)'),
 ('مير', 'erzak getirme, zahire alma (nemîru)'),
 ('صوع', 'kral su kabı, ölçek (suvâ\')'),
 ('فتأ', 'durmadan sürdürme — hâlâ (tefte\'u)'),
 ('ثرب', 'kınama, ayıplama (tesrîb)'),
 ('فند', 'bunaklıkla suçlama (tufennidûn)'),
 ('محل', 'çetin güç, tuzak (mihâl)'),
 ('جفأ', 'atılan köpük, süprüntü (cufâ\')'),
 ('جرع', 'yudumlama (yetecerra\'u)'),
 ('رمد', 'kül (remâd)'),
 ('فرع', 'dal (far\')'),
 ('جثث', 'kökünden sökülme (uctussat)'),
 # birleşik kayıt anahtarı 2:19-20 içinde (kapsam testi ikinci koşuda buldu)
 ('صبع', 'parmak (isba\', esâbi\')'),
]
nfc = lambda s: unicodedata.normalize('NFC', s)
korpus = {nfc(k): k for k in env}
eklendi, bulunamadi, zaten = [], [], []
for ara, tr in ISTEK:
    k = korpus.get(nfc(ara))
    if k is None: bulunamadi.append(ara); continue
    if k in kt: zaten.append(k); continue
    kt[k] = tr; eklendi.append((k, tr))
print('istek:', len(ISTEK), '· eklenen:', len(eklendi), '· zaten var:', zaten, '· bulunamayan:', bulunamadi)
assert not bulunamadi, 'NFC eşleşmesi yok — koşu DURDU'
json.dump(kt, open('kok_turkce.json', 'w', encoding='utf-8'), ensure_ascii=False, indent=1, sort_keys=True)
print('toplam kök:', len(kt))
