# -*- coding: utf-8 -*-
"""sad_metin_1.py — sûre 38 (Sâd) meal ve mercekler (◇ + ◈K ◈B ◈D ◈A), ayet 1-88.
Arapça sabit YOK: kökler yalnız korpus kök biçimiyle anılır, kelime biçimleri Latin harfle.
Yeni bloklar MEALn/Mn sözlükleri olarak eklenir ve sonda MEAL/M'ye katılır."""
MEAL = {}
M = {}

MEAL1 = {
 1: "Sâd. Zikir sahibi Kur'ân'a andolsun,",
 2: 'hayır, inkâr edenler bir büyüklenme ve ayrılık içindedir.',
 3: 'Onlardan önce nice nesilleri helâk ettik; feryat ettiler, ama artık kurtuluş vakti değildi.',
 4: 'İçlerinden bir uyarıcının gelmesine şaştılar; inkâr edenler dedi ki: "Bu, yalancı bir büyücüdür.',
 5: 'İlâhları tek bir ilâh mı yaptı? Şüphesiz bu çok tuhaf bir şey!"',
 6: 'İçlerinden ileri gelenler (şöyle diyerek) çıkıp gittiler: "Yürüyün, ilâhlarınıza sabredin; şüphesiz bu, (bizden) istenen bir şeydir.',
 7: 'Bunu son dinde (öteki millette) işitmedik; bu bir uydurmadan başka bir şey değil.',
 8: 'Zikir aramızdan ona mı indirildi?" Hayır, onlar benim zikrimden şüphe içindeler; hayır, henüz azabımı tatmadılar.',
 9: 'Yoksa mutlak güç sahibi, çok bağışlayan Rabbinin rahmet hazineleri onların yanında mı?',
 10: 'Yoksa göklerin, yerin ve ikisinin arasındakilerin mülkü onların mı? Öyleyse yollara (sebeplere) tırmansınlar!',
}
M1 = {
 1: "◇ Sûre tek harfle (Sâd; morfoloji INL, kök yok) ve yeminle açılıyor (QASEM): 've'l-qur'âni zi'z-zikr'. Adlı aktör Kur'ân (kitap, mecrur). Önceki sûre de yeminle açılmıştı (37:1 've's-sâffâti saffâ'), nesne adsız bir topluluktu; burada adlı bir kitap (okumada görüldü). قرأ [1/1]; ذكر [1/13] — kök sûrede 13 token, ilki 'zi'z-zikr'. Yeminin cevabı bu ayette yok; 38:2 'bel' ile açılıyor. harf 36 → harf3 16 (besmele + mukattaa farkı). Fâsıla ر (R sınıfı). 4 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 yemin, fiil yok; D2 QASEM; D3 'zû' tamlaması (zikir sahibi); D4 şahıs işareti yok.\n◈A — A1 Kur'ân (adlı kitap, yemin nesnesi); A4 sûre açılışı.",
 2: "◇ 'beli'llezîne keferû fî izzetin ve şiqâq' — 'bel' (IDRAB) ile yön değişimi: inkâr edenler büyüklenme ve ayrılık içinde. عزز [1/5]: 37:180 'rabbi'l-izzeti' (okundu — izzet Rab'bin) → 38:2 'fî izzetin' (izzet inkârcıların) → 38:9 'el-azîz' (Rab'bin sıfatı) — aynı kök, iki sahip (okumada görüldü). كفر [1/5]; شقق [1/1]. Fâsıla ق. 6 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 isim cümlesi (sıla + câr-mecrûr haber); D2 IDRAB; D4 3MP 2.\n◈A — A1 'inkâr edenler' (adsız sınıf); A3 yeminin ardından hüküm.",
 3: "◇ 'kem ehleknâ min qablihim min qarnin fe-nâdev ve lâte hîne menâs' — 1P 2: nice nesli helâk ettik; seslendiler, ama kurtuluş vakti değildi. İki HAPAKS: لوت ('lâte', olumsuzluk edatı) ve نوص ('menâs') → ★★★ kaynak hapaks z=6,79 (983 ailesi). هلك [1/1]; قرن [1/2] (nesil); ندي [1/2]: 'fe-nâdev' — 37:75 'nâdânâ nûhun' ve 37:104 'nâdeynâhu' ile aynı fiil, burada helâk edilenlerin feryadı (okumada görüldü). حين [1/2]. Fâsıla ص. 10 kelime.\n◈K — K1 —; K2 zaman: 'lâte hîne menâs' — kurtuluş vakti geçmiş; geçmişteki nesiller (PERF), 'min qablihim'; K3 —; K4 —.\n◈B — —\n◈D — D1 'kem' (haberî, çokluk) + PERF; D3 olumsuzluk edatı 'lâte' (hapaks) + zaman ismi; D4 1P 2 · 3MP 3.\n◈A — A1 'biz', helâk edilen nesiller (adsız); A2 sahne: geçmiş; A3 feryat — cevapsız.",
 4: "◇ 've acibû en câehum munzirun minhum; ve qâle'l-kâfirûne hâzâ sâhirun kezzâb' — şaşma + söz alıntısı (DIKKAT, işaret). xref 50:2 'bel acibû en câehum munzirun minhum fe-qâle'l-kâfirûne hâzâ şey'un acîb' — henüz okunmadı; xref 10:2 (okundu) 'qâle'l-kâfirûne inne hâzâ le-sâhirun mubîn'. سحر [1/1]; كذب [1/3]; نذر [1/3] ('munzir'); عجب [1/2]: 38:4 'acibû' → 38:5 'ucâb'. كفر [2/5]; قول [1/23]. Fâsıla ب. 10 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 iki fiil cümlesi + alıntı (isim cümlesi); D2 işaret 'hâzâ' (uyarıcıya); D4 3MP 4 · 3MS 2.\n◈A — A1 inkârcılar (konuşan), uyarıcı (adsız, 'içlerinden'); A3 sözle reddediş.",
 5: "◇ 'e-ce'ale'l-âliheta ilâhen vâhidâ; inne hâzâ le-şey'un ucâb' — alıntı sürüyor: soru (INTG) + tekit (EMPH). أله ×2 [1,2/7] ('âlihe' / 'ilâh'); sayı işareti vâhid (doğru). xref 7:138 (okundu): 'ic'al lenâ ilâhen kemâ lehum âliha' — orada Benî İsrâîl Mûsâ'dan put isterken, burada inkârcılar ilâhların teke indirilmesine şaşıyor; ilâh/âlihe çifti ters yönde (okumada görüldü). Önceki sûrenin dördüncü ayeti 37:4 'inne ilâhekum le-vâhid' (okundu) — burada itiraz edilen iddia (okumada görüldü, KAPATILAMAZ). nakarat3 'inne hâzâ le-şey'un' eşi 38:6 (GEÇMEZ). عجب [2/2] kapanıyor; وحد [1/4]; جعل [1/4]. 8 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 istifhâm (taaccüp) + tekitli isim cümlesi; D3 أله ikilemesi (çoğul → tekil); D4 3MS 1.\n◈A — A1 inkârcılar (konuşan), uyarıcı (3MS özne); A3 şaşma.",
 6: "◇ 've'ntaleqa'l-meleu minhum eni'mşû ve'sbirû alâ âlihetikum; inne hâzâ le-şey'un yurâd' — ileri gelenler gidiyor, söz alıntısı: iki emir (IMPV 2) + tekit. EDİLGEN 1/4 'yurâd' (isteniyor), pas z=1,10 — yıldız yok; isteyen adlanmıyor. nakarat3 'inne hâzâ le-şey'un' eşi 38:5: biri 'ucâb' (tuhaf), biri 'yurâd' (istenen) (okumada görüldü). 12 kelime — blokun en uzun ikinci ayeti (38:8 15). طلق [1/1], مشي [1/1], رود [1/1]; ملأ [1/3]; صبر [1/3]; أله [3/7]. Fâsıla د.\n◈K — —\n◈B — —\n◈D — D1 haber + 'en' tefsiriye ile alıntı: iki emir + tekitli isim cümlesi; D4 2MP 5 (alıntı içi) · 3MP 1 · 3MS 2.\n◈A — A1 'el-mele'' (ileri gelenler, adsız topluluk) konuşan; muhatap kendi toplulukları; A2 sahne: gidiş ('intalaqa'); A3 birbirine emir.",
 7: "◇ 'mâ semi'nâ bi-hâzâ fi'l-milleti'l-âhirati in hâzâ ille'htilâq' — alıntı içi 1P: bunu son/öteki dinde işitmedik; bu ancak uydurma (NEG 2 + RES, HASR + DIKKAT). İltifât alanı 1: 38:6 → 38:7 1P — alıntı içi 'biz' (1017 ailesi). خلق [1/6]: 'ihtilâq' (VIII. bab, uydurma) — gloss 'yaratma' bu anlamı taşımıyor (987/1015 ailesi, kayıt). سمع [1/1], ملل [1/1]; أخر [1/3]. esmâ: âhir e_oto 1 → e_el 'degil' (milletin sıfatı); ölçüm satırı ORTA konum. Fâsıla ق. 10 kelime, yıldız yok.\n◈K — —\n◈B — B1 —; B2 —; B3 işitme (سمع) — organ adlanmıyor, işlev fiil olarak, olumsuz ('mâ semi'nâ'); B4 —.\n◈D — D1 iki olumsuz cümle: mâ + PERF / in … illâ (hasr); D2 HASR + işaret; D4 1P 2.\n◈A — A1 ileri gelenler (alıntı içi 'biz'); A3 reddin gerekçesi: işitilmemiş olmak.",
 8: "◇ 'e-unzile aleyhi'z-zikru min beyninâ; bel hum fî şekkin min zikrî; bel lemmâ yezûqû azâb' — blokun en uzun ayeti (15 kelime). İlk cümle alıntı (onların 'beyninâ'sı, 1P); 'bel' ile anlatıcı araya giriyor ve 1S konuşuyor: 'zikrî' (benim zikrim), 'azâbi' (benim azabım — iyelik yâsı yazıda düşmüş) — ayet içinde 1P (onlar) → 1S; iltifât alanı ayetler arası olduğu için 0 (kayıt). EDİLGEN 1/2 'e-unzile', pas z=2,52 → ★★ kaynak pas; indiren adlanmıyor. ذكر ×2 [2,3/13]: 38:1 'zi'z-zikr' → 38:8 'ez-zikr' (onların ağzında) / 'zikrî' (1S). شكك [1/1]; ذوق [1/2]; عذب [1/4]; نزل [1/2]; بين [1/7]. Fâsıla ب.\n◈K — —\n◈B — —\n◈D — D1 soru (INTG, edilgen) + iki 'bel' (IDRAB); D3 ذكر ikilemesi; D4 1P 1 · 1S 2 · 3MP 3 · 3MS 2.\n◈A — A1 inkârcılar (alıntı), konuşan 'ben' (1S, adsız); A3 alıntıya karşı cevap aynı ayette.",
 9: "◇ 'em indehum hazâinu rahmeti rabbike'l-azîzi'l-vehhâb' — 'em' ile soru: Rabbinin rahmet hazineleri onların yanında mı? Rab sûrede ilk kez, 2MS iyelikle ('rabbike'); ★★ kaynak rab z=2,72. İki esmâ, ayet sonunda yan yana: azîz, vehhâb — ikisi de Rab'bin sıfatı → e_el 'ilahi'; §4.3 mühür EVET (ÇİFT) ve geçerli. xref 17:100 (okundu): 'lev entum temlikûne hazâine rahmeti rabbî' — orada 'rabbî' (1S), burada 'rabbike' (2MS) (okumada görüldü). عزز [2/5]: 38:2 'izzet' (inkârcıların) → 38:9 'el-azîz'. وهب [1/5]: 37:100 'heb lî' (İbrâhîm'in duası, okundu) ile aynı kök (okumada görüldü). خزن [1/1]; رحم [1/2]; عند [1/5]. Fâsıla ب. 7 kelime.\n◈K — —\n◈B — —\n◈D — D1 'em' (munkatı'a) + isim cümlesi; D3 iki sıfat ard arda (esmâ çifti); D4 2MS 1 · 3MP 1.\n◈A — A1 'onlar', Rab (2MS iyelik — muhatap Peygamber); A3 sorgu.",
 10: "◇ 'em lehum mulku's-semâvâti ve'l-ardi ve mâ beynehumâ; fe'l-yerteqû fi'l-esbâb' — ikinci 'em' sorusu + üçüncü şahsa emir (lâm-ı emir, IMPV): öyleyse yollara tırmansınlar. Öbek 'es-semâvâti ve'l-ardı ve mâ beynehumâ' harekesiz metin sayımıyla korpusta 17 ayet; sûre içinde nakarat3 3 ayet (GEÇER) — eşler henüz okunmadı; 37:5 (okundu) 'rabbu's-semâvâti ve'l-ardı ve mâ beynehumâ' (okumada görüldü). رقي [1/1], سبب [1/1]; ملك [1/5]; سمو [1/3]; أرض [1/5]; بين [2/7]. Fâsıla ب (38:4-5 ve 38:8-10 ب). 10 kelime, yıldız yok. 🜁 L0 — gökler, yer ve ikisinin arası adlanıyor; tek ilişki mülk (sahiplik sorusu) ve 'esbâb'a yükselme emri; süreç/ölçü yok (37:5 emsali); olgu evet, çıpa hayır; tarayıcı vermedi.\n◈K — K1 gökler (semâvât, lemma semâ'), yer, ikisinin arası; K2 —; K3 ölçek: en büyük birimler (gökler ve yer), sahiplik sorusu içinde; K4 hareket: 'yerteqû' (yükselsinler, VIII. bab) — özne onlar (emir, meydan okuma), hedef 'esbâb' (yollar/sebepler).\n◈B — —\n◈D — D1 'em' + isim cümlesi + fâ ile lâm-ı emir; D4 3MP 3 · 3D 1.\n◈A — A1 'onlar'; A3 meydan okuma; A4 blok sorularla kapanıyor (9 ve 10, iki 'em').",
}
MEAL.update(MEAL1); M.update(M1)

MEAL2 = {
 11: 'Onlar, orada bozguna uğratılacak hiziplerden (ahzâb) önemsiz bir ordudur.',
 12: 'Onlardan önce Nûh kavmi, Âd ve kazıklar sahibi Firavun da yalanlamıştı;',
 13: 'Semûd, Lût kavmi ve Eyke halkı da. İşte hizipler bunlardır.',
 14: 'Her biri elçileri yalanlamaktan başka bir şey yapmadı; bu yüzden cezam hak oldu.',
 15: 'Bunlar yalnızca tek bir çığlığı bekliyor; onun için bir duraklama yoktur.',
 16: 'Dediler ki: "Rabbimiz, hesap gününden önce payımızı bize çabucak ver!"',
 17: "Söylediklerine sabret ve güç sahibi kulumuz Dâvûd'u an; o çok dönen (evvâb) biriydi.",
 18: 'Biz dağları onunla birlikte boyun eğdirdik; akşam ve güneş doğarken tesbih ederler.',
 19: 'Kuşları da toplanmış olarak (boyun eğdirdik); hepsi ona dönüp duran (evvâb) idi.',
 20: "Onun mülkünü güçlendirdik; ona hikmeti ve sözü ayırt etmeyi (faslu'l-hıtâb) verdik.",
}
M2 = {
 11: "◇ 'cundun mâ hunâlike mehzûmun mine'l-ahzâb' — fiilsiz isim cümlesi: önemsiz ('mâ' belirsizlik) bir ordu, orada bozguna uğratılacak. هزم [1/1] — kök korpusta 3 ayet: 2:251 'fe-hezemûhum' (okundu — Dâvûd'un Câlût'u öldürdüğü ayet), 38:11, 54:45 (henüz okunmadı) (okumada görüldü, KAPATILAMAZ). جند [1/1]; حزب [1/2]: 38:11 'mine'l-ahzâb' → 38:13 'ulâike'l-ahzâb'. Fâsıla ب. 6 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 isim cümlesi, fiil yok; D3 'mâ' (tahkir) + işaret zarfı 'hunâlike'; D4 şahıs işareti yok.\n◈A — A1 'ordu' (adsız, inkârcılar); A3 bozgun haberi (ism-i meful 'mehzûm').",
 12: "◇ 'kezzebet qablehum qavmu nûhin ve âdun ve fir'avnu zu'l-evtâd' — yalanlayan topluluklar sayılıyor: Nûh kavmi, Âd, 'kazıklar sahibi' Firavun (aktör üç adlı). ذو MS sûrede 1-20 arasında üç kez: 38:1 'zi'z-zikr', 38:12 'zu'l-evtâd', 38:17 'ze'l-eyd' (okumada görüldü). 'zu'l-evtâd' korpusta 1 ayet; 'el-evtâd' 2 ayet (38:12, 89:10 henüz okunmadı). Kök alanında 'Âd' عود 'geri dönme' olarak sayılıyor — özel ad kök alanına giriyor (araç açığı, 924). كذب [2/3]; قبل [2/3]: 38:3 'min qablihim' → 38:12 'qablehum'. وتد [1/1]. Fâsıla د — KAFİYE KIRILMASI (38:11 ب → 38:12 د) → ★ kaynak kafiye. 8 kelime.\n◈K — —\n◈B — —\n◈D — D1 tek fiil (PERF, müennes 'kezzebet') + dört özne; D3 'zû' tamlaması; D4 3FS 1 · 3MP 1.\n◈A — A1 Nûh kavmi, Âd, Firavun (adlı); A2 sahne: geçmiş; A3 yalanlama.",
 13: "◇ 've semûdu ve qavmu lûtin ve ashâbu'l-eyke; ulâike'l-ahzâb' — liste sürüyor: Semûd, Lût kavmi, Eyke halkı; 'işte hizipler bunlar'. 38:12-13 altı topluluk. 'Eyke' (LEM eyke) morfolojide ne kök ne özel ad etiketi taşıyor — kök listesinde ve aktör alanında yok (araç açığı, 924); 'l-eyke' yazımı (ل ile) korpusta 2 ayet: 26:176 (okundu), 38:13; 'el-eyke' 2 ayet: 15:78 (okundu), 50:14 (henüz okunmadı). حزب [2/2] kapanıyor; قوم [2/2] kapanıyor; صحب [1/1]. Fâsıla ب (kırıktan sonra geri). 7 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 öncekine atıf (fiil 38:12'de) + işaret cümlesi; D2 işaret 'ulâike'; D4 şahıs işareti yok.\n◈A — A1 Semûd, Lût kavmi (adlı), Eyke halkı (alan dışı); A3 listenin adı: 'ahzâb'.",
 14: "◇ 'in kullun illâ kezzebe'r-rusule fe-haqqa ıqâb' — HASR (in … illâ): her biri elçileri yalanladı; 'ıqâbi' (benim cezam) — 1S iyelik yâsı yazıda düşmüş, morfoloji 1S sayıyor; 38:8 'azâbi' ile aynı yapı, ikisi de fâsıla ب (okumada görüldü). xref 50:14 'kullun kezzebe'r-rusule fe-haqqa vaîd' — henüz okunmadı. كذب [3/3] kapanıyor; عقب [1/1]; رسل [1/1]; حقق [1/6]; كلل [1/5]. 7 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 hasr + fâ ile sonuç; D2 HASR; D4 1S 1 · 3MS 2.\n◈A — A1 topluluklar ('kull'), elçiler (adsız çoğul), konuşan 'ben' (1S); A3 yalanlama → ceza.",
 15: "◇ 've mâ yanzuru hâulâi illâ sayhaten vâhideten mâ lehâ min fevâq' — HASR + işaret: bunlar yalnız tek bir çığlığı bekliyor; ona duraklama yok. 'sayhaten vâhideten' (harekesiz metin sayımı) korpusta 5 ayet: 36:29, 36:49, 36:53 (okundu), 38:15, 54:31 (henüz okunmadı); xref 36:49 'mâ yanzurûne illâ sayhaten vâhideten' (okundu). Sayı işareti vâhide (doğru). فوق [1/1]: 'fevâq' (iki sağım arası, duraklama) — gloss 'üst, üstünde' bu anlamı taşımıyor (987/1015 ailesi, kayıt). صيح [1/1]; نظر [1/3]; وحد [2/4]: 38:5 'ilâhen vâhidâ' → 38:15 'sayhaten vâhide'. Fâsıla ق — KAFİYE KIRILMASI → ★ kaynak kafiye. 10 kelime.\n◈K — —\n◈B — —\n◈D — D1 olumsuz hasr (mâ … illâ) + olumsuz isim cümlesi; D2 HASR + işaret 'hâulâi'; D4 3FS 1 · 3MS 1.\n◈A — A1 'bunlar' (inkârcılar); A3 bekleyiş — tek çığlık.",
 16: "◇ 've qâlû rabbenâ accil lenâ qıttanâ qable yevmi'l-hisâb' — inkârcıların ağzında dua kalıbı: 'Rabbimiz, payımızı acele ver'. Rab sûrede ikinci kez: 38:9 'rabbike' (2MS) → 38:16 'rabbenâ' (1P, inkârcıların sözü) (okumada görüldü). HAPAKS قطط ('qıtt') → ★★★ kaynak hapaks z=3,28; rab z=2,34. 'yevmi'l-hisâb' (metin sayımı) korpusta 4 ayet: 38:16, 38:26, 38:53, 40:27 — üçü bu sûrede; 38:26, 38:53, 40:27 henüz okunmadı. قبل [3/3] kapanıyor; عجل [1/1]; يوم [1/6]; حسب [1/4]; قول [2/23]; ربب [2/10]. Fâsıla ب. 8 kelime.\n◈K — K1 —; K2 zaman: 'qable yevmi'l-hisâb' — hesap gününden önce; acele isteği ('accil'); K3 —; K4 —.\n◈B — —\n◈D — D1 haber + alıntı: nidâ + emir (IMPV, dua kipi); D4 1P 3 · 2MS 1 · 3MP 2.\n◈A — A1 inkârcılar (konuşan), Rab (hitap); A3 alaycı istek (pay, acele).",
 17: "◇ 'isbir alâ mâ yaqûlûne ve'zkur abdenâ dâvûde ze'l-eyd; innehû evvâb' — iki emir (IMPV 2), muhatap 2MS: söylediklerine sabret, kulumuz Dâvûd'u an. Dâvûd sûrede ilk kez (aktör adlı, meful); korpusta Dâvûd lemması 16 ayet, sûre 38'de 5 (17, 22, 24, 26, 30 — dördü henüz okunmadı). 'isbir alâ mâ yaqûlûn' (metin sayımı) korpusta 4 ayet: 20:130 (okundu), 38:17, 50:39, 73:10 (henüz okunmadı). صبر [2/3]: 38:6 inkârcılar 've'sbirû alâ âlihetikum' → 38:17 'isbir alâ mâ yaqûlûn' — aynı emir iki tarafa (okumada görüldü). ذكر [4/13]: 'vezkur'. أوب [1/8]: 'evvâb' — kök sûrede 8 token. أيد [1/1] ('eyd', güç); عبد [1/6]; قول [3/23]. Fâsıla ب. 11 kelime — blokun en uzunu.\n◈K — —\n◈B — —\n◈D — D1 iki emir + tekitli isim cümlesi; D3 'zû' tamlaması (ze'l-eyd); D4 1P 1 · 2MS 2 · 3MP 2 · 3MS 1.\n◈A — A1 muhatap (2MS), Dâvûd (adlı, 'kulumuz'), 'biz'; A2 sahne geçişi: inkârcılardan Dâvûd'a; A3 sabır + anma emri.",
 18: "◇ 'innâ sahharne'l-cibâle meahû yusebbihne bi'l-aşiyyi ve'l-işrâq' — 1P 3: dağları onunla birlikte boyun eğdirdik; akşam ve güneş doğarken tesbih ederler (3FP, dağlar özne). xref 21:79 (okundu): 've sahharnâ mea dâvûde'l-cibâle yusebbihne ve't-tayr' — 'sahhara' + 'cibâl' korpusta yalnız bu iki ayette. 34:10 (okundu) 'yâ cibâlu evvibî meahû ve't-tayr' — orada dağlara أوب emri, burada 38:17 ve 38:19 'evvâb' (okumada görüldü, KAPATILAMAZ). سخر [1/3]; جبل [1/1]; سبح [1/1]; عشو [1/2]; شرق [1/1]. Fâsıla ق — KAFİYE KIRILMASI → ★ kaynak kafiye. 7 kelime. 🜁 L0 — dağlar ve günün iki ucu adlanıyor; ilişki teshir + tesbih; süreç/ölçü yok; olgu evet, çıpa hayır; tarayıcı vermedi.\n◈K — K1 dağlar (cibâl); K2 zaman: akşam ('aşiyy') ve doğuş ('işrâq') — günün iki ucu; K3 —; K4 hareket: dağlar özne, eylem tesbih (IMPF, süreklilik); teshir eden 1P.\n◈B — —\n◈D — D1 tekit (innâ) + PERF + hâl cümlesi (IMPF); D4 1P 3 · 3FP 2 · 3MS 1.\n◈A — A1 'biz', dağlar (özne), Dâvûd ('meahû'); A3 tesbihte birliktelik.",
 19: "◇ 've't-tayra mahşûrah; kullun lehû evvâb' — kuşlar da (boyun eğdirildi), toplanmış hâlde; hepsi ona dönüp duran. 38:18 dağlar → 38:19 kuşlar: 21:79 ve 34:10'da (okundu) dağ + kuş tek ayette, burada iki ayete bölünmüş (okumada görüldü). أوب [2/8]: 38:17 Dâvûd 'evvâb' → 38:19 'kullun lehû evvâb' — aynı sıfat Dâvûd'a ve dağ/kuşlara (okumada görüldü). حشر [1/1]: 'mahşûra' (ism-i meful, edilgen anlam; fiil olmadığı için edilgen alanı 0). طير [1/1]; كلل [2/5]. Fâsıla ب. 5 kelime — blokun en kısası, yıldız yok. 🜁 L0 — kuşlar adlanıyor, toplanmış hâlde; ilişki yönelim; süreç/ölçü yok; olgu evet, çıpa hayır; tarayıcı vermedi.\n◈K — —\n◈B — B1 kuşlar (tayr); B2 —; B3 —; B4 toplanmış ('mahşûra') ve 'ona dönen' — canlı, yönelimle anılıyor.\n◈D — D1 atıf (fiil 38:18'de) + isim cümlesi; D4 3MS 1.\n◈A — A1 kuşlar, 'hepsi', Dâvûd (zamir); A3 dönüş (evvâb).",
 20: "◇ 've şededna mulkehû ve âteynâhu'l-hikmete ve fasle'l-hıtâb' — 1P 4: mülkünü güçlendirdik; hikmet ve sözü ayırt etmeyi verdik. 2:251 (okundu) 've âtâhu'llâhu'l-mulke ve'l-hikmete' — Dâvûd'a mülk + hikmet; orada verici lafız (3. şahıs), burada 'biz' (okumada görüldü). ملك [2/5]: 38:10 'mulku's-semâvâti' (inkârcılara soru) → 38:20 'mulkehû' (Dâvûd'a verilen) (okumada görüldü). شدد [1/2]; أتي [1/2]; حكم [1/3]; فصل [1/1]; خطب [1/2]. Fâsıla ب. 6 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 iki PERF fiil (1P), iki meful; D4 1P 4 · 3MS 2.\n◈A — A1 'biz', Dâvûd (zamir); A3 verilenler: mülk, hikmet, faslu'l-hıtâb; A4 blok Dâvûd'a verilenlerle kapanıyor.",
}
MEAL.update(MEAL2); M.update(M2)

MEAL3 = {
 21: 'Davacıların haberi sana geldi mi? Hani duvarı aşıp mihraba girmişlerdi.',
 22: 'Dâvûd\'un yanına girdiklerinde ondan korktu. Dediler ki: "Korkma; biz iki davacıyız, birimiz ötekine haksızlık etti. Aramızda hakkaniyetle hüküm ver, aşırı gitme ve bizi yolun ortasına (doğrusuna) ilet.',
 23: 'Şu kardeşimin doksan dokuz dişi koyunu var, benim tek bir dişi koyunum var. "Onu da bana ver" dedi ve sözde beni yendi."',
 24: '(Dâvûd) dedi ki: "Andolsun, senin koyununu kendi koyunlarına katmak istemekle sana haksızlık etmiş. Ortakların çoğu birbirine haksızlık eder; iman edip iyi işler yapanlar hariç — onlar da ne kadar az!" Dâvûd, kendisini sınadığımızı anladı; Rabbinden bağışlanma diledi, rükû ederek yere kapandı ve (O\'na) yöneldi.',
 25: 'Biz de bunu ona bağışladık. Şüphesiz onun katımızda bir yakınlığı ve güzel bir dönüş yeri vardır.',
 26: 'Ey Dâvûd! Seni yeryüzünde halife kıldık; insanlar arasında hakkaniyetle hüküm ver, hevâya uyma; yoksa seni Allah\'ın yolundan saptırır. Allah\'ın yolundan sapanlara, hesap gününü unutmaları yüzünden çetin bir azap vardır.',
 27: 'Göğü, yeri ve ikisinin arasındakileri boş yere yaratmadık. Bu, inkâr edenlerin zannıdır. Ateşten dolayı vay inkâr edenlerin hâline!',
 28: 'Yoksa iman edip iyi işler yapanları yeryüzünde bozgunculuk yapanlar gibi mi tutacağız? Yoksa sakınanları günahkârlar gibi mi tutacağız?',
 29: '(Bu,) ayetlerini düşünsünler ve akıl sahipleri öğüt alsın diye sana indirdiğimiz bereketli bir kitaptır.',
 30: "Dâvûd'a Süleymân'ı bağışladık. Ne güzel kuldu! O çok dönen (evvâb) biriydi.",
}
M3 = {
 21: "◇ 've hel etâke nebeu'l-hasmi iz tesevverû'l-mihrâb' — soru (INTG), muhatap 2MS: davacıların haberi geldi mi? 'hel etâke' (metin sayımı) korpusta 6 ayet: 20:9 (okundu), 38:21, 51:24, 79:15, 85:17, 88:1 (henüz okunmadı). 'el-mihrâb' 4 ayet: 3:37, 3:39, 19:11 (okundu — üçü Zekeriyyâ sahnesi), 38:21 (okumada görüldü, KAPATILAMAZ). سور [1/1] 'tesevverû' (duvarı aşma, V. bab); حرب [1/1]; خصم [1/4]; نبأ [1/3]; أتي [2/2] kapanıyor. Fâsıla ب. 7 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 istifhâm + 'iz' ile zaman cümlesi (PERF); D4 2MS 1 · 3MP 2 · 3MS 1.\n◈A — A1 muhatap (2MS), davacılar ('el-hasm', adsız); A2 sahne: mihrap; A3 anlatı açılışı.",
 22: "◇ 'iz dehalû alâ dâvûde fe-fezia minhum; qâlû lâ tehaf; hasmâni beğâ ba'dunâ alâ ba'd; fahkum beynenâ bi'l-haqqi ve lâ tuştıt ve'hdinâ ilâ sevâi's-sırât' — Dâvûd korkuyor; davacılar konuşuyor: yasak (NEHY 2) + emir (IMPV 2). 'ihdinâ' (metin sayımı) korpusta 2 ayet: 1:6 (okundu, 'ihdine's-sırâta'l-mustaqîm') ve 38:22 — ikisinde de hidâyet + sırât; birinde kulun duası, burada davacıların hâkime isteği (okumada görüldü, KAPATILAMAZ). nakarat3 'beğâ ba'dunâ alâ ba'd' eşi 38:24 (GEÇER). 'fahkum beyne' 5 ayet: 3:55, 5:42, 5:48 (okundu), 38:22, 38:26; 'bi'l-haqqi ve lâ' 3 ayet: 25:68, 38:22, 38:26. شطط [1/1] — kök korpusta 3 ayet: 18:14 (okundu), 38:22, 72:4 (henüz okunmadı). فزع [1/1], خوف [1/1], هدي [1/1], صرط [1/1], دخل [1/1]; بعض ×2 [1,2/4]; حكم [2/3]: 38:20 'el-hikme' → 38:22 'fahkum'. Fâsıla ط — KAFİYE KIRILMASI → ★ (kafiye kırığı; n z=1,12). 23 kelime.\n◈K — —\n◈B — —\n◈D — D1 zaman cümlesi + alıntı: iki yasak, iki emir; D2 NEHY; D3 بعض ikilemesi; D4 1P 3 · 2MS 3 · 3FS 1 · 3MP 5 · 3MS 2.\n◈A — A1 Dâvûd (adlı, korkan), davacılar (konuşan, 'biz'); A3 dava sunumu.",
 23: "◇ 'inne hâzâ ahî lehû tis'un ve tis'ûne na'ceten ve liye na'cetun vâhide; fe-qâle ekfilnîhâ ve azzenî fi'l-hıtâb' — davacının sözü (1S 4): doksan dokuz / bir. Sayı işaretleri tis', tis', vâhide (doğru). 'tis'un ve tis'ûne' korpusta 1 ayet. نعج ×2 [1,2/4] — kök korpusta yalnız 38:23-24 (2 ayet). ◈B tetik listesi نعج'yi içermiyor → ◈B '—' (kayıt; S1 gereği tetik değişikliği yalnız ileriye). خطب [2/2]: 38:20 'fasle'l-hıtâb' (Dâvûd'a verilen) → 38:23 'azzenî fi'l-hıtâb' (sözde yenilgi, dava konusu) (okumada görüldü). عزز [3/5]: 38:2 'izzet' (inkârcılar) → 38:9 'el-azîz' → 38:23 'azzenî' (yendi). وحد [3/4]: 38:5 vâhid → 38:15 vâhide → 38:23 vâhide. أخو [1/1]; كفل [1/2]; تسع ×2 [1,2/2]; قول [5/23]. Fâsıla ب. 15 kelime, yıldız yok. 🜁 L1 — dişi koyunlar adlanıyor + sayı (99/1) ve sahiplik (36:71 en'âm emsali); misal anlatı içinde, süreç/ölçü yok; tarayıcı v4 adayı (F_ölçü — sayılar), çıpa değil (948).\n◈K — —\n◈B — —\n◈D — D1 tekitli isim cümlesi (DIKKAT) + alıntı içinde alıntı (emir); D3 sayı karşıtlığı 99/1; نعج ikilemesi; D4 1S 4 · 2MS 1 · 3FS 1 · 3MS 3.\n◈A — A1 davacı (1S), 'kardeşim' (3MS); A3 haksızlık şikâyeti.",
 24: "◇ 'qâle leqad zalemeke bi-suâli na'cetike ilâ niâcih; ve inne kesîren mine'l-hulatâi le-yebğî ba'duhum alâ ba'din illa'llezîne âmenû ve amilu's-sâlihâti ve qalîlun mâ hum; ve zanne dâvûdu ennemâ fetennâhu fe'steğfera rabbehû ve harra râkian ve enâb' — blokun en uzun ayeti (32 kelime). Üç parça: Dâvûd'un hükmü; genel kural (HASR, istisna); Dâvûd'un anlayışı ve dönüşü. 'fetennâhu' (1P) Dâvûd'un zannı içinde. Rab sûrede üçüncü kez: 38:9 'rabbike' → 38:16 'rabbenâ' → 38:24 'rabbehû' (3MS, Dâvûd'un Rabbi). Metinde secde işareti ۩. Sayı işaretleri kesîr / qalîl (karşıt). nakarat3 ×2: 'beğâ ba'd alâ ba'd' eşi 38:22 (davacının sözü Dâvûd'un ağzında genel kurala dönüşüyor — okumada görüldü); 'ellezîne âmenû ve amilu's-sâlihât' eşi 38:28 (GEÇER ikisi de). 'ba'duhum alâ ba'd' metin sayımı 9 ayet. 'fe'steğfera rabbehû' ve 'harra râkian' korpusta 1'er ayet. نعج ×2 [3,4/4] kapanıyor; خلط [1/1] 'hulatâ'; ركع [1/1]; خرر [1/1]; قلل [1/1]; ظلم [1/1]; فتن [1/2]; نوب [1/2] 'enâbe'; غفر [1/4]; بعض [3,4/4] kapanıyor. Fâsıla ب. ★★ kaynak n (uzunluk z=2,08). 🜁 L1 — koyunlar + sahiplik/katma; süreç/ölçü yok; tarayıcı v4 adayı (F_ölçü — kesîr/qalîl), çıpa değil (948).\n◈K — —\n◈B — —\n◈D — D1 qasem lâmı + tekit (CERT/EMPH) + hasr + PERF zinciri (zanne → isteğfera → harra → enâbe); D2 HASR; D3 iki ikileme (بعض, نعج); D4 1P 2 · 2MS 2 · 3MP 6 · 3MS 10.\n◈A — A1 Dâvûd (adlı, hükmeden → sınanan), davacılar, 'ortaklar' (sınıf), Rab; A3 hüküm → fark ediş → istiğfar → secde → inâbe.",
 25: "◇ 'fe-ğafernâ lehû zâlik; ve inne lehû indenâ le-zulfâ ve husne meâb' — 1P 3: bağışladık; katımızda yakınlık ve güzel dönüş yeri. غفر [2/4]: 38:24 'fe'steğfera' → 38:25 'fe-ğafernâ' — istek ve karşılık ardışık ayetlerde (okumada görüldü). nakarat3 'inne lehû indenâ le-zulfâ ve husne meâb' (6 kelime) eşi 38:40 — henüz okunmadı (GEÇER); 'zulfâ ve husne' metin sayımı 2 ayet (38:25, 38:40). أوب [3/8]: 38:17 'evvâb' → 38:25 'meâb' (dönen → dönüş yeri) (okumada görüldü). عند [2/5]: 38:9 'em indehum' (onların yanında mı?) → 38:25 'indenâ'. زلف [1/2]; حسن [1/3]. Fâsıla ب. 9 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 fâ + PERF (1P) + tekitli isim cümlesi; D4 1P 3 · 3MS 2.\n◈A — A1 'biz', Dâvûd (zamir); A3 bağışlama, yakınlık.",
 26: "◇ 'yâ dâvûdu innâ ce'alnâke halîfeten fi'l-ardı fahkum beyne'n-nâsi bi'l-haqqi ve lâ tettebi'i'l-hevâ fe-yudılleke an sebîli'llâh; inne'llezîne yadıllûne an sebîli'llâhi lehum azâbun şedîdun bimâ nesû yevme'l-hisâb' — nidâ (VOC) + emir + yasak. ALLAH LAFZI sûrede İLK KEZ (2 token, ikisi de 'sebîli'llâh'). 'yâ dâvûdu' korpusta 1 ayet. 'halîfe' (tekil, metin sayımı) 2 ayet: 2:30 (okundu, 'innî câilun fi'l-ardı halîfe') ve 38:26 — orada 1S (câil), burada 1P (ce'alnâke) (okumada görüldü, KAPATILAMAZ). 38:22 davacıların isteği 'fahkum beynenâ bi'l-haqqi ve lâ tuştıt' → 38:26 emir 'fahkum beyne'n-nâsi bi'l-haqqi ve lâ tettebi'' — aynı kalıp, istek emir olarak geri geliyor (okumada görüldü). 'yevme'l-hisâb': 38:16 inkârcıların alayı → 38:26 'nesû' (unuttular). xref 2:213, 4:58, 4:105, 4:167, 16:94 (okundu), 58:16 (henüz okunmadı). حكم [3/3] kapanıyor; ضلل ×2, سبل ×2; خلف [1/1]; هوي [1/1]; نسي [1/1]; أنس [1/1]; شدد [2/2]; عذب [2/4]. Fâsıla ب. 30 kelime; ★ kaynak n (uzunluk z=1,87).\n◈K — K1 yer ('fi'l-ard', halifelik alanı); K2 zaman: 'yevme'l-hisâb' — unutulan gün; K3 —; K4 —.\n◈B — B1 insanlar ('en-nâs', topluluk, hüküm alanı); B2 —; B3 —; B4 —.\n◈D — D1 nidâ + tekit + emir + yasak + fâ ile sonuç; ardından tekitli genel hüküm; D3 ضلل/سبل ikilemeleri; D4 1P 3 · 2MS 4 · 3MP 5 · 3MS 1.\n◈A — A1 Dâvûd (adlı, muhatap), 'biz', Allah (lafız, 'yolu'), insanlar, sapanlar; A3 görevlendirme + uyarı.",
 27: "◇ 've mâ halaqne's-semâe ve'l-arda ve mâ beynehumâ bâtılâ; zâlike zannu'llezîne keferû; fe-veylun li'llezîne keferû mine'n-nâr' — 1P: göğü, yeri ve arasını boş yere yaratmadık. 've mâ halaqne's-semâe ve'l-arda ve mâ beynehumâ' (tekil semâ, metin sayımı) 2 ayet: 21:16 (okundu, 'lâ'ibîn') ve 38:27 ('bâtılâ'). nakarat3 sûre içi 3 ayet, eşlerden 38:10 okundu ('mulku's-semâvât', çoğul — süzgeç lemma ile), biri henüz okunmadı (GEÇER). 'veylun li'llezîne keferû' 3 ayet: 19:37 (okundu), 38:27, 51:60 (henüz okunmadı). ظنن [2/2]: 38:24 'zanne dâvûdu' (doğru anlayış) → 38:27 'zannu'llezîne keferû' (yanlış zan) (okumada görüldü). بطل [1/1]; خلق [2/6]: 38:7 'ihtilâq' → 38:27 'halaqnâ'. كفر ×2 [3,4/5]; نور [1/5] ('en-nâr'). Fâsıla ر (ب dizisinden sonra). 16 kelime, yıldız yok. 🜁 L1 — gök, yer ve arası adlanıyor; nitelik ekleniyor: yaratılmışlık ve amaç ('bâtıl değil'); nedensellik/ölçü yok; olgu evet, çıpa hayır; tarayıcı vermedi.\n◈K — K1 gök (tekil semâ'), yer, ikisinin arası; K2 —; K3 ölçek: en büyük birimler, yaratma fiilinin nesnesi; K4 —.\n◈B — B1 —; B2 —; B3 —; B4 tetik خلق ('halaqnâ'): yaratma fiili, nesnesi gök/yer — canlı/beden unsuru yok.\n◈D — D1 olumsuz PERF (1P) + işaret cümlesi + 'veyl' bedduası; D3 كفر ikilemesi; D4 1P 2 · 3D 1 · 3MP 4.\n◈A — A1 'biz', inkârcılar; A3 zannın reddi + tehdit.",
 28: "◇ 'em nec'alu'llezîne âmenû ve amilu's-sâlihâti ke'l-mufsidîne fi'l-ard; em nec'alu'l-muttaqîne ke'l-fuccâr' — iki 'em' sorusu (1P, IMPF), iki karşıtlık çifti: iman edip iyi iş yapanlar / bozguncular; sakınanlar / günahkârlar. nakarat3 'ellezîne âmenû ve amilu's-sâlihât' eşi 38:24 (GEÇER): orada istisna (az olanlar), burada karşılaştırma. xref 18:94 (okundu) 'mufsidûne fi'l-ard'; 45:21 (henüz okunmadı). جعل ×2 [3,4/4] kapanıyor; أمن [2/2], عمل [2/2], صلح [2/2] kapanıyor; فسد [1/1]; وقي [1/2]; فجر [1/1]: 'fuccâr' (günahkârlar) — gloss 'fışkırtma; fecir' bu anlamı taşımıyor (987/1015 ailesi, kayıt). Fâsıla ر. 13 kelime, yıldız yok.\n◈K — K1 yer ('fi'l-ard', bozgunculuk alanı); K2 —; K3 —; K4 —.\n◈B — —\n◈D — D1 iki 'em' (munkatı'a) + IMPF; D3 جعل ikilemesi, iki karşıtlık çifti; D4 1P 2 · 3MP 4.\n◈A — A1 'biz', dört sınıf (müminler, bozguncular, muttakîler, fâcirler); A3 eşitlemenin reddi (soru biçiminde).",
 29: "◇ 'kitâbun enzelnâhu ileyke mubârakun li-yeddebberû âyâtihî ve li-yetezekkera ulu'l-elbâb' — bereketli kitap, iki amaç (lâm-ı ta'lîl): tedebbür ve tezekkür. 'kitâbun enzelnâhu' (metin sayımı) 4 ayet: 6:92, 6:155, 14:1 (okundu), 38:29; xref 6:92, 6:155. نزل [2/2]: 38:8 'e-unzile aleyhi'z-zikr' (inkârcıların sorusu, edilgen) → 38:29 'enzelnâhu ileyke' (1P, etken) (okumada görüldü). ذكر [5/13]: 38:1 'zi'z-zikr' → 38:8 → 38:17 → 38:29 'li-yetezekkera'. دبر [1/1]: 'yeddebberû' (tedebbür) — gloss 'arka' bu anlamı taşımıyor (987/1015 ailesi, kayıt). كتب [1/1]; برك [1/1]; أيي [1/1]; لبب [1/2]. Fâsıla ب. 9 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 isim cümlesi (haber + sıfat cümlesi) + iki amaç cümlesi; D4 1P 2 · 2MS 1 · 3MP 2 · 3MS 3.\n◈A — A1 'biz', muhatap (2MS), kitap, akıl sahipleri; A3 indirme ve amaç; A4 Dâvûd anlatısı arasında kitap üzerine ara ayet.",
 30: "◇ 've vehebnâ li-dâvûde suleymân; ni'me'l-abd; innehû evvâb' — 1P: Dâvûd'a Süleymân'ı bağışladık. Süleymân sûrede ilk kez (aktör adlı); lemma korpusta 16 ayet, sûre 38'de 2 (30, 34 henüz okunmadı). nakarat3 'ni'me'l-abdu innehû evvâb' eşi 38:44 — henüz okunmadı (GEÇER). 'innehû evvâb' (metin sayımı) 3 ayet: 38:17 Dâvûd, 38:30 Süleymân, 38:44 (henüz okunmadı). وهب [2/5]: 38:9 'el-vehhâb' (Rab'bin sıfatı) → 38:30 'vehebnâ' (okumada görüldü). عبد [2/6]: 38:17 'abdenâ dâvûd' → 38:30 'ni'me'l-abd'. أوب [4/8]. نعم [1/2] ('ni'me', övgü fiili). Fâsıla ب. 7 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 PERF (1P) + övgü cümlesi (ni'me) + tekitli isim cümlesi; D4 1P 2 · 3MS 2.\n◈A — A1 'biz', Dâvûd, Süleymân (adlı); A2 sahne geçişi: Dâvûd'dan Süleymân'a; A3 bağış + övgü.",
}
MEAL.update(MEAL3); M.update(M3)

MEAL4 = {
 31: 'Hani akşamüstü ona üç ayağı üstünde duran asil atlar sunulmuştu.',
 32: 'Dedi ki: "Doğrusu ben hayır sevgisini Rabbimi anmaktan (ötürü) sevdim." Derken perdenin ardına gizlendi.',
 33: '"Onları bana geri getirin." Ve bacaklarını, boyunlarını sıvazlamaya koyuldu.',
 34: "Andolsun, Süleymân'ı sınadık ve tahtının üzerine bir ceset bıraktık; sonra (O'na) yöneldi.",
 35: 'Dedi ki: "Rabbim, beni bağışla ve bana benden sonra hiç kimseye yakışmayacak bir mülk bağışla; şüphesiz sen çok bağışlayansın (Vehhâb)."',
 36: 'Bunun üzerine rüzgârı ona boyun eğdirdik; dilediği yere onun emriyle yumuşacık akardı.',
 37: 'Şeytanları da — her yapı ustasını ve dalgıcı —',
 38: 've zincirlerde birbirine bağlanmış diğerlerini de.',
 39: '"Bu bizim bağışımızdır; artık hesapsız olarak ister ver, ister tut."',
 40: 'Şüphesiz onun katımızda bir yakınlığı ve güzel bir dönüş yeri vardır.',
}
M4 = {
 31: "◇ 'iz urıda aleyhi bi'l-aşiyyi's-sâfinâtu'l-ciyâd' — EDİLGEN 1/1 'urıda' (sunuldu), sunan adlanmıyor; pas z=5,38 → ★★★ kaynak pas; HAPAKS صفن ('sâfinât') z=3,28 de eşik üstü. 'bi'l-aşiyy' (metin sayımı) 4 ayet: 3:41 (okundu), 38:18, 38:31, 40:55 (henüz okunmadı); عشو [2/2]: 38:18 dağların tesbih vakti → 38:31 atların sunulduğu vakit (okumada görüldü). جود [1/1] 'ciyâd' — kök korpusta 2 ayet: 11:44 (okundu, 'el-cûdiyy') ve 38:31. عرض [1/2]. Zamir 'aleyhi' önceki ayetteki Süleymân'a dönüyor (38:30). Fâsıla د — KAFİYE KIRILMASI. 6 kelime. 🜁 L1 — atlar adlanıyor + nitelik (sâfinât: üç ayak üstünde duran; ciyâd: asil/hızlı) ve vakit; süreç/ölçü yok; olgu evet, çıpa hayır.\n◈K — —\n◈B — —\n◈D — D1 'iz' + edilgen PERF; D3 iki sıfat ard arda (sâfinât, ciyâd), özne fiilden sonra; D4 3MS 2.\n◈A — A1 Süleymân (zamir), atlar (sunulan); A2 sahne: akşamüstü; A3 sunuş.",
 32: "◇ 'fe-qâle innî ahbebtu hubbe'l-hayri an zikri rabbî hattâ tevârat bi'l-hicâb' — Süleymân 1S 4: 'ahbebtu hubbe' — حبب mm2 (fiil + mastar, aynı kök ardışık); ★ kaynak rab (z=1,62). 'an zikri rabbî' iki okumaya açık: 'Rabbimi anmaktan ötürü' / 'Rabbimi anmayı bırakıp'; 'tevârat' (3FS) öznesi adlanmıyor — atlar ya da güneş okunabilir (KAPATILAMAZ). 'hubbe'l-hayr' (metin sayımı) 2 ayet: 38:32, 100:8 (henüz okunmadı). Rab sûrede dördüncü kez, ilk kez 1S iyelikle ('rabbî'): 38:9 rabbike → 38:16 rabbenâ → 38:24 rabbehû → 38:32 rabbî. ذكر [6/13]. حجب [1/1]; وري [1/1]; خير [1/4]. Fâsıla ب. 11 kelime.\n◈K — —\n◈B — —\n◈D — D1 tekitli isim cümlesi (inne + PERF) + 'hattâ' ile zaman sınırı; D3 حبب mm2 (fiil + mutlak meful); D4 1S 4 · 3FS 1 · 3MS 1.\n◈A — A1 Süleymân (konuşan), Rab ('rabbî'), adsız 3FS özne; A3 kendi sözüyle durum tespiti.",
 33: "◇ 'ruddûhâ aleyye; fe-tafiqa meshan bi's-sûqi ve'l-a'nâq' — emir (IMPV, 2MP — muhatap adlanmıyor) + 'tafiqa' (koyuldu): bacakları ve boyunları sıvazlama. طفق [1/1] — kök korpusta 3 ayet: 7:22, 20:121 (okundu — Âdem ile eşi 'tafiqâ yahsıfân') ve 38:33. 'ruddûhâ' 3 ayet: 4:86, 21:99 (okundu), 38:33. سوق [1/1]: 'sûq' (bacaklar, sâq'ın çoğulu) — gloss 'sürme; çarşı (sûk)' bu anlamı taşımıyor (987/1015 ailesi, kayıt). عنق [1/1] — ◈B tetik. مسح [1/1]; ردد [1/1]. Fâsıla ق — KAFİYE KIRILMASI → ★ (kafiye kırığı). 6 kelime. 🜁 L1 — atların organları (bacak, boyun) + eylem (sıvazlama); süreç/ölçü yok; olgu evet, çıpa hayır.\n◈K — —\n◈B — B1 atlar (zamir 'hâ'); B2 organlar: bacaklar (sûq), boyunlar (a'nâq) — at bedeni; B3 —; B4 dokunma ('mesh') — insan eli canlıya.\n◈D — D1 emir + fâ + 'tafiqa' (şurû fiili) + mastar; D4 1S 1 · 2MP 2 · 3FS 1 · 3MS 1.\n◈A — A1 Süleymân (konuşan/eden), adsız muhataplar (2MP), atlar; A3 geri getirtme ve dokunma.",
 34: "◇ 've leqad fetennâ suleymâne ve elqaynâ alâ kursiyyihî ceseden thumme enâb' — 1P 4: Süleymân'ı sınadık; tahtına bir ceset bıraktık; sonra yöneldi. فتن [2/2] ve نوب [2/2] kapanıyor: 38:24 Dâvûd 'ennemâ fetennâhu … ve enâb' → 38:34 Süleymân 'fetennâ … thumme enâb' — baba ve oğulda aynı iki kök aynı sırayla (sınama → inâbe) (okumada görüldü, KAPATILAMAZ). Cesedin ne olduğu metinde adlanmıyor. كرس [1/1] — kök korpusta 2 ayet: 2:255 (okundu, 'kursiyyuhu') ve 38:34. جسد [1/1] — kök korpusta 4 ayet: 7:148, 20:88 (okundu, ikisi buzağı 'iclen ceseden'), 21:8 (okundu), 38:34; ◈B tetik listesi جسد'yi içermiyor → ◈B '—' (kayıt; S1). لقي [1/1]. Fâsıla ب. 9 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 qasem lâmı + qad + iki PERF (1P) + 'thumme' ile üçüncü fiil (3MS); D4 1P 4 · 3MS 2.\n◈A — A1 'biz', Süleymân (adlı), ceset (adsız); A3 sınama → inâbe.",
 35: "◇ 'qâle rabbi'ğfir lî ve heb lî mulken lâ yenbeğî li-ehadin min ba'dî; inneke ente'l-vehhâb' — Süleymân'ın duası: iki emir (IMPV, dua) + tekit. Rab beşinci kez ('rabbi', 1S nidâ). esmâ: ehad 'degil' (olumsuz bağlamda 'kimse'); vehhâb 'ilahi' (Rab'be hitap, 2MS haber) — §4.3 mühür (ÇİFT) bilançoda geçerli sayılıyor (son konumdaki vehhâb ilahi). 'inneke ente'l-vehhâb' (metin sayımı) 2 ayet: 3:8 (okundu, 'rabbenâ … veheb lenâ min ledunke rahmeten inneke ente'l-vehhâb') ve 38:35 — iki duada 'heb' emri + aynı kapanış (okumada görüldü). 'heb lî' 7 ayet: 3:38, 14:39, 19:5, 26:21, 26:83, 37:100 (okundu), 38:35. وهب ×2 [3,4/5]: 38:9 'el-vehhâb' → 38:30 'vehebnâ' → 38:35 'heb lî … el-vehhâb'. غفر [3/4]: 38:24 'fe'steğfera' (Dâvûd) → 38:35 'iğfir lî' (Süleymân). ملك [3/5]: 38:10 göklerin mülkü (soru) → 38:20 Dâvûd'un mülkü → 38:35 istenen mülk. بغي [3/3] kapanıyor: 38:22, 38:24 'beğâ/yebğî' (haksızlık) → 38:35 'yenbeğî' (yakışmak, VII. bab) — aynı kök iki anlam; gloss ikisini taşıyor. أحد [1/1]; بعد [1/2]. Sayı işareti ehad. Fâsıla ب. 15 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 nidâ + iki emir (dua) + olumsuz sıfat cümlesi + tekitli isim cümlesi (inne + zamir + haber); D3 وهب ikilemesi; D4 1S 4 · 2MS 4 · 3MS 2.\n◈A — A1 Süleymân (konuşan), Rab (hitap, 'el-vehhâb'); A3 istiğfar + mülk isteği.",
 36: "◇ 'fe-sahharnâ lehu'r-rîha tecrî bi-emrihî ruhâen haysu esâb' — 1P: rüzgârı ona boyun eğdirdik; emriyle yumuşak, dilediği yere akar. HAPAKS رخو ('ruhâ'') z=3,28 → ★★★. 'tecrî bi-emrihî' (metin sayımı) 2 ayet: 21:81 (okundu, 've li-suleymâne'r-rîha âsıfeten tecrî bi-emrihî') ve 38:36 — orada 'âsıfa' (sert esen), burada 'ruhâ'' (yumuşak) (okumada görüldü, KAPATILAMAZ); 34:12 (okundu) 've li-suleymâne'r-rîh'. سخر [2/3]: 38:18 dağlar Dâvûd'la → 38:36 rüzgâr Süleymân'a (okumada görüldü). روح [1/2] (rîh); جري [1/1]; أمر [1/1]; حيث [1/1]; صوب [1/1]. Fâsıla ب. 8 kelime. 🜁 L1 — rüzgâr adlanıyor + nitelik (yumuşak) ve yön ('haysu esâb'), emre bağlılık; mekanizma/ölçü yok; olgu evet, çıpa hayır.\n◈K — K1 rüzgâr (rîh); K2 —; K3 —; K4 hareket: 'tecrî' (akar, IMPF) — yön dilediği yer, nitelik yumuşak; hareketi emreden Süleymân, teshir eden 1P.\n◈B — —\n◈D — D1 fâ + PERF (1P) + hâl cümlesi (IMPF) + hâl + mekân zarfı; D4 1P 2 · 3FS 1 · 3MS 3.\n◈A — A1 'biz', Süleymân (zamir), rüzgâr; A3 dua → karşılık (38:35 → 38:36, fâ ile).",
 37: "◇ 've'ş-şeyâtîne kulle bennâin ve ğavvâs' — fiil 38:36'dan ('sahharnâ'): şeytanları da, her yapıcı ve dalgıcı. Aktör adlı şeytan (gayb, meful). غوص [1/1] — kök korpusta 2 ayet: 21:82 (okundu, 've mine'ş-şeyâtîni men yeğûsûne lehû') ve 38:37 — ikisinde de Süleymân'a dalan şeytanlar (okumada görüldü). بني [1/1]; شطن [1/2]; كلل [3/5]. Fâsıla ص. 4 kelime — blokun en kısası (38:38 ile eşit), yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 atıf (fiil önceki ayette) + bedel ('kulle bennâin'); D3 iki mübalağa kalıbı (fa''âl: bennâ', ğavvâs); D4 şahıs işareti yok.\n◈A — A1 şeytanlar (adlı, gayb); A3 hizmet sınıfları: yapıcı, dalgıç.",
 38: "◇ 've âharîne muqarranîne fi'l-asfâd' — fiil yine 38:36'dan: zincirlerde birbirine bağlı diğerleri. 'muqarranîne fi'l-asfâd' (metin sayımı) 2 ayet: 14:49 (okundu, kıyamet günü mücrimler) ve 38:38 (Süleymân'a bağlı şeytanlar) — aynı ifade iki ayrı sahnede (okumada görüldü). صفد [1/1] — kök korpusta yalnız bu iki ayet. قرن [2/2] kapanıyor: 38:3 'qarn' (nesil) → 38:38 'muqarranîn' (bağlanmış) — aynı kök iki anlam; gloss ikisini taşıyor. أخر [2/3]. Fâsıla د. 4 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 atıf + hâl (ism-i meful) + câr-mecrûr; D4 şahıs işareti yok.\n◈A — A1 'diğerleri' (şeytanlardan, adsız); A3 bağlılık.",
 39: "◇ 'hâzâ atâunâ fe'mnun ev emsik bi-ğayri hisâb' — DIKKAT (işaret) + iki emir (IMPV 2, 2MS): bu bizim bağışımız; ver ya da tut, hesapsız. 'bi-ğayri hisâb' (metin sayımı) 7 ayet: 2:212, 3:27, 3:37, 24:38 (okundu), 38:39, 39:10, 40:40 (henüz okunmadı) — 3:37 aynı zamanda 'el-mihrâb' ayeti (38:21 bağı). حسب [3/4]: 38:16 'yevmi'l-hisâb' (alay) → 38:26 (unutulan gün) → 38:39 'bi-ğayri hisâb' (hesapsız bağış) (okumada görüldü). عطو [1/1]; منن [1/1]; مسك [1/1]; غير [1/1]. Fâsıla ب. 7 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 işaret cümlesi + fâ ile iki emir ('ev' seçenek); D2 işaret 'hâzâ'; D4 1P 1 · 2MS 2.\n◈A — A1 'biz' (konuşan), Süleymân (muhatap 2MS); A3 bağış ve serbest tasarruf.",
 40: "◇ 've inne lehû indenâ le-zulfâ ve husne meâb' — 38:25'in son altı kelimesi aynen (nakarat3 tür TAM, GEÇER): 38:25 Dâvûd için, 38:40 Süleymân için; iki anlatı aynı cümleyle kapanıyor (okumada görüldü). 'zulfâ ve husne' 2 ayet (ikisi de okundu). زلف [2/2] kapanıyor; عند [3/5]: 38:9 'indehum' → 38:25 'indenâ' → 38:40 'indenâ'; أوب [5/8]: evvâb (17, 19, 30) → meâb (25, 40). حسن [2/3]. Fâsıla ب. 6 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 tekitli isim cümlesi (inne + lâm); D4 1P 1 · 3MS 1.\n◈A — A1 'biz', Süleymân (zamir); A4 Süleymân anlatısının kapanışı.",
}
MEAL.update(MEAL4); M.update(M4)

MEAL5 = {
 41: 'Kulumuz Eyyûb\'u da an. Hani Rabbine: "Şeytan bana yorgunluk ve azap dokundurdu" diye seslenmişti.',
 42: '"Ayağını (yere) vur; işte yıkanacak serin bir su ve içecek."',
 43: 'Ona ailesini ve onlarla birlikte bir mislini, bizden bir rahmet ve akıl sahiplerine bir öğüt olarak bağışladık.',
 44: '"Eline bir demet al, onunla vur ve yeminini bozma." Biz onu sabırlı bulduk. Ne güzel kuldu! O çok dönen (evvâb) biriydi.',
 45: "Kullarımız İbrâhîm'i, İshâk'ı ve Ya'kûb'u da an; güç (eller) ve basiret (gözler) sahibiydiler.",
 46: 'Biz onları halis bir şeyle, yurdu anmakla arıttık.',
 47: 'Şüphesiz onlar katımızda seçilmişlerden, en hayırlılardandır.',
 48: "İsmâîl'i, Elyesa'ı ve Zü'l-Kifl'i de an; hepsi en hayırlılardandır.",
 49: 'Bu bir zikirdir. Şüphesiz sakınanlar için güzel bir dönüş yeri vardır:',
 50: 'kapıları onlara açılmış Adn cennetleri.',
}
M5 = {
 41: "◇ 've'zkur abdenâ eyyûbe iz nâdâ rabbehû ennî messeniye'ş-şeytânu bi-nusbin ve azâb' — anma emri (IMPV, 2MS) + Eyyûb'un nidâsı. 've'zkur abdenâ' (metin sayımı) korpusta 3 ayet, üçü bu sûrede: 38:17 Dâvûd, 38:41 Eyyûb, 38:45 'ibâdenâ' (okumada görüldü). xref 21:83 (okundu) 'iz nâdâ rabbehû ennî messeniye'd-durru' — orada 'durr' (zarar), burada 'şeytân … nusb ve azâb' (okumada görüldü, KAPATILAMAZ); 'nâdâ rabbehû' 4 ayet: 19:3, 21:83, 21:89 (okundu), 38:41. ندي [2/2]: 38:3 helâk edilenlerin cevapsız feryadı → 38:41 Eyyûb'un nidâsı. Rab altıncı kez ('rabbehû'); ★ kaynak rab (z=1,62). Aktör adlı Eyyûb ve şeytan (fail). عذب [3/4]: 38:8 'azâbi' (1S) → 38:26 → 38:41. نصب [1/1]; مسس [1/1]; شطن [2/2]; عبد [3/6]; ذكر [7/13]. Fâsıla ب. 11 kelime.\n◈K — —\n◈B — —\n◈D — D1 emir + 'iz' + PERF + 'enne' ile alıntı (1S); D4 1P 1 · 1S 2 · 2MS 1 · 3MS 3.\n◈A — A1 muhatap (2MS), Eyyûb (adlı, 'kulumuz'), Rab, şeytan (adlı, fail); A2 sahne geçişi: Süleymân'dan Eyyûb'a; A3 nidâ.",
 42: "◇ 'urkud bi-riclik; hâzâ muğtesel bâridun ve şarâb' — emir (IMPV, 2MS) + işaret (DIKKAT): ayağını vur; işte serin yıkanma suyu ve içecek. Konuşan adlanmıyor (önceki ayetteki nidâya cevap). 'urkud' ve 'muğtesel' korpusta 1'er ayet. ركض [1/1] — kök korpusta 3 ayet: 21:12, 21:13 (okundu — azap gelince kaçışma) ve 38:42 (ayakla vurma). رجل [1/2]: 'ricl' (ayak) — gloss 'adam; yaya' bu anlamı taşımıyor (987/1015 ailesi); ◈B tetik listesinde رجل yok → ◈B '—' (kayıt; S1). غسل [1/1]; برد [1/1] — kök korpusta 5 ayet, 21:69 (okundu, 'kûnî berden') ile ikisinde serinlik bir kurtuluş (okumada görüldü, KAPATILAMAZ). شرب [1/2]. Fâsıla ب. 6 kelime, yıldız yok. 🜁 L1 — su adlanıyor + nitelik (serin) ve işlev (yıkanma, içme); ayakla vurma ile ortaya çıkış — süreç/ölçü yok; olgu evet, çıpa hayır.\n◈K — —\n◈B — —\n◈D — D1 emir + işaret cümlesi; D2 işaret 'hâzâ'; D4 2MS 2.\n◈A — A1 Eyyûb (muhatap 2MS), konuşan (adsız); A3 cevap: emir ve gösterme.",
 43: "◇ 've vehebnâ lehû ehlehû ve mislehum meahum rahmeten minnâ ve zikrâ li-uli'l-elbâb' — 1P 3: ailesini ve bir mislini bağışladık; rahmet ve öğüt. xref 21:84 (okundu) 've âteynâhu ehlehû ve mislehum meahum rahmeten min ındinâ ve zikrâ li'l-âbidîn' — 'ehlehû ve mislehum meahum' metin sayımı 2 ayet; orada 'âteynâ' / 'âbidîn', burada 'vehebnâ' / 'uli'l-elbâb' (okumada görüldü). وهب [5/5] kapanıyor: 38:9 el-vehhâb → 38:30 vehebnâ (Süleymân) → 38:35 heb lî / el-vehhâb → 38:43 vehebnâ (Eyyûb'a aile). لبب [2/2]: 38:29 → 38:43 'uli'l-elbâb'. رحم [2/2]: 38:9 'hazâinu rahmeti rabbike' → 38:43 'rahmeten minnâ'. İltifât alanı 1 (38:42 2MS emir → 38:43 1P anlatı). مثل [1/1]; أهل [1/2]; ذكر [8/13]. Fâsıla ب. 10 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 PERF (1P) + iki meful + iki meful-i leh (rahmeten, zikrâ); D4 1P 3 · 3MP 2 · 3MS 2.\n◈A — A1 'biz', Eyyûb (zamir), aile; A3 bağış.",
 44: "◇ 've huz bi-yedike dığsen fe'drib bihî ve lâ tahnes; innâ vecednâhu sâbirâ; ni'me'l-abd; innehû evvâb' — emir + yasak (NEHY) + 1P hüküm. ضغث [1/1] — kök korpusta 3 ayet: 12:44, 21:5 (okundu, ikisi 'adğâsu ahlâm' — karışık düşler) ve 38:44 (ot demeti). حنث [1/1] — kök korpusta 2 ayet: 38:44, 56:46 (henüz okunmadı). nakarat3 'ni'me'l-abdu innehû evvâb' eşi 38:30 (GEÇER) — iki ucu artık okundu: Süleymân ve Eyyûb aynı övgüyle; 'innehû evvâb' 3 ayet: 38:17 Dâvûd, 38:30 Süleymân, 38:44 Eyyûb (okumada görüldü). صبر [3/3] kapanıyor: 38:6 'isbirû alâ âlihetikum' (inkârcılar) → 38:17 'isbir' (muhatap) → 38:44 'sâbiran' (Eyyûb). أوب [6/8]; نعم [2/2]; عبد [4/6]; يدي [1/3]; وجد [1/1]; ضرب [1/1]; أخذ [1/2]. Fâsıla ب. 14 kelime, yıldız yok.\n◈K — —\n◈B — B1 —; B2 el (yed, 2MS iyelik — Eyyûb'un eli); B3 —; B4 tutma ve vurma eylemi.\n◈D — D1 iki emir + yasak + tekitli PERF (1P) + övgü cümlesi + tekitli isim cümlesi; D2 NEHY; D4 1P 3 · 2MS 4 · 3MS 4.\n◈A — A1 Eyyûb (muhatap, sonra 3MS), 'biz'; A3 yemin meselesi → sabır övgüsü; A4 Eyyûb anlatısının kapanışı.",
 45: "◇ 've'zkur ibâdenâ ibrâhîme ve ishâqa ve ya'qûbe uli'l-eydî ve'l-ebsâr' — anma emri, üç adlı kul. 'uli'l-eydî ve'l-ebsâr' korpusta 1 ayet. ذو (MP, 'ulî') sûrede: 38:29 'ulu'l-elbâb', 38:43 'uli'l-elbâb', 38:45 'uli'l-eydî' (okumada görüldü). يدي [2/3]: 38:44 'bi-yedike' (Eyyûb'un eli, somut) → 38:45 'el-eydî' (güç, mecaz) — tetik organ kelimesiyle düşüyor, anlam güç. بصر [1/2]; عبد [5/6]: 'abdenâ' (17, 41) → 'ibâdenâ' (45). ذكر [9/13]. Fâsıla ر (ب dizisinden sonra). 8 kelime, yıldız yok.\n◈K — —\n◈B — B1 —; B2 eller (eydî) ve gözler (ebsâr) — organ adları, 'sahibi' tamlamasında nitelik olarak (güç, basiret); B3 görme (بصر) — nitelik; B4 —.\n◈D — D1 emir + üç meful + sıfat tamlaması ('ulî'); D4 1P 1 · 2MS 1.\n◈A — A1 İbrâhîm, İshâk, Ya'kûb (adlı), 'biz', muhatap; A2 sahne geçişi: tek tek anılanlardan topluca anılanlara.",
 46: "◇ 'innâ ahlasnâhum bi-hâlisatin zikra'd-dâr' — 1P: onları halis bir şeyle, yurdu anmakla arıttık. خلص ×2 [1,2/3] (fiil + sıfat). 'zikra'd-dâr' korpusta 1 ayet; 'ed-dâr' hangi yurt olduğu adlanmıyor. ذكر [10/13]: sûrede 'zikr/zikrâ' ve 'vezkur' iç içe — 38:1 zikir sahibi Kur'ân → 38:46 yurdu anma. دور [1/1]. Fâsıla ر. 5 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 tekitli PERF (1P) + câr-mecrûr + bedel; D3 خلص ikilemesi; D4 1P 3 · 3MP 1.\n◈A — A1 'biz', üç kul (zamir); A3 arıtma.",
 47: "◇ 've innehum indenâ le-mine'l-mustafeyne'l-ahyâr' — tekitli isim cümlesi: katımızda seçilmişlerden, en hayırlılardan. 'el-mustafeyn' korpusta 1 ayet; 'el-ahyâr' 2 ayet: 38:47, 38:48 (ikisi bu blokta). صفو [1/1]; خير [2/4]: 38:32 'hubbe'l-hayr' → 38:47 'ahyâr'. عند [4/5]: 38:25, 38:40 'indenâ' → 38:47 'indenâ'. Fâsıla ر. 5 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 inne + lâm + iki sıfat (ism-i meful, ism-i tafdil çoğulu); D4 1P 1 · 3MP 1.\n◈A — A1 'biz', üç kul (zamir); A3 seçilmişlik.",
 48: "◇ 've'zkur ismâîle ve'l-yesea ve ze'l-kifl; ve kullun mine'l-ahyâr' — anma emri, üç ad; hepsi en hayırlılardan. Aktör alanı İsmâîl ve Elyesa'ı adlı sayıyor; 'ze'l-kifl' ذو + كفل olarak ayrışmış — aktör alanında yok, kök alanında كفل 'üstlenme' sayılıyor (araç açığı, 924). كفل [2/2]: 38:23 'ekfilnîhâ' (fiil) → 38:48 'ze'l-kifl' (ad) — araç ikisini aynı iplikte sayıyor. 'ze'l-kifl' (metin sayımı) 2 ayet: 21:85 (okundu) ve 38:48; 've'l-yesea' 2 ayet: 6:86 (okundu), 38:48. 21:83-85'te (okundu) sıra Eyyûb → İsmâîl, İdrîs, Zü'l-Kifl ('kullun mine's-sâbirîn'); 38:41-48'de Eyyûb → İbrâhîm, İshâk, Ya'kûb → İsmâîl, Elyesa, Zü'l-Kifl ('kullun mine'l-ahyâr') (okumada görüldü, KAPATILAMAZ). ذو (MS) sûrede dördüncü: 38:1, 38:12, 38:17, 38:48. İltifât alanı 1 (38:47 1P → 38:48 2MS emir). خير [3/4]; كلل [4/5]; ذكر [11/13]. Fâsıla ر. 8 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 emir + üç meful + isim cümlesi; D3 'zû' tamlaması; D4 2MS 1.\n◈A — A1 İsmâîl, Elyesa (adlı), Zü'l-Kifl (alan dışı); A4 anılanlar dizisinin kapanışı.",
 49: "◇ 'hâzâ zikr; ve inne li'l-muttaqîne le-husne meâb' — işaret (DIKKAT) + tekit: bu bir zikir; sakınanlara güzel dönüş yeri. 'husne meâb' (metin sayımı) 4 ayet: 13:29 (okundu), 38:25, 38:40, 38:49 — sûrede üçüncü: 38:25 'lehû' (Dâvûd), 38:40 'lehû' (Süleymân), 38:49 'li'l-muttaqîn' (genel sınıf) (okumada görüldü). وقي [2/2]: 38:28 'el-muttaqîn' (karşılaştırma) → 38:49 (karşılık). حسن [3/3] kapanıyor; أوب [7/8]; ذكر [12/13]: 38:1 'zi'z-zikr' → 38:49 'hâzâ zikr'. Fâsıla ب. 6 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 işaret cümlesi + tekitli isim cümlesi (inne + lâm, haber önde); D2 işaret 'hâzâ'; D4 şahıs işareti yok.\n◈A — A1 sakınanlar (sınıf); A3 anılanlardan genel hükme geçiş.",
 50: "◇ 'cennâti adnin mufettahaten lehumu'l-ebvâb' — 38:49 'meâb'ın bedeli: kapıları açılmış Adn cennetleri. Aktör alanı 'Adn'i adlı yer sayıyor. 'cennâti adn' (metin sayımı) korpusta 11 ayet. 'mufettaha' korpusta 1 ayet. İltifât alanı 1 (38:49 şahıssız → 38:50 3MP). جنن [1/1]; فتح [1/1]; بوب [1/1]. Fâsıla ب. 5 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 bedel (isim tamlaması) + hâl (ism-i meful) + fâil ('el-ebvâb'); D4 3MP 1.\n◈A — A1 sakınanlar (zamir), Adn (adlı yer); A2 sahne: cennet.",
}
MEAL.update(MEAL5); M.update(M5)

MEAL6 = {
 51: 'Orada yaslanırlar; orada bol meyve ve içecek isterler.',
 52: 'Yanlarında bakışlarını sınırlayan yaşıtlar vardır.',
 53: 'İşte hesap günü için size vaat edilen budur.',
 54: 'Şüphesiz bu bizim rızkımızdır; onun tükenmesi yoktur.',
 55: 'Bu böyle. Azgınlar için ise kötü bir dönüş yeri vardır:',
 56: 'cehennem; oraya girerler. Ne kötü bir döşektir!',
 57: 'İşte bu; tatsınlar onu: kaynar su ve irin.',
 58: 'Ve onun türünden başka çeşitler.',
 59: '"Bu, sizinle birlikte dalıp giren bir kalabalık." — "Onlara merhaba yok! Onlar ateşe girecekler."',
 60: 'Dediler ki: "Hayır, asıl size merhaba yok! Bunu bize siz hazırladınız. Ne kötü bir karar yeri!"',
}
M6 = {
 51: "◇ 'muttekiîne fîhâ yed'ûne fîhâ bi-fâkihetin kesîratin ve şarâb' — Adn cennetlerinde (38:50) sakınanların hâli: yaslanmış, bol meyve ve içecek isteyen. 'fâkihetin kesîratin' (metin sayımı) 3 ayet: 38:51, 43:73, 56:32 (henüz okunmadı); 'yed'ûne fîhâ' 2 ayet: 38:51, 44:55 (henüz okunmadı). شرب [2/2]: 38:42 Eyyûb'a gösterilen 'şarâb' → 38:51 cennette 'şarâb' (okumada görüldü). كثر [2/2]: 38:24 'kesîran mine'l-hulatâ' → 38:51 'kesîra'; sayı işareti kesîra. وكأ [1/1]; دعو [1/1]; فكه [1/1]. Fâsıla ب. 7 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 hâl (ism-i fâil) + IMPF; D3 'fîhâ' ikilemesi; D4 3FS 2 · 3MP 2.\n◈A — A1 sakınanlar (zamir); A2 sahne: cennet; A3 istek.",
 52: "◇ 've indehum qâsırâtu't-tarfi etrâb' — yanlarında bakışlarını sınırlayan yaşıtlar. xref 37:48 (okundu) 've indehum qâsırâtu't-tarfi în' — aynı dört kelimelik açılış, sonda 'în' yerine 'etrâb' (okumada görüldü); 'qâsırâtu't-tarf' (metin sayımı) 3 ayet: 37:48, 38:52, 55:56 (henüz okunmadı); 'etrâb' 3 ayet: 38:52, 56:37, 78:33 (henüz okunmadı). ترب [1/1]: 'etrâb' (yaşıtlar) — gloss 'toprak' bu anlamı taşımıyor (987/1015 ailesi, kayıt). عند [5/5] kapanıyor: 38:9 'indehum' (hazineler onların yanında mı?) → 38:25, 38:40, 38:47 'indenâ' → 38:52 'indehum' (okumada görüldü). قصر [1/1]; طرف [1/1]. Fâsıla ب. 4 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 isim cümlesi, haber önde; D4 3MP 1.\n◈A — A1 sakınanlar (zamir), 'qâsırât' (adsız); A2 sahne: cennet.",
 53: "◇ 'hâzâ mâ tûadûne li-yevmi'l-hisâb' — işaret (DIKKAT) + EDİLGEN 1/1 'tûadûn' (vaat edilirsiniz), vaat eden adlanmıyor; pas z=5,38 → ★★★. Muhatap 2MP — iltifât alanı 1 (38:52 3MP → 38:53 2MP). 'hâzâ mâ tûadûn' (metin sayımı) 2 ayet: 38:53, 50:32 (henüz okunmadı). 'yevmi'l-hisâb' korpusta 4 ayet — sûre içindeki üçü de artık okundu: 38:16 inkârcıların alayı ('qable yevmi'l-hisâb') → 38:26 sapanların unuttuğu gün → 38:53 sakınanlara vaat edilen gün; 40:27 henüz okunmadı (okumada görüldü). حسب [4/4] kapanıyor: 38:16, 38:26, 38:39 'bi-ğayri hisâb', 38:53. وعد [1/1]; يوم [3/6]. Fâsıla ب. 5 kelime.\n◈K — K1 —; K2 zaman: 'li-yevmi'l-hisâb' — hesap günü (vaat edilen); K3 —; K4 —.\n◈B — —\n◈D — D1 işaret cümlesi + mevsûl + edilgen IMPF; D2 işaret 'hâzâ'; D4 2MP 2.\n◈A — A1 muhataplar (2MP, sakınanlar); A3 vaat.",
 54: "◇ 'inne hâzâ le-rizqunâ mâ lehû min nefâd' — tekit + olumsuzluk: bu bizim rızkımız; tükenmesi yok. 1P 'rizqunâ' — iltifât alanı 1 (38:53 2MP → 38:54 1P). 'min nefâd' korpusta 1 ayet. رزق [1/1]; نفد [1/1]. Fâsıla د — KAFİYE KIRILMASI → ★ (kafiye kırığı). 7 kelime.\n◈K — —\n◈B — —\n◈D — D1 tekitli isim cümlesi (inne + işaret + lâm) + olumsuz isim cümlesi; D2 işaret; D4 1P 1 · 3MS 1.\n◈A — A1 'biz' (rızkın sahibi); A3 süreklilik.",
 55: "◇ 'hâzâ; ve inne li't-tâğîne le-şerra meâb' — 'hâzâ' (bu böyle) ile kesme; sonra karşıt hüküm. 38:49 've inne li'l-muttaqîne le-husne meâb' ↔ 38:55 've inne li't-tâğîne le-şerra meâb' — aynı kalıp, iki karşıt çift: muttaqîn / tâğîn, husn / şerr (okumada görüldü; nakarat3 süzgeci yakalamıyor — kelimeler farklı). أوب [8/8] kapanıyor: 'evvâb' dört kez (38:17, 19, 30, 44) → 'meâb' dört kez (38:25, 40, 49, 55); son 'meâb' azgınların (okumada görüldü). طغي [1/1]; شرر [1/2]. Fâsıla ب — KAFİYE KIRILMASI (38:54 د'dan dönüş) → ★ (kafiye kırığı). 5 kelime.\n◈K — —\n◈B — —\n◈D — D1 işaret (mübtedâ, haberi hazf) + tekitli isim cümlesi (haber önde); D2 işaret 'hâzâ'; D4 şahıs işareti yok.\n◈A — A1 azgınlar (sınıf); A2 sahne geçişi: cennetten cehenneme; A3 karşıt hüküm.",
 56: "◇ 'cehenneme yaslevnehâ fe-bi'se'l-mihâd' — 38:55 'meâb'ın bedeli: cehennem; girerler; ne kötü döşek. esit2 → 14:29 (okundu) 'cehenneme yaslevnehâ ve bi'se'l-qarâr' (oran 0,85, BENZER) — 14:29'un iki yarısı burada ayrılıyor: 'cehenneme yaslevnehâ' 38:56'da, 'bi'se'l-qarâr' 38:60'ta (okumada görüldü, KAPATILAMAZ). 'cehenneme yaslevnehâ' (metin sayımı) 3 ayet: 14:29, 38:56, 58:8 (henüz okunmadı); 'bi'se'l-mihâd' 5 ayet: 2:206, 3:12, 3:197, 13:18 (okundu), 38:56. 38:50 'cennâti adn' ↔ 38:56 'cehennem' — aktör alanı ikisini de adlı yer sayıyor. صلي [1/2]; بأس [1/2]; مهد [1/1]. Fâsıla د. 4 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 bedel + IMPF + fâ ile zem fiili (bi'se); D4 3FS 1 · 3MP 2 · 3MS 1.\n◈A — A1 azgınlar (zamir), cehennem (adlı yer); A2 sahne: cehennem.",
 57: "◇ 'hâzâ fe'l-yezûqûhu hamîmun ve ğassâq' — işaret + üçüncü şahsa emir (lâm-ı emir): tatsınlar; kaynar su ve irin. ذوق [2/2] kapanıyor: 38:8 'bel lemmâ yezûqû azâb' (henüz azabımı tatmadılar) → 38:57 'fe'l-yezûqûh' (tatsınlar) (okumada görüldü). 'hamîmun ve ğassâq' korpusta 1 ayet; 78:25 'hamîmen ve ğassâqâ' (henüz okunmadı). 38:51 cennette 'şarâb' ↔ 38:57 cehennemde 'hamîm ve ğassâq' (okumada görüldü). حمم [1/1]; غسق [1/1]. Fâsıla ق. 4 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 işaret + fâ + lâm-ı emir (IMPF) + bedel; D2 işaret 'hâzâ'; D4 3MP 2 · 3MS 1.\n◈A — A1 azgınlar (zamir); A3 tattırma.",
 58: "◇ 've âharu min şeklihî ezvâc' — ve onun türünden başka çeşitler. 'ezvâc' burada 'türler, çeşitler' anlamında; sayı işareti zevc. زوج [1/1] ◈B'yi tetikliyor; anlam canlı eşleri değil, azap türleri. أخر [3/3] kapanıyor: 38:7 'el-milleti'l-âhira' → 38:38 'âharîn' → 38:58 'âhar'. شكل [1/1]. Fâsıla ج — sûrede tek (bu ayete kadar). 4 kelime, yıldız yok.\n◈K — —\n◈B — B1 —; B2 —; B3 —; B4 tetik زوج ('ezvâc'): anlam 'çeşitler' — canlı/eş unsuru yok.\n◈D — D1 isim cümlesi (mübtedâ + sıfat + haber); D4 3MS 1.\n◈A — A1 —; A3 azabın çoğaltılması.",
 59: "◇ 'hâzâ fevcun muqtahimun meakum; lâ merhaben bihim; innehum sâlu'n-nâr' — işaret + olumsuz karşılama + tekit. Konuşanlar adlanmıyor: önce 2MP'ye hitap ('meakum'), sonra 3MP hakkında söz ('bihim', 'innehum') — iki ses ya da tek ses, metin ayırmıyor (KAPATILAMAZ). 'lâ merhaben' (metin sayımı) 2 ayet: 38:59, 38:60 — karşılıklı. 'sâlu'n-nâr' korpusta 1 ayet. صلي [2/2] kapanıyor: 38:56 'yaslevnehâ' → 38:59 'sâlu'n-nâr'. نور [2/5]: 38:27 'mine'n-nâr' → 38:59 'en-nâr'. فوج [1/1]; قحم [1/1]; رحب [1/2]. Fâsıla ر. 10 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 işaret cümlesi + olumsuz mastar ('lâ merhaben') + tekitli isim cümlesi; D2 işaret 'hâzâ'; D4 2MP 1 · 3MP 2.\n◈A — A1 adsız konuşan(lar), dalıp giren kalabalık (fevc); A3 karşılama reddi.",
 60: "◇ 'qâlû bel entum lâ merhaben bikum; entum qaddemtumûhu lenâ; fe-bi'se'l-qarâr' — IDRAB ('bel'): cevap; 'lâ merhaben' geri çevriliyor (bihim → bikum). 'bi'se'l-qarâr' (metin sayımı) 2 ayet: 14:29 (okundu) ve 38:60 — 38:56 ile birlikte 14:29'un iki yarısı (okumada görüldü, KAPATILAMAZ). بأس [2/2] kapanıyor: 38:56 'bi'se'l-mihâd' → 38:60 'bi'se'l-qarâr'. رحب [2/2] kapanıyor. قدم [1/2]; قرر [1/1]; قول [9/23]. Fâsıla ر. 11 kelime — blokun en uzunu, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 'qâlû' + IDRAB + olumsuz mastar + PERF (2MP) + zem cümlesi; D2 IDRAB; D4 1P 1 · 2MP 5 · 3MP 2 · 3MS 2.\n◈A — A1 dalıp girenler (konuşan), önceki topluluk (muhatap 2MP); A3 suçlamanın geri çevrilmesi.",
}
MEAL.update(MEAL6); M.update(M6)

MEAL7 = {
 61: 'Dediler ki: "Rabbimiz, bunu bize kim hazırladıysa ateşte onun azabını kat kat artır!"',
 62: 'Ve dediler: "Bize ne oldu ki kötülerden saydığımız adamları göremiyoruz?',
 63: 'Onları alay konusu mu edinmiştik, yoksa gözler mi onlardan kaydı?"',
 64: 'Şüphesiz bu, ateş ehlinin birbiriyle çekişmesi, gerçektir.',
 65: 'De ki: "Ben ancak bir uyarıcıyım. Tek ve her şeye üstün gelen (Kahhâr) Allah\'tan başka ilâh yoktur.',
 66: 'Göklerin, yerin ve ikisinin arasındakilerin Rabbi; mutlak güç sahibi, çok bağışlayan (Ğaffâr)."',
 67: 'De ki: "O, büyük bir haberdir;',
 68: 'siz ondan yüz çeviriyorsunuz.',
 69: 'Yüce topluluk (el-meleu\'l-a\'lâ) tartışırken benim onlar hakkında bir bilgim yoktu.',
 70: 'Bana ancak benim apaçık bir uyarıcı olduğum vahyediliyor."',
}
M7 = {
 61: "◇ 'qâlû rabbenâ men qaddeme lenâ hâzâ fe-zidhu azâben dı'fen fi'n-nâr' — cehennemdekilerin duası: 'Rabbimiz, bunu bize hazırlayanın azabını kat kat artır'. xref 7:38 (okundu) 'rabbenâ hâulâi edallûnâ fe-âtihim azâben dı'fen mine'n-nâr' — 'azâben dı'fen' (metin sayımı) korpusta 2 ayet: 7:38, 38:61; ikisinde de sonraki topluluk öncekiler için kat kat azap istiyor (okumada görüldü). Rab yedinci kez; 'rabbenâ' ikinci kez inkârcı ağzında: 38:16 'rabbenâ accil lenâ qıttanâ' (alay) → 38:61 'rabbenâ … fe-zidhu' (cehennemde) (okumada görüldü). ★ kaynak rab (z=1,62). قدم [2/2] kapanıyor: 38:60 'qaddemtumûhu lenâ' → 38:61 'men qaddeme lenâ'. عذب [4/4] kapanıyor: 38:8 'azâbi' → 38:26 → 38:41 → 38:61. زيد [1/1]; ضعف [1/1]; نور [3/5]; قول [10/23]. Fâsıla ر. 11 kelime.\n◈K — —\n◈B — —\n◈D — D1 nidâ + şart mevsûlü ('men') + fâ ile emir (dua); D2 işaret 'hâzâ'; D4 1P 2 · 2MS 1 · 3MP 2 · 3MS 2.\n◈A — A1 cehennemdekiler (konuşan), Rab (hitap), 'hazırlayan' (adsız); A3 karşılıklı suçlamadan Rab'be başvuruya.",
 62: "◇ 've qâlû mâ lenâ lâ nerâ ricâlen kunnâ nauddehum mine'l-eşrâr' — soru: kötülerden saydığımız adamları neden görmüyoruz? Aktör alanı 'ricâl'i adsız (racül) işaretliyor. 'mine'l-eşrâr' korpusta 1 ayet. Ölçüm 'sayı işareti عَدَّ' veriyor — 'nauddu' burada 'saymak, kabul etmek' (biri saymak değil); araç fiili sayı işareti olarak alıyor (kayıt). شرر [2/2] kapanıyor: 38:55 'şerra meâb' (azgınlara kötü dönüş) → 38:62 'eşrâr' (azgınların başkalarına taktığı ad) (okumada görüldü). رجل [2/2]: 38:42 'ricl' (ayak) → 38:62 'ricâl' (adamlar) — aynı kök iki anlam. رأي [1/1]; عدد [1/1]; كون [1/4]; قول [11/23]. Fâsıla ر. 10 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 'mâ lenâ' soru kalıbı + olumsuz IMPF + kâne + IMPF; D4 1P 5 · 3MP 3.\n◈A — A1 cehennemdekiler (konuşan, 1P), 'adamlar' (adsız, yok olan); A3 arayış.",
 63: "◇ 'e-ttehaznâhum sihriyyen em zâğat anhumu'l-ebsâr' — iki seçenekli soru: alay mı ettik, gözler mi kaydı? 'sihriyyâ' (metin sayımı) 3 ayet: 23:110 (okundu, 'fettehaztumûhum sihriyyen'), 38:63, 43:32 (henüz okunmadı). 'zâğat' 2 ayet: 33:10 (okundu, 'iz zâğati'l-ebsâr'), 38:63 — ikisinde de özne 'el-ebsâr' (okumada görüldü). سخر [3/3] kapanıyor: 38:18 dağların teshiri → 38:36 rüzgârın teshiri → 38:63 'sihriyy' (alay) — gloss 'boyun eğdirme' alay anlamını taşımıyor (987/1015 ailesi, kayıt). بصر [2/2] kapanıyor: 38:45 'uli'l-ebsâr' (basiret sahipleri) → 38:63 'zâğati'l-ebsâr' (kayan gözler) (okumada görüldü). أخذ [2/2]; زيغ [1/1]. Fâsıla ر. 6 kelime, yıldız yok.\n◈K — —\n◈B — B1 —; B2 gözler (ebsâr) — 'kayma' fiilinin öznesi; B3 görme — kaymış/sapmış; B4 —.\n◈D — D1 istifhâm (hemze) + PERF + 'em' + PERF; D4 1P 2 · 3FS 1 · 3MP 2.\n◈A — A1 cehennemdekiler (1P), adsız adamlar (3MP); A3 iki ihtimal, cevap yok.",
 64: "◇ 'inne zâlike le-haqqun tehâsumu ehli'n-nâr' — anlatıcının hükmü: bu gerçek, ateş ehlinin çekişmesi. 'tehâsum' korpusta 1 ayet. خصم [3/4]: 38:21-22 davacılar ('el-hasm', 'hasmân') → 38:64 'tehâsum' (ateş ehli) → 38:69 'yahtasımûn' (yüce topluluk) (okumada görüldü). حقق [4/6]; أهل [2/2] kapanıyor: 38:43 'ehlehû' (Eyyûb'un ailesi) → 38:64 'ehli'n-nâr'. نور [4/5]. Fâsıla ر. 6 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 tekitli isim cümlesi (inne + lâm) + bedel; D4 şahıs işareti yok.\n◈A — A1 anlatıcı (hüküm), ateş ehli; A4 cehennem sahnesinin kapanışı.",
 65: "◇ 'qul innemâ ene munzir; ve mâ min ilâhin illa'llâhu'l-vâhidu'l-qahhâr' — 'qul' emri + iki HASR: ben ancak uyarıcıyım; Allah'tan başka ilâh yok. ALLAH LAFZI sûrede ikinci kez (ilki 38:26). esmâ: qahhâr 'ilahi' (son konum); ölçüm satırı 'MÜHÜRSÜZ' yazıyor, bilanço §4.3 mührü geçerli sayıyor — iki alan ayrışıyor (38:35'te de aynı; kayıt). 'el-vâhidu'l-qahhâr' (metin sayımı) 5 ayet: 12:39, 14:48 (okundu), 38:65, 39:4, 40:16 (henüz okunmadı). وحد [4/4] kapanıyor: 38:5 inkârcıların itirazı 'e-ce'ale'l-âliheta ilâhen vâhidâ' → 38:65 'mâ min ilâhin illa'llâhu'l-vâhid' — itiraz edilen iddia burada 'qul' ile söyletiliyor (okumada görüldü, KAPATILAMAZ). أله [6,7/7] kapanıyor. نذر [2/3]: 38:4 'acibû en câehum munzir' → 38:65 'innemâ ene munzir'; 'innemâ ene munzir' korpusta 1 ayet. قهر [1/1]. Sayı işareti vâhid (doğru). Fâsıla ر. 11 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 emir + iki hasr (innemâ / mâ … illâ); D2 HASR; D3 أله ikilemesi (ilâh / Allah); D4 1S 1 · 2MS 1.\n◈A — A1 muhatap (2MS → 1S konuşan: uyarıcı), Allah (lafız); A3 sûrenin açılış itirazına cevap.",
 66: "◇ 'rabbu's-semâvâti ve'l-ardı ve mâ beynehumâ'l-azîzu'l-ğaffâr' — 38:65'teki lafzın sıfatları sürüyor: Rab + iki esmâ (azîz, ğaffâr), ikisi 'ilahi'; §4.3 mühür ÇİFT. ★★ kaynak rab (z=2,72). nakarat3 'es-semâvâti ve'l-ardı ve mâ beynehumâ' sûre içi üçüncü: 38:10 (mülk sorusu) → 38:27 (boşuna yaratılmadı) → 38:66 (Rabbi) — üç ucu da okundu (okumada görüldü). 'rabbu's-semâvâti ve'l-ardı ve mâ beynehumâ' (metin sayımı) 6 ayet: 19:65, 26:24, 37:5 (okundu), 38:66, 44:7, 78:37 (henüz okunmadı). 'el-azîzu'l-ğaffâr' 3 ayet: 38:66, 39:5, 40:42 (henüz okunmadı). عزز [4/5]: 38:2 izzet (inkârcılar) → 38:9 azîz → 38:23 azzenî → 38:66 azîz. غفر [4/4] kapanıyor: 38:24 isteğfera → 38:25 ğafernâ → 38:35 iğfir lî → 38:66 el-ğaffâr (okumada görüldü). سمو [3/3], أرض [5/5] kapanıyor; بين [6/7]. İltifât alanı 1. Fâsıla ر. 7 kelime. 🜁 L0 — gökler, yer, ikisinin arası adlanıyor; ilişki rablık (sahiplik); süreç/ölçü yok (37:5, 38:10 emsali); olgu evet, çıpa hayır; tarayıcı vermedi.\n◈K — K1 gökler (semâvât), yer, ikisinin arası; K2 —; K3 ölçek: en büyük birimler, Rab'be izafe; K4 —.\n◈B — —\n◈D — D1 bedel/sıfat zinciri (fiil yok); D3 iki esmâ ard arda; D4 3D 1.\n◈A — A1 Rab (lafzın bedeli); A3 sıfatlar.",
 67: "◇ 'qul huve nebeun azîm' — ikinci 'qul': o büyük bir haber. 'huve' zamirinin göndergesi adlanmıyor (KAPATILAMAZ). 'nebeun azîm' (belirsiz) korpusta 1 ayet; belirli 'en-nebei'l-azîm' 78:2 (henüz okunmadı). نبأ [2/3]: 38:21 'nebeu'l-hasm' → 38:67 'nebeun azîm'. عظم [1/1]; قول [13/23]. Fâsıla م (N sınıfı) — 38:67'den itibaren fâsıla ر'den م/ن'ye geçiyor; kafiye kırığı alanı bu geçişi işaretlemiyor. 4 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 emir + isim cümlesi; D4 2MS 1 · 3MS 1.\n◈A — A1 muhatap (2MS), haber (zamir); A3 haberin büyüklüğü.",
 68: "◇ 'entum anhu mu'ridûn' — siz ondan yüz çeviriyorsunuz. Sûrenin en kısa ayeti (3 kelime; 1-70 arasında). 'mu'ridûn' korpusta 14 ayet. عرض [2/2] kapanıyor: 38:31 'urıda aleyhi' (atlar sunuldu) → 38:68 'mu'ridûn' (yüz çevirenler) — aynı kök iki anlam; gloss ikisini taşıyor (okumada görüldü). Fâsıla ن. Yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 isim cümlesi (zamir + ism-i fâil); D4 2MP 1 · 3MS 1.\n◈A — A1 muhataplar (2MP); A3 yüz çevirme.",
 69: "◇ 'mâ kâne liye min ilmin bi'l-melei'l-a'lâ iz yahtasımûn' — 1S: yüce topluluk tartışırken bilgim yoktu. 'el-meleu'l-a'lâ' (metin sayımı) 2 ayet: 37:8 (okundu, şeytanlar 'ona kulak veremez') ve 38:69 (okumada görüldü). ملأ [2/3]: 38:6 'el-meleu minhum' (inkârcıların ileri gelenleri) → 38:69 'el-meleu'l-a'lâ'. خصم [4/4] kapanıyor: davacılar (21-22) → ateş ehlinin çekişmesi (64) → yüce topluluğun tartışması (69) (okumada görüldü). علم [1/4]; علو [1/2]; كون [2/4]. Fâsıla ن. 9 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 olumsuz kâne + câr-mecrûr + 'iz' + IMPF; D4 1S 1 · 3MP 2 · 3MS 1.\n◈A — A1 uyarıcı (1S), yüce topluluk (adsız); A3 bilginin sınırı.",
 70: "◇ 'in yûhâ ileyye illâ ennemâ ene nezîrun mubîn' — HASR + EDİLGEN 1/1 'yûhâ' (vahyediliyor), vahyeden adlanmıyor; pas z=5,38 → ★★★. esmâ: mubîn 'degil' (uyarıcının sıfatı) — §4.3 mühür adayı, geçersiz. 'innemâ ene nezîrun mubîn' (metin sayımı) 3 ayet: 29:50 (okundu), 38:70, 67:26 (henüz okunmadı); xref 46:9 (henüz okunmadı). نذر [3/3] kapanıyor: 38:4 'munzir' (şaşılan) → 38:65 'innemâ ene munzir' → 38:70 'innemâ ene nezîr' (okumada görüldü). بين [7/7] kapanıyor; وحي [1/1]. Fâsıla ن. 8 kelime.\n◈K — —\n◈B — —\n◈D — D1 olumsuz 'in' + edilgen IMPF + 'illâ' + innemâ (çift hasr); D2 HASR; D4 1S 2 · 3MS 1.\n◈A — A1 uyarıcı (1S), vahyeden (adsız); A3 görevin sınırı.",
}
MEAL.update(MEAL7); M.update(M7)

MEAL8 = {
 71: 'Hani Rabbin meleklere demişti: "Ben çamurdan bir beşer yaratacağım.',
 72: 'Onu düzenleyip içine ruhumdan üflediğimde, hemen ona secdeye kapanın."',
 73: 'Meleklerin hepsi topluca secde etti;',
 74: 'İblîs hariç; o büyüklendi ve inkâr edenlerden oldu.',
 75: 'Dedi ki: "Ey İblîs! İki elimle yarattığıma secde etmekten seni ne alıkoydu? Büyüklendin mi, yoksa yücelerden mi oldun?"',
 76: 'Dedi ki: "Ben ondan hayırlıyım; beni ateşten yarattın, onu ise çamurdan yarattın."',
 77: 'Dedi ki: "Öyleyse çık oradan; çünkü sen kovulmuşsun.',
 78: 'Ve din gününe kadar lânetim senin üzerinedir."',
 79: 'Dedi ki: "Rabbim, öyleyse onların diriltilecekleri güne kadar bana mühlet ver."',
 80: 'Dedi ki: "Sen mühlet verilenlerdensin,',
}
M8 = {
 71: "◇ 'iz qâle rabbuke li'l-melâiketi innî hâliqun beşeren min tîn' — sahne açılışı: Rab meleklere konuşuyor (1S). Rab dokuzuncu kez ('rabbuke', 2MS iyelik); ★★ kaynak rab (z=2,05). esmâ: hâliq 'ilahi' (inne'nin haberi, konuşan Rab; 34:11 emsali); ölçüm satırı 'ORTA konum, MÜHÜRSÜZ', bilanço §4.3 mührü geçerli sayıyor (38:35, 38:65 emsali; kayıt). xref 15:28 (okundu) 've iz qâle rabbuke li'l-melâiketi innî hâliqun beşeren min salsâlin min hamein mesnûn' — açılış aynı, madde farklı: orada 'salsâl, hame' mesnûn', burada 'tîn' (okumada görüldü); 'beşeren min tîn' korpusta 1 ayet. xref 2:30 (okundu) 'innî câilun fi'l-ardı halîfe' — 38:26'daki 'halîfe' bağı. Ayette 'Âdem' adı geçmiyor; 'beşer'. ملك [4/5]: araç 'melâike'yi ملك (mülk) ipliğine sayıyor — 38:10, 38:20, 38:35 'mulk' → 38:71 'melâike'; gloss 'mülk; melik' melek anlamını taşımıyor (987/1015 ailesi, kayıt). خلق [3/6]; بشر [1/1]; طين [1/2]; قول [14/23]. Fâsıla ن. 9 kelime. 🜁 L1 — beşer + madde (tîn); madde ve sonuç, ara aşama yok (36:77 nutfe emsali); olgu evet, çıpa hayır.\n◈K — —\n◈B — B1 beşer (insan, yaratılacak); B2 —; B3 —; B4 yaratma (hâliq) — madde: çamur.\n◈D — D1 'iz' + PERF + alıntı: tekitli isim cümlesi (inne + ism-i fâil, gelecek anlamlı); D4 1S 1 · 2MS 1 · 3MS 1.\n◈A — A1 Rab (konuşan), melekler (muhatap), muhatap Peygamber ('rabbuke'); A2 sahne geçişi: uyarıcının sözünden yaratılış sahnesine; A3 duyuru.",
 72: "◇ 'fe-izâ sevveytuhû ve nefahtu fîhi min rûhî fe-qaû lehû sâcidîn' — 1S 5: düzenleyip ruhumdan üflediğimde secdeye kapanın (IMPV, 2MP). esit2 → 15:29 oran 1,00 (TAM) — ayet 15:29 ile harfi harfine aynı (okundu). xref 32:9 (okundu) 'thumme sevvâhu ve nefaha fîhi min rûhih' — orada 3MS (sevvâhu, rûhih), burada 1S (sevveytuhû, rûhî) (okumada görüldü). روح [2/2] kapanıyor: 38:36 'er-rîh' (rüzgâr) → 38:72 'rûhî' (ruhum) — aynı kök iki anlam; gloss ikisini taşıyor. سوي [2/2] kapanıyor: 38:22 'sevâi's-sırât' → 38:72 'sevveytuhû'. نفخ [1/1]; وقع [1/1]; سجد [1/3]. Fâsıla ن. 9 kelime, yıldız yok. 🜁 L1 — iki aşama (tesviye → nefh) sırayla adlanıyor; mekanizma/ölçü yok; olgu evet, çıpa hayır.\n◈K — —\n◈B — —\n◈D — D1 şart ('izâ') + iki PERF (1S) + fâ ile emir; D4 1S 5 · 2MP 2 · 3MS 3.\n◈A — A1 Rab (1S), melekler (2MP), beşer (zamir); A3 emir: secde.",
 73: "◇ 'fe-secede'l-melâiketu kulluhum ecmaûn' — esit2 → 15:30 oran 1,00 (TAM). 'kulluhum ecmaûn' (metin sayımı) 2 ayet: 15:30, 38:73. كلل [5/5] kapanıyor: 38:14 'in kullun' → 38:19 'kullun lehû evvâb' → 38:37 'kulle bennâ'' → 38:48 'kullun mine'l-ahyâr' → 38:73 'kulluhum'. ملك [5/5] kapanıyor ('melâike'; araç mülk ipliğine sayıyor, kayıt). سجد [2/3]; جمع [1/3]. Fâsıla ن. 4 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 fâ + PERF + iki tekit (kull, ecma'); D4 3MP 1 · 3MS 1.\n◈A — A1 melekler (hepsi); A3 itaat.",
 74: "◇ 'illâ iblîse'stekbera ve kâne mine'l-kâfirîn' — istisna (HASR): İblîs büyüklendi, inkârcılardan oldu. Aktör adlı İblîs. esit2 15:31 ile eşleşmiyor (15:31 'ebâ en yekûne mea's-sâcidîn'); 'istekbera ve kâne mine'l-kâfirîn' (metin sayımı) 2 ayet: 2:34 (okundu, 'ebâ ve'stekbera ve kâne mine'l-kâfirîn') ve 38:74 — burada 'ebâ' yok (okumada görüldü). xref 39:59 (henüz okunmadı). 38:72-80 dizisinde 15:29-37 ile TAM/BENZER eşleşme 74-76'da kesiliyor; bu üç ayet 2:34 ve 7:12'ye yaslanıyor (okumada görüldü, KAPATILAMAZ). كفر [5/5] kapanıyor: 38:2 'ellezîne keferû' → 38:4 'el-kâfirûn' → 38:27 ×2 → 38:74 İblîs 'mine'l-kâfirîn' (okumada görüldü). كبر [1/2]; كون [3/4]. Fâsıla ن. 6 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 istisna + iki PERF (X. bab + kâne); D2 HASR; D4 3MS 2.\n◈A — A1 İblîs (adlı); A3 istisna: büyüklenme.",
 75: "◇ 'qâle yâ iblîsu mâ meneake en tescude li-mâ halaqtu bi-yedeyy; e-stekberte em kunte mine'l-âlîn' — nidâ + iki soru (1S konuşan, 2MS İblîs). 'bi-yedeyy' (iki elimle, ikil + 1S iyelik) korpusta 1 ayet. xref 7:12 (okundu) 'mâ meneake ellâ tescude iz emertuk' — 'mâ meneake' ortak; burada sebep 'li-mâ halaqtu bi-yedeyy' (okumada görüldü). 15:32 (okundu) 'mâ leke ellâ tekûne mea's-sâcidîn'. يدي [3/3] kapanıyor: 38:44 Eyyûb'un eli → 38:45 'uli'l-eydî' (güç) → 38:75 'bi-yedeyy' (okumada görüldü). كبر [2/2]: 38:74 'istekbera' (anlatı) → 38:75 'e-stekberte' (soru). علو [2/2]: 38:69 'el-meleu'l-a'lâ' → 38:75 'mine'l-âlîn'. سجد [3/3] kapanıyor; منع [1/1]; خلق [4/6]; كون [4/4]. Fâsıla ن. 14 kelime — blokun en uzunu, yıldız yok.\n◈K — —\n◈B — B1 beşer ('mâ halaqtu', adlanmıyor); B2 eller (yedeyy, ikil, 1S iyelik) — yaratma fiiline bağlı; B3 —; B4 yaratma.\n◈D — D1 nidâ + 'mâ' soru + 'en' mastar + mevsûl + PERF; ikinci soru 'e … em'; D4 1S 3 · 2MS 6 · 3MS 2.\n◈A — A1 konuşan (1S, 'qâle' öznesi adlanmıyor — önceki sahneden Rab), İblîs (muhatap, adlı); A3 hesap sorma.",
 76: "◇ 'qâle ene hayrun minhu; halaqtenî min nârin ve halaqtehû min tîn' — İblîs'in cevabı: ben ondan hayırlıyım; madde karşılaştırması. xref 7:12 (okundu) 'ene hayrun minhu halaqtenî min nârin ve halaqtehû min tîn' — cevap kısmı harfi harfine aynı; 'halaqtenî min nâr' (metin sayımı) 2 ayet: 7:12, 38:76. 15:33 (okundu) 'lem ekun li-escude li-beşerin halaqtehû min salsâl' — orada ateş anılmıyor (okumada görüldü). خلق ×2 [5,6/6] kapanıyor: 38:7 'ihtilâq' → 38:27 'halaqnâ' → 38:71 'hâliq' → 38:75 'halaqtu' → 38:76 'halaqtenî / halaqtehû'. نور [5/5] kapanıyor: 38:27, 59, 61, 64 cehennem ateşi → 38:76 İblîs'in yaratıldığı ateş (okumada görüldü). خير [4/4] kapanıyor: 38:32 'hubbe'l-hayr' → 38:47-48 'ahyâr' → 38:76 'ene hayrun minh'. طين [2/2] kapanıyor; قول [16/23]. Fâsıla ن. 10 kelime, yıldız yok. 🜁 L1 — iki madde (ateş, çamur) adlanıyor + karşılaştırma iddiası (İblîs'in sözü); süreç/ölçü yok; olgu evet, çıpa hayır.\n◈K — —\n◈B — B1 İblîs (1S), beşer (3MS); B2 —; B3 —; B4 yaratma — iki madde: ateş / çamur.\n◈D — D1 isim cümlesi (tafdil) + iki PERF (2MS fail, 1S/3MS meful) — paralel yapı; D3 خلق ikilemesi; D4 1S 2 · 2MS 4 · 3MS 3.\n◈A — A1 İblîs (konuşan), Rab (muhatap 2MS), beşer (3MS); A3 üstünlük iddiası.",
 77: "◇ 'qâle fe'hruc minhâ fe-inneke racîm' — emir + tekit: çık oradan, sen kovulmuşsun. esit2 → 15:34 oran 1,00 (TAM); 'fe'hruc minhâ fe-inneke racîm' metin sayımı 2 ayet: 15:34, 38:77. 'minhâ' zamirinin göndergesi adlanmıyor (KAPATILAMAZ). خرج [1/1]; رجم [1/1]; قول [17/23]. Fâsıla م. 5 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 emir + fâ + tekitli isim cümlesi; D4 2MS 2 · 3FS 1 · 3MS 1.\n◈A — A1 konuşan (adlanmıyor), İblîs (muhatap); A3 kovma.",
 78: "◇ 've inne aleyke la'netî ilâ yevmi'd-dîn' — tekit: din gününe kadar lânetim üzerinde. esit2 → 15:35 oran 0,89 (BENZER): 15:35 'aleyke'l-la'nete' (belirli), burada 'la'netî' (1S iyelik) — tek fark (okumada görüldü). 'la'netî' korpusta 1 ayet; 'yevmi'd-dîn' 13 ayet. لعن [1/1]; دين [1/1]; يوم [4/6]. Fâsıla ن. 6 kelime, yıldız yok.\n◈K — K1 —; K2 zaman: 'ilâ yevmi'd-dîn' — din gününe kadar (süre sınırı); K3 —; K4 —.\n◈B — —\n◈D — D1 tekitli isim cümlesi (haber önde) + 'ilâ' ile süre; D4 1S 1 · 2MS 1.\n◈A — A1 konuşan (1S), İblîs (2MS); A3 lânet.",
 79: "◇ 'qâle rabbi fe-enzirnî ilâ yevmi yub'asûn' — İblîs'in isteği: Rabbim, diriltilecekleri güne kadar mühlet ver. Rab onuncu ve son kez ([10/10]) — İblîs'in ağzında 'rabbi' (1S nidâ); ★★★ kaynak rab (z=3,23). esit2 → 15:36 oran 1,00 (TAM), 7:14 oran 0,93 (BENZER). 'ilâ yevmi yub'asûn' (metin sayımı) 5 ayet: 7:14, 15:36, 23:100, 37:144 (okundu), 38:79. EDİLGEN 1/3 'yub'asûn' (diriltilecekler), pas z=1,57 de eşik üstü. Rab sûrede: 38:9 rabbike → 16 rabbenâ (inkârcılar) → 24 rabbehû → 32 rabbî (Süleymân) → 35 rabbi (Süleymân) → 41 rabbehû → 61 rabbenâ (cehennemdekiler) → 66 rabbu's-semâvât → 71 rabbuke → 79 rabbi (İblîs) (okumada görüldü). بعث [1/1]; نظر [2/3]; يوم [5/6]; قول [18/23]. Fâsıla ن. 6 kelime.\n◈K — K1 —; K2 zaman: 'ilâ yevmi yub'asûn' — diriliş gününe kadar (süre sınırı); K3 —; K4 —.\n◈B — —\n◈D — D1 nidâ + fâ + emir (dua) + 'ilâ' ile süre (edilgen IMPF); D4 1S 2 · 2MS 1 · 3MP 2 · 3MS 1.\n◈A — A1 İblîs (konuşan), Rab (hitap); A3 mühlet isteği.",
 80: "◇ 'qâle fe-inneke mine'l-munzarîn' — cevap: sen mühlet verilenlerdensin. esit2 → 15:37 oran 1,00 (TAM); 'mine'l-munzarîn' (metin sayımı) 3 ayet: 7:15, 15:37 (okundu), 38:80. 38:72-80'de esit2 TAM eşleşme 5 ayet (72, 73, 77, 79, 80 — hepsi sûre 15'le), BENZER 1 (78); 74-76 sûre 15'ten ayrılıyor (okumada görüldü). نظر [3/3] kapanıyor: 38:15 'mâ yanzuru' (bekliyorlar) → 38:79 'enzirnî' → 38:80 'el-munzarîn' — kök iki anlam (bakma/bekleme, mühlet). قول [19/23]. Fâsıla ن. 4 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 fâ + tekitli isim cümlesi; D4 2MS 1 · 3MS 1.\n◈A — A1 konuşan (adlanmıyor), İblîs (2MS); A3 mühlet verilmesi.",
}
MEAL.update(MEAL8); M.update(M8)

MEAL9 = {
 81: 'bilinen vaktin gününe kadar."',
 82: 'Dedi ki: "Senin izzetine andolsun, onların hepsini azdıracağım;',
 83: 'içlerinden ihlâsa erdirilmiş kulların hariç."',
 84: 'Dedi ki: "Hak budur; ben de hakkı söylerim:',
 85: 'Andolsun, cehennemi senden ve onlardan sana uyanların hepsinden dolduracağım."',
 86: 'De ki: "Buna karşılık sizden bir ücret istemiyorum; ben kendiliğinden yükümlülük uyduranlardan da değilim.',
 87: 'O, âlemler için ancak bir zikirdir.',
 88: 'Onun haberini bir süre sonra mutlaka bileceksiniz."',
}
M9 = {
 81: "◇ 'ilâ yevmi'l-vaqti'l-ma'lûm' — 38:80'in devamı: bilinen vaktin gününe kadar. esit2 → 15:38 oran 1,00 (TAM); 'yevmi'l-vaqti'l-ma'lûm' (metin sayımı) 2 ayet: 15:38, 38:81. يوم [6/6] kapanıyor: 38:16 'yevmi'l-hisâb' (alay) → 38:26 (unutulan) → 38:53 (vaat) → 38:78 'yevmi'd-dîn' → 38:79 'yevmi yub'asûn' (İblîs'in istediği) → 38:81 'yevmi'l-vaqti'l-ma'lûm' (verilen) — İblîs'in istediği gün ile verilen gün farklı adlanıyor (okumada görüldü, KAPATILAMAZ). وقت [1/1]; علم [2/4]. Fâsıla م. 4 kelime, yıldız yok.\n◈K — K1 —; K2 zaman: 'yevmi'l-vaqti'l-ma'lûm' — bilinen vakit (süre sınırı, adlanmıyor); K3 —; K4 —.\n◈B — —\n◈D — D1 câr-mecrûr (önceki cümleye bağlı), fiil yok; D4 şahıs işareti yok.\n◈A — A1 —; A3 mühletin sınırı.",
 82: "◇ 'qâle fe-bi-izzetike le-uğviyennehum ecmaîn' — İblîs'in yemini (EMPH 2): senin izzetine andolsun, hepsini azdıracağım. 'bi-izzetike' korpusta 1 ayet; 'le-uğviyennehum ecmaîn' (metin sayımı) 2 ayet: 15:39 (okundu, 'rabbi bimâ ağveytenî … ve le-uğviyennehum ecmaîn') ve 38:82 — 15:39'da gerekçe 'bimâ ağveytenî' (beni azdırmana karşılık), burada yemin 'bi-izzetike' (okumada görüldü). عزز [5/5] kapanıyor: 38:2 inkârcıların izzeti → 38:9 el-azîz → 38:23 azzenî → 38:66 el-azîz → 38:82 İblîs'in yemin ettiği izzet (okumada görüldü). غوي [1/1]; جمع [2/3]; قول [20/23]. Fâsıla ن. 4 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 fâ + yemin bâ'sı + qasem lâmı + nûn-ı tekit (IMPF); D4 1S 1 · 2MS 1 · 3MP 1 · 3MS 1.\n◈A — A1 İblîs (konuşan), Rab (hitap), 'onlar' (insanlar, adsız); A3 yemin.",
 83: "◇ 'illâ ibâdeke minhumu'l-muhlasîn' — istisna (HASR): ihlâsa erdirilmiş kulların hariç. esit2 → 15:40 oran 1,00 (TAM). خلص [3/3] kapanıyor: 38:46 'innâ ahlasnâhum bi-hâlisa' (üç kul arıtıldı) → 38:83 'el-muhlasîn' (İblîs'in eli yetmeyenler) (okumada görüldü). عبد [6/6] kapanıyor: 'abdenâ' (17 Dâvûd, 41 Eyyûb) → 'ni'me'l-abd' (30, 44) → 'ibâdenâ' (45) → 38:83 'ibâdeke' (İblîs'in ağzında 'senin kulların'). Fâsıla ن. 4 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 istisna + ism-i meful (IV. bab, edilgen anlam); D2 HASR; D4 2MS 1 · 3MP 1.\n◈A — A1 İblîs (konuşan), kullar (adsız sınıf); A3 kendi gücüne sınır.",
 84: "◇ 'qâle fe'l-haqqu ve'l-haqqa equl' — cevap: hak (budur), ve hakkı söylerim. حقق ×2 [5,6/6] kapanıyor; iki 'haqq' farklı i'râbda (NOM / ACC — ölçüm satırında ACC 1 · NOM 1); 'fe'l-haqqu ve'l-haqqa' korpusta 1 ayet. قول ×2 [21,22/23] ('qâle' / 'equlu'). 'qâle' öznesi adlanmıyor (KAPATILAMAZ). حقق ipliği: 38:14 'fe-haqqa ıqâb' → 38:22 / 38:26 'bi'l-haqq' → 38:64 'le-haqqun' → 38:84. Fâsıla ل — KAFİYE KIRILMASI → ★ (kafiye kırığı); ل sınıfı sûrede yalnız bu ayette (38:1-88). 4 kelime.\n◈K — —\n◈B — —\n◈D — D1 'qâle' + iki 'haqq' (biri mübtedâ/haber, biri meful, öne alınmış) + IMPF (1S); D3 حقق ve قول ikilemeleri; D4 1S 1 · 3MS 1.\n◈A — A1 konuşan (adlanmıyor, 1S), İblîs (muhatap, önceki ayetten); A3 hak sözü.",
 85: "◇ 'le-emleenne cehenneme minke ve mimmen tebiake minhum ecmaîn' — yemin (EMPH 2): cehennemi senden ve sana uyanlardan dolduracağım. 'le-emleenne cehenneme' (metin sayımı) 4 ayet: 7:18, 11:119, 32:13 (okundu), 38:85. ملأ [3/3] kapanıyor: 38:6 'el-meleu' (inkârcıların ileri gelenleri) → 38:69 'el-meleu'l-a'lâ' → 38:85 'le-emleenne' (doldurma) — aynı kök iki anlam; gloss ikisini taşıyor (okumada görüldü). تبع [2/2] kapanıyor: 38:26 've lâ tettebi'i'l-hevâ' (Dâvûd'a) → 38:85 'men tebiake' (İblîs'e uyanlar). جمع [3/3] kapanıyor: 38:73 meleklerin hepsi ('ecmaûn') → 38:82 azdırılacakların hepsi → 38:85 cehennemi dolduranların hepsi ('ecmaîn') (okumada görüldü). Aktör alanı 'cehennem'i adlı yer sayıyor. Fâsıla ن. 7 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 qasem lâmı + nûn-ı tekit (IMPF, 1S) + iki 'min'; D4 1S 1 · 2MS 2 · 3MP 1 · 3MS 1.\n◈A — A1 konuşan (1S), İblîs (2MS), uyanlar; A2 sahne: cehennem; A3 karşılık yemini.",
 86: "◇ 'qul mâ es'elukum aleyhi min ecrin ve mâ ene mine'l-mutekellifîn' — üçüncü 'qul' (65, 67, 86): ücret istemiyorum; yükümlülük uyduranlardan değilim (NEG 2). 'aleyhi min ecr' (metin sayımı) 8 ayet: 12:104, 25:57, 26:109, 26:127, 26:145, 26:164, 26:180 (okundu), 38:86. 'el-mutekellifîn' korpusta 1 ayet; كلف [1/1] — kök korpusta 8 ayet. قول [23/23] kapanıyor: sûrede 23 token, sonuncusu 'qul'. سأل [2/2]: 38:24 'bi-suâli na'cetike' (koyun istemek) → 38:86 'mâ es'elukum' (ücret istememek) (okumada görüldü). أجر [1/1]. Fâsıla ن. 10 kelime — blokun en uzunu, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 emir + iki olumsuz cümle (mâ + IMPF / mâ + isim cümlesi); D4 1S 2 · 2MP 1 · 2MS 1 · 3MS 1.\n◈A — A1 muhatap (2MS → 1S uyarıcı), dinleyenler (2MP); A3 ücretsizlik ve külfetsizlik.",
 87: "◇ 'in huve illâ zikrun li'l-âlemîn' — HASR: o ancak âlemler için bir zikir. esit2 → 81:27 oran 1,00 (TAM), 68:52 oran 0,91 (BENZER) — ikisi henüz okunmadı. 'in huve illâ zikrun li'l-âlemîn' (metin sayımı) 4 ayet: 12:104 (okundu), 38:87, 68:52, 81:27. 12:104 (okundu) 've mâ tes'eluhum aleyhi min ecrin; in huve illâ zikrun li'l-âlemîn' — tek ayet; burada iki ayete bölünmüş: ücret 38:86, zikir 38:87 (okumada görüldü, KAPATILAMAZ). ذكر [13/13] kapanıyor: 38:1 've'l-qur'âni zi'z-zikr' (açılış yemini) → … → 38:87 'zikrun li'l-âlemîn' — sûre zikirle açılıp zikirle kapanıyor (okumada görüldü). 'huve' göndergesi adlanmıyor (38:67 emsali; KAPATILAMAZ). علم [3/4]. Fâsıla ن. 5 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 olumsuz 'in' + 'illâ' (hasr) + isim cümlesi; D2 HASR; D4 3MS 1.\n◈A — A1 'o' (zamir), âlemler; A3 zikrin kapsamı.",
 88: "◇ 've le-ta'lemunne nebeehû ba'de hîn' — tekit (EMPH 2): onun haberini bir süre sonra mutlaka bileceksiniz. Sûrenin son ayeti. 've le-ta'lemunne' (metin sayımı) 2 ayet: 20:71 (okundu, Firavun'un tehdidi), 38:88; 'ba'de hîn' 1 ayet. نبأ [3/3] kapanıyor: 38:21 'nebeu'l-hasm' → 38:67 'nebeun azîm' → 38:88 'nebeehû'. حين [2/2] kapanıyor: 38:3 've lâte hîne menâs' (kurtuluş vakti değil) → 38:88 'ba'de hîn' (bir süre sonra) — sûrenin üçüncü ayeti ile son ayeti aynı kökle (okumada görüldü, KAPATILAMAZ). علم [4/4] kapanıyor; بعد [2/2]. Fâsıla ن. 4 kelime, yıldız yok.\n◈K — K1 —; K2 zaman: 'ba'de hîn' — belirsiz bir süre sonra (gelecek, IMPF); K3 —; K4 —.\n◈B — —\n◈D — D1 qasem lâmı + nûn-ı tekit (IMPF, 2MP) + zaman zarfı; D4 2MP 1 · 3MS 1.\n◈A — A1 muhataplar (2MP); A4 sûrenin kapanışı: bilinecek haber.",
}
MEAL.update(MEAL9); M.update(M9)
