# -*- coding: utf-8 -*-
"""saffat_metin_1.py — sûre 37 (Sâffât) meal ve mercekler (◇ + ◈K ◈B ◈D ◈A), ayet 1-182.
Arapça sabit YOK: kökler yalnız korpus kök biçimiyle anılır, kelime biçimleri Latin harfle.
Yeni bloklar MEALn/Mn sözlükleri olarak eklenir ve sonda MEAL/M'ye katılır.
37:1-90 2026-10-07 ortam kaybından sonra blok HTML'lerinden birebir geri alındı (okuma_37_*_*.html)."""
MEAL = {}
M = {}

MEAL1 = {
 1: 'Saf saf dizilenlere andolsun,',
 2: 'sürüp azarlayanlara,',
 3: 'zikri okuyanlara ki,',
 4: 'şüphesiz ilâhınız birdir;',
 5: 'göklerin, yerin ve ikisinin arasındakilerin Rabbi, doğuların da Rabbi.',
 6: 'Biz dünya göğünü bir süsle, yıldızlarla süsledik,',
 7: 've her azgın şeytandan korumak için.',
 8: 'Onlar yüce topluluğa kulak veremezler; her yandan atışa tutulurlar,',
 9: 'kovularak; ve onlar için kesintisiz bir azap vardır.',
 10: 'Ancak (sözden) bir kapış kapan olursa, onu delip geçen bir alev izler.',
}
M1 = {
 1: "◇ Sûre yeminle açılıyor (biçim QASEM; alan yemini yalnız 37:1'de işaretliyor). İki kelime: dişil çoğul sıfat-fiil + aynı kökten mastar ('saffan') — kök ikilemesi صفف ×2, [1,2/3]; üçüncü token henüz okunmamış ayette. Yemin edilenin kim olduğu söylenmiyor: adsız bir topluluk, yalnız edimiyle (saf olma) adlanıyor. Lafız 0, Rab 0, yıldız yok, bağ yok; fâsıla ا (A sınıfı). harf 29 → harf3 9: eski alan besmeleyi sayıyor (onarım tablosu), harf3 saymıyor.\n◈K — —\n◈B — —\n◈D — D1 yemin, kip yok; D2 qasem 've' ile; D3 kök ikilemesi: sıfat-fiil kendi mastarıyla pekiştiriliyor (mef'ûl-i mutlak, ACC 1); D4 şahıs işareti yok.\n◈A — A1 adsız topluluk (sâffât), rolü yemin nesnesi; A4 sûre açılışı.",
 2: "◇ Fâ ile ikinci yemin nesnesi; 37:1'in kalıbı birebir: dişil çoğul sıfat-fiil + aynı kökten mastar ('zecran') — kök ikilemesi زجر ×2, [1,2/3]. Biçim alanı burada QASEM yazmıyor: fâ atfı yemini sürdürüyor — tek yemin, sıralı üç nesne okunuşuyla tutarlı. İki kelime, fâsıla ا; harf 12 → harf3 11, isaret 1.\n◈K — —\n◈B — —\n◈D — D1 yeminin devamı (fâ atfı), kip yok; D3 37:1 kalıbının tekrarı (sıfat-fiil + kendi mastarı); D4 şahıs işareti yok.\n◈A — A1 ikinci adsız topluluk (zâcirât); 37:1'deki toplulukla aynı mı ayrı mı metin söylemiyor, fâ yalnız sıra veriyor.",
 3: "◇ Üçüncü yemin nesnesi ve kalıp kırılıyor: sıfat-fiilin ardından gelen artık kendi mastarı değil, başka kökten bir nesne ('zikran'). تلو [1/1] kapanıyor; ذكر [1/5]. 37:1-3: üç ayet, her biri 2 kelime, üçünde de fâsıla ا (A sınıfı) — yemin bloğu biçimce tek parça; ilk ikisi kök ikilemeli, üçüncüsü değil.\n◈K — —\n◈B — —\n◈D — D1 yeminin devamı (fâ), kip yok; D3 kalıbın ikinci yarısı değişiyor: 37:1-2'de mef'ûl-i mutlak (aynı kök), 37:3'te mef'ûl bih (zikr) — tekrar burada kesiliyor; D4 şahıs işareti yok.\n◈A — A1 üçüncü adsız topluluk (tâliyât), edimi okuma, nesnesi zikir.",
 4: "◇ Yeminin cevabı: 'inne ilâhekum le-vâhid' — inne + lâm (kip EMPH 1). Muhatap ilk kez görünüyor (2MP 1): yemin muhatapsızdı, cevap muhataplı. Üç kelime. أله [1/20], وحد [1/2]; say işareti 'vâhid' — doğru (sayı 'bir'). esmâ e_oto 0. Fâsıla د: 37:1-3'ün ا dizisinden çıkış; alan kırılma yazmıyor (komşular 37:3 ا, 37:5 ق — ölçüt iki komşunun eşitliğini istiyor).\n◈K — —\n◈B — —\n◈D — D1 haber, çift tekit (inne + lâm) — cevâb-ı kasem; D2 yemin-cevap çifti tamamlanıyor; D4 2MP 1, konuşan adlanmıyor.\n◈A — A3 konuşan adsız, muhatap 2MP; A4 yemin + cevap birimi (37:1-4) burada tamam.",
 5: "◇ 37:4'ün haberi sürüyor (NOM 2): 'Rabbu's-semâvâti ve'l-ardı ve mâ beynehumâ ve rabbu'l-meşâriq'. ربب ×2 [1,2/14] — birinci 'rabb' üç öğeye (gökler, yer, ikisinin arası), ikincisi tek öğeye (doğular, çoğul). سمو [1/2], بين [1/8]; أرض [1/1] ve شرق [1/1] kapanıyor. 7 kelime, ★★★ kaynak rab (z=5,77; başka eşik geçen yok) — 7 kelimede 2 Rab, oran temelli şişme (1020/983 ailesi; 37:5 kısa ayet değil, 7 kelime). İltifât alanı 1: 37:4 2MP → 37:5 3D; ama 3D zamirin ('beynehumâ') göndergesi gökler ve yer — konuşan ve muhatap değişmiyor: yanlış pozitif (1017 ailesi). Fâsıla ق. 🜁 L0 — gökler, yer, ara, doğular adlanıyor; tek ilişki rubûbiyet tamlaması; 'meşâriq' çoğulluğu ad düzeyinde, sayı yok; olgu evet, çıpa hayır; tarayıcı vermedi.\n◈K — K1 gökler, yer, ikisinin arası, doğular (شرق, çoğul); K2 zaman birimi yok; K3 ölçek: en büyük birim gökler-yer, 'ara' adlı ama sınırı verilmiyor; doğular çoğul, sayısız; K4 hareket fiili yok — ilişki isim tamlamasıyla (rabb).\n◈B — —\n◈D — D1 isim cümlesi, haberin devamı (bedel/ikinci haber), kip yok; D3 'rabb' tekrarı: aynı ad iki tamlamada, ikinci tamlama tek öğeye ayrılıyor; D4 3D zamir nesne göndergeli — iltifât alanı yanlış pozitif.\n◈A — —",
 6: "◇ Konuşan 1P'ye geçiyor (1P 3): 37:4-5'te adla anılan (ilâh, rabb) burada 'biz' — 'innâ zeyyennâ es-semâ'e'd-dunyâ bi-zîneti'l-kevâkib'. İltifât alanı 1 — bu kez gerçek (gönderge aynı, şahıs değişiyor; alan bunu 37:5'in 3D'si üzerinden yakalıyor). زين ×2 [1,2/2] kapanıyor (fiil zeyyennâ, II. bab + isim zîne); سمو [2/2] kapanıyor: 37:5 çoğul 'semâvât' → 37:6 tekil 'semâ'' + 'dunyâ' sıfatı; دنو [1/1], كوكب [1/1]. xref 41:12, 67:5 (aynı terkip) — henüz okunmadı. Okunmuş emsal 15:16 'zeyyennâhâ li'n-nâzırîn' (aynı fiil, aynı gök, alıcı 'bakanlar') — defter bağı yok. 6 kelime, yıldız yok. 🜁 L1 — gök + nitelik (süs) + süsün kendisi yıldızlar; süreç ve neden yok (15:16 emsali); olgu evet, çıpa hayır; tarayıcı vermedi.\n◈K — K1 en yakın gök ('dunyâ' sıfatı) ve yıldızlar (كوكب); K2 geçmiş (PERF 1); K3 ölçek 37:5'in çoğul göklerinden tek katmana iniyor; K4 düzen fiili 'zeyyene' (II. bab): özne 'biz', nesne gök, araç yıldızlar.\n◈B — —\n◈D — D1 haber, inne ile tekit ('innâ'); D2 iltifât: ad (3. şahıs) → 'biz'; D3 زين fiil + aynı kökten isim (zeyyennâ … zîne) — mm2 alanı boş (zîne harf-i cerle GEN, ACC değil); D4 1P 3.\n◈A — A3 konuşan 'biz' — 37:4-5'te üçüncü şahısla anılanın kendisi; A2 sahne gök.",
 7: "◇ 've hifzan min kulli şeytânin mârid' — 'hifzan' (ACC) 37:6'nın fiiline bağlı: süsleme ve koruma tek eylemin iki amacı, ayet sınırı cümleyi bölüyor. حفظ [1/1] ve مرد [1/1] kapanıyor; كلل [1/2], شطن [1/2]. xref 15:17 (okundu): 've hafiznâhâ min kulli şeytânin racîm' — ortak 'min kulli şeytân', fiil/mastar farkı (hafiznâ / hifzan) ve sıfat farkı (racîm / mârid). KAFİYE KIRILMASI: د, iki komşu (37:6, 37:8) ب. ★: ölçüm satırında n z=-0,79 eşik altı — ★'ı kafiye kırığı veriyor; bilanço etiketi 'n' yanlış (aday 1001), elle düzeltme: kaynak kafiye kırığı. 5 kelime.\n◈K — —\n◈B — —\n◈D — D1 haber sürüyor: mastar (ACC) önceki ayetin fiiline bağlı; D3 'min kulli' bu ayette kaynak (her şeytandan) — 37:8'de yön olarak tekrar ediyor; D4 şahıs işareti yok.\n◈A — A1 adsız cins aktör: şeytan, sıfatı 'mârid' (azgın), rolü korunulan tehdit; A2 sahne gök.",
 8: "◇ Özne şeytanlar (3MP 4). İki fiil: olumsuz V. bab 'lâ yessemme'ûn' (kulak verme çabası) + I. bab edilgen 'yuqzefûn' (atılırlar). EDİLGEN 1/2, pas z=2,52 → ★★ kaynak pas (kafiye kırığı yok, kaynak doğru); atan adlanmıyor. 'min kulli' 37:7'den tekrar: orada kaynak (her şeytan), burada yön (her yan) — كلل [2/2] kapanıyor. سمع [1/1], علو [1/1], قذف [1/1], جنب [1/1] kapanıyor; ملأ [1/2] ('el-mele'u'l-a'lâ', yüce topluluk). İltifât alanı 1: 37:6 1P → 37:8 3MP; 3MP'nin göndergesi şeytanlar — konuşan değişmiyor: yanlış pozitif (1017 ailesi). 9 kelime.\n◈K — —\n◈B — B3 tetik سمع organ anlamında değil: kulak verme eylemi (V. bab, olumsuz), öznesi şeytanlar.\n◈D — D1 olumsuz haber (NEG 1) + edilgen haber, atıfla; D3 'min kulli' kalıbının iki ardışık ayette iki işlevi (kaynak → yön); D4 3MP 4 — alan iltifâtı gönderge değişimi, yanlış pozitif.\n◈A — A1 şeytanlar (3MP, adsız cins) ve 'yüce topluluk' (adsız); atan fail adlanmıyor; A2 sahne göğün üst katı; A4 37:6'da açılan gök sahnesi sürüyor.",
 9: "◇ 'duhûran' (ACC) 37:8'in edilgen fiiline bağlı (kovulma olarak); vakf işaretinden sonra isim cümlesi: 've lehum azâbun vâsib' (haber öne alınmış). دحر [1/1] ve وصب [1/1] kapanıyor — ikisi de bu sûre için eklenen 21 kökten; عذب [1/5]. 4 kelime, yıldız yok. Azabın yeri ve zamanı adlanmıyor, yalnız süresi ('vâsib', kesintisiz).\n◈K — —\n◈B — —\n◈D — D1 mastar (ACC) + isim cümlesi (haber önde: 'lehum'); D2 tahsis sezdiren takdim — alan biçim yazmıyor (kayıt); D4 3MP 1.\n◈A — A1 şeytanlar; A2 azabın sahnesi adlanmıyor; A4 gök sahnesi sürüyor.",
 10: "◇ 'illâ men hatife'l-hatfete fe-etbe'ahû şihâbun sâqib' — istisna 37:8'in olumsuz fiiline bağlı: olumsuz + illâ yapısı ayet sınırını aşıyor; biçim HASR, kip RES 1. mm2 [3, خطف]: fiil + aynı kökten belirli ACC isim (bir kez kapma) — kök ikilemesi خطف ×2 [1,2/2] kapanıyor. تبع [1/1] (IV. bab), شهب [1/1], ثقب [1/1] kapanıyor. Çoğul şeytanlardan tekil istisna (3MS 3). Okunmuş emsal 15:18: 'illâ meni'steraqa's-sem'a fe-etbe'ahû şihâbun mubîn' — aynı iskelet (illâ men + kapma fiili + fe-etbe'ahû şihâbun + sıfat), fiil farkı (istaraqa / hatife), sıfat farkı (mubîn / sâqib); defter bağı yok, ortak dizi 'fe-etbe'ahû şihâbun' 2 kelime, nakarat3 alt sınırının altında (KAYIT). 15:16-18 ile 37:6-10 aynı sırada dört adım: süsleme → 'min kulli şeytân' koruma → 'illâ men' istisna → şihâb izler (okumada görüldü, KAPATILAMAZ). 7 kelime, yıldız yok. 🜁 L1 — alev (şihâb) + nitelik (delip geçen) + izleme işlevi; anlatı içinde, mekanizma/ölçü yok; olgu evet, çıpa hayır; tarayıcı vermedi.\n◈K — —\n◈B — —\n◈D — D1 istisna, olumsuzu önceki ayette; D2 HASR (alan) — ayet içi olumsuz yok, yapı 37:8'e dayanıyor; D3 mm2: fiil + aynı kökten 'merre' ismi (hatfe); D4 3MP → 3MS: topluluktan tekil istisna.\n◈A — A1 kapan (adsız tekil, 'men') ve izleyen alev (cansız fail); A3 konuşma yok; A4 37:6'dan beri tek fiil zincirinin uzantısı (zeyyennâ → hifzan → lâ yessemme'ûn → duhûran → illâ men); birimin kapanıp kapanmadığı 37:11 okununca.",
}
MEAL.update(MEAL1); M.update(M1)

MEAL2 = {
 11: 'Şimdi onlara sor: Yaratılışça onlar mı daha çetin, yoksa bizim yarattıklarımız mı? Biz onları yapışkan bir çamurdan yarattık.',
 12: 'Hayır, sen şaştın; onlar ise alay ediyorlar.',
 13: 'Kendilerine hatırlatıldığında hatırlamazlar (öğüt almazlar).',
 14: 'Bir âyet gördüklerinde de onu alaya alırlar.',
 15: "Ve dediler: 'Bu apaçık bir büyüden başka bir şey değil.'",
 16: "'Öldüğümüz, toprak ve kemik olduğumuz zaman mı? Gerçekten biz mi diriltileceğiz?'",
 17: "'Önceki atalarımız da mı?'",
 18: "De ki: 'Evet, hem de siz küçülüp boyun eğmiş olarak.'",
 19: 'O yalnızca tek bir haykırıştır; bir de bakarsın ki onlar bakıp duruyorlar.',
 20: "Ve dediler: 'Vay bize! Bu, din (hesap) günüdür.'",
}
M2 = {
 11: "◇ Muhatap 2MS — sûrede ilk (37:1-10'da 2MS yok): 'fe'steftihim' (X. bab, 'hüküm sor'). Soru (INTG) + emir (IMPV): 'onlar mı yaratılışça daha çetin, yoksa bizim yarattıklarımız mı' — ikinci şıkkın göndergesi adlanmıyor ('men halaqnâ'); 37:5-10'da sayılan yaratılmışlar okunuşu metinde açık değil. خلق ×3 [1,2,3/6] — sûredeki 6 tokenin 3'ü bu ayette (halqan · halaqnâ · halaqnâhum): ölçü (çetinlik) → kıyas nesnesi → insanın maddesi. شدد [1/1], طين [1/1], لزب [1/1] kapanıyor; فتي [1/2]. HAPAKS لزب (lâzib) → ★★★ kaynak hapaks z=3,28 (983 ailesi; başka eşik geçen yok). 12 kelime — 37:1-20'nin en uzunu. 🜁 L1 — madde (tîn) + nitelik (lâzib, yapışkan); aşama ve nedensellik yok (32:7, 35:11 emsali); olgu evet, çıpa hayır; tarayıcı vermedi.\n◈K — —\n◈B — B1 insan (3MP zamir, 'onlar'); B2 oluşum: tek madde adlı — yapışkan çamur; aşama yok, ara durum yok; B3 organ yok; B4 —.\n◈D — D1 emir + soru (IMPV 1, INTG 1) + haber (innâ ile tekit); D2 'em' ile karşılaştırma sorusu; D3 خلق üç kez, üç ayrı sözdizim görevinde (temyiz, sıla fiili, haber fiili); D4 2MS (emir) → 3MP (soru konusu) → 1P (yaratan) — konuşan değişmiyor, iltifât alanı 0 doğru.\n◈A — A1 konuşan 'biz', muhatap tekil (2MS, adlanmıyor), konu 3MP (adsız inkârcılar); A3 muhataba bir soru görevi veriliyor; A4 37:6-10'un gök sahnesinden insanlara geçiş — yeni birim açılıyor.",
 12: "◇ 'bel acibte ve yesharûn' — biçim IDRAB ('bel'): 2MS şaşırıyor, 3MP alay ediyor; iki fiil, iki özne, iki tepki (3 kelime). عجب [1/1] kapanıyor; سخر [1/2]. Fâsıla N — 37:12'den itibaren ن (N sınıfı); 37:6-11 ب idi (37:7 د kırığı hariç).\n◈K — —\n◈B — —\n◈D — D1 haber, IDRAB; D2 'bel' ile önceki soruya karşı yönelim; D4 2MS 2 → 3MP 2 aynı ayette: muhatap ile konu yan yana; konuşan değişmiyor.\n◈A — A1 muhatap (2MS) ve inkârcılar (3MP) karşı tepkilerle; A3 konuşma yok, anlatıcı iki tutumu koyuyor.",
 13: "◇ 've izâ zukkirû lâ yezkurûn' — aynı kök iki çatıda: II. bab edilgen (hatırlatıldıklarında) / I. bab etken olumsuz (hatırlamazlar). ذكر ×2 [2,3/5] (37:3 zikran'dan sonra). EDİLGEN 1/2, pas z=2,52 → ★★ kaynak pas (kafiye kırığı yok, kaynak doğru); hatırlatan fail adlanmıyor. 4 kelime.\n◈K — —\n◈B — —\n◈D — D1 şart ('izâ') + olumsuz cevap (NEG 1); D3 aynı kök: dışarıdan verilen (II. bab edilgen) / içeride olmayan (I. bab olumsuz); D4 3MP 4.\n◈A — A1 inkârcılar (3MP); hatırlatan adlanmıyor; A4 37:12'deki tutum alışkanlık olarak açılıyor.",
 14: "◇ 've izâ ra'ev âyeten yestesharûn' — 37:13'ün kalıbı: 've izâ' + PERF fiil + IMPF cevap; iki ardışık ayet aynı iskelet. سخر [2/2] kapanıyor: 37:12 yesharûn (I. bab) → 37:14 yestesharûn (X. bab, alaya alma/alaya çağırma) — aynı kök, iki bab, iki ayet arayla. رأي [1/5]; أيي [1/1] kapanıyor (924 araç notu: أيي ipliği eyyuhâ'yı âyetle birleştirebiliyor — burada token 'âyeten', ad). 4 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 şart + cevap (IMPF); D3 37:13 ile paralel kalıp ('ve izâ' + PERF + IMPF); سخر'ın I. → X. bab yükselişi; D4 3MP 4.\n◈A — A1 inkârcılar; A4 alışkanlık dizisi (37:12-14) sürüyor.",
 15: "◇ Konuşma açılıyor: 've qâlû' — 'in hâzâ illâ sihrun mubîn' (biçim DIKKAT + HASR; NEG 1 · RES 1). قول [1/24]; سحر [1/1] kapanıyor; بين [2/8]: 37:5'te 'ara' (beynehumâ), burada 'apaçık' (mubîn) — aynı kök, iki anlam. esmâ: mubîn e_oto 1 → e_el 'degil' (sihrin sıfatı); §4.3 mühür EVET ama geçersiz. Kalıp ('in hâzâ illâ sihrun mubîn') harekesiz metin sayımıyla korpusta 5 ayet: 5:110, 6:7, 11:7, 34:43, 37:15 — okunmuş 11:7 ve 34:43; nakarat3 tanımı sûre içi, xref boş, defter bağı yok (KAYIT; metin sayımı, defter alanı değil). 6 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 haber, olumsuz + istisna (in … illâ = hasr); D2 HASR + işaret zamiri (DIKKAT); D3 بين'in ikinci anlamı; D4 3MP 2 — konuşma alıntısı açılıyor.\n◈A — A1 inkârcılar konuşan (qâlû); A3 hitap edilen yok, 'bu' (hâzâ) göndergesi 37:14'teki âyet; A4 alıntı başlıyor (37:15-17).",
 16: "◇ Alıntı sürüyor, inkârcılar kendi ağızlarından (1P 5): 'e-izâ mitnâ ve kunnâ turâben ve izâmen e-innâ le-meb'ûsûn' — iki INTG + EMPH. Sıra: ölüm → toprak ve kemik → diriliş sorusu. موت [1/4], كون [1/20], ترب [1/2], عظم [1/6], بعث [1/2]. nakarat3: kalıp ('e-izâ mâte kâne turâb izâm e-inne', 6 kelime) sûre içinde 2 ayet — eşi 37:53 (defterden koşuldu; henüz okunmadı). esit2 23:82 (BENZER, okundu: 'qâlû' + aynı soru) · 37:53; xref 23:35, 23:82 (okundu), 37:53, 56:47. İltifât alanı 1: 37:15 3MP → 37:16 1P — alıntı içi 'biz', gönderge aynı topluluk, anlatıcı değişmiyor (1017 ailesi). EDİLGEN 1/2, pas z=2,52 → ★★ kaynak pas — ama edilgen sayılan fiil 'mitnâ': morfoloji 'mâte'nin 'mit-' biçimini burada PASS etiketliyor; aynı biçim 19:23 ve 19:66'da etken etiketli (aday 1037; araç açığı, metin hakkında kanıt değil). 'meb'ûsûn' edilgen ortaç, fiil sayımına girmiyor. 7 kelime. 🜁 L1 — ölüm → toprak + kemik: aşamalar adlı, itirazın içinde; nedensellik yok (36:78 L0, 35:11 L1 emsali); olgu evet, çıpa hayır; tarayıcı vermedi.\n◈K — —\n◈B — B2 aşama sırası: ölüm → toprak ve kemik (ara durum adlı) → diriliş (soru); B3 kemik (عظم) organ listesinde yok, malzeme olarak anılıyor; B4 ölüm verilmiş, diriliş sorgulanıyor.\n◈D — D1 çift soru (e-izâ … e-innâ), ikincisi inne + lâm ile tekitli; D2 istifhâm-ı inkârî; D4 1P 5 — alıntı içi 'biz', iltifât alanı yanlış pozitif.\n◈A — A1 inkârcılar konuşan; A3 kime söylendiği adlanmıyor; A4 alıntı sürüyor.",
 17: "◇ 'e-ve âbâunâ'l-evvelûn' — 2 kelime, soru (INTG). أبو [1/5], أول [1/5]. esmâ: evvel e_oto 1 → e_el 'degil' (ataların sıfatı); ölçüm satırı 'esmâ yok' yazıyor, esma_kayit yazıyor — 1022 ayrışması yine (36:79 evvel emsali). §4.3 mühür EVET, geçersiz. esit2 56:48 TAM — henüz okunmadı. Yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 soru, eksiltili (37:16'nın fiili takdir ediliyor); D4 1P 1 ('atalarımız').\n◈A — A1 inkârcılar ve 'ilk atalar' (adsız, geçmiş kuşak); A4 alıntı burada kapanıyor.",
 18: "◇ Cevap emirle: 'qul na'am ve entum dâhirûn' — 2MS'ye 'de ki', içerik 2MP'ye: 'evet, hem de siz boyun eğmiş olarak' (hâl cümlesi). قول [2/24]; دخر [1/1] kapanıyor. İltifât alanı 1: 37:16-17 1P → 37:18 2 — alıntı sınırı/konuşma sırası değişimi (1017 ailesi), aynı konuşanda şahıs dönüşü değil. 4 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 emir (IMPV) + cevap edatı 'na'am' + hâl cümlesi; D4 2MS (emir alan) → 2MP (cevabın muhatabı): iki ayrı muhatap tek ayette.\n◈A — A1 konuşan (adlanmıyor, 'de' emrini veren), aracı 2MS, muhatap inkârcılar; A3 37:16-17 sorusuna cevap; A4 soru-cevap birimi (37:15-18).",
 19: "◇ 'fe-innemâ hiye zecretun vâhidetun fe-izâ hum yenzurûn' — 'innemâ' (biçim alanı HASR yazmıyor: 924 araç notu, sûre 36'daki 36:11, 36:82 emsali). زجر [3/3] kapanıyor: 37:2 'ez-zâcirâti zecran' ×2 → 37:19 'zecre' — yemin nesnesinin edimi burada diriliş haykırışının adı. وحد [2/2] kapanıyor: 37:4 'ilâhukum le-vâhid' → 37:19 'zecretun vâhide' — 'bir' iki kez, biri ilâhın, biri haykırışın sıfatı (okumada görüldü, KAPATILAMAZ). say 'vâhide' doğru. نظر [1/5]. 'fe-izâ hum' + IMPF ani sonuç. İltifât alanı 1: 37:18 2 → 37:19 3 — cevaptan anlatıya dönüş (1017 ailesi). 7 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 haber, 'innemâ' ile sınırlama (biçim alanı boş — araç açığı); D2 fücâiyye 'izâ' (ani sonuç); D3 زجر ve وحد sûre başındaki iki ayetle aynı kökler; D4 3FS (zecre) + 3MP.\n◈A — A1 inkârcılar (bakakalanlar); haykıranın kim olduğu adlanmıyor; A2 sahne değişiyor: diriliş anı; A4 dünyadaki itirazdan diriliş sahnesine geçiş.",
 20: "◇ 've qâlû yâ veylenâ hâzâ yevmu'd-dîn' — nidâ (VOC) + işaret (DIKKAT): diriltilenlerin sözü, geçmiş kipte (PERF). قول [3/24], يوم [1/5], دين [1/2]. 'yâ veylenâ' harekesiz metin sayımıyla 3 ayet: 21:97, 36:52, 37:20 — 36:52'de de diriliş anında, 'qâlû' ile (2 kelime, nakarat3 alt sınırının altında; KAYIT). 37:15'te 'hâzâ' büyüydü, burada 'hâzâ' din günü — aynı konuşanlar, aynı işaret zamiri (okumada görüldü). 5 kelime, yıldız yok.\n◈K — K1 gök cismi yok; K2 zaman birimi 'yevm' — adlı bir gün (din günü), konuşanlar için şimdiki; K3 —; K4 —.\n◈B — —\n◈D — D1 nidâ + isim cümlesi; D2 nidâ, işaret zamiriyle hüküm; D4 alıntı içi 1P ('veylenâ') + 3MP (qâlû).\n◈A — A1 diriltilen inkârcılar konuşan; A2 sahne din günü; A3 kendilerine hitap (nidâ); A4 diriliş sahnesi sürüyor.",
}
MEAL.update(MEAL2); M.update(M2)

MEAL3 = {
 21: "'Bu, sizin yalanlayıp durduğunuz ayrım (hüküm) günüdür.'",
 22: "'Zulmedenleri, eşlerini ve tapmakta olduklarını toplayın —",
 23: "Allah'ı bırakıp (taptıklarını) — ve onları cehennemin yoluna yöneltin.",
 24: "Durdurun onları; çünkü onlar sorguya çekilecekler.'",
 25: "'Size ne oluyor ki birbirinize yardım etmiyorsunuz?'",
 26: 'Hayır, onlar bugün teslim olmuşlardır.',
 27: 'Birbirlerine dönüp soruşurlar.',
 28: "Dediler: 'Siz bize sağ yandan (güç ve güvenle) gelirdiniz.'",
 29: "Dediler: 'Hayır, siz zaten inananlar değildiniz.",
 30: 'Bizim size karşı hiçbir gücümüz yoktu; aksine siz azgın bir topluluktunuz.',
}
M3 = {
 21: "◇ 'hâzâ yevmu'l-fasli'llezî kuntum bihî tukezzibûn' — 37:20'nin hemen ardından ikinci 'hâzâ yevmu …': 37:20 'yevmu'd-dîn' (diriltilenlerin sözü), 37:21 'yevmu'l-fasl' (cevap, 2MP) — 'hâzâ yevm' iki kelime, nakarat3 alt sınırının altında (KAYIT). Konuşan adlanmıyor; muhatap 2MP 4 (inkârcılar). يوم [2/5], كون [2/20]; فصل [1/1] kapanıyor; كذب [1/3] (II. bab, yalanlama). xref 78:17 (aynı terkip 'yevme'l-fasl … kâne') — henüz okunmadı. 7 kelime, yıldız yok.\n◈K — K1 gök cismi yok; K2 zaman birimi 'yevm' — adlı gün (ayrım günü), konuşulan an için şimdiki; geçmişteki yalanlama (kuntum … tukezzibûn, sürekli geçmiş) ile karşılaştırılıyor; K3 —; K4 —.\n◈B — —\n◈D — D1 isim cümlesi (işaret + haber) + sıla; D2 işaret zamiri (DIKKAT); D3 37:20'deki 'hâzâ yevmu' kalıbının tekrarı, isim değişiyor (dîn → fasl); D4 2MP 4 — konuşma sırası değişiyor (37:20 inkârcılar 1P, 37:21 onlara hitap), iltifât alanı 0.\n◈A — A1 konuşan adsız, muhatap inkârcılar; A2 sahne din/ayrım günü; A3 37:20'deki nidâya cevap; A4 diriliş sahnesi sürüyor.",
 22: "◇ Emir 2MP'ye: 'uhşurû' (toplayın) — emri alanlar adlanmıyor. Toplanacaklar üç grup: 'zulmedenler' + 'eşleri' + 'tapmakta oldukları'. حشر [1/1], زوج [1/1] kapanıyor; ظلم [1/3], كون [3/20], عبد [1/14]. say işareti 'zevc' — yanlış pozitif (sayı değil, 'eşler/benzerler'; 1004/1005 ailesi, 36:36, 36:56 emsali). Cümle ayet sınırını aşıyor: tapılanların tanımı 37:23 'min dûni'llâh' ile bitiyor. 7 kelime, yıldız yok.\n◈K — —\n◈B — B1 tetik زوج üreme/oluşum anlamında değil: 'ezvâc' — zalimlerin eşleri ya da benzerleri; canlı sınıfı adlanmıyor.\n◈D — D1 emir (IMPV) + üç nesne; D3 'kânû ya'budûn' sürekli geçmiş (37:21 'kuntum tukezzibûn' ile aynı yapı); D4 2MP 2 (emir alanlar) · 3MP 7 (toplananlar) — üç taraf: konuşan, emir alan, hakkında emir verilen.\n◈A — A1 emir veren (adsız), emri alanlar (adsız 2MP), zalimler + eşleri + tapılanlar; A2 sahne toplanma; A3 hitap inkârcılardan emir alanlara geçiyor.",
 23: "◇ Sûrede ilk lafız: 'min dûni'llâh' (37:1-22 lafız 0) — tapılanların tanımı, olumsuz bağlam ('Allah'tan başka'). ★★ kaynak allah z=2,33 (7 kelimede 1 lafız; başka eşik geçen yok). أله [2/20] (37:4 ilâh → 37:23 lafız). Sonra ikinci emir: 'fe'hdûhum ilâ sırâti'l-cahîm' — 'yol göstermek' fiili cehennemin yoluna: هدي [1/3], صرط [1/2], جحم [1/6]; دون [1/2]. xref 3:101 (lafız + hidâyet + sırât; orada 'sırât-ı müstakîm' terkibiyle) — henüz okunmadı. Fâsıla م, sınıfı N. 7 kelime.\n◈K — —\n◈B — —\n◈D — D1 37:22 cümlesinin devamı + emir (IMPV); D3 هدي fiili alışılmış nesnesinin karşıtıyla (cahîmin yolu) — kök kendi ters yönünde kullanılıyor (okumada görüldü); D4 2MP 2 · 3MP 1.\n◈A — A1 emir alanlar ve sevk edilenler; A2 sahne cahîme giden yol.",
 24: "◇ 've qifûhum innehum mes'ûlûn' — üçüncü emir (durdurun), gerekçe inne ile: 'onlar sorguya çekilecek'. وقف [1/1] kapanıyor; سأل [1/3] ('mes'ûlûn', edilgen ortaç — fiil sayımına girmiyor, edilgen alanı 0). Emir dizisi: topla (37:22) → yönelt (37:23) → durdur (37:24); vakf işareti emirle gerekçeyi ayırıyor. 3 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 emir + tekitli gerekçe (inne); D3 emir zinciri üç fiil (I. bab); D4 2MP 2 · 3MP 2.\n◈A — A1 emir alanlar, durdurulanlar; sorgulayan adlanmıyor; A4 toplama sahnesinin üçüncü adımı.",
 25: "◇ 'mâ lekum lâ tenâsarûn' — soru + olumsuz (INTG 1 · NEG 1), VI. bab: karşılıklı yardımlaşma. Hitap 2MP 3 — durdurulanlara dönük; soranın kimliği adlanmıyor. نصر [1/3]. nakarat3 'mâ lekum lâ' (3 kelime) sûre içi 2 ayet — eşi 37:92 (defterden koşuldu; henüz okunmadı); süzgeç GEÇMEZ (3 kelime, 2 ayet). 4 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 istifhâm (kınama), olumsuz IMPF; D3 VI. bab — eylem karşılıklı, ve olmayan bir karşılıklılık soruluyor; D4 2MP 3: 37:22-24'te 3MP anılanlara şimdi doğrudan hitap.\n◈A — A1 durdurulanlar muhatap; konuşan adsız; A3 soru cevapsız (37:26 anlatıcı cümlesi).",
 26: "◇ 'bel humu'l-yevme musteslimûn' — biçim IDRAB ('bel'): yardımlaşma değil, teslimiyet. 'el-yevm' (bugün): يوم [3/5]; سلم [1/8] (X. bab ortaç, 'teslim olmuş'). İltifât alanı 1: 37:25 2MP → 37:26 3MP — gönderge aynı topluluk (hitaptan gaybete); ama 37:25'in konuşanı adlanmıyor, 37:26'nın konuşanı anlatıcı da olabilir — iltifât mı alıntı sınırı mı ayırt edilemiyor (1017 ailesi, KAPATILAMAZ). 4 kelime, yıldız yok.\n◈K — K1 —; K2 'el-yevm' — anlatının şimdisi (din günü içi); K3 —; K4 —.\n◈B — —\n◈D — D1 isim cümlesi, IDRAB; D2 'bel' sûrede ikinci kez (37:12'den sonra); D4 2MP → 3MP, gönderge aynı.\n◈A — A1 durdurulanlar (3MP); A3 soru (37:25) cevapsız kalıyor, yerine durum bildiriliyor; A4 sahne sürüyor.",
 27: "◇ 've aqbele ba'duhum alâ ba'din yetesâelûn' — بعض ×2 [1,2/4] (birbirlerine), VI. bab 'yetesâelûn' (karşılıklı soruşma). سأل [2/3]: 37:24 'mes'ûlûn' (sorgulanacaklar, edilgen) → 37:27 'yetesâelûn' (birbirlerine soruyorlar, karşılıklı) — aynı kök, sorgulanandan soruşana. 37:25 'tenâsarûn' (VI. bab, olumsuz) ile 37:27 'yetesâelûn' (VI. bab, olumlu): karşılıklı yardım yok, karşılıklı soru var (okumada görüldü). قبل [1/5]. nakarat3 kalıbı (5 kelime, tür TAM — ayetin tamamı) sûre içi 2 ayet: eşi 37:50 (defterden koşuldu; henüz okunmadı); esit2 37:50 TAM · 52:25 TAM · 68:30 BENZER — henüz okunmadı. 5 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 haber (PERF + IMPF hâl); D3 بعض ikilemesi — karşılıklılık hem sözcükle (ba'd … ba'd) hem babla (VI.) kuruluyor; D4 3MP 3 · 3MS 1.\n◈A — A1 toplananlar kendi aralarında; A3 konuşma açılıyor (37:28-30 alıntıları); A4 karşılıklı konuşma birimi başlıyor.",
 28: "◇ Birinci ses: 'qâlû innekum kuntum te'tûnenâ ani'l-yemîn' — konuşan 1P ('bize'), muhatap 2MP ('siz'): biri ötekini suçluyor. يمن [1/2] ('sağ yan'; gloss: sağ el, sağ yan — 'güç/yemin' okunuşları gloss'ta yok, yalnız yön). أتي [1/3], قول [4/24], كون [4/20]. xref 40:50 (qâle · kâne · etâ) — henüz okunmadı. 6 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 haber, inne ile tekit + sürekli geçmiş ('kuntum te'tûne'); D4 alıntı içi 1P + 2MP, çerçeve 3MP (qâlû) — üç şahıs tek ayette, iltifât alanı 0.\n◈A — A1 konuşanlar: toplananların bir kesimi (adlanmıyor; 'bize gelirdiniz' diyenler — izleyenler okunuşu metinde açık değil); muhatap öteki kesim; A3 suçlama; A4 karşılıklı konuşmanın ilk sırası.",
 29: "◇ İkinci ses: 'qâlû bel lem tekûnû mu'minîn' — biçim IDRAB ('bel'), olumsuz geçmiş (lem + IMPF). esmâ: mu'min e_oto 1 → e_el 'degil' (insanların sıfatı); §4.3 mühür EVET, geçersiz (ölçüm satırı 'MÜHÜRSÜZ' yazıyor: ölçüm alanının mühür tanımı §4.3 değil). قول [5/24], كون [5/20], أمن [1/6]. 5 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 IDRAB + olumsuz kâne; D2 'bel' — 37:28'deki suçlamayı reddederek yön değiştiriyor; D4 alıntı içi 2MP (suçlayanlar artık muhatap).\n◈A — A1 suçlananlar konuşuyor (cevap veren taraf); A3 37:28'e cevap; A4 karşılıklı konuşma sürüyor.",
 30: "◇ Cevap sürüyor: 've mâ kâne lenâ aleykum min sultân, bel kuntum qavmen tâğîn' — olumsuz (NEG 1) + IDRAB: 'size karşı yetkimiz yoktu; siz azgın bir kavimdiniz'. 37:29-30 iki ardışık 'bel' (IDRAB) — 37:1-30'da IDRAB alanı 4 ayet: 12, 26, 29, 30 (ölçüm satırlarından). كون ×2 [6,7/20] (kâne / kuntum); سلط [1/2], قوم [1/6]; طغي [1/1] kapanıyor. 10 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 olumsuz + IDRAB; D3 كون iki kez: 'bizim için yoktu' / 'siz … idiniz' — sorumluluk aynı fiille bir taraftan öbürüne aktarılıyor; D4 1P ('lenâ') + 2MP ('aleykum', 'kuntum').\n◈A — A1 suçlanan taraf konuşuyor; A3 37:28 suçlamasına ikinci cevap cümlesi; A4 konuşmanın nerede bittiği 37:31 okununca.",
}
MEAL.update(MEAL3); M.update(M3)

MEAL4 = {
 31: 'Rabbimizin sözü üzerimize hak oldu; biz (azabı) tadacağız.',
 32: "Sizi azdırdık; çünkü biz de azgındık.'",
 33: 'O gün onlar azapta ortaktırlar.',
 34: 'Biz suçlulara işte böyle yaparız.',
 35: "Onlara 'Allah'tan başka ilâh yoktur' denildiğinde büyüklenirlerdi,",
 36: "ve 'Deli bir şair için ilâhlarımızı mı bırakacağız?' derlerdi.",
 37: 'Hayır, o hakkı getirdi ve gönderilmiş elçileri doğruladı.',
 38: 'Siz elbette o acıklı azabı tadacaksınız;',
 39: 'yaptıklarınızdan başkasıyla cezalandırılmayacaksınız —',
 40: "Allah'ın ihlâsa erdirilmiş kulları müstesna.",
}
M4 = {
 31: "◇ Cevap veren taraf sürüyor (1P 3): 'fe-haqqa aleynâ qavlu rabbinâ, innâ le-zâiqûn' — 'Rabbimiz' konuşanların ağzında. ★★★ kaynak rab z=3,23 (6 kelimede 1 Rab; başka eşik geçen yok) — kısa ayet oran şişmesi (1020 ailesi). ربب [3/14], قول [6/24]; حقق [1/2], ذوق [1/2]. 'innâ le-zâiqûn' (biz tadacağız, inne + lâm + ortaç) — 37:38'de aynı yapı 2MP'ye dönecek ('innekum le-zâiqû'). xref 28:63 (hakk · qavl · rabb) — henüz okunmadı. 6 kelime.\n◈K — —\n◈B — —\n◈D — D1 haber (PERF) + tekitli haber (inne + lâm, EMPH 1); D3 'zâiq' ortacı — eylem gelecekte, biçim isim; D4 alıntı içi 1P + 3MS (qavl).\n◈A — A1 suçlanan taraf; 'Rab' onların ağzında, kendileri hakkındaki hükmün sahibi; A3 37:28-30 cevabının devamı; A4 alıntı sürüyor.",
 32: "◇ 'fe-ağveynâkum innâ kunnâ ğâvîn' — غوي ×2 [1,2/2] kapanıyor: IV. bab 'ağveynâ' (azdırdık) + I. bab ortaç 'ğâvîn' (azgınlar) — etki ve hâl aynı kökle; azdıran kendini de azgın sayıyor. كون [8/20]. 4 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 haber + inne'li gerekçe; D3 kök ikilemesi: geçişli (IV.) / durum (ortaç) — 'sizi azdırdık çünkü biz azgındık'; D4 1P 5 · 2MP 1.\n◈A — A1 suçlanan taraf konuşuyor; A3 37:28 suçlamasının kısmen kabulü (37:29-30 reddinden sonra); A4 alıntı burada kapanıyor (37:33 anlatıcı).",
 33: "◇ Anlatıcı sesi: 'fe-innehum yevme'izin fi'l-azâbi muşterikûn' — iki taraf (suçlayan ve suçlanan) azapta ortak. يوم [4/5] ('yevme'izin'); عذب [2/5]; شرك [1/1] kapanıyor — gloss 'ortak koşma' (baskın lemma şirk), burada 'ortak olan' (VIII. bab ortaç, 'muşterik'): aynı kökün tanrı-ortaklığı anlamında değil (1015/987 gloss ailesine not). İltifât alanı 1: 37:32 1P → 37:33 3MP — alıntıdan anlatıya geçiş (1017 ailesi). 5 kelime, yıldız yok.\n◈K — K1 —; K2 'yevme'izin' (o gün) — ertelenmiş gün, anlatıda şimdi; K3 —; K4 —.\n◈B — —\n◈D — D1 tekitli isim cümlesi (inne); D3 شرك'in ikinci anlamı; D4 alıntı sınırı — iltifât alanı yanlış pozitif.\n◈A — A1 iki taraf tek grup ('onlar'); A3 anlatıcı tartışmayı tek hükümle kapatıyor; A4 37:27'de açılan karşılıklı konuşma birimi kapanıyor.",
 34: "◇ 'innâ kezâlike nef'alu bi'l-mucrimîn' — konuşan 'biz' (1P 2), genelleme: 'suçlulara böyle yaparız'. فعل [1/2]; جرم [1/1] kapanıyor. esit2 77:18 BENZER — henüz okunmadı. İltifât alanı 1: 37:33 3MP (onlar) → 37:34 1P (biz) — gönderge farklı (inkârcılar → konuşan), anlatıcı kendini 'biz' diye anıyor; aynı göndergede şahıs dönüşü değil, iltifât sayılması tartışmalı (1017 ailesi). 4 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 tekitli haber, IMPF (genel geçer); D2 'kezâlike' — tekil vakadan kurala; D4 1P 2.\n◈A — A1 konuşan 'biz', hakkında konuşulan suçlular (genel sınıf); A4 sahne vakasından genel hükme geçiş.",
 35: "◇ Gerekçe (inne): 'innehum kânû izâ qîle lehum lâ ilâhe illa'llâhu yestekbirûn' — sûrenin ikinci lafzı (37:23'ten sonra), tevhid cümlesinin içinde, alıntılanmış söz olarak. Biçim HASR (lâ … illâ). Kalıp ('lâ ilâhe illa'llâh') harekesiz metin sayımıyla korpusta 2 ayet: 37:35, 47:19 (henüz okunmadı); 'lâ ilâhe illâ huve' vb. varyantlar sayılmadı. أله ×2 [3,4/20] (ilâh + lafız). كبر [1/1] kapanıyor (X. bab, büyüklenme); كون [9/20], قول [7/24]. EDİLGEN 1/3: 'qîle' (denildiğinde) — söyleyen adlanmıyor; ★ kaynak pas z=1,57 (kaynak doğru). İltifât alanı 1: 37:34 1P → 37:35 3MP — gönderge değişimi (1017). 10 kelime. Lafız z=1,47 eşik altı.\n◈K — —\n◈B — —\n◈D — D1 tekitli haber + şart ('izâ') + alıntı (tevhid cümlesi) + IMPF cevap; D2 HASR alıntı içinde; D3 أله aynı cümlede cins ad (ilâh) ve lafız; D4 3MP 6.\n◈A — A1 suçlular; söyleyen adsız (edilgen); A3 alıntı içinde alıntı: başkasının sözü ve onlara verilen tepki; A4 dünyadaki geçmişe dönüş (kânû).",
 36: "◇ 've yeqûlûne e-innâ le-târikû âlihetinâ li-şâ'irin mecnûn' — soru (INTG) + tekit (EMPH): 'ilâhlarımızı bırakacak mıyız'. أله [5/20]: 37:35 'lâ ilâhe illa'llâh' → 37:36 'âlihetinâ' (çoğul) — aynı kök, iki ayet arayla tekil olumsuz → çoğul iyelikli (okumada görüldü). شعر [1/1] kapanıyor; جنن [1/4], ترك [1/5], قول [8/24]. 6 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 istifhâm-ı inkârî (e-innâ … le-); D3 أله tekil/çoğul karşıtlığı; D4 alıntı içi 1P ('biz', 'ilâhlarımız') + 3MP çerçeve.\n◈A — A1 suçlular konuşan; hakkında konuşulan 'deli bir şair' (adlanmıyor); A3 tevhid sözüne cevap; A4 geçmişteki konuşma.",
 37: "◇ 'bel câe bi'l-haqqi ve saddeqa'l-murselîn' — biçim IDRAB: 37:36'daki nitelemeyi reddediyor. 37:1-37'de IDRAB alanı 5 ayet: 12, 26, 29, 30, 37 (ölçüm satırlarından). حقق [2/2] kapanıyor: 37:31 'haqqa qavlu rabbinâ' (hüküm gerçekleşti, konuşanlar suçlular) → 37:37 'bi'l-haqq' (getirilen hak, anlatıcı) — aynı kök iki ağızda. صدق [1/4], رسل [1/8], جيأ [1/2]. 3MS 2 — özne 37:36'daki 'şair', adı yok. 5 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 haber, IDRAB; D2 'bel' ile reddiye; D4 3MS (getiren).\n◈A — A1 getiren (adsız tekil, 37:36'da 'şair' denen), önceki elçiler (murselîn, adsız); A3 anlatıcı cevabı; A4 alıntıdan anlatıcı yargısına.",
 38: "◇ Hitap: 'innekum le-zâiqu'l-azâbi'l-elîm' — 37:31 'innâ le-zâiqûn' (biz tadacağız, suçluların ağzında) → 37:38 'innekum le-zâiqû' (siz tadacaksınız, onlara hitap): aynı yapı (inne + lâm + ortaç), 1P → 2MP. ذوق [2/2] ve ألم [1/1] kapanıyor; عذب [3/5]. İltifât alanı 1: 37:37 3MS → 37:38 2MP; gönderge açısından 37:35-36'nın 3MP'si (suçlular) burada 2MP — gaybetten hitaba, gönderge aynı: gerçek iltifât (alanın karşılaştırdığı komşu ise 37:37'nin 3MS'i). Fâsıla م, N sınıfı. 4 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 tekitli haber (inne + lâm); D2 iltifât (3MP → 2MP, aynı gönderge); D3 37:31 kalıbının şahıs değiştirerek dönüşü; D4 2MP 1.\n◈A — A1 suçlular muhatap; konuşan adsız; A3 doğrudan hitap; A4 hüküm sahnesine dönüş.",
 39: "◇ 've mâ tuczevne illâ mâ kuntum ta'melûn' — biçim HASR (mâ … illâ): karşılık yalnız yapılanla. EDİLGEN 1/3 'tuczevne' (karşılık verileceksiniz) — veren adlanmıyor; ★ kaynak pas z=1,57 (doğru). جزي [1/6], عمل [1/4], كون [10/20]. 6 kelime.\n◈K — —\n◈B — —\n◈D — D1 olumsuz + istisna (hasr); D3 karşılık (جزي) ve amel (عمل) eşitleniyor; D4 2MP 6.\n◈A — A1 suçlular muhatap; karşılık veren adsız; A4 hüküm sürüyor.",
 40: "◇ 'illâ ibâda'llâhi'l-muhlesîn' — istisna: 37:38-39'un 2MP hükmünden 'Allah'ın ihlâsa erdirilmiş kulları' ayrılıyor (biçim HASR, kip RES). 'muhlas' edilgen ortaç (IV. bab) — ihlâsı verilen; fiil olmadığı için edilgen alanı 0. عبد [2/14], خلص [1/5], أله [6/20]. ★★★ kaynak allah z=4,47 — 4 kelimede 1 lafız, kısa ayet şişmesi (1012 ailesi). nakarat3 (defterden koşuldu): 4 kelimelik 'illâ ibâda'llâhi'l-muhlesîn' tür TAM, sûre içi 4 ayet: 40, 74, 128, 160; 3 kelimelik 'ibâda'llâhi'l-muhlesîn' 5 ayet: + 169 — eşlerin hepsi henüz okunmadı. esit2 37:74, 37:128, 37:160 TAM, 37:169 BENZER; xref ayrıca 39:2, 39:11, 98:5 — henüz okunmadı. Lafız 37:35'ten sonra sûrede üçüncü.\n◈K — —\n◈B — —\n◈D — D1 istisna (önceki ayetin hasrına bağlı, ayet sınırını aşıyor); D2 HASR; D3 ilk nakarat — sûre içinde dört kez tam tekrar edecek kalıbın ilk geçişi (defter bağı); D4 şahıs işareti yok — 2MP hitaptan şahıssız ad tamlamasına.\n◈A — A1 'Allah'ın kulları' (adsız topluluk, sıfatı muhlas); A3 hitap dışı tutulan grup; A4 suçlular sahnesinden karşı gruba geçiş — birimin yönü 37:41 okununca.",
}
MEAL.update(MEAL4); M.update(M4)

MEAL5 = {
 41: 'İşte onlar için bilinen bir rızık vardır:',
 42: 'meyveler; ve onlar ağırlanırlar,',
 43: 'nimet cennetlerinde,',
 44: 'karşılıklı tahtlar üzerinde.',
 45: 'Pınardan doldurulmuş bir kadeh aralarında dolaştırılır —',
 46: 'bembeyaz, içenlere lezzet veren;',
 47: 'onda ne bir sersemletme vardır, ne de onlar ondan sarhoş olurlar.',
 48: 'Yanlarında bakışlarını (eşlerine) hasretmiş, iri gözlü (eşler) vardır;',
 49: 'sanki onlar saklı (korunmuş) yumurtalardır.',
 50: 'Derken birbirlerine dönüp soruşurlar.',
}
M5 = {
 41: "◇ 'ulâ'ike lehum rizqun ma'lûm' — 37:40'ta ayrılan 'ihlâsa erdirilmiş kullar'a işaret (ulâ'ike): sahne suçlulardan onlara geçiyor. رزق [1/1] kapanıyor; علم [1/7] ('ma'lûm', edilgen ortaç: bilinen, belirlenmiş). İltifât alanı 1: son şahıslı ayet 37:39 (2MP, suçlular) → 37:41 3MP (muhlas kullar) — gönderge farklı, konuşan değişmiyor (1017 ailesi). 4 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 isim cümlesi (haber önde: 'lehum'); D2 işaret zamiri (ulâ'ike) — 37:40'a bağlanma; D4 3MP 1, iltifât alanı yanlış pozitif.\n◈A — A1 muhlas kullar (adsız topluluk); A2 sahne cennete dönüyor (adı 37:43'te); A4 yeni birim açılıyor: 37:22-39 suçlular sahnesinin karşı paneli.",
 42: "◇ 'fevâkihu ve hum mukramûn' — rızkın ilk açılımı: meyveler; ardından durum: ağırlanırlar (IV. bab edilgen ortaç). فكه [1/1], كرم [1/1] kapanıyor. 3 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 bedel (fevâkih, 37:41'in rızkı) + isim cümlesi; D3 ağırlayan adlanmıyor (ortaç); D4 3MP 1.\n◈A — A1 muhlas kullar; ağırlayan adsız; A4 cennet sahnesi sürüyor.",
 43: "◇ 'fî cennâti'n-na'îm' — mekân adlanıyor: nimet cennetleri. جنن [2/4]: 37:36 'mecnûn' (deli, suçluların ağzında) → 37:43 'cennât' — aynı kök, iki anlam (okumada görüldü). نعم [1/3] ('na'îm', nimet). esit2 56:12 TAM — henüz okunmadı. 3 kelime, yıldız yok. ◈B: §8 S1 düzeltmesinin ilk etkisi — نعم artık yalnız 'davar' lemmasıyla tetikliyor; burada nimet (na'îm) olduğu için ◈B tetiği yok (eski listeyle 'canlı türü' tetiği verirdi).\n◈K — —\n◈B — —\n◈D — D1 yer zarfı (önceki cümleye bağlı); D3 جنن'in ikinci anlamı; D4 şahıs işareti yok.\n◈A — A2 sahne adı: cennât (nimet cennetleri); A4 sahne sürüyor.",
 44: "◇ 'alâ sururin mutekâbilîn' — tahtlar üzerinde, karşı karşıya. قبل [2/5]: VI. bab 'mutekâbilîn' (karşılıklı) — 37:27'de 'aqbele' (birbirine yönelme, suçlular) — aynı kök, cennette yüz yüze oturuş (okumada görüldü). سرر [1/1] kapanıyor — gloss 'sır, gizleme'; burada 'surur' = tahtlar (serîr çoğulu): gloss baskın lemmayı karşılamıyor, 987/1015 gloss ailesi. 3 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 hâl/yer tamlaması; D3 VI. bab karşılıklılık (37:25 tenâsarûn, 37:27 yetesâelûn ile aynı bab); D4 şahıs işareti yok.\n◈A — A2 sahne: tahtlar, karşılıklı oturuş; A4 cennet sahnesi.",
 45: "◇ 'yutâfu aleyhim bi-ke'sin min ma'în' — edilgen (yutâfu, dolaştırılır): dolaştıran adlanmıyor. EDİLGEN 1/1, pas z=5,38 → ★★★ kaynak pas — tek fiilli ayette oran 1/1 (1009 edilgen ★★★ ailesi; kaynak doğru: morfoloji PASS, metin edilgen). طوف [1/1], كأس [1/1] kapanıyor; عين [1/2] ('ma'în' — akan pınar suyu). 5 kelime.\n◈K — —\n◈B — B3 tetik عين organ anlamında değil: 'ma'în' — pınar, akarsu (ön-kayıt §2'deki 'عين pınar' örneği).\n◈D — D1 edilgen haber, IMPF; D3 dolaştıran gizli; D4 3MS (fiil) · 3MP (aleyhim).\n◈A — A1 muhlas kullar alıcı; hizmet eden adsız; A2 kadeh, pınar.",
 46: "◇ 'beydâ'e lezzetin li'ş-şâribîn' — kadehin iki sıfatı: bembeyaz, içenlere lezzet. بيض [1/2] (37:49'da [2/2]); لذذ [1/1], شرب [1/1] kapanıyor. 3 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 sıfatlar (kadehe bağlı, ayet sınırını aşıyor); D3 renk + tat; D4 şahıs işareti yok.\n◈A — A1 'içenler' (şâribîn) — muhlas kullar işleviyle adlanıyor.",
 47: "◇ 'lâ fîhâ ğavlun ve lâ hum anhâ yunzefûn' — iki olumsuzluk (NEG 2): onda sersemletme yok / onlar ondan sarhoş olmaz. HAPAKS غول (ğavl) → ★★★ kaynak hapaks z=3,28 (983 ailesi); نزف [1/1] kapanıyor. Morfoloji 'yunzefûn'u (fethalı, edilgen biçim) PASS etiketlemiyor — edilgen alanı 0; aynı lemmanın 56:19'daki kesreli 'yunzifûn' biçimi etken. Edilgen etiketinin biçimle uyuşmadığı ikinci vaka (aday 1037'ye ek vaka; araç açığı, metin hakkında kanıt değil). 7 kelime.\n◈K — —\n◈B — —\n◈D — D1 çifte olumsuz isim + fiil cümlesi; D3 'lâ … ve lâ' paralelliği: içkinin özelliği / içenlerin hâli; D4 3FS (kadeh) · 3MP.\n◈A — A1 içenler; A4 cennet sahnesi sürüyor.",
 48: "◇ 've indehum qâsırâtu't-tarfi în' — yanlarında bakışı sınırlı, iri gözlü eşler (adlanmıyor, sıfatlarıyla). عند [1/2]; قصر [1/1] ('qâsırât' — kısan, sınırlayan); طرف [1/1] ('tarf' — bakış; gloss 'uç, kenar' bu anlamı karşılamıyor, 987/1015 gloss ailesi); عين [2/2] kapanıyor ('în' — iri gözlü). xref 38:52 — henüz okunmadı. 4 kelime, yıldız yok.\n◈K — —\n◈B — B3 organ: göz — iki kez, iki sözcükle: 'tarf' (bakış, işlev sınırlı) ve 'în' (iri gözlü, nitelik); B1 adsız eşler (dişil çoğul sıfatla).\n◈D — D1 isim cümlesi (haber önde: indehum); D3 iki sıfat tamlaması, isim hiç yok; D4 3MP 1.\n◈A — A1 eşler (adsız, yalnız sıfatla), muhlas kullar; A4 sahne sürüyor.",
 49: "◇ 'ke-ennehunne beydun meknûn' — teşbih (ke-enne): saklı/korunmuş yumurta. بيض [2/2] kapanıyor: 37:46 'beydâ'' (kadehin beyazlığı) → 37:49 'beyd' (yumurta, benzetme) — aynı kök üç ayet arayla, sıfat → isim (okumada görüldü). كنن [1/1] kapanıyor (meknûn, edilgen ortaç). 3FP 1. Biçim alanında teşbih türü yok (yalnız kip/biçim listesi). 3 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 isim cümlesi, benzetme; D2 teşbih (ke-enne) — biçim alanı kapsamıyor (kayıt); D3 بيض'in ikinci kullanımı; D4 3FP.\n◈A — A1 eşler; A4 betimleme kapanıyor.",
 50: "◇ 'fe-aqbele ba'duhum alâ ba'din yetesâelûn' — 37:27'nin tam tekrarı (nakarat3, 5 kelime, tür TAM; defterden koşuldu: eş 37:27 — artık İKİSİ DE OKUNDU; esit2 37:27 TAM, 52:25 TAM, 68:30 BENZER — sonrakiler henüz okunmadı). Yalnız bağlaç farklı: 37:27 've-', 37:50 'fe-'. Aynı cümle iki gruba: 37:27'de suçlular (ardından suçlama/inkâr: 37:28-32), 37:50'de muhlas kullar (ardından ne geleceği 37:51 okununca). بعض ×2 [3,4/4] ve سأل [3/3] kapanıyor (37:24 mes'ûlûn → 37:27 → 37:50); قبل [3/5]. 5 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 haber (PERF + IMPF hâl); D3 nakarat — 23 ayet arayla tam tekrar, iki karşıt sahnede; D4 3MP 3 · 3MS 1.\n◈A — A1 muhlas kullar kendi aralarında; A3 konuşma açılıyor; A4 karşılıklı konuşma birimi başlıyor — 37:27'deki birimin aynası (okumada görüldü, KAPATILAMAZ).",
}
MEAL.update(MEAL5); M.update(M5)

MEAL6 = {
 51: "İçlerinden biri der ki: 'Benim bir yakın arkadaşım vardı;",
 52: 'derdi ki: "Sen de mi (dirilişi) doğrulayanlardansın?',
 53: 'Ölüp toprak ve kemik olduğumuzda mı, gerçekten biz mi hesaba çekilip cezalandırılacağız?"\'',
 54: "Der ki: 'Siz (onu) yukarıdan görmek ister misiniz?'",
 55: 'Bakar ve onu cahîmin ortasında görür.',
 56: "Der ki: 'Allah'a yemin olsun, az kalsın beni de helak edecektin!",
 57: 'Rabbimin nimeti olmasaydı, ben de (oraya) getirilenlerden olurdum.',
 58: 'Peki biz artık ölecek değil miyiz,',
 59: "ilk ölümümüz dışında? Ve biz azaba uğratılacak da değiliz.'",
 60: 'Şüphesiz bu, büyük kurtuluşun ta kendisidir.',
}
M6 = {
 51: "◇ 37:50'de açılan soruşma tek sese iniyor: 'qâle qâ'ilun minhum' — içlerinden biri (adsız). 1S ilk kez (sûrede 1S: 51, 56, 57 — defterden): 'innî kâne lî qarîn'. قول ×2 [9,10/24] (qâle + qâ'il: fiil + ortaç aynı kökten; mm2 alanı boş — mm2 fiil + aynı kökten ACC isim arıyor, burada ortaç NOM). قرن [1/1] kapanıyor — gloss 'nesil, çağ; bağlama'; burada 'qarîn' = yakın arkadaş (987/1015 gloss ailesi). كون [11/20]. 7 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 haber + alıntı (inne ile tekitli); D3 قول fiili ve ortacı yan yana ('dedi bir diyen'); D4 3MS (qâle) → alıntı içi 1S.\n◈A — A1 adsız tekil konuşan (cennettekilerden), adsız 'qarîn'; A3 soruşmanın ilk sesi; A4 anlatı içinde anlatı (geçmişteki arkadaş) açılıyor.",
 52: "◇ Alıntı içinde alıntı: arkadaşın geçmişteki sözü — 'e-inneke le-mine'l-musaddiqîn' (INTG + EMPH, 2MS: konuşana hitap). صدق [2/4]: 37:37 'saddeqa'l-murselîn' (elçileri doğruladı) → 37:52 'musaddiqîn' (doğrulayanlar, arkadaşın alaycı sorusunda). قول [11/24]. 4 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 soru (e-inne … le-); D3 صدق'ın ikinci geçişi, alaycı soruda; D4 2MS (alıntı içi muhatap = 37:51'in konuşanı) · 3MS (yeqûlu).\n◈A — A1 'qarîn' konuşan (geçmişte), muhatap 37:51'in konuşanı; A3 iki katmanlı alıntı; A4 geçmiş sahnesi.",
 53: "◇ Arkadaşın sorusu sürüyor: 'e-izâ mitnâ ve kunnâ turâben ve izâmen e-innâ le-medînûn' — 37:16'nın nakaratı (nakarat3 6 kelime, sûre içi 2 ayet; esit2 37:16 BENZER) — artık iki ucu da okundu. Tek fark son kelime: 37:16 'le-meb'ûsûn' (diriltilecek miyiz) → 37:53 'le-medînûn' (hesaba çekilip cezalandırılacak mıyız). Aynı soru iki ağızda: 37:16 inkârcıların kendi itirazı, 37:53 bir inkârcının cennetteki arkadaşına yönelttiği alay (okumada görüldü). دين [2/2] kapanıyor (37:20 'yevmu'd-dîn' → 37:53 'medînûn'); ترب [2/2] kapanıyor; موت [2/4], عظم [2/6], كون [12/20]. EDİLGEN 1/2, pas z=2,52 → ★★ — kaynak yine 'mitnâ' PASS etiketi (aday 1037 listesindeki 37:53; araç açığı). İltifât alanı 1: alıntı içi 1P (1017 ailesi). xref 23:35, 23:82 (okundu), 37:16 (okundu), 56:47 (henüz okunmadı). 7 kelime.\n◈K — —\n◈B — B2 ölüm → toprak + kemik (37:16 ile aynı sıra); B4 ölüm verilmiş, ceza sorgulanıyor (37:16'da diriliş sorgulanıyordu).\n◈D — D1 çift soru (e-izâ … e-innâ … le-); D3 nakarat, son kelime değişiyor (meb'ûsûn → medînûn); D4 alıntı içi 1P 5.\n◈A — A1 'qarîn' konuşan (geçmişte); A3 37:16'daki itirazın tekil ağızda tekrarı; A4 geçmiş sahnesi kapanıyor.",
 54: "◇ Konuşan cennettekilere döner: 'qâle hel entum muttali'ûn' — 'siz (onu) yukarıdan görmek ister misiniz?' (INTG). طلع [1/3] — gloss 'doğma (güneş)'; burada VIII. bab 'ittala'a' — yukarıdan bakıp görme (987/1015 gloss ailesi). قول [12/24]. İltifât alanı 1: 37:53 alıntı içi 1P → 37:54 2MP (cennettekilere hitap) — konuşma sırası değişimi (1017 ailesi). 4 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 soru ('hel'); D4 3MS (qâle) + 2MP — alıntıdan çıkış, yeni hitap.\n◈A — A1 konuşan (37:51'in adsız tekili), muhatap cennettekiler (2MP); A3 geçmiş anlatısından şimdiki sahneye dönüş.",
 55: "◇ 'fe'ttala'a fe-raâhu fî sevâ'i'l-cahîm' — bakar, görür: arkadaşı cahîmin ortasında. طلع [2/3] (37:54 'muttali'ûn' → 37:55 'ittala'a', aynı VIII. bab); رأي [2/5]; سوي [1/1] kapanıyor ('sevâ'' — orta); جحم [2/6]: 37:23 'sırâti'l-cahîm' (cahîmin yolu, sevk) → 37:55 'sevâ'i'l-cahîm' (cahîmin ortası, varış) (okumada görüldü). 5 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 iki fâ'lı ardışık fiil (bakma → görme); D4 3MS 3.\n◈A — A1 konuşan (gören) ve 'qarîn' (görülen, cahîmde); A2 iki sahne aynı anda: cennetten cahîme bakış; A4 sahne birleşiyor.",
 56: "◇ Yemin: 'qâle ta'llâhi in kidte le-turdîn' — lafız (sûrede dördüncü: 23, 35, 40, 56) bir cennettekinin ağzında, tâ-yemin harfiyle. ★★★ kaynak allah z=3,47 (5 kelimede 1 lafız, 1012 ailesi). Alan arızaları: (1) biçim alanı tâ-yemini QASEM saymıyor — aday 443'ün 9/9 listesindeki 37:56 (araç notu); (2) kip COND, edim 'şart': 'in' burada şart değil, hafifletilmiş inne (in-i muhaffefe) + lâm-ı fârıka ('le-turdîn'); (3) şahıs alanı 3FS 1: 'turdîni' (beni helak edecektin) 2MS (kidte ile uyumlu) — morfoloji tu- önekini 3FS etiketlemiş. أله [7/20]; كود [1/1], ردي [1/1] kapanıyor; قول [13/24]. 5 kelime.\n◈K — —\n◈B — —\n◈D — D1 yemin + tekitli haber (in-i muhaffefe + lâm); D2 qasem (tâ) — alan kaçırıyor (443); D4 1S + 2MS (arkadaşa hitap); alan 3FS'i yanlış (kayıt).\n◈A — A1 cennetteki konuşan, muhatap cahîmdeki 'qarîn'; A3 doğrudan hitap — iki sahne arasında konuşma.",
 57: "◇ 've lev lâ ni'metu rabbî le-kuntu mine'l-muhdarîn' — 'Rabbimin nimeti olmasaydı, ben de getirilenlerden olurdum'. 'rabbî' (1S) — sûrede Rab konuşanın ağzında ikinci kez (37:31 suçluların 'rabbinâ'sı, 37:57 cennettekinin 'rabbî'si; okumada görüldü). ★★★ kaynak rab z=3,23 (6 kelimede 1 Rab, 1020 ailesi). نعم [2/3] ('ni'me', nimet — §8 S1 ile ◈B tetiği yok); حضر [1/3] ('muhdarîn', edilgen ortaç: hazır edilen, getirilen — kim getirdiği adlanmıyor); كون [13/20], ربب [4/14]. 6 kelime.\n◈K — —\n◈B — —\n◈D — D1 şart (lev-lâ) + cevap (le-kuntu); D3 37:31 'rabbinâ' (1P, suçlular) ↔ 37:57 'rabbî' (1S, cennetteki); D4 1S 3.\n◈A — A1 cennetteki konuşan; Rab onun ağzında, nimetin sahibi; A3 37:56'daki hitabın devamı.",
 58: "◇ 'e-femâ nahnu bi-meyyitîn' — soru + olumsuz: 'peki biz ölecek değil miyiz'. موت [3/4]. 1P 1 — konuşan artık 'biz' (cennettekiler). 3 kelime, yıldız yok.\n◈K — —\n◈B — B4 ölüm olumsuzlanıyor (meyyitîn, ölecek olanlar) — soru biçiminde.\n◈D — D1 istifhâm (sevinç/hayret), olumsuz isim cümlesi; D4 1S'ten 1P'ye — konuşan grubu katıyor.\n◈A — A1 cennetteki konuşan (+ arkadaşları); A3 kime söylendiği metinde açık değil (cennettekilere mi, cahîmdekine mi) — KAPATILAMAZ.",
 59: "◇ 'illâ mevtetene'l-ûlâ ve mâ nahnu bi-mu'azzebîn' — biçim HASR: tek ölüm, ilk ölüm; azap da yok. موت [4/4] kapanıyor: sûredeki dört token — 37:16 'mitnâ' (inkârcılar), 37:53 'mitnâ' (qarîn), 37:58 'meyyitîn', 37:59 'mevtete' — ölüm iki kez itirazda, iki kez cennettekinin ağzında. أول [2/5]: 37:17 'âbâunâ'l-evvelûn' (ilk atalar) → 37:59 'mevtetene'l-ûlâ' (ilk ölüm). esmâ: evvel (ûlâ) e_oto 1 → e_el 'degil' (ölümün sıfatı); §4.3 mühür EVET, geçersiz. عذب [4/5] ('mu'azzebîn', edilgen ortaç). 6 kelime, yıldız yok.\n◈K — —\n◈B — B4 ölüm: bir kez verilmiş (ilk ölüm), ikincisi yok; azap yok.\n◈D — D1 istisna (hasr) + olumsuz isim cümlesi; D3 موت ipliğinin kapanışı; D4 1P 2.\n◈A — A1 cennettekiler ('biz'); A4 konuşma burada kapanıyor gibi — 37:60 anlatıcı mı konuşan mı, metinde belirsiz.",
 60: "◇ 'inne hâzâ le-huve'l-fevzu'l-azîm' — tekit (inne + lâm + huve) + işaret (DIKKAT). فوز [1/1] kapanıyor; عظم [3/6]: 37:16 ve 37:53 'izâm' (kemik, itirazda) → 37:60 'azîm' (büyük kurtuluş) — aynı kök iki anlamda (okumada görüldü). nakarat3 'inne hâzâ le-huve' (3 kelime) sûre içi 2 ayet — eşi 37:106 (defterden koşuldu; henüz okunmadı); süzgeç GEÇMEZ. İltifât alanı 1: 1P → 3MS (huve = 'bu', nesne göndergeli) — 1017 ailesi. 5 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 üçlü tekit (inne, lâm, ayırma zamiri huve); D2 işaret (hâzâ); D3 عظم'in ikinci anlamı; D4 3MS — nesne (durum) göndergeli.\n◈A — A1 konuşan belirsiz (cennetteki mi, anlatıcı mı); A4 37:41'de açılan cennet birimi yargıyla kapanıyor.",
}
MEAL.update(MEAL6); M.update(M6)

MEAL7 = {
 61: 'Çalışanlar bunun gibisi için çalışsın.',
 62: 'Konukluk olarak bu mu daha hayırlı, yoksa zakkum ağacı mı?',
 63: 'Biz onu zalimler için bir sınama kıldık.',
 64: 'O, cahîmin dibinden çıkan bir ağaçtır;',
 65: 'tomurcukları sanki şeytanların başlarıdır.',
 66: 'Onlar ondan elbette yiyecekler ve karınlarını ondan dolduracaklar.',
 67: 'Sonra onlar için onun üstüne kaynar sudan bir karışım vardır.',
 68: 'Sonra dönüşleri elbette cahîmedir.',
 69: 'Çünkü onlar atalarını sapmış buldular;',
 70: 've onların izleri üzerinde koşturulup gidiyorlar.',
}
M7 = {
 61: "◇ 'li-misli hâzâ fe'l-ya'meli'l-âmilûn' — üçüncü şahsa emir (lâm-ı emir, IMPV), işaret (DIKKAT): 'bunun gibisi' 37:41-60'ın cennet sahnesine dönüyor. عمل ×2 [2,3/4]: fiil + aynı kökten ortaç ('ya'mel … âmilûn' — 37:51 'qâle qâ'il' gibi, mm2 alanı boş: ortaç NOM); 37:39 'mâ kuntum ta'melûn' (suçluların yaptıkları) → 37:61 'âmilûn' (çalışanlar) (okumada görüldü). مثل [1/1] kapanıyor. 4 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 emir (3. şahsa, lâm ile); D2 işaret (hâzâ); D3 fiil + kendi ortacı; D4 3MS (alan) — gönderge genel 'çalışanlar'.\n◈A — A1 'çalışanlar' (genel sınıf, adsız); A4 cennet birimini (37:41-60) kapatan yargı/çağrı.",
 62: "◇ Karşılaştırma sorusu: 'e-zâlike hayrun nuzulen em şeceratu'z-zaqqûm' — 37:11'in iskeleti: 'e-hum eşeddu halqan em men halaqnâ' / 'e-zâlike hayrun nuzulen em şeceratu'z-zaqqûm' — soru + üstünlük sıfatı + temyiz (ACC) + 'em' (okumada görüldü, KAPATILAMAZ). خير [1/1], زقم [1/1] kapanıyor; نزل [1/2] — gloss 'inme, indirme'; burada 'nuzul' konuğa sunulan ikram (987/1015 gloss ailesi); شجر [1/3]. Aktör alanı 'zaqqûm'u adlı aktör (yer) sayıyor — bir bitki adı (kayıt). 6 kelime, yıldız yok.\n◈K — —\n◈B — B1 bitki: ağaç (şecere) — adı zakkum; canlı olarak değil ikram/ceza nesnesi olarak anılıyor.\n◈D — D1 istifhâm (takrîrî), 'e … em' karşılaştırması; D3 37:11 ile aynı iskelet; D4 şahıs işareti yok.\n◈A — A1 zakkum ağacı (adlı, aktör alanında); A2 iki sahne karşı karşıya: cennet ikramı / zakkum; A4 cennet → cahîm geçişi.",
 63: "◇ 'innâ ce'alnâhâ fitneten li'z-zâlimîn' — konuşan 'biz' (1P 3): ağacı zalimler için sınama kıldık. فتن [1/2]; ظلم [2/3]: 37:22 'ellezîne zalemû' (toplananlar) → 37:63 'zâlimîn'. جعل [1/4]. 4 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 tekitli haber (inne), PERF; D4 1P 3 · 3FS 1 (ağaç); iltifât alanı 0 (37:62 şahıssız).\n◈A — A1 konuşan 'biz', zalimler; A3 ağacın işlevi açıklanıyor.",
 64: "◇ 'innehâ şeceratun tahrucu fî asli'l-cahîm' — ağaç cahîmin dibinden çıkar. جحم [3/6]: 37:23 'sırâti'l-cahîm' (yolu) → 37:55 'sevâ'i'l-cahîm' (ortası) → 37:64 'asli'l-cahîm' (dibi) — aynı ad üç tamlamada, yol → orta → dip (okumada görüldü, KAPATILAMAZ). شجر [2/3]; خرج [1/1], أصل [1/1] kapanıyor. 6 kelime, yıldız yok. Çıpa: doğa olgusu değil (cahîm içi ağaç) — değerlendirme dışı.\n◈K — —\n◈B — B1 bitki (ağaç); B2 çıkış yeri adlı: cahîmin dibi — oluşum aşaması yok, yalnız 'çıkar' (IMPF).\n◈D — D1 tekitli isim cümlesi + sıfat cümlesi; D3 جحم tamlama dizisi; D4 3FS 2.\n◈A — A2 sahne: cahîmin dibi.",
 65: "◇ 'tal'uhâ ke-ennehû ru'ûsu'ş-şeyâtîn' — teşbih (ke-enne): tomurcukları şeytan başları gibi. Sûrede ikinci 'ke-enne' teşbihi (37:49 'beydun meknûn' — cennet eşleri; 37:65 şeytan başları — zakkum): iki karşıt sahnede birer benzetme (okumada görüldü). طلع [3/3] kapanıyor: 37:54-55 'muttali'ûn / ittala'a' (yukarıdan bakma) → 37:65 'tal'' (tomurcuk) — gloss 'doğma (güneş)' ikisini de karşılamıyor (987/1015). شطن [2/2] kapanıyor: 37:7 'şeytânin mârid' → 37:65 'ru'ûsu'ş-şeyâtîn'. رأس [1/1] kapanıyor. Aktör alanı 'şeytân'ı adlı (gayb) sayıyor — burada benzetmenin terimi. 4 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 isim cümlesi, benzetme; D2 teşbih — biçim alanı kapsamıyor (37:49 kaydı); D4 3FS · 3MS.\n◈A — A1 şeytanlar (benzetmede, sahnede değil); A4 zakkum betimlemesi.",
 66: "◇ 'fe-innehum le-âkilûne minhâ fe-mâli'ûne minhe'l-butûn' — iki ortaç (yiyenler, dolduranlar), ikisi de 'minhâ'. ملأ [2/2] kapanıyor: 37:8 'el-mele'i'l-a'lâ' (yüce topluluk) → 37:66 'mâli'ûn' (dolduranlar) — aynı kök iki anlam (okumada görüldü). أكل [1/2], بطن [1/2]. 6 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 tekitli haber (inne + lâm) + fâ ile ikinci haber; D3 'minhâ' ikilemesi; D4 3MP · 3FS.\n◈A — A1 zalimler; A2 cahîm; A4 zakkumdan beslenme.",
 67: "◇ 'summe inne lehum aleyhâ le-şevben min hamîm' — 'summe' (sonra) ile sıra: zakkumun üstüne kaynar su karışımı. HAPAKS شوب (şevb) → ★★★ kaynak hapaks z=3,28 (983 ailesi); حمم [1/1] kapanıyor. 7 kelime.\n◈K — —\n◈B — —\n◈D — D1 tekitli haber (inne + lâm), haber önde; D3 'summe' dizisinin ilki (37:67, 37:68); D4 3MP · 3FS.\n◈A — A1 zalimler; A4 sıra: yeme → içme.",
 68: "◇ 'summe inne merci'ahum le-ile'l-cahîm' — ikinci 'summe': dönüş cahîme. جحم [4/6]; رجع [1/1] kapanıyor. 'summe … inne … le-' kalıbı 37:67 ile aynı (iki ardışık ayet; nakarat3 alt sınırının altında — KAYIT). 5 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 tekitli haber (inne + lâm, harf-i cer üzerinde); D3 37:67 ile paralel açılış; D4 3MP 1.\n◈A — A2 sahne: cahîm (dönüş yeri); A4 zakkum birimi kapanıyor.",
 69: "◇ Gerekçe (inne): 'innehum elfev âbâ'ehum dâllîn' — atalarını sapmış buldular. أبو [2/5]: 37:17 'âbâunâ'l-evvelûn' (inkârcıların ağzında, diriliş itirazı) → 37:69 'âbâ'ehum dâllîn' (anlatıcının ağzında, sapmış) (okumada görüldü). لفو [1/1] kapanıyor; ضلل [1/2]. 4 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 tekitli haber, IV. bab PERF ('elfev'); D4 3MP 4.\n◈A — A1 zalimler ve ataları (adsız); A4 cahîm sahnesinden dünyadaki nedene dönüş.",
 70: "◇ 'fe-hum alâ âsârihim yuhra'ûn' — atalarının izinde koşturuluyorlar. EDİLGEN 1/1 'yuhra'ûn' (koşturulurlar) — sürükleyen adlanmıyor; ★★★ kaynak pas z=5,38 — tek fiilli ayet, oran 1/1 (1009 ailesi; morfoloji PASS, biçim edilgen — kaynak doğru). هرع [1/1] kapanıyor; أثر [1/1] — gloss 'tercih etme, üstün tutma'; burada 'âsâr' izler (987/1015 gloss ailesi). 4 kelime.\n◈K — —\n◈B — —\n◈D — D1 isim cümlesi, haber edilgen fiil; D3 sürükleyen gizli; D4 3MP 4.\n◈A — A1 zalimler, atalar (iz bırakanlar); A4 birim kapanıyor — 37:71'de ne açılacağı okununca.",
}
MEAL.update(MEAL7); M.update(M7)

MEAL8 = {
 71: 'Andolsun, onlardan önce de öncekilerin çoğu sapmıştı.',
 72: 'Andolsun, onların içine uyarıcılar göndermiştik.',
 73: 'Bak, uyarılanların sonu nasıl oldu —',
 74: "Allah'ın ihlâsa erdirilmiş kulları müstesna.",
 75: 'Andolsun, Nûh bize seslenmişti; ne güzel icabet edenleriz!',
 76: 'Onu ve ailesini o büyük sıkıntıdan kurtardık,',
 77: 've yalnız onun soyunu kalıcı kıldık.',
 78: 'Sonrakiler arasında onun için (güzel bir anılış) bıraktık:',
 79: "'Âlemler içinde Nûh'a selâm!'",
 80: 'Biz iyilik edenleri işte böyle ödüllendiririz.',
}
M8 = {
 71: "◇ 've le-qad dalle qablehum ekseru'l-evvelîn' — 'le-qad' (kip CERT + EMPH) yeni birim: zalimlerden önceki kuşaklar. ضلل [2/2] kapanıyor: 37:69 'dâllîn' (sapmış atalar) → 37:71 'dalle' (saptı). أول [3/5]: 37:17 'âbâunâ'l-evvelûn' → 37:59 'mevtetene'l-ûlâ' → 37:71 'ekseru'l-evvelîn'. كثر [1/1] kapanıyor; قبل [4/5]. say işareti 'ekser' — yanlış pozitif (sayı değil, çoğunluk; 981/992 ailesi). esmâ: evvel e_oto 1 → e_el 'degil' (insanlar); §4.3 mühür EVET, geçersiz. 5 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 yeminli/tekitli haber (le-qad); D3 ضلل sıfattan fiile; D4 3MP · 3MS.\n◈A — A1 'öncekilerin çoğu' (adsız kuşaklar); A4 yeni birim açılıyor: geçmiş ümmetler.",
 72: "◇ 've le-qad erselnâ fîhim munzirîn' — ikinci 'le-qad': biz onlara uyarıcılar gönderdik (1P 2). رسل [2/8] (37:37 'murselîn' → 'erselnâ'); نذر [1/3] ('munzirîn', uyaranlar, IV. bab etken ortaç). 4 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 'le-qad' + PERF; D3 'le-qad' 37:71-72 ardışık; D4 1P 2.\n◈A — A1 konuşan 'biz', uyarıcılar (adsız), öncekiler; A4 birim sürüyor.",
 73: "◇ 'fe'nzur keyfe kâne âqıbetu'l-munzerîn' — emir 2MS (bak): uyarılanların sonu. نذر [2/3]: 37:72 'munzirîn' (uyaranlar, etken ortaç) → 37:73 'munzerîn' (uyarılanlar, edilgen ortaç) — aynı kök, aynı bab, iki ayet arayla iki taraf (okumada görüldü). عقب [1/1] kapanıyor; نظر [2/5], كيف [1/2], كون [14/20]. xref 10:73 (okundu): aynı dizge 'fe'nzur keyfe kâne âqıbetu'l-munzerîn' — 10:73'te de Nûh kıssasının sonunda (okumada görüldü; nakarat3 sûre içi, defterde yalnız xref). 5 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 emir + soru (keyfe); D3 etken/edilgen ortaç çifti; D4 2MS (muhatap, adlanmıyor).\n◈A — A1 muhatap 2MS; A3 dinleyiciye bakma çağrısı; A4 birim sürüyor.",
 74: "◇ 'illâ ibâda'llâhi'l-muhlesîn' — 37:40'ın nakaratı (nakarat3 4 kelime tür TAM, sûre içi 4 ayet: 40, 74, 128, 160; esit2 37:40 TAM) — ikinci geçiş; 37:40'ta suçlulardan, burada uyarılanlardan istisna. Lafız sûrede beşinci (23, 35, 40, 56, 74). ★★★ kaynak allah z=4,47 (4 kelime, 1012 ailesi). عبد [3/14], خلص [2/5], أله [8/20]. eşler 128, 160, 169 henüz okunmadı. Ölçüm alanı 37:40'tan farklı olarak 'nakarat 4 (temsil [37, 40])' yazıyor — ilk geçiş temsil. 4 kelime.\n◈K — —\n◈B — —\n◈D — D1 istisna (37:73'e bağlı); D2 HASR; D3 nakarat — iki farklı hükümden aynı istisna; D4 şahıs işareti yok.\n◈A — A1 'Allah'ın kulları'; A4 37:71-74 alt birimi kapanıyor.",
 75: "◇ Kıssa açılıyor, sûrenin ilk adlı kişisi: 've le-qad nâdânâ Nûhun fe-le-ni'me'l-mucîbûn' — Nûh bize seslendi; ne güzel icabet edenleriz. Aktör alanı: Nûh (kişi, fail) — 37:62 zakkum ve 37:65 şeytandan sonra ilk kişi adı. ندي [1/2] (III. bab 'nâdâ'); جوب [1/1] kapanıyor; نعم [3/3] kapanıyor ('ni'me' — övgü fiili; §8 S1 ile ◈B tetiği yok). esmâ: 'mucîbûn' e_oto 1 → e_el 'ilahi' — övülen (mahsûs bi'l-medh) gizli 'biz' = konuşan Tanrı; ama biçim çoğul (azamet çoğulu): SINIR VAKASI, 999/1019 ailesine not. §4.3 mühür EVET ve e_el ilahi — sûrede ilk geçerli mühür adayı (e_suzgec tam okuma sonrası). 5 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 'le-qad' + PERF + övgü cümlesi ('fe-le-ni'me'); D3 nidâ (çağrı) → icabet: soru-cevap tek ayette; D4 3MS (Nûh) → 1P (övgü).\n◈A — A1 Nûh (adlı, fail: çağıran), 'biz' (cevap veren); A3 çağrı ve cevap; A4 Nûh kıssası açılıyor.",
 76: "◇ 've neccaynâhu ve ehlehû mine'l-kerbi'l-azîm' — kurtarma (II. bab 'neccâ'). نجو [1/3], أهل [1/2], كرب [1/2]; عظم [4/6] (37:60 'el-fevzu'l-azîm' → 37:76 'el-kerbi'l-azîm' — aynı sıfat, büyük kurtuluş / büyük sıkıntı; okumada görüldü). nakarat3 'mine'l-kerbi'l-azîm' (3 kelime) sûre içi 2 ayet — eşi 37:115 (defterden; henüz okunmadı); süzgeç GEÇMEZ. xref 21:76 (okundu): 've neccaynâhu ve ehlehû mine'l-kerbi'l-azîm' — orada da Nûh (okumada görüldü). 5 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 haber, PERF; D4 1P 2 · 3MS 2.\n◈A — A1 Nûh ve ailesi (adsız); A2 sıkıntı adlanıyor, ne olduğu söylenmiyor; A4 kıssa sürüyor.",
 77: "◇ 've ce'alnâ zurriyyetehû humu'l-bâqîn' — soyu kalıcı kılındı; ayırma zamiri 'hum' (yalnız onlar). ذرر [1/2]; بقي [1/1] kapanıyor; جعل [2/4]. 4 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 haber + ayırma zamiri (hasr anlamı; biçim alanı yazmıyor — kayıt); D4 1P 2 · 3MS · 3MP.\n◈A — A1 Nûh'un soyu (adsız); A4 kıssa sürüyor.",
 78: "◇ 've tereknâ aleyhi fi'l-âhirîn' — sonrakiler arasında onun için bıraktık. nakarat3 (4 kelime, tür TAM) sûre içi 3 ayet: 78, 108, 129 (defterden; eşler henüz okunmadı); esit2 37:108, 37:129 TAM (alan çift basıyor — 37:40 kaydı). ترك [2/5]: 37:36 'le-târikû âlihetinâ' (ilâhlarımızı bırakacak mıyız) → 37:78 'tereknâ aleyhi' (onun için bıraktık) (okumada görüldü). أخر [1/6]. esmâ: âhir e_oto 1 → 'degil' (sonraki insanlar); §4.3 mühür EVET, geçersiz. Bırakılanın ne olduğu 37:79'da (söz). 4 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 haber, nesnesi bir sonraki ayette (alıntı); D3 nakarat; D4 1P 2 · 3MS.\n◈A — A1 'sonrakiler' (gelecek kuşaklar); A4 kıssanın kapanış formülü başlıyor.",
 79: "◇ 'selâmun alâ Nûhin fi'l-âlemîn' — 37:78'de bırakılan söz: âlemlerde Nûh'a selâm. Şahıs işareti yok, fiil yok. سلم [2/8] (37:26 'musteslimûn' — teslim olmuş suçlular → 37:79 'selâm'; okumada görüldü); علم [2/7] ('âlemîn'). esmâ: selâm e_oto 1 → 'degil' (selamlama, ad değil); §4.3 mühür EVET, geçersiz. nakarat3 boş: 'selâmun alâ' 2 kelime, kişi adı değişken — alt sınırın altında (KAYIT). 5 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 isim cümlesi (dua/selam, haber biçiminde); D3 alıntı — 37:78'in nesnesi; D4 şahıs işareti yok.\n◈A — A1 Nûh (adlı, mecrur); A3 bırakılan söz — konuşanı yok; A4 kapanış formülü.",
 80: "◇ 'innâ kezâlike neczi'l-muhsinîn' — ödül kuralı. nakarat3 (4 kelime, tür TAM) sûre içi 4 ayet: 80, 105, 121, 131; 3 kelimelik 5 ayet (+110) — eşler henüz okunmadı; esit2 ayrıca 77:44 TAM (henüz okunmadı). 37:34 (okundu) aynı çerçeve: 'innâ kezâlike nef'alu bi'l-mucrimîn' — suçlulara 'böyle yaparız' / iyilere 'böyle karşılık veririz' (okumada görüldü; nakarat3 dışında, KAPATILAMAZ). جزي [2/6] (37:39 'tuczevne' → 'neczî'); حسن [1/7]. 4 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 tekitli haber (inne), IMPF (genel kural); D2 'kezâlike' vakadan kurala; D3 37:34 çerçevesinin karşıt tamamlayıcısı; D4 1P 2.\n◈A — A1 'iyilik edenler' (genel sınıf); A4 Nûh kıssasından genel hükme.",
}
MEAL.update(MEAL8); M.update(M8)

MEAL9 = {
 81: 'Çünkü o, bizim inanan kullarımızdandı.',
 82: 'Sonra ötekileri boğduk.',
 83: 'Şüphesiz İbrâhîm de onun yolundakilerdendi —',
 84: 'hani o, Rabbine arınmış (sağlam) bir kalple gelmişti;',
 85: "hani babasına ve kavmine: 'Neye tapıyorsunuz?' demişti,",
 86: "'Allah'ı bırakıp bir uydurma olarak ilâhlar mı istiyorsunuz?",
 87: "Peki âlemlerin Rabbi hakkında ne sanıyorsunuz?'",
 88: 'Sonra yıldızlara bir bakış baktı,',
 89: "ve 'Ben hastayım' dedi.",
 90: 'Bunun üzerine ondan yüz çevirip uzaklaştılar.',
}
M9 = {
 81: "◇ 'innehû min ibâdine'l-mu'minîn' — gerekçe (inne): Nûh 'bizim inanan kullarımız'dan. nakarat3 (4 kelime, tür TAM) sûre içi 3 ayet: 81, 111, 132; 3 kelimelik 4 ayet (+122) — eşler henüz okunmadı. عبد [4/14]: 37:40/74 'ibâda'llâh' (lafızla) → 37:81 'ibâdinâ' (1P iyelikle) (okumada görüldü). أمن [2/6]: 37:29 'lem tekûnû mu'minîn' (suçlular arasında) → 37:81 'el-mu'minîn' (Nûh). esmâ: mu'min e_oto 1 → 'degil' (kulların sıfatı); §4.3 mühür EVET, geçersiz. 4 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 tekitli haber (inne); D3 kapanış formülünün üçüncü halkası (78 bırakma → 79 selâm → 80 kural → 81 gerekçe); D4 1P 1 · 3MS 1.\n◈A — A1 Nûh (zamirle), 'biz'; A4 Nûh kıssasının kapanış formülü tamam.",
 82: "◇ 'summe ağraqne'l-âharîn' — kapanış formülünden SONRA boğma: kıssa sıralaması 75 çağrı → 76-77 kurtarma, soy → 78-81 formül → 82 ötekilerin boğulması (okumada görüldü). esit2 26:66 TAM (okundu): aynı cümle, 26:66'da Mûsâ kıssasında (Fir'avn tarafı) — aynı dizge iki farklı kıssada (okumada görüldü). أخر [2/6]: 37:78 'el-âhirîn' (sonrakiler) → 37:82 'el-âharîn' (ötekiler) — harekesiz yazımları aynı, harekeyle ayrılan iki kelime (okumada görüldü). غرق [1/1] kapanıyor. 3 kelime, yıldız yok. Çıpa: boğulma adlanıyor, olay (tufan) betimlenmiyor — değerlendirme dışı.\n◈K — —\n◈B — —\n◈D — D1 'summe' + PERF (IV. bab); D3 أخر'in ikinci kelimesi; D4 1P 2.\n◈A — A1 'ötekiler' (adsız); A4 Nûh kıssası kapanıyor (75-82, 8 ayet).",
 83: "◇ İkinci kıssa: 've inne min şî'atihî le-İbrâhîm' — İbrâhîm, Nûh'un 'şîa'sından (yolunu izleyen topluluğundan). Aktör alanı: İbrâhîm (kişi). شيع [1/1] kapanıyor. inne + lâm (EMPH). İltifât alanı 1: 37:82 1P → 37:83 3MS — gönderge farklı (1017 ailesi). 4 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 tekitli haber (inne + lâm, haber önde); D4 3MS.\n◈A — A1 İbrâhîm (adlı), Nûh (zamirle); A4 İbrâhîm kıssası açılıyor — Nûh'a bağlanarak.",
 84: "◇ 'iz câe rabbehû bi-qalbin selîm' — Rabbine sağlam/arınmış bir kalple geldi. ★★★ kaynak rab z=3,94 (5 kelimede 1 Rab, 1020 ailesi). ربب [5/14]; جيأ [2/2] kapanıyor (37:37 'câe bi'l-haqq' → 37:84 'câe rabbehû'); قلب [1/1] kapanıyor; سلم [3/8]: 37:79 'selâm' (Nûh'a) → 37:84 'selîm' (İbrâhîm'in kalbi) (okumada görüldü). 5 kelime.\n◈K — —\n◈B — B3 organ: kalp (qalb) — işlevi niteliğiyle: 'selîm' (sağlam/arınmış); bedensel değil, Rabbe gelişin aracı.\n◈D — D1 zaman zarfı ('iz') + PERF; D4 3MS 2.\n◈A — A1 İbrâhîm, Rab (onun Rabbi); A3 konuşma yok, tutum adlanıyor.",
 85: "◇ İkinci 'iz': 'iz qâle li-ebîhi ve qavmihî mâzâ ta'budûn' — babasına ve kavmine soru. esit2 26:70 YAKIN (okundu): 'iz qâle li-ebîhi ve qavmihî mâ ta'budûn' — 26:70'te de İbrâhîm; fark 'mâ' / 'mâzâ' (okumada görüldü). أبو [3/5]: 37:17 'âbâunâ' (itiraz) → 37:69 'âbâ'ehum dâllîn' → 37:85 'ebîhi' (İbrâhîm'in babası). قوم [2/6], عبد [5/14], قول [14/24]. 6 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 zaman zarfı + alıntı (soru, INTG); D4 3MS (çerçeve) + 2MP (alıntı içi).\n◈A — A1 İbrâhîm konuşan; babası ve kavmi (adsız) muhatap; A3 sorgu açılıyor.",
 86: "◇ 'e-ifken âliheten dûna'llâhi turîdûn' — İbrâhîm'in sorusu: Allah'ı bırakıp uydurma ilâhlar mı? Lafız sûrede altıncı (23, 35, 40, 56, 74, 86). ★★★ kaynak allah z=3,47 (5 kelime, 1012 ailesi). أله ×2 [9,10/20] — çoğul 'âliha' + lafız aynı cümlede, 37:35-36 çiftinin ('lâ ilâhe illa'llâh' / 'âlihetinâ') İbrâhîm ağzındaki karşılığı (okumada görüldü). دون [2/2] kapanıyor: 37:23 'min dûni'llâh' (tapılanlar, anlatıcı) → 37:86 'dûna'llâh' (İbrâhîm). أفك [1/2], رود [1/2]. xref 5:116, 39:38 — henüz okunmadı. 5 kelime.\n◈K — —\n◈B — —\n◈D — D1 istifhâm-ı inkârî, nesne öne alınmış ('e-ifken âliheten … turîdûn'); D3 أله tekil (lafız) / çoğul; D4 2MP 2.\n◈A — A1 İbrâhîm konuşan, kavmi muhatap; A3 sorgunun ikinci sorusu.",
 87: "◇ 'fe-mâ zannukum bi-rabbi'l-âlemîn' — üçüncü soru: âlemlerin Rabbi hakkında zannınız ne? ★★★ kaynak rab z=5,01 (4 kelimede 1 Rab, 1020 ailesi). ربب [6/14]; ظنن [1/1] kapanıyor; علم [3/7] ('âlemîn' — 37:79 'fi'l-âlemîn' → 37:87 'rabbi'l-âlemîn'). 37:86 lafız + 37:87 Rab: İbrâhîm'in ağzında ardışık iki ayette iki ad (okumada görüldü). 4 kelime.\n◈K — —\n◈B — —\n◈D — D1 soru (INTG); D3 lafızdan Rab'ba geçiş; D4 2MP 1.\n◈A — A1 İbrâhîm, kavmi; A3 sorgu kapanıyor — cevap yok.",
 88: "◇ 'fe-nazara nazraten fi'n-nucûm' — yıldızlara bir bakış baktı. mm2 [1, نظر]: fiil + aynı kökten 'merre' mastarı (nazra, bir kez bakma) — kök ikilemesi نظر ×2 [3,4/5]. نجم [1/1] kapanıyor. İltifât alanı 1: 37:87 alıntı içi 2MP → 37:88 3MS (anlatı) — alıntı sınırı (1017). 4 kelime, yıldız yok. 🜁 L0 — yıldızlar (nucûm) yalnız bakışın nesnesi olarak adlanıyor; süreç, nitelik, ölçü yok; olgu evet, çıpa hayır; tarayıcı vermedi.\n◈K — K1 yıldızlar (نجم; 37:6'da 'kevâkib' — farklı kök); K2 zaman yok; K3 —; K4 hareket fiili gözlemcide: İbrâhîm bakıyor, yıldızlar için fiil yok; amacı söylenmiyor.\n◈B — —\n◈D — D1 haber, PERF + mef'ûl-i mutlak (merre); D3 mm2; D4 3MS 1.\n◈A — A1 İbrâhîm (tek); A2 sahne gökyüzü (bakış); A4 sorgudan eyleme geçiş.",
 89: "◇ 'fe-qâle innî sekîm' — 'ben hastayım' (1S). سقم [1/2]; قول [15/24]. Söz 37:88'deki bakışın ardından fâ ile geliyor; bağlantı metinde açıklanmıyor. 3 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 tekitli haber (inne), alıntı; D3 fâ zinciri (88 baktı → 89 dedi → 90 yüz çevirdiler); D4 3MS + alıntı içi 1S.\n◈A — A1 İbrâhîm konuşan, muhatap kavim (adlanmıyor); A3 tek cümlelik söz.",
 90: "◇ 'fe-tevellev anhu mudbirîn' — yüz çevirip arkalarını dönerek gittiler. ولي [1/3] (V. bab 'tevellî'); دبر [1/1] kapanıyor ('mudbirîn', arka çeviren). Fiil + hâl ortacı aynı hareketi iki kez adlıyor (yüz çevirme / arka dönme). 3 kelime, yıldız yok.\n◈K — —\n◈B — —\n◈D — D1 haber + hâl (mudbirîn); D3 eşanlamlı pekiştirme; D4 3MP 2 · 3MS.\n◈A — A1 kavim gidiyor, İbrâhîm kalıyor; A4 sahne boşalıyor — sonrası 37:91 okununca.",
}
MEAL.update(MEAL9); M.update(M9)
