# -*- coding: utf-8 -*-
"""sebe_metin_1.py — sûre 34 (Sebe') meal ve matematikçi merceği, ayet 1-54.
Arapça sabit YOK: kökler yalnız korpus kök biçimiyle anılır, kelime biçimleri Latin harfle."""
MEAL = {
 1: "Hamd, göklerde ne var yerde ne varsa kendisinin olan Allah'adır. Âhirette de hamd O'nundur. O hikmet sahibidir, her şeyden haberdardır.",
 2: "Yere gireni ve ondan çıkanı, gökten ineni ve oraya yükseleni bilir. O esirgeyendir, bağışlayandır.",
 3: "Kâfirler, 'Kıyamet bize gelmeyecek' dediler. De ki: 'Hayır, Rabbime andolsun ki o size mutlaka gelecek.' O, gaybı bilendir; göklerde ve yerde zerre ağırlığınca bir şey, bundan daha küçüğü ve daha büyüğü O'ndan gizli kalmaz — hepsi apaçık bir Kitap'tadır.",
 4: "(Bu) iman edip salih ameller işleyenleri ödüllendirmesi içindir. İşte onlar için bağışlanma ve cömertçe bir rızık vardır.",
 5: "Âyetlerimizi boşa çıkarmak için yarışırcasına çabalayanlar — işte onlar için elem veren pislikten bir azap vardır.",
 6: "Kendilerine ilim verilenler, Rabbinden sana indirilenin hakkın ta kendisi olduğunu ve mutlak güç sahibi, övgüye lâyık olanın yoluna ilettiğini görürler.",
 7: "Kâfirler dediler ki: 'Size, paramparça dağıtıldığınızda mutlaka yeni bir yaratılışta olacağınızı haber veren bir adam gösterelim mi?'",
 8: "'Allah'a karşı yalan mı uydurdu, yoksa onda bir delilik mi var?' Hayır! Âhirete inanmayanlar azabın ve derin sapıklığın içindedirler.",
 9: "Önlerindeki ve arkalarındaki göğe ve yere bakmadılar mı? Dilersek onları yere geçiririz ya da üzerlerine gökten parçalar düşürürüz. Şüphesiz bunda, (Allah'a) yönelen her kul için bir âyet vardır.",
 10: "Andolsun, Dâvûd'a tarafımızdan bir lütuf verdik: 'Ey dağlar, onunla birlikte tesbih edin; ey kuşlar, siz de!' Demiri de ona yumuşattık.",
}
M = {
 1: "◇ Sûre hamd ile açılıyor. İlk kelimesi hamd kökü olan sûre açılışları korpusta dört: 6, 18, 34, 35 (Fâtiha'da hamd 1:2'de). Ayet hamdı İKİ alana dağıtıyor: göklerde ve yerde olanlar (lehû mâ fî...) ve âhiret — حمد [1,2/3] aynı ayette iki kez. Hamd kökü ile âhir lemması birlikte 4 ayette (10:10, 28:70, 34:1, 60:6); âhir'in 'âhiret yurdu' olduğu ve hamdın ORAYA konduğu yalnız ikisi: 28:70 (ûlâ ve âhira — zaman ikilisi) ve 34:1 (gökler-yer ve âhira — mekân + zaman). Esmâ kaydı: âhira (14. kelime) e_oto tokeni ama ilâhî değil; mühür hakîm-habîr ÇİFT, geçerli. 🜁 L0, olgu evet (gökler, yer adlandırılıyor). Bağ yok (esit2, nakarat3, xref boş).",
 2: "◇ Dört fiil, iki alan, iki yön — bir 2×2 tablo: yere GİREN / yerden ÇIKAN · gökten İNEN / göğe YÜKSELEN (ولج خرج نزل عرج, hepsi [1/1], hepsi IMPF). Bilginin kapsamı hareketin yönüyle çiziliyor; nesne adı yok, yalnız 'mâ' (ne). xref beş üçlünün beşi de 57:4'e: aynı yedi lemmalık dizi (علم يلج أرض خرج نزل سماء يعرج) 57:4'te yaratılış ve istivâdan sonra geliyor, orada mühür basîr. Mühür rahîm-gafûr ÇİFT ve SIRASI TERS: bu iki lemma korpusta 72 ayette bitişik; 71'inde gafûr önce, YALNIZ 34:2'de rahîm önce (TAM SAYIM, içerik lemması dizisi). Lafız YOK, Rab YOK — sınıf E, zamir huve 1. ayetteki lafza dönüyor. 🜁 L1, olgu evet: dört süreç adlanıyor, yön ekleniyor, mekanizma yok. Tarayıcı vermedi.",
 3: "◇ Kâfirlerin olumsuz iddiası AYNI fiille olumluya çevriliyor: lâ te'tînâ (bize gelmeyecek) → le-te'tiyenneküm (size mutlaka gelecek) — أتي [1,2/6], şahıs da dönüyor (1P → 2MP). Cevap Rab'be yeminle (ve-Rabbî, 1S): blokun ilk Rab'i. Ölçek 10:61'deki gibi kurulu — referans nokta zerre ağırlığı, sonra 'daha küçüğü ve daha büyüğü': referans bir sınır değil skala üzerinde bir işaret; nakarat3 10:61 ile 7 kelime, xref de 10:61. ذرر ile ثقل birlikte 6 ayette (4:40, 10:61, 34:3, 34:22, 99:7, 99:8) — 34:22 sûrede ileride. Yeni kök عزب (uzak kalma), korpusta 2 ayet: 10:61 ve 34:3 — iki ayetin ortak iskeletine giriyor. 🜁 L1, olgu HAYIR: ölçü birimi var ama iddia bilgiye dair, olgu örnek (31:16 emsali). ★★ tek kaynak n z=2,08 (32 kelime, blokun en uzunu). Esmâ: âlim Rab'bin sıfatı, ilâhî ama ortada; mübîn kitabın sıfatı → §4.3 mührü YANLIŞ (son-üç: ekber, kitâb, mübîn).",
 4: "◇ 34:3'ün amaç uzantısı (li-yecziye): ayet tek başına cümle değil. 34:4-5 bir AYNA ÇİFTİ, aynı çerçeve ülâike lehüm ile: iman + salih amel → bağışlanma + kerîm rızık | âyetleri boşa çıkarmaya çabalamak → ricz'den elem veren azap. Aynı çift 22:50-51'de: esit2 22:50 BENZER (0,8706), 34:5'in xref'i 22:51. Esmâ kerîm rızkın sıfatı → §4.3 mührü YANLIŞ (33:31 'rızk kerîm' ile aynı tür); sınıf e_oto E, e_el 0.",
 5: "◇ Aynanın ikinci yarısı. Allah'ın 1P konuşması blokta İLK kez burada: âyâtinâ (34:3'teki 1P kâfirlerin sözü). mu'âcizîn lemması korpusta 3 ayette (22:51, 34:5, 34:38) — üçüncüsü bu sûrede, 33 ayet sonra; nakarat3 bu ayeti 6 kelimelik kalıpla eşliyor. Ceza üç katmanlı isim tamlaması: azâb · min ricz · elîm (عذب رجز ألم, üçü de ilk anma). Esmâ yok, sınıf 0.",
 6: "◇ Görenler bir SINIF olarak tanımlanıyor: 'kendilerine ilim verilenler' — fiil edilgen (ûtû), indirilen de edilgen (unzile): EDİLGEN 2/4, ★★ tek kaynak pas z=2,52. Veren de indiren de adsız; kaynak yalnız 'Rabbinden'. حمد [3/3] burada tamamlanıyor: hamd ipliği sûrenin ilk altı ayetinde başlayıp kapanıyor (34:1'de iki kez, 34:6'da hamîd olarak). عزز [1/2]. Mühür azîz-hamîd ÇİFT, ton karma; 'sırâtı'l-azîzi'l-hamîd' kalıbı xref 14:1'de. Esmâ kararı SINIR VAKASI: iki isim yüklem değil muzâfun ileyh; göndergesi Allah olduğu için 'ilahi' verildi, gerekçe bilançoda.",
 7: "◇ Kâfirlerin ikinci sözü (34:3'ten sonra) ve konu yine âhiret. Muhatap Peygamber adıyla değil 'bir adam' (racül, adsız aktör) diye anılıyor. مزق iki kez yan yana: mezzaktum kulle mumazzak — fiil (edilgen, II. bab) + aynı kökten isim; mm2 yakalamıyor: aynı kökten isim ACC değil, kull'a bağlı GEN ve bitişik değil — işlevce mef'ûl-i mutlak (borç 982 ailesi; araç açığı, metin hakkında kanıt değil). مزق korpusta YALNIZ bu sûrede: 34:7 ve 34:19 (4 token / 2 ayet), nakarat3 ikisini 3 kelimeyle eşliyor. Burada bedenin dağılması iddianın konusu; 34:19 henüz okunmadı — bağ kaydedildi, doğrulanmadı.",
 8: "◇ İki seçenekli soru: iftira mı, cinnet mi (em ile ikili ayrım). Cevap 'bel' (biçim IDRAB) iki seçeneği de reddetmiyor, SORANLARI sınıflıyor: âhirete inanmayanlar azapta ve uzak sapıklıkta. Soru bir kişiyi sınıflamaya çalışıyor, cevap soranı sınıflıyor — ters yön. عذب [2/9] 34:5'ten sonra ikinci. âhira bu kez de e_oto tokeni, ilâhî değil; sınıf A lafızdan (Allah 3. kelime, tek lafız). Blokta kâfirlerin iki sözü (34:3, 34:7-8) ikisi de âhiret inkârı; 34:8'in cevabı ikisini tek sınıfa topluyor.",
 9: "◇ Konumsal çerçeve iki eksenli: ön/arka × gök/yer. Tehdit bu eksenlerin uçlarını TEK TEK kullanıyor: yer → yere geçirme (hasf), gök → gökten parça düşürme (kisef) — سمو ve أرض ayette ikişer kez [4,5/7]. Şart fiili 1P (in neşe'): Allah'ın 1P konuşması 34:5'ten sonra ikinci kez. xref 26:187: aynı üçlü (düşürmek · parça · gök) orada Şuayb'ın kavminin TALEBİ ('gökten üzerimize parça düşür'), burada tehdit — aynı ifade iki yönde. Sûre 26 okundu; bağ kaydedildi. Fâsıla münîb (ب): blokun TEK kafiye kırığı; ★ tek kaynak n z=1,76, kafiye kırığı yıldıza girmiyor (borç #15). 🜁 L1, olgu evet (iki doğal olay, koşul kipinde, mekanizma yok). TARAYICI v4 ADAY VERDİ — çıpa değil: kesinlik 0/1.",
 10: "◇ Anlatı katmanı açılıyor: adlı aktör Dâvûd (sûrenin ilk adlı kişisi). Blokun TEK 1-baskın ayeti (1P ×5: âteynâ, minnâ, elennâ...). Nidâ cansız varlığa: 'ey dağlar' — emir 2FS (evvibî). أوب korpusta 17 ayet, 8'i sûre 38'de; bu sûrede tek. جبل ile طير birlikte 3 ayette (2:260, 21:79, 34:10) — 21:79 aynı sahne (dağlar ve kuşlar Dâvûd'la tesbih), sûre 21 okundu. Demir: hadîd lemması 6 ayette; yumuşatma (لين, korpusta 5 ayet) — maddenin niteliği değişiyor, mekanizma yok. 🜁 L1, olgu HAYIR (mucize anlatısı, doğal düzenlilik iddiası değil).",
}
MEAL2 = {
 11: "'Geniş zırhlar yap, örgüde ölçüyü gözet.' Salih amel işleyin; şüphesiz ben yaptıklarınızı görenim.",
 12: "Süleyman'a da rüzgârı (verdik): sabah gidişi bir aylık, akşam dönüşü bir aylık (yoldu). Ona erimiş bakır pınarını akıttık. Cinlerden de Rabbinin izniyle onun önünde çalışanlar vardı; onlardan kim emrimizden saparsa ona alevli ateşin azabından tattırırız.",
 13: "Ona dilediği şeyleri yaparlardı: yüksek mâbedler, heykeller, havuz gibi çanaklar ve yerinden oynamaz kazanlar. 'Ey Dâvûd ailesi, şükür olarak çalışın!' Kullarımdan pek azı çok şükredendir.",
 14: "Onun ölümüne hükmettiğimizde, ölümünü onlara, değneğini yiyen bir yer kurdundan başkası göstermedi. O yıkılınca cinler anladı ki gaybı bilselerdi alçaltıcı azap içinde kalmazlardı.",
 15: "Andolsun, Sebe' halkının yurdunda bir âyet vardı: sağda ve solda iki bahçe. 'Rabbinizin rızkından yiyin ve O'na şükredin: güzel bir belde ve bağışlayan bir Rab.'",
 16: "Ama yüz çevirdiler. Biz de üzerlerine Arim selini gönderdik ve iki bahçelerini, acı meyveli, ılgınlı ve biraz da sedirli iki bahçeye çevirdik.",
 17: "Nankörlük ettikleri için onları böyle cezalandırdık. Biz nankörden başkasını cezalandırır mıyız?",
 18: "Onlarla bereketlendirdiğimiz kasabalar arasına birbirinden görülen kasabalar yaptık ve aralarındaki yürüyüşü ölçülü kıldık: 'Oralarda geceler ve günler boyu güven içinde yürüyün.'",
 19: "Dediler ki: 'Rabbimiz, yolculuklarımızın arasını uzaklaştır.' Kendilerine zulmettiler; biz de onları dillerde dolaşan hikâyeler yaptık ve paramparça dağıttık. Şüphesiz bunda çok sabreden, çok şükreden herkes için âyetler vardır.",
 20: "Andolsun, İblîs onlar hakkındaki zannını doğru çıkardı; mü'minlerden bir grup dışında ona uydular.",
}
M2 = {
 11: "◇ 34:10'un emir kısmı devam ediyor, ama muhatap ayet içinde DEĞİŞİYOR: i'mel (2MS, Dâvûd) → i'melû (2MP) → ta'melûn (2MP); konuşan 1S (innî). عمل ayette üç kez [2,3,4/11]. Ölçü kelimesi zanaatın içinde: qaddir fi's-serd — 'örgüde ölçüyü gözet' (قدر [1/5]). ★★★ tek kaynak hapaks سرد z=3,28 (korpusta yalnız bu ayet). Mühür basîr tekil, 'inne'nin haberi ve konuşan Allah — geçerli (aday 961'in 'tekil gerçek esmâ' türü). xref 23:51 (i'melû sâlihan — peygamberlere hitap). Lafız YOK, Rab YOK: sınıf E.",
 12: "◇ İkinci adlı kişi Süleyman, ayetin İLK kelimesinde (li-Süleymân) — 34:10'daki Dâvûd kalıbının devamı; ayette ana fiil yok, cümle 34:10'un fiiline bağlı. روح [1,2/2] iki ayrı anlamla: rîh (rüzgâr) ve revâh (akşam dönüşü) — aynı kök, iki kelime, iki anlam; شهر [1,2/2] iki kez simetrik: 'sabahı bir ay · akşamı bir ay'. Rüzgârın iki yönü bir süre birimiyle ölçülüyor. 🜁 kademe L4 BİÇİMİNDE (birim: ay), ama olgu HAYIR — Süleyman'a verilen tasarruf, doğal düzenlilik iddiası değil; çıpa verilmedi, tanım açığı kaydedildi (aday 1002). Tarayıcı vermedi. Cinler çalışıyor 'Rabbinin izniyle' (Rab [3/14]) — ama sapan için 'emrimizden' (1P): izin Rab'be, emir 1P'ye bağlı. Adlı-rüzgâr ikilisi 21:81'de (borç 972: Süleyman köksüz ad, ikili alanında görünmüyor).",
 13: "◇ Dört kalemli bir liste: mahârîb · temâsîl · cifân ke'l-cevâb · qudûr râsiyât — son ikisi benzetme/sıfatla genişliyor. ★★★ tek kaynak hapaks جفن z=3,28. Emir i'melû Âle Dâvûde şükran: şükür amelin ADI (ACC). شكر [1,2/4], sonra 34:15 ve 34:19 — iplik blokta tamamlanıyor. Kapanış bir oran iddiası: 'kullarımdan az olan şekûr' — qalîl say alanında sayı işareti (981 ailesi). Esmâ şekûr İNSAN (ibâdî) → §4.3 mührü YANLIŞ; e_el 0, sınıf E→0. Gloss: cevâb (havuzlar) kök جبي 'ictibâ' glossuyla, âl (aile) kök أول 'ilk' glossuyla görünüyor — 987 ailesi.",
 14: "◇ Ölüm iki kez (موت [1,2/2]): hükmedilen ölüm / fark edilmeyen ölüm. Fark ettiren insan değil, bir canlı: dâbbetü'l-arz değneği yiyor; değnek düşünce beden düşüyor (harra), düşüş bilgiyi doğuruyor (tebeyyenet). Zincir: yeme → düşme → anlama. Ders cinlerin BİLGİSİZLİĞİ: 'gaybı bilselerdi' — 34:3'te gaybın bilicisi Rab (âlimi'l-gayb), burada gaybı bilmeyen cinler: غيب [2/4] sûre içinde iki zıt özne. xref 7:188 (Peygamber: 'gaybı bilseydim'). 🜁 L2, olgu evet: canlının odunu yemesiyle düşme arasında nedensellik; mekanizma yok. TARAYICI v4 ADAY VERDİ — çıpa değil: kesinlik 0/1. Fâsıla mühîn: kafiye kırığı; ★ n z=1,55, kırık yıldıza EKLENMİYOR (formül: kırık yalnız diğer bileşenler 1,5'i geçmezse ★ verir).",
 15: "◇ Sûrenin adı olan kavim burada: Sebe' (PN kavim) korpusta 2 ayette, 27:22 ve 34:15. Âyet somut: 'sağda ve solda iki bahçe' — يمن ve شمل ikisi de [1/1]; ikili bir sayı, ikili bir yön. İki emir (yiyin · şükredin) ve iki isim cümlesi ayna gibi: 'güzel bir belde' (yer + sıfat) · 'bağışlayan bir Rab' (Rab + sıfat). Rab iki kez [4,5/14], ★ tek kaynak rab z=1,81. غفر [3/3] burada tamamlanıyor. Mühür gafûr Rab'bin sıfatı — geçerli, tekil. 🜁 L0, olgu evet (bahçeler adlandırılıyor).",
 16: "◇ 34:15'in simetrisi korunarak içeriği değişiyor: iki bahçe → İKİ bahçe (ikil korunuyor: cenneteyhim → cenneteyn, جنن [5,6/8]), meyve güzel → acı; ağaç listesi: hamt · esl · sidr. Ayette ÜÇ hapaks (عرم, خمط, أثل): ★★★ tek kaynak hapaks z=10,30 (blokun en yüksek z'si). Sidr kökü korpusta 4 ayette: 34:16, 53:14, 53:16, 56:28 — öteki üçünde cennet/sidre bağlamı, burada cezanın bitkisi. Fâsıla qalîl: kafiye kırığı ve say alanında sayı işareti (981). Neden-sonuç: yüz çevirme → sel → bahçelerin dönüşümü. 🜁 L2, olgu evet (sel ve bitki örtüsünün değişimi; mekanizma yok).",
 17: "◇ Sekiz kelime, iki kök, ikişer kez: جزي [2,3/5] ve كفر [3,4/10] — cezalandırdık / nankörlük ettiler / cezalandırır mıyız / nankör. Ayet kendi içinde kapalı halka (33:3 tipi). Soru biçiminde HASR: ceza yalnız kefûr'a. 1P baskın. Esmâ yok.",
 18: "◇ Nimetin ikinci yüzü: mekân ve mesafe. Aralarında 'görülen' kasabalar; yürüyüş 'ölçülü kılındı' (qaddarnâ — قدر [3/5]: 34:11 zırhın ölçüsü, 34:18 yolun ölçüsü). سير iki kez [1,2/2]; قري iki kez. 'Geceler ve günler' sırası: leyâlî + eyyâm birlikte 5 ayette (7:54, 28:71, 28:72, 34:18, 69:7). Kafiye kırığı âminîn (ن): blokta ★ yalnız bundan — bilanço kaynağı 'allah z=-0,53' diye yazıyor, YANLIŞ ETİKET (aday 1001). 🜁 L1, olgu hayır (yerleşim düzeni, insan eseri).",
 19: "◇ 34:18'in TERSİ bir talep: 'yolculuklarımızın arasını uzaklaştır' — بين 34:18'de 'aralarına kasabalar kıldık' [5,6/16], burada [7/16]; nimet olarak verilen yakınlık, dua ile uzaklığa çevriliyor. Sonuç iki fiille: hikâye kıldık · paramparça ettik. مزق [3,4/4] burada TAMAMLANIYOR: 34:7'de kâfirler bedenlerin dağılmasıyla alay ediyordu, 34:19'da aynı formül bir KAVMİN dağılması — nakarat3 iki ayeti 3 kelimeyle eşliyor (bağ doğrulandı). Kapanış 34:9'un formülü: 'inne fî zâlike le-âyet(ler) li-kulli ...' — 34:9 abdin münîb · 34:19 sabbârin şekûr. شكر [4/4] tamamlanıyor. 'Sabbâr şekûr' ikilisi korpusta 4 ayette (14:5, 31:31, 34:19, 42:33). Esmâ şekûr insan → §4.3 mührü YANLIŞ. Rab kâfirlerin duasında (Rabbenâ). ★ kafiye kırığından (bilanço 'rab 0,8' yazıyor — yanlış etiket, aday 1001).",
 20: "◇ Anlatı kıssadan genel hükme geçiyor: adlı aktör İblîs (gayb, fail). 'Zannını doğruladı' — صدق [1/2], ظنن [1/1]: doğruluk kökü bir ZANNI nitelendiriyor. Uyanlar çoğunluk, istisna 'bir grup' (ferîq, adsız). 34:13'teki 'kullarımdan az olan şekûr' ile yapısal ayna: az şükreden · az istisna. Esmâ mü'min insan → §4.3 mührü YANLIŞ; sınıf e_oto E, e_el 0. Lafız YOK, Rab YOK.",
}
MEAL.update(MEAL2); M.update(M2)
MEAL3 = {
 21: "Oysa onun (İblîs'in) onlar üzerinde hiçbir zorlayıcı gücü yoktu; ancak âhirete inananı ondan şüphe içinde olandan ayırt edelim diye (buna izin verdik). Rabbin her şeyi gözetip koruyandır.",
 22: "De ki: 'Allah'ı bırakıp (tanrı) sandıklarınızı çağırın! Onlar göklerde ve yerde zerre ağırlığınca bir şeye sahip değiller; ikisinde onların hiçbir ortaklığı yoktur, O'nun onlardan bir yardımcısı da yoktur.'",
 23: "O'nun katında, izin verdiği kimseden başkasının şefaati fayda vermez. Nihayet kalplerinden korku giderilince 'Rabbiniz ne dedi?' derler; 'Hakkı (söyledi)' derler. O yücedir, büyüktür.",
 24: "De ki: 'Sizi göklerden ve yerden kim rızıklandırıyor?' De ki: 'Allah.' Şüphesiz ya biz ya siz, (birimiz) doğru yol üzerinde ya da apaçık bir sapıklık içindedir.",
 25: "De ki: 'Bizim işlediğimiz suçlardan siz sorulmazsınız, sizin yaptıklarınızdan da biz sorulmayız.'",
 26: "De ki: 'Rabbimiz hepimizi bir araya toplayacak, sonra aramızda hak ile hüküm verecektir. O, hükmü açıp verendir, bilendir.'",
 27: "De ki: 'O'na ortak olarak kattıklarınızı bana gösterin!' Hayır! Bilakis O, mutlak güç sahibi, hikmet sahibi Allah'tır.",
 28: "Biz seni bütün insanlara ancak müjdeci ve uyarıcı olarak gönderdik; fakat insanların çoğu bilmez.",
 29: "'Doğru söyleyenlerseniz bu vaat ne zaman?' diyorlar.",
 30: "De ki: 'Sizin için bir günün vakti belirlenmiştir; ondan ne bir an geri kalabilirsiniz ne de öne geçebilirsiniz.'",
}
M3 = {
 21: "◇ 34:20'nin sınırı: İblîs'in 'sultanı' yok (سلط [1/1]) — uyma bir zorlama değil. Amaç lâmı 1P bilgiye bağlanıyor (li-na'leme): âhirete inanan / ondan şüphede olan — İKİ SINIF ayırt ediliyor, ayırıcı âhiret. أخر [3/4]: âhira sûrede üçüncü kez (34:1, 34:8, 34:21) ve üçünde de e_oto tokeni, ilâhî değil. Mühür hafîz Rab'bin haberi — geçerli, tekil (xref 11:57: 'Rabbim her şeyi koruyandır'). nakarat3 'alâ kulli şey' kalıbı sûre içinde 34:47 ile.",
 22: "◇ Üç kademeli dışlama: mülk yok (zerre ağırlığınca bile) · ortaklık yok · yardımcılık yok (zahîr). 34:3'ün ölçeği AYNEN dönüyor: nakarat3 7 kelime — kalıp sûre içinde yalnız 34:3 ve 34:22'de; ثقل [2/2] ve ذرر [2/2] burada tamamlanıyor. 34:3'te ölçek BİLGİNİN kapsamıydı (O'ndan gizli kalmaz), 34:22'de MÜLKÜN kapsamı (onlar sahip değil): aynı ölçek iki özne, iki ilişki. ظهر [2/2]: 34:18 'görünen' kasabalar / 34:22 'yardımcı' — aynı kök iki anlam. 🜁 L1, olgu hayır (34:3 emsali). Esmâ yok; sınıf A.",
 23: "◇ Şefaat 'izin' ile sınırlanıyor (أذن [2/2]: 34:12 cinlerin çalışması 'Rabbinin izniyle' / 34:23 şefaat izinle). Sahne diyalog: 'Rabbiniz ne dedi?' · 'Hakkı' — قول üç kez [6,7,8/36]. Edilgen fuzzi'a (korku giderildi, fail adsız). Mühür alîy-kebîr ÇİFT, ton celâl, geçerli; bu çift korpusta 5 ayette (4:34, 22:62, 31:30, 34:23, 40:12). علو [1/1].",
 24: "◇ Soru-cevap tek ayette: 'kim rızıklandırıyor?' · 'Allah'. Ardından iki taraf × iki durum: 'ya biz ya siz · ya hidayette ya apaçık sapıklıkta' — ev ×2; eşleme SÖYLENMİYOR, okuyucuya bırakılıyor (2×2 tablo, hücre ataması açık; 34:2'nin 2×2'sinden farkı bu). سمو [7/7] ve أرض [8/8] burada tamamlanıyor. nakarat3 'min semâ ve ard' sûre içinde 34:9 ile. Esmâ mübîn sapıklığın sıfatı → §4.3 mührü YANLIŞ. 🜁 L0, olgu evet (gökten ve yerden rızık — adlandırma).",
 25: "◇ Dokuz kelimelik ayna, ama simetri kırık: 'bizim işlediğimiz SUÇ' (ecremnâ, جرم [1/2]) · 'sizin YAPTIĞINIZ' (ta'melûn, عمل [8/11]) — kendi tarafına 'suç', karşı tarafa nötr 'amel'. İki fiil edilgen (tüs'elûne · nüs'elu): EDİLGEN 2/5, ★ tek kaynak pas z=1,95. سأل [1,2/3]. Lafız YOK, Rab YOK, esmâ yok.",
 26: "◇ İki fiil, iki aşama: toplama (yecma'u) → açma/ayırma (yefteh). بين iki kez [9,10/16]: 'aramızı' toplar · 'aramızı' açar. فتح [1,2/2] fiil + isim: yefteh → fettâh. Fettâh lemması korpusta YALNIZ bu ayette (1 ayet). Mühür fettâh-alîm ÇİFT, geçerli. ★ tek kaynak rab z=1,62 (Rabbunâ, 11 kelimede). xref 7:89 (Şuayb: 'Rabbimiz, aramızda hakla hüküm ver').",
 27: "◇ Blokun üçüncü çift mührü üst üste (34:23 alîy-kebîr · 34:26 fettâh-alîm · 34:27 azîz-hakîm). Biçim IDRAB + KELLA: 'gösterin' → 'hayır' → 'bilakis O Allah'. شرك [2/2] (34:22 şirk · 34:27 şürekâ') tamamlanıyor; عزز [2/2] (34:6) ve حكم [2/2] (34:1) da burada tamamlanıyor — sûrenin ilk bloğunun iki esmâ kökü bu ayette kapanıyor. Blokta 10 ayetin 6'sı 'qul' emriyle açılıyor (22, 24, 25, 26, 27, 30; 34:24'te ikinci kez).",
 28: "◇ Gönderilişin kapsamı: kâffeten li'n-nâs — 'bütün insanlar' (كفف [1/1]); iki rol: müjdeci ve uyarıcı. أنس iki kez: bütün insanlar / insanların çoğu — kapsam ile bilginin oranı aynı kelimeyle. nakarat3 'lâkinne ekseren-nâsi lâ ya'lemûn' sûre içinde 34:36 ile. say alanı ekser'i sayı işareti sayıyor (981 ailesi). Lafız YOK, Rab YOK; konuşan 1P, muhatap 2MS.",
 29: "◇ Yedi kelime ve korpusun en tekrarlı sorularından: esit2 dört ayette TAM (10:48, 21:38, 27:71, 36:48), 67:25 YAKIN, 32:28 BENZER. Aynı cümle beş ayrı sûrede kelimesi kelimesine. Kâfirlerin sûredeki üçüncü sözü (34:3 · 34:7 · 34:29): üçü de âhiretin zamanı/gerçekliği hakkında. وعد [1/2].",
 30: "◇ Cevap ölçü diliyle: mî'âd (belirlenmiş vakit, وعد [2/2]) · sâ'a (bir an) · iki X. bab fiil ayna: geri kalmak (teste'hirûn) / öne geçmek (testaqdimûn). سوع [2/2]: 34:3'te es-sâ'a (kıyamet) · 34:30'da sâ'aten (bir an) — aynı kelime iki ölçek. أخر [4/4] tamamlanıyor: dört anmanın üçü âhira, sonuncusu 'geri kalmak'. 34:29 soru, 34:30 cevap: 'ne zaman?' sorusuna TARİH verilmiyor, yalnız sapmanın sıfır olduğu söyleniyor.",
}
MEAL.update(MEAL3); M.update(M3)
MEAL4 = {
 31: "Kâfirler, 'Bu Kur'an'a da ondan öncekine de asla inanmayacağız' dediler. Zalimlerin Rableri huzurunda durdurulup birbirlerine söz çevirdiklerini bir görsen! Zayıf düşürülenler büyüklenenlere, 'Siz olmasaydınız mutlaka mü'min olurduk' derler.",
 32: "Büyüklenenler zayıf düşürülenlere, 'Size hidayet geldikten sonra sizi ondan biz mi alıkoyduk? Hayır, siz suçlulardınız' derler.",
 33: "Zayıf düşürülenler de büyüklenenlere, 'Hayır, gece gündüz kurduğunuz tuzaktı; bize Allah'ı inkâr etmemizi ve O'na denkler koşmamızı emrediyordunuz' derler. Azabı gördüklerinde pişmanlıklarını içlerine gömerler. Biz de kâfirlerin boyunlarına demir halkalar geçirdik. Onlar yaptıklarından başkasıyla mı cezalandırılırlar?",
 34: "Hangi kasabaya bir uyarıcı gönderdiysek, oranın varlık içinde şımarmışları mutlaka, 'Biz sizinle gönderilen şeyi inkâr ediyoruz' dediler.",
 35: "'Biz mal ve evlatça daha çoğuz; biz azaba uğratılacak değiliz' dediler.",
 36: "De ki: 'Rabbim rızkı dilediğine genişletir de daraltır da; fakat insanların çoğu bilmez.'",
 37: "Sizi bize yaklaştıracak olan ne mallarınızdır ne de evlatlarınız; ancak iman edip salih amel işleyen başka. İşte onlar için yaptıklarına karşılık kat kat ödül vardır; onlar yüksek köşklerde güven içindedirler.",
 38: "Âyetlerimizi boşa çıkarmak için yarışırcasına çabalayanlar ise azabın içine getirilip hazır tutulacaklardır.",
 39: "De ki: 'Rabbim, kullarından dilediğine rızkı genişletir de ona daraltır da. Siz neyi (Allah yolunda) harcarsanız, O onun yerine başkasını koyar. O rızık verenlerin en hayırlısıdır.'",
 40: "Onların hepsini toplayacağı gün, meleklere, 'Bunlar mı size tapıyorlardı?' diyecek.",
}
M4 = {
 31: "◇ Kâfirlerin dördüncü sözü (34:3 · 34:7 · 34:29 · 34:31) ve ilk kez nesnesi âhiret değil KİTAP: adlı aktör Kur'an (kitab, mecrur) — 'bununla da önündekiyle de'. Ardından sahne değişiyor: 'bir görsen' (lev terâ; nakarat3 sûre içinde 34:51 ile), zalimler Rab katında durdurulmuş (Rab [10/14]), söz birbirine dönüyor — بعض iki kez [1,2/4]: 'birbirlerine'. İki grup X. babla adlanıyor ama çatısı AYRI: zayıf düşürülenler EDİLGEN (istud'ifû), büyüklenenler ETKEN (istekberû) — biri başkası tarafından yapılmış, öteki kendi kendini yapmış. ★★ tek kaynak n z=2,08 (32 kelime). Esmâ mü'min insan → §4.3 mührü YANLIŞ.",
 32: "◇ Diyaloğun ikinci turu: büyüklenenler cevap veriyor; biçim soru + IDRAB ('biz mi alıkoyduk? · hayır, siz suçlulardınız'). جرم [2/2] burada tamamlanıyor: 34:25'te Peygamber tarafı suçu KENDİNE yazıyordu (ecremnâ), 34:32'de büyüklenenler suçu KARŞI tarafa yazıyor (mücrimîn) — aynı kök, iki yönde atıf. صدد [1/2], هدي [3/4].",
 33: "◇ Üçüncü tur: söz yine zayıf düşürülenlerde — konuşma sırası ضعف → كبر → ضعف (31 · 32 · 33); nakarat3 5 kelime 34:31 ile (sûre içi). 'Gece ve gündüzün tuzağı' — zaman ikilisi tuzağın faili gibi (ليل [2/2]: 34:18 'geceler ve günler güvenle yürüyün' / 34:33 'gece gündüz tuzak'). جعل iki kez [3,4/4] burada tamamlanıyor, iki özneyle: onlar Allah'a DENKLER KILMAYI emrediyordu · Biz boyunlara BOYUNDURUK KILDIK — aynı fiil, suç ve karşılığı. غلل (boyunduruk) [1/1]. Kapanış 34:17'nin soru-HASR kalıbı: 'yaptıklarından başkasıyla mı cezalandırılırlar?' — جزي [4/5]. xref 10:54 (pişmanlığı gizlemek). ★★ tek kaynak n z=2,29 (34 kelime, blokun en uzunu). Blokun TEK lafzı (Allah, 14. kelime). كبر [5/5] tamamlanıyor.",
 34: "◇ Tekil sahneden genel kurala: 'hangi kasabaya uyarıcı gönderdiysek'. رسل iki kez [3,4/6]: erselnâ (1P, etken) · ursiltum (2MP, edilgen) — gönderen konuşuyor, gönderilen edilgen; ★ tek kaynak pas z=1,57. قري [3/3] tamamlanıyor: 34:18'de 'bereketlendirdiğimiz' kasabalar, 34:34'te müterefleri inkâr eden kasaba. ترف [1/1]. xref 43:23 (aynı kalıp: kasaba · uyarıcı · müterefler dedi).",
 35: "◇ Sayıdan güvenceye akıl yürütme: 'mal ve evlatça daha çoğuz → azaba uğratılmayız'. ekser burada GERÇEK bir karşılaştırmalı nicelik iddiası — say alanının işaretlediği 'ekser' 34:28 ve 34:36'da nicelik belirteci, burada karşılaştırma: 981'in yanlış pozitif sayımında bu ayet ayrı tutulmalı. مول [1/2], ولد [1/2]. xref 9:69 (mal ve evlatça daha çok olanlar).",
 36: "◇ 34:35'e cevap AYNI kelimeyle: ekser ('biz daha çoğuz') → 'insanların ÇOĞU bilmez' — كثر [2,3/4] iki ayette iki işlevle. Rızık iki yönlü: genişletir (بسط) / daraltır (قدر) — قدر sûrede dördüncü anlamında: zırhın ölçüsü (34:11), yolun ölçüsü (34:18), burada daraltma. nakarat3 7 kelime 34:39 ile, 5 kelime 34:28 ile (sûre içi; 34:28'de kaydedilen bağ doğrulandı). Rab [11/14]. Esmâ yok.",
 37: "◇ 34:35'in cevabının ikinci yarısı: mal ve evlat yaklaştırmaz — مول [2/2] ve ولد [2/2] tamamlanıyor. İstisna iman + salih amel; karşılık 'cezâu'd-dı'f' (kat kat). ضعف [4/4] burada tamamlanıyor: ilk üçü istud'ifû (zayıf düşürülmek, 34:31-33), dördüncüsü dı'f (kat, iki misli) — aynı kök 'zayıflık' ve 'katlanma'. Güven iki kez aynı sıfatla: 34:18 yolda âminîn · 34:37 köşklerde âminûn. عمل [10,11/11], صلح [3/3], جزي [5/5] burada tamamlanıyor. xref 18:88.",
 38: "◇ 34:5'in dönüşü, 33 ayet sonra: nakarat3 6 kelime (sûre içi, 34:5 ile). 34:5'te ceza 'ricz'den elem veren azap', burada 'azaba getirilip hazır tutulurlar' (muhdarûn, حضر [1/1]). سعي [2/2] ve عجز [2/2] burada tamamlanıyor. 34:37-38 bir AYNA ÇİFTİ — 34:4-5'in yapısı: iman+amel → ödül / âyetleri boşa çıkarma → azap.",
 39: "◇ 34:36'nın tekrarı, iki ekle: 'kullarından' ve daraltmanın AYNI kişiye yapılabileceği ('ona', lehû) — nakarat3 7 kelime 34:36 ile. Üçüncü unsur: 'harcadığınızın yerine koyar' — خلف [2/2]: 34:9'da 'arkalarındaki' (halfehum), burada 'yerine koymak' (yuhlifuhû). رزق [5,6/6] iki kez ve tamamlanıyor; قدر [5/5] tamamlanıyor. 'Rızık verenlerin en hayırlısı' — râzık esmâ listesinde yok, e_oto tokeni çıkmadı.",
 40: "◇ Sahne mahşere dönüyor: 'hepsini toplayacağı gün' — جمع [2/2]: 34:26 'Rabbimiz aramızı toplar' → 34:40 'hepsini toplar'. Soru meleklere: 'bunlar size mi tapıyordu?' — soru tapılanlara soruluyor, tapanlara değil. xref 6:22, 10:28. Gloss: ملك 'mülk; melik' — melâike (melek) bu kökte, gloss meleği taşımıyor (987 ailesi).",
}
MEAL.update(MEAL4); M.update(M4)
MEAL5 = {
 41: "Melekler, 'Seni tenzih ederiz; bizim velimiz onlar değil, sensin. Hayır, onlar cinlere tapıyorlardı; çoğu onlara inanıyordu' derler.",
 42: "O gün birbirinize ne fayda ne de zarar verebilirsiniz. Zulmedenlere, 'Yalanladığınız ateşin azabını tadın' deriz.",
 43: "Âyetlerimiz onlara apaçık olarak okunduğunda, 'Bu, sizi atalarınızın taptıklarından alıkoymak isteyen bir adamdan başkası değil' dediler; 'Bu, uydurulmuş bir yalandan başka bir şey değil' dediler. Kâfirler kendilerine gelen hak için, 'Bu apaçık bir büyüden başka bir şey değil' dediler.",
 44: "Oysa biz onlara okuyup inceleyecekleri kitaplar vermemiştik, senden önce onlara bir uyarıcı da göndermemiştik.",
 45: "Onlardan öncekiler de yalanlamıştı; bunlar onlara verdiğimizin onda birine bile ulaşmadılar. Onlar elçilerimi yalanladı; benim inkârım (cezam) nasıl oldu!",
 46: "De ki: 'Size yalnız bir tek şey öğütlüyorum: Allah için ikişer ikişer ve teker teker kalkın, sonra düşünün; arkadaşınızda hiçbir delilik yoktur. O, çetin bir azabın önünde sizin için ancak bir uyarıcıdır.'",
 47: "De ki: 'Sizden ne ücret istediysem o sizin olsun. Benim ücretim yalnız Allah'a aittir. O her şeye şahittir.'",
 48: "De ki: 'Rabbim hakkı (bâtılın üstüne) fırlatır; O gaybları hakkıyla bilendir.'",
 49: "De ki: 'Hak geldi; bâtıl ne bir şeyi başlatabilir ne de geri getirebilir.'",
 50: "De ki: 'Eğer saparsam, yalnız kendi aleyhime saparım; eğer doğru yolu bulursam, bu Rabbimin bana vahyetmesi sayesindedir. Şüphesiz O işitendir, yakındır.'",
}
M5 = {
 41: "◇ 34:40'taki soruya meleklerin cevabı: tenzih (sübhâneke, سبح [1/1]) + 'velimiz sensin' + IDRAB 'onlar cinlere tapıyordu'. Soru tapılana sorulmuştu (34:40), cevap tapılanı değiştiriyor: melekler değil CİNLER. جنن [7/8]: sûrede bu kök üç anlamla dolaşıyor — cinnet (34:8), cin (34:12, 34:14, 34:41), bahçe (34:15, 34:16 ×2); 34:46 sekizinci. كثر [4/4] tamamlanıyor: dört anmada iki işlev — 34:35 karşılaştırma ('daha çoğuz'), 34:28, 34:36, 34:41 belirteç ('çoğu') (aday 1004). Esmâ: velî meleklerin Allah'a hitabı, ilâhî ama ortada; son-üçte mü'min insan → §4.3 mührü YANLIŞ.",
 42: "◇ 'O gün': يوم [4/4] tamamlanıyor. بعض iki kez [3,4/4] tamamlanıyor: 34:31'de 'birbirlerine söz çeviriyorlardı', 34:42'de 'birbirinize ne fayda ne zarar' — söz dönüyordu, fayda dönmüyor. ملك [3/3] tamamlanıyor: 34:22 'sahip değiller', 34:40 melekler, 34:42 'güç yetiremez' (lâ yemliku). ذوق [2/2]: 34:12 sapan cinlere alevli ateşten TATTIRIRIZ / 34:42 zalimlere 'TADIN' — aynı fiil, cin ve insan. xref 32:20 (ateşin azabını tadın, yalanladığınız — sûre 32 okundu). Konuşan 1P (neqûlu).",
 43: "◇ Âyetler okununca üç ayrı itiraz, üçü de aynı HASR kalıbıyla ('bu ancak ...'): bir ADAM (racül, adsız — 34:7'deki 'bir adam' ile aynı adsız atıf) · uydurulmuş YALAN (فري [2/2]: 34:8 'yalan mı uydurdu?' sorusunun cevabı gibi burada iddia) · apaçık SİHİR. قول üç kez [28,29,30/36]. Kâfirlerin sûredeki beşinci sözü (3 · 7 · 29 · 31 · 43). ★★ tek kaynak n z=2,29 (34 kelime). أيي [6/6], صدد [2/2], عبد [6/6] tamamlanıyor. Esmâ mübîn sihrin sıfatı → §4.3 mührü YANLIŞ. xref 46:7 (hakka 'apaçık sihir').",
 44: "◇ İki olumsuz: kitap vermedik · uyarıcı göndermedik — kendi iddialarının DAYANAĞI yok. كتب [2/2] tamamlanıyor: 34:3 'apaçık kitap' (her şeyin kaydı) / 34:44 'okuyacakları kitaplar' (verilmemiş). درس [1/1]. Konuşan 1P (âteynâ, erselnâ), muhatap 2MS (qableke).",
 45: "◇ Ölçek bu kez kesirli: 'verdiğimizin ONDA BİRİNE ulaşmadılar' — mi'şâr lemması korpusta YALNIZ bu ayette. say alanı mi'şâr'ı işaretliyor: bu DOĞRU pozitif (gerçek kesir, 1/10). Yalanlama iki kez (كذب [3,4/4] tamamlanıyor): öncekiler yalanladı · elçilerimi yalanladılar. Konuşan 1S'ye geçiyor: rusulî (elçilerim), nekîri (benim inkârım) — 34:44'te 1P idi; ayet sonundaki 1S zamiri yazımda düşük (nekîr). أتي [6/6] ve رسل [6/6] tamamlanıyor.",
 46: "◇ Sayı ifadeleri üst üste: 'BİR tek şey' (vâhide) · 'İKİŞER' (mesnâ) · 'TEKER TEKER' (furâdâ). say alanı ilk ikisini yakalıyor, furâdâ'yı YAKALAMIYOR (yanlış negatif; furâdâ lemması korpusta 2 ayette: 6:94, 34:46). Öğüt: kalkın, sonra düşünün (فكر [1/1]) — sonuç: 'arkadaşınızda cinnet yok'. جنن [8/8] burada tamamlanıyor ve 34:8'deki soruya ('onda cinnet mi var?') 38 ayet sonra cevap: 'yok'. عذب [9/9], نذر [4/4], يدي [4/4] tamamlanıyor. TARAYICI v4 ADAY VERDİ — sayı kelimeleri tetikledi, doğal olgu yok: çıpa değil, kesinlik 0/1. xref 7:184.",
 47: "◇ Ücret iki kez (أجر [1,2/2]): 'sizden istediğim sizin' · 'benim ücretim Allah'a'. سأل [3/3] tamamlanıyor: 34:25'te 'sorulmazsınız · sorulmayız', 34:47'de 'istedim' — soru/sorumluluk ile istemek aynı kökte. nakarat3 'alâ kulli şey' 34:21 ile (sûre içi; 34:21'de kaydedilen bağ doğrulandı): 34:21 Rab her şeyi KORUYAN (hafîz), 34:47 Allah her şeye ŞAHİT (şehîd). Mühür şehîd tekil, geçerli. أله [8/8] tamamlanıyor: lafız sûrede 8 ayette. كلل [6/6], شيأ [8/8] tamamlanıyor.",
 48: "◇ Yedi kelime. 'Rabbim hakkı fırlatır' — قذف [1/2]; ikinci anma 34:53'te (henüz okunmadı). Aynı fiil + hak 21:18'de de ('hakkı bâtılın üstüne fırlatırız', sûre 21 okundu). 'Gaybları bilen' — gayb burada ÇOĞUL (ğuyûb): غيب [3/4]: 34:3 âlimu'l-gayb (tekil) → 34:14 cinler gaybı bilmez → 34:48 allâmu'l-ğuyûb (mübalağa + çoğul). allâm esmâ listesinde yok (e_oto çıkmadı; lemma korpusta 4 ayette). علم [9/9] tamamlanıyor. ★★ tek kaynak rab z=2,72 (7 kelimede 1 Rab); fâsıla ğuyûb kafiye kırığı, yıldıza eklenmiyor. nakarat3 'qul inne Rabbî' sûre içinde 34:36, 34:39, 34:48 — üç ayet.",
 49: "◇ Sekiz kelime: hak geldi · bâtıl ne başlatır (يبدئ) ne tekrarlar (يعيد). بدأ ile عود korpusta 10 ayette birlikte; 34:49'da özne bâtıl ve iki fiil de olumsuz (öteki dokuzun özneleri bu okumada sayılmadı). حقق [6/6] ve جيأ [3/3] tamamlanıyor. xref 17:81 ('hak geldi, bâtıl yok oldu'). Kafiye kırığı (yu'îd, د): ★ kafiye kırığından — bilanço 'allah z=-0,53' yazıyor, YANLIŞ ETİKET (aday 1001; sûrenin üçüncü vakası, 34:18 ve 34:19'dan sonra).",
 50: "◇ Asimetrik şart çifti: 'sapsam — KENDİ aleyhime' (ضلل iki kez [3,4/4], tamamlanıyor) · 'doğru yolu bulursam — Rabbimin VAHYİYLE' (هدي [4/4] tamamlanıyor). Sapmanın faili ben, hidayetin kaynağı Rab — 34:25'teki asimetrinin (bizim 'suç'umuz / sizin 'amel'iniz) tekil konuşandaki karşılığı. Rab [14/14] tamamlanıyor. Mühür semî'-karîb ÇİFT, ton karma, geçerli; bu çift korpusta YALNIZ bu ayette (semî' ve karîb lemmaları birlikte 1 ayet).",
}
MEAL.update(MEAL5); M.update(M5)
MEAL6 = {
 51: "Korkuya kapıldıkları zaman bir görsen! Artık kaçış yoktur; yakın bir yerden yakalanmışlardır.",
 52: "'Ona inandık' derler. Ama uzak bir yerden (imana) erişmek onlar için nasıl mümkün olur?",
 53: "Oysa daha önce onu inkâr etmişlerdi; uzak bir yerden gayba taş atıp duruyorlardı.",
 54: "Daha önce benzerlerine yapıldığı gibi, kendileriyle arzuladıkları şey arasına engel konuldu. Çünkü onlar kuşku verici bir şüphe içindeydiler.",
}
M6 = {
 51: "◇ 'Bir görsen' (lev terâ) — nakarat3 sûre içinde 34:31 ile (34:31'de kaydedilen ileri bağ doğrulandı): 34:31'de Rab katında durdurulmuşlar, 34:51'de korkuya kapılmışlar. فزع [2/2]: 34:23'te kalplerden korku GİDERİLİYOR (fuzzi'a), 34:51'de korkuya KAPILIYORLAR (feziû) — aynı kök iki yönde. فوت [1/1] (yeni kök): kaçış yok. 'Yakın bir yerden' — karîb 34:50'de Rab'bin sıfatı (semî' karîb), 34:51'de mekânın sıfatı: قرب [3/3] tamamlanıyor; e_oto tokeni ama ilâhî değil → §4.3 mührü YANLIŞ. ★ tek kaynak pas z=1,57 (ühizû).",
 52: "◇ Geç gelen iman: 'inandık' (âmennâ) — أمن [11/11] tamamlanıyor; قول [36/36] tamamlanıyor: sûredeki son 'dediler'. Soru: 'uzak bir yerden erişmek nerede?' — tenâvüş (نوش, korpusta yalnız bu ayet): ★★★ tek kaynak hapaks z=3,28. Mekân üç ayettir ayet sonunda: 34:51 yakın · 34:52 uzak · 34:53 uzak; nakarat3 'min mekânin ba'îd' 34:52-53 (sûre içi).",
 53: "◇ قذف [2/2] tamamlanıyor ve iki anma TERS YÖNDE: 34:48'de Rab hakkı FIRLATIR, 34:53'te onlar gayba (zanla) taş ATAR — aynı fiil, iki özne, iki nesne (hak / gayb). غيب [4/4] tamamlanıyor: 34:3 gaybın bilicisi · 34:14 gaybı bilmeyen cinler · 34:48 gaybları çok bilen · 34:53 gayba atış. كفر [10/10] tamamlanıyor. بعد [5/5] tamamlanıyor: 34:8 'uzak sapıklık', 34:19 'uzaklaştır', 34:32 'sonra', 34:52-53 'uzak yer'.",
 54: "◇ Sûrenin son ayeti. İki edilgen: engel konuldu (hîle) · yapıldı (fu'ile) — fail adsız; EDİLGEN 2/4, ★★ tek kaynak pas z=2,52. بين [15,16/16] tamamlanıyor: sûrede 'ara' üç kez nimetten cezaya dönüyor — 34:18 aralarına görünen kasabalar · 34:19 'aramızı uzaklaştır' · 34:54 aralarına engel. شكك [2/2] tamamlanıyor: 34:21'de İblîs'e izin, âhirete inananı ondan ŞÜPHEDE olandan ayırmak içindi; sûre 'kuşku verici şüphe' (şekkin murîb) ile kapanıyor — ريب [1/1]. كون [16/16] tamamlanıyor. Lafız YOK, Rab YOK, esmâ yok: son dört ayette eksen sıfır.",
}
MEAL.update(MEAL6); M.update(M6)
