# -*- coding: utf-8 -*-
"""yasin_metin_1.py — sûre 36 (Yâsîn) meal ve matematikçi merceği, ayet 1-83.
Arapça sabit YOK: kökler yalnız korpus kök biçimiyle anılır, kelime biçimleri Latin harfle."""
MEAL = {}
M = {}
MEAL1 = {
 1: "Yâ Sîn.",
 2: "Hikmetli Kur'an'a andolsun ki,",
 3: "sen elbette gönderilen elçilerdensin,",
 4: "dosdoğru bir yol üzerindesin.",
 5: "(Bu Kur'an) mutlak güç sahibi, çok merhametli olanın indirmesidir;",
 6: "ataları uyarılmamış, bu yüzden gafil kalmış bir kavmi uyarman için.",
 7: "Andolsun, onların çoğu üzerine söz hak olmuştur; artık onlar iman etmezler.",
 8: "Biz onların boyunlarına halkalar geçirdik; o halkalar çenelerine kadardır, bu yüzden başları yukarı kalkık kalmıştır.",
 9: "Önlerine bir set, arkalarına bir set çektik; onları örttük, artık görmezler.",
 10: "Onları uyarsan da uyarmasan da onlar için birdir; iman etmezler.",
}
M1 = {
 1: "◇ Tek kelime, iki harf (hurûf-u mukattaa): n=1, kök yok, bağ yok. Ölçüm harf 21 → harf3 2 — yazım alanı harf adlarını değil işaretleri sayıyor. Fâsıla sınıfı ayrı (ٓ). Lafız YOK, Rab YOK, sınıf 0.",
 2: "◇ YEMİN (QASEM): 'hikmetli Kur'an'a andolsun'. Adlı aktör Kur'an (kitap, mecrur). Esmâ hakîm burada Kur'an'ın sıfatı → değil; §4.3 mühür e_oto EVET, e_el YOK: YANLIŞ MÜHÜR, sûrede ilk. حكم [1/1], قرأ [1/2]. n=2.",
 3: "◇ Yeminin cevabı: 'sen elbette gönderilenlerdensin' — 2MS, EMPH. رسل [1/8] (sûre içi 8 anma — sûre 35'te 6'ydı). n=3.",
 4: "◇ 'Dosdoğru bir yol üzerinde' — صرط [1/3], قوم [1/7]. 36:1-5 beş ayet: n = 1, 2, 3, 3, 3 — sûre beş kısa ayetle açılıyor (n 1-3); 36:2-5 fâsılası N sınıfı (م, ن).",
 5: "◇ 'Azîz ve rahîm olanın indirmesi': azîz-rahîm yüklem değil, tenzîl'in muzâfun ileyhi — tamlama içinde ad olarak esmâ, göndergesi Allah: e_el 'ilahi', aday 999'un ÜÇÜNCÜ vakası (34:6, 35:14, 36:5). §4.3 mühür ÇİFT geçerli, ton karma. Lafız YOK, Rab YOK — esmâ zamirsiz ve lafızsız: sınıf E. نزل [1/5], عزز [1/3], رحم [1/8].",
 6: "◇ Uyarma kökü iki kez, iki yönde: 'uyarman için' (tunzira, etken) / 'ataları uyarılmadı' (unzira, EDİLGEN) — نذر [1,2/6]. 7 kelimede 2 fiilin 1'i edilgen: ★★ tek kaynak pas z=2,52. Sonuç: gaflet (غفل [1/1]). أبو [1/1].",
 7: "◇ 'Söz onların çoğu üzerine hak oldu' — nakarat3 'haqqa'l-qavlu alâ' sûre içi, eşi 36:70 (defterden; kalıp korpusta yalnız bu iki ayette). say alanı ekser'i ('çoğu') sayı işareti saydı — belirteç, sayı değil (1004/1005 ailesi, yanlış pozitif). Fâsıla 'lâ yu'minûn' — 36:10 da aynı iki kelimeyle bitiyor.",
 8: "◇ DİKEY eksen: boyunlarda halkalar (ağlâl) → çenelere kadar (ezkân) → başlar yukarı kalkık (muqmahûn). Konuşan 1P (innâ ce'alnâ). قمح korpusta YALNIZ bu ayette: ★★★ tek kaynak hapaks z=3,28 (983 birikimi, hapaks kaynaklı). ذقن [1/1] — ezkân lemması korpusta 3 ayet; öteki ikisi 17:107 ve 17:109: 'çeneleri üzerine (yere) kapanırlar' (secde). Aynı organ zıt yönde: secdede çene yere / burada çene zincirde, baş yukarı. Yeni kökler ذقن ve قمح.",
 9: "◇ YATAY eksen: önlerinde set / arkalarında set — سدد [1,2/2] iki kez, ön ve arka; sonra 'örttük' (ağşeynâ, غشو [1/1]) → 'görmezler'. 36:8 dikey (boyun → çene → baş), 36:9 yatay (ön ↔ arka) + örtü: iki ayet, iki eksen, sonuç görmeme. جعل [2/5] iki ayette aynı fiil (ce'alnâ). بصر [1/2].",
 10: "◇ Simetrik bir eşitlik: 'uyarsan da uyarmasan da birdir' — نذر [3,4/6], olumlu/olumsuz aynı fiil; سوي [1/1]. 36:10, 2:6'nın 'inkâr edenler' öznesinden sonraki kısmıyla lemma lemma AYNI (morfoloji, 9 segment; 36:10 başta yalnız 've' ekliyor; xref iki üçlü). 'lâ yu'minûn' 36:7'yi tekrar ediyor: blok iki kez aynı sonuçla kapanıyor. Blokta نذر dört anma (36:6 ×2, 36:10 ×2), lafız ve Rab hiç yok.",
}
MEAL.update(MEAL1); M.update(M1)
MEAL2 = {
 11: "Sen ancak zikre uyan ve görmediği hâlde Rahmân'dan korkan kimseyi uyarırsın. Onu bağışlanma ve değerli bir ödülle müjdele.",
 12: "Şüphesiz ölüleri biz diriltiriz; onların önden gönderdiklerini ve bıraktıkları izleri yazarız. Her şeyi apaçık bir kitapta tek tek saymışızdır.",
 13: "Onlara o kasaba halkını örnek ver: Hani oraya elçiler gelmişti.",
 14: "Hani onlara iki elçi göndermiştik, onları yalanlamışlardı; biz de üçüncüsüyle destekledik. 'Biz size gönderilmiş elçileriz' dediler.",
 15: "Dediler ki: 'Siz ancak bizim gibi insanlarsınız. Rahmân hiçbir şey indirmemiştir. Siz ancak yalan söylüyorsunuz.'",
 16: "Dediler ki: 'Rabbimiz biliyor ki biz size elbette gönderilmiş elçileriz.",
 17: "Bize düşen ancak apaçık tebliğdir.'",
 18: "Dediler ki: 'Biz sizin yüzünüzden uğursuzluğa uğradık. Eğer vazgeçmezseniz sizi mutlaka taşlarız; bizden size acı bir azap dokunur.'",
 19: "Dediler ki: 'Uğursuzluğunuz sizinle beraberdir. Size öğüt verildi diye mi (böyle diyorsunuz)? Hayır, siz aşırı giden bir kavimsiniz.'",
 20: "Şehrin en uzak ucundan bir adam koşarak geldi. 'Ey kavmim, elçilere uyun' dedi.",
}
M2 = {
 11: "◇ Uyarının muhatabı daraltılıyor: 'ancak' zikre uyan ve 'gaybda Rahmân'dan korkan'. Aynı kalıp 35:18'de 'gaybda Rablerinden korkanlar'dı — burada Rab yerine Rahmân (xref 50:33: gaybda Rahmân'dan korkan). Rahmân sıfat değil bağımsız ad (nesne), göndergesi Allah: e_el 'ilahi' — e_el tanımı bu kullanımı saymıyor (aday 1019, 999 emsali). Müjde: bağışlanma + değerli ödül (ecrun kerîm; kerîm ödülün sıfatı → değil). 35:7 'mağfiret ve büyük ödül' ile aynı çift, sıfat değişiyor (kebîr → kerîm). نذر [5/6], خشي [1/1], غيب [1/1]. Lafız YOK, Rab YOK, sınıf oto E → el E.",
 12: "◇ Konuşan 1P, altı kez: diriltiriz · yazarız · saydık. İki yazım nesnesi: önden gönderdikleri (qaddemû) ve bıraktıkları izler (âsâr) — öne ve arkaya, 36:9'daki ön/arka ekseninin zaman karşılığı. 'Her şeyi saydık' (ahsaynâ): حصي [1/1], كلل [1/6], شيأ [1/10]; xref 78:29. Esmâ mübîn kitabın sıfatı → değil; §4.3 mühür e_oto EVET, e_el YOK: YANLIŞ MÜHÜR. حيي [1/5], موت [1/2]. Doğal olgu yok (diriltme anlatı), merdiven uygulanmadı.",
 13: "◇ Mesel açılışı: 'o kasabanın halkını örnek ver' — adsız aktör karye. ضرب [1/2], مثل [1/5], قري [1/1]. Elçiler geldi: رسل [2/8]. Fâsıla murselûn. Mesel anlatısı burada açılıyor; sınırı ileriki bloklarda okunacak.",
 14: "◇ Sayılı bir dizi: İKİ elçi → yalanladılar → ÜÇÜNCÜ ile destekledik. say alanı isneyn ve sâlis'i yakaladı: DOĞRU POZİTİF ×2. İkil şahıs 3D (iki elçi). عزز [2/3]: 36:5 'azîz' (esmâ) → 36:14 'azzeznâ' (destekledik) — aynı kök, Allah'ın sıfatı ve Allah'ın eylemi. كذب [1/2]. nakarat3 'innâ ileykum murselûn' sûre içi, eşi 36:16 (defterden). TARAYICI v4 ADAY VERDİ (F_ölçü — sayı kelimeleri), doğal olgu değil, merdiven uygulanmadı (35:1 ile aynı tetik).",
 15: "◇ Halkın cevabı, iki HASR: 'siz ANCAK bizim gibi insanlarsınız' / 'siz ANCAK yalan söylüyorsunuz'; arada 'Rahmân hiçbir şey indirmedi' (NEG 3). Rahmân bu kez inkârcıların ağzında, özne — gönderge yine Allah: e_el 'ilahi' (aday 1019). بشر [2/2] kapanıyor: 36:11 'müjdele' (beşşir) / 36:15 'beşer' (insan) — tek kök, iki anlam, gloss ikisini de taşıyor. كذب [2/2] kapanıyor: yalanladılar (36:14) → 'siz yalan söylüyorsunuz' (36:15) — suçlama yön değiştiriyor. nakarat3 'in entum illâ' sûre içi, eşi 36:47.",
 16: "◇ Elçilerin ikinci cümlesi, 36:14'ün PEKİŞTİRİLMİŞİ: 'innâ ileykum murselûn' → 'innâ ileykum LE-murselûn' (lâm-ı tekit eklendi) ve tanık olarak 'Rabbimiz biliyor'. İddia → inkâr → tekitli iddia. 6 kelimede bir Rab: ★★★ tek kaynak rab z=3,23 — 35:15/35:17'deki kısa ayet lafız şişmesinin Rab karşılığı (aday 1020, 1012 ailesi). Sûrede ilk Rab. ربب [1/6], علم [1/8], رسل [5/8]. xref 21:4.",
 17: "◇ 5 kelime, HASR: 'bize düşen ANCAK apaçık tebliğ'. بلغ [1/1]. Esmâ mübîn tebliğin sıfatı → değil; YANLIŞ MÜHÜR (36:12 ile aynı kelime, aynı karar). Elçilerin sözü 36:16-17 iki ayete yayılıyor.",
 18: "◇ Halkın ikinci cevabı, tehdit: 'sizin yüzünüzden uğursuzluğa uğradık' (tetayyernâ) → vazgeçmezseniz TAŞLARIZ → acı azap dokunur. Pekiştirme (EMPH) 5 — blokta en yüksek kip sayısı (36:11-20 ölçüm satırları). طير [1/2] uğursuzluk anlamında; gloss 'kuş; uçan', uğursuzluk anlamı yok (aday 1000 ailesi). رجم [1/1], مسس [1/1], عذب [1/1], ألم [1/1]. xref 11:48 (acı azap dokunur).",
 19: "◇ Elçilerin cevabı: 'uğursuzluğunuz SİZİNLE' — طير [2/2] kapanıyor; uğursuzluk dışarıdan (elçilerden) içeriye (onların kendisine) çevriliyor: 36:18'in tersine çevrilmesi. 'Size öğüt verildi diye mi' (zukkirtum, EDİLGEN): ★★ tek kaynak pas z=2,52. IDRAB: 'hayır, siz aşırı giden bir kavimsiniz' — سرف [1/1]. ذكر [2/3] (36:11 'zikre uyan'). TARAYICI v4 ADAY VERDİ (şart; طير kökü 'kuş' olarak tetikliyor olabilir), doğal olgu yok.",
 20: "◇ Yeni aktör: adsız bir adam (racül), şehrin EN UZAK ucundan, KOŞARAK. 36:13'te 'kasaba' (karye, قري [1/1]), burada 'şehir' (medîne, مدن [1/1]) — aynı yer iki adla. Nidâ: 'ey kavmim, elçilere uyun' — تبع [2/3]: 36:11 'zikre uyan' / 36:20 'elçilere uyun'. Konuşma sırası 36:14-20: elçiler (14) → halk (15) → elçiler (16-17) → halk (18) → elçiler (19) → adam (20); قول kökü yedi ayetin altısında (14, 15, 16, 18, 19, 20). Fâsıla murselîn: 36:1-20'de mursel- ile biten ayet 5 (3, 13, 14, 16, 20).",
}
MEAL.update(MEAL2); M.update(M2)
MEAL3 = {
 21: "Sizden hiçbir ücret istemeyen, kendileri de doğru yolda olan kimselere uyun.",
 22: "Hem bana ne oluyor ki beni yaratana kulluk etmeyeyim? Siz de O'na döndürüleceksiniz.",
 23: "O'ndan başka ilâhlar mı edineyim? Rahmân bana bir zarar dilerse, onların şefaati bana hiçbir fayda vermez, beni kurtaramazlar da.",
 24: "O takdirde ben apaçık bir sapıklık içinde olurum.",
 25: "Ben sizin Rabbinize iman ettim; beni dinleyin.",
 26: "(Ona) 'Cennete gir' denildi. Dedi ki: 'Keşke kavmim bilseydi,'",
 27: "'Rabbimin beni bağışladığını ve beni ikram edilenlerden kıldığını.'",
 28: "Ondan sonra kavminin üzerine gökten hiçbir ordu indirmedik; indirecek de değildik.",
 29: "Yalnızca tek bir çığlık oldu; bir de baktılar ki sönüp gitmişler.",
 30: "Yazık şu kullara! Kendilerine hiçbir elçi gelmez ki onunla alay ediyor olmasınlar.",
}
M3 = {
 21: "◇ Adamın sözü sürüyor: 36:20'nin emri ('ittebi'û') ikinci kez, bu kez elçilerin iki niteliğiyle — biri olumsuz (ücret istemez), biri olumlu (hidayettedir). تبع [3/3] kapanıyor (36:11 zikre uyan · 36:20 · 36:21). أجر [2/2] kapanıyor: 36:11 'ecrun kerîm' (ödül) / 36:21 'ecran' (ücret) — tek kök, verilen ve istenmeyen karşılık. سأل [1/1], هدي [1/1]. 7 kelime, yıldız yok, bağ yok.\n◈K — —\n◈B — —\n◈D — D1 emir (IMPV 1) + olumsuz sıla (NEG 1) + hâl cümlesi ('ve hum muhtedûn'); D3 aynı emir fiili iki ardışık ayette (36:20-21) — pekiştirme; D4 muhatap 2MP 3, konuşan ayette 1. şahısla görünmüyor.\n◈A — A1 konuşan 36:20'deki adsız adam, muhatap kavmi, konu elçiler (3MP); A2 şehir (36:20 medîne); A4 adamın konuşması sürüyor.",
 22: "◇ Konuşma 1S'ye dönüyor: adam kendini örnek veriyor. Soru (INTG) + olumsuz: 'bana ne oluyor ki kulluk etmeyeyim'. Kulluğun nesnesi ad değil sıla: 'beni yaratan' (fatara-nî) — فطر [1/1]. Son cümle 2MP: 'O'na döndürüleceksiniz' (turja'ûn, EDİLGEN): ★ tek kaynak pas z=1,57 (kafiye kırığı yok, kaynak doğru). عبد [1/4], رجع [1/5]. İçerik lemması yok: son3 boş, mühür değerlendirilemez.\n◈K — —\n◈B — —\n◈D — D1 istifhâm-ı inkârî (soru biçiminde olumsuzlama); D4 ayet içinde zamir 1S → 2MP ('beni yaratan' / 'döndürüleceksiniz'); konuşan değişmiyor, değişen muhatap — iltifât alanı 0 doğru; döndüren fail edilgenle adlanmıyor.\n◈A — A1 konuşan adam, kendini (1S) örnek olarak koyuyor; A3 muhatap kavim; A4 konuşma sürüyor.",
 23: "◇ Blokun en uzun ayeti (15 kelime; blokta n 4-15, tek). İki soru-şart: 'O'ndan başka ilâhlar mı edineyim?' → 'Rahmân bir zarar dilerse' → iki olumsuz sonuç (şefaatleri fayda vermez · kurtaramazlar). أله [1/5]: sûrede أله kökünün İLK tokeni lafız değil 'âlihe' (ilâhlar, çoğul) — 36:1-30 lafız 0 (korpus sayımı). Rahmân üçüncü kez bağımsız ad (36:11 nesne · 36:15 özne · 36:23 şart cümlesinde özne): e_el 'ilahi', tanım dışı (aday 1019). رحم [4/8], ضرر [1/1], غني [1/1], شفع [1/1], نقذ [1/2]. nakarat3 'ittehaze min dûn' sûre içi 2 ayet → eşi 36:74 (defterden; henüz okunmadı); kalıp korpusta 8 ayette (19:17 · 19:81 · 25:3 · 25:18 · 36:23 · 36:74 · 39:3 · 39:43). xref 53:26 (şefaat hiçbir şey fayda vermez). Esmâ sınıf oto E → el E, mühür yok.\n◈K — —\n◈B — —\n◈D — D1 soru + şart (COND 1 · INTG 1 · NEG 2); D2 cevap iki olumsuzla kuruluyor ('lâ tuğnî … ve lâ yunqizûn'); D4 1S 4 (konuşan) · 3MP 3 — edinilen ilâhlar akıllı eril çoğul zamirle anılıyor (şefâatu-hum, yunqizûn) · 3FS 1 (şefaat).\n◈A — A1 aktörler: adam (1S), Rahmân, adsız 'ilâhlar' (3MP); A3 konuşan adam, muhatap kavim; A4 sürüyor.",
 24: "◇ 5 kelime: 36:23'ün sonucu — 'o takdirde (izen) ben apaçık sapıklıktayım'. Tekit (inne + lâm, EMPH 1). Esmâ mübîn sapıklığın sıfatı → değil; §4.3 mühür e_oto EVET, e_el YOK: YANLIŞ MÜHÜR (sûrede mübîn için üçüncü: 36:12 kitap · 36:17 tebliğ · 36:24 sapıklık). ضلل [1/3], بين [4/9].\n◈K — —\n◈B — —\n◈D — D1 tekitli haber; D2 'izen' (o takdirde) şart-sonuç bağı: 36:23 şart, 36:24 sonuç — mantıksal birim iki ayete yayılıyor; D4 1S 1.\n◈A — A3 konuşan adam; A4 sürüyor.",
 25: "◇ 4 kelime, blokun en kısa ayeti (tek): 'sizin Rabbinize iman ettim, beni dinleyin'. Rab sûrede ikinci kez (ربب [2/6]); 36:16'dan sonra. ★★★ tek kaynak rab z=5,01 — 36:16'daki kısa ayet Rab şişmesinin ikinci vakası (aday 1020: 36:16 6 kelime z=3,23 · 36:25 4 kelime z=5,01). أمن [3/4], سمع [1/1]. Rab'bin iyelik eki: 36:22 'beni yaratan' (1S sıla) → 36:25 'sizin Rabbiniz' (2MP).\n◈K — —\n◈B — —\n◈D — D1 haber + emir ('fe'smeûn', IMPV 1); D4 1S 4 · 2MP 3.\n◈A — A3 konuşan adam; muhatap 2MP — kavim mi elçiler mi ayetten belirlenemiyor; 36:20 nidâsına (ey kavmim) göre kavim okunuyor; A4 adamın dünya sahnesindeki son sözü (36:26'da sahne değişiyor).",
 26: "◇ Sahne sıçraması: 'Cennete gir' DENİLDİ (qîle, EDİLGEN; söyleyen adlanmıyor, pas z=1,10, yıldız yok). Adamın 36:25 ile 36:26 arasındaki akıbeti metinde yok — anlatı doğrudan cennet emrine geçiyor (okuma gözlemi, KAPATILAMAZ). Kök ikilemesi قول ×2 [8,9/20]: edilgen qîle / etken qâle. Nidâ-temenni 'yâ leyte qavmî ya'lemûn': 36:20 'yâ qavmi' ile aynı hitap, artık ulaşamayacağı kavme. Aktör adlı cennet (yer, meful). جنن [1/3], دخل [1/1], علم [2/8], قوم [5/7]. xref 2:111, 18:39.\n◈K — —\n◈B — —\n◈D — D1 emir (IMPV 1) + temenni nidâsı (VOC 1); D3 aynı kökün edilgen ve etken biçimi art arda; D4 2MS 1 (emir) · 1S 1 · 3MP 2 · 3MS 2 — ayette üç şahıs.\n◈A — A2 sahne dünya → cennet; A3 konuşan önce adsız/edilgen ses, sonra adam; A4 adamın dünya anlatısı kapandı, cennet sahnesi açıldı.",
 27: "◇ 36:26'nın cümlesi sürüyor ('keşke bilseydiler — Rabbimin beni bağışladığını…'): ayet sınırı cümleyi bölüyor. Rab üçüncü kez (ربب [3/6]) ve ilk kez 1S iyelikli: 'Rabbî'. Aynı konuşanda Rab'bin eki 36:25 'sizin' → 36:27 'benim'. ★★ tek kaynak rab z=2,72 (7 kelime). غفر [2/2] ve كرم [2/2] kapanıyor; أجر [2/2] 36:21'de kapanmıştı: 36:11 müjdesinin üç kökü (mağfiret · ecr · kerîm) 36:21-27 arasında bu adamın sözünde yeniden geçiyor (okuma gözlemi, KAPATILAMAZ). جعل [3/5].\n◈K — —\n◈B — —\n◈D — D1 haber (PERF 2), 'bimâ' ile 36:26'daki 'ya'lemûn'un nesnesi; D2 'mukramîn' edilgen ism-i meful — ikram eden adlanmıyor; D4 1S 3 · 3MS 2.\n◈A — A2 cennet; A3 konuşan adam, söz kavmine yönelik dilek; A4 cennet sahnesi bu ayette kapanıyor (36:28'de konuşan değişiyor).",
 28: "◇ Konuşan değişiyor: adamın 1S'i → 1P (4). Kök ikilemesi نزل ×2 [3,4/5]: 'indirmedik' (enzelnâ, PERF) / 'indirecek de değildik' (munzilîn, ism-i fail) — iki olumsuz (NEG 2): olay ve âdet birlikte olumsuzlanıyor. 'min ba'dihî' (ondan, adamdan sonra). Ordu gökten (جند [1/2], سمو [1/2]). قوم [6/7], بعد [1/1], كون [1/15]. 🜁 L0 — gök yalnız indirmenin çıkış yeri olarak adlanıyor, süreç yok (olgu evet, çıpa hayır); tarayıcı vermedi.\n◈K — K1 gök (سمو); K2 geçmiş, 'adamdan sonra'; K4 hareket fiili 'indirmek' — özne 1P, nesne ordu, olumsuz.\n◈B — —\n◈D — D1 olumsuz haber ×2; D3 aynı kök fiil + ism-i fail (eylem / sıfat); D4 1P 4 · 3MS 2 — ayetler arası konuşan değişimi (alan ayet içini ölçüyor, iltifât 0).\n◈A — A2 sahne cennetten kavme (dünya) dönüyor; A3 anlatıcı 1P; A4 kasaba meselinin (36:13) kavim kolu yeniden açılıyor.",
 29: "◇ HASR (in … illâ): 'yalnızca TEK bir çığlık oldu'. say işareti vâhide — DOĞRU POZİTİF ('tek', sayı). 'fe-izâ hum hâmidûn': ani sonuç (fe-izâ) + 'sönmüşler' — خمد [1/1] 'sönme, ateşin bitmesi' insanlar için. صيح [1/3], وحد [1/3], كون [2/15]. nakarat3 iki kalıp: 7 kelimelik 'in kânet illâ sayhaten vâhideten fe-izâ hum' sûre içi 2 ayet → eşi 36:53; 3 kelimelik 'illâ sayhaten vâhideten' 3 ayet → 36:49, 36:53 (defterden; ikisi de henüz okunmadı). Çığlığın faili adlanmıyor.\n◈K — —\n◈B — —\n◈D — D1 HASR'lı haber (NEG 1 · RES 1); D2 istiâre: ateşin sönmesi fiili (hâmid) insan topluluğu için; mufâcee 'fe-izâ'; D4 3FS 1 · 3MP 1.\n◈A — A1 aktör adsız kavim (hum); A2 kasaba, helâk anı; A4 kavmin akıbeti tek ayette anlatılıyor.",
 30: "◇ Nidâ (yâ hasraten) + HASR (mâ … illâ): 'yazık kullara — gelen her elçiyle alay ettiler'. Muzari + kâne: tek olay değil süren örüntü. رسل [7/8] — elçi ipliği sûrede 8 tokenin 7.'si. عبد [2/4]: 36:22 'kulluk ederim' / 36:30 'kullar'. هزأ [1/1], أتي [1/2]. GLOSS: حسر 'yorgunluk, bitkinlik' — ayetteki anlam hasret/pişmanlık; korpus TAM SAYIM 12 token: hasra 7 · hasrat 1 · hasratâ 1 (pişmanlık, 9) / mahsûr · yestahsir · hasîr (yorgunluk, 3) — baskın lemma gloss'ta yok (aday 1015 ailesi, ظلل vakasının eşi). nakarat3 'mâ ye'tî … min' sûre içi 2 ayet → eşi 36:46 (defterden; henüz okunmadı). xref 9:65, 15:11.\n◈K — —\n◈B — —\n◈D — D1 nidâ (VOC 1) + HASR (NEG 1 · RES 1); D3 'mâ ye'tîhim … illâ kânû' genel-zaman kalıbı; D4 3MP 5 · 3MS 2 — hasret nidâsının konuşanı adlanmıyor.\n◈A — A1 aktör kasaba halkından 'kullar'a (ibâd) genişliyor; A2 sahne zamansızlaşıyor; A4 mesel anlatısından genel hükme geçiş.",
}
MEAL.update(MEAL3); M.update(M3)
MEAL4 = {
 31: "Görmediler mi, kendilerinden önce nice nesilleri helâk ettik; onlar artık kendilerine dönmüyorlar.",
 32: "Hepsi de toplanmış olarak mutlaka huzurumuza getirilecekler.",
 33: "Ölü toprak onlar için bir âyettir: onu dirilttik, ondan tane çıkardık; işte ondan yerler.",
 34: "Orada hurmalıklardan ve üzüm bağlarından bahçeler kıldık, içinde pınarlar fışkırttık,",
 35: "ki onun meyvesinden yesinler — bunu onların elleri yapmadı. Hâlâ şükretmeyecekler mi?",
 36: "Yerin bitirdiklerinden, kendilerinden ve bilmedikleri şeylerden bütün çiftleri yaratan her türlü eksiklikten uzaktır.",
 37: "Gece de onlar için bir âyettir: gündüzü ondan sıyırırız, bir de bakarsın karanlıkta kalmışlar.",
 38: "Güneş de kendisine ait bir karar yerine doğru akar. Bu, Azîz ve Alîm olanın takdiridir.",
 39: "Ay için de konaklar takdir ettik; sonunda eski, kuru hurma salkımı sapı gibi döner.",
 40: "Ne güneşe ayı yakalamak yaraşır, ne de gece gündüzü geçebilir. Her biri bir yörüngede yüzer.",
}
M4 = {
 31: "◇ Soru (INTG) + NEG 2: 'görmediler mi, nice nesli helâk ettik'. 36:30'un 'kullar'ı burada 'nesiller' (kurûn) — genelleme tarihe uzanıyor. 'kem' çokluk bildiriyor, sayı vermiyor (say alanı boş, doğru). رجع [2/5]: 36:22 'O'na döndürüleceksiniz' / 36:31 'onlara dönmezler' — aynı kök, iki yön. هلك [1/1], قبل [1/1], قرن [1/1], رأي [1/3]. Konuşan 1P 2. xref 6:6.\n◈K — —\n◈B — —\n◈D — D1 olumsuz soru (istifhâm-ı takrîrî) + 'enne' ile bağlı ikinci olumsuz; D4 1P 2 · 3MP 7 — 'onlar' iki ayrı topluluk: görmeyenler ve helâk edilenler.\n◈A — A1 aktörler adsız: muhataplar (3MP) ve önceki nesiller; A2 tarih (geçmiş); A4 kasaba meselinden geçmiş nesillere geçiş.",
 32: "◇ 6 kelime, blokun en kısa ayeti (tek; blokta n 6-15). ISTISNA biçimi (in … lemmâ): 'hepsi toplanmış olarak huzurumuza getirilecek'. كلل [2/6], جمع [1/2], حضر [1/3]. 'ledeynâ' 1P 1. nakarat3 'cemî'un ledeynâ muhdarûn' sûre içi 2 ayet → eşi 36:53 (defterden; henüz okunmadı).\n◈K — —\n◈B — —\n◈D — D1 haber, in-muhaffefe + lemmâ (ISTISNA); D2 tekit; 'muhdarûn' edilgen ism-i meful — getiren adlanmıyor; D4 1P 1.\n◈A — A2 sahne: huzur (ledeynâ) — ertelenmiş; A4 31'in geçmişi 32'de geleceğe bağlanıyor.",
 33: "◇ Yeni bölüm açılışı: 've âyetun lehum' — أيي [1/6], sûrede 'âyet' kökünün İLK tokeni. Zincir: ölü yer → dirilttik → tane çıkardık → ondan yerler (fe-minhu). حيي ve موت çifti 36:12'de insan için ('ölüleri diriltiriz', ikisi de [1/x]), burada yer için (موت [2/2], حيي [2/5]) — okuma gözlemi, KAPATILAMAZ. 1P 4. GLOSS: حبب 'sevgi, sevme' — ayette habb (tane); korpus TAM SAYIM 95 token: ahbeb 64 · hubb 9 · habb 7 · habbe 5 … — 'tane' anlamı (12 token) gloss'ta yok (aday 1021). أرض [1/3], خرج [1/1], أكل [1/3]. 🜁 L2 — diriltme → çıkış → yeme nedensel zinciri; yağmur adlanmıyor (35:9 emsali L2); olgu evet, çıpa hayır; tarayıcı vermedi.\n◈K — K1 yer (أرض); K4 diriltme ve çıkarma fiilleri — özne 1P, nesne yer ve tane.\n◈B — B1 bitki ürünü (tane); B4 ölü → diri yönünde, yer için (ölüm/dirim fiilleri cansız özneye).\n◈D — D1 haber; D2 âyet + açıklayıcı fiil cümlesi (ölü yer → ahyeynâhâ); D4 1P 4 · 3FS 2 · 3MP 3.\n◈A — A4 anlatıdan (36:13-32) delil listesine geçiş: aktör yok, sahne yeryüzü.",
 34: "◇ 36:33'ün devamı: bahçeler (hurma + üzüm) ve pınarlar. جنن [2/3]: 36:26 'cennet' / 36:34 'bahçeler' — tek kök, iki anlam. جعل [4/5], نخل [1/1], عنب [1/1], فجر [1/1], عين [1/2]. 1P 4, iki fiil (kıldık · fışkırttık). xref 17:91 (hurma, üzüm, fışkırtma). 🜁 L1 — bitki ve su yapıları yer alanında adlanıyor, aralarında ilişki kurulmuyor (27:61 emsali); olgu evet, çıpa hayır.\n◈K — —\n◈B — B1 hurma, üzüm (bitki türleri); B3 tetik عين — burada anlam pınar, organ değil.\n◈D — D1 haber, iki PERF 1P fiil; D3 'fîhâ' iki kez (orada · içinde) — yer zamiri tekrarı; D4 1P 4 · 3FS 2.\n◈A — —",
 35: "◇ Amaç (li-ye'kulû) + soru (e-felâ yeşkurûn). 'mâ amilethu eydîhim' iki okumaya açık: nâfiye (elleri yapmadı — meal bu) ya da mevsûle (ellerinin yaptıkları). أكل [2/3], ثمر [1/1], عمل [1/3], يدي [2/6], شكر [1/2]. TARAYICI v4 ADAY VERDİ. 🜁 L2 — nâfiye okumasıyla YETİ SINIRI (27:60 emsali); mevsûle okunursa L1. Kademe i'râb seçimine bağlı, KAPATILAMAZ; olgu evet, çıpa hayır.\n◈K — —\n◈B — B1 meyve; B3 organ el (يدي) — iş yapma işleviyle, olumsuzlanmış (nâfiye okumasında).\n◈D — D1 amaç cümlesi + olumsuz soru (INTG 1 · NEG 2); D2 'mâ' çok anlamlılığı (nâfiye/mevsûle) — ölçüm alanı ayırt etmiyor; D4 3MP 5.\n◈A — —",
 36: "◇ Tesbih açılışı: 'subhâne'llezî' — سبح [1/3]; özne ad değil sıla (36:22 'ellezî fataranî' gibi). خلق [1/10]: sûrede خلق kökünün İLK tokeni. Çiftlerin üç alanı: yerin bitirdiği · kendileri (enfus) · bilmedikleri. say alanı زوج'u işaretledi — YANLIŞ POZİTİF (zevc 'eş/çift' tür adı, sayı değil; aday 1005 ailesi). كلل [3/6], نبت [1/1], أرض [2/3], نفس [1/2], علم [3/8]. xref 43:12. 🜁 L1 — çift kavramı üç alana dağıtılıyor, sınıflara üye eşlenmiyor (29:40 ölçütü; 30:22, 35:27 emsali); olgu evet, çıpa hayır; tarayıcı vermedi.\n◈K — —\n◈B — B1 bitki (yerin bitirdiği), insan (enfus), bilinmeyen; B2 oluşum: çift (زوج) — aşama yok, yalnız çiftlilik; yaratma fiili (خلق).\n◈D — D1 tenzih kalıbı (subhâne + sıla); D3 'min' üç kez (mimmâ · min · mimmâ) paralel üçlü; D4 3MP 3 · 3FS 2 · 3MS 1.\n◈A — —",
 37: "◇ İkinci 've âyetun lehum' — أيي [2/6]; 36:33 ile aynı iki kelimelik açılış (nakarat3'ün 3 kelime alt sınırı altında, ikili alanı da boş — eşleşme okumada görüldü). 'Gündüzü geceden sıyırırız' — سلخ [1/1] (sûre için eklenen kök) → 'bir de bakarsın karanlıktalar' (fe-izâ). GLOSS: نهر 'ırmak' — ayette nehâr (gündüz); korpus TAM SAYIM 113 token: nehâr 57 · nehar 54 · tenher 2 — BASKIN lemma 'gündüz' gloss'ta YOK (aday 1021; ظلل vakası tipi). ظلم [1/2] 'muzlimûn' karanlık anlamında, gloss 'zulüm' (aday 1015 kaydı: zulumât). ليل [1/2]. 🜁 L2 — sıyırma → karanlık sonucu nedensel bağlanıyor; 31:29 ve 35:13 (karşılıklı geçiş) L1'di (1010 ailesi: yakın olgu, farklı kademe); olgu evet, çıpa hayır; tarayıcı vermedi.\n◈K — K1 gece, gündüz; K2 döngüsel şimdi (IMPF 'nesleḫu'); K4 sıyırma fiili — özne 1P, nesne gündüz, kaynak gece.\n◈B — —\n◈D — D2 istiâre: deri/kabuk sıyırma fiili (سلخ) gündüz için; mufâcee 'fe-izâ' (36:29 ile aynı yapı); D4 1P 1 · 3MP 2.\n◈A — —",
 38: "◇ Güneş 'kendisine ait bir karar yerine' akar (li-mustaqarrin lehâ). Kapanış: 'bu, Azîz ve Alîm'in takdiri' — tamlama içinde ad, göndergesi Allah: e_el 'ilahi' ×2 (aday 999, dördüncü vaka: 34:6, 35:14, 36:5, 36:38). §4.3 mühür ÇİFT, geçerli, ton karma; sınıf oto E → el E. عزز [3/3] kapanıyor: 36:5 azîz · 36:14 azzeznâ · 36:38 azîz. علم [4/8], شمس [1/2], جري [1/1], قرر [1/1], قدر [1/3]. xref 6:96, 41:12 (aynı terkip). 🜁 L1 — akış + varış yeri; 'takdîr' ölçü adı ama birim ve sayı yok (35:13 emsali); olgu evet, çıpa hayır; tarayıcı vermedi.\n◈K — K1 güneş; K2 yönlü süreç: bir karar yerine doğru (ertelenmiş son nokta); K4 akma fiili — özne güneş, öznenin kendisi; düzenleyen 'takdîr' ile adlanıyor.\n◈B — —\n◈D — D1 haber; D2 işaret zamiri (zâlike) ile hüküm cümlesi + çift esmâ kapanışı; D4 3FS 2.\n◈A — —",
 39: "◇ 7 kelime. 'Ay için konaklar takdir ettik' — قدر [2/3]: 36:38 isim (takdîr) → 36:39 fiil 1P (qaddarnâhu). نزل [5/5] kapanıyor: 36:5 tenzîl · 36:15 enzele · 36:28 enzelnâ/munzilîn · 36:39 menâzil (inilen yer). Sonuç: 'eski kuru hurma salkımı sapı gibi döner' — عرجن [1/1] HAPAKS: ★★★ tek kaynak hapaks z=3,28 (983 ailesi; sûrede ikinci, 36:8 قمح). قمر [1/2], عود [1/1], قدم [2/2] (36:12 qaddemû / 36:39 qadîm). 🜁 L1 — ölçü fiili + birim adı (menâzil) var, SAYI yok: L4 ölçü koluna sınırda (32:5'te sayı ve karşılaştırma vardı; 30:4 belirsiz nicelik emsali); benzetmede karşılaştırma var ama algı/durum ayrımı yok → L3 değil. Olgu evet, çıpa hayır; tarayıcı vermedi.\n◈K — K1 ay; K2 evreli süreç, uç noktası adlı ('hattâ âde'); K3 ölçek birimi: menzil (sayısız); K4 takdir fiili — özne 1P, nesne ay.\n◈B — B1 bitki parçası (hurma salkımı sapı) — benzetmenin tabanı, canlı olarak değil.\n◈D — D1 haber (PERF 2); D2 teşbih (ke-) + 'hattâ' ile süreç sonu; D4 1P 2 · 3MS 2.\n◈A — —",
 40: "◇ Blokun en uzun ayeti (15 kelime, tek). İki paralel olumsuz (NEG 2): güneş ayı yakalayamaz / gece gündüzü geçemez — çiftler 36:38-39 (güneş, ay) ve 36:37 (gece, gündüz) çiftlerini birleştiriyor. Dört iplik birden kapanıyor: شمس [2/2], قمر [2/2], ليل [2/2], نهر [2/2]. Kapanış: 'her biri bir yörüngede yüzer' — سبح [2/3]: 36:36 subhân (tenzih) / 36:40 yesbehûn (yüzerler) — tek kök iki anlam; gloss 'tesbih, tenzih' yüzme anlamını taşımıyor (korpus: yesbah 2 · sabh 2 · sâbiha 1 = 5/92; aday 1021). كلل [4/6], فلك [1/2], بغي [1/2] (yenbeğî, gloss'ta var), درك [1/1], سبق [1/2]. xref 21:33. 🜁 L2 — güneş için YETİ SINIRI ('yaraşmaz/yetişemez') + her birinin ayrı yörüngesi; süreç nasıl işliyor adlanmıyor → L4 değil; olgu evet, çıpa hayır; tarayıcı vermedi.\n◈K — K1 güneş, ay, gece, gündüz, felek; K2 süren şimdi (IMPF 3), sınırsız; K3 tekil cisimden 'hepsi'ne (kullun); K4 hareket fiilleri yakalamak, öne geçmek, yüzmek — özneler gök cisimleri ve vakitler, 1P özne yok.\n◈B — —\n◈D — D1 olumsuz haber ×2 (lâ … ve lâ …); D2 paralellik (güneş/ay — gece/gündüz); D4 3MP 2: gök cisimleri 'yesbehûn' ile akıllı eril çoğul fiille anılıyor (36:23 putlar için aynı zamir gözlemi).\n◈A — —",
}
MEAL.update(MEAL4); M.update(M4)
MEAL5 = {
 41: "Onların zürriyetini dolu gemide taşımamız da onlar için bir âyettir.",
 42: "Onun benzerinden binecekleri şeyler de yarattık.",
 43: "Dilersek onları boğarız; o zaman ne yardımlarına koşan olur, ne de kurtarılırlar —",
 44: "ancak tarafımızdan bir rahmet ve bir süreye kadar faydalandırma olarak (kurtarılırlar).",
 45: "Onlara: 'Önünüzdekinden ve arkanızdakinden sakının, umulur ki merhamet olunursunuz' denildiğinde (yüz çevirirler).",
 46: "Rablerinin âyetlerinden kendilerine hiçbir âyet gelmez ki ondan yüz çeviriyor olmasınlar.",
 47: "Onlara: 'Allah'ın size verdiği rızıktan harcayın' denildiğinde, inkâr edenler iman edenlere dedi ki: 'Allah dileseydi kendisinin doyuracağı kimseyi mi biz doyuracağız? Siz ancak apaçık bir sapıklık içindesiniz.'",
 48: "Ve diyorlar ki: 'Doğru söyleyenlerseniz, bu vaat ne zaman?'",
 49: "Onlar yalnızca tek bir çığlığı bekliyorlar; o, onlar çekişip dururken onları yakalayıverir.",
 50: "O zaman ne bir vasiyette bulunabilirler, ne de ailelerine dönebilirler.",
}
M5 = {
 41: "◇ Üçüncü 've âyetun lehum' — أيي [3/6] (36:33 ölü yer · 36:37 gece · 36:41 gemi). Konuşan 1P 3: 'zürriyetlerini dolu gemide taşıdık'. فلك [2/2] kapanıyor: 36:40 felek (yörünge, lemma felek) / 36:41 fulk (gemi, lemma fulk) — ardışık iki ayette tek kök, iki lemma, iki anlam; gloss 'gemi, felek' ikisini de taşıyor. حمل [1/1], ذرر [1/1], شحن [1/1]. 🜁 L1 — gemi adlanıyor + işlevi (taşıma); olgu HAYIR (araç, doğal süreç değil; 28:73 adlandırma+işlev emsali); çıpa hayır; tarayıcı vermedi.\n◈K — K1 tetik فلك — burada anlam gemi (fulk), gök cismi değil.\n◈B — B1 insan soyu (zürriyet); tetik حمل — burada anlam taşıma, gebelik değil.\n◈D — D1 haber, 'enne' ile isim cümlesine bağlı âyet açıklaması (36:33, 36:37'de fiil cümlesiydi); D4 1P 3 · 3MP 2.\n◈A — A1 adsız 'onlar' ve zürriyetleri; A2 deniz/gemi.",
 42: "◇ 6 kelime: 'onun benzerinden binecekleri şeyler yarattık' — benzerin neyin benzeri olduğu zamirle (mislihî) gemiye dönüyor; neyin kastedildiği adlanmıyor. خلق [2/10] (36:36 çiftleri yaratan), مثل [3/5], ركب [1/2]. 1P 2.\n◈K — —\n◈B — B2 tetik خلق — yaratma fiili, nesne binekler (adsız).\n◈D — D1 haber; D2 belirsiz ism-i mevsul 'mâ yerkebûn' — nesne adlanmıyor; D4 1P 2 · 3MP 3.\n◈A — —",
 43: "◇ Şart: 'dilersek boğarız' → iki olumsuz sonuç (NEG 2): yardıma koşan yok · kurtarılmazlar (yunqazûn, EDİLGEN): ★ tek kaynak pas z=1,57 (kırık yok). نقذ [2/2] kapanıyor: 36:23 'putlar beni kurtaramazlar' (etken) / 36:43 'kurtarılmazlar' (edilgen). شيأ [4/10], غرق [1/1], صرخ [1/1].\n◈K — —\n◈B — B4 ölüm (boğulma) — şarta bağlı, gerçekleşmemiş.\n◈D — D1 şart (COND 1) + cevap; D2 'fe-lâ … ve lâ …' iki olumsuz paralel (36:23 'lâ tuğnî … ve lâ yunqizûn' ile aynı yapı); D4 1P 2 · 3MP 5.\n◈A — A2 deniz (36:41'den süren sahne).",
 44: "◇ 6 kelime (36:42 ile eşit; blokun en kısaları). HASR (illâ): 36:43'ün istisnası — 'ancak bizden bir rahmet ve bir süreye kadar faydalandırma'. Ayet 36:43'ün cümlesini tamamlıyor; tek başına yüklemsiz. رحم [5/8], متع [1/1], حين [1/1]. 1P 1 ('minnâ').\n◈K — K2 zaman: 'ilâ hîn' — süreli, sonu belirsiz erteleme.\n◈B — B4 ömrün uzatılması (metâ' ilâ hîn) — ertelemeli.\n◈D — D1 istisna (RES 1, HASR); D2 iki mef'ûlün leh (rahmeten · metâ'an); D4 1P 1.\n◈A — —",
 45: "◇ 'Onlara … denildiğinde' (iżâ qîle lehum): şart cümlesinin cevabı ayette YOK (hazf) — 36:46'nın yüz çevirme hükmü onu tamamlıyor. Söylenen: 'önünüzdekinden ve arkanızdakinden sakının'. Ön/arka çifti sûrede üçüncü kez: 36:9 (önlerinde ve arkalarında set) · 36:12 (önden gönderdikleri ve izleri) · 36:45 — يدي [3/6], خلف [2/2] kapanıyor (36:9 / 36:45). ★★★ tek kaynak pas z=3,48 (2/3 fiil edilgen: qîle, turhamûn) — 35:4 ile aynı tür (aday 1009). İLTİFÂT ALANI 1 (yön '1>23') — ayette 1. şahıs yok; değişim 3MP (lehum) → 2MP (alıntı içi) — konuşan değişmiyor, alıntı başlıyor: YANLIŞ POZİTİF (1017 ailesi; aynı yapıdaki 36:47'de alan 0). nakarat3 'iżâ qîle lehum' sûre içi 2 ayet → eşi 36:47 (bu blokta). وقي [1/1], بين [5/9], رحم [6/8], قول [10/20].\n◈K — —\n◈B — B3 tetik يدي — deyim ('elleriniz arası' = önünüz), organ işlevi yok.\n◈D — D1 şart (iżâ) + alıntı içinde emir (IMPV 1) + recâ (le'allekum); D2 cevap hazfı; D4 3MP 1 → 2MP 7 (alıntı).\n◈A — A3 söyleyen adlanmıyor (edilgen qîle), muhatap 'onlar'; A4 delil listesinden (36:33-44) tepkiye geçiş.",
 46: "◇ HASR (mâ … illâ): 'Rablerinin âyetlerinden hiçbir âyet gelmez ki yüz çevirmesinler'. Kök ikilemesi أيي ×2 [4,5/6] — 36:33/37/41'deki üç 'âyet'in karşılığı: âyetler sayıldı, gelen âyetten yüz çevriliyor. Rab dördüncü kez (ربب [4/6]), 3MP iyelikli ('rabbihim'): ★ tek kaynak rab z=1,62. nakarat3 'mâ te'tîhim min' → eşi 36:30 (bağ 36:30 → 36:46 DOĞRULANDI: 36:30 elçi gelir · 36:46 âyet gelir, ikisinde de 'illâ kânû'). أتي [2/2] kapanıyor (36:30 / 36:46). esit2 → 6:4 YAKIN (0,9882). عرض [1/1], كون [4/15].\n◈K — —\n◈B — —\n◈D — D1 olumsuz + istisna (NEG 1 · RES 1); D3 aynı kök ikilemesi (min âyetin min âyâti); D4 3FS 2 · 3MP 4.\n◈A — A1 'onlar' (adsız); A4 36:45'in hazf edilen cevabı yerine genel hüküm.",
 47: "◇ SÛREDE İLK LAFIZ: أله [2,3/5] — 36:1-46'da lafız 0 (korpus sayımı; أله'nin ilk tokeni 36:23 'âlihe'ydi). İki lafız, ikisi de alıntı içinde: 'Allah'ın size verdiği rızıktan harcayın' (söyleyen adlanmıyor) · 'Allah dileseydi' (inkârcıların sözü). Blokun en uzun ayeti (24 kelime, tek). Üç konuşma katmanı: edilgen söyleyici → inkârcılar → mü'minler (2MP). İki kök ikilemesi: طعم ×2 [1,2/2] (doyuracağız / doyururdu), قول ×2. nakarat3 'iżâ qîle lehum' eşi 36:45 ve 'in entum illâ' eşi 36:15 (bağ 36:15 → 36:47 DOĞRULANDI: 36:15 halk elçilere · 36:47 inkârcılar mü'minlere, aynı HASR). 'dalâlin mübîn' 36:24'te adamın kendi hakkındaki şartlı hükmüydü (ضلل [1/3] → [2/3]). Esmâ mübîn sapıklığın sıfatı → değil; §4.3 mühür e_oto EVET, e_el YOK: YANLIŞ MÜHÜR (sûrede mübîn için dördüncü: 36:12 · 17 · 24 · 47); sınıf oto A → el A. نفق [1/1], رزق [1/1], كفر [1/3], أمن [4/4] kapanıyor, شيأ [5/10], بين [6/9]. xref 4:39, 7:50. İltifât 0 — 36:45 ile aynı alıntı yapısı, alan burada vermiyor.\n◈K — —\n◈B — —\n◈D — D1 şart (iżâ) + alıntı içinde emir + soru + şart (lev) + HASR — beş kip (COND · IMPV · INTG · NEG · RES); D2 istifhâm-ı inkârî (e-nut'imu); D3 طعم ikilemesi: insanın doyurması / Allah'ın doyurması; D4 1P 1 (inkârcılar 'biz') · 2MP 4 · 3MP 5 · 3MS 6.\n◈A — A1 aktörler: adsız söyleyen, 'inkâr edenler', 'iman edenler'; A3 konuşma sırası: emir (edilgen) → inkârcıların cevabı mü'minlere; alıntı içi 'biz' inkârcıların (aday 1017); A4 tepki sahnesi sürüyor.",
 48: "◇ Soru + şart: 'doğru söyleyenlerseniz bu vaat ne zaman?' — biçim DİKKAT (hâzâ). esit2 TAM ×4: 10:48, 21:38, 27:71, 34:29 · YAKIN 67:25 · BENZER 32:28 — alan altı eş ayet veriyor (dördü birebir). قول [13/20], وعد [1/3], كون [5/15], صدق [1/2].\n◈K — K2 zaman sorusu (metâ): ertelenmiş, belirsiz gelecek.\n◈B — —\n◈D — D1 soru (INTG) + şart (COND), cevapsız; D2 işaret zamiri (hâzâ); D4 2MP 2 · 3MP 2.\n◈A — A3 konuşan inkârcılar (3MP yeqûlûn), muhatap 2MP — mü'minler ya da elçi; ayetten belirlenmiyor.",
 49: "◇ HASR (mâ … illâ): cevap 36:48'in sorusuna değil, durumuna: 'yalnız tek bir çığlık bekliyorlar'. nakarat3 'illâ sayhaten vâhideten' 3 ayet → 36:29 (okundu) · 36:49 · 36:53 (henüz okunmadı). 36:29'da çığlık geçmiş kasaba için, 36:49'da muhataplar için bekleyen. say vâhide DOĞRU POZİTİF. صيح [2/3], وحد [2/3], أخذ [2/3], نظر [1/1], خصم [1/2]. Hâl cümlesi: 'onlar çekişip dururken'. xref 38:15.\n◈K — K2 bekleyiş (IMPF): gelecek, ani.\n◈B — —\n◈D — D1 HASR (NEG 1 · RES 1); D2 hâl cümlesi (ve hum yaḫissimûn); D4 3FS 1 · 3MP 6.\n◈A — A2 sahne: gündelik çekişme anı → ani yakalanma; A4 36:29'daki helâk kalıbı muhataplara aktarılıyor (okuma gözlemi, KAPATILAMAZ).",
 50: "◇ İki olumsuz (NEG 2): vasiyet edemezler · ailelerine dönemezler. رجع [3/5]: 36:22 'O'na döndürüleceksiniz' · 36:31 'helâk edilenler onlara dönmez' · 36:50 'ailelerine dönemezler'. طوع [1/3], وصي [1/1], أهل [1/1]. 7 kelime.\n◈K — —\n◈B — B4 ölüm anı — vasiyetin ve dönüşün imkânı alınıyor.\n◈D — D1 olumsuz haber ×2 (fe-lâ … ve lâ …); D4 3MP 5.\n◈A — A2 çığlık anı (36:49'un devamı); A4 sahne 36:49-50'de kapanıyor.",
}
MEAL.update(MEAL5); M.update(M5)
MEAL6 = {
 51: "Sûra üfürülmüştür; bir de bakarsın kabirlerinden Rablerine doğru akın ediyorlar.",
 52: "Derler ki: 'Vay hâlimize! Bizi uyku yerimizden kim kaldırdı?' — 'Bu, Rahmân'ın vaat ettiğidir; elçiler doğru söylemiş.'",
 53: "Yalnızca tek bir çığlık olur; bir de bakarsın hepsi toplanmış, huzurumuza getirilmişler.",
 54: "O gün hiçbir kimseye hiçbir şekilde zulmedilmez; siz ancak yapmakta olduklarınızla karşılık görürsünüz.",
 55: "Cennet halkı o gün bir meşguliyet içinde, keyif sürmektedir.",
 56: "Onlar ve eşleri gölgeler içinde, süslü koltuklar üzerine yaslanmışlardır.",
 57: "Orada onlar için meyve vardır; istedikleri her şey onlarındır.",
 58: "Merhametli bir Rab'den bir söz olarak: 'Selâm!'",
 59: "'Ey suçlular! Bugün ayrılın!'",
 60: "'Ey Âdemoğulları! Size şeytana kulluk etmeyin diye ahit vermedim mi? O sizin için apaçık bir düşmandır.'",
}
M6 = {
 51: "◇ Sahne kıyamete geçiyor: 'sûra üfürüldü' (nufiḫa, EDİLGEN; üfüren adlanmıyor) → 'fe-izâ' → kabirlerden Rablerine akın. ★★ kaynak pas z=2,52; rab z=1,81 de eşiği geçiyor — iki bileşen, iki yıldız (kırık yok, kaynak etiketi tutarlı). Rab beşinci kez (ربب [5/6]), 3MP iyelikli (36:46 ile aynı: 'rabbihim'). 'fe-izâ hum' sûrede dördüncü kez: 36:29 (söndüler) · 36:37 (karanlıktalar) · 36:51 (akın ediyorlar) · 36:53 (huzurdalar) — metin sayımı 36:1-60. جدث [1/1] (sûre için eklenen kök), نفخ [1/1], صور [1/1], نسل [1/1].\n◈K — —\n◈B — —\n◈D — D1 haber (PERF edilgen + IMPF); D2 mufâcee 'fe-izâ'; D4 3MP 4 · 3MS 1.\n◈A — A2 sahne dünya → kıyamet (kabirler); A1 aktör adsız 'onlar', üfüren adlanmıyor; A4 36:49-50'deki çığlık sahnesinden sonra yeni sahne açılıyor.",
 52: "◇ Dirilenlerin sözü (1P 3, alıntı): 'vay hâlimize, bizi uyku yerimizden (merqad) kim kaldırdı?' — kabir 'uyku yeri' adıyla: رقد [1/1] (sûre için eklenen kök). Cevap: 'bu, Rahmân'ın vaat ettiği; elçiler doğru söyledi' — söyleyen adlanmıyor (dirilenlerin kendisi ya da başka ses; ayet ayırmıyor). وعد [2/3]: 36:48 'bu vaat (hâzâ'l-va'd) ne zaman?' → 36:52 'bu (hâzâ), Rahmân'ın vaadi' — soru dört ayet sonra aynı işaret zamiriyle cevaplanıyor (okuma gözlemi, KAPATILAMAZ). صدق [2/2] kapanıyor: 36:48 'doğru söyleyenlerseniz' / 36:52 'elçiler doğru söyledi'. رسل [8/8] kapanıyor. Rahmân dördüncü kez bağımsız ad (36:11 · 15 · 23 · 52), özne: e_el 'ilahi' (aday 1019). §4.3 mühür EVET geçerli (son üç lemmada Rahmân), ton cemâl; ölçüm satırının 'MÜHÜRSÜZ' etiketi ayrı tanım (son kelime mürselûn). بعث [1/1], رحم [7/8].\n◈K — —\n◈B — B4 ölüm uyku olarak adlanıyor (merqad), dirilme 'kaldırılma' (be'ase).\n◈D — D1 nidâ (yâ veylenâ) + soru + haber; D2 istiâre (kabir = uyku yeri); işaret zamiri hâzâ (DİKKAT); D4 1P 3 (dirilenler) · 3MS 3 · 3MP 2.\n◈A — A3 iki konuşma: dirilenler (soru) → adsız ses ya da kendileri (cevap); alıntı içi 'biz' dirilenlerin (aday 1017); A2 kabir/diriliş.",
 53: "◇ Üç nakarat3 kalıbı tek ayette: 'in kânet illâ sayhaten vâhideten fe-izâ hum' (7 kelime) eşi 36:29 — DOĞRULANDI · 'illâ sayhaten vâhideten' 3 ayet: 36:29 · 36:49 · 36:53 — DOĞRULANDI · 'cemî'un ledeynâ muhdarûn' eşi 36:32 — DOĞRULANDI. Ayetin ilk yarısı 36:29'la, ikinci yarısı 36:32'yle aynı: 36:29'da tek çığlık → 'söndüler', 36:53'te tek çığlık → 'huzurdalar' — aynı çerçeve, ters sonuç (okuma gözlemi, KAPATILAMAZ). Üç iplik kapanıyor: صيح [3/3], وحد [3/3], جمع [2/2]. say vâhide DOĞRU POZİTİF. حضر [2/3], كون [6/15]. 1P 1 (ledeynâ).\n◈K — —\n◈B — —\n◈D — D1 HASR (in … illâ); D2 mufâcee 'fe-izâ'; D3 iki önceki ayetin parçalarının birleşimi; D4 1P 1 · 3FS 1 · 3MP 1.\n◈A — A2 kıyamet, huzur (ledeynâ); A4 diriliş sahnesi sürüyor.",
 54: "◇ 'Fe'l-yevme': sûrede يوم kökünün İLK tokeni (يوم [1/5]). Hitap 2MP 6 — anlatımdan doğrudan hitaba geçiş (ayetler arası). İki olumsuz + HASR: 'hiçbir nefse zulmedilmez (tuzlemu, EDİLGEN; pas z=1,10, yıldız yok) · ancak yaptığınızla karşılık görürsünüz'. ظلم [2/2] kapanıyor: 36:37 'muzlimûn' (karanlıkta) / 36:54 'tuzlemu' (zulmedilmez) — tek kök iki anlam; gloss 'zulüm' yalnız ikincisini taşıyor (aday 1015). نفس [2/2] kapanıyor (36:36 enfus). جزي [1/1], عمل [2/3] (36:35 'elleri yapmadı' / 36:54 'yaptıklarınız'), شيأ [6/10]. xref 21:47.\n◈K — K2 zaman: 'el-yevm' — o gün, belirli (kıyamet günü).\n◈B — —\n◈D — D1 olumsuz haber + HASR (NEG 2 · RES 1); D2 'şey'en' mef'ûl-i mutlak yerinde (hiçbir şekilde); D4 2MP 6 · 3FS 1.\n◈A — A3 konuşan adlanmıyor, muhatap 2MP (dirilenler); A2 hesap günü.",
 55: "◇ Sahne cennete: 'cennet halkı o gün bir meşguliyette, keyif sürüyor'. Şahıs işareti yok (isim cümlesi). شغل [1/1] (sûre için eklenen kök). جنن [3/3] kapanıyor: 36:26 cennet · 36:34 bahçeler · 36:55 cennet. صحب [2/2] kapanıyor: 36:13 'ashâbe'l-qarye' (kasaba halkı) / 36:55 'ashâbe'l-cenne' (cennet halkı) — aynı tamlama kalıbı, iki zıt topluluk (okuma gözlemi, KAPATILAMAZ). يوم [2/5], فكه [1/2] (fâkihûn: keyifli). xref 25:24. Aktör adlı cennet (yer).\n◈K — K2 zaman: 'el-yevm' (o gün).\n◈B — —\n◈D — D1 tekitli isim cümlesi (inne); D4 şahıs işareti yok.\n◈A — A2 sahne hesaptan cennete; A1 aktör 'cennet halkı' (adsız topluluk); A4 cennet sahnesi açılıyor.",
 56: "◇ 'Onlar ve eşleri gölgelerde, koltuklar üzerinde yaslanmış'. زوج [2/2] kapanıyor: 36:36 ezvâc (çiftler) / 36:56 ezvâc (eşler) — tek lemma iki anlam; say alanı zevc'i yine işaretledi — YANLIŞ POZİTİF (aday 1005 ailesi). GLOSS: ظلل 'sürüp gitme, olmayı sürdürme' — ayette zılâl (gölgeler); aday 1015'te kayıtlı vaka (baskın lemma zıll 'gölge' gloss'ta yok) — sûre 36 girdisi. أرك [1/1] (sûre için eklenen kök), وكأ [1/1].\n◈K — —\n◈B — B1 insan çiftleri (eşler); B4 —.\n◈D — D1 isim cümlesi, iki yer bildiren (fî · alâ); D4 3MP 2.\n◈A — A1 cennet halkı ve eşleri; A2 cennet (gölge, koltuk).",
 57: "◇ 6 kelime: 'orada meyve var; istedikleri onların'. فكه [2/2] kapanıyor: 36:55 fâkihûn (keyifli) / 36:57 fâkihe (meyve) — ardışık ayetlerde tek kök iki anlam; gloss 'meyve; şakalaşma' ikisini taşıyor. دعو [1/1] 'yedde'ûn' (isterler, VIII. bab) — gloss 'çağırma, dua' istemek anlamına yakın ama ayrı yazmıyor (kayıt). 'lehum' iki kez.\n◈K — —\n◈B — B1 meyve.\n◈D — D1 isim cümlesi ×2; D3 'lehum' tekrarı — paralel; D4 3MP 4 · 3FS 1.\n◈A — A2 cennet.",
 58: "◇ 5 kelime: 'Selâm — merhametli bir Rab'den bir söz'. Rab altıncı ve son kez (ربب [6/6] kapanıyor) ve sûrede İYELİKSİZ tek Rab: 36:16 Rabbimiz · 36:25 Rabbiniz · 36:27 Rabbim · 36:46 ve 36:51 Rableri · 36:58 'bir Rab' (nekre). ★★★ tek kaynak rab z=3,94 — kısa ayet Rab şişmesinin üçüncü vakası (aday 1020: 36:16 · 36:25 · 36:58). رحم [8/8] kapanıyor: rahmet ipliği sûrede rahîm (36:5) ile açılıp rahîm (36:58) ile kapanıyor (iplik sınırlarının sayımı, yorum yok). Esmâ: selâm burada esenlik sözü (nekre) → değil; rahîm Rab'bin sıfatı → ilahi; §4.3 mühür EVET geçerli, ton cemâl. سلم [1/1], قول [15/20].\n◈K — —\n◈B — —\n◈D — D1 isim cümlesi, yüklem hazf; D2 'qavlen' mef'ûl-i mutlak (söz olarak); D4 şahıs işareti yok.\n◈A — A3 konuşan Rab (adla, 3. şahıs dolaylı); muhatap cennet halkı; A4 cennet sahnesi selâmla kapanıyor.",
 59: "◇ 4 kelime, blokun en kısa ayeti (tek). Emir + nidâ: 'ey suçlular, bugün ayrılın'. Sahne cennetten suçlulara. İLTİFÂT ALANI 1 (yön '3>2') — ayette yalnız 2MP 2; değişim önceki ayetle ya da nidâ edilen isim (el-mucrimûn) üzerinden olabilir, alan hangisi olduğunu yazmıyor (517/1017 ailesi, kayıt). ARAÇ NOTU: 'eyyuhâ' (nidâ edatı, lemma eyy) korpus morfolojisinde أيي köküne bağlı — ölçüm satırında أيي [6/6] bu tokenle kapanıyor; sûredeki 'âyet' tokenleri 5 (36:33, 37, 41, 46 ×2), altıncı token nidâ edatı. Kök ipliği iki ayrı kelimeyi birleştiriyor (aday 924: metin hakkında kanıt değil). يوم [3/5], ميز [1/1], جرم [1/1].\n◈K — K2 zaman: 'el-yevm' (bugün).\n◈B — —\n◈D — D1 emir (IMPV 1) + nidâ; D2 DİKKAT (eyyuhâ); D4 2MP 2.\n◈A — A1 'suçlular' (adsız topluluk); A2 hesap sahnesi; A4 cennet halkı / suçlular ayrımı.",
 60: "◇ Konuşan 1S (a'had): sûrede ilâhî 1S ilk kez — 36:22-27'deki 1S şehrin ucundan gelen adamındı; 36:53'te 1P (ledeynâ) → 36:60 1S. Soru (e lem) + nidâ (yâ benî âdem) + yasak (NEHY): 'şeytana kulluk etmeyin'. Aktörler adlı: Âdem (kişi), şeytan (gayb). عبد [3/4]: 36:22 'kulluk etmeyeyim mi' · 36:30 'kullar' · 36:60 'kulluk etmeyin'. Esmâ mübîn düşmanın sıfatı → değil; §4.3 YANLIŞ MÜHÜR (sûrede mübîn için beşinci: 36:12 · 17 · 24 · 47 · 60). GLOSS: بني 'bina, yapma' — ayette benî (oğulları); korpus TAM SAYIM 184 token: benî 80 · ibn 63 · bint 17 (160, akrabalık) / binâ fiili 11 · bunyân 7 · binâ' 2 (20, yapı) — BASKIN anlam gloss'ta YOK (aday 1021'e girdi). عهد [1/1], أدم [1/1], شطن [1/1], عدو [1/1], بين [7/9].\n◈K — —\n◈B — —\n◈D — D1 olumsuz soru (takrîr) + nidâ + yasak (INTG · NEG · PRO · VOC); D2 'en' tefsiriyye ile ahdin içeriği; tekit (innehû); D4 1S 1 · 2MP 4 · 3MS 1.\n◈A — A1 adlı aktörler Âdem (soy adı olarak) ve şeytan; A3 konuşan 1S (Allah), muhatap Âdemoğulları; A2 hesap sahnesi; A4 hitap sürüyor.",
}
MEAL.update(MEAL6); M.update(M6)
MEAL7 = {
 61: "'Ve bana kulluk edin; bu dosdoğru bir yoldur' (demedim mi?)",
 62: "'Andolsun, o sizden pek çok topluluğu saptırdı. Hâlâ akıl erdirmiyor muydunuz?'",
 63: "'İşte bu, size vaat edilip durulan cehennemdir.'",
 64: "'İnkâr etmekte olduğunuz için bugün girin oraya!'",
 65: "O gün ağızlarını mühürleriz; elleri bize konuşur, ayakları da kazanmakta olduklarına şahitlik eder.",
 66: "Dileseydik gözlerini silip yok ederdik; yola koşuşurlardı, ama nasıl görebilirlerdi?",
 67: "Dileseydik onları oldukları yerde başka bir şekle çevirirdik; ne ileri gidebilirlerdi, ne de geri dönebilirlerdi.",
 68: "Kime uzun ömür verirsek onu yaratılışta tersine çeviririz. Hâlâ akıl erdirmiyorlar mı?",
 69: "Biz ona şiir öğretmedik; bu ona yaraşmaz da. O ancak bir öğüt ve apaçık bir Kur'an'dır,",
 70: "diri olanı uyarsın ve inkâr edenler üzerine söz hak olsun diye.",
}
M7 = {
 61: "◇ 36:60'ın 1S hitabı sürüyor: 'bana kulluk edin' (u'budûnî). عبد [4/4] kapanıyor: 36:22 · 30 · 60 · 61 — 'kulluk etmeyeyim mi' (adam) → 'kullar' → 'şeytana kulluk etmeyin' → 'bana kulluk edin'. 'Sırâtun mustaqîm': 36:4 'sırâtın mustaqîm üzerindesin' (elçiye) ile aynı terkip — صرط [2/3], قوم [7/7] kapanıyor (mustaqîm her iki ayette de bu kökten). 5 kelime — blokta 36:63 ve 36:64 ile EŞİT en kısa (üçü de 5).\n◈K — —\n◈B — —\n◈D — D1 emir (IMPV 1) + işaret zamirli haber (hâzâ, DİKKAT); D2 'en' ile 36:60'taki ahde bağlı ikinci içerik; D4 1S 1 · 2MP 2.\n◈A — A3 konuşan 1S (Allah), muhatap Âdemoğulları; A4 hitap sürüyor.",
 62: "◇ Tekit (le-qad, CERT + EMPH): 'o (şeytan) sizden pek çok topluluğu saptırdı' + soru 'akıl erdirmiyor muydunuz?' ضلل [3/3] kapanıyor: 36:24 adamın şartlı 'sapıklık' hükmü · 36:47 inkârcıların mü'minlere hükmü · 36:62 şeytanın saptırması — sapıklık ipliği üç konuşanda. GLOSS: جبل 'dağ' — ayette cibill (topluluk, nesil); TAM SAYIM 41 token: cebel 39 · cibille 2 — anlam gloss'ta yok, baskın değil (kayıt, 1021 ailesi). say alanı kesîr'i işaretledi — YANLIŞ POZİTİF ('çok' belirteç, sayı değil; aday 1004 ailesi, 36:7 ekser ile aynı tür). كثر [2/2] kapanıyor (36:7 ekser / 36:62 kesîr). عقل [1/2], كون [8/15].\n◈K — —\n◈B — —\n◈D — D1 tekitli haber + olumsuz soru; D2 qasem lâmı + qad; D4 2MP 5 · 3MS 1 (şeytan).\n◈A — A1 aktör şeytan (zamirle, 36:60'tan), 'pek çok topluluk'; A3 konuşan 1S.",
 63: "◇ 5 kelime, işaret: 'işte bu, size vaat edilip duran cehennem'. tû'adûn EDİLGEN: ★★ tek kaynak pas z=2,52 (kırık yok). وعد [3/3] kapanıyor: 36:48 'bu vaat ne zaman?' · 36:52 'bu, Rahmân'ın vaadi' · 36:63 'bu, vaat olunduğunuz cehennem' — üçünde de 'hâzâ/hâzihî' (okuma gözlemi, KAPATILAMAZ). Aktör adlı cehennem (yer, fail).\n◈K — —\n◈B — —\n◈D — D1 isim cümlesi, işaret zamiri (DİKKAT); D2 kâne + muzari edilgen: süregelen vaat; D4 2MP 4.\n◈A — A2 sahne cehennem; A3 konuşan adlanmıyor (36:60-62'nin 1S'i sürüyor olabilir, ayet 1. şahıs taşımıyor), muhatap 2MP.",
 64: "◇ 5 kelime, emir: 'inkâr etmekte olduğunuz için bugün girin oraya'. صلي [1/1], يوم [4/5], كفر [2/3] (36:47 inkâr edenler · 36:64 inkâr ediyordunuz), كون [10/15].\n◈K — K2 zaman: 'el-yevm' (bugün).\n◈B — —\n◈D — D1 emir (IMPV 1) + sebep (bi-mâ); D4 2MP 6 · 3FS 1.\n◈A — A2 cehennem; A3 muhatap 2MP; A4 2MP hitabının son ayeti (36:65'te 3MP'ye dönüyor).",
 65: "◇ Hitap 2MP'den 3MP'ye dönüyor, konuşan 1P: 'o gün ağızlarını mühürleriz; elleri bize konuşur, ayakları şahitlik eder'. Üç organ, üç işlev: ağız susturuluyor · el konuşuyor · ayak tanıklık ediyor. يوم [5/5] kapanıyor: 36:54 · 55 · 59 · 64 · 65 — beşi de 'el-yevm'. يدي [4/6] (36:9 · 35 · 45 · 65). GLOSS: رجل 'adam; yaya' — ayette ercul (ayaklar); TAM SAYIM 73 token: racul 29 · ricâl 28 · ricl 15 — 'ayak' anlamı gloss'ta yok, baskın değil (kayıt, 1021 ailesi); رجل [2/2]: 36:20 'bir adam' / 36:65 'ayakları'. ختم [1/1], فوه [1/1], كلم [1/1], شهد [1/1], كسب [1/1].\n◈K — K2 zaman: 'el-yevm'.\n◈B — B3 organlar: ağız (mühürlenme — işlev alınıyor), el (konuşma), ayak (şahitlik) — organlara asıl işlevleri dışında işlev veriliyor.\n◈D — D1 haber (IMPF 4); D3 üç paralel fiil cümlesi; D4 1P 2 · 3MP 7 · 3FS 2 — 2MP → 3MP ayetler arası geçiş.\n◈A — A1 aktörler organlar (el, ayak) konuşan/tanık rolünde; A2 hesap; A3 konuşan 1P.",
 66: "◇ Şart (lev neşâ'u): 'dileseydik gözlerini silerdik' → yola koşuşurlar → 'nasıl görecekler?' — sûrede 'dilersek' üçüncü kez (36:43 in neşa' · 36:66 · 36:67 lev neşâ'u ×2). طمس [1/1] (sûre için eklenen kök). عين [2/2] kapanıyor: 36:34 'uyûn' (pınarlar) / 36:66 'a'yun' (gözler) — tek kök iki anlam. صرط [3/3] kapanıyor (36:4 · 61 · 66 — dosdoğru yol / yola koşuşma). سبق [2/2] (36:40 gece gündüzü geçemez / 36:66 yarışırcasına koşuşma). بصر [2/2] (36:9 'görmezler' / 36:66 'nasıl görecekler'). TARAYICI v4 ADAY VERDİ — doğal olgu yok, çıpa değil.\n◈K — —\n◈B — B3 organ göz — silinme (şartlı), görme işlevi alınıyor.\n◈D — D1 şart (COND) + tekit lâmı (EMPH) + soru (ennâ); D2 'fe-' ile iki sonuç; D4 1P 3 · 3MP 5.\n◈A — —",
 67: "◇ İkinci 'lev neşâ'u': 'oldukları yerde şekillerini değiştirirdik; ne ileri ne geri' — مسخ [1/1] HAPAKS: ★★★ tek kaynak hapaks z=3,28 (983 ailesi; sûrede üçüncü: 36:8 قمح · 36:39 عرجن · 36:67 مسخ). مضي [1/1] (sûre için eklenen kök). Yapı 36:50 ile aynı: 'güç yetiremezler (istitâ'a) … ve dönemezler (lâ yerci'ûn)' — طوع [2/3], رجع [4/5]; nakarat3 yakalamıyor (kelime dizisi farklı; okuma gözlemi, KAPATILAMAZ). شيأ [8/10], كون [12/15].\n◈K — —\n◈B — B2 biçim değişimi (mesh) — şartlı, gerçekleşmemiş.\n◈D — D1 şart + tekit lâmı + iki olumsuz sonuç (NEG 2); D2 36:66 ile paralel şart yapısı; D4 1P 3 · 3MP 6.\n◈A — —",
 68: "◇ 'Kime uzun ömür verirsek onu yaratılışta tersine çeviririz' + soru 'akıl erdirmiyorlar mı?'. عقل [2/2] kapanıyor: 36:62 2MP (akıl erdirmiyor muydunuz) / 36:68 3MP (akıl erdirmiyorlar mı). عمر [1/1], نكس [1/1], خلق [3/10]. 🜁 L2 — ömrün uzaması → yaratılışta tersine dönüş: iki durum arasında bağımlılık (yaşlanmada gerileme), mekanizma ve aşama adı yok; olgu evet, çıpa hayır; tarayıcı vermedi.\n◈K — K2 zaman: ömür (süre), uzayan.\n◈B — B4 ömür uzatılıyor; B2 'yaratılışta' (fi'l-halq) tersine çevrilme — oluşumun geri yönü, aşama adsız.\n◈D — D1 şart-ism-i mevsul (men) + cevap + olumsuz soru; D2 'fî' ile alan; D4 1P 2 · 3MS 2 · 3MP 2.\n◈A — —",
 69: "◇ Konuşan 1P, gönderge elçi (3MS, adsız): 'ona şiir öğretmedik, ona yaraşmaz da' + HASR: 'o ancak bir öğüt ve apaçık Kur'an'. NEG 3. Aktör adlı Kur'an (kitap). قرأ [2/2] kapanıyor: 36:2 'hikmetli Kur'an'a andolsun' / 36:69 'apaçık Kur'an'. ذكر [3/3] kapanıyor (36:11 zikr · 36:19 zukkirtum · 36:69 zikr). بغي [2/2] kapanıyor: 36:40 güneşe 'yaraşmaz' / 36:69 elçiye 'yaraşmaz' — aynı fiil (yenbeğî), aynı olumsuzluk, iki farklı özne (okuma gözlemi, KAPATILAMAZ). Esmâ mübîn Kur'an'ın sıfatı → değil; §4.3 YANLIŞ MÜHÜR (sûrede mübîn için altıncı: 36:12 · 17 · 24 · 47 · 60 · 69). شعر [1/1], علم [5/8], بين [8/9]. Blokun en uzun ayeti (12 kelime, tek).\n◈K — —\n◈B — —\n◈D — D1 olumsuz haber ×2 + HASR (NEG 3 · RES 1); D4 1P 2 · 3MS 4.\n◈A — A1 aktör Kur'an; elçi zamirle; A4 hesap sahnesinden elçi/kitap konusuna geçiş (36:2-6 açılışına dönüş).",
 70: "◇ Amaç: 'diri olanı uyarsın ve inkâr edenler üzerine söz hak olsun diye'. nakarat3 'haqqa'l-qavlu alâ' eşi 36:7 — DOĞRULANDI (36:7 'söz çoğunun üzerine hak oldu' / 36:70 'söz kâfirler üzerine hak olsun'). حقق [2/2], نذر [6/6], كفر [3/3] kapanıyor; نذر ipliği 36:6'da (uyarman için) açılıp 36:70'te (uyarsın diye) kapanıyor. حيي [3/5] 'hayyen' (diri olan, insan). ESMÂ: e_oto 'hayy'i esmâ saydı (D2 eşlemesi) — gönderge insan → e_el 'degil'; §4.3 mühür e_oto EVET → YANLIŞ MÜHÜR. Ölçüm satırı 'esmâ yok' yazıyor, esmâ kaydı e_oto=1 — iki alan ayrışıyor (kayıt). TARAYICI v4 ADAY VERDİ — doğal olgu yok, çıpa değil.\n◈K — —\n◈B — B4 'diri' (hayy) — dirim metaforu (öğüdü alabilen).\n◈D — D1 amaç cümlesi (li-) iki fiille; D4 3MS 3.\n◈A — A4 elçi/kitap bölümü sürüyor; 36:7'nin hükmü burada yeniden kuruluyor.",
}
MEAL.update(MEAL7); M.update(M7)
MEAL8 = {
 71: "Görmediler mi, ellerimizin yaptıklarından onlar için davarlar yarattık; onlar da bunlara sahip oluyorlar.",
 72: "Onları kendilerine boyun eğdirdik; kimine binerler, kiminden yerler.",
 73: "Onlarda kendileri için faydalar ve içecekler vardır. Hâlâ şükretmeyecekler mi?",
 74: "Yardım görürler umuduyla Allah'tan başka ilâhlar edindiler.",
 75: "Onlar onlara yardım edemezler; onlar ise onlar için hazır bekletilen bir ordudur.",
 76: "Onların sözü seni üzmesin. Biz onların gizlediklerini de açığa vurduklarını da biliriz.",
 77: "İnsan görmedi mi ki biz onu bir nutfeden yarattık; bir de bakarsın apaçık bir hasım kesilmiş!",
 78: "Kendi yaratılışını unutup bize bir misal getirdi: 'Çürümüşken kemikleri kim diriltecek?' dedi.",
 79: "De ki: 'Onları ilk kez var eden diriltecek. O her yaratılmışı bilendir.'",
 80: "O ki size yeşil ağaçtan ateş çıkardı; bir de bakarsınız ondan yakıyorsunuz.",
 81: "Gökleri ve yeri yaratan, onların benzerini yaratmaya kadir değil mi? Elbette! O, yaratıcıdır, bilendir.",
 82: "O bir şeyi dilediğinde emri ona yalnızca 'Ol!' demektir; o da hemen oluverir.",
 83: "Her şeyin hükümranlığı elinde olan, her türlü eksiklikten uzaktır. Siz O'na döndürüleceksiniz.",
}
M8 = {
 71: "◇ 'Görmediler mi' — رأي [2/3]: 36:31 'e lem yeraw' (helâk edilen nesiller) → 36:71 'e ve lem yeraw' (davarlar). 'Ellerimizin yaptıklarından' (mimmâ amilet eydînâ): 36:35 'mâ amilethu eydîhim' (bunu onların elleri yapmadı) ile aynı fiil ve aynı nesne — insanın eli / 1P'nin eli (okuma gözlemi, KAPATILAMAZ). عمل [3/3] kapanıyor (36:35 · 54 · 71); يدي [5/6]. نعم [1/1] (en'âm, davarlar), ملك [1/2] (mâlikûn: sahipler), خلق [4/10]. TARAYICI v4 ADAY VERDİ. 🜁 L1 — davar sınıfı adlanıyor + sahiplik işlevi (36:72-73 ile sürüyor); olgu evet, çıpa hayır.\n◈K — —\n◈B — B1 davarlar (en'âm); B2 yaratma (خلق) fiili, aşama yok.\n◈D — D1 olumsuz soru (takrîr) + 'enne' cümlesi + 'fe' ile sonuç; D3 36:35'teki 'amile + yed' kalıbının 1P'ye çevrilmesi; D4 1P 4 · 3MP 4 · 3FS 2.\n◈A — A1 aktör adsız 'onlar', davarlar; A4 âyet listesi (36:33-44) türüne dönüş.",
 72: "◇ 6 kelime: 'onları boyun eğdirdik; kimine binerler, kiminden yerler' — 'fe-minhâ … ve minhâ' paralel. ذلل [1/1]. ركب [2/2] kapanıyor: 36:42 'binecekleri şeyler' / 36:72 'binekleri'. أكل [3/3] kapanıyor: 36:33 tane · 36:35 meyve · 36:72 davar — yeme ipliği bitkiden hayvana. 🜁 L1 — işlev (binme, yeme); olgu evet, çıpa hayır. 36:73 ile eşit en kısa (6).\n◈K — —\n◈B — B1 davarlar; işlev: binek ve besin.\n◈D — D1 haber; D3 'min' paralel ikilisi; D4 1P 2 · 3FS 3 · 3MP 4.\n◈A — —",
 73: "◇ 6 kelime: 'faydalar ve içecekler; hâlâ şükretmeyecekler mi?' شكر [2/2] kapanıyor: 36:35 'e-felâ yeşkurûn' / 36:73 'e-felâ yeşkurûn' — aynı soru iki kez, ikisi de yeme/ürün listesinin sonunda (metin sayımı; nakarat3 yakalamıyor — iki kelime). نفع [1/1], شرب [1/1]. 🜁 L1 — fayda ve içecek (süt) işlevi adlanıyor, madde adı yok; olgu evet, çıpa hayır.\n◈K — —\n◈B — B1 davar ürünleri (içecekler — madde adlanmıyor).\n◈D — D1 isim cümlesi + olumsuz soru; D4 3MP 3 · 3FS 1.\n◈A — —",
 74: "◇ İkinci lafız ayeti: أله [4,5/5] kapanıyor — 'Allah'tan başka ilâhlar edindiler'. nakarat3 'ittehaze min dûn' eşi 36:23 — DOĞRULANDI: 36:23 'O'ndan (min dûnihî) başka ilâhlar mı edineyim?' (adam, 1S, soru) / 36:74 'Allah'tan (min dûni'llâh) başka ilâhlar edindiler' (3MP, haber) — aynı terkip, zamir → lafız (okuma gözlemi, KAPATILAMAZ). Sûrede lafız: 36:47 (2 token) · 36:74 (1) — toplam 3 token, 2 ayet. ★★ kaynak pas z=2,52 (yunsarûn); allah z=2,33 de eşiği geçiyor — iki bileşen (kırık yok). أخذ [3/3], دون [2/2] kapanıyor; نصر [1/2]. xref 19:81.\n◈K — —\n◈B — —\n◈D — D1 haber + recâ (le'allehum) + edilgen (yunsarûn); D4 3MP 5.\n◈A — A1 'onlar' ve adsız 'ilâhlar'; A4 36:23'teki adamın sorusu burada hüküm olarak.",
 75: "◇ 'Onlar onlara yardım edemezler; onlar ise onlar için hazır bekletilen bir ordudur' — iki 'hum' iki ayrı topluluk (putlar / putperestler); hangisinin hangisine ordu olduğu zamirlerden kesin çıkmıyor (ayet ayırmıyor). Dört iplik kapanıyor: طوع [3/3] (36:50 · 67 · 75 — üçü de 'güç yetiremez'), نصر [2/2], جند [2/2] (36:28 gökten ordu indirmedik / 36:75 hazır ordu), حضر [3/3] (36:32 · 53 · 75 — üçü de fâsılada 'muhdarûn').\n◈K — —\n◈B — —\n◈D — D1 olumsuz haber + isim cümlesi; D2 zamir belirsizliği (hum … lehum); D4 3MP 5.\n◈A — A1 putlar ve putperestler, ikisi de adsız 'onlar'; A2 (muhdarûn) hesap sahnesine işaret.",
 76: "◇ Elçiye hitap (2MS 1) + yasak (NEHY): 'sözleri seni üzmesin' — 1P: 'gizlediklerini ve açıkladıklarını biliriz'. سرر [1/1] / علن [1/1] — zıt çift tek ayette. حزن [1/1], علم [6/8], قول [17/20].\n◈K — —\n◈B — —\n◈D — D1 yasak + tekitli haber; D3 zıt çift (yusirrûn / yu'linûn); D4 1P 2 · 2MS 1 · 3MP 5 · 3MS 1.\n◈A — A3 konuşan 1P, muhatap elçi (2MS, adsız); A4 36:69-70'teki elçi konusu sürüyor.",
 77: "◇ Üçüncü 'görmedi mi': رأي [3/3] kapanıyor (36:31 · 71 · 77) — bu kez tekil 'insan' (ilk kez adla: أنس [1/1]). 'Onu bir nutfeden yarattık; bir de bakarsın apaçık hasım' — 'fe-izâ' sûrede beşinci (36:29 · 37 · 51 · 53 · 77; 36:80 altıncı). خصم [2/2] kapanıyor: 36:49 'çekişirken' (yahissimûn) / 36:77 'hasîm'. بين [9/9] kapanıyor. Esmâ mübîn hasmın sıfatı → değil; §4.3 YANLIŞ MÜHÜR (sûrede mübîn için yedinci ve son: 36:12 · 17 · 24 · 47 · 60 · 69 · 77). نطف [1/1], خلق [5/10]. xref 16:4 (aynı terkip). TARAYICI v4 ADAY VERDİ. 🜁 L1 — madde (nutfe) → sonuç; ara aşama yok (35:11, 32:7 emsali); olgu evet, çıpa hayır.\n◈K — —\n◈B — B2 oluşum: nutfe — tek aşama adlı, ara durum yok; B1 insan.\n◈D — D1 olumsuz soru + 'fe-izâ' mufâcee; D4 1P 3 · 3MS 3.\n◈A — A1 aktör 'insan' (tekil, cins); A4 itirazcı insan sahnesi açılıyor.",
 78: "◇ 'Bize bir misal getirdi, kendi yaratılışını unuttu: çürümüş kemikleri kim diriltecek?'. ضرب [2/2] kapanıyor: 36:13 'onlara misal getir' (elçiye emir) / 36:78 'bize misal getirdi' (insan) — misal getirenin yönü tersine (okuma gözlemi, KAPATILAMAZ). رمم [1/1] (sûre için eklenen kök), عظم [1/1], نسي [1/1], مثل [4/5], حيي [4/5], خلق [6/10]. 🜁 L0 — kemiklerin çürümesi adlanıyor (itirazın içinde), süreç yok; olgu evet, çıpa hayır.\n◈K — —\n◈B — B3 kemik (organ değil, doku) — çürümüş hâliyle; B4 dirim sorusu (kim diriltecek).\n◈D — D1 haber + alıntı içinde soru; D2 hâl cümlesi (ve hiye ramîm); D4 1P 1 · 3MS 5 · 3FS 1.\n◈A — A3 konuşan insan (alıntı), konu dirilme; A4 itiraz sahnesi sürüyor.",
 79: "◇ Cevap emri (qul, 2MS): 'onları ilk kez var eden diriltecek; O her yaratılmışı bilir'. حيي [5/5] kapanıyor: 36:12 ölüleri diriltiriz · 36:33 ölü yeri dirilttik · 36:70 diri olan · 36:78 kim diriltecek · 36:79 ilk kez var eden diriltecek. Esmâ: alîm — O'na dönen zamirin haberi → ilahi; evvel ('ilk kez', zaman) e_oto esmâ saydı → değil (36:70 hayy ile aynı tür ayrışma: ölçüm satırı evvel'i esmâ yazmıyor, esmâ kaydı yazıyor). §4.3 mühür EVET geçerli (alîm), ton denge; sınıf oto E → el E. نشأ [1/1], أول [1/1], مرر [1/1], كلل [5/6], خلق [7/10], علم [7/8].\n◈K — K2 zaman: 'evvele merra' — ilk kez / ikinci kez (diriltme) — tekrar yönü.\n◈B — B4 dirim yeniden veriliyor (ilk oluşum = dirilişin modeli).\n◈D — D1 emir (qul) + haber; D3 ilk inşâ / yeniden diriltme; D4 2MS 1 · 3MS 3 · 3FS 2.\n◈A — A3 elçiye söylenecek cevap; A4 itiraza cevap.",
 80: "◇ 'O ki size yeşil ağaçtan ateş çıkardı; bir de bakarsınız ondan yakıyorsunuz' — 'fe-izâ' sûrede altıncı. Hitap 2MP. جعل [5/5] kapanıyor. شجر [1/1], خضر [1/1], نور [1/1] (nâr — gloss 'nûr; nâr' ikisini taşıyor), وقد [1/1]. 🜁 L1 — madde (yeşil ağaç) → ürün (ateş) + kullanım; dönüşümün nasıl olduğu yok; olgu evet, çıpa hayır; tarayıcı vermedi.\n◈K — —\n◈B — B1 ağaç (yeşil — canlılık niteliği).\n◈D — D1 sıla (ellezî) + 'fe-izâ'; D2 zıtlık: yeşil / ateş; D4 2MP 4 · 3MS 2.\n◈A — —",
 81: "◇ 'Gökleri ve yeri yaratan, benzerlerini yaratmaya kadir değil mi? Evet (belâ)!' — kök ikilemesi خلق ×3 [8,9,10/10] kapanıyor. Kapanış: 'O, Hallâq'tır, Alîm'dir' — O'na dönen zamirin haberi: e_el 'ilahi' ×2; §4.3 mühür ÇİFT geçerli, ton denge. Aynı ayette altı iplik kapanıyor: خلق, سمو [2/2] (36:28 gök / 36:81 gökler), أرض [3/3], قدر [3/3] (36:38 takdîr · 36:39 qaddarnâ · 36:81 qâdir), مثل [5/5], علم [8/8]. ليس [1/1]. Blokun en uzun ayeti (14 kelime, tek). xref 17:99. 🜁 L0 — gökler ve yer adlanıyor (a fortiori delil), süreç yok; olgu evet, çıpa hayır.\n◈K — K1 gökler, yer; K3 ölçek: gökler-yer ↔ insan (misilleri) — büyükten küçüğe kıyas.\n◈B — B2 yaratma (خلق ×3) — insanın 'benzerini' yeniden yaratma.\n◈D — D1 olumsuz soru + 'belâ' cevabı; D2 mübalağa kalıbı (hallâq); D4 3MS 4 · 3MP 1.\n◈A — A3 soru-cevap aynı ayette (sorulan ve cevaplayan aynı ses).",
 82: "◇ 'O'nun emri, bir şeyi dilediğinde ona yalnızca Ol! demektir; o da olur'. Kök ikilemesi كون ×2 [14,15/15] kapanıyor (kun / yekûn). قول [20/20] kapanıyor. رود [2/2]: 36:23 'Rahmân bana bir zarar dilerse' / 36:82 'bir şeyi dilediğinde'. أمر [1/1], شيأ [9/10]. ALAN: 'innemâ' hasr edatı — biçim alanı HASR yazmıyor (36:11 'innemâ tunziru'da da yazmamıştı); alan arızası, metin hakkında kanıt değil (aday 924).\n◈K — —\n◈B — —\n◈D — D1 haber (innemâ — HASR, alan kaçırıyor) + alıntı içinde emir (kun); D3 كون: emir ve sonuç; D4 3MS 5 · 2MS 1 (kun'un muhatabı 'şey').\n◈A — —",
 83: "◇ Sûre kapanışı: 'her şeyin hükümranlığı elinde olan tenzih edilir; O'na döndürüleceksiniz'. 'Subhâne'llezî' 36:36'daki açılışla aynı: سبح [3/3] kapanıyor (36:36 subhân · 36:40 yesbehûn · 36:83 subhân). 've ileyhi turja'ûn' 36:22'de adamın sözünün sonuydu — sûrenin son üç kelimesi (metin sayımı; nakarat3 yakalamıyor). رجع [5/5] kapanıyor (36:22 · 31 · 50 · 67 · 83). يدي [6/6] kapanıyor: 'bi-yedihî' — el ipliğinin son tokeni O'nun eli. ملك [2/2]: 36:71 insanlar davarlara 'mâlik' / 36:83 her şeyin 'melekût'u O'nun (okuma gözlemi, KAPATILAMAZ). كلل [6/6], شيأ [10/10] kapanıyor. ★★★ tek kaynak pas z=5,38 (tek fiil edilgen, 8 kelime) — edilgen kaynaklı ★★★ (aday 1009 ailesi; 36:45 ile sûrede ikinci). xref 23:88.\n◈K — —\n◈B — —\n◈D — D1 tenzih kalıbı (subhâne + sıla) + haber; D2 edilgen (turja'ûn, döndüren adlanmıyor); D4 3MS 2 · 2MP 2.\n◈A — A4 sûrenin anlatı ve hitabı burada kapanıyor.",
}
MEAL.update(MEAL8); M.update(M8)
