# -*- coding: utf-8 -*-
# Claude-üretimi kök adları, parti 2
ADLAR = {
"فأد":"kalp/fuâd","لهو":"eğlence/oyalanma","كيل":"ölçek/ölçme","خبث":"pislik/habislik","حبط":"boşa gitme/hübût-u amel",
"صمم":"sağırlık","شكك":"şüphe/şekk","حرج":"darlık/sıkıntı","بدأ":"başlama/ilk yaratma","ثوي":"barınak/kalma yeri",
"وصف":"niteleme/vasıf","عطو":"verme/atâ","صفف":"saf/dizilme","لوم":"kınama/levm","زرع":"ekin/ekme",
"رسو":"sabit dağlar/demirleme","رجم":"taşlama/kovulmuş (racîm)","حرث":"ekin/tarla","صيح":"çığlık/sayha","ضيق":"darlık/daralma",
"يأس":"ümitsizlik","شهو":"arzu/şehvet","نجم":"yıldız","حلف":"yemin etme","فدي":"fidye/kurtulmalık",
"ركع":"rükû","طمأن":"huzur bulma/itmi'nân","غلظ":"katılık/sertlik","أبي":"diretme/kabul etmeme","رأف":"şefkat/raûf",
"فوه":"ağız","قنت":"gönülden itaat/kunût","غلم":"oğlan/genç","وقت":"vakit/mîkât","بغت":"ansızın/bağteten",
"نصح":"öğüt/samimiyet","خرر":"yere kapanma","طين":"çamur/balçık","خوض":"dalma/boş söze dalma","عسر":"zorluk/güçlük",
"عذر":"mazeret/özür","نيل":"erişme/nail olma","نطق":"konuşma/nutk","شقو":"bedbahtlık/şakîlik","طمع":"umma/tamah",
"شبه":"benzeşme/müteşâbih","لحم":"et","حنف":"hanîf/dosdoğru yönelen","جحد":"bile bile inkâr","سلك":"sokma/yol tutma",
"عصو":"asa/değnek","نطف":"nutfe/damla","بخل":"cimrilik","سفه":"akılsızlık/sefihlik","طبع":"mühürleme/tab",
"عنب":"üzüm","طرف":"göz ucu/bakış","غيظ":"öfke/kin","حصي":"sayma/kuşatıcı bilme","فرر":"kaçma/firar",
"وقد":"tutuşturma/yakma","وكأ":"yaslanma","رضع":"emzirme","لغو":"boş söz/lağv","صعق":"yıldırım/çarpılma",
"فأي":"topluluk/fırka","رجس":"pislik/rics","زلف":"yaklaştırma/zülfâ","زيل":"ayrılma/zeval bulma","ملو":"mühlet verme/süre tanıma",
"عزل":"ayrılma/uzlet","مأي":"yüz (sayı)","سفل":"aşağı/alçak","دفع":"savma/itme","حيق":"kuşatıp çarpma",
"دمو":"kan","جبر":"zorbalık/cebbâr","رعي":"gözetme/çobanlık","عتو":"azgınlık/haddini aşma","دمر":"yerle bir etme/tedmîr",
"بطش":"şiddetle yakalama","ضيع":"zayi etme/boşa çıkarma","رهق":"bürüme/zorlama","نقص":"eksiltme","قهر":"kahır/ezici güç",
"ضحك":"gülme","رجز":"azap/pislik (ricz)","قدس":"kutsallık/takdîs","دوم":"süreklilik/devam","نوم":"uyku",
"همم":"yeltenme/kastetme","حلي":"süs/takı","عنق":"boyun","فيض":"taşma/akın etme","بقر":"sığır/inek",
"زيغ":"kayma/eğrilme","زني":"zina","برز":"ortaya çıkma","عوم":"yıl","كنز":"hazine/biriktirme",
"وهن":"gevşeme/zayıflık","سرق":"hırsızlık","تجر":"ticaret","عوج":"eğrilik","عكف":"kapanma/itikâf",
"حرق":"yakma/yangın","رمي":"atma/iftira atma","قذف":"fırlatma/atma","لون":"renk","قبض":"tutma/kabz",
"ذبح":"boğazlama/kurban kesme","عزم":"kararlılık/azim","لطف":"incelik/latîf","حجب":"perde/hicâb","أون":"şimdi/an",
"ختم":"mühürleme/hatm","كلف":"yükümlü kılma/teklif","ستت":"altı","سقط":"düşme","خسف":"yere batırma",
"صوت":"ses","صفح":"hoşgörüp geçme/safh","هبط":"inme/hübût","سلف":"geçmiş/öncekiler","قبر":"kabir",
"خمس":"beş","عيش":"geçim/yaşayış","رغب":"rağbet/isteme","دلل":"yol gösterme/delâlet","خضر":"yeşil",
"ترف":"refah şımarıklığı/mütref","برهن":"burhan/kesin delil","ندم":"pişmanlık","حظظ":"pay/nasip","موج":"dalga",
"تسع":"dokuz","دكك":"dümdüz etme/dekk","حبل":"ip/bağ","ضحو":"kuşluk","زيت":"zeytin",
"نسك":"ibadet/mensek","بكي":"ağlama","عقد":"düğüm/bağıt","سرح":"salıverme/güzelce bırakma","خطف":"kapıp alma",
"بعل":"koca/Ba'l putu","نوق":"dişi deve/nâka","مكث":"bekleme/kalma","نكث":"bozma/ahdi çözme","بخس":"eksik verme",
"خمر":"içki/örtü","عمه":"şaşkın bocalama","قسو":"katılaşma/kasvet","علق":"alak/asılı pıhtı","نصف":"yarım",
"مقت":"nefret/gazapla kınama","ضوأ":"aydınlatma/ışık","زلزل":"sarsıntı/zelzele","قنط":"ümit kesme","تبر":"yıkıp yok etme/tedbîr",
"ميل":"meyletme/eğilme","درس":"okuyup öğrenme/ders","رصد":"gözetleme","صيد":"av","نزغ":"dürtme/vesvese sokma",
"قمص":"gömlek","أدي":"ödeme/yerine verme","كلب":"köpek","فزع":"dehşet/korkuya kapılma","لؤلؤ":"inci",
"لحق":"katma/yetişme","حطم":"kırıp dökme/enkaz","كأس":"kadeh","بكم":"dilsizlik","غرم":"borç yükü/ödeme",
"ثقف":"ele geçirme/yakalama","زجر":"haykırışla sürme/zecr","كرر":"dönüş/tekrar","كهف":"mağara","كظم":"öfke yutma/kezm",
"شفي":"şifa","فرغ":"boşaltma/dökme","ندد":"denk koşulan/eşler","قصد":"orta yol/kasıt","ذرأ":"türetip yayma",
"ضيف":"misafir","حصد":"biçme/hasat","ردي":"helâke düşürme","دأب":"âdet/süregelen hal","سنبل":"başak",
"طمس":"silme/köreltme","قصو":"uzak/en uç","جثم":"yüzüstü çöküp kalma","شحح":"aşırı cimrilik","مضي":"geçip gitme",
"كسو":"giydirme","فرد":"tek/yalnız","رعب":"korku salma","أرك":"koltuk/taht (erîke)","قرف":"işleme/kazanma (günah)",
"بلس":"ümitsizce susma/iblâs","ثور":"sürüp kabartma","كمل":"tamamlama/kemâl","صفر":"sararma","حوت":"balık",
"وجل":"ürperme/titreme","كوكب":"gezegen/yıldız","عثو":"bozgunculukta azma","جوز":"geçme/aşma","قرع":"çarpan/kāria",
"مصر":"Mısır","ربط":"bağlama/pekiştirme","لوي":"eğip bükme","شهب":"alev topu/şihâb","لمس":"dokunma/arama",
"نسف":"savurup dağıtma","سبط":"torunlar/kollar (esbât)","بور":"yokluk/helâk","حرص":"hırs/düşkünlük","شرح":"açma/genişletme",
"وسط":"orta","خطو":"adım","أسف":"üzüntü/esef","خنزر":"domuz","جوع":"açlık",
"زهق":"yok olup gitme","عتب":"özür dileme/hoşnut etme","خرص":"saçma tahmin/yalan atma","سدس":"altıda bir","حسد":"haset",
"نفد":"tükenme","بغض":"buğz/nefret","صنم":"put","خوي":"bomboş çökme","نقذ":"kurtarma",
"غوث":"yardım isteme/istiğâse","خدع":"aldatma","هزز":"silkeleme/titretme","ثبر":"helâk çığlığı/sübûr","صبب":"dökme",
"وسوس":"vesvese","صرخ":"feryat/imdat","فوج":"bölük/dalga dalga","درأ":"savma/giderme","قفو":"ardınca gönderme/izleme",
"خيب":"boşa çıkma/hüsran","عمم":"hala","طرد":"kovma","شتت":"darmadağın/çeşit çeşit","شطر":"yön/taraf",
"كسف":"parça (gökten düşen)","حيص":"kaçacak yer","لزم":"gerekli kılma/yapışma",
}
